### ISSUE TITLE
Get cheap older copy of Corel for large cutter PC ?

### ISSUE THREAD

**Issue by osfameron** [DoESLiverpool/somebody-should#100]
Obviously we don't want to spend £100s on latest Corel draw suite, but we can get a cheaper version?

   http://www.amazon.co.uk/Corel-Draw-Select-Edition/dp/B000ASAVM4/  (really cut down version -- will it have the DXF capabilities we need?)

Otherwise the Home/Student suite might be in our budget (~£50) or there are various baffling options via Ebay.

(And have we asked our Autodesk friends about their graphics software?  as that comes up as a related item on Amazon search...)

**Comment by amcewen** [comment]
@DefProc says the ideal version is X4 (although that's well out of date - so matches the age of the laser-cutter software :-)

If we can find a download of X4, we could try transferring the licence from the Vinyl Cutter laptop

**Comment by DefProc** [comment]
I just tried to get a copy for £40 on ebay, but the seller's paypal account can't accept payments atm. I'll see what we get back from my question.

**Comment by amcewen** [comment]
I see in issue #356 that @ajlennon has found the installer files for X4, so I reckon we should transfer the licence for X4 from the vinyl-cutter laptop across to Gerald, and maybe not bother with Corel on the vinyl-cutter PC, as that doesn't have the same "get it into DXF" issue that the laser-cutters do.

**Comment by ajlennon** [comment]
X4 should be working on Gerald-PC ?

**Comment by amcewen** [comment]
Seems to be working fine, thanks @ajlennon.  I made a note of the licence key for X3 that's on the old vinyl cutter laptop too, see https://www.flickr.com/photos/amcewen/32347949086/in/dateposted/
