### ISSUE TITLE
Ikea Shopping List

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1004]
There have been numerous conversations about some fancy touches to make the place nicer, and they tend to come down to doing an Ikea trip at some point, so it makes sense to have a place to keep track of anything we might want to get from there. Please add any ideas to the list - if possible with the right name or even a URL

- [x] FULLEN - mirror with shelf - 601.890.27 -https://www.ikea.com/gb/en/products/decoration/bathroom-mirrors/fullen-mirror-with-shelf-art-60189027/
- [x] 2 x Toilet roll holders - 003.285.40 - https://www.ikea.com/gb/en/products/small-storage-organisers/bathroom-accessories/brogrund-toilet-roll-holder-stainless-steel-art-00328540/
- [x] Drawing paper rolls x 3 - 803.240.72 - https://www.ikea.com/gb/en/products/childrens-ikea-products/children-3-7/toys-play/måla-drawing-paper-roll-art-80324072/

**Comment by johnmckerrell** [comment]
Added mirror & toilet roll holders

**Comment by DoESsean** [comment]
Is there a reason those toilet roll holders are better than the ones we have? Not an antagonistic question, by the way, just making sure we're not doubling up on stuff we already have.

**Comment by johnmckerrell** [comment]
If they were hanging on the wall I think it would no longer have the issue where they get blown by the hand dryer. I think also people find the existing ones too low down, so the existing ones could hold the spares but you’d have one on the wall for the “active” roll.

**Comment by amcewen** [comment]
Is there a reason why we're not sourcing wall art from within the community?  Are there any particular walls that we'd like adorning?

**Comment by ajlennon** [comment]
That sounds a great plan @amcewen. I like the places where they have art by local artists up, and especially when you can buy the art to support them. Perhaps with a commission to support DoES?

**Comment by DoESsean** [comment]
No problem with that at all, and I'd actually prefer it - I had a discussion with... someone, at some point, about finding out if we could make DoES almost like a gallery, with rotating art works by local artists every three months or so, similar to how some cafes do.

The Ikea art discussion had come about as @johnmckerrell was talking about some brilliant MASSIVE posters they do which might be suitable for the big white wall in Room 29, something like a huge world map or similar.

**Comment by jackie1050** [comment]
I go past IKEA on my way home from work every day and would normally be happy to pick stuff up if you give me the catalogue numbers.

Also I feel hesitant to add to visual clutter with "wall art" and plants. If we did want anything (perhaps in Room 29?), it feels that it might be more thoughtful (and fun) to make it ourselves, or commission something from community members or local businesses.

On 13 Dec 2018 14:43, John McKerrell <notifications@github.com> wrote:
If they were hanging on the wall I think it would no longer have the issue where they get blown by the hand dryer. I think also people find the existing ones too low down, so the existing ones could hold the spares but you’d have one on the wall for the “active” roll.

**Comment by jackie1050** [comment]
Obvs hadn't received all replies when I posted mine.
________________________________

**Comment by johnmckerrell** [comment]
Without wanting to pile on the "wall art" thing but I do recall saying the Ikea do a good big world map which might be a nice addition, perhaps that's where this came from.

**Comment by amcewen** [comment]
It makes more sense as a specific "maybe we should get X for space Y" rather than a general "buy some wall art".  

In issue #650, I've just noticed, @johnmckerrell did mention getting http://www.ikea.com/gb/en/products/decoration/frames-pictures/bj%C3%B6rksta-picture-planet-earth-art-80329121/ (although looking at that, it'll only cover about a third of the width of the big white wall in Room 29, so is it big enough?)

**Comment by jackie1050** [comment]
If the map's a bit small, perhaps it might look good and take up more space with something like those clocks that display times in different locations, but with more interesting data.

Or is there a way to project something onto the wall from right next to it?
________________________________

**Comment by ajlennon** [comment]
On 14/12/2018 13:39, Jackie Pease wrote:
> If the map's a bit small, perhaps it might look good and take up more 
> space with something like those clocks that display times in different 
> locations, but with more interesting data.
>

QR code flags linking to our twinned makespaces around the world?

A/

**Comment by johnmckerrell** [comment]
@jackie1050 no rush but there's three specific items in the shopping list if you'd like to pop into Ikea sometime.

**Comment by jackie1050** [comment]
Will do
________________________________

**Comment by DoESsean** [comment]
This can be reopened if we need more stuff from Ikea, in the way the Costco list is. However, for now it can be closed.
