### ISSUE TITLE
New Poster Frames

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1005]
I'm going to be putting up the A3 frames once I have access to the drill.

We'll need some signage to fill them, and, as I'm somewhat worthless when it comes to graphic design stuff, I'm hoping that someone (possibly @zarino as he's awesome at it, although I don't want to put too much on any one person's plate) will be able to help with knocking together some fairly standard templates to go alongside the more bespoke ones we'll need on an irregular basis.

On an initial basis, I'm after:

- [ ] Payment reminder for the workshop (Happy to work on the wording for that)
- [ ] Monthly Events Calendar
- [ ] Price List

If possible to get them done super quickly (it's probably not), it would be good to have:
- [ ] Christmas Party
- [ ] Mince Pie Tasting

**Comment by johnmckerrell** [comment]
I would say payment reminder and price list would be the same thing most likely?

**Comment by DoESsean** [comment]
The frames are up in the toilets, I'm going to put the rest up Saturday
before the party - I'd sort of forgotten how loud drilling is, especially
when people are working.

**Comment by ajlennon** [comment]
>I would say payment reminder and price list would be the same thing most likely?

Mashing up recent conversations, we could take a lesson from the Chinese "good citizen" moves and put an EL Wire display up that flashes "Polite reminder: You have a payment outstanding" when fobs-in-debt enter the building.

Or perhaps not... ;) Which reminds me I have an invoice to pay...

**Comment by DoESsean** [comment]
>  Or perhaps not... ;) Which reminds me I have an invoice to pay...

The system works! :)

@johnmckerrell Not quite the same, for me.  

Price list would be general info for anyone coming in the space. Payment reminder would be along the lines of 'remember to ask for an invoice or, if you've paid in the jar, note it on the handy sheet' (which we will also probably have).

**Comment by johnmckerrell** [comment]
Happy to consider both but I’d imagined something like:

PRICES 

DoES Liverpool costs £4000 per month to keep running. We really appreciate your contribution! Remember to ask for an invoice or, if you've paid in the jar, note it on the handy sheet. 

(List or actual prices)

--
