### ISSUE TITLE
Dishwasher isn't washing dishes...

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1007]
The dishwasher currently seems to not run a program, which isn't very useful...

**Comment by amcewen** [comment]
@jackie1050 and I prodded it a bit, cleaned the filter, and it was still reporting an aquastop error.  @jackie1050 found some details online that suggested tipping the dishwasher back up to 45 degrees to clear a flood.  That dumps the water flooding it out onto the floor, so you need to be ready to catch it with some towels or similar (and we only tipped it back ~15 degrees).

It *seems* happier now, we've left it running a programme to see how it gets on...

**Comment by jackie1050** [comment]
I checked on the dishwasher before I left yesterday. There were no lights on, and there was water in the bottom as if it should still be running. I switched it off and on again and it carried on with its program, but I didn't stay to see if it finished. 
We should probably try to drain more water from the base.

**Comment by jackie1050** [comment]
Dishwasher seems to have been working correctly for a while now
