### ISSUE TITLE
Put signage on dangerous equipment as a temporary measure

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1008]
As a temporary measure we want to put signs on the equipment to indicate that it should not be used when you are in the space on your own. This would include:
 - [ ] Routers (CNC and non)
 - [ ] Bandsaws
 - [ ] Pillar Drill

This would be covered later through general out of hours induction procedures.

**Comment by jackie1050** [comment]
I have printed labels and stuck them to the above machines. If there is anything else that people believe to be a risk then please reopen the issue.
