### ISSUE TITLE
We should run a "Hack the Space" event focussed on the software used to run the space

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#101]
We should have a software hack day during which we try to improve the software we use for the space, so upgrading the doorbot software to be centralised, have a customer management portal, that sort of thing.

**Comment by DoESsean** [comment]
I've put a post in the Google Group to gauge interest in this, with a view to being able to set up a day/evening to get it done.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
