### ISSUE TITLE
Gerald currently unable to engrave properly, head/lens was left un-assembled upon discovery.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1010]
The power on Gerald is massively reduced at the moment.

Darren discovered the lens/head had been disassembled and left that way in the room this afternoon, with some pieces of it having fell through the bed and onto the scrap materials beneath. He put the assembly back together and had it functioning pretty well, however upon my attempt to engrave some acrylic, the result was lacking massively in terms of power. What usually takes only 20 power now takes 70 and the results are still flaky and inconsistent. It also won't cut through material.

Removing the air assist has not fully fixed or alleviated the issue, but it is cutting slightly more powerfully.

**Comment by MatthewCroughan** [comment]
On another topic, does anybody have some acrylic? Someone needed some yesterday, so I gave them some, and now that Gerald has had its way with the piece I had left, I have none to make some orders for Etsy. I've asked material world, and I'm sure they'll come through, but in the case that they don't it'd be good to have a backup.

**Comment by magman2112** [comment]
Closing this issue, as I suspect it is related to #1003 and this issue may already have been addressed.
