### ISSUE TITLE
Get the 3D sense scanner working

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1011]
I think it's this,  https://www.3dsystems.com/shop/sense and there's evidence that @MatthewCroughan has tried to get it going on the CNC computer, though there seems to be an error.  (As there is no issue for it, there's no record for how far he's got.)

**Comment by ajlennon** [comment]
The drivers for it weren't installed on the PC it is attached to.

I've installed the drivers, ran up the application and it needs an authentication code.

The 3D systems site says the authentication code is already registered to another user so I'll email them to try to get the code.

Unless somebody else has already been through this loop?

**Comment by ajlennon** [comment]
Been in touch with Andy. He's registered with the 3D Systems site but the site isn't working correctly. Howver we do have the needed code for the serial number of the device. This worked ok on the CNC PC and hopefully will work on other systems...

```
Congratulations! You have successfully registered your Sense 3D scanner.

Your Sense 3D scanner serial number is 1401030136

To activate your Sense 3D scanner use activation key 5839
```

**Comment by ajlennon** [comment]
Closing for now...

**Comment by se3d** [comment]
Hi, I have one too and the cubify site is not working.

My serial Number is 1405200651

Can you help me?

**Comment by bolsoncerrado** [comment]
I'm curious as well to learn where the 4 digit code is stored or how can I activate the 3d sense scanner without the website which no longer exists...

**Comment by peqpez** [comment]
Me too:
> I'm curious as well to learn where the 4 digit code is stored or how can I activate the 3d sense scanner without the website which no longer exists...

**Comment by SulLa0** [comment]
> Мне также интересно узнать, где хранится 4-значный код или как я могу активировать сканер 3d sense без веб-сайта, который больше не существует...

пни меня если найдешь, та же фигня

**Comment by forum-user-77** [comment]
Is there a solution to this issue? I'm also experiencing this problem!

**Comment by clodICL** [comment]
hey guys I am also struggling with this issue as I cant get the 4-digit code. 

Can anyone help? thanks!

**Comment by ajlennon** [comment]
Doesn't 5839 work ?

**Comment by peqpez** [comment]
If you have the device's serial number you can ask the company about the activation code.
I sent a request at the support of 3D Systems and, although they do not support the product anymore, they sent me the device's activation code, about a month later.
Good luck!

**Comment by clodICL** [comment]
Hey!

Yes I wanted to let people know I have contacted them through the support and they still provide the activation code for whoever needs it. That is a relief!

Thanks for replying to my query!

**Comment by forum-user-77** [comment]
But how did you contact with them and get the code? Because they said me that my issue would be repaireid and I've been waiting for 2 weeks with no response.

**Comment by clodICL** [comment]
yes I contact them through the customer support link but I only needed the activation code. they told me that that is the only service they still provide. so I guess if you don't need that but something else they will not be able to help you.

**Comment by TheWerewolf** [comment]
They've started charging $130 per request.

I have the algorithm for generating the codes though...

**Comment by kenshyura** [comment]
For those who wants to try to activate, here's the link for the manual from the official site of 3dsystems where you can find the offline link (not so "offline" really) to create a support ticket:
https://s3.amazonaws.com/dl.3dsystems.com/binaries/support/sense-scanner/Sense2_UserGuide_031519.pdf
To create the ticket: https://www.3dsystems.com/shop/sense/activate
I'm in the process of activating my Sense 2 3D scanner, so I'll let you know if it works.

**Comment by TheWerewolf** [comment]
Try "3466" on any Sense scanner using the most recent software. 
It should work.

**Comment by kenshyura** [comment]
@TheWerewolf, thank you very much for your reply, apparently it works great, I could activate the software. Now gotta speed up my computer because it's scan a little bit slow.

**Comment by kenshyura** [comment]
Final results about the 3D Systems techsupport: After few weeks waiting: Unless you pay nowadays USD 129, the won't give you for free the code. They were give for free until july 2023 but not anymore. 
More info: https://support.3dsystems.com/s/article/Activation-Code-for-EOSL-Products-Notification-and-FAQs?language=en_US
Thanks again @TheWerewolf

**Comment by arthurvangeersdaele** [comment]
> Try "3466" on any Sense scanner using the most recent software. It should work.

My god it worked

**Comment by ajlennon** [comment]
> > Try "3466" on any Sense scanner using the most recent software. It should work.
> 
> My god it worked

Of course it worked!

**Comment by Disaqx** [comment]
> Try "3466" on any Sense scanner using the most recent software. It should work.

Bro I've been looking for answers everywere for 2 days. You are the best. Im using the sofware for Sense V2 on the Sense V1 and it works perfectly. Ty man you saved me a lot.
