### ISSUE TITLE
Direct robotchallenge.doesliverpool A and AAAA records to my server to host forum.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1013]
This was requested by @Sean-anotherone so we can host a forum for the robotwars. Not revealing the IP here in case it gets scraped by bots, everything will be going through cloudflare as to obscure it anyway.

**Comment by amcewen** [comment]
Records set up.  I'll let you leave it a while and then confirm that they're resolving okay and close the issue.

**Comment by Sean-anotherone** [comment]
robotwars. is returning a 503 today.

Probably an idea to change it to robochallenge at the same time as investigating ?

**Comment by MatthewCroughan** [comment]
@Sean-anotherone Server migration, short downtime. Moved everything to hetzner, 1gbps and cheaper, multiple ips and hosting what was once two servers in a single machine now via lxc containers.

**Comment by MatthewCroughan** [comment]
@amcewen @johnmckerrell 

Today @Sean-anotherone asked me if I could put this up again in order to show the work that was done off to someone. Is it possible you could update the A record for this to point to `185.135.107.83` (my IP at does)? where I will host that for him? 

#1187 decided that we would use the domain `robochallenge.doesliverpool.com` instead of `robotwars.doesliverpool.com`

**Comment by Sean-anotherone** [comment]
I asked for this, quite lucky that Matt still had the posts backed up.

It's to allow Dave (the kit donation Dave) to take a look at the BOM and structure for the robot challenge that never got off the ground - he is involved in some similar groups.

**Comment by amcewen** [comment]
I've done the A records (for both robotwars and robochallenge).  I've removed the AAAA records (for now) because I don't know what your IPv6 address is (they were set to `2a01:4f9:2b:16d5::1`), and figured that was better than leaving them there pointing at a stale address.

I can add them back in if needed, if you tell me the address to use.

**Comment by MatthewCroughan** [comment]
Restored for the time being. https://robochallenge.doesliverpool.com/
