### ISSUE TITLE
Install sensor to record the whole electricity usage in the space

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1015]
Apparently the electricity bills for the heating are costing more than we're spending on 3D printer filament.  

Why do we know the cost of filament per metre, but not the cost of the heating box running per minute?  

What is the cost of the laser cutter per minute, given that we can monitory it in realtime?  Power varies by 3x so etching is not as energy intensive as cutting.  

Where is the electricity meter?  We could get a rough calibration of the cost of each of our systems (lighting, heating, laser power, pot of coffee, baseline) by running each of these individually for a set time out of hours and recording the difference.  The numbers should correspond somewhat to the ratings on the devices.  

From the unit costs, the secondary effect costs are the time it takes to raise the temperature by 1degree.  This could feed through to a rule that the heating can be put on only when there are N people in the room out of hours; or you've got to pay for it like you would pay for a packet of crisps.  

For comfort, we should make available N-1 heated waistcoats:
    https://www.primrose.co.uk/heated-gilets-jackets-c-37_753.html

None of this is high tech (like OCR of power meter).  Just very simple accountancy and curiosity.

**Comment by amcewen** [comment]
Our meter (for *all* of our usage) is downstairs... looks like this:

![Main electricity meter](https://user-images.githubusercontent.com/108468/56742119-10f2fe80-676c-11e9-929c-1c20b1d48d44.JPG)

**Comment by goatchurchprime** [comment]
There's a red flashing LED that flashes 10 times for every 0.001 that shows on the LCD screen.

There are arduino pulse counter things projects that watch for these flashes.
    http://www.reuk.co.uk/wordpress/solar/flashing-led-on-electricity-meter/

If we had to do it, we could plug in an ESP32 powered from the handy mains socket just below it and stuck on with a bit of double-sided foam tape and possibly pick up an MQTT signal count for every pulse in real time.  

> topic=alldoespower 
> message=[microseconds since last pulse] [pulse count modulo 1000]

The meter in the picture should be one of the ones on this page, but I can't find it exactly:
https://www.landisgyr.com/devices/?product-cat=334&product-region=678&product-country=8&keyword=#filter

Many of the options have communications built in, so it should potentially be done through its own interface somewhere.  (In my dreams it's got a built-in hotspot that allows us to login and point it to the MQTT server.)

**Comment by ajlennon** [comment]
I did something very similar to monitor the gas meter in my old house.

**Comment by ajlennon** [comment]
We could add something to Espurna easily enough I suspect

**Comment by goatchurchprime** [comment]
The ESP32 device with the light sensor is programmed and ready to be installed.  It's been tested outside the door and the wifi reaches it.  

![photometer](https://user-images.githubusercontent.com/677254/58351126-cbefe400-7e5f-11e9-9407-98cbe3f5144c.jpg)

The code installed on it is here:

https://github.com/goatchurchprime/jupyter_micropython_developer_notebooks/blob/master/projects/electricity_meter_flashes_to_mqtt.ipynb

The command to see what it reads is:
`mosquitto_sub -v -h mqtt.local -t "esp32powflash/#"`

The message is composed of 3 numbers separated by spaces: 
 [number of milliseconds since last flash] [duration is flash milliseconds] [flash counter]

**Comment by goatchurchprime** [comment]
It's now installed and working.  It took a while to debug because the duration of the flash is 24 milliseconds, and I was filtering out any spike that was less than 50ms.  

The payload format is "[flash period (ms)] [flash duration (ms)] [sequence number]", so `esp32powflash/ticks 862 24 8506` is equivalent to 3600/862=4.17kW, because there are 1000 flashes per kWh.

**Comment by ajlennon** [comment]
Brilliant!

**Comment by ajlennon** [comment]
What do we need to do to turn this into the metric scale? Should we handle conversion in the node-red flow?

**Comment by goatchurchprime** [comment]
The data is conversion is available two ways.  

There is one record added to the database per flash.  

The nodered converts the milliseconds-since-last-flash to kiloWatts by the formula `3600 / msflashtime` and stores it in the database.  

The count of the number of records in the database within a set duration (eg from midnight until now()) equals the number of flashes.  Divide this number by 1000 and you get the total kWhrs used for the day.  Cost is then 15p times this number.

**Comment by goatchurchprime** [comment]
It stopped working at 7am this morning.  I don't know why.  

Maybe the code is too simple and it's not catching the exception that can be thrown in from client.publish().  

Also, it will probably fail to reconnect if either the router or the mqtt-broker reboots.  Maybe I need to base this code on the mqtt_as (asynchronous version) which would look after all that sort of stuff.

**Comment by ajlennon** [comment]
I meant to suggest to you that we should enable webrepl (unless there's a better way) so we can do remote updates to it in case things break...

**Comment by ajlennon** [comment]
We should also look at what watchdog capability there is to reset it if/when things bugger up

**Comment by goatchurchprime** [comment]
Fixed up.  Turns out that the device fell off and ripped out its wires.  A sticky on the side of the box isn't good enough in such a warm environment, so I've made longer wires for the LDR and placed it on the top of the meter so it is no longer defying gravity.

**Comment by goatchurchprime** [comment]
The power monitor seems to have fallen offline at around 10pm last night, according to the graph.  
Nothing showing up on the MQTT:
    `mosquitto_sub -v -h mqtt.local -t "esp32powflash/#"`

Need to get into the room to find out what's happened (has it been unplugged or something)?  It won't have fallen off this time.  

It would be useful to find out its ip-number so we can ping it.  I don't know if it's possible to reboot it remotely when it's crashed.  There might be some webrepl service now on ESP32s that could be used to probe what's going on.

**Comment by ajlennon** [comment]
Webrepl?

**Comment by johnmckerrell** [comment]
I can try finding out its ip address but it would help if you know anything to describe it, MAC address or if it has a self-assigned hostname. I’d be happy to fix the IP addresses of all the MQTT monitors (although now I think about it, are they actually running off the standard DoES Wi-Fi?)

**Comment by johnmckerrell** [comment]
I've mentioned this to Jason, he's in tomorrow and will let me or Julian into the room to take a look.

**Comment by goatchurchprime** [comment]
I've got the webrepl on the IR sensor in Room29, and it also puts its IP number on the mqtt gateway, so we can look it up.  

Webrepl is a websocket that gives access to the command line, so we can connect to it, find out what the exception is, as well as restart it -- all as if we had a serial connection to it.  

(It came as default in ESP8266s, accounting for their amazing bootstrapping abilities, due to a hack that was possible in its version of the TCP libraries.)

**Comment by johnmckerrell** [comment]
This seems to be down at the moment. It's been up and down a few times since the last update I think. Any update on what's going on with it? We're likely to need the air con on soon and it would be nice to monitor it. I can gain access to the room this morning so if it's a simple power cycle let me know.

**Comment by johnmckerrell** [comment]
I did power cycle it, not seeing any updates yet but I'll check again later. We have access to the key so can do more if necessary.

**Comment by ajlennon** [comment]
I think one problem was the LDR sensor had dropped off in the past

**Comment by johnmckerrell** [comment]
Still not seeing anything, checked again and I can see some lights on the breadboard and the sensor seems to be in the right place (as far as I can tell) so not sure what the problem is.

Just an FYI but Jason might be interested on doing this for the building, at least for 24 hours, as part of an investigation into getting solar installed on the building.

**Comment by goatchurchprime** [comment]
It's back up.  Turns out that the mDNS component of the mqtt.local machine fails after a while.  It started working again once I power cycled it.  

The code on the power device is very simple and probably can't come up from a hiccup in the service.  It's not using the asynchronous mqtt library like a lot of the other devices.  

This is another service that needs monitoring for the internal logging watchdog system on the Rpi to find out why or how it fails.   

I've updated the current state of knowledge here
https://github.com/DoESLiverpool/somebody-should/wiki/ESP-devices

**Comment by ajlennon** [comment]
This went down again a few days ago. @johnmckerrell power cycled it and it came back up straight away.

**Comment by ajlennon** [comment]
@goatchurchprime the wiki notes say the power meter is running this code.

https://github.com/goatchurchprime/jupyter_micropython_developer_notebooks/blob/master/Sensor_Kennel/esp8266_MQTT_Main.py.ipynb

Is this correct as I can't see how the "ticks" values are being generated here?

**Comment by goatchurchprime** [comment]
It's this code, I think:

https://github.com/goatchurchprime/jupyter_micropython_developer_notebooks/blob/master/projects/electricity_meter_flashes_to_mqtt.ipynb

I have updated in the wiki.

The active loop in the code is just doing this:

```python
n, t0 = 0, 0
while True:
    x = machine.time_pulse_us(pdetector, 0, 10000000)//1000
    t = time.ticks_ms()
    dt = t - t0
    client.publish(topicname, "%d %d %d" % (dt, x, n))
    t0 = t
    n += 1
    pled.value(n%2) 


```
