### ISSUE TITLE
Run a 35C3 satellite conference in DoESLiverpool

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1016]
Alex just tried (and failed) to get tickets for this, which happens between Xmas and new year:
    https://events.ccc.de/2018/09/11/35c3-call-for-participation-and-submission-guidelines/

Normally you go to these and then hang out with the folks from your area you find there.  

They do a lot of livestreaming. https://media.ccc.de/

We could set it up and in the events room streaming the main stage, if there's any days where the schedule looks good, and put it out on twitter that we're watching and its open, so as to get any other folks in Liverpool who may be watching and would have wanted to go.

**Comment by ajlennon** [comment]
+1

**Comment by goatchurchprime** [comment]
We're missing lots of them  https://media.ccc.de/c/35c3

**Comment by goatchurchprime** [comment]
We're missing lots of them  https://media.ccc.de/c/35c3
