### ISSUE TITLE
Shopping Label in Github

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1019]
This might seem a weird thing to do, but it seems like the best way to reach all the github users!

It's regularly confusing to figure out what actually needs buying among the conversations about laser cutter repairs, drill bits and everything else that gets discussed in here, which can lead to delays in getting stuff. I was going to start a shopping list issue where anything that was decided upon could be listed and ticked off as it was bought, but thought that might be a bit pointless, as it would just be a duplication of effort.

However, @amcewen pointed out that there is already a Shopping label which doesn't see a huge amount of use. So, if you can remember, please add this label to any issue that has something in it which needs purchasing once the decision on what to actually buy has been made, and it can be sorted out and the label removed. Hopefully this should help keep things tidy, and ensure that nothing gets missed.

**Comment by amcewen** [comment]
Presumably everyone will know about the `shopping` label now, so I'm closing this...
