### ISSUE TITLE
Fix and reassemble the big table from Gostins

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1020]
As part of #961 we want to install the big table that used to be in the main room at Gostins into Dinky.

However, part of it got damaged in the move, so we need to fix it up and then reassemble it in Dinky.  Ideally we'd get this sorted in the next week or two.

@magman2112 do you know what needs doing to fix it?

**Comment by magman2112** [comment]
The splines that join the large pieces of wood to make a single piece have broken at one end of the table base. The broken splines (strips of wood fitted into a mortice to make a joint) need to be removed, probably using a router, then new splines need to be glued in to replace them.

As you may have guessed, I have the tools to do this and can look at undertaking this repair in the coming weeks.

**Comment by magman2112** [comment]
The broken leg is now back in one piece. There is still some remedial work to do on this leg, mainly filling in some of the gaps due to shrinkage and from when the leg first broke. Then this leg will need to be sanded.

The remaining tasks are all sanding related.

**Comment by DoESsean** [comment]
@magman2112 Would you say this issue can be closed now? Or would you like it left open until the final varnish, etc, is complete?

**Comment by johnmckerrell** [comment]
I was thinking it would probably make sense to cut a hole or two in the middle of the table for passing wires through. Might seem quite drastic but will certainly work a lot better than having them draped around the edges. Might be fun to put some Qi charging pads in too :-)

**Comment by Thingomy** [comment]
I can see why it might be useful to have wires coming up through the centre of the table, but I'm finding it hard to imagine how this could look good. Also the table might still be there long term but the need for wires might have gone (I've still got a desk with a hand sawn slot for fanfold paper ...).
I think we should collect ideas on how other people have made this work before going ahead.

**Comment by jackie1050** [comment]
I can see why it might be useful to have wires coming up through the centre of the table, but I'm finding it hard to imagine how this could look good. Also the table might still be there long term but the need for wires might have gone (I've still got a desk with a hand sawn slot for fanfold paper ...).
I think we should collect ideas on how other people have made this work before going ahead.

**Comment by ajlennon** [comment]
I originally had a box setup for wireless streaming which I still think would work well

**Comment by jackie1050** [comment]
Note: original grumpy comment was from me - apologies - I hadn't realised JR was still logged on my laptop. But that sounds like a great idea...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ajlennon** [comment]
Or if that’s too painful for people to set up is there a wireless HDMI dongle we could get in cheaply ?

**Comment by johnmckerrell** [comment]
Can we do universal wireless power too?

--

**Comment by ajlennon** [comment]
Course we can... heads off to build Tesla coil...

**Comment by magman2112** [comment]
The table has now been finish sanded and waxed. New fixing screws have been fitted in all fixing holes.
