### ISSUE TITLE
Check on First Aid kits for New Year.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1022]
I noticed that there are apparently at least 2 First Aid Kits in DoES at present, one near the kitchen (on top of the mains fusebox) and one in the laser cutters room (that is now hung on the wall outside the metal workshop).

As neither of these kits are in ideal locations and the one by the metal workshop needs checking as it is far from complete at present, this raises the following questions:

- how many First Aid kits we should have and where should they be located?
- how frequently should they be checked and refreshed?
- who should be informed so they know where to find the First Aid kits in an emergency?
- if the kits can be wall mounted, where should they be installed?

**Comment by DoESsean** [comment]
[https://www.firstaid4less.co.uk/First-Aid-Kits-Refills/HSE-Compliant-First-Aid-Kits-Refills/HSE-Compliant-First-Aid-Kits-Refills?utm_source=google&utm_medium=product_feed_or_listings&pl=STD&ccv=Y&gclid=EAIaIQobChMIs8Sow6Pj3wIVyrftCh1DVAK7EAYYASABEgKXDvD_BwE](url)

**Comment by DoESsean** [comment]
[This is HSE compliant, and less than £12.](https://www.firstaid4less.co.uk/First-Aid-Kits-Refills/HSE-Compliant-First-Aid-Kits-Refills/HSE-Compliant-First-Aid-Kits-Refills?utm_source=google&utm_medium=product_feed_or_listings&pl=STD&ccv=Y&gclid=EAIaIQobChMIs8Sow6Pj3wIVyrftCh1DVAK7EAYYASABEgKXDvD_BwE)

**Comment by DoESsean** [comment]
[St John's Ambulance one here](http://www.stjohnsupplies.co.uk/products/First-aid-kits/Workplace-kits/Small-BSI-compliant-kits/-St-John-Ambulance-small-standard-workplace-first-aid-kit)

[First hit on Amazon](https://www.amazon.co.uk/210-Piece-First-Kit-Emergency/dp/B07431BT96/ref=sr_1_1_sspa?ie=UTF8&qid=1547126346&sr=8-1-spons&keywords=First+Aid+Kits&psc=1)

**Comment by DoESsean** [comment]
> [This is HSE compliant, and less than £12.](https://www.firstaid4less.co.uk/First-Aid-Kits-Refills/HSE-Compliant-First-Aid-Kits-Refills/HSE-Compliant-First-Aid-Kits-Refills?utm_source=google&utm_medium=product_feed_or_listings&pl=STD&ccv=Y&gclid=EAIaIQobChMIs8Sow6Pj3wIVyrftCh1DVAK7EAYYASABEgKXDvD_BwE)

I've ordered 5 of these kits - one each for the events space, Room 29, Main Room, CNC Room and Laser Room.

**Comment by DoESsean** [comment]
These have arrived and been placed in the rooms.
