### ISSUE TITLE
Floorboard in events room has broken

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1028]
One of the floorboards in the event room has broken. I think it's the one my chair fell through at the Christmas party but the hole has started getting bigger. I'll put some safety tape on to highlight it shortly but would be good to repair sooner than later.

**Comment by magman2112** [comment]
The broken floorboard has now been replaced with new wood. 

I will leave this issue open for a little while longer, as I plan to stain and seal the gaps on the new wood, along with a few other flooring repairs in the event room,

**Comment by amcewen** [comment]
Given we've closed #708, I'm assuming this is all done and dusted now.
