### ISSUE TITLE
Carpet coming up near the soundproof room

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1029]
The edging strip by Matt's desk has come off and the carpet is lifting along that edge.  We need to glue the carpet back down and refit the edging strip.

Ben has lent us some spray contact adhesive to use for it (I had bought some carpet tape too, which is in the tape drawer) and it's in the solvents cupboard at the minute.  We should screw/nail down the edging strip too so it stays in place once refitted.  (Find Out also have an extra bit of edging strip to fit across the doorway to their room, which it would be good to refit for them too while we're at it).

**Comment by magman2112** [comment]
With the help of @amcewen, this carpet has been glued back down and the edge strip screwed down. This should hopefully stay put now.
