### ISSUE TITLE
Kitchen cupboard (tea/coffee) veneer has come loose

### ISSUE THREAD

**Issue by osfameron** [DoESLiverpool/somebody-should#103]
just needs gluing back in place?

**Comment by johnmckerrell** [comment]
I've glued some of the pieces successfully but it seems like someone has bent one back, assumedly to improve it, but that's making it tricky to flatten it. Currently secured with duct tape to hopefully let the glue take, it's quite likely it won't work in which case we're probably better off just ripping that piece off

**Comment by johnmckerrell** [comment]
Taken duct tape off, doesn't look great but should do.
