### ISSUE TITLE
Commission and name the new drill press

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1033]
We've been given [a brand new drill press](https://twitter.com/DoESLiverpool/status/1086291691802374145) by the very generous Jim Chadwick.  We need to...

 * [x] Assemble it
 * [x] Install it in the workshop
 * [x] Name it
 * [x] Set up the wiki page for it

**Comment by magman2112** [comment]
@Sean-anotherone assembled the drill last Maker Night. As the machine is quite heavy though, it needs to be bolted to the bench before use (there is a sign on it at present to make people aware).

**Comment by amcewen** [comment]
@Sean-anotherone has bolted it down now and named it Sergeant.

**Comment by DoESsean** [comment]
I've created [a Wiki page](https://github.com/DoESLiverpool/somebody-should/wiki/Drill-Press-(Sergeant)) for this, but have no idea what should go in it. 

If someone could fill it out with the required info, we can get this issue closed.

**Comment by amcewen** [comment]
[Its wiki page](https://github.com/DoESLiverpool/somebody-should/wiki/DrillPressSergeant) has been fleshed out, using the [Equipment Template](https://github.com/DoESLiverpool/somebody-should/wiki/Template-Equipment-Page)
