### ISSUE TITLE
Gerald's gantry is skewed (s̶c̶r̶e̶w̶e̶d̶)

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1036]
Gerald is cutting parallelograms, when told to cut squares.

It seems that the left side of the gantry is too far forward by approx 1 part per 100 parts of gantry width. 2 identicaly outlined parts are shown in the photograph overlaid, they are 140mm square, aligned on one edge  [with one upside down -- JRP], and are seen to be aprox 3mm misaligned at the other side.

This will be affecting all jobs cut on the machine.

@DoESLiverpool/laser-maintenance 
 
![img_20190121_210756](https://user-images.githubusercontent.com/26458780/51499346-d6bb3f00-1dc1-11e9-82a6-40b35fb039b9.jpg)
![img_20190121_211438](https://user-images.githubusercontent.com/26458780/51499347-d753d580-1dc1-11e9-9782-d67b25329f0c.jpg)

**Comment by jrp** [comment]
I just realised that I have parts that I need to cut to match some that were cut in this state, so if anyone is planning on fixing this, please let me know first, so I can quickly get them cut before the fix.

**Comment by magman2112** [comment]
We have a laser maintenance day booked for this coming Saturday, 2nd February. We may get round to looking at this issue on Saturday, but I suspect we will be busy moving Morris into the laser room for most of the day.

I would suggest @jrp that cutting your parts sooner rather later would be a good idea though, as there are a few tasks queued for Gerald that when fixed could also address this issue.

**Comment by KarlDunkerley** [comment]
What time Mike?
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Tuesday, 29 January 2019, 17:25:32 GMT, Mike Gorman <notifications@github.com> wrote:  
 
 
We have a laser maintenance day booked for this coming Saturday, 2nd February. We may get round to looking at this issue on Saturday, but I suspect we will be busy moving Morris into the laser room for most of the day.

I would suggest @jrp that cutting your parts sooner rather later would be a good idea though, as there are a few tasks queued for Gerald that when fixed could also address this issue.

**Comment by Thingomy** [comment]
Ok, my parts are now cut so all good. I will try to be around on Sunday if I have a time.

**Comment by magman2112** [comment]
I did a couple of measurements with @Sean-anotherone on Maker Night and the x-axis is approx 6mm out of alignment from left to right across the bed. 

I plan to replace the y-axis belts in #1055 on Saturday, so I can check if the belts are affecting this issue and possibly check some other alignment issues at the same time.

@DoESLiverpool/laser-maintenance

**Comment by magman2112** [comment]
With the replacement of the y-axis drive belts on Sunday, it was found that the x-axis gantry was very loose, so it was possible to move the gantry 10-15mm on one end compared to the other. A number of loose bolts for the gantry were also found.

The gantry was initially trued up by using the large steel ruler to measure to the back of the machine and by moving the drive belt on one side by steps on the belt. I was ably assisted by @Thingomy with this task.

Once initially aligned, a large test pattern was engraved into a piece of cardboard the size of the bed with crosses in the 4 corners then measuring the diagonals to find equality - this was measured to within 1mm, which equates to less than 1mm accuracy across the full width of the bed.

I will close this issue for now, but the issue should be re-opened if this issue should re-occur, as we now have a practice to adjust the axis for accuracy.

**Comment by MatthewCroughan** [comment]
This has been further remedied with a realignment performed by @magman2112, after doing this we discovered another issue. #1093
