### ISSUE TITLE
Take a couple of good photos of Room 29

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1037]
Now that Room29 is finished, we should take a few good photos of it.  I've [taken one today](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Promo/Photos/room29-3.jpg) (because I want to use it in a talk I'm giving to the North Wales Tech group this evening), but the weather isn't best for it.

Getting another couple when it's sunnier and ideally when there are a load of people using the space would be good.

**Comment by johnmckerrell** [comment]
https://twitter.com/DoESLiverpool/status/1096033649022173185
https://twitter.com/LiverpoolHR/status/1106118040398237696

**Comment by johnmckerrell** [comment]
There's now 4 photos in somewhere-safe, should do for now but we should take more if we get the opportunity.
