### ISSUE TITLE
Refit the door on Dinky

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1038]
With the new carpet in Dinky, the door needed to come off as it no longer fits.  We need to shave a bit off the bottom and re-fit it.

**Comment by magman2112** [comment]
I have shaved about 4mm off the door to Dinky and temporarily re-installed the door. It will close now, but is rubbing a bit too much on the carpet at the moment methinks.

I am hoping to come in on Sunday to make a few more adjustments to close this issue.

**Comment by magman2112** [comment]
Adjusted and re-fitted. All OK now.
