### ISSUE TITLE
Do something for World Book Day

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1043]
Obviously books are unimaginably cool and the gateway drugs to happiness, success, awareness and all sorts of weird things.

Can we do something @DoES for #WorldBookDay? I'll be there if so

![image](https://user-images.githubusercontent.com/1537834/51703254-cc8d8080-200d-11e9-939a-73001f7724f4.png)

**Comment by johnmckerrell** [comment]
Can I ask you when it is?

--

**Comment by ajlennon** [comment]
Here you go

![image](https://user-images.githubusercontent.com/1537834/51704958-3c056f00-2012-11e9-8e64-82fa8dad7193.png)

**Comment by ajlennon** [comment]
6 days after my birthday just in case anybody needs to know for present buying and so forth...

**Comment by johnmckerrell** [comment]
What would you like to do?

--

**Comment by ajlennon** [comment]
I would like to organise a reading day in the events room.

- AM session and PM sessions.
- Fifteen minute reading sessions. 
- People read from the book(s) or poetry they love.
- Open access of course, we live stream and record.

I strongly suspect that this can be improved upon. Can we get some schools or other groups involved to come and see us?

**Comment by johnmckerrell** [comment]
Yes

--

**Comment by ajlennon** [comment]
Thank you. I'm very keen on this x

**Comment by DoESsean** [comment]
Just went and had a chat to Toni who is the Sharks leader. She says she loves World Book Day, so may well be interested in trying to fit something together.

If you want to drop her a line, @ajlennon, her email is @toni.winder@salesharks.com

**Comment by DoESsean** [comment]
Did you follow this up @ajlennon? Do we have any plans afoot?

**Comment by ajlennon** [comment]
Trying to arrange to meet up with Toni :)

**Comment by ajlennon** [comment]
Much as I wish I had been able to progess this I didn't. And it's too late for 2019 :(
