### ISSUE TITLE
Cut up spare L-shaped desk tops to use as CNC sacrificial beds

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1044]
As we're using the metal frames from (two of) the old L-shaped desks, we've got their (scratched, not much use anyway) tops spare.

They're cluttering up the main room at the moment, but rather than just get rid of them, @magman2112 suggested they'd work as sacrificial beds for the Kinetic CNC router.  We should cut them to a suitable size and store them somewhere in the CNC room out of the way.

**Comment by Sean-anotherone** [comment]
Great idea !  Thicker and more solid than the various bits of MDF currently in use.

**Comment by magman2112** [comment]
This has now been done. These have been stored under the CNC cutter table.
