### ISSUE TITLE
Set up and commission reflow oven

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1045]
Courtesy of Aeternum (John Cassidy's company) there's now a T962 reflow oven in the space on loan.

There seem to be a few improvements that people do to them, as documented in https://github.com/UnifiedEngineering/T-962-improvements  We should do a couple of them (at least) before putting it into general use.

 * [x] Check earthing
 * [x] Replace masking tape with kapton
 * [x] Document its usage
 * [x] Find a home for it (the workshop reorg planned in #955 should help there)
 * [x] Give it a name

**Comment by amcewen** [comment]
I've created the [wiki page for it](https://github.com/DoESLiverpool/somebody-should/wiki/Reflow-Oven) and updated [the usage instructions from the old oven](https://github.com/DoESLiverpool/somebody-should/wiki/Using-the-Reflow-Oven).

*fingers crossed* @MatthewCroughan has reflowed his first board in it too.

Given that you'll take it to wherever you're working on the boards, it can live next to the electronics workbench, with the oscilloscopes.

Only remaining task for it is to give it a name!

**Comment by magman2112** [comment]
Not many suggestions for names have come forward so far, so I'm going to propose Flo, or Florence.

**Comment by DoESsean** [comment]
Since I'd only left this issue open in order to remind me to cut some vinyl lettering to name her, and I've just found out that she's not actually ours so I probably shouldn't do that, I'm closing this issue.
