### ISSUE TITLE
Accessibility in the Laser room.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1046]
With all of the changes planned for the Laser room in #955, I thought it may be useful to investigate any additional changes that we can make in this room to make some of the lasers more accessible.

In particular, we have an option to use lower desks for the laser PC’s (in place of the high worktops we currently use) and possibly to place Sophia on a lower support to make it more accessible. We will also be paying careful attention to space around the machines as well.

Are these options of any practical use? In particular, I would appreciate comments from @Robotorium and @cheapjack.

**Comment by Robotorium** [comment]
I would especially love Sophia to be a bit lower down. The computers being
lower would be great, but I can make it work as they are if I need to. I
can't use the actual lasercutters without help, as things stand.

Op do 31 jan. 2019 12:15 schreef Mike Gorman <notifications@github.com:

**Comment by DoESsean** [comment]
If this is possible to do safely, then I definitely think it's something we should do.

**Comment by amcewen** [comment]
![Smaller laser-cutter in its new, lower position](https://pbs.twimg.com/media/Dyp_pBaWoAAfZ0W.jpg)

Sophia is now lower (and in a great looking laser-cutter workshop!), so it'll be good to know how well it works in practice (and if there are any other bits that would help).  Admittedly, issue #5 will also help with this (and is now moving fowards) :-)

**Comment by Robotorium** [comment]
I'll be in as soon as my wheelchair is returned to its former glory.
Currently a pile of scrap, more or less...

Op di 5 feb. 2019 om 17:00 schreef Adrian McEwen <notifications@github.com>:

**Comment by Robotorium** [comment]
But that looks *awesome* to me!

Op wo 6 feb. 2019 om 16:52 schreef Snoof Snoofington <snoofers@gmail.com>:

**Comment by johnmckerrell** [comment]
Thanks @Robotorium , I've been meaning to report that someone *not* in a wheelchair was in using Sophia today and reported that the positions for Sophia worked fine but that it might be nice if the keyboard and mouse were a little higher. I think @magman2112 did have something in mind for putting a small desk or shelf there.

**Comment by Robotorium** [comment]
That makes sense. I'll try and make it tomorrow night or Saturday, anyway,
but if not I should (all digits crossed) bumble over next week and give it
a whirl.

Op wo 6 feb. 2019 16:56 schreef John McKerrell <notifications@github.com:

**Comment by DoESsean** [comment]
I assume just a floating shelf under the window would work? There's not going to be anything too heavy on it.

**Comment by magman2112** [comment]
I have an old style Swing out TV wall bracket that might work as a solution for this issue. It was designed for an old style portable TV, so is deep enough for a monitor and keyboard if we add a piece of wood to widen it a little. I will bring it in on Thursday so we can try it for size.

**Comment by Robotorium** [comment]
I've just been in, it's awesome and I love it!

Op do 7 feb. 2019 11:22 schreef Mike Gorman <notifications@github.com:
