### ISSUE TITLE
Plan layout of the recess now that laser cutter Morris has been moved to the laser cutter room

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1048]
This is a place to record details for the layout of the recess, to make sure everyone is aware of any plans and has a chance to discuss them.
Particularly:
- what equipment and storage should go in the recess
- whether we can have equipment at a height where it can be accessible from wheelchairs without having to ask for assistance

**Comment by johnmckerrell** [comment]
A few things I think it would be worth considering moving into here:

* Printers (2D!)
* Mailboxes
* Maybe the secure disposal bin?

Having the mailboxes tucked away a little might help for security, although if placement of equipment means there's a good reason for random people to be in there anyway that might negate this.

**Comment by DoESsean** [comment]
Ok, so this is actually a ridiculous idea but it occurred to me so I'm going to write it down.

If we got a couple of couches in there, we could have a really nice little chat show-type set up. We could actually film stuff to go on our YouTube channel with the people that work here, or interesting folk that come and do events.

This wouldn't necessarily preclude us having other stuff in there too, and could be moved in and out as we liked so long as there was a nice clear central space.

Again, I realise this is kind of mental but, from a visibility point of view, it could be very good for us.

**Comment by magman2112** [comment]
I've talked to a few people about this, but now it is time to write it down.

I propose that we move the cupboards and worktops that are currently next to the laser room, along with all of the equipment on them into the recess.

Once these are move, we have two desks that can be placed next to the laser room to make a sowing area (as the current worktops are too high for sowing, etc.), also the light is good in this area for sowing. This will also clear the desks and legs out of the recess area at the same time.

This combined move will make the recess a more useful space and add a useful sowing area, as well as moving a quite active area, with respect to the sublimation printer, etc,  into another part of the maker space.

As part of this move, I also plan to install some shelf brackets on the wall next to the CNC Room, which can be used for the mailboxes and possibly relocate the laser printers and some stationary supplies into this same area on top of the plans chest, whihc will stay where it is at present.

We could also install some shelves on the far wall (adjacent to the stairs corridor) for additional storage at a later date.

**Comment by magman2112** [comment]
The worktop, drawers and equipment have now been moved and the desks set up for the sewing equipment.

I still plan to cut down the worktop on the CNC room side of the recess, to give a bit mor accessibleity in this area, as well as possibly installing some more shelves as in #1098, so will leave this issue open for now.
