### ISSUE TITLE
Gerald too noisy

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1051]
Jason (the landlord) mentioned that Gerald had gone noisy again since the move. I think it's the air compressor causing most of the noise so I've moved it down next to the extractor fan. I've also put some cardboard under both of them as additional padding. Hopefully that'll sort it but we need to be careful with this if we move things around.

**Comment by johnmckerrell** [comment]
Ah, #982 is the previous issue about this.

**Comment by magman2112** [comment]
Jackie mentioned this to me last week. After the re-arrangement of the room the extractor fan was placed on top of the cooler, which possibly contributed to more noise from the extractor. After Jackie’s comment, I moved the extractor back under Gerald and placed it on the carpet it had been sat upon prior to the move.

I did notice when I was coming into DoES last Sunday that the fan is now quieter than it was before the move.
