### ISSUE TITLE
Buy ink cartridges for A3 HP OfficeJet 7510 (at least Black, but probably whole set)

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1052]
The OfficeJet 7510 won’t print anything until we replace the Black cartridge.

It looks like last time, we bought [a set of these CMYBabee compatibles](https://www.amazon.co.uk/gp/product/B06XSGS27Q), but [this Gohepi set](https://www.amazon.co.uk/gp/product/B01KWQ5MQ8/) included a _second_ Black cartridge for the same price, so I’ve gone with that instead.

The delivery should arrive tomorrow, so I’ll use it to print the Pricelist and Safe Space posters from #962 and #940 on Monday, and report back.

**Comment by johnmckerrell** [comment]
There might be one on Sean’s desk?

--

**Comment by zarino** [comment]
> There might be one on Sean’s desk?

There was indeed a stack of catridges on Sean’s desk, as well as a box of empties. I‘ve moved them all into the stationery cupboard.

Turns out the printer didn’t like the Black cartridge I bought, so while I follow that up with the seller, I’ve installed the spare Black that was on Sean‘s desk.

**Comment by DoESsean** [comment]
Can this be closed then? Or do we need to buy replacements for the spares first?

**Comment by zarino** [comment]
We should probably buy another set of https://www.amazon.co.uk/gp/product/B06XSGS27Q since we know they work, and that way they’ll be ready to swap in as soon as the current ones run out. @DoESsean Do you want to handle that, then close this issue once the order’s been placed?

**Comment by DoESsean** [comment]
These have been ordered and should be delivered tomorrow. We'll close this once they arrive.

**Comment by DoESsean** [comment]
Tied in with #233

**Comment by zarino** [comment]
@DoESsean I assume these arrived _ages ago_ and this ticket can now be closed?

**Comment by DoESsean** [comment]
That was my assumption when I went on my spree, but I wanted to wait until I'd had chance to sort out the stationery cupboard and printing supplies to make sure we had a stash hidden away for when they're needed before closing.

**Comment by DoESsean** [comment]
We do have a full set of inks available.
