### ISSUE TITLE
Add power control for Ultimakers 

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1054]
I’ve finally managed to revisit 3D printing cams and we have a new channel showing real time printing for one of the printers:

www.youtube.com/doesliverpool

The mount needs a bit more work but I’m pleased with what we can do with a Pi0w and a PiCam.

If we think this is useful and should stay then I’m thinking it would be worth putting a couple of Sonoff switches in so that if a print goes wrong we can remotely turn off the Ultimaker. 

How does that sound?

@goatchurch?

**Comment by ajlennon** [comment]
Have had feedback that being able to turn off prints (eg when they go wrong overnight and filament is being wasted) would be useful.

**Comment by ajlennon** [comment]
eg the point made was we wouldn’t want random people turning things on and off which I guess is pretty obvious ☺️

**Comment by Pezmc** [comment]
Alternatively, you could use https://octoprint.org/  (and a VPN) on the (or a) Pi to enable remote control of the printers, which would include start/stop/pause or print jobs.

**Comment by JackiePease** [comment]
Closing as it doesn't seem to be much of an issue currently and might not be easy to implement given access and Ultimaker Octoprint issues.
