### ISSUE TITLE
Add an extension cable for presentation/display on the TV in DoeS Dinky

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1059]
It would be useful to be able to have a laptop on the meeting room table and display presentations on the TV on the wall.

Either

- long HDMI cable possibly with adaptors for USB-C etc.
- some kind of TV dongle that we can stream to?

**Comment by johnmckerrell** [comment]
There’s an (old style) Apple TV on my desk, it needs a power supply (and HDMI cable) I’ll put that in there for now.

**Comment by ajlennon** [comment]
The UX room HDMI is connected to one of the TV inputs and the Apple TV to another.

We can either stream to the Apple TV for presentations or connect to the HDMI cable

![tv setup](https://user-images.githubusercontent.com/1537834/53019089-deffac00-344b-11e9-84bf-fc0937e6317c.jpg)

Probably work finding a longer HDMI cable that will reach to the desk...

**Comment by ajlennon** [comment]
Leaving this open pending finding a cable that reaches from the TV to the meeting table.

It was also mentioned by Cheshire Fire Service this morning that the cables there are a trip hazard. Do we have something to put on top of them somewhere?

**Comment by chris-does** [comment]
### Installed a robust 10M HDMI Cable (supports upto 4K@60Hz)
### Installed a [D-Line FC83H Medium Duty Linkable Floor Cable Cover](https://www.d-line-it.com/pdf/uk/datasheets/D-Line_FC83H_Datasheet.pdf)

- The HDMI cable is currently connected directly to an HDMI port at the back of the Toshiba display. 
- The cable then runs straight down the wall from the display to the ground, where it is then routed along the edge of the floor (against the skirting board) into the corner with the bare brick wall.
- The cable run then continues along the edge of the floor against the brick wall (at several points - where space permits - the cable has been run in the gap between the wall and the floor boards to minimise exposure and any risk of tripping). 
- The cable then reaches a small hole in the brick wall where it is turned through 90 degrees (perpendicular to the narrow end of the table). At this point the cable has been inserted into a [D-Line FC83H Medium Duty Linkable Floor Cable Cover](https://www.d-line-it.com/pdf/uk/datasheets/D-Line_FC83H_Datasheet.pdf).
- Now protected by the floor cable cover, the cable runs under the table and exits the cable cover at the end of its 1.8m length.
- The remaining length of the cable is then "free" to be positioned on / under the table where required. 
- A plug cover/protector has been placed over the end of the HDMI plug to minimise the ingress of dust / dirt / fluids etc. when not in use.

![5](https://user-images.githubusercontent.com/52704101/61524899-5479a380-aa0f-11e9-926f-64bac6941f41.jpg)
![4](https://user-images.githubusercontent.com/52704101/61524910-5a6f8480-aa0f-11e9-8242-ccb09955d271.jpg)
![3](https://user-images.githubusercontent.com/52704101/61524914-5d6a7500-aa0f-11e9-89df-74449698680f.jpg)
![2](https://user-images.githubusercontent.com/52704101/61524918-5f343880-aa0f-11e9-8072-6fa32fe57de6.jpg)
![1](https://user-images.githubusercontent.com/52704101/61524923-61969280-aa0f-11e9-8412-6342d2b3ae18.jpg)
![6](https://user-images.githubusercontent.com/52704101/61524933-63f8ec80-aa0f-11e9-9b4a-932c8c989a7d.jpg)

@DoESsean are you able to confirm if the cable routing as described and pictured above is sufficient from a Heath & Safety perspective? If so, I will leave it there. 
If more protection is required, I can install some ducting around the edge of the floor and insert the currently exposed parts of the cable into it.

I have left the previous HDMI dongle that was connected to the Toshiba display, the HDMI cable connected to the dongle, and the HDMI coupler connected to the other end of the HDMI cable in the middle of the table to be "re-homed" wherever is most appropriate.

Regarding dongles / adapters for use with the new HDMI lead, I can potentially provide the following:

- [ ] [USB 3.1 Type C to HDMI 2.0 UHD Active Dongle 150mmm](https://www.club-3d.com/en/detail/2349/usb_3.1_type_c_to_hdmi_2.0_uhd_active_adapter/);
- [ ] [Mini DisplayPort 1.4 to HDMI 2.0b HDR Active Dongle 168.6mm](https://www.club-3d.com/en/detail/2443/mini_displayport_1.4_to_hdmi_2.0b_hdr/);
- [ ] [DisplayPort 1.4 to HDMI 2.0b HDR Active Dongle 191.7mm](https://www.club-3d.com/en/detail/2442/displayport_1.4_to_hdmi_2.0b_hdr/);
- [ ] [Mini HDMI to HDMI 2.0 Cable 1M](https://www.club-3d.com/en/detail/2343/mini_hdmi_to_hdmi_2.0_cable_m-m_1m-3.28ft/);
- [ ] [SpeaKa Professional HDMI plug C mini - HDMI socket Adapter](https://www.conrad.com/p/speaka-professional-hdmi-adapter-1x-hdmi-plug-c-mini-1x-hdmi-socket-black-gold-plated-connectors-325220);
- [ ] [Micro HDMI to HDMI 2.0 Cable 1M](https://www.club-3d.com/en/detail/2344/micro_hdmi_to_hdmi_2.0_4k60hz_cable_m-m_1m-3.28ft/);
- [ ] [SpeaKa Professional HDMI plug D Micro - HDMI socket Adapter](https://www.conrad.com/p/speaka-professional-hdmi-adapter-1x-hdmi-socket-d-micro-1x-hdmi-socket-black-gold-plated-connectors-audio-return-ch-189743);
- [ ] [DVI-D to HDMI Passive Adapter](https://www.club-3d.com/en/detail/2375/dvi_d_to_hdmi_passive_adapter/);

@DoESsean, @ajlennon If either / both of you are able to tick which dongles / adapters you think there is sufficient demand for, that would be great as it means I wont just be going with a "1 of everything, just in case" approach. 
I'll leave this open until the end of July 2019 and then provide whichever items have been ticked and close this issue #1059 accordingly.

**Comment by ajlennon** [comment]
That's great thanks! We're in Dinky this morning and I've just spotted the cable.

We need to use the big screen so that's absolutely brilliant thanks.

Will feedback on usage and dongles and such. At the moment just HDMI which is here :)

**Comment by johnmckerrell** [comment]
Can you just confirm that you didn’t unplug the white cable that goes through to the other room?

--

**Comment by johnmckerrell** [comment]
Not you, Chris. 

--

**Comment by chris-does** [comment]
>Not you, Chris.

@johnmckerrell - I can confirm I left the white cable connected between the Toshiba display and the other room untouched.

Though I did not test the white cable’s connection after my installation.

I did lift up the Toshiba display slightly, just to make it easier to access the HDMI port whilst installing the new cable, though I returned it to its original position post installation.

I don’t believe the white cable came loose at any point, so I hope that it has been unaffected by the installation and works as it did before.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chris-does** [comment]
Per above, I have left this open through the last full week of July 2019.

None of the dongle / adapter options above have been ticked, so I shall assume that - for now at least - no additional dongles / adapters are required.

On this basis, I will close the issue.

Should a need for dongles / adapters arise in the future, I may still be able to provide those in the following list, so feel free to @chris-does with a request.

Potential dongles / adapters:

- [ ] [USB 3.1 Type C to HDMI 2.0 UHD Active Dongle 150mmm](https://www.club-3d.com/en/detail/2349/usb_3.1_type_c_to_hdmi_2.0_uhd_active_adapter/);
- [ ] [Mini DisplayPort 1.4 to HDMI 2.0b HDR Active Dongle 168.6mm](https://www.club-3d.com/en/detail/2443/mini_displayport_1.4_to_hdmi_2.0b_hdr/);
- [ ] [DisplayPort 1.4 to HDMI 2.0b HDR Active Dongle 191.7mm](https://www.club-3d.com/en/detail/2442/displayport_1.4_to_hdmi_2.0b_hdr/);
- [ ] [Mini HDMI to HDMI 2.0 Cable 1M](https://www.club-3d.com/en/detail/2343/mini_hdmi_to_hdmi_2.0_cable_m-m_1m-3.28ft/);
- [ ] [SpeaKa Professional HDMI plug C mini - HDMI socket Adapter](https://www.conrad.com/p/speaka-professional-hdmi-adapter-1x-hdmi-plug-c-mini-1x-hdmi-socket-black-gold-plated-connectors-325220);
- [ ] [Micro HDMI to HDMI 2.0 Cable 1M](https://www.club-3d.com/en/detail/2344/micro_hdmi_to_hdmi_2.0_4k60hz_cable_m-m_1m-3.28ft/);
- [ ] [SpeaKa Professional HDMI plug D Micro - HDMI socket Adapter](https://www.conrad.com/p/speaka-professional-hdmi-adapter-1x-hdmi-socket-d-micro-1x-hdmi-socket-black-gold-plated-connectors-audio-return-ch-189743);
- [ ] [DVI-D to HDMI Passive Adapter](https://www.club-3d.com/en/detail/2375/dvi_d_to_hdmi_passive_adapter/);
