### ISSUE TITLE
Create pledge for laser-cutter improvements

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#106]
- [x] Create list of things we want to do to improve the laser cutters - ducting, chiller, lenses(?), etc. with associated costs
- [x] Decide pledge platform (wiki, Kickstarter, etc.)
- [x] Publicise the pledge
- [x] Celebrate pledge being met
- [x] Buy stuff, fit stuff (might spawn new issues at this point)

**Comment by amcewen** [comment]
It's getting warmer again.  Twice this week the coolant temp has been running in the 30s :-/

Getting the chiller would be very handy.

**Comment by DefProc** [comment]
To improve the efficiency and reliability of the laser cutters, we should:

 * Have a cooler attached to each cutter *this is the single biggest improvement we could make*
   * A [CW3000](http://shop.justaddsharks.co.uk/collections/featured/products/cw3000-water-chiller) would suit Sophia (£240)
   * A [CW5200](http://shop.justaddsharks.co.uk/collections/featured/products/cw5200-water-chiller) would suit Gerald (£500)
   * or a CW7000 would do both at once (~£700)
 * Gerald needs a new, and much more powerful extractor fan (~£100)
 * Built-in ducting would simplify user operation (~£100)
 * We will need to replace the lens on Gerald (~£65) at some point in the not-too-distant future.

So our ideal amount to raise would be: **£1000**

**Comment by DefProc** [comment]
Pledge published: http://doesliverpool.com/?p=1601

**Comment by amcewen** [comment]
How much publicising have we done?  I've spotted some tweets, but are we going to post it to the Google group and send it out to the occasional-announcements mailing list too?  A poster near the laser-cutters?  A notice on the laser-cutter booking page on the website?

**Comment by DoESsean** [comment]
Good thinking.

We've just added a thermometer to the original post, so that definitely
warrants new Tweets, and I'll also send something to the Google Group and
do a mail out.
