### ISSUE TITLE
Tool: Bandsaw - Startrite 301 S

### ISSUE THREAD

**Issue by RussCoty** [DoESLiverpool/somebody-should#1063]
Blade fully blunt.

(Looks like someone has been cutting a material with the wrong blade type).

**Comment by DoESsean** [comment]
I've ordered a new one today.

**Comment by DoESsean** [comment]
Blade has arrived and is on the machine ready to be fit.

**Comment by magman2112** [comment]
@Sean-anotherone fitted this new blade on Makernight, so this saw is operational again.
