### ISSUE TITLE
Russell's head has broken the ear protectors

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1066]
They seem quite shoddy, and exploded upon impact. We need new ones, preferably more comfortable! These look good.

https://www.amazon.co.uk/d/Ear-Defenders/Ear-Defenders-Comfortable-Adjustable-Construction/B06WVG2VFF/ref=sr_1_4?

Some sad pictures

![img_20190227_220749](https://user-images.githubusercontent.com/26458780/53526803-0eae5400-3add-11e9-9fce-40e856bd2931.jpg)
![img_20190227_220816](https://user-images.githubusercontent.com/26458780/53526804-0eae5400-3add-11e9-83c8-875f6aeaa9b1.jpg)

**Comment by magman2112** [comment]
The other set of ear defenders broke on Maker Night, so we now have no useable ear defenders in the space. We do have ear plugs in the metal drawers, so we will have to make sure people are aware of these whilst we source replacement ear defenders.

**Comment by MatthewCroughan** [comment]
@DoESsean https://www.amazon.co.uk/Mpow-Defenders-Comfortable-Folding-Padded-Construction/dp/B01KBZDB4K/ref=sr_1_5?keywords=ear+protectors&qid=1559499282&s=diy&sr=1-5

These ear defenders are a bit cheaper than the ones I've already mentioned, it'd be worth closing this issue once we have a pair or two!

**Comment by DoESsean** [comment]
I've ordered two pairs of these, they should be delivered tomorrow then the issue can be closed.

**Comment by amcewen** [comment]
There are ear defenders hanging on the ducks bills next to the CNC room, so I guess this can be closed.
