### ISSUE TITLE
Fire Risk Assessment

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1067]
It's really quite bad that we don't have this done, and I know it's something Jason has asked for a couple of times.

I've been wary, due to money being tight, of how much it will cost, but it looks like [we can actually do it ourselves.](https://www.gov.uk/workplace-fire-safety-your-responsibilities/fire-risk-assessments)

Would anyone feel comfortable doing this? It's pretty darned important.

On a similar note, we need to sort out various fire extinguishers. These will come with an upfront cost (for purchase and commissioning) and likely a yearly cost for maintenance.

**Comment by johnmckerrell** [comment]
It’s done and approved . Was featured in the directors meeting minutes recently. We would be better with some more extinguishers though. 

--

**Comment by DoESsean** [comment]
I should possibly read those minutes!

Will have a look at some companies to do extinguishers, but can close this issue.
