### ISSUE TITLE
Gas strut on Gerald failing

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1068]
The left hand gas strut on Gerald is starting to fail and the lid now doesn't stay up without support.

@amcewen remembered that there was a previous issue with these struts being replaced and that they are a custom size. I have not managed to find a GitHub issue with these details as yet, so if anyone can find the previous issue, please add it to the thread.

@DoESLiverpool/laser-maintenance

**Comment by amcewen** [comment]
The struts definitely got replaced - with some that were custom made, but were pretty cheap.

However, I can't find any mention of it in an issue anywhere either, so presumably Patrick didn't document it :-(  (**this is why I'm always encouraging people to write things down!**)

Searching through the accounts, it seems that we got them from [SGS Engineering](https://www.sgs-engineering.com/), and they cost £51.94 for the pair.  No details of the spec there though...

**Comment by KarlDunkerley** [comment]
If you have the date and amount the company should be able to dig out the specs I would suggest. They should keep records of jobs if they are any good.
    On Saturday, 2 March 2019, 13:10:09 GMT, Adrian McEwen <notifications@github.com> wrote:  
 
 
The struts definitely got replaced - with some that were custom made, but were pretty cheap.

However, I can't find any mention of it in an issue anywhere either, so presumably Patrick didn't document it :-( (this is why I'm always encouraging people to write things down!)

Searching through the accounts, it seems that we got them from SGS Engineering, and they cost £51.94 for the pair. No details of the spec there though...

**Comment by magman2112** [comment]
Checking on the SGS Engineering site and looking at the part numbers on the Gas struts in Gerald, it would appear that we need part number GS8-18-160-200.

This would appear to be this part:
https://www.sgs-engineering.com/gs8-18-160-200

These appear to be £21.18 each including VAT. I suspect though that we would have to confirm which ends come on these struts so that they are a direct replacement. We need M8 holes in both ends of the strut for Gerald. I would also suggest replacing both struts at the same time, as they are both of the same age (July 2015 appears to be the manufacturing date.

If this sounds OK, is this something that @DoESsean can order?

**Comment by magman2112** [comment]
Just checked some of the ordering questions and it appears that we need 200N force as one of the required parameters - these details are printed on the existing struts, so I expect these are the required settings for this part.

**Comment by DoESsean** [comment]
This has been ordered and will be delivered on Monday.

**Comment by amcewen** [comment]
The struts arrived today!  They're in the cardboard tube they arrived in, behind the monitor for Gerald's PC, ready to be installed.

**Comment by magman2112** [comment]
Both struts have now been replaced on Gerald. The failed unit has been binned and the old working one has been stored in the laser spares cupboard.
