### ISSUE TITLE
RFID reader on events space doorbot isn't working

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1069]
doorbot1 on the events room door isn't recognising tags at the moment.

It's still up and running, and can unlock the door from the command line.  There's power to the RFID reader, and the wiring at the reader end looks okay.  I tried a reboot but that didn't fix anything.

**Comment by johnmckerrell** [comment]
I opened the internal electronics box open (at which point the backup battery fell out!)all the connections looked fine but there was a few exposed connections so I wondered if they might be shorting or something like that, while the electronics were more spaced out I tried using the RFID reader again and it seemed fine. Added some insulation tape to the exposed connections and everything seems to be working ok now. @ajlennon also improved the position of the reader so he can now use his implant too!

**Comment by johnmckerrell** [comment]
Happened again. Haven't tried anything beyond a reboot yet.

**Comment by magman2112** [comment]
Both Jackie and I could not get into the event space on Maker night, so I guess this may be an issue for Friday possibly.

**Comment by johnmckerrell** [comment]
I've tweaked the page about Doorbots on the organiser's wiki so hopefully you can use that to get access if no-one else gets chance to investigate. A SSH client is needed but everything else should be documented.

**Comment by johnmckerrell** [comment]
Opened it up again, poked at all connections including by the RFID reader itself, nothing helped. SSHed in and powered down, turned off power entirely, unplugged the RFID reader from the doorbot board, and the doorbot board from the Pi, plugged it all back in again and powered everything back up. Now works again.
