### ISSUE TITLE
The UP printer nozzle is blocked

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#107]
The nozzle on the Up is blocked.  I've dismantled the extruder to check it's not blocked elsewhere and that's all fine, and running it without the nozzle on it extrudes okay.

I had tried soaking the nozzle in acetone overnight, but it's still not clear.

**Comment by cheapjack** [comment]
Mark Wright suggested using a needle or drill to clear thru' (he used an acupuncture needle apparently just right size)

**Comment by amcewen** [comment]
Yeah, he mentioned that to me when I emailed him to see if we could steal the spare printer back.  And it did the trick - a random needle that I presume had ended up knocking around the space at Sewing Club.  It's now stored in the printer toolkit box.

**Comment by DefProc** [comment]
I've ordered a spare nozzle that should at least give us the option to replace-while-cleaning.
