### ISSUE TITLE
Top edge of the window above the electronics bench isn't fully secured

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1070]
Given it was ridiculously windy yesterday evening, I noticed some (small) movement in the window above the electronics bench.  Pushing it by hand you can see it moving a bit across the top edge, which doesn't seem to be fixed in at all...

It's not going to go anywhere, but we should get it fixed (and it'll reduce the drafts too :-)  @johnmckerrell has a video to show Jason.

**Comment by johnmckerrell** [comment]
And then Jason popped by so we demo-ed it in person instead.

**Comment by amcewen** [comment]
He's going to get his contractor to come fix it - we'll need to move the electronics workbench and clear the surface next to it when it's being done.

**Comment by amcewen** [comment]
They're going to fix it at 2:30pm today, so we need to move the electronics workbench out of the way before then!

**Comment by amcewen** [comment]
They haven't managed to get all the kit they need to do it today.  They're going to call in Wednesday morning to see if there's a half-hour-or-so slot on Weds that they'd be able to do it in, to fit round Ben's visitors

**Comment by amcewen** [comment]
Targetting doing it on Monday 8th April now, they're going to call in early on to check times.

**Comment by DoESsean** [comment]
Did the contractor find a time to do this, or do I need to chase it up?

**Comment by amcewen** [comment]
Still a problem (have just tested it to check)

**Comment by amcewen** [comment]
This is scheduled to be done on 22nd November.  We'll need to move the electronics workbench out of the way and clear the surface next to it beforehand.  (Maybe at the end of #MakerNight?)

**Comment by amcewen** [comment]
This was done on the 22nd as planned - screwed into the lintel and sealed along the top edge.
