### ISSUE TITLE
Order more filament for the 3D printers

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1071]
We're getting a bit low on filament for the Ultimakers.  We should order another couple of spools of PLA.  Any preference on colours?

Alex (the architect) would like some light grey.

We should get a spool of PETG too so we can see how that prints compared to ABS.

**Comment by jackie1050** [comment]
I think there are still some PETG samples by the Ultimakers. Could test on something small.
________________________________

**Comment by Pezmc** [comment]
Don't forget to protect the bed when printing PETG! It binds to the print surface.

I believe Ultimaker advise using PVA to create a thin layer between the bed and the print?

**Comment by jackie1050** [comment]
Some clear 3mm PLA would be useful, also something translucent in a darker colour e.g. smoky grey or emerald green.

**Comment by amcewen** [comment]
We have a load more filament now (for future info, we shouldn't order the 2.3Kg spools as they don't fit on the Ultimakers properly)
