### ISSUE TITLE
Fit water powered LED mixer accessory to various taps

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1077]
Here's a cheap recommended one.

https://www.amazon.co.uk/TIMETOP-Faucet-Stream-Temperature-Sensor/dp/B00ASFVFDI/ref=pd_sbs_79_1/258-8218794-8365810?_encoding=UTF8&pd_rd_i=B00ASFVFDI&pd_rd_r=ead0f5dd-4805-11e9-917c-7de6dac306e9&pd_rd_w=5xnCP&pd_rd_wg=8dJ0x&pf_rd_p=18edf98b-139a-41ee-bb40-d725dd59d1d3&pf_rd_r=RZ3RMBRJ8TDKN6EG9426&psc=1&refRID=RZ3RMBRJ8TDKN6EG9426

Need to check the threads we have are right.  Or just get some anyway.  

Need also to get some spares for a teardown, to see if it has enough energy to run some lora broadcasts.

**Comment by goatchurchprime** [comment]
Here's a pretty comprehensive teardown video, which can save us the bother.  
    https://www.youtube.com/watch?v=ngS5oJvkoDM

**Comment by johnmckerrell** [comment]
Guessing you might have checked by now but I'm fairly sure, from when we wanted to attach a hose pipe, that none of our taps have the screw fitting.

**Comment by goatchurchprime** [comment]
Here's a pretty comprehensive teardown video, which can save us the bother.  
    https://www.youtube.com/watch?v=ngS5oJvkoDM

**Comment by goatchurchprime** [comment]
I've ordered 3 to be delivered here mid-April.

**Comment by goatchurchprime** [comment]
Came through.  One on the sink tap, one to JohnC and one taken home
