### ISSUE TITLE
Add CO2 monitoring to our meeting rooms

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1078]
> "three people quietly sitting in a mid-size conference room produced CO2 levels that within 60 minutes, reached concentrations high enough to impair their ability to make the right decisions."

http://blog.gigabase.org/en/contents/132

**Comment by goatchurchprime** [comment]
This is already done.  I have the CO2 monitor and MQTT thing running from a breadboard on my desk, and showing up on the node-red dashboard.  It has a screen with the numbers on it, so it is portable.  All it takes is we got to do something with it.
