### ISSUE TITLE
Make use of the space next to Dinky, also resin printer pledge?

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1079]
John Cassidy has long wanted to get his equipment away from the junk area next to the CNC room, is it possible that we could use this space instead of the junk space to do some production, clearing and curing of resin prints?

Since resin printers are cheap, we would do well to make such a corner now rather than later, @ajlennon has expressed interest in buying one, I'd be interested in making/pledging to one also. Now that we have one, we know it doesn't stink much at all.

https://www.amazon.co.uk/Premium-Sparkmaker-High-resolution-Printer-Printing/dp/B07GDGYHNC/ref=sr_1_4?ie=UTF8&qid=1553016683&sr=8-4&keywords=resin+printer

I pledge £50 towards this, anybody else joining me?

**Comment by ajlennon** [comment]
Is this a good one then? Does DoES want a nano-bot invasion of additative manufacturing? :)

**Comment by MatthewCroughan** [comment]
@ajlennon It's the cheapest on the market, but it performs basically the same. The shell is just cheap plastic, and there's no preview screen, you load the SD on and the file comes right off, that's it.

With that limitation, it'd be interesting to see if we could hack the hell out of it and have it support Octoprint-like stuff for DLPs. https://www.nanodlp.com/

The processing requirements for DLP printing are immensely lowered since it's 2d projection, so much so that the slicing is fast even on a pi. You upload an STL to nanodlp, in a browser, and all the slicing takes place on the pi, and displays it to you via the browser.

**Comment by MatthewCroughan** [comment]
It's also worth noting that we could probably do better making our own, for the same price (£219), however, this thing would be fun to hack!

**Comment by Robotorium** [comment]
I'm full of skintness but can probably contribute a little bit in a few
weeks. I would very much like to partake of a robot army I seem to recall
being mentioned.

What's the cost of resin vs filament?

Op di 19 mrt. 2019 17:39 schreef MatthewCroughan <notifications@github.com>:

**Comment by ajlennon** [comment]
What's the cheapest one out there that supports NanoDLP without having the hell hacked out of it?

**Comment by ajlennon** [comment]
We need some Resin WormBerts!

**Comment by MatthewCroughan** [comment]
@ajlennon Those things don't go together. We can make our own and use nanoDLP though. Cheapest I can find is $2499

https://www.muve3d.net/press/

**Comment by ajlennon** [comment]
Why don't they go together? A DLP software tool and a DLP printer?

**Comment by MatthewCroughan** [comment]
@ajlennon No, "cheap" and "NanoDLP" :)

**Comment by ajlennon** [comment]
I've ordered the new Creality Resin Printer for us to have a play with! Should be arriving early next year...

https://www.banggood.com/Creality-3D-LD-002R-LCD-UV-Resin-3D-Printer-with-120X68X170mm-Print-Colume-Ultra-HD-2K-LCD-ScreenBall-type-Linear-Rail-p-1602694.html

**Comment by MatthewCroughan** [comment]
@jackie1050 We should tweet about this when we get it. This lets people do intricate modeling of figurines, something which is not as appealing or easy to do with FDM.

**Comment by jackie1050** [comment]
@MatthewCroughan I know - I also saw some very detailed jewellery designs when I visited 3DGBIRE in Chorley with @ka81 
It will be a good addition to the space - thanks @ajlennon

**Comment by DoESsean** [comment]
Printer is here and up and running.
