### ISSUE TITLE
Put a note on the main room bin about bin bags

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#108]
We should put a small note on the top of the main room bin bag saying that there are custom fit bags available.

**Comment by amcewen** [comment]
Could we put the label on the kitchen drawers instead?

Bags...
Black: general refuse
White: pedal bin in main room
Green: recycling

**Comment by DoESsean** [comment]
I've printed off both the above labels and stuck them on. They're not fancy, but they're effective.

**Comment by DoESsean** [comment]
Closed #108

**Comment by DoESsean** [comment]
Effective isn't good enough ;)
