### ISSUE TITLE
Get the Cisco VoIP phones working

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1080]
* [x] Find the Cisco VOIP phones that @DoESsean brought in
 * [ ] Evaluate their usefulness
 * [ ] Place in CNC room, laser room, Dinky in case of emergency

**Comment by amcewen** [comment]
I'm pretty sure they're in a couple of crates on the left-hand side of the alcove, on the floor.

**Comment by johnmckerrell** [comment]
Found the VOIP phones and have now moved them onto the racking by the toilets while I evaluate them. I've ordered a power supply from eBay so that I can at least try one out.

**Comment by johnmckerrell** [comment]
I put some documentation as I was working on this here: https://github.com/DoESLiverpool/somebody-should/wiki/Cisco-IP-Phone-7960

Not got them working yet.

**Comment by johnmckerrell** [comment]
These have been recycled now.
