### ISSUE TITLE
Check our address on our Google listing and update if necessary

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1087]
Beth from Sewing Club says one of the Sewing club members was misled by the address in our Google listing (it starts with 1, The Tapestry so she thought it would be where the Fashion Hub is)

**Comment by DoESsean** [comment]
I think it was @johnmckerrell that put us on Google in the first place, and the password isn't in the password repo, so I'm unable to log into our account to change things at the moment.

**Comment by johnmckerrell** [comment]
I looked and it offered me the ability to “suggest an edit” so I did that.

**Comment by johnmckerrell** [comment]
Updated now
