### ISSUE TITLE
Add a shelf next to the Microwave in the kitchen for tea and other items.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1089]
With the new Microwave in place in the kitchen, items should not be stored on this Microwave, as it is also a convention oven, so the top of the oven can become hot.

Whilst clearing out the alcove, it was decided to dispose one of the black desks. I thought it should be possible to cut down part of this desktop to act as a shelf in the kitchen to give us a bit more storage and make the tea, etc more accessible as well as making the other worktops in the kitchen tidier.

I will pick up some shelf brackets on Saturday to see if we can fit this over the weekend, which will get rid of one desk as well as making more space in the kitchen.

**Comment by DoESsean** [comment]
Shelf in place, things on it, I think we can consider this well and truly actioned.
