### ISSUE TITLE
Create an artistic yet functional randomness generator

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1091]
Raising this on behalf of Mark McKinlay.

He was suggesting we could do something similar to what CloudFlare do with LavaRand - i.e. LavaLamps generating randomness.

https://blog.cloudflare.com/randomness-101-lavarand-in-production

Could link nicely to the @MakeSpaceLive camera work and the #OpenCV work @goatchurchprime wants to do with image analysis

**Comment by seanspotatobusiness** [comment]
Might be a useless idea but schlieren imaging apperatus can be used to image turbulence in air which I've heard is pretty random. I'm not sure how difficult/expensive/bulky such equipment is.
