### ISSUE TITLE
Put musical instruments on the walls in Nook

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1092]
Mike, Jackie and I have discussed this being a good idea for the nook, since people have been playing my guitar and Chris Thompson's trumpet since they've been lying around. I'm more than happy to let people play it.

Also interested in making a nice LED edge lit display to go under the instruments to let people know they can play them.

![IMG_20190326_190652](https://user-images.githubusercontent.com/26458780/55026390-cfe7bd00-4ffa-11e9-96bd-ef8413e547bb.jpg)
![IMG_20190326_190700](https://user-images.githubusercontent.com/26458780/55026392-d0805380-4ffa-11e9-8a3a-bbacfc8fe93b.jpg)

**Comment by MatthewCroughan** [comment]
![IMG_20190326_205731](https://user-images.githubusercontent.com/26458780/55033796-cfa3ed80-500b-11e9-8d5b-c9f2fbe161d1.jpg)

Remedied, I have two more instruments to add in the case that we have space for it:

![IMG_20190326_211354](https://user-images.githubusercontent.com/26458780/55033955-3de8b000-500c-11e9-8853-683a2911c846.jpg)

**Comment by Robotorium** [comment]
Is
Is that a hammer

Op di 26 mrt. 2019 om 21:15 schreef MatthewCroughan <
notifications@github.com>:

**Comment by MatthewCroughan** [comment]
@Robotorium Nope, that's an Erhu, you're not the only one saying that :)
![image](https://user-images.githubusercontent.com/26458780/55036818-af782c80-5013-11e9-9e90-de7df2dd4ce0.png)

**Comment by Robotorium** [comment]
Looks cool, even though my inner drummer is sad about it.

Op di 26 mrt. 2019 22:08 schreef MatthewCroughan <notifications@github.com>:
