### ISSUE TITLE
Gerald needs new clips for Y axis

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1093]
The belts need retensioning on the clips because they're on the maximum screw adjustment, we have no ability to add more tension to the belts.

Successor to #1036 

@magman2112 knows more about this than me, so should comment with more details.

@DoESLiverpool/laser-maintenance

**Comment by Sean-anotherone** [comment]
I think I have some material suitable to make new compression clips for the belt, I'll make some and bring them this Thursday

**Comment by Sean-anotherone** [comment]
Fitted new clips and re-tensioned the belts- no longer slipping and missing steps and the alignment is within about 1mm across the whole bed, but major overhaul still required to bring Gerald back to his former glory
