### ISSUE TITLE
Put up shelving in the alcove for Mailboxes

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1098]
Now that most of the moves in the alcove have been completed, I discussed with @DoESsean about moving the mailboxes on top of the plans chest, using rails on the wall to add shelves for these, as well as storage for parcels.

There are rails left over from the shelving installation near the electronics bench that could be used, plus there are spare worktops that were proposed to be used as sacrificial beds for the CNC machine that could be used as shelves instead.

Julian had mentioned using these rails in #1095, so we will have to agree which is the best use for these rails first methinks.

We could potentially move the laser printer here as well, as there are LAN points on the wall behind the plans chest.

**Comment by amcewen** [comment]
We are allowed to buy more rails too :-)  

My preference would be that we paint them black before installing, to fit with our needs-to-be-written style guide.  Similarly if it makes the shelving look nicer/more consistent I think we should consider buying materials for that.

**Comment by magman2112** [comment]
I think that the rails we have are already black, though we do have to buy some more shelf supports (again in black).

It would be doable to paint the shelves as well though, especially as we have plenty of the grey paint that the doors were painted with.

**Comment by amcewen** [comment]
Ah, I thought we were talking about the shorter, white rails that are knocking around from Gostins.

@magman2112, @zarino and I just had a quick confab about colours, etc., and reckon we should get black hardware (rails and brackets) when fixing to brick walls, and white hardware when fixing to white walls.  We're going to try painting the shelves the same grey as the doors, with a view to adopting that as "standard colour" if it looks alright.

**Comment by magman2112** [comment]
I've ordered some new white rails for the alcove and 5 pairs of black brackets. The black brackets can replace the white ones by the electronics bench which will then free the white ones to be used in the alcove.

The hardware is due to be delivered on Wednesday.

**Comment by magman2112** [comment]
The rails have been installed and we had enough spare brackets to install 4 shelves. I cut down some of the spare worktops to make shelves. I also made 2 larger shelves for by the electronics bench.

Unfortunately, the black brackets that I bought are not compatible with the uprights, so these will need to be returned and another supplier found. I will open this as a separate issue. I will also open a separate issue for painting the shelves.
