### ISSUE TITLE
Sophia needs a new tube

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#110]
Power has been dropping on Sophia for a little while now (e.g. I ended up with speed 12 to get through 1.5mm acrylic a week or two back, and it was down to a speed of 6 yesterday).  @DefProc is in the process of getting a new tube ordered, but until then it's out of action.

**Comment by DefProc** [comment]
Tube is on order from Just Add Sharks

**Comment by DefProc** [comment]
Tube received, I'm expecting to fit it tomorrow.

**Comment by DefProc** [comment]
The tube is fitted (took me about 45 minutes in total). Checked with the "laser" button, and it's firing correctly. There was no obvious misalignment when run statically, so I've not gone to the trouble of checking beam alignment at this time.

**Comment by DefProc** [comment]
The beam was showing a double mark, indicating a misalignment, so the mirrors have been aligned as described in [rabbitlaserusa's guide](http://www.rabbitlaserusa.com/Manuals/BeamAlignment.html)
