### ISSUE TITLE
Add vinyl lettering in the lift to reinforce the message that you have to keep the button pressed

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1100]
We had an incident this weekend where someone thought they were stuck in the lift, having momentarily pressed the floor 1 button then been unable to open the door.
Although there is a label saying that you need to keep the button pressed to keep the lift moving, it seems that this can be easily overlooked so it would be good to have an additional notice. Agreed with Jason that we can produce some vinyl lettering.

**Comment by jackie1050** [comment]
Related info: if the lift alarm gets set off and you need to reset it, you just have to hold one of the call buttons (on any floor I think) for more than 10 seconds.  And if anyone ever needs to get into the control panel on the top floor, we've now got a triangle key for it in DoES...

**Comment by amcewen** [comment]
I've put the triangle key in the top drawer of the filing cabinet under the coffee machine for safe-keeping.  It's the black cross-shaped thing (like a minature 4-way tyre iron)

**Comment by DoESsean** [comment]
@amcewen Is there any chance you could tackle this while you do the white vinyl sign for the door?

**Comment by DoESsean** [comment]
I'm actually going to close this - the current lettering saying what to do is literally above the button. There is nowhere we could put it that would make it easier to see, other than at eye level, but that's not really any use if you get in the lift on the ground floor as it's only the platform that moves.

I think we have to just try and trust people to see what's there.
