### ISSUE TITLE
Door handle and lock broken on door for Dinky

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1101]
At the first Child friendly co-working day (precursor to Jelly Tots), the lock broke in the Dinky door whilst quite a few people were in the room. Fortunately, we were able to get the door open again and the broken lock removed.

I have now ordered a replacement Heavy Duty latch and replacement handles, which should be delivered on Wednesday. I should be able to fit these on Thursday, when I am planning to next be in DoES.

**Comment by DoESsean** [comment]
@magman2112 Did this handle and lock arrive? As with the CNC handle, it might be that someone else will have chance to fit them.

**Comment by johnmckerrell** [comment]
If there's any possibility of doing this before Thursday I know Ben will be very appreciative.

**Comment by magman2112** [comment]
New door handle now fitted and door can now be opened easily.

The door does catch a little bit on the floor trim and the sound proofing seal provides a bit of resistance to opening the door, but it is not too tight and I will put an extra screw in the floor trim to make this a little easier.
