### ISSUE TITLE
Payment details missing

### ISSUE THREAD

**Issue by BeckaLawson** [DoESLiverpool/somebody-should#1108]
It seems tricky to pay a recurrent non-standard amount to DoES. This started with me emailing Sean last month "I noticed all the new signs round DoES about prices so was trying to increase my donation ... but it seems surprisingly hard to do". I just wanted a link on the website to sign up for membership and another to donate a fixed amount per month of my choice.

There are various Paypal options on the website but only 4 levels of recurrent payment (at £35/65/80/180 per month)
https://doesliverpool.com/services/
https://doesliverpool.com/gift-vouchers/

Paypal doesn't seem to allow me to alter the amount of my recurrent payment, it only lets me cancel my current amount and set up another one. I could set up multiple £10 recurrent payments as a clunky alternative ... but I can't even see how to set this amount up as a separate item on the website - has it disappeared recently?

I also couldn't find the bank details on the wiki to set up a direct debit. All I could see was this
https://github.com/DoESLiverpool/somebody-should/wiki

cheers, Becka

**Comment by Robotorium** [comment]
I've set mine up as a standing order, seemed easiest and I've had no issues.

Op vr 12 apr. 2019 15:18 schreef BeckaLawson <notifications@github.com>:

**Comment by BeckaLawson** [comment]
Yes, standing order sounds good and means Paypal doesn't get a cut - but then in general the payment details need to be easily obtainable either by giving a contact email or on the wiki somewhere

**Comment by amcewen** [comment]
The bank details are on the wiki, at https://github.com/DoESLiverpool/somebody-should/wiki/DoES-Liverpool-Bank-Details but I'm all in favour of it being easier for people to give us money :-D

**Comment by BeckaLawson** [comment]
Thanks Adrian.

OK, I've edited this page https://github.com/DoESLiverpool/somebody-should/wiki to say

Payment You can set up a Paypal account for a desk or workshop access using the DoES website or a standing order for one-off or recurrent payments using these details.

and I'll email Sean to suggest that he adds a line on the two pages on the DoES website to either link to the bank details or, if you don't want that made too public, to give an email to ask for the info,

I'll close this issue now.
