### ISSUE TITLE
Dinky booking

### ISSUE THREAD

**Issue by mdunschen** [DoESLiverpool/somebody-should#111]
It would be good to be able to book Dinky from the website, just ike booking the laser.

**Comment by johnmckerrell** [comment]
+1

Should be doable, not sure but we might be able to setup another YouBookMe thing without paying any more.

**Comment by DefProc** [comment]
We can add more booking forms.

There's a trial setup live at [newdinky.youcanbook.me](https://newdinky.youcanbook.me/) that makes bookings to the visitor's calendar, available in ½–2hr slots 9·30am–17·30pm Monday to Friday.

How's that?

**Comment by mdunschen** [comment]
That looks very good, perfectly usable, albeit it took a long time on my
computer to load that page, which could be entirely my fault.

**Comment by DefProc** [comment]
OK then, (@DoESLiverpool) what's the best way to advertise this new feature?

**Comment by DoESsean** [comment]
Tweet, weeknotes, message to the Google Group.

**Comment by DoESsean** [comment]
Tweeted, and emailed the Google Group. Then realised I'd forgotten to
hashtag it with weeknotes, so we either need to keep an eye out for it, or
retweet a bit later with the tag, so as not to clog people's feeds.

**Comment by amcewen** [comment]
It should be listed in the DoES welcome pack/manual that gets given to new arrivals too.

**Comment by amcewen** [comment]
And given that "make a manual" predates this issue list, have now created issue #118 to track it.

**Comment by amcewen** [comment]
In lieu of us having a manual, and because things like this should also be put somewhere where the info won't disappear with time... I've added a link to it to the wiki on http://wiki.doesliverpool.com/Calendars
