### ISSUE TITLE
Block out the 2019 bank holidays from the laser calendars and desk calendar

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1112]
Just needs a booking that covers the 9:30-17:30 time span, can be an "all day" one so long as it shows as "Busy".

**Comment by DoESsean** [comment]
Done up to the end of 2020, so we don't have to worry about it again for like two years, and that's Future Seán's problem.

**Comment by DoESsean** [comment]
The 2026 Bank Holidays have been blanked out, and I've also deleted Maker Night on Christmas and New Year's Eves, and the Repair Cafe on 20/12.
