### ISSUE TITLE
Consult and optimize the coffee pot power schedule protocol

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1114]
At the moment the coffeepot is on a espurna/sonoff switch.  This has the old timer schedule programmed into it on the panel http://10.0.38.3/# to turn off at 21:00 and on at 9:00.  (@johnmckerrell noticed that the on-time is not necessary, because we can press the sonoff button when putting the coffee on)

I've done a basic calculation from the coffee machine power use.  

> heatpadWatts: 58
> waterheatingWatts: 2127
> waterheatingTime: 240 seconds
> Energy per boil: 0.1418 KWh
> Hotplate energy 24 hrs: 1.392 KWh
> 1 boil = 2.44 Hotplate hours

We could program an automatic turn-off into the sonoff switch after 2.5 hrs to keep the power use on the boil and the keep-warm the same.  

The auto turn-off feature would need to be set in a node-red instance as it's not programmable for in the espurna.  This would detect water boiling events and set a timer to when it switches off.

I'm going to put a probe in the keep-warm coffee on the next cycle to see if it actually keeps it warm.  We could put a little insulation wall around the pot to see if it keeps it warmer.  Some people just put their put in the microwave to warm it up.  

I know the energy use here is trivial (10 pots per day with both plates permanently on comes to 4KWh or about 64p), but this analysis can be applied to other devices when we have automated this one.

**Comment by ajlennon** [comment]
It looks like the pulse timer might do the job

https://github.com/xoseperez/espurna/issues/454

If not why don’t you raise an issue?

**Comment by goatchurchprime** [comment]
Need to look at the feature further.  Here's the simplest implementation to test out:

Suppose the pulse timer listened to its own power/on switch button, and it read its own mqtt signals without having to send them to the broker, then we've got a simple timeout system.  I'll need to check if this happens.  

Then its a matter of listening to slightly more complex pulse trigger functions than 1 or 0, such as x>2000 and then it can do it by listening to its own power out channel.

**Comment by goatchurchprime** [comment]
The coffee machine is a Bavilor Bonomat Novo2.  The 2019 price book describes the Novo as:

> 1 brewing system, 2 decanters and 2 hot plates.
> Holding capacity 2 decanters (24 cups) throughput per hour 18 litres (144 cups) 
> Brewing time 5 min. / 1 decanter  Price: £284

The up to date version is Mondo, which says it has "Self-regulating hot plates to preserve the optimum quality of the coffee"  https://www.bravilor.com/en-gb/product/mondo/200  

Our glass decanters cost £15.70, but there is a stainless steep one that's £24.60 and an equivalent vacuum flask brew through for £32.50.

I'll send them an email about whether we can just put a vacuum flask in place of the glass decanter and disconnect the hot-plate.

**Comment by goatchurchprime** [comment]
I've got a not very helpful reply from them, establishing that they're not treating this as an opportunity for a retrofitting product range:

> if you disconnect the hot plate you need to insulate the wires, the hot plate can not detect a empty glass jug and will stay on all the time the machine is turned on.
> ​
> the flask is a very tight fit but will just go under without the lid on and coffee should only be kept for around two hours as it will start to stew and the more air that gets into the flask the quicker the coffee will start to lose heat.
> 
> Ticket: https://braviloruk.freshdesk.com/helpdesk/tickets/173609

The 1.0L brew through vacuum flask is 175mm high, and the 1.5L flask is 215mm high.  There's 190mm of a gap if you removed the hotplate (which takes up 12mm), so only the 1.0L flask is going to fit.  

The 1.5L is available here (can't find the 1.0L one):  https://www.heatoncateringequipment.co.uk/catering-appliances-c803/beverage-equipment-c851/coffee-machine-accessories-c3094/bravilor-1-5-litre-brew-through-vacuum-flask-p53860

There's a 1.9L 7"=178mm tall one here that would fit: https://www.webstaurantstore.com/curtis-clxp6401s100-1-9-liter-stainless-steel-seamless-coffee-server-with-brew-thru-lid/945CLXP64.html

**Comment by goatchurchprime** [comment]
I've just sent off a message to the WilburCurtis about their flask.

> Retrofitting vacuum flasks to filter machines 
> 
> I'm in an office with an old Bravilor Bonomat filter machine that's switched on all the time.  I've calculated that the 58W hot-plate uses about 1 kWH of electricity a day, which costs about 20cents in your money.  Multiply this out by a year and it comes to more than the cost of a new brew-through vacuum flask.  
> 
> I've asked Bravilor about this (replacement flasks that would fit under the machine and disconnecting the hot-plate) and they were not very helpful.  The only flask that would fit in the 180mm gap is their 1.0Litre flask (the default glass one is 1.7Litres).  
> 
> Now I've noticed that you make a flask (Model: CLXP6401S100) that holds 1.9Litres and is 7.04inches=189mm tall, that could theoretically fit in its place.  
> 
> Have you checked this out already and know if it's a good idea to make this replacement?  Also, have you done any temperature comparisons over time between vacuum flask vs a hot plate technology that you could share?  (eg how long does the coffee stay warmer than it would on a hot-plate in a glass flask?)  
> 
> I see a lot of these machines in offices I go to, and it would be really nice if people were there was this easy replacement that was cheaper, improved the coffee while at the same time as saving electricity.  
>

**Comment by ajlennon** [comment]
This is all brilliant but I don't like not being able to push the "on" button on the pot like I used to. If I feel this way I suspect others are also a bit put out. Should we revert this back to the way it was and just monitor the current inconspicuously?

**Comment by ajlennon** [comment]
or is there another "clever" non-instrusive solution...

**Comment by johnmckerrell** [comment]
I don't think I'd mind having to press two buttons so long as it's very obvious, e.g. a note by the pot saying "if this button doesn't work press the button on the sonoff". Actually I suppose you could leave that button pressed in at all times and just use the sonoff to turn it on&off. I'd say the main thing is to make it very clear what to do, an improvement would be moving the relevant sonoff to be much closer.

**Comment by amcewen** [comment]
+1 to @johnmckerrell's comment.  It would be nice if it was obvious which of the two Sonoff devices I'm supposed to press the button on to get the coffee on.  One way would be to neatly stow the superfluous one where it isn't easy to spot, and move the correct one next to the coffee machine so people don't have to hunt around on the desk next to the coffee machine on the off-chance that some of the general clutter on it is related to making coffee...

On a separate note, this morning, having pressed the buttons on both of the Sonoffs to get the coffee to brew, it had then turned off again by the time any of us had wanted to drink any of the coffee.  (Which I'm assuming should be logged as a bug report for you?)

**Comment by ajlennon** [comment]
That's interesting. I didn't think it was on a timer. @goatchurchprime have you been experimenting with the pulse timer? Or is this related to the timer switch which I know we had some trouble with in the past?

**Comment by johnmckerrell** [comment]
FYI I just tried accessing the coffee pot remotely via the VPN. The web page didn't load properly, it asked for my username and password but then gave a blank page. The source suggested it had plenty of HTML there but it wasn't rendering properly. But it appeared to have turned the coffee on, so without me actually doing anything. Something to be aware of I thought.

**Comment by ajlennon** [comment]
We have a VPN ? 😯

**Comment by johnmckerrell** [comment]
/I/ do ;-)

**Comment by ajlennon** [comment]
Nicely done 😉 

What were you accessing? One of the two Sonoffs? Were you doing this with a real computer or something from Apple 🍏?

**Comment by johnmckerrell** [comment]
Yes, accessing 10.3.141.164, using Safari and Chrome, but like I say it worked fine if I was on the Wi-Fi, just not via the VPN.

**Comment by ajlennon** [comment]
Let’s investigate tomorrow!

**Comment by johnmckerrell** [comment]
Can this be closed now, are you still planning to do something with the flasks? The sonoff setup and automatically turning off in the evening seems to work pretty well?

**Comment by arthurrowland** [comment]
The sonoff had lost it's schedule settings so feature had broken. I have now set them up again.

Closing as I suspect the community have other priorities at the moment, but of course anyone is welcome to reopen if needed.

**Comment by arthurrowland** [comment]
I have set it only to turn off at 9pm, but not back on in the morning, following a burn-in of the coffee on Sunday.

I assume the hot plate buttons had been depressed but appeared to be off to the person locking up since the LEDs wouldn't have been lit, then came back on in the morning and things kicked back in and burned out.

I will try and make the sonoff switch obvious to reduce risk of people getting confused in the morning.
