### ISSUE TITLE
Living Wage Accreditation

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1115]
As an ethical organisation, we already pay the national living wage to anyone (ie, me and the cleaner) that is paid by DoES.

With that in mind, would we be interested in becoming a Living Wage Accredited Company?

It's £60+VAT a year, and allows us to use the LW logo on our website, we'll get a plaque, and be listed on their site. It's very much a PR exercise rather than it making any real difference to us, as we would be the first co-working space in Liverpool listed on their website (and only the second listing nationwide to use the term makerspace).

Personally, I think it's worth doing if we can parlay it into some publicity, but if it's going to be kept quiet, we may as well keep the money.

**Comment by ajlennon** [comment]
Sounds awesome to me. There's also a Social Mobility Foundation "Social Mobility Employer Index" which seems like it might be of interest?

http://www.socialmobility.org.uk/index/

**Comment by DoESsean** [comment]
If there are no objections, I'll do this on Thursday. It just seems like something that we can actually make a big deal of, so I'll figure out how we can do that too.

**Comment by DoESsean** [comment]
Filled in the form for this today, so I imagine I have to wait to hear back.

**Comment by DoESsean** [comment]
This is all done, we're on the website and I've emailed @willcrobinson about how easy it is to get the logo put on our website.

They'll be sending us some swag in the next few weeks - stickers, pens, etc and an actual plaque to go on the wall, so that's nice. 

FYI, we are the first co-working space in Liverpool that is on their map of accredited companies, and only the second makerspace in the UK, so it's worth letting people know.
