### ISSUE TITLE
Add resources for room bookings

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1117]
it turns out GSuite can do resource calendars, so we can add Dinky and Events Room as resources which can then be invited to meetings like people can.

It seems like only people with an account in our domain are able to invite the room as a resource but external people can use the resource as a calendar, adding entries there. 

I’ll do this sometime when I get chance.

**Comment by DoESsean** [comment]
This will be really useful for someone like Ben, and also Duncan was asking
earlier how people go about booking meeting rooms, so being able to see
their availability more easily would definitely be helpful.

**Comment by ajlennon** [comment]
I have been thinking about this myself.

We did talk about meeting room usage that was covered by taking a desk at DoES versus larger "event" format usage which would be paid.

Could we clarify this a bit. I am finding I have one or sometimes two people coming in for chats. I (perhaps wrongly!) understand this would be covered by the existing payment but I would like to book a room in advance to make sure I have somewhere to sit with them.

Can somebody advise? Thanks!

**Comment by DoESsean** [comment]
I think you're right @ajlennon 

One or two people coming in for a bit is classed as a meeting and covered. I think there is something of a grey area as to the number of people which would no longer constitute a meeting, or the amount of time that the meeting would have to last before it became people working out of DoES for the day, but, as far as I'm aware and concerned, you wouldn't have started getting into those grey areas yet.

**Comment by ajlennon** [comment]
The Science Park have an online portal based room booking system where you can book in half hour segments. Can show that to you if you need any ideas

**Comment by ajlennon** [comment]
The Dinky room booking portal is very useful, thanks.

https://newdinky.youcanbook.me

One confusion though. It seems to block off half an hour before and half an hour after a booking is made. This seems a bit of a waste? Is it by design or should we change a configuration setting somewhere?

**Comment by johnmckerrell** [comment]
Yes looks like it was a setting, although interestingly it only added the required period to the calendar, the padding was entirely in the UI. I’ve removed that setting and it seems to work better.

FWIW this issue has gone completely off the original track which was largely a technical change in the way we manage the calendars.

**Comment by ajlennon** [comment]
Oh great. Thanks

**Comment by johnmckerrell** [comment]
I've done this now, there's resources for Dinky, Events Room and Main Room. I've gone through and tried to update relevant future entries but it's quite possible I've missed something. I've put some instructions here, probably need to edit the events page and possibly others.

https://github.com/DoESLiverpool/somebody-should/wiki/Booking-Rooms

**Comment by johnmckerrell** [comment]
For the record I did update the YouCanBook.me to point at the new resource calendar.
