### ISSUE TITLE
Reassemble the UoL telepresence robot and get it working

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1119]
I've borrowed a home-built telepresence robot from the UoL that was left behind a door for the last five years.  

I partially dismantled it to get the batteries out (to recharge) and the board with the computer on.  There were lots of wires connecting the boards.  (photos of the different connections are attached)

We need to plug the computer into the hard disk and run it to check that it still functions and what its features are.  

The code (based on ROS) is on github here:  https://github.com/smARTLab-liv/mitro

Then we need to make an assessment of whether it can be pressed into service, returned to the dept or broken down for parts.  

Alternatively, I am attempting to find someone who is willing to sell me a Double2 robot. which is proving quite difficult.

![photo_2019-04-28_11-21-25](https://user-images.githubusercontent.com/677254/56862947-408e4a80-69a8-11e9-8d4a-f25781b91992.jpg)
![photo_2019-04-28_11-21-19](https://user-images.githubusercontent.com/677254/56862948-4126e100-69a8-11e9-9902-6495aa07c1f2.jpg)
![photo_2019-04-28_11-21-13](https://user-images.githubusercontent.com/677254/56862949-4126e100-69a8-11e9-92c5-ffc41c1278f5.jpg)
![photo_2019-04-28_11-21-02](https://user-images.githubusercontent.com/677254/56862950-4126e100-69a8-11e9-9634-e8a522ad0151.jpg)
![photo_2019-04-28_11-20-43](https://user-images.githubusercontent.com/677254/56862951-4126e100-69a8-11e9-915b-52d8c5da1eb0.jpg)
![photo_2019-04-28_11-20-32](https://user-images.githubusercontent.com/677254/56862952-4126e100-69a8-11e9-84dd-4f7b9029292f.jpg)

**Comment by martimorta** [comment]
I am happy to help with at least with the ROS side of things!
I have seen the ROS packages were upgraded but not tested to the Hydro version and catkin, the second version of the compiler for ROS. Currently the versions used by most of the people are Indigo, Kinetic and Melodic. But this shouldn't be a problem as far as we can ssh into it!

**Comment by zarino** [comment]
@goatchurchprime Are you still planning on doing this? Or is the UoL robot obsolete now you’ve got the Double2?

**Comment by goatchurchprime** [comment]
Yep.  I'm trying to arrange returning the pieces to where it came from.  http://wordpress.csc.liv.ac.uk/smartlab/

**Comment by DoESsean** [comment]
Should this be closed now then?

**Comment by JackiePease** [comment]
This has been disassembled

**Comment by MatthewCroughan** [comment]
I was the one who disassembled and repurposed the hardware. I got permission from @goatchurchprime at the time who had bought the [wheeliepad](https://twitter.com/wheeliepad) and given up on this. I turned it into [this computer](https://github.com/DoESLiverpool/nixcfgs/tree/master/hosts/doesnix)

**Comment by zarino** [comment]
Oh cool! So _that’s_ what that computer’s for! I like the case!

**Comment by MatthewCroughan** [comment]
@zarino Thanks! I made it in Inkscape, and with Gerald!
