### ISSUE TITLE
The laser cutter coolant needs flushing and replacing

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#112]
While the last change of the water cleaned the pumps, tank and pipes, there is still some flotsam and jetsam in the laser tube water jackets. The current fresh water should flush the pipes, and we can then replace with a longer term coolant choice. 

To change coolant, we will need to buy:

 - [ ] De-ionised Water
 - [ ] Ethyl Glycol based anti-freeze/summer coolant
 - [ ] algae infibitor

**Comment by DoESsean** [comment]
Spent a fortune on new bits to avoid this happening anymore. Consider yourself closed!
