### ISSUE TITLE
Filament spool winder design. 

### ISSUE THREAD

**Issue by RussCoty** [DoESLiverpool/somebody-should#1120]
Create a winding device for unspooled filament.

**Comment by RussCoty** [comment]
Please delete if this is not the correct place.

There was a google thread on this but Github seems better for an open source design process.

So for the spool winder I’ve stared on a 3D laser cut box design. There’s a rough image here ![Image](https://i.imgur.com/qlAHM2j.jpg)

I’ve donated an arduino compatible board with a motor driver that I make. This will drive a motor for the spool and a motor linear pot to select position. Anyone who wants to join the project let me know. 

Should I host this in my own repo or here? Thoughts please.

**Comment by amcewen** [comment]
This is *so* the right place that there's already another issue discussing such a thing - #678 :-D

I've copied your comment over there, and we can close this as a duplicate...
