### ISSUE TITLE
The Liver Bird

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1122]
@MatthewCroughan and I were discussing last week how it would be great to do something with the Liver Bird. I brought this up with @amcewen today, and he agrees that, although it needs some TLC, it could definitely be repurposed to serve DoES.

At the moment, it monitors the Echo's social media, which isn't really of any use to us. Since there appears to be very little movement on it going back there (and any changes could be easily reverted if they want it), we should look to have it trawling our stuff instead.

If you have any ideas how it could be used, please let us know and we can work out which ones are a) viable, b) useful and c) doable.

So far, I'm thinking that a very simple change would be to make the newspaper flash when someone mentions us, possibly with different colours for different things (so red for a tweet mentioning @doesliverpool, for example, and blue for a #weeknotes post).

Another thing we could do is use it as a totaliser. For things like the laser pledge, we could have it filled from the bottom depending how much of our goal has been raised. Apparently this would also be pretty easy to do.

One other option would be as a weather forecaster - have it change colour depending on how the weather is expected to be in an hour, say.

**Comment by DoESsean** [comment]
As well as new usage, it would be really good to get it mounted on the wall. It would look so much better - more permanent and less like it's just been left on the side - if it was mounted, and would also free up the desk space that it's stood on.

**Comment by goatchurchprime** [comment]
Has this been authorized and decided a place where it could go?  My choice is right up to the close to the ceiling and move the clock out of the way onto another wall (eg above the free stuff).  
 
There's no obvious attachment points to hang it by.  (Maybe @magman2112 would have some ideas.)  

Then we could enabled the controller to some MQTT control rather than twitter control and start experimenting.

**Comment by DoESsean** [comment]
I would suggest that, in the absence of any complaints or other suggestions, we get this mounted. Putting it higher up and relocating the clock does seem to make some sense, we could then have some shelving below it (possibly for awards and such).

**Comment by MatthewCroughan** [comment]
Agreeing with Sean, we need to get this moved higher up in order to begin populating the wall with nice things!

**Comment by jackie1050** [comment]
Another option (if we could get electricity to it) might be to hang it on the wall outside Findout's room, if they were happy with that.

We did originally talk about having a mural there.
________________________________

**Comment by goatchurchprime** [comment]
Have purchased a pair of these brackets to go on the wall and hold the weight from underneath
    https://www.ebay.co.uk/itm/254015162875

Then we need to secure it from toppling forward from its perch.

**Comment by goatchurchprime** [comment]
Put up successfully with thanks from Nat and Niel. 

There's a bracket at the top holding it in with a small screw.  Easy to take out before lifting down from the supports, as we did several times till we worked out about the extra wire you need to plug in to make it work.
