### ISSUE TITLE
LED light failed in main space

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1123]
One of the LED lights in the main space has failed. There was a burning plastic smell and now the light is just flickering.

**Comment by jackie1050** [comment]
It is the light nearest to the laser cutter room.
I've spoken to Mick, the Tapestry electrician. He says it's safe to carry on using the other lights, and is coming in on Tuesday, so will arrange for the light to be replaced - it has a 2 year warranty and shouldn't have failed.
He will also discuss lighting requirements in general.

**Comment by jackie1050** [comment]
Jason commented that if there are any doubts or further burning smells then we should contact Mick again or leave the lights off.

**Comment by amcewen** [comment]
Mick has come in and replaced the broken light (with a different type - see https://github.com/DoESLiverpool/somebody-should/issues/808#issuecomment-494755289 for more detail)
