### ISSUE TITLE
Update our Twitter banner image

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1126]
So Jo Hinchliffe has just pointed out that the DoES Liverpool banner image on our Twitter profile (because it shows our laser-etched membership cards) features our old address :-)

We should change it to something more up to date

**Comment by DoESsean** [comment]
Probably something from the Gadget Show, for now at least.

**Comment by DoESsean** [comment]
I've done this, not a Gadget Show pic but something that will definitely suffice in lieu of someone finding something they prefer.
