### ISSUE TITLE
Threshold strip on main door may be loose

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1129]
The threshold strip on the main door may be loose, it seemed like it was stopping one of the doors from closing (the one furthest from the RFID reader) so I tried pushing it inwards, but the whole thing came off, so I tried pushing it down and that may have held. If it turns out to be problematic we should screw it in like we've done elsewhere.

**Comment by DoESsean** [comment]
There's no 'may' about it - the entire thing has kicked up numerous times today.

To be fair, it probably needs sticking down properly tonight as it's a legit trip hazard at this point.

**Comment by magman2112** [comment]
I’m planning to be in DoES on Tuesday. I will drill and screw this strip down, like we did near Matt’s desk, so that this will stay put hopefully.

**Comment by magman2112** [comment]
This has now been screwed down, so should hopefully not give any more concerns.
