### ISSUE TITLE
Gerald's Flow Sensor Is Not Working Consistently

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#113]
Follow up to closed issue #109 The flow sensor is not working properly. It is still plumbed into the Gerald system and was tested to confirm it does not restrict the water flow. It's not responding consistently to the flow however and may need replacing or further investigation. We have bypassed the switch so that Gerald is operational but people on the Big Laser will need to check coolant is flowing before cutting until it's fixed.

**Comment by cheapjack** [comment]
Might be worth noting that while the sensor is bypassed anyone monitoring/managing bookings with Gerald need to check that water is flowing ok on start and to make the person aware that it's a potential issue and any odd behaviour of firing/performance should trigger a check on the flow as a first step in troubleshooting. Thanks @DefProc for self assigning :+1:

**Comment by DefProc** [comment]
I've tested and reconnected the flow sensor. It is checks out as working now, but I'll monitor function as it gets used this week.
