### ISSUE TITLE
Construct new recycling bin boxes

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1137]
The recycling boxes we have are a bit short for the bags we have, i.e. when the box is full there's still plenty of capacity in the bag. The simplest thing to do would be to create new cardboard tubes that are just a bit taller but there might be more we can do. We need to make sure that the box isn't so big that when it is full you can't actually close the bag though. Issue #1136 talks about a wood recycling box which would be for the same bags but need to be stronger.

**Comment by ajlennon** [comment]
Is the bin outside still there for cardboard? Are we allowed to put cardboard in it? The box in the kitchen always seems to be full and I'm wondering if we could do something about taking boxes and such out the back?

**Comment by johnmckerrell** [comment]
The grey wheelie bin is ours and we can put stuff in it but it only really holds two plastic bags worth. The box in the kitchen is always full because nobody empties it. It’s currently not totally full, probably 80-90% although I’ve got a box I can use to tip it over.

**Comment by ajlennon** [comment]
OK so box in kitchen can go in green wheelie bin? Good to know. I'll try to help emptying it. 

Do you think it would help us to have a label on it "When full empty in green wheelie bin" or some such as I didn't know

**Comment by johnmckerrell** [comment]
Signage would definitely need to read GREY wheelie bin. Wiki actually has some instructions around this. It’s barely worth mentioning the wheelie bin as it holds so little, other than that it just needs to be stored on the racking by the toilets for now.

**Comment by ajlennon** [comment]
Grey. Got it. That's for recycling though is it?

**Comment by johnmckerrell** [comment]
Yes, I just tried to put something in though and it was full so have put that bag on the racking. We're a week away from our next collection but as we're mostly on empty bags we should be ok (although we filled a bag with wood just over the weekend!)

**Comment by johnmckerrell** [comment]
Aforementioned wiki page is https://github.com/DoESLiverpool/somebody-should/wiki/Waste,-recycling-and-cleaning-up

**Comment by johnmckerrell** [comment]
I notice we've got two more A4 clip frames. Not that this issue was about signage but if someone did make a sign mounting it in a frame would be preferable!

**Comment by johnmckerrell** [comment]
If we construct new boxes we could also put some in the events room too.

**Comment by johnmckerrell** [comment]
Existing boxes are 315x415 mm. 510mm high. I reckon we could go up to 800mm.

**Comment by amcewen** [comment]
We don't have any recycling any more :cry:
