### ISSUE TITLE
Replace the Old TV in DoES with my TV

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1138]
https://www.philips.co.uk/c-p/43PUS6401_12/6000-series-4k-ultra-slim-tv-powered-by-android-tvtm-with-ambilight-2-sided-and-pixel-plus-ultra-hd 

I've got one of these and no longer have anywhere to put it, but would like to see it used in DoES, especially for graphs and calendars, IoT stuff, etc. Can we arrange this?

**Comment by ajlennon** [comment]
Shall we close this?

**Comment by MatthewCroughan** [comment]
Yup, it's all set up. I'm going to open up a new issue relating to games, consoles, fun and entertainment on the maintain TV.

**Comment by MatthewCroughan** [comment]
![JPEG_20190527_230610](https://user-images.githubusercontent.com/26458780/58766067-5926ed00-8572-11e9-82dd-e152a0135cf9.jpg)
