### ISSUE TITLE
Does @cheapjack need to be set as a contributor to somebody-should?

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#114]
Think I need someone to make me a contributor so I can label and re-open the recent Gerald issues correctly #113 and #109 ta

**Comment by osfameron** [comment]
I've invited you now.

**Comment by amcewen** [comment]
Ah, that'll be why he was already invited when I went to do it :-)

**Comment by cheapjack** [comment]
ta! will label :)
