### ISSUE TITLE
Critical Thinking Posters

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1140]
Hi all,

I've taken the liberty of white-tacking up a couple of my favourite critical thinking posters in the accessible toilet. 

Just to add a little je ne sais quoi to those cogitative moments....

I hope they are of interest and viewed as welcome. If not let me know and I'll take them down! 

(Hopefully we can find a place worthy of them though as I do think they are rather good)

![image](https://user-images.githubusercontent.com/1537834/58331614-6b49b280-7e31-11e9-9506-588ea0cd92e0.png)

![image](https://user-images.githubusercontent.com/1537834/58331621-6e44a300-7e31-11e9-9e07-3573ad9926c2.png)

**Comment by ajlennon** [comment]
What do you think @johnmckerrell ?

**Comment by Robotorium** [comment]
Have you got digital copies of these? I can't quite read the second one.

Op vr 24 mei 2019 14:38 schreef Alex Lennon <notifications@github.com>:

**Comment by ajlennon** [comment]
Yup they are from these guys - https://yourlogicalfallacyis.com/

**Comment by johnmckerrell** [comment]
Not up to me @ajlennon

**Comment by MatthewCroughan** [comment]
@ajlennon Shall we close this now?
