### ISSUE TITLE
No audio on the handset on the phone in the Events Space

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1145]
The phone in the events space seems to mostly work, but there's no dialtone when you lift the receiver, and when you answer the door you can't hear the people downstairs.

It doesn't seem to be a problem with *all* the handset audio, as I got it to beep at me a few times while poking round with menu items to try to fix it.

**Comment by amcewen** [comment]
I've saved a copy of [the manual for the phones](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/Manuals/sipt20p.pdf) into `somewhere-safe`, and we should have a play with the handset to try things out when there isn't a meetup taking place (like there is at the moment)

**Comment by johnmckerrell** [comment]
This all seems fine at the moment. I wonder if it was defaulting to line 2 and now I've set it up with a second line that means it does stuff.
