### ISSUE TITLE
Felicity not working

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1146]
When I arrived, Felicity was in the middle of a failed print. There were lots of frizzy bits of filament.
I tried to change the filament. It looks as though there may be lots of the previous filament stuck in the nozzle - while some of this melted, I wasn't able to get the new filament to extrude, despite doing a couple of cold pulls.
Probably not a serious issue, but I don't have any more time to spend on it tonight

**Comment by johnmckerrell** [comment]
I don’t know if someone else tried kicking it off later but this failed for the first time around 4pm. I managed to clean the failed print off and manually extrude and start it off and it seemed like it was doing the raft ok but failed soon after. I then did a quick clean and restarted again but didn’t check up on it. 

--

**Comment by amcewen** [comment]
It had failed before I left last night and was moving a mess of plastic around at the time, so might need a bit more disassembly and cleaning?

**Comment by jackie1050** [comment]
@MatthewCroughan unblocked the nozzle using a pin.
There seemed to have been further problems on Makernight with a suggestion that someone might have changed the nozzle?
Prints on Friday and over the weekend were successful so seems ok now.
