### ISSUE TITLE
Information about the events space missing from front page

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1147]
The page here lists "Meeting Rooms" but does not mention the event space https://doesliverpool.com/

It is also not photographed or mentioned on the "Take a tour" section further down -- where anyway you cannot take any sort of tour, so I don't know why it says such a thing.

Event space hiring also missing from the price list:   https://doesliverpool.com/services/

There is this page here, but you have to know exactly how to find it:
    https://doesliverpool.com/host-your-own-events/

It does at least quote a price.  Maybe that price ought to be moved off of there into the single price list page.

**Comment by MatthewCroughan** [comment]
It should also mention the fact that can offer free usage of the space, providing that entry is free, something which is probably far more exciting to a lot of people than you'd think, and that only a few people are utilizing at present.

**Comment by DoESsean** [comment]
I've added the Host Your Own Events page to the Services menu, and emailed @willcrobinson about the other changes, as they seem like things that will be very quick for someone who knows what they're doing, and an absolute pain for someone who doesn't.

**Comment by magman2112** [comment]
Should the room booking system for Dinky be added to the web site as well?

**Comment by johnmckerrell** [comment]
We’ve mostly not done that as it wasn’t flexible enough and we wanted more control. Might be worth tweaking you can book me though.  

--

**Comment by willcrobinson** [comment]
Removed the "Take a tour" text, added a section for the events space and linked to the page mentioned by @goatchurchprime
