### ISSUE TITLE
Make a Big Red LED display

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1148]
I've decided to make a Big Red LED display for fun. This probably overlaps with #1142 somewhere.

Not entirely sure why I'm doing it or what to do with it but maybe it's something we could take along to events and have "interesting things" going on it.

It also links in with my interest in getting some OpenSource software going on FPGAs as people seem to be driving these kinds of display from FPGAs and it seems like a good Hello World example for me to try.

In the initial incarnation it's more likely to be driven from an ESP32 or a RPi.

So it's going to be based on these 4 x 8x8 LED segments

https://www.gearbest.com/other-accessories/pp_1257191.html?wid=1433363

- I have 75 on the way and each of them has four 8x8 segments.

- I'm starting with a 4:3 aspect ratio so that should give me a 160 x 120 pixel display

-  So that should be 20 x 15 8x8 displays. Each one is 2cm square so 40cm x 30cm (sort of A3 size?)

All ideas on what interesting stuff we can put on this much appreciated...

**Comment by ajlennon** [comment]
I could also do with advice on the best way of connecting them together and mounting them so the configuration is strong but can be moved about without damaging it

**Comment by amcewen** [comment]
Given nothing has happened on this since @zarino suggested it had been superseded, I'm agreeing and closing this.
