### ISSUE TITLE
Event room doorbot didn’t work

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1149]
Doorbot1 was not working this morning, @zarino tried SSHing in but it wouldn't connect. Ended up needing a power cycle.

**Comment by johnmckerrell** [comment]
Only thing in `/var/log/messages` is:

```
Jun  6 06:20:02 doorbot1 rsyslogd-2007: action 'action 17' suspended, next retry is Thu Jun  6 06:21:32 2019 [try http://www.rsyslog.com/e/2007 ]
Jun  6 06:25:01 doorbot1 rsyslogd-2007: action 'action 17' suspended, next retry is Thu Jun  6 06:26:31 2019 [try http://www.rsyslog.com/e/2007 ]
Jun  6 06:25:11 doorbot1 rsyslogd: [origin software="rsyslogd" swVersion="8.4.2" x-pid="373" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Jun  6 06:30:01 doorbot1 rsyslogd0: action 'action 17' resumed (module 'builtin:ompipe') [try http://www.rsyslog.com/e/0 ]
Jun  6 06:30:01 doorbot1 rsyslogd-2359: action 'action 17' resumed (module 'builtin:ompipe') [try http://www.rsyslog.com/e/2359 ]
Jun  6 08:17:12 doorbot1 rsyslogd: [origin software="rsyslogd" swVersion="8.4.2" x-pid="372" x-info="http://www.rsyslog.com"] start
```

But that seems to have been going on for a while, might be worth solving anyway, something is mentioned here:

https://www.rsyslog.com/rsyslog-error-2007/

Actually I've done that now, removed the last block of config from that file, should move that change into Ansible if it works.

The `messages` log suggests the problem occurred at 6:30 but the `syslog` shows the machine did continue running until it was rebooted.

**Comment by zarino** [comment]
Don’t know whether it’s related, but this morning I was unable to open the main workshop door (doorbot2).

Swiping the fob illuminated the red LED on the reader, but the maglock didn’t unlock.

I SSHed in and took a look at `/var/log/messages` but all it contained were lots of "voltage normalised" lines:

```
pi@doorbot2:~ $ tail /var/log/messages
Jun  9 08:50:23 doorbot2 kernel: [76759.765603] Voltage normalised (0x00000000)
Jun  9 08:56:25 doorbot2 kernel: [77121.682281] Voltage normalised (0x00000000)
Jun  9 09:02:27 doorbot2 kernel: [77483.599634] Voltage normalised (0x00000000)
Jun  9 09:02:44 doorbot2 kernel: [77500.239775] Voltage normalised (0x00000000)
Jun  9 09:07:20 doorbot2 kernel: [77776.877704] Voltage normalised (0x00000000)
Jun  9 09:08:31 doorbot2 kernel: [77847.597255] Voltage normalised (0x00000000)
Jun  9 09:14:22 doorbot2 kernel: [78199.115108] Voltage normalised (0x00000000)
Jun  9 09:17:09 doorbot2 kernel: [78365.514128] Voltage normalised (0x00000000)
Jun  9 09:19:49 doorbot2 kernel: [78525.673164] Voltage normalised (0x00000000)
Jun  9 09:21:18 doorbot2 kernel: [78615.112681] Voltage normalised (0x00000000)
```

SSH access and the door opener script both worked fine, so it’s not like the whole Pi had locked up.

**Comment by johnmckerrell** [comment]
I think this is actually #1139, can you confirm you just had issues with the main room not the events room today? I think the fob reader just took a while to come back on as I see someone has made it in since?

**Comment by johnmckerrell** [comment]
As these were separate issues I've renamed this one back to only talk about the events room. I'm going to close this for now, the messages log looks quieter, can reopen if we see the issue again.
