### ISSUE TITLE
The UP printer's fan is missing a blade

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#115]
While unblocking the extruder recently I managed to catch the fan on it with a screwdriver while it was spinning.  That's broken one of the blades on it, which has made it noisier and introduced some vibration into it.

It'd be good to replace the fan sometime (or maybe we should just snap a blade off the other side to balance it out? :-)

**Comment by amcewen** [comment]
Given that Rose is currently broken (see issue #138), I've swapped the fans over between Rose and Violet, so Violet's fan is now fine, but Rose's is faulty.

**Comment by DefProc** [comment]
I've ordered a new 12V 40mm fan. 

It looks like the only difference to the original is the Up uses a 3-way connector, with the centre pin missing. We can just splice the new fan wires to the old connector wires if I have any trouble swapping the connector housings.

**Comment by DefProc** [comment]
The connector on the new one is smaller, so they are currently both hidden where I left them in the workshop. (the 3D printer box is a good starting point in your search)

**Comment by DoESsean** [comment]
Was this fixed or is it still waiting to be changed?

**Comment by goatchurchprime** [comment]
We got worse problems than this to deal with
