### ISSUE TITLE
Buy more kapton tape

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1150]
We're out of kapton (heatproof) tape for use with the mug press.

**Comment by DoESsean** [comment]
Ordered this, it should be with us tomorrow.

[https://www.amazon.co.uk/Roll-10m-High-Temp-Tapes/dp/B07LGX6YYM/ref=sr_1_3?keywords=kapton+tape&qid=1560249659&s=lighting&sr=8-3](url)

**Comment by amcewen** [comment]
Arrived and now in the tape drawer.
