### ISSUE TITLE
Calendar bookings not working temporarily

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1156]
It looks like Google Calendars has an issue which is causing YouCanBook.Me to have issues too.

**Comment by johnmckerrell** [comment]
https://www.google.com/appsstatus#hl=en&v=issue&sid=2&iid=cc21ebe3962430b2e4ae2b52e3dde98f

**Comment by amcewen** [comment]
When it's back it would be good to block out Sophia as busy until #1143 gets fixed :-/

**Comment by johnmckerrell** [comment]
I've done that until end of day Thursday already (well I think I have).

**Comment by johnmckerrell** [comment]
Now fixed, I've also blocked Sophie out until the end of next week.
