### ISSUE TITLE
Signs of recent fire on Gerald, but no one had reported it.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1157]
I was in DoES on Thursday when one of the people who had booked Gerald for the morning was having some issues. 

It turned out that there had been a fire in Gerald which had damaged the X-axis belt.

Luckily we had some spare belt, so I could replace the damaged one, but the key issue was that it was not reported, so it was just a matter of time before the belt broke, putting Gerald out of action. The machine also had to be cleaned as there was a lot of debris, dust and melted acrylic on the bed (though some had been cleaned away) as a consequence of the fire.

If @DoESsean can possibly send an email to people who have booked the laser in the last week, we can then ask people to report the issue should it happen in the future. This is not to point fingers, as fires are a common risk with laser cutters, just to report when it does happen again, so that we can keep Gerald working as best as possible.

We also still have sufficient belt in stock to replace any one belt one more time.
@DoESLiverpool/laser-maintenance 

I will leave this issue open for a short while, as the new belt will need to be re-tensioned in a few days.

**Comment by johnmckerrell** [comment]
"one belt one more time" I say let's buy more now :-)

**Comment by magman2112** [comment]
I brought up this issue in the community meeting on Thursday evening.

We have now agreed that cleaning the laser bed after use should be part of the laser induction and that was brought into effect later the same evening.

We also need to add some signage to advise people to please clean the laser bed after use.

**Comment by seanspotatobusiness** [comment]
Is the laser bed the grating that the work piece rests upon or the area
underneath that grating?

**Comment by DuncReid** [comment]
The 'how' of getting to the bed wasn't covered in the induction I did about a month ago but it's in the Wiki. I suspect folk may be overly worried about disturbing calibrations or causing damage and that triggers the 'don't bother, someone else's problem' subroutine.

If a more experienced laser user wants to demonstrate the process, I'll happily video it (quick & dirty phone filming :) ), fling it on YouTube and it can be linked from the Wiki?

**Comment by jackie1050** [comment]
Hi Dunc

That's a good idea. Are you around on Makernight? That could be a good time.

Jackie


On 25 Jun 2019 07:49, Dunc Reid <notifications@github.com> wrote:

The 'how' of getting to the bed wasn't covered in the induction I did about a month ago but it's in the Wiki. I suspect folk may be overly worried about disturbing calibrations or causing damage and that triggers the 'don't bother, someone else's problem' subroutine.

If a more experienced laser user wants to demonstrate the process, I'll happily video it (quick & dirty phone filming :) ), fling it on YouTube and it can be linked from the Wiki?

**Comment by DuncReid** [comment]
Sadly not.

In today (if I can get parked.. grrr!!) and tomorrow am.


On 25 Jun 2019, at 08:37, Jackie Pease <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Dunc

That's a good idea. Are you around on Makernight? That could be a good time.

Jackie


On 25 Jun 2019 07:49, Dunc Reid <notifications@github.com<mailto:notifications@github.com>> wrote:

The 'how' of getting to the bed wasn't covered in the induction I did about a month ago but it's in the Wiki. I suspect folk may be overly worried about disturbing calibrations or causing damage and that triggers the 'don't bother, someone else's problem' subroutine.

If a more experienced laser user wants to demonstrate the process, I'll happily video it (quick & dirty phone filming :) ), fling it on YouTube and it can be linked from the Wiki?

**Comment by jackie1050** [comment]
Hope you got parked.

Probably best to just ask around then - I'm sure there'll be someone there today who can show you how to clear out Gerald.

**Comment by magman2112** [comment]
Closing this issue for now - as we don’t really need to keep this open.
