### ISSUE TITLE
Gerald PC crashing and USB extension lead needs replacing.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1158]
Steve had an issue on Thursday afternoon with the Lasercut software reporting a crash in the printer driver.

After a lot of head scratching, the fault was identified as a bad USB extension lead. Obviously taping it to the floor was not an ideal solution. It also appears that there have been similar issues for about a week, but it just terminally failed on Thursday.

I found a temporary replacement USB extension lead in the AV cables draw and used a cable guard to install this in the laser room, but I think we should ideally have a buffered lead for this installation, given the electrical noise around Gerald and the fan motors.

I also had two blue screen crashes with Geralds PC during Maker Night. These could possibly be related to the very long USB lead for Gerald, as it was the Lasercut software that was running when the PC crashed (I suspect the driver is old and a bit buggy).

This will likely need a bit of monitoring until a replacement buffered USB extension is bought and fitted. But we may also need to repair or replace Gerald’s PC, should this be developing a fault.

**Comment by chris-does** [comment]
@magman2112 If you can let me know the the total (cable routed, rather than straight line) distance between the Gerald PC and the target peripheral (laser cutter I presume); I will provide a buffered USB lead for the whole length.
Please also specify USB A / USB B & Male / Female connections for both the Gerald PC end (I presume USB A Male) and the peripheral end.
Lastly, if you can let me know where to deposit the cable, I shall place it there accordingly.

**Comment by magman2112** [comment]
Hi Chris, sorry for not replying earlier.

We can get away with 3m cable, but I think it would be better with a slightly longer cable, say 4 or 5m, as this would allow us to use a shorter cable from the active end to the laser cutter port.

**Comment by chris-does** [comment]
>Hi Chris, sorry for not replying earlier. ...

@magman2112 No apologies required! 

I shall bring a 5m cable with me when I am next in, likely Thursday 15th August if not before (alas I had already departed for DoES today when I saw your reply).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chris-does** [comment]
### Installed 1x [UGREEN USB 3.0 Active Extension Cable USB Repeater Cable 5m](https://www.ugreen.com/product/UGREEN_USB_Active_Extension_Cable_USB_Repeater_Cable-en.html).

With the assistance of @magman2112 , on Thursday 15th August 2019 a [UGREEN USB 3.0 Active Extension Cable USB Repeater Cable Extender with Signal Amplifier Type A Male to Female Cord Superspeed 15 Feet/5M](https://www.ugreen.com/product/UGREEN_USB_Active_Extension_Cable_USB_Repeater_Cable-en.html) was installed between [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) and [LaserCutterGerald](https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutterGerald).

This new cable was tested and all appears to be working as it should.

The additional power connector (for signal boosting) at the [LaserCutterGerald](https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutterGerald) end of the cable has not been made use of at this time. If signal drop-out is experienced in the future, then this can be made use of as a first step to return to service.

The missing USB and motherboard drivers for [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) were also installed and updated - this may/may not have had a beneficial effect; though the warning icons in Device Manager are certainly no more! :-)

The cable that was originally running between  [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) and [LaserCutterGerald](https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutterGerald) has been placed in the USB cable rack located above and to the left of the [Electronics Equipment](https://github.com/DoESLiverpool/somebody-should/wiki/Electronics-Equipment)

![USB](https://user-images.githubusercontent.com/52704101/63218672-6148fe80-c157-11e9-80dd-53e1158f220a.jpg)
