### ISSUE TITLE
Printz Adam making a graunching noise when moving the printhead around

### ISSUE THREAD

**Issue by keepease** [DoESLiverpool/somebody-should#1159]
Suggestion at maker night was that the top rails might need greasing, but there seemed to be uncertainty.

Recommendation from Ultimaker is to use a light machine oil e.g. sewing machine oil
https://ultimaker.com/en/resources/23130-lubricate-the-axles

**Comment by jackie1050** [comment]
That was me using another user ID

**Comment by amcewen** [comment]
I put a few drops of 3-in-1 oil on the rails a few days back, which has made it better, but I'm not sure it's fully done.

**Comment by jackie1050** [comment]
Sounding worse now. There is a noise as if caused by worn bearings, or part of the toothed belt rubbing against something. The print quality seems poor too, so as it's late I've switched the printer off and will look again tomorrow evening.

**Comment by jackie1050** [comment]
Still having problems. On a couple of occasions yesterday the filament stopped extruding mid print (once with light grey and once with clear PLA).
Today I did 3 cold pulls and material appeared to be coming through, but when I started a print only a limited amount of material was extruded.

- [ ] Do we need a new 0.4mm nozzle? I was going to try one of @ajlennon 's but the threaded part is shorter and I wasn't sure whether this would be an issue
- [ ] The Bowden tube is in a bad state and appears splayed at the nozzle end. @amcewen says there could be some spare tubing from when it was last replaced - we should look for that
- [ ] There are no clips now where the tubing attaches to the hot end - did someone decide they weren't useful?

**Comment by jackie1050** [comment]
Another part which we should look at replacing is the coupler. This is a consumable item that hasn't been replaced recently and is apparently a common cause of under-extrusion: https://ultimaker.com/en/resources/21477-how-to-fix-under-extrusion

**Comment by jackie1050** [comment]
Related issue #283

**Comment by amcewen** [comment]
Both printers are now sounding much better after @Sean-anotherone spent an evening lubricating everything.

I've spun the "Prints Adam not printing nicely" problem out separately as #1191.
