### ISSUE TITLE
Fix the dripping tap on right hand sink in kitchen

### ISSUE THREAD

**Issue by Helen-8** [DoESLiverpool/somebody-should#1160]
It may just need something tightening inside it. It gets worse just after it's been used but then dies off after a while I think. Afraid that's the fullness of my plumbing knowledge but happy to help if I can!

**Comment by johnmckerrell** [comment]
On Monday (15th) it was making a high pitched whistling. I took the head off the tap but what's underneath seems quite impenetrable. There's a bit that would take a spanner and I had a go at it but it wouldn't move in either direction. I could be wrong but it seems like potentially we would need a new tap rather than just being able to replace a washer or something similar. Unfortunately there's no isolators on these pipes (would be good to fit some if we do replace the tap!)

**Comment by johnmckerrell** [comment]
Yesterday Mohny had a look and managed to loosen the spanner bit but that then seemed to fix the drip so we've done no more. I'll close this actually, at least if it comes back we can replace the part from screw fix easier now that it's loosened.

**Comment by johnmckerrell** [comment]
It didn't fix it.

**Comment by johnmckerrell** [comment]
So I removed the valve and took it up to Screwfix, the guy there wasn't sure and sent me to Plumbase, the guy there told me they didn't have any but it would be solvable. We need to take it apart, remove the rubber bits from the innermost bit, "put it all in a cup of full fat coke overnight" then put it back together. If that fails York & Young on Smithdown Road should be able to help. For the record it's a quarter turn one.

**Comment by johnmckerrell** [comment]
I really struggled to unscrew the screw holding the tap cover off, I was nearly giving up but a small blue Stanley screwdriver eventually did the trick, including a photo in case it's useful in the future.

![2019-09-30 13 54 23](https://user-images.githubusercontent.com/27243/65896376-0127b800-e3a5-11e9-93c5-5406f5d630c3.jpg)

**Comment by jackie1050** [comment]
The left hand tap is also leaking. We should try to buy all the parts at once.

**Comment by johnmckerrell** [comment]
Missing part of the story is that I didn’t do the coke trick, just put it back together and that fixed it for a few weeks (or maybe days).

**Comment by amcewen** [comment]
@jackie1050 and I have dismantled all four taps and left them soaking in coke.  We didn't remove any of the spring clips on the ones which still have their spring clips.

I couldn't find the screwdriver @johnmckerrell photographed above, but found that one of the hex-screwdriver bits labelled PZ1 did the trick.

**Comment by jackie1050** [comment]
I tried to buy spring clips. Most plumbing supply shops don't seem to be open until Monday. Screwfix don't supply tap inserts of the correct size. Tool Station only sell complete taps.
There aren't that many people around today, so will leave until tomorrow when someone has a car.

**Comment by magman2112** [comment]
One of the taps was still leaking after the attempted fix with coke.

A trip to B&Q obtained a pair of tap inserts, fitting one on the cold side fixed the drip.

The spare tap insert will be stored in the screws draw near the vinyl cutters.

**Comment by johnmckerrell** [comment]
Re-opening this as the tap on the left is leaking again. TBH I thought it had been leaking all along so glad to hear this was fixed for a while! Hopefully we still have the spare tap insert mentioned in the previous comment and can fit it to fix the problem.

**Comment by magman2112** [comment]
I dug out the spare cartridge from the Nuts & Bolts draw. I will try and fit it later when DoES is a little less busy. 

For the record, the insert is "Quarter Turn 1/2" tap gland, 8mm spline, 20 teeth".

Mike Rush tried to replace the insert with one he brought with him at the last Repair Cafe, but his had the wrong spline type for taps. He did identify though that it was the hot tap which was leaking, which is good as this is the spare we have.

**Comment by goatchurchprime** [comment]
This was driving me nuts for two weeks.  

I found the cold water isolation valve behind the fridge, which is very difficult as the slot head is very worn out.  The hot water isolation is easier just on the tank.

First I capped off the two incoming water plastic pipes with blanking plugs, so things couldn't be any worse.

Then I discovered I had a spare hot water tap at home whose mechanism matched the cold water one in the sink.  I replaced it and it no longer leaks.  However the two taps now both go clockwise, but who cares?

**Comment by johnmckerrell** [comment]
Alas the tap on the right is now dripping! Sounds like the spare that @magman2112 was aware of is still around?

**Comment by magman2112** [comment]
It appears we need to pay more attention to the title perhaps, as the sink @goatchurchprime and I have been working on is the left hand one.

The spare insert we had (it was in the screws and nuts draw) has already been fitted to the left hand sink and Julian has fitted a hot insert in the cold side of the left hand sink.

So it comes back to buying some new inserts again, which I got from B&Q last time. I suggest it’s worth getting two sets, so the left hand sink has the correct rotation for its side. I will look to pick some of these up in the next few days.

**Comment by johnmckerrell** [comment]
Oh you definitely fixed the correct tap last time (or somebody did), just that the right one has started dripping again now!--Sent from my mobile phone hence brevity and errorsOn 21 Nov 2022, at 21:10, Mike Gorman ***@***.***> wrote:﻿
It appears we need to pay more attention to the title perhaps, as the sink @goatchurchprime and I have been working on is the left hand one.
The spare insert we had (it was in the screws and nuts draw) has already been fitted to the left hand sink and Julian has fitted a hot insert in the cold side of the left hand sink.
So it comes back to buying some new inserts again, which I got from B&Q last time. I suggest it’s worth getting two sets, so the left hand sink has the correct rotation for its side. I will look to pick some of these up in the next few days.

**Comment by johnmckerrell** [comment]
Two more pairs of inserts bought from Screwfix and left on Seán's desk today. I got these:

https://www.screwfix.com/p/flomasta-1-2-bsp-quarter-turn-ceramic-tap-glands-pack/2611f

FLOMASTA 1/2" BSP QUARTER TURN CERAMIC TAP GLANDS PACK

**Comment by johnmckerrell** [comment]
I was having a look today and noted that the hot water tank has isolators on the input and output, and given the tap that is leaking is the hot water tap that might help. Actually now I notice Julian already mention that, oh well. Looking in the more accessible loo there's some isolators there which may isolate the kitchen so if the kitchen one is difficult to use it might be worth trying the one in the bathroom. Also, for reference, the stop cock is in the corner of room 29 nearest the door.

**Comment by johnmckerrell** [comment]
James Sparrow has now replaced all of the tap valves, given we had them and a few needed doing. No more drips!
