### ISSUE TITLE
Need to buy more nitryl gloves

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1162]
Whoever cleared out the last of the nitryl gloves didn't reorder any :-(

We should get some in so that the *next* person looking for some can find some.

**Comment by chris-does** [comment]
@amcewen Is there a preferred supplier / brand / size / colour for these gloves or will "any" (of suitable quality) suffice?

If there are no fixed standards, I will be able to provide a box (or two).

**Comment by amcewen** [comment]
@chris-does There's no preferred brand/supplier, however I *think* I remember some arriving recently, which probably means that @DoESsean (IIRC) has done the work but not tidied up the paperwork :-D

I'll try to remember to check next time I'm in, but that won't be till Thursday evening.  Maybe someone else in the space can look in the correct grey drawer and confirm/deny...

**Comment by amcewen** [comment]
P.S. I don't know if you're on the Google Group @chris-does and have seen https://groups.google.com/forum/#!topic/does-liverpool/gWkEeyyvTb0 but in case not, it'd be nice to see you on Friday if you (or anyone else reading this) can make it...

**Comment by DoESsean** [comment]
Yes!

They're here and in the drawer.

**Comment by chris-does** [comment]
@DoESsean Grand - one less thing for me to carry when I head in today :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
