### ISSUE TITLE
Get new hoses for the extraction on both laser-cutters

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1165]
Given it looks like it might be a while yet before #5 gets closed, and that both extraction hoses barely reach out of the window at present, I think we should get some new hoses as an interim measure.

**Comment by amcewen** [comment]
Sophia has a 4" hose, and will need at least 6' to reach out of the window.  Gerald has a 6" hose and we'll need 9' to get out of the window.  A bit longer would be good for both of them.

I've ordered 5m of 100mm (4") and 5m of 150mm (6") of [this aluminium-lined PVC tubing](https://www.ebay.co.uk/itm/Combi-Ducting-5M-White-PVC-Flexiable-Air-Extractor-Ventilation-Duct-Hydroponics/262583851155?hash=item3d23379893:m:mrHNclAiPxjSEDXtbQV-1Ew&var=561460629303).

I've also ordered a [pack of 5 120mm](http://www.ebay.co.uk/itm/282014972437) and [one 175mm](http://www.ebay.co.uk/itm/392235506153) jubilee clips, so we can fix the hoses on better than just taping them.

**Comment by amcewen** [comment]
The hoses and jubilee clips have all arrived.  I've stuck them on the bottom shelf of the laser-spares cupboard (the hoses are wrapped in a black plastic bag)

**Comment by Sean-anotherone** [comment]
Sophia's exhaust is replumbed successfully.

**Comment by amcewen** [comment]
@Sean-anotherone got Gerald's done too.
