### ISSUE TITLE
Fix downlighting on DoES tower

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1168]
The DoES tower downlighting used to respond to tweets to @doestower by changing colour etc.
Somebody should get it to do this again, perhaps using an ESP instead of an Arduino.

**Comment by amcewen** [comment]
Currently it's got an Arduino Uno with a WiFi shield, and uses the code at https://github.com/brett-lempereur/beaconbot

That expects there to be a companion Raspberry Pi, which monitors twitter to respond to mentions of @DoESTower, and set the colours plus can take a photo with camera connected to the Pi and reply to whoever asks for a new colour with a photo showing it updated.  

It might make sense to have it respond to the #cheerlights hashtag instead?  Then we wouldn't need to have a Pi (that we haven't taken along with the tower to any events for a while now...).  There's an [MQTT feed for #cheerlights](https://cheerlights.com/cheerlights-now-supports-mqtt/) (I don't know how many colours that supports, or if there's a different one that copes with all the CSS colours...)

(If we switched to an ESP8266, then we could add https://github.com/tzapu/WiFiManager to let us configure new WiFi networks more easily when it's out at events)

**Comment by amcewen** [comment]
It feels like we should upgrade this to run on [WLED](https://github.com/Aircoookie/WLED/), then it could be added to the stuff controlled via MQTT or #1269.  We can set up different segments in it for the downlights and the ones behind the letters...

**Comment by amcewen** [comment]
It's been running on a My Baby's Got LED board (so ESP8266 with WLED) for a while now.
