### ISSUE TITLE
Do we need more calipers?

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1169]
We seem to only have a single pair of calipers left, which luckily I'd spotted buried under some stuff on Alex's desk.

We have 3 cases for calipers in the calipers drawer.

How do we get to a point where people return equipment to where it should live so others can find it?
Should I relabel the calipers drawer as the "calipers cases" drawer?
If we buy more calipers, how we will know we'll still have any sets in six months?

**Comment by Sean-anotherone** [comment]
Not guilty - although I do use them regularly.  I can only recall ever seeing one set, despite there being three boxes.

I would suggest that more are needed, but I would wait until they are in stock in ALDI / LIDL so they cost <£10, rather than paying the silly prices they can attract elsewhere.

**Comment by Thingomy** [comment]
>How do we get to a point where people
>return equipment to where it should live
>so others can find it?

I've come to the conclusion, after many years of studying the human
condition, that the only way to achieve this is to get rid of all the
people. I for one welcome our incoming robot overlords...

On a more relevent note, can I request some of them be actual vernier
calipers? The lack of reliance on batteries is helpful.

JR

**Comment by chris-does** [comment]
I can provide a, @Thingomy non battery dependent, pair of vernier calipers.

I shall bring them with me next time I am in (likely Thursday 25th July if not before).

@amcewen with regards to the tracking of / ensuring the return of tools in general, would a tracking (BLE or RFID based) system be deemed too cumbersome / excessive? 
Could this aspect (the tracking) be addressed as part of #360 and #362 - or, indeed, perhaps combine #360 and #362 (closing them) and create a new "Inventory Management Mission"?

**Comment by chris-does** [comment]
### Provided a pair of vernier calipers



New pair of manual/analogue (non battery dependent) vernier calipers, supplied in their own black case, added to the Calipers draw.



Will add the above aspect relating to tools tracking in general to both #360 and #362 enabling a "clean close" of this issue.

**Comment by norru** [comment]
> How do we get to a point where people return equipment to where it should live so others can find it?

Idea. "Checklist" poster on the door to be seen by anyone on their way out. Akin to "have you washed your hands?" on the door of public toilets.

"We hope you enjoyed DoES. Make sure anybody does!
Did you
- clean up after yourself? [x]
- placed all tools you used in ty [x]
- yadda
- yadda
"

Cute stuff on the poster (e.g. kittens, hamsters, puppies, goats) will extend the attention span of the viewer.
