### ISSUE TITLE
We need some new polythene boxes for the workshop shelves

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1172]
There don't seem to be any empty boxes for new members at the moment

**Comment by norru** [comment]
@jackie1050 I would like a box too. I am happy to buy one and bring it over. Who do I contact to rent some shelf space to keep the box? :)

**Comment by DoESsean** [comment]
Hi @norru, sorry I didn't reply earlier! 

Drop me an email at sean@doesliverpool.com and we can sort things out.

**Comment by DoESsean** [comment]
I've ordered 10 of these [45l boxes](https://www.ebay.co.uk/itm/JMS-Large-Plastic-Storage-Clear-Box-Clear-Lid-Container-Made-In-U-K-Set-of-5/292189752748?var=591121944204) which are the ones @amcewen has ordered in the past.

We shouldn't need any of the bigger ones right now. They should be with us next week.

**Comment by DoESsean** [comment]
They're here, so this issue isn't.
