### ISSUE TITLE
Make a 3D RGB cube

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1173]
Like this one

https://twitter.com/i/status/1147558308036980737

The thread talks about LED panels here

https://1bitsquared.com/collections/embedded-hardware/products/led-panel

I have 6 32x32 LED panels from ABX-LABS to play with. Dunno if we can drive them the same way

![image](https://user-images.githubusercontent.com/1537834/60774381-2b9e0800-a10b-11e9-93a8-153772834c0c.png)

FPGAs, OpenGL, what's not to like...

A/

**Comment by Pezmc** [comment]
Looks great!, You’re going to need a lot of power if each panel is 4a 5v! If you need a hand/want someone to bounce ideas off let me know!

**Comment by ajlennon** [comment]
Yeah abxlabs said it should generally be a lot less than that but I take your point! Will keep you updated!

**Comment by jackie1050** [comment]
We've been having to consider power a lot recently with some of the LED projects we've been working on. If you do have issues might be worth asking @magman2112 about the power supply he's just been putting together for the Defence Dress.

**Comment by RiverMersey** [comment]
https://github.com/kbob/LED-Cube

**Comment by ajlennon** [comment]
No progress on this so closing for now
