### ISSUE TITLE
Gerald not cutting or engravin on full power

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1174]
Yesterday evening Gerald was working as normal e.g. I was able to cut a box from poplar sheet, but then it was suddenly a lot weaker when Rob tried to cut something. We tried poplar again but it couldn't even cut that.

**Comment by amcewen** [comment]
It seems to be an alignment problem - Graham is in trying to do some cutting today and we tried removing the air-assist nozzle to see if that improved things and it started cutting fine.

Checking with come masking tape, the last mirror seemed way out.  Graham is realigning it.

**Comment by gbowman85** [comment]
I've realigned it and it's cutting well now!

**Comment by amcewen** [comment]
Thanks @gbowman85!  You should be added to the DoES Liverpool organisation on github now (or at least have had an invite to it) so feel free to close this issue down (that'll let you confirm I've added you correctly :-D)
