### ISSUE TITLE
Weeknotes Generator doesn't seem to have generated any Weeknotes for Week 422

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1175]
There doesn't seem to be a reminder for this week, and I can't find a draft post in WordPress

**Comment by amcewen** [comment]
I blame @DoESsean for closing too many issues ;-)  The script got rate-limited by github because it makes too many requests to the API.  

I've opened https://github.com/DoESLiverpool/weeknote-generator/issues/29 to track the fix, and will get it sorted sometime in the next day or two.
