### ISSUE TITLE
Please add me to the Github organisation

### ISSUE THREAD

**Issue by chris-does** [DoESLiverpool/somebody-should#1176]
* Please add me to the Github organisation per: https://github.com/DoESLiverpool/somebody-should/wiki/Joining-DoES-Liverpool-on-Github

**Comment by amcewen** [comment]
Welcome!  You should have an invite to join the organisation now.  Once you're in, I'll let you close this issue down :-)

**Comment by chris-does** [comment]
Thank you for the rapid action and resolution.

**Comment by chris-does** [comment]
> Welcome! You should have an invite to join the organisation now. Once you're in, I'll let you close this issue down :-)

Thank you for the rapid action and resolution.
