### ISSUE TITLE
Display power used in KWh since midnight

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1177]
I've created the flow on node-red to count the ticks, and you can see it with the command:

` mosquitto_sub -h mqtt.local -v -t "daypowerkwh"`

Maybe one of those LED panels could display the number for today and yesterday.  

We do seem to have a baseload of 2kW all the time.  It might be worth getting an account of this from the fridge, the VR PC, and what the other components of this are (eg the magnetic door lock).

**Comment by goatchurchprime** [comment]
I'd do this right now with one of those LED dot matrix panels if I could find one, and nail it to the wall near the CO2 sensor.

**Comment by ajlennon** [comment]
I think there should be a 4x1 strip in one of my boxes under my desk or maybe a bag on my desk I took to Holland. You’re welcome to use it if you can find it

**Comment by goatchurchprime** [comment]
@ajlennon any sign of getting hold of one of these?  

I'm trying to get that power measuring going again, but the mdns stuff has ceased to work, and only responds to .localdomain rather than .local.  

Apparently mdns has been implemented into micropython, so I'm testing that out shortly.

**Comment by goatchurchprime** [comment]
mDNS is now working in ESP32s as part of the Micropython (so I no longer need my hacky implementation.  However mqtt.local is not working.

**Comment by ajlennon** [comment]
DIdnt' we just turn it on in the firmware?

**Comment by DoESsean** [comment]
This is up and running and on display in the space.
