### ISSUE TITLE
Propose a victory round of applause for the number of issues Sean is closing down 

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1178]
I'll begin

👏👏👏👏👏👏👏

**Comment by DoESsean** [comment]
Is it wrong that I want to just insta-close this issue?

**Comment by ajlennon** [comment]
Not at all. Your strength of character in closing this stuff helps us all (imho) x

**Comment by Pezmc** [comment]
Too many emails 😆, keep it up!

**Comment by ajlennon** [comment]
OK that's enough. Don't want him getting too big headed. Closing this down!
