### ISSUE TITLE
Rumbling/Groaning noise from Gerald's Belly. 

### ISSUE THREAD

**Issue by Draughtworx** [DoESLiverpool/somebody-should#1182]
Hi there, last night Gerald was making a strange intermittent sound, I couldn't locate the exact area, but I think it may be coming from the extractor fan underneath, it sounds like there's a rumbling or a groaning in his belly. He still works perfectly well. I wondered if it was perhaps to do with the new extractor ducts, but like I say, I was unable to determine just where it was coming from. Thought it might be worth mentioning.

**Comment by amcewen** [comment]
Thanks for the report.  I noticed it yesterday too, and there was also noticeably more noise from the laser-cutter in the stairwell too.

Investigating, the air pump was on its side, rather than sat on its rubber feet.  I've righted it and that seems to have done the trick.
