### ISSUE TITLE
Hang a steel ruler (or two?) to in the laser-cutter room

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1183]
We should have a half-metre rule (and ideally a metre rule too?) hanging from a nail in the laser room like we do in the CNC room, so there's a ruler for measuring stock, etc. to hand.

**Comment by chris-does** [comment]
I can provide a set of three :

- 305mm;
- 540mm; and
- 1050mm.

I shall bring them with me next time I am in (likely Thursday 25th July if not before).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chris-does** [comment]
### Three rulers added to the [Laser Workshop](https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutting):

- 305mm;
- 540mm; and
- 1050mm.

### One ruler added to the [Metal Workshop](https://github.com/DoESLiverpool/somebody-should/wiki/Rooms#metal-working-room):

- 1050mm.
