### ISSUE TITLE
North-side air conditioning provides "additional cooling" by dripping lots of water

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1186]
The air-con has been on today, and is dripping lots from the two units in the main room :-(

The iciing up we had last summer was covered in #700 and was supposed to be fixed by the engineers in November.

Maybe we didn't run the aircon hard enough then to test it (or it wasn't hot enough to exercise it properly) or maybe there's a different issue, but it's not very good at present.

**Comment by amcewen** [comment]
![image](https://user-images.githubusercontent.com/108468/61904399-b1e58700-af1e-11e9-8232-de235ef21234.png)

I've installed a "temporary excess water routing system" which means almost all of the water makes it into the bucket below, as shown above.

It seems that it's all coming from the white drainage pipes which drain any condensate, so maybe the drain pipe is blocked somewhere?

We should ping Jason and get him to investigate.

**Comment by amcewen** [comment]
I pinged Jason on Friday.  Apparently maintenance of the aircon falls under our responsibility on the lease, and the air con engineers number is 01704 212322 Envirocool.

I haven't done anything more about it yet.

**Comment by DuncReid** [comment]
Is the aircon under a maintenance agreement with Envirocool? I have a good contact at a different HVAC Company based in Baltic if needed.

**Comment by johnmckerrell** [comment]
Envirocool were the people to last look at this so hopefully it'll be covered under warranty so we'll stick with them for now. I've called them now, they won't be able to come today, might be tomorrow but certainly by Wednesday.

**Comment by Sean-anotherone** [comment]
Condensate pump blockage?  Very common failure mode - gets fluffed up all winter and them turns to felt on the 4 days per year you need cooling.

**Comment by johnmckerrell** [comment]
Doesn't look like they'll be here tomorrow so hopefully they'll be in and sort it out tomorrow. We need to remove the temporary fix by Thursday though.

Also can I point out that the mop bucket marked TOILET is only for use for cleaning the toilets, any other use is unsanitary.

**Comment by amcewen** [comment]
The aircon engineers were here yesterday and replaced the white waste pipes that were siliconed-in with the proper sort of fittings (I assume).  These are *lots* better, although I think there were still a couple of drips from the unit at the carpet end.  I'm running the air-con today to double-check things before we close this.

**Comment by johnmckerrell** [comment]
Obviously it would help if they had said something but should we be leaving them off while glue/silicon dries out?

**Comment by amcewen** [comment]
I'm pretty sure they didn't use any sealant (I didn't spot them with any, but wasn't watching the whole time they were working on it) and I'm also pretty sure that they left them on and running when they left, so I don't think there's anything like that to worry about.

I didn't speak to them before they left though.

**Comment by amcewen** [comment]
The aircon was on all day yesterday and didn't seem to cause any problems, but @kayharvey confirmed there'd been some drips the day before.  I think we're okay to close this (and reopen it if the dripping recurs)
