### ISSUE TITLE
Reprogram the Liver bird to be MQTT powered (or DMX)

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1189]
Now that the Liver bird is up on the wall (issue #1122) it needs a new protocol for controlling it through MQTT, probably based on the current mapping, where there are sub-assemblies of lights where the colour can be set all as one, or lights within them submapped.  

The protocol should be general enough allow for the whole colour map to be set in one frame. 

Then the node-red system could be set up to make it look like a cup of coffee when the coffee has brewed.  It could turn red and sweaty when the temperature is high enough to use the air-cons (or preferably a fan).  Or turn blue with raindrops when there's a storm outside.

**Comment by ajlennon** [comment]
The netballs looked great. They were DMX controlled weren't they. What was actually doing the DMX control @jackie1050 @zarino ?

**Comment by zarino** [comment]
@ajlennon All the code is here https://github.com/zarino/netballs. We had an Arduino Uno with a DMX Shield, [reading the DMX input, and sending it on to a Raspberry Pi over serial](https://github.com/zarino/netballs/tree/master/dmx-receiver-arduino). 

(The Pi generated its own wifi network and ran its own MQTT server, which it then [published messages to](https://github.com/zarino/netballs/tree/master/netball-broker-python). ESP32s in the two netballs [joined the wifi network, listened for MQTT messages from the server, and changed lights accordingly](https://github.com/zarino/netballs/tree/master/mqtt-led-controller-esp32).)

I’m not sure I’d recommend you use DMX to control the Liver bird. It’s really only worth going down the DMX route if you have a _source_ of DMX data that you want to use with the bird, and you have some way (either in that DMX source, or in the bird, or in an intermediary, like our Raspberry Pi) to transform the DMX data into something the bird can use.

**Comment by jackie1050** [comment]
I quite liked the DMX idea as it would be good to maintain some knowledge of such a widely used protocol, and it could be fun to program some effects in that people on same WiFi network could control with phone apps such as  Art net contoller Lite (https://sites.google.com/site/artnetcontroller)
I've used this to control Neopixels attached to an ESP32 using this tutorial: https://learn.sparkfun.com/tutorials/using-artnet-dmx-and-the-esp32-to-drive-pixels.
(I notice that Sparkfun also sell a DMX shield for ESP32 https://learn.sparkfun.com/tutorials/sparkfun-esp32-dmx-to-led-shield#).

I was wondering whether DMX and mqtt might work together?

As we are also fixing the geometric lights it might make more sense to do this with them though.



On 28 Jul 2019 10:55, Zarino Zappia <notifications@github.com> wrote:

@ajlennon<https://github.com/ajlennon> All the code is here https://github.com/zarino/netballs. We had an Arduino Uno with a DMX Shield, reading the DMX input, and sending it on to a Raspberry Pi over serial<https://github.com/zarino/netballs/tree/master/dmx-receiver-arduino>.

(The Pi generated its own wifi network and ran its own MQTT server, which it then published messages to<https://github.com/zarino/netballs/tree/master/netball-broker-python>. ESP32s in the two netballs joined the wifi network, listened for MQTT messages from the server, and changed lights accordingly<https://github.com/zarino/netballs/tree/master/mqtt-led-controller-esp32>.)

I’m not sure I’d recommend you use DMX to control the Liver bird. It’s really only worth going down the DMX route if you have a source of DMX data that you want to use with the bird, and you have some way (either in that DMX source, or in the bird, or in an intermediary, like our Raspberry Pi) to transform the DMX data into something the bird can use.

**Comment by ajlennon** [comment]
Thanks guys - yeah that's what I was wondering about - the Arena engineer's lighting desk. That seems really cool. Do we know anybody who knows how to set up something like that?

**Comment by amcewen** [comment]
The Liver Bird has a Pi running NodeRED in it, which talks to an Arduino that controls the lights.  I've pulled the interface that the Arduino provides through and made it available from MQTT on a variety of `liverbird/...` topics.

It's all documented in [the Electric Liver Bird section of the MQTT page on the wiki](https://github.com/DoESLiverpool/somebody-should/wiki/MQTT-services#the-electric-liver-bird)

At present it's showing our daily power usage (the logic for that lives in the NodeRED on `mqtt.local`), but the newspaper, beak and eye colours are available to show other things (or we can have it display something else than power usage...)
