### ISSUE TITLE
Make a repo for DoES media/marketing related assets

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1190]
I made useful livestreaming/media assets for makefest this year, such as a stinger (scene transition), it makes sense that these should go in their own repo so we can collaborate on them. There should be a strict structure in order to have this make sense to do with git, since there may be binary files involved, we should stick to assets that are up to 10MB in size, and not change them too much, making sure they're perfect before uploading them, etc. 

As a test I'll be uploading AEP (adobe premiere project) files that I've used for the scene transitions. Anyone who has Adobe Premiere on their system can download the project folder and expect everything to be in the right place. They can then render this on their own computer, which will result in the otherwise large binary file output. The particular scenes I've created are intended to be variable, wherein the logos can be replaced and manipulated, along with color.

The reason I think this is worth having its own repository is due to the binary nature of the stuff in somewhere-safe, that repo may reach its filesize limit at some point, whereas if we keep this separate and binary minimal or binary free, that won't be a problem.

## The transitions:

![does-stinger](https://user-images.githubusercontent.com/26458780/62022818-df079300-b1c5-11e9-8e7d-357a7e7d1463.gif)

![makefest-stinger](https://user-images.githubusercontent.com/26458780/62022860-0bbbaa80-b1c6-11e9-83c3-43430948c62a.gif)

**Comment by amcewen** [comment]
Seems like a good idea to share making them (and store the original project files to let someone else recreate them in future if need be).  You should have the right permissions to create a new repo @MatthewCroughan,

**Comment by MatthewCroughan** [comment]
I've done so at https://github.com/DoESLiverpool/media. It's also worth noting that I, along with many others, have permissions to DELETE many repos, including the somebody-should repo. Just in case you didn't know that. I don't think anyone's that evil, but you know.. there's really no backup of the issues, and other important things, so I really think that should be changed.

**Comment by johnmckerrell** [comment]
FWIW I had a little look at the permissions, it's possible to remove this permission, specifically I've unchecked a box marked:

> Allow members to delete or transfer repositories for this organization
> If enabled, members with admin permissions for the repository will be able to delete or transfer public and private repositories. If disabled, only organization owners can delete or transfer repositories.

I also removed Members from having Admin permission on the somebody-should repo, I've left other repos though and with this permission turned off I think we're probably safe.

**Comment by ajlennon** [comment]
Nice work. Doesn't this stuff go in somewhere-safe though?

**Comment by MatthewCroughan** [comment]
@ajlennon I've noted that the repo size limit is a concern with somewhere-safe since these files have the potential to get a bit large, and we'd want to make as much usage of the 5GB repo size limit as possible, a lot of which has already been used in somewhere-safe.

**Comment by ajlennon** [comment]
Gotcha. Maybe put something in somewhere-safe and/or the wiki to point to the new collateral then?

**Comment by MatthewCroughan** [comment]
@ajlennon Will do, I've renamed it from media to branding-kit, I reckon having a go-to place to direct people if/when they want to represent does will be a good thing.
