### ISSUE TITLE
Prints Adam not printing cleanly

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1191]
Spinning out the problems with Prints Adam printing from #1159.  In that issue @jackie1050 commented:

> Still having problems. On a couple of occasions yesterday the filament stopped extruding mid print (once with light grey and once with clear PLA).
> Today I did 3 cold pulls and material appeared to be coming through, but when I started a print only a limited amount of material was extruded.
>
> * [ ] Do we need a new 0.4mm nozzle? I was going to try one of @ajlennon 's but the threaded part is shorter and I wasn't sure whether this would be an issue
> * [ ] The Bowden tube is in a bad state and appears splayed at the nozzle end. @amcewen says there could be some spare tubing from when it was last replaced - we should look for that
> * [ ] There are no clips now where the tubing attaches to the hot end - did someone decide they weren't useful?

> Another part which we should look at replacing is the coupler. This is a consumable item that hasn't been replaced recently and is apparently a common cause of under-extrusion: https://ultimaker.com/en/resources/21477-how-to-fix-under-extrusion

> Related issue #283

**Comment by amcewen** [comment]
I've ordered 3 [PTFE couplers from imakr](https://www.imakr.com/uk/spare-parts/ultimaker-2-ptfe-glass-filled-coupler) (one for now, and a spare for each printer)

I think the clips are missing because people lose them and don't report it or replace them, so we should replace them.  There might be some more tubing in the 3D printer spares, or we can order some more...

**Comment by Sean-anotherone** [comment]
I spotted during the lubricating session that the ptfe coupler looked in pretty poor shape, that will help a lot.  Replacing the tube will be another plus and if it can be identified, the fitting at the print head that the feed tube plugs into - it's a compressed air fitting ( matching it up will, I suspect, be a lot cheaper than buying an ultimaker one)

**Comment by Sean-anotherone** [comment]
And I'm not sure it's possible to have too many nozzles.....

**Comment by Sean-anotherone** [comment]
MY suspicion is that the Y bearings and stepper motor will be the next things to fail.

**Comment by amcewen** [comment]
As I just mentioned in #1220...
>The new couplers haven't turned up yet - although iMakr are in the US, so a couple of weeks delivery is believable.  I'll have a look at how bad Felicity's coupler is, as swapping that over might get us better printing from Prints Adam until the parts arrive

**Comment by amcewen** [comment]
Felicity's coupler is on the bottom, Prints Adam's is on the top...
![DSC_0071](https://user-images.githubusercontent.com/108468/63022769-814c9980-be9b-11e9-9436-e62203348596.JPG)

I've now swapped them over so that the better one is on Prints Adam.  We can replace both of them when the new ones turn up but Prints Adam is printing lots better now.

**Comment by amcewen** [comment]
@DoESsean is trying to track down what has happened to the ones we ordered, but in the meantime we should order some from https://www.makers-hut.com/product/ultimaker-2-um2-hot-end-isolator-coupler-ptfe-teflon-inner-sleeve-for-3-00mm/ instead (/as well, the others will always work as spares)

**Comment by amcewen** [comment]
The new couplers have arrived.  I've left them in a plastic bag with Felicity.

**Comment by amcewen** [comment]
I've fitted a new coupler to Prints Adam, who seems to be printing fine now, and have made a note on #1203 that we should replace Felicity's too.
