### ISSUE TITLE
Need more clear transfer tape

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1195]
We seem not to have any clear transfer tape for the vinyl cutter, so #719 is stalled until we get some :-(

**Comment by jackie1050** [comment]
When ordering, could we also order a roll of black sign vinyl please

**Comment by DoESsean** [comment]
Tape and black vinyl ordered from [MDP](https://www.mdpsupplies.co.uk/)

**Comment by amcewen** [comment]
Tape and black vinyl have arrived!
