### ISSUE TITLE
Find better mounting point for Gerald's air pump

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1197]
The pump for Gerald's air assist is just sat loose on the floor at the moment, and transfers a reasonable amount of noise into the floor as a result.  That means it's fairly noisy (even more so if it falls onto its side, like in #1182) by the entrance downstairs.

It'd be nice if we could find a better mounting option to reduce the noise/vibration more.

It used to be sat on, and cabled-tied to, Gerald's frame but I don't know if that would transfer *more* vibration through.  Maybe we should try it and compare?  Or find something better?

**Comment by johnmckerrell** [comment]
FWIW I just tried placing it on the "socket height" wood but it still sounds noisy downstairs. For the record we have had comments from Jason about this in the past and concerns that it would affect a downstairs tenant.

**Comment by RussCoty** [comment]
I would try spring mounting or on some rubber/foam. 

The other option is a very heavy block of concrete to bolt it to. 

My Instinct from the audio world would be spring mount it in a frame

**Comment by RussCoty** [comment]
There are a few folks using half tennis balls as anti vibration feet on speaker cabinets and drum kits. Might be worth a try

**Comment by Sean-anotherone** [comment]
hang it on a bungee.  Elastic coupling along the bungee and none anywhere else !

**Comment by magman2112** [comment]
Someone has now mounted this pump on a piece of what appears to be innertube, hanging off the laser exhaust bracket, this appears to be working well.

Safe to close this for now methinks.

**Comment by Sean-anotherone** [comment]
Hi Mike, I did that while fitting a new tube - I did not know there was an issue, just mounted it like that to shut it up !
Sean
    On Friday, 3 July 2020, 19:27:44 BST, Mike Gorman <notifications@github.com> wrote:  
 
 


Someone has now mounted this pump on a piece of what appears to be innertube, hanging off the laser exhaust bracket, this appears to be working well.

Safe to close this for now methinks.
