### ISSUE TITLE
We need to commission the pillar drill

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#120]
There's a pillar drill sat on the woodwork bench in the workshop.  @MerseyViking brought it in, I think.

I guess we need to find out if it's a donation or a long-term loan, and label accordingly.

Then it needs siting somewhere and a suitable power supply run to it.

**Comment by MerseyViking** [comment]
It's a donation.

**Comment by goatchurchprime** [comment]
Is this the one that's in the right that I've been using all week?  If so, should we close this issue?

**Comment by DefProc** [comment]
Yup. I belive it was officially named [Lyra Heartstrings](http://mlp.wikia.com/wiki/Lyra_Heartstrings)
