### ISSUE TITLE
Finish the Defence Dress power supply, and return it to Little Inventors

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1205]
Spun out from #1124.

- [x] Finish power supply – @magman2112.
- [x] Test safety.
- [x] Amend instructions – @zarino.
- [x] Package dress and power supply.
- [x] Send to Little Inventors **by 5th September**.
- [x] Email jill@littleinventors.org to say it’s been sent.

Address to send to:
16 The Crescent
West Rainton
Houghton-le-Spring
Tyne & Wear
DH4 6SB

**Comment by magman2112** [comment]
The power supply has now been tested and appears to be fully working. One faulty extension lead caused the 555 IC to fail, which affected the push button operation. The faulty IC has now been replaced and the faulty extension cable repaired, so all aspects are now working OK.

I would like to tidy up the electronics into the dress and make some of the cables more secure before we return the dress. Also, the some of the covers for the USB plugs and sockets could do with being fixed more securely, possibly with a band of heatsink. I plan to sort out these issues hopefully tomorrow.

**Comment by magman2112** [comment]
I have now made the connectors on the dress more secure and moved the electronics back into its pocket in the dress.

I have also put a band of heatshrink on all of the USB connectors, so the shells won't come of as easy now.

The dress has now been taken off the mannequin and placed on the desk in Room 29, along with the PSU and mains, ready for packaging. I have also placed the box of cables and test panels there, though these are not to be sent back to Newcastle. I suspect some of these parts can be used on the wings as we continue working on them.

In terms of updates to the documentation, the new PSU has made things a little simpler perhaps. To connect the PSU, there are 6 USB sockets on the front along with 6 USB power extension cables. These can be connected in any order. For the connections to the dress, there is one USB connector that is labelled A, this is the only critical connector, as this powers the switch controller. The rest of the USB connectors can be connected in any order, they will just power up more LED jewels as they are connected. Once power is applied to USB A, the button in the sleeve needs to be pressed to switch the LED's on.

If you need any further details @zarino , then just ping me on Whatsapp.
