### ISSUE TITLE
We need to commission the injection moulding machine

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#121]
We've been very generously loaned a small injection moulding machine.  It's currently sat on the floor by the vacuum former.

Someone needs to work out how to use it :-)  And then write up the process on the wiki

**Comment by shrkey** [comment]
Will have a nose at the make / model when next in and see if I can find some info online.

**Comment by johnmckerrell** [comment]
Some photos.

![2015-03-26 14 03 09](https://cloud.githubusercontent.com/assets/27243/6847855/72929f08-d3c1-11e4-9211-46a2d19b708f.jpg)
![2015-03-26 14 03 46](https://cloud.githubusercontent.com/assets/27243/6847867/8e44f110-d3c1-11e4-94fd-5d921fc63c3a.jpg)

**Comment by Paul12M** [comment]
I had this extruding plastic no problem @ 3 weeks ago , the machine needs a new temp control knob  ,steel blocks for holding moulds ( if somebody can make a mould ) ?  .a lever for securing the mould ,new bolts at bottom to allow front  slider to move freely . PLA pellets for the feed ...

1 pellets into hopper .2 move feed flap at side to fill feeder cone .3 wind piston fully up to let pellets drop into extruder  .4 wind lever down to extrude . 5 eat  spinach ! ,you'll need arms like Popeye :)

**Comment by shrkey** [comment]
I was looking for second hand moulds for experimenting with a while ago and
got sidetracked :) Will see if I can track one or two down again. Got
nowhere looking for docs, other than a lot of dead threads of people
looking for docs...

**Comment by Paul12M** [comment]
I know what you mean ,I was looking at making something like this for a test 
 http://www.instructables.com/id/Home-Plastic-Injection-Molding-with-an-Epoxy-Mold/    ,
but my time is very limited at the moment but it would be good to see it working .

**Comment by DoESsean** [comment]
Do we still have this machine? Has it been returned?

Is this still a live issue?

**Comment by DoESsean** [comment]
I think this thing works now, do we have the instructions for use anywhere? If so, let's tidy this issue away.

**Comment by amcewen** [comment]
You think wrong.  It doesn't work yet.  However, issue #928 has better information in what needs doing to it, so although this is older, I'm going to close it as a duplicate of that.
