### ISSUE TITLE
Wheeliepad needs rebooting

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1214]
It says it's offline for some reason.  Is it charging still?

**Comment by johnmckerrell** [comment]
It’s on the charger, the iPad has power but says that the bluetooth is disconnected. What do you want me to do?

**Comment by MatthewCroughan** [comment]
I used it once the other week, this happened. The solution was to turn on aeroplane mode and turn it off again, or some combination of this and unplugging the thing that's plugged into the headphone jack.

**Comment by johnmckerrell** [comment]
I did both these things and it has stopped complaining, but I also can’t connect. Perhaps leave it a few minutes and try it.

**Comment by goatchurchprime** [comment]
Just powercycle it fully.  The off-button is on the bottom left of the ipad as you're facing it (because it's upside down in the holder).  Hold that till it gives you the option to turn it off.  Then turn it on again.  Login with the usual DoESLiverpool computer password, then select the Double-app.

**Comment by johnmckerrell** [comment]
Ok that’s working again. I’ve left it off the charger looking out the window as I assume you’ll be connecting shortly.
