### ISSUE TITLE
Give mqtt.local a static IP

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1217]
With devices like the the [prototype room occupancy sensor/display](https://github.com/DoESLiverpool/somebody-should/issues/1185) talking to the IP address (they don't have mDNS support to talk to `mqtt.local`) of the MQTT broker it would be good if it was on a static IP so that a reboot doesn't take some of the services accidentally offliine.

**Comment by johnmckerrell** [comment]
The next time it reboots it will pick up `10.0.100.1` and should remain there.

**Comment by johnmckerrell** [comment]
Seems like someone rebooted this, or at least it refreshed its DHCP lease.
