### ISSUE TITLE
6mm Collet jamming in CNC machine

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1224]
The 6mm collet is getting jammed in the cutter to a level where I don't believe we should use it any more, as the potential for damage to the Spindle Motor is very high.

I have placed the collet in my storage box, to remove the temptation for people to use this collect again and I am looking to order a replacement, as in the previous issue.

The cheapest is looking to be from CNC Plus in Germany - where the CNC Machine came from - @17.90 euros each, but I will do a bit more research before jumping in.

**Comment by MatthewCroughan** [comment]
@magman2112 Are you sure it is not the imperial collet? I recall @goatchurchprime once telling me that he got this stuck and had to have @Sean-anotherone remove it with magic (elbow grease). We have one or two imperial collets that aren't for usage with the machine, would be good to get rid of them now.

**Comment by magman2112** [comment]
@MatthewCroughan It is the 6mm collet that is at fault. 

We need to keep the imperial collets as some of the woodworking cutters are 1/4" and the 1/8" collet is for Dremel tools.

**Comment by amcewen** [comment]
(I've taken the `Broken` label off because the machine itself is still usable, and the broken label is for if it's completely out-of-action)

**Comment by norru** [comment]
Hi @MatthewCroughan, I have used the 1/4" collet (6.35 mm) multiple times last week with zero issues.

The broken one is definitely the 6mm. I never used it but I had to take it out of the spindle twice and it wasn't fun.

**Comment by MatthewCroughan** [comment]
Right, so our router takes imperial collets despite coming from Germany? I still think this is the problem that @goatchurchprime had a while back that we didn't document. 

@norru @magman2112

**Comment by MatthewCroughan** [comment]
After reading a bit more, Julian did document the issue I wrongly recalled in #978 

>I've created a much worse problem. I did the 1.8inch collet up too tight on a 3mm tool, and now it's completely jammed in -- tool and collet. I'm asking cnc-step for help instead of complaining about their high prices.

>Is there a 3mm collet anywhere? I've only got a 1/4inch and this big one that measures at 8mm.

Perhaps we have a bunch more collets lying around that could cause the same problems?

**Comment by RussCoty** [comment]
Let’s not confuse the inner diameter with the outer diameter though folks

**Comment by magman2112** [comment]
OK, this is getting a little bit confusing, so hopefully this clarifies things.

The CNC machine was bought by Martin from Germany and the machine was supplied with a Suhner spindle motor along with three collets - 3mm, 3.125mm (1/8 inch) and 6mm.

I subsequently bought the 6.25mm (1/4 inch) collet so that we could use standard router cutters, like those from Trend and Axminster, for wood cutting and bed levelling.

At some stage the 6mm collet was damaged, hence #978. The 6mm collet was repaired by @Sean-anotherone to close this issue, but that collet was still damaged to a degree and has subsequently started getting jammed in the spindle motor - hence this issue.

@MatthewCroughan The spindle motor is metric and the collets allow us to adapt the spindle motor to hold cutters with different sized shafts.

I have now ordered 2 new 6mm collets as well as a new 8mm collet specifically for the Suhner spindle motor from CNC-Zone in Germany. Hopefully these will fit OK and we can close this issue. 

The 8mm collet is a suggestion from @RussCoty, as he has some cutters with 8mm shafts that we should be able to use in the future.

So once the new collets arrive we should be able to accommodate cutters with the following shaft diameters.

- 3mm
- 3.125mm (1/8”)
- 6mm
- 6.25mm (1/4”)
- 8mm

**Comment by RussCoty** [comment]
I’ll bring in my new box of end mills at some point and I have a load of wood bits for various router sizes. Maybe some will be of use

**Comment by magman2112** [comment]
After one failed attempt with one supplier of collets from Germany, I finally plumped for the collet and nut set from Protools. This has now arrived and does fit the Suhner router and 6mm bits fit easily for a change.

Finally closing this issue.
