### ISSUE TITLE
Consider how we make the mailboxes wheelchair-accessible

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1226]
Two issues I have with the mailboxes right now:

1. The upward-facing labels are impossible to read unless you’re on tiptoes.
2. They’re high up and far back – hard to reach if you’re short, or using a wheelchair.

![IMG_8728](https://user-images.githubusercontent.com/739624/63346226-6f13a500-c34c-11e9-8b16-da06a79973c3.jpg)

I fear this is only going to get worse if we need to add another layer of mailboxes – as was alluded to in last week’s community meeting.

Potential solutions:

1. Remove the unused laser printer and Double2 carboard boxes that are currently on top of the plan chest, and use the newly freed-up space to move the mailbox shelves down – this solves the height problem, but they’re still annoyingly far back.
2. Move the plan chest somewhere else – although I’m not sure where we have room for something so wide and deep?
3. Move the mailbox shelves somewhere else – the space between the doors to Dinky and the soundproof room maybe?
4. (Crazy idea:) Replace the mailbox shelves with something free-standing, like our rotating component cabinet – would obviously require more work, but makes much better use of vertical and horizontal space.

**Comment by DoESsean** [comment]
I like option 4 quite a lot. As you say, more work, but if we had someone
that was willing to lead it, it would be great.

**Comment by ajlennon** [comment]
Random thoughts.... Do all mailboxes need to be wheelchair accessible or do we only need mailboxes for people with difficulty reaching up to be accessible? i.e. could we have a couple of more accessible boxes elsewhere instead of having to move the entire thing?

**Comment by johnmckerrell** [comment]
rotating 90 degrees before putting on the plan chest would fix the "annoyingly far back" problem, but as @ajlennon says in the short term we probably only need to make a few more accessible then longer term need a better solution.

**Comment by RiverMersey** [comment]
Could we build a mailbox robot?
Have individual mailboxes slide around on rails parking them up in the ceiling and a control panel that can call any one of them to a wheelchair accessible point in the doesLiverpool space

Not sure how it might work for someone posting something into a parked mailbox though

**Comment by ajlennon** [comment]
If we get some mechanical arms onto @goatchurchprime 's WheelieBot we may have the solution...

https://www.banggood.com/DIY-5DOF-Robot-Arm-Five-Fingers-Metal-Mechanical-Paw-Left-and-Right-Hand-p-1099018.html

**Comment by goatchurchprime** [comment]
Given the price of other things, like this: https://www.workspacedesigns.co.uk/mail-room-furniture-post-assembled-24-space-c2x28221516  the cardboard stacks we're using are pretty good value.  

I think the plan chest needs moving as it blocks having sensible shelves lower down towards the floor.  Without it, you get a lot more connected open space behind my desk for swinging cats.  

Normally the plan chest would go under sophia laser cutter, but then the latter would not be wheelchair accessible. We could move it to the events room to act as another surface, or lift it onto the racking by the solder station if that's deep enough.  It's starting to feel like we're playing tetris in the space.

**Comment by amcewen** [comment]
The new mailboxes are much lower down than the old ones, and have the numbers printed on the front, so I *think* this will be covered by #1392.  (Feel free to reopen if I've missed something)
