### ISSUE TITLE
Strange networking issues today, DNS?

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1227]
![image](https://user-images.githubusercontent.com/26458780/63364365-55368a00-c36d-11e9-9e8d-79db09f78f6d.png)

I have got absolutely no idea what I'm looking at. But pings to google get redirected to WN3000RPv3 which is presumably one of the pi's in the networking cupboard.

There is 100% packet loss to whatever this is, hence these strange issues.

A consequitive dig reveals that my machine keeps failing over to Cloudflare's DNS. Is this a problem with our DNS server? I'm not the only person to have been experiencing this today.

![image](https://user-images.githubusercontent.com/26458780/63364582-cc6c1e00-c36d-11e9-9f13-13bf47c8c9d8.png)

**Comment by skos-ninja** [comment]
The failover to cloudflare is correct behaviour as it is set as the backup dns via DHCP.

The client appears to be a Netgear router that was causing rogue broadcasts. As such it is blocked on the network until the person who has configured it fixes it.

**Comment by MatthewCroughan** [comment]
There's a bit of a coincidence with John Cassidy plugging in a wifi range extender, then unplugging it and whatever this is stopping.

That wifi repeater is a netgear, so I'm pretty certain it is indeed that unit. @skos-ninja

**Comment by MatthewCroughan** [comment]
Right, I think I get it. It connected to the network here and attempted to act as the DHCP/Gateway, correct? wn3000rpv3 is the unit in question, that is his range extender I just checked the label on it.

**Comment by MatthewCroughan** [comment]
I've asked him if he could turn it off, since it's still causing issues on the network. But he acted quite aggressively towards me and told me no. Is there anything you can do to stop this from causing dropouts? @skos-ninja

**Comment by ajlennon** [comment]
Guys - can we take this offline please

**Comment by MatthewCroughan** [comment]
![image](https://user-images.githubusercontent.com/26458780/63366630-1820c680-c372-11e9-8b80-e4cd11b362b2.png)

The unit is causing 50% packet loss at the moment.

**Comment by skos-ninja** [comment]
The device is blocked from talking on the network however it might still be broadcasting a wifi signal itself that could cause further issues.

I'm unable to fix that from 200 miles away I'm afraid 😞

**Comment by amcewen** [comment]
@skos-ninja doing some investigation is seems to cause issues (even though you've blocked it?) when the Ethernet is plugged into it.  John C has unplugged the Ethernet now (we tested it unplugged - no packet loss, and then the packet loss restarted when it was plugged back in).  Do you have any more info on the problem it was causing?

**Comment by skos-ninja** [comment]
@amcewen Sorry for the late reply I have been a bit ill.

To me what that looks like is symptoms of the device broadcasting incorrect routes to the network and due to how our Dell switch is configured this route broadcasting is allowed and as such devices will accept the route without first talking to the gateway to confirm it's correct.

I can investigate further to see what settings I can configure on the switch to disallow that type of broadcasts however what I don't want to do is force all traffic to talk via the gateway as the load that will cause may be more significant than the gains we get from thsi

**Comment by ajlennon** [comment]
fwiw I’m not sure if this is the same thing but the mDNS is flakey. Sometimes it works fine and other times we can’t map .local addresses. Seems to come and go. Can’t work out why

**Comment by johnmckerrell** [comment]
Can this issue be closed now? I don't know if @skos-ninja has found any settings but it would seem that the solution to "something plugged into the network is causing problems" would be "unplug the thing from the network" and that has now happened.

**Comment by ajlennon** [comment]
Well, I guess. But somebody does keep plugging something into the network that breaks it every now and again. It would be great if it didn't happen

**Comment by johnmckerrell** [comment]
I think it's much less likely to happen now and it's difficult to fully guard against bad actors on the network.
