### ISSUE TITLE
Cutting Fluid for CNC

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1229]
@RussCoty  mentioned today that we needed some new fluid for the CNC machine.

Apparently, @magman2112 had brought in what we currently have, so I've bought [some of this](https://www.ebay.co.uk/p/Ambersil-TUFCUT-Aqua-Cutting-Fluid-300ml/675325150?iid=263506688902&chn=ps&norover=1&mkevt=1&mkrid=710-134428-41853-0&mkcid=2&itemid=263506688902&targetid=594652374160&device=c&mktype=pla&googleloc=9046552&poi=&campaignid=1782815970&mkgroupid=70885939082&rlsatarget=pla-594652374160&abcId=1140486&merchantid=114941810&gclid=EAIaIQobChMIqovV2d2W5AIVy7TtCh0K1QauEAYYASABEgJKovD_BwE) which seems to be the same stuff.

**Comment by magman2112** [comment]
There is a bottle of concentrate in the cupboard next to the CNC machine. I have shown this to Russ and he is going to make up some more coolant.

**Comment by RussCoty** [comment]
Done. Now we have enough to last until the apocalypse.

**Comment by norru** [comment]
I have also bought some "vegetable oil" lubricant. Some is available beside the CNC machine and some spare is in the poison cupboard.
