### ISSUE TITLE
Get the bed level so we can print raftless on the Up 3d printer

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#123]
If you try printing without a raft on the blue Up 3d printer, you get a variety of levels of adhesion to the bed, and your print will generally fail.

That's because the bed isn't quite level.  http://www.thingiverse.com/thing:39430/#instructions seems an interesting approach where you level the bed while it's printing.  We should try that to see if we can get to consistent, raftless printing.

**Comment by DefProc** [comment]
I've levelled the bed on Violet (the blue one), and it's printing much better that this morning.
