### ISSUE TITLE
Document a methodology to best setup the Creality CR-10S and get the best prints

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1230]
So this continues on from #1163 as we have a replacement Creality printer now.

I've started documenting a process to setup / calibrate the printer in the Wiki

https://github.com/DoESLiverpool/somebody-should/wiki/Creality-CR-10S-3D-Printer

We've been having a lot of problems getting prints to adhere with the first layer not going down right. Luckily @Sean-anotherone has given us a mini-masterclass.

The first thing which we hadn't done was to set the "erratics" properly. i.e. The wheels that grip the sides and underneath need to be gripping properly which they weren't. When they are set correctly the glass bed is really solid and you can feel the stepper motor moving as you move the glass bed forwards and backwards.

You have to be very careful setting the erratics as if you overtighten you can break the machine.

I am going to put a bit of thought into how best to document this.

Then with that first step out of the way (and hopefully if doesn't have to be done often) you can then 

- level the corners
- do the mesh levelling.

The levelling is best done with a sheet of mylar (PCB plastic bags - one side only) and with that done we seem to be getting much better prints.

Also the nuts holding the prusa frame together seem to be a bit lose so if all the above still doesn't get us where we need to be we'll strip the frame down and rebuild checking that everything is correctly angled together.

I'll get around to updating the wiki with the above when I have things clearer in my mind.

Please comment / correct / enhance the above!

**Comment by ajlennon** [comment]
Blocked on #1559

**Comment by amcewen** [comment]
This printer isn't in DoES any more, so I'm going to close this.
