### ISSUE TITLE
Laser cutter required blower maintenance, was clogged.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1231]
@magman2112 tells me this is an ongoing issue, could you please cross reference this and then close the issue?

https://twitter.com/DoESLiverpool/status/1165984960261623810

![image](https://user-images.githubusercontent.com/26458780/63882302-9fe97f00-c9c9-11e9-8b98-432aa73c1064.png)

**Comment by magman2112** [comment]
As part of #474, a filter will be included before the blower, which should hopefully remove this as an issue in the future.

Closing this as an issue for now.
