### ISSUE TITLE
Make electricity a calculated and separate metric in the financial report

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1233]
Electricity is not mentioned in the financial reports on the Wiki. Julian wants this to calculate things.

**Comment by johnmckerrell** [comment]
I'll have a look, we do get this broken out and it would be useful to see. Not sure it's worth me going back through all the reports so far though.

**Comment by johnmckerrell** [comment]
![Does March 19](https://user-images.githubusercontent.com/27243/64081405-4dc19a00-ccf8-11e9-9d9b-ebcafb853b5b.png)

Having now done this I'm not actually convinced you want it breaking out or if you just want to know the price we pay to put in a graph. Here's the last breakdown we had in April. I'll leave it as an exercise for the reader to work out what it means. I'm not 100% sure myself from a glance but bear in mind we may be paying some communal electricity on top of our own meter readings. July's financial report with electricity is in so I'll close this but the previous ones will follow shortly.

**Comment by johnmckerrell** [comment]
I'll need to review this as I realised I was going to put the same figure in the July and August financial reports. I'm guessing I've offset them all by a month (so I've put, e.g., April's electricity usage into April's financial report although we wouldn't have paid for it until May).

**Comment by johnmckerrell** [comment]
I corrected the numbers recently.
