### ISSUE TITLE
Gerald and Sophia cutting/alignment issues

### ISSUE THREAD

**Issue by JessCollinge** [DoESLiverpool/somebody-should#1238]
Hello,

myself and Laura have been using the laser cutters today and have noticed the following issues:

**Gerald:** 

Having to run the speed a lot slower than usual to get him to cut through material. 

Cutting through OK on the left-hand side but not on the right.

**Sofia:**

Struggling to cut through material and having to run the speed a lot slower than the usual settings (struggled to cut through 1.5mm ply and was running at 3mm speed/power).

Etch alignment seems to be off. Also jumping whilst etching – no particular pattern to this, just etching out of position every now and again.

If anyone is around tonight to take a look at the both of them, that would be great.

Thanks, Jess

**Comment by magman2112** [comment]
Gerald did have a alignment problem, but after some adjustment this appears to be working well again. Also the lense and one of the mirrors needed cleaning.

I didn’t find any issues with Sophia last night and was cutting 3mm plywood at a speed of 12. I did clean the lens though. I didn’t check this across the full bed though, so will check this out again when I am next in (probably Sunday now).

I will leave this issue open for now, until I have checked out Sophia a bit more.

One small point. If you include @DoESLiverpool/laser-maintenance in the issue, this then flags the issue to the laser maintenance team, which will hopefully get a quicker response to your issue.
