### ISSUE TITLE
A box for 3D printed ABS recycling

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#124]
I'm producing a lot of waste with my prototypes and support material.  

Let's start collecting it in a clear plastic box now, knowing that there's no technical reason it can't be ground down, remelted and used for printing again, once we find someone to do it (or eventually make a machine to do it ourselves).  

It' would be good if the melting didn't mix up the colours thoroughly into a shade of brown, but left the filament all streaky and multicoloured.

**Comment by DefProc** [comment]
May be useful for material for the injection mouding machine #121

**Comment by amcewen** [comment]
Well, given that we're nearing a full box of ABS for recycling, I suspect this issue can be closed.  I don't know if that means we should spawn a new issue for "Build a filament extruder" though... :-D
