### ISSUE TITLE
Setup for Repair Cafe

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1245]
With our first Repair Cafe now in the calender, as a support event for The Festival of Maintenance, this issue is to capture the requirements to support the Repair Cafe and to log critical issues as we identify them.

**Comment by zarino** [comment]
@jackie1050 notes that you might want to buy some more jewellery glue for this. And/or some Gorrilla Glue.

**Comment by DoESsean** [comment]
Seeing as the day went off well, I'm closing this issue.
