### ISSUE TITLE
Gerald not working.

### ISSUE THREAD

**Issue by Draughtworx** [DoESLiverpool/somebody-should#1246]
Gerald stopped working this evening, 3 minutes into use, after making what I can only describe as a rather loud high pitched hissing sound. The laser head continues to move but produces no laser and makes a different sound. I'm not sure if maybe the CO2 tube has blown, or if it's something else. The cut's it made immediately before stopping were fine. At the same time it stopped working the LCD display went funny also, the display disappeared and it began to flicker, once I hit pause it returned to normal.

**Comment by MatthewCroughan** [comment]
Is the sound loud enough to be heard outside the room? If that's true, then that's something that happened when @magman2112 installed the tube but it wasn't attached strongly enough if so.

**Comment by jackie1050** [comment]
@LeeCarmichael mentioned that there was a strange clicking noise earlier in the evening and was going to raise an issue if it continued.

**Comment by amcewen** [comment]
Just trying the laser button you get a high-pitched squeak when it tries to fire.  I think we had that relatively recently, so there might be a record of whether it was the tube or the power supply.

Having a look at the tube it doesn't seem great...

![Laser tube with strange brown deposits](https://user-images.githubusercontent.com/108468/64952793-24b51380-d879-11e9-88b6-c96235feaba7.JPG)

There are bits of that brown deposit all along the tube, although it's worst at the "pointy" end.

/cc @DoESLiverpool/laser-maintenance

**Comment by LeeCarmichael** [comment]
Yes when i was using yesterday it started making an arcing sound but was cutting fine. Finished the cut and then called it a day.

**Comment by magman2112** [comment]
At first I thought it may be the water being a bit low in the chiller. Whilst topping this up though, I spotted some arcing of the HT lead to the chassis, below the laser tube.

On further investigation, the connection appeared to be broken, hence the arcing. The joint was also at the join of the two pieces of silicone tubing, which has likely but additional stress on th3 connection.

I remade the connection with an extra layer of heat shrink tubing, moved the joint further along in the silicone tubing and wrapped insulating tape over the join in the silicone tubing.

The laser then worked first time and on further tests was cutting well.

**Comment by amcewen** [comment]
This is what the HT lead looked like before @magman2112 made his fix :-)

![DSC_0099](https://user-images.githubusercontent.com/108468/64965591-39070980-d895-11e9-9b85-b4f02b369494.JPG)
