### ISSUE TITLE
Move the QR codifier to the dymo printer and document

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1247]
Alex made/found a QR codifier thing, used here:
    https://github.com/DoESLiverpool/somebody-should/wiki/IoT-Lending-Library

The sophia PC originally had the dymo printer, but now that's moved, so the app should move with it.  

I'd also like the documentation of it so we can hack and change it because I've decided that Becka has an application for it; of encoding dates and places into the qr code and photographing objects with them in it, given that we have the opencv tech to find and read these things from it.

**Comment by amcewen** [comment]
https://duckduckgo.com/?q=qr+Just+type+qr+and+the+text%2Flink+into+DuckDuckGo&t=h_&ia=answer

![QR code created at the above link](https://user-images.githubusercontent.com/108468/64954981-f89c9100-d87e-11e9-85b4-8eb76ee17115.png)

**Comment by goatchurchprime** [comment]
Alex's codifier hooks in with the label printer and writes it in english beside the qr code, so it more fun.  Also I want to see if qr codes can encode not urls, but the aquisition dates, prices and places of things.

![qrcodifiererror](https://user-images.githubusercontent.com/677254/64959260-af513f00-d888-11e9-9dad-58305ce20472.png)

**Comment by ajlennon** [comment]
Had a quick look. The current source and installer is here

https://github.com/DynamicDevices/qrcodifier

The current release installs ok but craps out when I run it.

We may need to recompile it...

**Comment by goatchurchprime** [comment]
I had a good go at trying to get the javascript version of the dymo thing going just now
    https://github.com/MaxSmith/DYMO-Label-Framework

There's something still missing, even after I sorted out the cross site thing.  The example thing is here:
    http://developers.dymo.com/2010/06/02/dymo-label-framework-javascript-library-samples-print-a-label/

Didn't work. It wants to connect to localhost:41951 which I presume is served by the dymo software.  (There's a newer version, but don't know if it's 64 bit only)

A javascript implementation would be preferable as it would be more hackable.  


One application is to quickly generate templated labels with QR or Aruco tags to stick onto things or people.  We have already demonstrated the capability to lift out Arucos using opencv, and there are libraries to extend to QR and barcodes for real-time tracking.  
    https://answers.opencv.org/question/198783/opencv-real-time-tracking-only-qrcode/

QRs and images can emulate most of the same things as RFIDs, but with the advantage that they are visible, very cheap, longer distance, and you can get positional information from them.  We should call them LFIDs for "Light Frequency IDs".  

We could print the QI code for the MAC address each SONOFF to stick on the box, which could mean that we'd have a faster way to commission any such IoT item when they are moved about in a place.

**Comment by ajlennon** [comment]
So I downloaded Visual Studio 2019 Community edition, rebuilt the QR codifier and it runs up.

The QR code is the wrong size and when you push a button it hangs.

I wonder if the label size for this printer is different or something.

We need to look at the label template it is using and I need to work out why it is hanging.

Collar me when you're about @goatchurchprime and we'll look at it together.

**Comment by ajlennon** [comment]
Working now. Just run from the shortcut.

Somebody needs to commit the code.

**Comment by ajlennon** [comment]
@goatchurchprime  For docs see the Dymo SDK docs.

http://www.dymo.com/en-GB/online-support-sdk

There's an XML label definition format which you can load directly into the Dymo LabelWrite program you usually use. You can edit the format and re-save it...
