### ISSUE TITLE
Add some biocide to the coolant for the laser-cutters

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1249]
Given the brown gunge in Gerald's tube (photo in the comments of #1246), we should add a few drops of biocide to the coolant in both cutters.

I've got some, which I'll bring in sometime.

**Comment by DoESsean** [comment]
Did the biocide get brought in?

**Comment by amcewen** [comment]
Yes.  Kept forgetting to update this (or just add a few drops to let this be closed).  The vial is on top of the component drawers on my desk, among my 3D prints collection (IIRC).

**Comment by DoESsean** [comment]
Excellent. If it's ok, I'll leave this to someone else to finish up as I'm likely to use the wrong thing, put it in the wrong place, or use a wildly wrong amount.

**Comment by amcewen** [comment]
I remembered about this just now when @Sean-anotherone was fitting the new tube to Gerald, so we've done both of the cutters.
