### ISSUE TITLE
Apply for discretionary business rates relief

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1250]
We have a received now received a business rates bill and will need to apply for relief. 

https://forms.liverpool.gov.uk/contour-forms/business-rates-discretionary-rates-relief/

The questions on the form follow, any help providing answers is appreciated.

* Is this a registered charity?*
    * ~Yes~
    * No 
* Is the organisation a Company Limited by Guarantee?:*
    * ~Yes~ 
    * No 
* Is the organisation established or conducted for profit?:*
    * ~Yes~
    * No
* What is your role/capacity at the organisation?*
> Director
* Email:*
> john@
 
## Facilities and community
* What facilities are provided at this address?*
> DoES Liverpool provides coworking (shared office) facilities, events and meeting rooms, and a workshop containing tools and digital fabrication equipment. The coworking facilities provide desks and office facilities to entrepreneurs, freelancers and small business owners. Our events and meeting rooms are used by many local community groups and by local businesses. We regularly provide these facilities for free for public meetings and events. Our workshop is used by a huge variety of people. This can include, but is not limited to, artisans working on bespoke pieces, entrepreneurs building prototypes, young people looking to enhance their skills in digital and making, older people entering retirement looking to join a community and pass on their skills, and many more.
> All of our users also get access to our high speed internet connection, kitchen facilities, and access to a community of like-minded people to share ideas and collaborate with. We provide multiple opportunities for people to make use of these facilities for free and then due to our not-for-profit status we are able to keep our prices for further use low, also offering a membership scheme with further discounts. We see our role in the city as a lively, connective and inclusive community helping to build skills in areas such as innovation, digital, and creativity, and are proud of our capacity to welcome and include people no matter their socioeconomic background. We also have a strong focus on a sustainable and green future, and regularly host groups and individuals doing cutting edge work in this area.

* What percentage of your members/service users are resident in Liverpool*
 63%

* Are the facilities provided for the benefit of a specific geographic area?*
    * Yes 
    * ~No~ 
* Which area?
> Liverpool City Region

* How are the general public made aware of the facilities?*
> We work with partners such as the Princes Trust, Sale Sharks and Little Sandbox. We advertise our services on the internet and are very active on social media, at a regional and national level. We have built up strong connections in a number of communities over our nearly ten years of operation and much of our membership joins through word of mouth. We have also hosted delegations from overseas who are interested in seeing a leading example of best practice in makerspaces and local business hubs, contributing to a thriving city environment. We have even been featured on national TV, such as a very successful segment on Channel 5's The Gadget Show.
 
* Provide details of any particular sectors of the community who are encouraged to use the facilities:*
> DoES Liverpool welcomes anyone who wants to use our facilities but we do focus on enabling people to generate self-sustaining income, creating opportunities for more inclusive growth. Our initial free access allows people to experiment with ideas for products or artworks, and our low prices allow them to expand without incurring high fees.
 
* Is there a membership fee to use the facilities?*
    * Yes
    * ~No~
> We provide multiple opportunities to members of the community to use our services for free. The first day of access for anyone is always free (with a donation of cake recommended!) We have monthly free hot desk days through Jelly Liverpool, and our own weekly Maker Night and monthly Maker Day events which give free access to our workshop and equipment. Our events room is offered out to community groups for free if their event is free to attend by the public.
> Outside this we have low pricing and encourage people to be a member for £10/month for further reductions. We charge £12/day (£10 for members), then £35/month (£25 for members) for out of hours access, and then further monthly options for further access of £65 (£50), £80 (£70) up to £180 (£165 for members) to have an allocated desk and access to all services and meeting rooms. We also hire out our events room and meeting rooms for £100/day for private events.
* Do you offer any facilities for use to non-members or other groups within the community e.g. schools, residents groups etc.*
    * Yes 
    * ~No~ 
* Does the organisation provide training or education for its members or other groups that use the facilities?*
    * Yes 
    * ~No~ 
* Provide details*
> Our regular Maker Night and Maker Day events allow people free opportunity to receive training in the use of our equipment. We also work with a variety of partners to provide further training in a variety of subjects including getting young people into employment, making use of the various equipment we have in the space, and improving software development skills. We also host peer learning events such as linux user groups, a plastic recycling group, amazon web services, and many more.
 
* If applicable, tell us how these schemes encourage any particular groups to develop their skills e.g. young people, disabled, retired etc.
> We have worked with partners such as Sale Sharks and The Prince's Trust to provide training for young people to improve their employability. We have also provided work experience placements to students between the ages of 15-18 from the local area and also from overseas allowing them to develop their technical skills and also their independence. When moving to our current location we put a particular focus on making sure our space, including equipment in our workshop, is accessible to wheelchair users and others who would not be able to access equipment in a standard workshop.
 
* List any local or national affiliations:
> Living Wage Foundation, UK Hackspace Foundation, Fabric District Stakeholders Group
 
* Are there social facilities at the premises e.g. a bar or other:*
    * ~Yes~ 
    * No 
## Accounts and finance
As you are applying for help to pay the rates, we need to see information about the organisation’s income, expenditure and balances.
* Upload a copy of the organisation’s constitution or memorandum and articles*

* Upload a copy of your available audited or signed accounts:*

* Unless specifically mentioned in your accounts, provide details of any grant aid you receive from Liverpool City Council and other sources, and what they are for:
> We have not received any grant aid recently.
 
* Has the organisation’s financial year recently ended, or is it near to its end?*
    * Yes 
    * ~No~ 
* If the accounts are still being prepared, or you are near the end of your financial year, please tell us about anything that is likely to have a significant effect on the end of year balances and reserves:*
> Our 2017-2018 accounts will indicate that we had a surplus of funds, this was saved to allow fitting out of our new premises.
We are expecting our 2018-2019 accounts to show that we are running a healthy well functioning company. The only thing that will impact this in the 2019-2020 financial year is the backdated business rates, that we were in no position to predict the extent of.

## Further information
* If you wish to provide further information about the benefit of the organisation to individual groups and residents of Liverpool, please tell us:
> In nearly ten years of operation DoES Liverpool has been an important part in supporting many small businesses starting up in the Liverpool region. Some of these have continued with DoES Liverpool while some have expanded enough to move into their own premises. An example would be the smart sensor company Aeternum who originally chose Sensor City as their base but moved to DoES Liverpool for easier access to equipment and community. DoES Liverpool has envigorated their business helping them to grow at such a rate that in less than a year they have needed to move out and rent their own space. DoES Liverpool has been involved in a wealth of community events, from 3D printing prosthetics for children with FACT Liverpool, through "What Does Health Look Like" which enabled people to experiment with sensors to improve their health, "Plastic Playgroup" which gives people an environment to experiment with recycling plastics, many community groups hosted for free such as sewing club, Amazon Web Services group, Ladies of Code and many more. We also host a number of groups working to improve the environment and help Liverpool be more sustainable.

**Comment by zarino** [comment]
> How are the general public made aware of the facilities?

Do you think it’s worth mentioning our listings on sites like coworker.com, our social media channels, and meetup event pages?

> If you wish to provide further information about the benefit of the organisation to individual groups and residents of Liverpool, please tell us:

Engage Liverpool CIC is always very appreciative of being offered free space for their board meetings (via my membership) – I could rustle up a glowing quote for you if you think it’d be useful?

**Comment by johnmckerrell** [comment]
FYI this is the information about the form, so this tells us what we're trying to cover in our application:
> We have discretion to grant relief of up to 100% of the rates on properties occupied by certain non-profit making bodies, or in the case of registered charities that are entitled to 80% relief to top up the relief to 100%. These include charitable, philanthropic, religious, educational, social welfare, science, literature and fine arts.

> When making a decision on discretionary relief, we'll look at **the contribution that the organisation makes to the area**.

(emphasis mine)

**Comment by johnmckerrell** [comment]
I've put it on a Google Doc for now to make interaction a bit easier.
https://docs.google.com/document/d/1i_Be9Dv_wHxrojvKDOpR8G4KqnXvps_W0gNeP1j9tDs/edit

Feel free to request access.

**Comment by johnmckerrell** [comment]
I was asked about deadlines. Right now we're expected to make a large payment (which we can't afford) by next Wednesday 25th September. We would want to apply for this relief and then inform them that we have done so and ask for a stop on collection, so ideally we would get this in this week.

**Comment by johnmckerrell** [comment]
I have now made this application using the information above (pretty certain it matches). I have also emailed the business unit asking them to put a pause on payments but I will probably call them in a few hours to make sure. Also CCed Councillor Nick Small who has been quite supportive.

**Comment by johnmckerrell** [comment]
I called them later, was told that they couldn't put a hold on the account and that we should make a payment so have now made the first payment of £3,668.15. Probably not much left for this issue now but I'll keep it open until we hear back.

**Comment by johnmckerrell** [comment]
We were turned down for this, around "The surplus of funds and the distribution / use of such funds". Which I take to mean "you have too much money" which seems surprising to me as I'm sure I would have noticed!

The accounts that I submitted with the application said that we had £2,262 cash in hand, it also mentions ~£2k of debtors and also £10k of assets. The assets are basically the fit-out that we had done when we moved into the tapestry so I'll have to explain that to them in an appeal.

**Comment by johnmckerrell** [comment]
I've now appealed against this. Apparently they can take up to ten days to reply to emails although the previous one took longer.

**Comment by johnmckerrell** [comment]
Still waiting to hear back. I called them just now to ask about the additional surcharge and extending the payment plan (and to see if there was any news on the appeal). Unfortunately over the phone the only thing they could tell me was that there was no news. I've emailed the other two questions over to the business unit now.

**Comment by johnmckerrell** [comment]
I just called again (10 minutes), she noted that it had been a long time without an answer so she said she'd chase it up and took my phone number so hopefully we'll hear... something... before long.

**Comment by johnmckerrell** [comment]
We've had an email today saying that the appeal has been sent to management for a decision to be made. No suggestion of how long that will take though.

**Comment by johnmckerrell** [comment]
Apparently the information is being prepared tomorrow but then it depends when they meet, and then the reply needs writing up so there could still be months. One useful piece of information I got this week though is that payment collection has been paused while the appeal is reviewed.

**Comment by johnmckerrell** [comment]
We have been rejected on appeal. Next steps are #1397 to get an improved plan and #1251 to get the amount down.
