### ISSUE TITLE
Contest business rates bill

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1251]
We have been sent a business rates bill that is very high and is back dated to April 1st. The bill has the rateable value set at £21,250 (of which we pay approximately half) which is much higher than the £12,000 which would be required to get full small business rates relief.

We were not expecting this. We had so far been working to estimations as the re-rating of the building hadn't been completed but as an example the whole building had previously been rated at a value of £[18,250](https://www.tax.service.gov.uk/business-rates-find/other-properties/valuation/20997288000/17312560000?uarn=9320280000) so if that value for the whole building had even doubled, our portion would still be less than £12k. As it is, our floor alone has been rated higher.

The bill sets out a payment plan that has us paying ~£2085 each month until February and also ~£11.5k within 14 days. This would be impossible for us to pay.

It seems there's a few ways that we can tackle this. We can contest the valuation, for example we are being charged over £50/square metre whereas all but one of the other properties on our road are £30 or under so this is clearly a very high rating for the area. We can also look at re-rating so that the soundproof room is considered a separate unit and the tenants become liable themselves, for which they would get full small business rates relief. The hope would be that we can get our rating down enough to get under the relief limit.

We can also apply for discretionary relief as a non-profit, this is separately covered under #1250 . We have previously applied for this and been turned down. In theory not a lot has changed about our business in this time but we have a higher profile and are in a regeneration area so hopefully we would have a better chance (we're still not limited by guarantee though, see #321 ).

@johnmckerrell will call to find out what we can do in the short term to avoid having to pay the large amounts straight away and to confirm whether we will automatically fail to get discretionary relief or not. @johnmckerrell also incidentally has a meeting with local councillors soon so will raise it there.

**Comment by johnmckerrell** [comment]
VOA 03000 501 501

Can't put a stop on it when it's at bill stage, because "we should have told them when we moved". Certainly not for contesting the valuation but if we do apply for discretionary relief too then I think the team who receive that will be able to put the pause on. They can be contacted at: business.unit@liverpool.gov.uk

Also we should be able to apply for discretionary relief even though we've been rejected in the past.

**Comment by johnmckerrell** [comment]
I've emailed Mason Owen who perform contesting business rates as a service to find out if they can help us and how much they'd charge.

**Comment by johnmckerrell** [comment]
I've also emailed Andrew Gardner surveyors for a quote, once that comes back we'll decide between him and Mason Owen and make a start!

**Comment by johnmckerrell** [comment]
We should do an initial challenge ourselves: https://www.gov.uk/guidance/how-to-check-your-rateable-value-is-correct

**Comment by johnmckerrell** [comment]
Regarding the transitional surcharge I've just emailed the council business unit the following:

> I also have to further contest the transitional surcharge that we have been charged. I believe this is a charge that relates to the building's valuation and not to our own unit. The building that we are in was given a rateable value of £28,750 on 19th August 2014 and this was reduced to £18,250 on 1st April 2017. My understanding is that the transitional surcharge relates to a change in value of a property to cushion large changes so that neither the council or the business owner sees a large change in the amount that they pay. I can understand that in that case the building may have been in a transitional period and so paying a transitional surcharge. The problem however is that the building was then split up and the units re-rated on the 2nd February 2018. A result of that is that our single floor now has a rateable value of of £21,250. Thus the rateable value of the building has gone back up again, in fact adding up the current rateable values for all the units in the building comes to £74,600. There is no way that this should result in an additional fee on top, in fact it should surely activate the transitional relief in the other direction. I do not see that the existing transitional period should still be valid once the building was split up and re-rated, especially as the total value of the building went up to more than double the original value! (This value is frankly ridiculous but I'm well aware it is not within your control) Please can you review this again and if there's anything that you can do to remove this charge, please do so.

To be honest I wouldn't be surprised if this aspect was also in the hands of the VOA but I'll see what they say.

**Comment by johnmckerrell** [comment]
@mattwilsondotuk offered this link that looks helpful https://www.valuationtribunal.gov.uk/

**Comment by johnmckerrell** [comment]
I'm looking at contesting the valuation now. It seems we have to do it for one of a small set of reasons. It seems that the following two options are our most applicable ones:

> I want to (pick the main one that applies):
>  * confirm the property details are correct or update them to reflect a change (for example if the floor area measurements are incorrect, or you’ve added something to the property)
>  * tell you this property has been split into more than one

As we intended to split it out to make the soundproof room separate that would suggest we need to use the second option here and then as part of splitting it out, also mention the other changes.

The following screen says:

> Split this property
> 
> You’ll need to provide supporting documents that include:
> 
> why the property should be split
> details of the new properties you want to create, including floor areas for those you own or occupy
> the date the property should be split
> It’s important to provide as much evidence as you can of any changes as it will help us make an accurate valuation.

And after that we get:

> 
> Supporting documents
> 
> If there are any changes to your property that you have been unable to tell us about in the form, you can upload documents to give us more information.
> 
> You’ll need to include the date of the changes.
> 
> You've told us your property should be split from another.
> 
> Please upload documents that show:
> 
> why the property should be split
> details of the new properties you want to create, including floor areas for those you own or occupy
> the date the property should be split
> You can upload documents:
> 
> only PDF and JPEG files can be accepted
> only 10 files in total can be accepted
> you can't upload more than 50MB of files in total
> each file must be less than 10MB in size

I suggest we might send:
 * A covering letter explaining what we think should happen:
    * split out Find Out's room, explain that the reason we're doing it so late is because we were waiting for the valuation and it only came in September, and since then we've been in communication with the council about getting relief (I don't know if they'll actually care about why we've taken so long).
    * Reduce the area because they did it Gross Internal Area on the whole floor so included Jason's landing and staircase, we will do Net Internal Area and remove the network cabinet, the toilets, structural walls and columns, unfortunately it doesn't look like we can exclude much else (going by [this list](https://www.gov.uk/guidance/how-non-domestic-property-including-plant-and-machinery-is-valued#what-counts-as-plant-and-machinery)
    * Reduce the value because the entire space is not an office, argue that in fact only room 29 is an office.
    * Reduce the value because we have been rated as the most valuable property in the area which isn't true, even new builds have been rated lower (I think, check!)
    * Reduce the value because our rateable value here is much more than Hanover Street.
 * A copy of Find Out's first bill to "prove" they are subletting? We might need to "write up" our agreement with them, so possibly it would be better to leave out the bill and just state as fact that they sublet and are responsible for rates.
 * A copy of the layout of the space, overlaying with colours the areas that we believe are covered by us and those covered by Find Out. Perhaps highlight the server cabinet and toilets to note why we believe they're excluded.
 * A separate copy of the layout identifying the usages of each area in our space. Meeting rooms, event space, office and the large workshop areas. I'm not entirely sure this will actually help so should investigate this more.

**Comment by johnmckerrell** [comment]
@zarino would you have any time available to help with this? Specifically providing the two colour coded plans I mention at the bottom of my previous comment, and perhaps while you're in there you could look at working out the square-metre-age too? That would be for Find Out's room and then for our usable spaces (as defined in previous comment also). I imagine we don't need to be too accurate about it as I'd expect they would come to measure themselves if they were actually going to make a change (but I could be wrong on that so definitely don't over-estimate!)

**Comment by zarino** [comment]
Approximate measurements of net internal area (excluding structural walls):

## Room 29
10.24 × 6.39 m
**= Total 65.4336 m²**

## Events room
10.24 × 6.39 m
**= Total 65.4336 m²**

## ‘Workshop’
1.10 × 2.50 m (walkway to Room 29)
4.70 × 2.30 m (meeting nook)
2.28 × 0.30 m (entrance to meeting nook)
5.80 × 2.30 m (kitchen)
2.28 × 0.30 m (entrance to kitchen)
15.85 × 2.08 m (area from double door entrance, across to fire exit)
11.84 × 4.30 m (top half of open workspace)
1.66 × 3.00 m (far end of vinyl cutter space)
8.80 × 6.90 m (bottom half of open workspace)
3.40 × 3.75 m (woodworking room)
6.14 × 3.10 m (laser room)
**= Total 209.632 m²**

## Dinky
5.20 × 6.00 m (dinky)
1.00 × 1.00 ("cupboard" space behind dinky door)
**= Total 32.2 m²**

## Find Out
4.00 × 2.08 m
**= Total 8.32 m²**

## Network cabinet, toilets
Not measured.

**Comment by johnmckerrell** [comment]
@zarino when you did that did you have chance to do the two colour coded plans I mentioned?

**Comment by zarino** [comment]
I didn’t! How’s this?

![DoES-floor-areas](https://user-images.githubusercontent.com/739624/87411555-cb646080-c5bf-11ea-85d5-866d5d02e896.jpg)

**Comment by johnmckerrell** [comment]
Great, thanks!

**Comment by johnmckerrell** [comment]
I submitted this last night. In the end I went with the first option not the "split into multiple units" option because I didn't want that to be the focus. Really not sure what will happen but 🤞 , doubt anything will happen quickly anyway.

**Comment by johnmckerrell** [comment]
> We have received a Check case for the property on 17 July 2020.
> ...
> You don't need to do anything. We will consider the information and evidence that you have submitted as part of your Check.
> ...
> We aim to provide a decision on this Check case within 12 weeks. We prioritise cases from smaller proposers. Some complex cases may take longer to resolve.

**Comment by johnmckerrell** [comment]
I had some feedback last week (27th). What I submitted was a "Check". It sounds like they are happy splitting the soundproof room out as part of this, although they still mention "once I have made a decision on this check submission" so perhaps that may still not happen. Apparently though we would then need to submit a "Challenge" about the incorrect valuation.

**Comment by johnmckerrell** [comment]
We got the splitting out approved which made very little difference to our rateable value but created a new listing for the soundproof room. We do now need to submit a challenge.

**Comment by johnmckerrell** [comment]
I've submitted a challenge. I calculated the valuation as £7,080 but I doubt they'll accept that! I included the following statement which should provide most of the information:

We believe that the valuation for our unit is too high for multiple reasons. Primarily this is because it has been rated at something like “Grade-A office space” when the unit is nothing of the sort. In addition the dimensions of the whole floor have been used when in fact the floor includes communal spaces. Finally the unit includes multiple types of space but they have all been assigned the designation “Office”. It is also worth mentioning that the value of the entire building was previously less than the amount that our single floor has been assigned.

I have included the previous valuation of the entire building.

I have included three photos as a representation of the state of the unit when we took it over, indicating that it is not Grade-A office space.

I have included three valuations for nearby properties that show a much lower valuation than the £57 per square metre that we have been charged.

I have recalculated the rateable value by splitting the unit into areas of different types, then using values from the valuations that I have attached to work out the values. I have included a plan showing how the different areas have been assigned. I did not find a valuation for “meeting room” so I have used “office” although if “meeting room” would be less that would be preferable. I have used the valuation for “hall” for our events room, perhaps this could also be used for the meeting rooms. I also could not find a valuation for “workshop” so used a valuation for “plant room” that I found. The values I used are as follows:

Room 29
= Total 65.4336 m²
65.5 * 24 = 1572

Events room
= Total 65.4336 m²
65.5 * 16 = 1048 (taken from “hall”)

‘Workshop, etc.’
= Total 209.632 m²
210 * 16 = 3360 (Taken from “plant room”)

Dinky
= Total 32.2 m²
32.2 * 24 = 772.8 (Office)

Find Out
= Total 8.32 m²
8.3  * 24 = 199.2 (Office)

Toilets
= 9m²
9 * 10.67 = 96.03

Network cupboard
= 2m²
2 * 16 = 32 (Plant room)

Total = 32 + 96.03 + 199.2 + 772.8 + 3360 + 1048 + 1572 = £7,080.03

**Comment by johnmckerrell** [comment]
They've already been in touch basically to tell me I challenged on the wrong thing and need to re-apply. Good that they're on the ball though, the instructions given in the message told me to download a T012 (or TO12) form, when I finally found a link to it I got a 404 so I've gone through the challenge process (which I think is what they told us to do on the phone) and this time chosen a different reason for the challenge. It looks like because we've said we're in hardship they will look at it promptly.

**Comment by johnmckerrell** [comment]
Apparently they're coming for a look around on 29th April.

**Comment by johnmckerrell** [comment]
So the result of the visit was that they maintained their opinion. I contested this by email but they've come back with final conclusions that they are not going to make a change. At this point I don't think there's much we can do. To be fair even with arguments around size and use of the building they tend to use the rent as a big factor and our rent is close to our rateable value if I recall correctly.

**Comment by seanspotatobusiness** [comment]
Sorry if this is a stupid question but why doesn't DoeS qualify for 100% small business rates relief? It says here that below £12K rateable value qualifies for 100% SSBR: https://liverpool.gov.uk/media/1359002/ndr-2023-24.pdf

**Comment by DoESsean** [comment]
Unfortunately, our rateable value is CONSIDERABLY higher than that.

**Comment by seanspotatobusiness** [comment]
Oh, sorry. I thought it was 11K. Not sure where I got that from.

**Comment by johnmckerrell** [comment]
So £11k is the amount we have to pay. The rateable value of the whole unit is more like 40k, up from around 20k previously. You generally pay half of the value but they’ve also applied a transitional relief because it went up so much. Tbh it could be worth contesting again given that 6 months ago they said 20k was right!--Sent from my mobile phone hence brevity and errorsOn 27 Apr 2023, at 15:26, seanspotatobusiness ***@***.***> wrote:﻿
Closed #1251 as completed.
