### ISSUE TITLE
Pay ICO fee

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1253]
Had a letter about paying our ICO fee for our data protection registration.

I'll submit the direct debit letter as we get a reduction if we do that.

**Comment by johnmckerrell** [comment]
Have emailed direct debit letter. Will wait until we've had a reply before closing this (or they've taken a payment I guess).

**Comment by DoESsean** [comment]
Rang today, was told that they had received the mandate and were in the process of getting it actioned. This could take up to 14 days, but it's on its way.

**Comment by johnmckerrell** [comment]
"Confirming receipt of your direct debit instruction"
