### ISSUE TITLE
Internet to Martin's desk is flakey

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#126]
@mdunschen keeps having his Internet connection interrupted, which causes his VPN to drop.

He's got an Ethernet connection, wired through a small switch on his bank of desks (which the printer also connects through, so maybe that's why that's a bit hit-and-miss at times?), then through the big blue switch, then the gateway and finally the modem.

As a first test, he's bypassed he small switch on his desk (so the laser printer is currently off the network) to see if it's the switch at fault.

**Comment by johnmckerrell** [comment]
I often find that my ssh session has dropped, or at least paused. Sometimes it's better than others. I could see it being related, rebooting the router has helped with that (sometimes more than others). My VPN connection seems to be pretty stable but I think it's good at reconnecting so it might be dropping out and I just don't notice.

**Comment by amcewen** [comment]
I've not been seeing many problems with my ssh session (and hadn't had any trouble with it yesterday, FWIW), I'm tunnelling IMAP over it, with my email client running pretty much all the time, so there'll be regular traffic over it.  As a datapoint of some sorts.

**Comment by DoESsean** [comment]
Have just spoken to Martin and he says that using the new switch has helped massively. No problems since that solution has been implemented, so I'm closing this issue.

**Comment by amcewen** [comment]
I'm pretty sure we haven't bought a new switch, but Martin said he'd swapped out a network cable, so that could have improved matters.

**Comment by mdunschen** [comment]
I'm pretty sure we haven't... really means: 'No, we definitely haven't'. :)
