### ISSUE TITLE
Prepare the events space as a green room for Festival of Maintenance

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#1260]
Using the events space as a green room for Festival of Maintenance on Saturday 28th Sept 2019 is a nice way of telling participants at FoM about DoES and spreading the word ;)

To prepare for Saturday Morning:

- [ ] FoM organiser phone nos. (Naomi, Jackie, Laura) 
- [ ] Setup the big telly in the Event space with the livestream on low volume to keep tabs on schedule (we can use an old laptop of @amcewen )
- [ ] What is DoES Poster
- [x] Check we can use a 'backstage' exit behind the presenters for quicker access to DoES for green room and giving attendees promotional tours of our available desks and facilities ;) 
- [ ] Space to dump bags and sit and prepare or escape
- [ ] Coat rack
- [ ] Coffee & Tea  
- [ ] Biscuits
- [ ] Big Water jar/jug 
- [x] DoES WiFi Poster
- [x] info pack with schedule for DoES 
- [x] Taxi number
- [x] Prep Wheelie pad for the remote speakers and check it's cool with @goatchurchprime

**Comment by ajlennon** [comment]
- [ ] Prosecco (?)

**Comment by amcewen** [comment]
The green room was set up and used, we even live-streamed the conference onto the big TV.

Thanks @cheapjack and Hwa Young for staffing it on the day!
