### ISSUE TITLE
Change the website to explain what "£10/month membership" is

### ISSUE THREAD

**Issue by rah2501** [DoESLiverpool/somebody-should#1261]
[This page](https://doesliverpool.com/services/) lists a number of services with their prices.  Above the services are the sentence

> All prices discounted if you take £10/month membership.

However, I cannot find any information on this page about what "£10/month membership" means.  In fact, I can find no information about this "£10/month membership" anywhere on either the website or the wiki.

Somebody should sort this out and make it clear what "£10/month membership" is.

**Comment by DoESsean** [comment]
I've added a page on the website explaining membership, and linked to that from the prices page.

Hopefully that now makes sense but, if anyone thinks there needs to be further info, let me know.

**Comment by johnmckerrell** [comment]
I find "£10p/m membership" quite confusing, think "£10/month membership" would be right?

Can you link to the membership PayPal button from the page too? I think it was linked to in @amcewen's recent Google Group post.

**Comment by DoESsean** [comment]
Done and done. And I mean done.

**Comment by johnmckerrell** [comment]
Apparently you didn't mean done though! Still says "Ten pounds pence per month". I've taken the offending "p" out.
