### ISSUE TITLE
Switch to plastic-free tea bags or leaf tea

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1263]
Some details here

https://www.1millionwomen.com.au/blog/tea-bag-or-not-tea-bag-guide-plastic-free-tea

**Comment by DoESsean** [comment]
Given that Yorkshire Tea seems to be the tea of choice, for the most part, we [should be ok.](https://www.yorkshiretea.co.uk/brew-news/our-use-of-plastic)

**Comment by ajlennon** [comment]
Is Yorkshire Tea ok? I did look on that list as it's my goto tea on the occasion I drink tea but I didn't see it?

**Comment by ajlennon** [comment]
Ah! I missed your clever use of linkage. Well fantastic. I shall close this down then :-D
