### ISSUE TITLE
Test if LaserCut53 works well on Linux as is being reported online.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1264]
https://github.com/cchaine/LaserCut-Linux
http://wiki.makeitlabs.com/training/laser/lasercut53personal

There's multiple examples now of this working, so I want to test how well this works. I'll set this up on something like an Atomic Pi computer since they're cheap (£30-40) and would be nice and simple to deploy around the space if this were to be a success.

#990 #1127 need something like this to be easy and simple.

If this works out, I'm going to experiment with two build systems to satisfy #1127. The first is debootstrap which deploys debian systems from a simple DSL like Docker or Ansible. The second is cloud-init which I'm seeing used and advertised every single time I install Ubuntu on something.

This would allow us to make simple text files that get the system up and running to a base working state without having to store large multi-GB backups of machines. They would be instantly re-deployable. Although we'd keep a hard backup just in case.

There is no software that I'm aware of on these systems that does not work in Linux, including Corel Draw which runs natively. If this works out it offers us a lot of re-deployability and maintainability for the systems at does.

**Comment by MatthewCroughan** [comment]
It should be noted also that I intend to get to this once I've closed a bunch of other issues I've opened up that I haven't forgotten about, I don't want to clog up the issue list with stuff I'm never going to get done.

**Comment by norru** [comment]
Also have a look at this perhaps? 

https://github.com/t-oster/VisiCut

Got the link from this thread.

https://www.cnczone.com/forums/lasercut/187766-alternative-lasercut-5-3-a-2.html

**Comment by MatthewCroughan** [comment]
@norru I hadn't seen that, you and this thread are suggesting that this can be done with the existing controller for the machine? That's quite an amazing thing if so.

**Comment by norru** [comment]
@MatthewCroughan I have no idea of what can be done, I just sniffed around. I am very keen of advocating the adoption of Free Software as often as we can :).

For the Kinetic CNC machine I managed to use FreeCad on Linux (also available on Windows!) rather than Fusion360 (Windows only), thanks to @goatchurchprime who kindly contributed a postprocessor for our Kinetic NC!

Perhaps a similar thing is/could be made available for the laser cutters?

**Comment by MatthewCroughan** [comment]
@norru My plans on the CNC room are to run Windows on an Atomic Pi tiny computer and have the same setup, but this unit makes sense for longevity, since that room gets incredibly dusty and the lifespan of the existing computer is probably quite slim, not guaranteed at all.

Alternatively, @magman2112 has suggested that we have two systems, one for designing parts (outside the room) and one computer inside the room that is for milling them and sending them to the printer. In this ideal setup, the system inside the room would be running a very basic Linux environment for the purpose of sending gcode to the machine and not much more, alleviating errors andpreventing dangerous screw-ups as currently can happen with the buggy KineticNC software. I can make an issue about those bugs as they come up again in future.

This is also made more ideal by the fact that we have a resident programmer who can alleviate issues that people have with post processing, adding features, etc.

**Comment by MatthewCroughan** [comment]
As for the laser cutters, all of the software we currently use on them runs fine on Linux, (apparently even lasercut53), so the best case scenario is that we end up using the far more intuitive Visicut, the worst is that we end up with a fully maintainable and reproducible Linux system that runs lasercut53 instead of Visicut, both are good prospects in my opinion :)

**Comment by MatthewCroughan** [comment]
As an interesting update to my last comment, seeedstudio have released an x86 machine *more* powerful than the aforementioned atomic pi, and as small as a raspberry pi. 

https://www.seeedstudio.com/Rock-Pi-X-Model-B-4GB-p-4277.html

![image](https://user-images.githubusercontent.com/26458780/95483657-6c787280-0987-11eb-9564-d1784b7bc3e0.png)

**Comment by arthurrowland** [comment]
@MatthewCroughan could you check in on this one please - something still in the works, or one to close off?

**Comment by amcewen** [comment]
Given we're (slowly) planning to move all the machines over to Lightburn to match Tony, we'll be moving away from LaserCut on any OS, so closing this to tidy things up :-D

**Comment by MatthewCroughan** [comment]
FWIW LaserCut53 (not 50) does seem to work fine in Wine. No more LaserCut sounds better to me, thanks for closing.
