### ISSUE TITLE
Create better physical mailboxes

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#127]
The cardboard boxes are fine but really we should have something wooden, with names.

**Comment by DefProc** [comment]
I have then inklings of a plan from those stacking trays on @DoESsean 's desk, but I need to sketch it out.

**Comment by DoESsean** [comment]
We need a new solution for the new building, so I'm adding the Move tags to this issue.

We will need a more secure version too, as the likelihood is that my desk will be in the main section and therefore more accessible to anyone that walks in.

**Comment by johnmckerrell** [comment]
Closing this as superseded by #606 which has more detail.
