### ISSUE TITLE
Order some more filament for the Ultimakers

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1272]
We need some more filament for the Ultimakers.
Black and/or dark grey PLA have been requested.
We still have lots of the horrible brown colour so don't need any more of that.
Any other requests?

**Comment by MatthewCroughan** [comment]
I'm aiming to get some reels of black pla personally, that can hold people over sooner if there's none ordered in the next week.

**Comment by DoESsean** [comment]
If we can get some consensus by Thursday, I'll put the order in then.

**Comment by DoESsean** [comment]
Ordered from Filaprint.

**Comment by MatthewCroughan** [comment]
@DoESsean @jackie1050 These were ordered, and I've sene them around the space haven't I? Should this issue be closed?

**Comment by jackie1050** [comment]
Thanks @MatthewCroughan - I  put the filament on the shelf and the delivery note on @DoESsean desk. It's probably worth keeping an eye on this batch as there have been some breaks/snapping from the clear fluoro reel.
