### ISSUE TITLE
CNC Room has been left in a bad dusty state

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1278]
Whoever last used the CNC room, can you comment here as to why its been left in the state it is in this image?

The sidepanel for the computer has been left off, this makes me think the system is dead and whoever was last in tried to diagnose that.

![IMG_20191012_161906](https://user-images.githubusercontent.com/26458780/66703928-75504d00-ed0f-11e9-9761-984c0a843020.jpg)

**Comment by norru** [comment]
I've observed also the bad habit of people leaving the collet die on the bed, as it could easily get lost. Those things are expensive to replace.

**Comment by MatthewCroughan** [comment]
I won't close this issue until we find out who's responsible for leaving it like this, however I will make a separate issue about cleaning it.

**Comment by MatthewCroughan** [comment]
We can only assume it was someone outside of the general DoES crowd on a night like maker night, or Yusef who hasn't been in a while. Though at this point it's lost to time, so will now close the issue.
