### ISSUE TITLE
Look at ways to communicate better to people about DoES.

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#128]
Upcoming Events like The BuildYourOwn FACT show, Maker Faire Newcastle,  Liverpool Make Fest, possible extra maker nights etc are all big opportunities to raise awareness of DoES, I've found the business cards really useful,  when I try to explain to people where I work its great to just hand them a card that has all the basics on there: so if we all give them out when we are out and about meeting people thats probably a way more effective way of marketing than flyers sitting somewhere

**Comment by cheapjack** [comment]
@amcewen noted to revisit #32 on this :)

**Comment by DefProc** [comment]
From today's organiser's meeting: we should include info on how to submit posts for publishing on the DoES website at the end of each weeknotes post. 

[github.com/DoESLiverpool/weeknote-generator/issues/12](https://github.com/DoESLiverpool/weeknote-generator/issues/12)
