### ISSUE TITLE
Mount Rob's lovely artwork somewhere

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1288]
Rob's huge laser-cut artwork is currently cluttering up Room 29, we should mount it on a wall somewhere (until he wants it back) - @jackie1050 suggested the wall on the left when you go into the Events Space.

**Comment by magman2112** [comment]
Rob informed me yesterday that he will likely be taking this artwork to display in his new shop in the old Cains Brewery.

I will wait till he actually does this before closing the issue though.

**Comment by magman2112** [comment]
Rob has now taken this artwork to his new shop, so closing this issue.
