### ISSUE TITLE
Gerald front panel lock bent back

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1291]
The lever on the lock on the top right lock on Gerald's front panel was bent quite far back and the panels fell off while in use today. I bent it back and it seems fine now but it's quite strange that it would "spontaneously" become bent, I wonder if someone has been leaning on it or something, or maybe leaning on the lid puts pressure on it (though surely not?)

**Comment by johnmckerrell** [comment]
@DoESLiverpool/laser-maintenance just FYI

**Comment by jackie1050** [comment]
People often lean on it - I've mentioned it to individuals, but I expect we could do with a vinyl cut sign
