### ISSUE TITLE
Christmas Food Bank Drive

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1293]
Last year's food bank drive seemed to be fairly successful, and it's not like the number of people using food banks has dropped dramatically in the last year, so it makes sense to do the same again this year.

I've emailed the South Liverpool foodbank (as this has the most convenient drop off points for me, and I don't want to force others to do my dirty work) as to what they are most in need of, and asked whether there are additional things we should be looking at for a mid December drop off.

**Comment by DoESsean** [comment]
I've had a reply from Nicola at South Liverpool Foodbank, so we're going to go ahead and get this set up.

Brilliantly, her husband already uses the space for 3d printing, so she's offered to actually do the pick up herself, meaning we won't have to figure out a time or person to do it.

As well as this, it means that I'm going to set up a permanent space for foodbank donations. Although I don't think it will have as much traction for the rest of the year as in the run up to Christmas, it can't hurt to have somewhere that people can donate.

**Comment by MatthewCroughan** [comment]
Christmas is over now. Shall we close this? Or should we rename it to 2020 and try and set this up for 2020? @DoESsean

**Comment by DoESsean** [comment]
Let's close it - I don't think there are going to be enough people in to organise a communal drive this year (although, of course, it's my personal opinion that people should absolutely be helping out their local food bank where possible on an individual basis).
