### ISSUE TITLE
Sophia ghosting when trying to cut out Permission to Make tags

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1296]
I was cutting Permission to Make tags at a laser induction on Thursday evening. Although the engraved parts were fine, the line engraved letters were very wobbly and there was a fuzzy curve on the left hand side by the cut line. It also hadn't cut very well.
Perhaps an issue with the mirror?

**Comment by amcewen** [comment]
The laser was barely making it through the hole into the laser head (before it hits the mirror that bounces it down through the lens).  @dazz-ling realigned the mirrors, so AFAIK this is now fixed.
