### ISSUE TITLE
Get some more plates

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1299]
I'd like us to get some more plates, we were asked for some by people booking the events room today but I could only find 7 that were actually clean (with about 7 in the cupboard but dirty).

I checked in glasslines across the road but theirs were around £20 for 6 which seemed expensive to me, although they felt heavy and quite good quality. We should shop around a bit and see what else is available.

**Comment by johnmckerrell** [comment]
Ikea have a very cheap plate - https://www.ikea.com/gb/en/p/oftast-plate-white-30258913/

The ones that Fashion Hub have feel a bit cheap, this one may be similar, debatable whether it matters but I'd like us to be a bit more professional than having a random mixed selection. It would also be good to be able to use these for parties rather than getting disposable all the time.

**Comment by jackie1050** [comment]
I think are like the Fashion Hub ones, as they're glass too.
There are some ok plates in Asda for £2.50 each, not sure how they compare in quality with the Glasslines ones.
Flitighet from IKEA might be alright - they're only £1.50 each. I could probably make a trip to IKEA later in the week if necessary.

**Comment by amcewen** [comment]
Can we get @dazz-ling to get some decals and personalise them for us?  It's standard practice in restaurants in Italy to have the restaurant name on the crockery, and given it's not too tricky to do (AIUI, you just send off some artwork and get decals back to put onto crockery) it'd be cool to have a small DoES logo, or similar on ours.  Do Epic Sustenance? ;-)

(I don't think that would/should stop us finding and buying the plates themselves though, it's a secondary step that would be a bonus)

**Comment by amcewen** [comment]
@johnmckerrell  has bought more plates now (the glass ones from Ikea that he was also complaining about, but they're cheap and do the job)
