### ISSUE TITLE
Buy new sublimation mugs

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1304]
There are hardly any sublimation mugs left, and probably more people will want to use them in the run up to Christmas.
We should definitely get some more white mugs.The black thermochromic mugs are really interesting but the surface on several of them has been damaged. It could be that they aren't dishwasher proof, but would be OK if we told people that, but we should find out if that's the problem before ordering more: @dazz-ling do you know?

**Comment by dazz-ling** [comment]
Hi.
The black ones aren't dish washer proof. The white ones are more
christmassy friendly anyway. Worth looking out to make sure it's ones that
come with boxes

**Comment by jackie1050** [comment]
Thanks - good to know

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DoESsean** [comment]
I've ordered a load of plain white ones which will be delivered tomorrow.

I've gone with [these ones from eBay](https://www.ebay.co.uk/p/White-Double-Layer-Coated-11-Oz-Large-Handle-Sublimation-Heat-Press-Mug/1862124002?iid=302776359387&chn=ps&norover=1&mkevt=1&mkrid=710-134428-41853-0&mkcid=2&itemid=302776359387&targetid=522579804663&device=c&mktype=pla&googleloc=9046552&poi=&campaignid=6744139827&mkgroupid=78343140366&rlsatarget=pla-522579804663&abcId=1139126&merchantid=101765586&gclid=EAIaIQobChMI2KTogo7T5QIVjbHtCh3vmAXLEAYYASABEgKkm_D_BwE&thm=10) as the reviews are excellent, they're a very good price and will be here quickly.

**Comment by amcewen** [comment]
I assume these came and have been used up, see #1707 for the latest order :grin:
