### ISSUE TITLE
Dishwasher misbehaving

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1307]
The dishwasher seems to be having issues. I put it on at around 5pm usually on the usual basic program, later in the evening it was groaning and hadn't finished, looked inside and there has been some water and the tablet has mostly dissolved but there is still some remnants. I turned it off for a few seconds and it let me set the usual program and turn it on but it just groaned again and was still doing that this morning. I've turned it off for now, inspecting the bottom there was a milk bottle top and a cable tie in there but I don't think either would completely stop it draining. I've realised now that the lights were probably indicating a specific error so I'll try again later and note the error down.

**Comment by johnmckerrell** [comment]
Still not working. It's showing a flashing left light, static right light. Which apparently is:

> E1 or E9 – Overfill Issue

> The flood protection system has been activated which means the water level in your dishwasher has reached a higher level than it is supposed to. This could be caused by a faulty valve that lets water into your machine, a blocked filter stopping water from draining or excessive foaming as a result of adding too much detergent.

From: https://www.espares.co.uk/advice/careandmaintenance/smeg-dishwasher-error-fault-codes-using-5-programme-leds

The drain tube seems fine though and the filters inside are not blocked. There might be a separate filter that's harder to get to that needs unblocking. I undid two screws at the front near the bottom of the unit but that front panel didn't seem to move, rather the sides moved out.

There's more information on the link above about taking it apart, also some more info here which might be useful if anyone feels like investigating tonight:

https://www.ukwhitegoods.co.uk/help/fault-codes/dishwasher-fault-codes/2927-smeg-5-led-dishwasher-flashing-lights

**Comment by amcewen** [comment]
Did you try the tilting it back ~15&deg; trick that [seemed to fix it last time we had a similar issue](https://github.com/DoESLiverpool/somebody-should/issues/1007#issuecomment-447667194) (that does dump a load of water onto the floor, so needs towels deployed before you try it)

**Comment by johnmckerrell** [comment]
Aha, no I did not.

**Comment by johnmckerrell** [comment]
Yes that worked. Seemed to be working fine. Water came out to the sides which surprised me.
