### ISSUE TITLE
Copy about DoESLiverpool for the Hannah Directory

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#131]
I was asked a while back if we'd like to be included in the printed and online **Hannah Directory**  and gave them a tour of the space with Neil from ReDock. http://www.hannahfestival.com/hannah-directory-festival/
The actually printed publication will be made by Textbook Studio:
http://www.textbookstudio.co.uk/

I thought it was a good idea as although visual arts based it has alot of crossover with craft, tech and maker communities in the North. It's free to have a page and they just want an image and some text on who we are and what we do. There's no advertising and its just a labour of love (and possibly art) as far as I can see. I've also agreed to host a launch event i.e. hand out copies of the book at Maker Night on the 10th June 2015 at 6pm, if there are no objections, so I will be around to manage and lockup for that one. I dont think we will get much new members from being involved but makes sense to be on something cross discipline that tries to represent interesting stuff in the North, which we are!

I've drafted the copy on this PiratePad 
http://piratepad.net/ryZSV2Zy80
so if you can have a quick look and amend I can get it to them for the **deadline** which is **this Friday** If I dont hear will assume its good to go and send to them end of play Friday

I thought this is a good photo for it
https://www.flickr.com/photos/amcewen/16110088224/

![image](https://cloud.githubusercontent.com/assets/128456/7048937/bd75e498-de0d-11e4-9fe3-b7c1a89266be.png)

**Comment by DoESsean** [comment]
Looks good to me.

I've added an email address (hello@) as a contact point.

**Comment by cheapjack** [comment]
##What is DoESLiverpool?

###DoES Liverpool is a community
* First and foremost DoES Liverpool is a community of people with a diverse range of skills and interests. 
* By joining the DoES community you will get to mingle with entrepreneurs and company founders, artists and makers, developers and hardware engineers, academics and students (and many people that are less easy to label).
* You can also be part of our community though our Google Group.
http://doesliverpool.com/get-involved/

###DoES Liverpool is a place

We are a co-working space located in the heart of Liverpool. Desks are available to rent by the month or by the day.  The DoES workshop is well equipped with a range of electronics equipment, 3d printers, vacuum former, CNC mill and laser cutters.
* DoES Liverpool host events
* DoES Liverpool organises a range of regular and semi-regular events.
We also host a number of events run by different people.
###DoES Liverpool is a company

* We are a Community Interest Company. This means that any profit we make is fed back to help the community – making the space bigger, or buying more useful bits of kit.
What do we aspire to be?
* We want to be the place where you do your best work.
* We want to be the natural home for startups and businesses in Liverpool and beyond.
* We want to be a welcoming and friendly environment that inspires you and fosters collaboration between you and other community members.
* We want to stay true to our roots. We are community based and we want to keep the freedom that that brings.
* We want to support the growth of the region in a meaningful way – by doing rather than talking about it.
* Most of all we want you to be a part of our community and help us grow. If you would like to get involved please get in touch! hello@doesliverpool.com

***DoESLiverpool
Gostins Building, 
4th Floor. 
32-36 Hanover Street. 
Liverpool 
L1 4LN. 
http://doesliverpool.com
hello@doesliverpool.com
[@DoESLiverpool](http://twitter.com/DoESLiverpool)***

**Comment by cheapjack** [comment]
Ok I've added stuff about maker night during their launch week and formatted it and stuck it [here](https://github.com/DoESLiverpool/somewhere-safe/blob/master/HannahDirectoryCopy/README.md)

Hope that's ok, seemed a handy thing to have formatted on the repo somewhere not just in the issue comments, but didn't warrant its own space.
