### ISSUE TITLE
Sophia's bed is out of alignment

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1310]
Sophia's bed has gotten skewed and so (a) isn't level and (b) doesn't move up and down.

**Comment by johnmckerrell** [comment]
Removing the broken label from this as it has now been fixed but leaving the issue open until the process has been documented.

**Comment by magman2112** [comment]
I had some time to check the bed levelling on Sophia yesterday. I found the bed to be mostly level (but adjusted it anyway]. There was some debris under the honeycomb bed as well though, which likely caused some of the issues. This has all been cleared out now.

Closing this issue, as it is a duplicate as well.
