### ISSUE TITLE
Buy some more hacksaw blades

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1311]
The hacksaws have rather blunt blades on them.  We should pick up some more blades.

**Comment by DoESsean** [comment]
Is it the normal hacksaw or junior?

[These seem reasonable on Amazon](https://www.amazon.co.uk/HAUTMEC-Replacement-BI-Metal-Grounded-HT0016-CT/dp/B07C75CPRG/ref=sr_1_2_sspa?adgrpid=48685280610&gclid=EAIaIQobChMI9cyamdTk5QIVAsreCh1muQvuEAAYASAAEgKilvD_BwE&hvadid=259080416309&hvdev=c&hvlocphy=9046551&hvnetw=g&hvpos=1t1&hvqmt=e&hvrand=15523516836563921751&hvtargid=kwd-325916913244&hydadcr=28149_1752716&keywords=hacksaw+blades&qid=1573561189&sr=8-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFNR1RSRjNXVldNT1kmZW5jcnlwdGVkSWQ9QTAzNDYwMTcxVlJNSkdVRFJMVVQmZW5jcnlwdGVkQWRJZD1BMDE5NTE5MDFFQlAwQ1FYUEQ5UTAmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl)

**Comment by amcewen** [comment]
Normal.  We've still got a few spare junior hacksaw blades (although I did replace one of them on Saturday too)

**Comment by DoESsean** [comment]
Grand, I've ordered the above.

**Comment by DoESsean** [comment]
Blades have arrived and are in the sawing drawer.
