### ISSUE TITLE
Fix the soldering station lamp

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1312]
The soldering station lamp isn't working - we need to investigate why, and fix if possible.

**Comment by magman2112** [comment]
I checked this with Chris a couple of weeks ago and it appears that the tube has died. We also checked the other magnifying lamp on the shelves as this appears to have a similar tube, but this was dead as well.

I have managed to identify some possible replacements at CPC, so have ordered a couple of these for delivery to DoES, hopefully in the next few days.

https://cpc.farnell.com/crompton-lighting/cir22spcw/210mm-22w-circ-flu-cw-g10q-4pin/dp/LP05002

**Comment by magman2112** [comment]
The replacement tube arrived today and has been fitted. The lamp is now working again.
