### ISSUE TITLE
Log a complaint about the council's phone service

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1316]
I tried to call the council twice yesterday and @DoESsean tried today, both times we were on hold for long periods and then instantly hung up on. This page[1] suggests we should make a complaint directly to the department which seems like it would be the business rates business unit, although I doubt it's really their problem if it's a technical issue but we're supposed to do that first at least.

Details of calls are:

* 0151 233 3008 - 2019-11-12 15:32 - 37 minutes - John's personal mobile
* 0151 233 3008 - 2019-11-12 14:53 - 25 minutes - John's personal mobile
* 0151 233 3008 - 2019-11-12 12:24 - 19 minutes - Seán's personal phone.

1 - https://liverpool.gov.uk/contact-us/complaints-and-feedback/make-a-complaint-about-most-council-services/

**Comment by DoESsean** [comment]
I've called today:

0151 233 3008 - 2019-11-12 - 19 minutes - from my personal phone.

**Comment by johnmckerrell** [comment]
Not really worth it now, bit late.
