### ISSUE TITLE
Buy more plasters for First Aid Kit(s)

### ISSUE THREAD

**Issue by DuncReid** [DoESLiverpool/somebody-should#1319]
I was just attacked by something sharp living under Sean's desk and went to the FA Kit by the main door for plasters.

I'm obviously not the first! :) Only two small ones there - now only one remains. Can we get a selection box put in there - I suspect plasters are one of our most common consumables 🤣

**Comment by chris-does** [comment]
[St John Ambulance Assorted Blue Detectable Plasters - Pack of 100](https://www.amazon.co.uk/St-John-Ambulance-Assorted-Detectable/dp/B00M35RM92/) has been purchased and will be delivered to DoES (addressed to @DoESsean) on Monday 18th November 2019.

**Comment by DoESsean** [comment]
These have arrived, I'll stick them (ha!) in the first aid box.

I'm also fascinated by what I have under my desk that attacks people...

**Comment by DuncReid** [comment]
It was small, green, furry & armed with fearsome teeth...

Or then again, it might have been an edge of a sheet of acrylic or similar that I walked into whilst distracted by She-Who-Must-Be-Obeyed's natterings about mugs! :)

No good creative work is ever complete without a blood acrifice so that's all good...



-- Sent whilst out & about : Please excuse brevity --
Duncan Reid : 07903 603518 : 0151 558 1020
The Duncan Reid Consultancy : SEO Consultants
The Old School, 188 Liscard Rd, CH44 5TN
Based Crosby & in Liverpool's Tapestry Building

________________________________

**Comment by johnmckerrell** [comment]
Just a note that I see in the Directors meeting minutes that Seán updated the first aid supplies in July. It seems surprising that we've gone through all the plasters since then, I wonder if we need labelling around the first aid boxes to make sure people report accidents, and also report when they use the last plaster!
