### ISSUE TITLE
The current clamps need to be reattached

### ISSUE THREAD

**Issue by skos-ninja** [DoESLiverpool/somebody-should#132]
The current clamps are not attached to Gerald or Sophia so have not been reporting any data. It would be good to get them attached at some point as this data is now being used by the [status](http://status.doesliverpool.com) so the data being relayed is incorrect!

**Comment by DefProc** [comment]
the leads on the clamps are very short, so they pull out easily for Gerald, and won't reach for Sophia. To make it more reliable, we should buy some 2.5mm audio male to female extension leads (can't remember of the top of my head if it's stereo or mono) to fix the problem.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
