### ISSUE TITLE
Missing retaining clip on ethernet connection to CNC PC

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1322]
Needs a new cable or a new connector

**Comment by MatthewCroughan** [comment]
I've got a spare long one I'm not using at home which I'll bring in later today.

**Comment by MatthewCroughan** [comment]
Replacing this tonight since nobody has done so yet.

**Comment by MatthewCroughan** [comment]
Since the cables are so deeply embedded in the mess, I'm going to solve this when I solve #1286

**Comment by arthurrowland** [comment]
I don't know how it came about, but can confirm this cable does now have a clip.
