### ISSUE TITLE
Gerald laser stopped cutting in middle of job at 1pm

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1323]
Laser was cutting fine and then laser stopped working while it was still moving.  There seems to be a strange whistle-hissing noise from the laser box when it should be cutting (when it is running).

**Comment by amcewen** [comment]
The [last time there were strange noises](https://github.com/DoESLiverpool/somebody-should/issues/987#issuecomment-442371037) it turned out to be arcing from the HT lead (obviously only check this if you know what you're doing around super-high voltages)

**Comment by magman2112** [comment]
I've had a look at Gerald and there appears to be arcing coming from within the Power Supply for the Laser Tube.

**Comment by magman2112** [comment]
We had another High Voltage PSU left over from #165 that was likely to be working, so I replaced the faulty PSU in Gerald and lo and behold, Gerald is back working again.
