### ISSUE TITLE
Gerald’s focus

### ISSUE THREAD

**Issue by JessCollinge** [DoESLiverpool/somebody-should#1328]
Gerald isn’t cutting to his best ability – I think his focus might need a tweak. If anyone has time this evening to have a tinker, I’m sure he’ll be grateful! 

Thanks

**Comment by magman2112** [comment]
I have refocused Gerald and also gave the lenses and mirrors a good clean, as they were all very dirty.

**Comment by magman2112** [comment]
Jess, it is also a good idea to assign a label for these issues, like I just added. Also, if you add @DoESLiverpool/laser-maintenance to your issue, this then gets emailed to the Laser Maintenance team, so the issue gets dealt with quickly. I just happened to be in DoES this afternoon and spotted your issue, hence the quick response.

**Comment by JessCollinge** [comment]
Thanks very much, Mike. I’ll make sure I put it under the maintenance label next time.
