### ISSUE TITLE
Strapline for DoES Mugs

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1329]
We want to send a load of mugs out into the world to advertise us a bit, and the 3 step plan is a great design for them.

However, we also want a little strapline that will tell people more about what we do and who we are, and, since we have such a lot of creative people here, I figured it made sense to ask you.

So, hit me with your best shot, everyone.

**Comment by amcewen** [comment]
```
Co-working.  Events.  Makerspace.
DoESLiverpool.com @DoESLiverpool
```

IMO it's not the "Liverpool's home for creative minds" or whatever that's missing - the 3-step plan provides that side of things (and in a way that doesn't merge into all the other "inspirational" straplines every other business has) - it's the this-is-what-we-actually-provide, and the contact details so anyone who happens to encounter the mug and doesn't have the first idea of what DoES Liverpool is can find out more...

**Comment by RussCoty** [comment]
Every department and almost every project in Sony used to have/has a 3 word slogan. For instance PLAY|CREATE|SHARE. It’s a nice succinct way of saying things.

Just a thought.

**Comment by johnmckerrell** [comment]
I quite like what @amcewen is getting at, it should be "coworking" though. Also feels quite punctuation heavy but part of that could be fixed by moving the @alias down a line (then it makes a triangle, is that a good thing?! :) Maybe the full stops could also be a grey rather than black (or even a colour, surely not?!)

http://www.deskmag.com/en/coworking-or-co-working-with-hyphen-252
(See comment right at the bottom about AP Stylebook being updated)

**Comment by johnmckerrell** [comment]
Might be a bit late for Christmas but just a thought that we should really offer to sell these as well as "send" them. Maybe at the Christmas market.

**Comment by zarino** [comment]
There is now [a 2022 mug design in Somewhere Safe](https://github.com/DoESLiverpool/somewhere-safe/blob/master/designs/mugs/2022%20mug%20220x90mm.pdf), featuring the tagline @amcewen proposed:

![2022 mug 220x90mm copy](https://user-images.githubusercontent.com/739624/174861187-5d240bfd-4bc8-4668-8e69-344db00a9acf.png)

**Comment by zarino** [comment]
I’m closing this issue in favour of https://github.com/DoESLiverpool/somebody-should/issues/976 which covers actually _producing_ this new round of mugs.

**Comment by amcewen** [comment]
Excellent, thanks!  I got as far as wondering exactly where to stick the extra text and realising that I didn't have InDesign(?) to modify the original design files, after I'd ordered more mugs.

Looks good.
