### ISSUE TITLE
Buy some more sublimation mugs

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1334]
There don't seem to be many left although it's only 24 days since #1304.

Sasha asked if we could get more of the black thermochromic mugs too - they seem a bit fragile to me  but it might be worth looking round to see what else is available.

**Comment by DoESsean** [comment]
I've ordered more white ones.

**Comment by amcewen** [comment]
The "Blank mugs" drawer has plenty of mugs in it
