### ISSUE TITLE
Buy some new scalpel handles

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1335]
Buy around 10 new scalpel handles - Swann Morton No. 3 are the best make

**Comment by DoESsean** [comment]
Is there any particular type? All the things I'm seeing say that they're for a certain number blade.

**Comment by jackie1050** [comment]
The type is Swann Morton

**Comment by DoESsean** [comment]
Ah, number 3!

I'd been looking at this on the email I'd got, which didn't show the edit to say No. 3. So now I've seen that on here, I look and feel a bit simple.

**Comment by DoESsean** [comment]
Right, those are ordered, should arrive on Monday.

**Comment by jackie1050** [comment]
These did arrive on Monday. I've attached blades to 4 of them and put them in the sharps drawer. The rest are in the top drawer under @DoESsean desk.
