### ISSUE TITLE
Make a Ready At Time clock for each of the 3D printers

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#134]
The UP printers give a pretty accurate time to build estimate.  If we move the hour and minute hand to match it, then people will know when the current build will be complete.  That way the next person knows when to start getting their model ready for the next build or, if the print is over-running too far into someone else's scheduled slot, ping the part build off and toss in the recycling.  

Should also have a slidy switch that says: "This build is PLA/ABS"

**Comment by DefProc** [comment]
Perhaps related to #130, to at least show free/busy remotely

**Comment by johnmckerrell** [comment]
Think we can close this as the printers give an estimate themselves and the others aren't running?
