### ISSUE TITLE
Get power supply for the electronic knitting machine

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1340]
We have a new (to us) electronic knitting machine which has been donated by Sam Meech. It's a Brother Electroknit KH-900 and needs a new power supply.

**Comment by magman2112** [comment]
I had a look for the Service Manual for this knitting machine and found a copy online. The PSU needed is 7.5V DC with a centre negative connector. It needs a power rating of 1-1.2A.

I will store the service manual in the usual Somewhere Safe space, then post a link on this thread.

**Comment by jackie1050** [comment]
I ordered a power supply from CPC - part number PW03074. It was despatched this morning.
Donation to DoES Liverpool

**Comment by jackie1050** [comment]
The power supply has arrived. It's by the knitting machine. I'll wait until @magman2112 is in for advice on adapting it for centre negative.

**Comment by JackiePease** [comment]
This was fixed - the knitting machine has been working
