### ISSUE TITLE
Organize a Friday epic trip to Bangor Fablab and then stay overnight in the Astral ship

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1343]
The [FabLab in Bangor](https://sites.google.com/enterprisebydesign.ac.uk/fablabenglish) was visited by 
@MatthewCroughan and @MethodDan last week, and report that it is very well stocked and has open days on Fridays.  

We go over, spend the whole day there (the coworkers could work, and the rest of us could play) and then we could drive up the hill and stay the night at @astralship, have a party and sleep in in the morning, because it's Saturday.  

How about in January, and then make it a possibility to have a regular event?

**Comment by MatthewCroughan** [comment]
https://github.com/carwyn

**Comment by carwyn** [comment]
"Other accommodation providers are available" there are a fair few bunkhouses in the area used by the mountaineers during peak season that are less busy in the winter (unless there is snow on the mountains). There's lots of scope to combine these trips with other outdoor (or indoor) activities too, for example https://www.beaconclimbing.com/ or https://www.zipworld.co.uk/

Closer to Bangor we might be able to get some good deals on rooms in the Uni halls too.

**Comment by carwyn** [comment]
In terms of the facilities available see:

* https://tickets.pontio.co.uk/online/fabfriday (main booking details)
* http://www.bangor.ac.uk/fablab (documentation and details on equipment)

"Arloesi Pontio Innovation" (API) have been sponsors and supporters of North Wales Tech since the very beginning, we work very closely with them and the Uni Science Park M-SParc.

**Comment by ajlennon** [comment]
I'm up for that!

**Comment by huffeec** [comment]
I'd be in too.

**Comment by carwyn** [comment]
Copying in @ehler

**Comment by goatchurchprime** [comment]
@ajlennon and @amcewen could both be free for Friday 17 January, staying over for Saturday.  

How soon could we book this?

**Comment by goatchurchprime** [comment]
@carwyn that pontio bangor university website has no zero listings for "FabFriday" when I search for it. I'd like to book it for one carload from Liverpool (participants yet to be determined.)

**Comment by carwyn** [comment]
@goatchurchprime you'll be wanting this link and then click the "Book Induction" button:

https://tickets.pontio.co.uk/online/fabfriday

There are sessions on the 17th, 24th and 31st of January. If there are a lot of you, I'd get in touch with @ehler though and work out a more specific plan.

**Comment by ajlennon** [comment]
Looks like I'm double booked for 17th @carwyn. I think 24th is busy and I'm at FOSDEM 31st.

Maybe we can do something in February?

**Comment by goatchurchprime** [comment]
@jackie1050, @MatthewCroughan, @huffeec  and whoever else is coming on Friday 17 January, I've bought my induction ticket for £0.00 from this website for Friday morning https://tickets.pontio.co.uk/Online/default.asp 
Follow the instructions to go through their system (see below).  I can't tell who we should phone up to check that the tickets have worked through and there's going to be someone there (and that we won't make it till 11). 
I am assuming I'm picking people up in the morning by about 9am and driving out there, and then we stay the night at the astral ship (still to be worked out).  
![image](https://user-images.githubusercontent.com/677254/72096307-df2dc200-3311-11ea-8340-b3c01c701581.png)

**Comment by ajlennon** [comment]
Hi - I can’t make it Friday unfortunately much as I want to, but what’s your plan Sat/Sun?

**Comment by amcewen** [comment]
I've bought my ticket.  I got a confirmation email, with a ticket PDF attached

**Comment by carwyn** [comment]
I spoke to @ehler about this and we wondered if a more bespoke arrangement might be better for the DoES visit as as-is you'd be contending with unknown availability of the people and equipment on the open Friday session.

What we could do is sketch out more of an Epic day for you to look at Pontio Fablab but also potentially bring in a visit to M-SParc (which from Jan 23rd will host the DSP development centre) and/or the School of Computer Science and Electronic Engineering. Could also tie this in to a North Wales Tech event or session while you are over.

What do you think?

**Comment by goatchurchprime** [comment]
If other people are using the kit on fridays thats cool. We can see what
people are doing in real life and talk to them. We absolutely dont want
this to be like some trade delegation ministerial tour show people in
suits, we need hours to sit around and do stuff.

**Comment by jackie1050** [comment]
@carwyn Booked for Friday. Hope @ehler is OK with this. If not please say.

**Comment by MatthewCroughan** [comment]
I'm also done booking my ticket. All in all it looks like it's going to be Me, Jackie, Julian and Adrian. Is that confirmed? @jackie1050 @amcewen @goatchurchprime 

I'll be staying in the Astral Ship along with Julian, is anybody else coming to the Astral Ship?

**Comment by MatthewCroughan** [comment]
I've received comment in person that Jackie, Adrian, Julian and I will be staying in the Astral Ship and are all attending.

**Comment by ehler** [comment]
I've had a staff member call in sick. Doesn't introduce any real issues, but I may be slicing my time more than usual.

PS. in RL you'll be asking to see John.

**Comment by amcewen** [comment]
We had a lovely trip over.  Thanks @ehler for showing us round!  There are a few photos in this week's #weeknotes https://doesliverpool.com/weeknotes/week-450-the-day-we-went-to-bangor/
