### ISSUE TITLE
Create a DoES Liverpool Digital Twin in Minecraft

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1344]
I thought we already had an issue for this but I can't see one so have created here.

This is actually a proposed digital twin for the Fabric District as, why not

![image](https://user-images.githubusercontent.com/1537834/70862164-9f510600-1f30-11ea-853a-a6a1bc9a052b.png)

We've made some initial progress on this which I've documented in the Wiki.

https://github.com/DoESLiverpool/somebody-should/wiki/Minecraft-Digital-Twin

Looking for enthusiastic people to check if my documentation works, explore, contribute idea, and most importantly build !!!

**Comment by ajlennon** [comment]
Also need to have a think now about how to architect MQtt support to link VR to IRL

**Comment by ajlennon** [comment]
Am thinking for starters we have the energy information easily accessible to could represent that above buildings somehow maybe?

**Comment by amcewen** [comment]
Well, Dan Hill was sketching that sort of thing in his [The Personal Well-Tempered Environment](https://www.cityofsound.com/blog/2008/01/the-personal-we.html) blog post (about 3/4 of the way down that).  I don't like his get-buildings-to-compete-with-each-other approach, but the sparklines are nice, and the floating text aligned with the front edge of the building is nice.

**Comment by ajlennon** [comment]
Oh yes that’s nice isn’t it. Dunno if we can be that sexy with the sparklines but would love to try. You think he’d be interested in chatting with us?

**Comment by ajlennon** [comment]
No progress on this for ages so closing for now
