### ISSUE TITLE
Button that raises the bed on Gerald isn't working

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1346]
While doing a laser induction yesterday, I was only able to raise the bed to 1mm short of where it should have been for cutting 3mm ply.
Arthur is cutting something at the moment and the up button doesn't appear to be working at all. He's had to rest the edges of the material he's using on wooden slats.

**Comment by jackie1050** [comment]
I've spoken to @magman2112 who hopes to come in tomorrow at some stage. We have been able to cut stuff today by using the solution above, but this isn't ideal for many purposes

**Comment by magman2112** [comment]
Added @DoESLiverpool/laser-maintenance

**Comment by MatthewCroughan** [comment]
I noticed this and forgot to mention it last night, Rob was the first to mention it at around 10PM.

**Comment by MatthewCroughan** [comment]
This may have something to do with the pictured region of Gerald. This is the wiring from directly beneath the control panel, beneath the bottom right corner of the bed.

![image](https://user-images.githubusercontent.com/26458780/70883086-c9a2d200-1fc9-11ea-9672-1d9c3cd43a8b.png)

Rob wiggled this and it seemed to allow the bed to go up again, this is still working as of this post.

**Comment by jadenoon** [comment]
The up button worked for moment this morning but will not work at all now to raise the bed.

**Comment by magman2112** [comment]
There was a broken connection on one of the limit micro switches for the bed screws, this has now been re-soldered and the bed motion is now working again. 

I will also check the level of the bed and adjust as required.
