### ISSUE TITLE
Standardise Creality 3D Printer Configurations

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1350]
As part of #1349 I've cleaned the 3d printing workspace and standardized their setup. Each printer now has its own 4 gang extension lead directly behind the unit. They are equally spaced to provide ample room for manipulation, and hopefully it stays as clean as it is now.

I've removed the PC I previously set up, as it didn't see much usage and was arguably taking up way too much space on the desk. 

Each printer is now running https://github.com/MatthewCroughan/octobalena

Once we set up OpenBalena in the space, we can close #933 instead of creating a cloud-managed Balena.IO account. This plays well into #18 which I'm a big supporter of.

I have flashed Marlin 2.0 with a standard configuration, uploaded the binaries to github so they can be reprovisioned at any time. That can be found here:
[Binaries](https://github.com/DoESLiverpool/marlinconfigs/releases/)
[Configuration](https://github.com/DoESLiverpool/marlinconfigs/)

# Cleaned
![image](https://user-images.githubusercontent.com/26458780/70890643-776bac00-1fdd-11ea-98bc-c3670ec64ff7.png)

# A Wall Socket Each
![image](https://user-images.githubusercontent.com/26458780/70890681-89e5e580-1fdd-11ea-8aa4-02995e34bba4.png)

# All running Octobalena
![image](https://user-images.githubusercontent.com/26458780/70890703-979b6b00-1fdd-11ea-9501-63258bb1ffeb.png)

**Comment by ajlennon** [comment]
Well done !
