### ISSUE TITLE
Internet or power off at does?

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1351]
At least 6 machines are not responding at the moment, is is the power or is it the internet? Was there a warning somewhere I did not see or is it spontaneous?

**Comment by johnmckerrell** [comment]
Yes the internet is down.

**Comment by MatthewCroughan** [comment]
@johnmckerrell if that means @mattwilsondotuk  is popping in, could you ask him to scan his email for the one from matthewcroughan@protonmail.com? :)

**Comment by johnmckerrell** [comment]
I think you just did.

**Comment by amcewen** [comment]
The Internet has been back on since a few hours after this was reported.
