### ISSUE TITLE
Accessible toilet door is sticking

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1368]
The door to the accessible toilet seems to be catching a bit at the bottom, so is tricky to close at times.  Presumably needs a touch more planed off where it's already had some planed off :-)

**Comment by johnmckerrell** [comment]
Actually it’s the threshold strip, I’ve been meaning to add an issue!

--

**Comment by johnmckerrell** [comment]
To confirm, the threshold strip on this door has lifted and won't now stay down. We need to screw it down to make sure it stays, similar to what was done in the main room.

**Comment by johnmckerrell** [comment]
I've put one screw in the end that was coming up and that's done the trick for the threshold strip. I couldn't find a countersink bit so I compromised so I won't put other screws in for now. The door was still connecting at the top corner too though so I tightened the screws in the hinges and that seems to have sorted that out too.
