### ISSUE TITLE
doorbot3 kindle integration has died

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#137]
it's currently complaining in screen:

```
Can't reach Kindle...
umount: /media/Kindle: not found
Oops #<Errno::EHOSTUNREACH: No route to host - connect(2)>
```

The kindle looks like it's on (static DoES Liverpool logo), but is not responding to any button input I've tried, including the power slider. I've tried rebooting the pi with no change.

**Comment by johnmckerrell** [comment]
I've "commented out" the bit about the kindle for now so the door does at least work.

**Comment by DefProc** [comment]
and again…
