### ISSUE TITLE
Set up new industrial sewing machine

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1375]
Mary Lamb from the Fabrication Studio just up the road has generously donated an industrial sewing machine to us:

![image](https://user-images.githubusercontent.com/108468/73123655-f1526600-3f89-11ea-96e5-e64f9bbf7e9c.png)

@goatchurchprime, @ajlennon and Zombie Chris did a sterling job of carrying it down the road.  We've left it next to the pigeonholes for now, but we need to:

 * [ ] re-jig the textiles area to give it a permanent home
 * [ ] create a page for it on the wiki
 * [x] give it a name (and update the label)

**Comment by jackie1050** [comment]
Cathy has brought in special zipper and leather feet, some spools and needles. These are inoe in the drawer in the sewing machine stand.

**Comment by jackie1050** [comment]
Caroline Corby has named the industrial sewing machine: "Gertie"

**Comment by Sean-anotherone** [comment]
Gertie has been positioned, requisite items, bobbins etc. are all in the drawer and a suitably extended mains lead has been installed.
It is fitted with a 5A fuse, the motor is plated for 2.9A so that should be plenty.
Closed #1375
