### ISSUE TITLE
Top up the oil in the sewing machine

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1376]
The industrial sewing machine has an oil-filled sump, and at present the oil is below the minimum level shown in the casting.

**Comment by jackie1050** [comment]
Cathy has brought in some sewing machine oil. It's on the stand with the sewing machine.
She believes it's ok to add it to the oil that's already there

**Comment by jackie1050** [comment]
I've added around half the oil to the sewing machine - it's now midway between the lower and upper limits.
I've labelled the remaining oil "Oil for the Industrial Sewing Machine (Gertie)" and put it in the poisons cupboard
