### ISSUE TITLE
Internet outage 1st Feb 2020 4am

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1379]
Just making a note that this happened whilst I was remoted into a machine, has been this way for about an hour now. Devices on my assigned IP are also inaccessible, not just the machine I was remoted into.

**Comment by amcewen** [comment]
It's hard for machines to respond when there's no electricity for them :-)

(Seems there was a power outage overnight for the whole building).

**Comment by MatthewCroughan** [comment]
@amcewen Oh I see! Damn. Guess there's no way to tell the difference from outside.
