### ISSUE TITLE
Rose the red 3D printer can't complete a print

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#138]
I've submitted a ticket with [3dprintingsystems.freshdesk.com], and I'm waiting to here back, but the red UP printer will get partway though a job and stop. Monitoring while it happens, the UP program reports that the bed temperature is too high (in the bottom right) when the print fails and the head holds position. The bed temperature is indicated above 110% and both the bed and print head temperature fall after the printer stops. 

Pre-heating the bed made this happen earlier in the print.

**Comment by DefProc** [comment]
From Bruce Jackson at 3dprintingsystems.com:

Hi Patrick,

This can be fixed easily by replacing the platform heater (that is the most common cause) 
First check which type you have, see this link:  http://store.3dprintingsystems.com/Parts/Platform%20Heater%20Sensor

To swap the platform heater V2/V3 in your UP Plus Printer:

 *  Remove the black table (2 screws)
 *  Remove the front two screws on the X axis arm
 *  Remove the back right hand side screw on the X axis arm
 *  Then remove the X axis cover
 *  Take a photo of the old cable layout and use as a reference to replace with the new cable.
    Ensure there are as few twists/bends as possible in the new cable as this will ensure it lasts longer.
    Replace cover and screws

**Comment by goatchurchprime** [comment]
Is it this one: 
   https://isupply3d.com/UP-Printer-Section/up!-printer-spares/up-platform-heater

We need to take the table apart and see if it matches the picture, then I'm happy to order

**Comment by amcewen** [comment]
We tried disassembling, and checking the heating element and thermocouple(/thermistor) - couldn't spot any problems with them (@defproc has found an alternative source of parts that should be lots cheaper than from Up).

So we tried another print on it, without any joy.

The error reported is:
    Platform too hot
    Err Code: 013; The platform overheat

**Comment by amcewen** [comment]
It had managed to get ~4mm high on a pretty large print (a Raptor Reloaded palm and some pins) in ABS.  Maybe try it with a tall thin model on ABS to see if it gets higher up - to check it's a problem with the amount of time the heater is on?  Or just buy a new heater element and thermocouple...?

**Comment by DefProc** [comment]
The platform heater we have is this one: https://isupply3d.com/UP-Printer-Section/up!-printer-spares?product_id=206

Although there are equivalent cartridge heaters (24V 30W, 6mm OD and up to 30mm length) available without the board on places like [ebay](http://www.ebay.co.uk/itm/12-24V-30-40W-Ceramic-Cartridge-Heater-for-3D-Printer-Heating-Element-Reprap-UK-/281649206489?pt=LH_DefaultDomain_3&var=&hash=item419399d4d9)

**Comment by cheapjack** [comment]
I've swapped Rose out while she's under repair with another Red Up from FACT which I will label to up our capacity over the weekend and next week for run up to the [Desktop Prosthetics](http://doesliverpool.com/events/desktopprosthetics/) I will place Rose in the plastic box the FACT one was delivered in. I will leave the cables where they are and the FACT UP Printer cables in that box also.

**Comment by DefProc** [comment]
I have a shorter, 30W rated element ready to try, although it would be good to try swapping the heater plates over as we have an extra machine in the workshop atm.

**Comment by DefProc** [comment]
My research seems to suggest that a connection issue is more likely than a heater or temperature probe failure to be the problem. 

My next step to fixing (before changing the heater with the new one, would be to check the ribbon cable for continuity (it undergoes a lot of flexing) to see if that's the issue.

**Comment by amcewen** [comment]
I powered Rose up last night at #makernight to remove the filament out of the way.  While doing that I noticed that the (not heated at all) bed was reporting its temperature as 363 deg C, which adds to the "it's probably not the heating element" argument...

**Comment by DefProc** [comment]
I've taken a look at the cable again, and found a fault with it. The white printed, static cable holder is poorly located in the slider, so it can move in use, and hit the side of the ribbon cable, just at the corner where it enters the socket (circled in cyan): 

![up_cable_failure](https://cloud.githubusercontent.com/assets/343000/10453730/851fd0ea-71a6-11e5-8c9b-62af7762cf4e.jpg)

Floating guide (red) can hit the moving carriage (cyan). 

The cable isn't available as an Up spare anywhere I could find, but it is a standard flat flex cable (FFC), and I was able to find a replacement. While the original cable was 450mm long, I could only find a 500mm replacement easily. 

The original part is marked: `AWM 20624 80C 60V VW-1`, although this is not a unique part number. the closest replacement I could find is a `Würth Elektronik 686708050001`, which is a 50cm long, 8-way, 1mm pitch, type-2 FFC (connectors on opposite sides). 

 * [Octopart](https://octopart.com/686708050001-w%C3%BCrth+elektronik-20372176)
 * [Digi-Key](http://www.digikey.co.uk/product-search/en?keywords=732-3531-ND)
 * [RS](http://uk.rs-online.com/web/p/products/7635454/)
 * [Farnell](http://uk.farnell.com/webapp/wcs/stores/servlet/ProductDisplay?catalogId=15001&langId=44&urlRequestType=Base&partNumber=1908489&storeId=10151)
 * [Rapid](http://www.rapidonline.com/cables-connectors/wurth-686708050001-flat-flexible-cable-contacts-on-opposite-side-8-way-1mm-pitch-54-8108)

I have one on order, expected tomorrow.

**Comment by DefProc** [comment]
So, I've had to make a custom order direct from an FFC supplier in China: [ffc_factory CUSTOM](http://www.aliexpress.com/store/product/CUSTOMIZED-ORDER-FFC0-5-0-8-1-0-1-25-2-54-pitch-4-5-6/722430_32473535388.html). 

I've specified: 

 * 450mm
 * 8pin
 * 9mm wide
 * 1mm pitch
 * type-B (contacts on opposide sides)
 * 20624 80C 60V VW-1

I've ordered 5, on the grounds that postage (£14 ~10days) is more than the item cost (66p per unit), so we'll see what arrives.

**Comment by DefProc** [comment]
The 450mm FFC cables arrived, and appear to be as specified, and visually match the original, though they're a little thinner.

I've installed a new one, so can someone with the UP sofware installed on a computer they have with them try the printer and check it prints please.
