### ISSUE TITLE
Events space doorbot (doorbot1) failing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1380]
Yesterday afternoon and again this morning, the doorbot on the Events Space had stopped responding.  The red light was showing, when cards were presented, but the door didn't unlock.

Power cycling the doorbot from the fusebox in the main room fixed the issue, but that's not a great fix :-)

**Comment by amcewen** [comment]
There's only 56K of real memory available, with KWeb3 using 27.5% and ruby 11.5%, so maybe it's a duplicate of #1139 (but on doorbot1)?

**Comment by amcewen** [comment]
I've killed KWeb3 on it for now, in case it's the memory problem, as that'll hopefully make it through tomorrow too (given the Global Game Jam is on), and we can investigate better next week...

**Comment by JackiePease** [comment]
There don't seem to have been any further issues
