### ISSUE TITLE
Buy new flat ended soldering tip

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1381]
There's a red light on the soldering station when the flat ended tip is used, and it doesn't heat up.
I'm guessing that means we need a new one?

**Comment by MatthewCroughan** [comment]
The red light shows up when the soldering iron detects that no tip is inserted. I suspect it does this through capacitance, if the other tips work then can you try and clean the metal on the bottom of the piece you're talking about? It might be that it's just not making good contact, maybe you need to push it down more?

**Comment by MatthewCroughan** [comment]
I've tested this tonight, I can't seem to get it to work despite cleaning, since @amcewen is the owner of it maybe he knows how these tips functionally actuate the detector inside the iron?

**Comment by amcewen** [comment]
I don't, but given the other tips seem to work okay, it's presumably a problem with the tip itself (it is the oldest tip we've got for this iron).  This is presumably superseded by issue #1483, to get a full set of new tips.
