### ISSUE TITLE
Liverpool Makefest - 27 June 2020 - DoES Liverpool stand

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1386]
This is to list exhibits and things we need to get ready for Liverpool Makefest, which is on 27 June (please add your name to assignees if you want to be involved in organising)

**Comment by jackie1050** [comment]
List of exhibits (please add details of anything you want to display here):

**Comment by jackie1050** [comment]
List of display-related stuff to take with us:
- black tablecloths
- display triangles (need cable ties), or alternative
- printed descriptions for exhibits
- stands for descriptions
- vertical display unit (may need some new connecting pieces)
- business cards and flyers
- television to show promotional videos

**Comment by jackie1050** [comment]
List of people who are able to help move stuff and set up our stand on Friday evening (please add your name and whether you can provide transport)

**Comment by jackie1050** [comment]
List of people who are able to help take downour stand and move everything back to DoES immediately after Makefest ends on Saturday (please add your name and whether you can provide transport)

**Comment by JackiePease** [comment]
This has been cancelled due to the coronavirus
