### ISSUE TITLE
The A3 colour ink jet printer isn't printing properly

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1389]
There are:

- lines across the print
- blotches of black ink on the top edge

**Comment by johnmckerrell** [comment]
I did a clean, still blotchy. It offered me a "second level clean" and that came out fine so I tried printing a photo. This then had a few black blotches and it seemed like the leading edge of the paper might have been a bit mangled although overall the print might be usable for my purposes. We are low on Cyan though.

**Comment by johnmckerrell** [comment]
It had offered me a "third level clean" but as the second appeared to do the trick I didn't go for it.

**Comment by JackiePease** [comment]
This printer has been disposed of.
