### ISSUE TITLE
Damaged paint in New Dinky needs repairing (and possibly mitigating in the future)

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#139]
Yesterday there was some paperwork and wiring mounted on the walls in Dinky with duct tape and where it's been removed, there are now patches of missing paint. Obviously this needs repairing if Dinky is to stay as a "nice" room. 

As an aside, there's a discussion to be had about whether we need to have some self standing pinboards/boards to allow for vertically mounted stuff that doesn't affect the finish of Dinky. 

 * Do users normally want to mount things on the wall? 
 * Is it often? 
 * Should we disallow it completely or spend money on providing facilities to accommodate it?

**Comment by DoESsean** [comment]
There was a discussion a while back about encouraging the groups that use
DoES to have displays on the wall talking about themselves and what they
do. We could tie this in with that? I'm not sure exactly what form it could
take, as it might seem a little odd to have 'spare' boards on the walls
that would be empty most of the time, but we could definitely figure
something out.

**Comment by DefProc** [comment]
From today's organiser's meeting, the consensus is that we'll fix the current damage, and keep an eye on how often this happens (as it's only once so far) to see if it needs addressing in a different way in the future. 

Current action is to:

 - [ ] repaint the wall

**Comment by amcewen** [comment]
I don't think the damaged paint was stopping anyone from using Dinky, so I've taken off the "broken" tag :-)

**Comment by huffeec** [comment]
Given it a couple of coats at maker day today.
