### ISSUE TITLE
We're out of hotglue

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1395]
The hot glue gun drawer usually contains some glue, there is none this time around when I went to use one of them.

**Comment by DoESsean** [comment]
What size do we need?

**Comment by MatthewCroughan** [comment]
@DoESsean Not sure, never knew there was different sizes. Will be in soon and find out and will document that in the wiki.

**Comment by johnmckerrell** [comment]
Last lot were bought from Clas Ohlson 🤷‍♂  #375

**Comment by DoESsean** [comment]
Between @amcewen and me, we used the descriptors 'large', 'small', 'fat', and 'thin' in that thread. And not a single measurement in sight.

**Comment by johnmckerrell** [comment]
Replaced by #1450 in which @JackiePease actually ordered some.
