### ISSUE TITLE
Sophia bed alignment issue 

### ISSUE THREAD

**Issue by RussCoty** [DoESLiverpool/somebody-should#1399]
Sophia bed is exhibiting focus issues across the y axis (as seen on screen). 

The focus seems to be off towards the bottom of screen.

Is this a screw position issue @magman2112 @Sean-anotherone

**Comment by johnmckerrell** [comment]
Hello @DoESLiverpool/laser-maintenance

**Comment by Sean-anotherone** [comment]
I refitted the y belt as it had come off and the machine seems to be cutting just fine??

I'll not close this for now just in case, but it is working.

**Comment by MatthewCroughan** [comment]
Sophia has more dooming issues than this, so this issue is looking stale so I'll close it.

**Comment by JackiePease** [comment]
Sophia is due to be returned once Tony's in operation, so it would be useful to know all the things that are wrong

**Comment by MatthewCroughan** [comment]
@JackiePease Yes, but is this issue still active? It seems like it will not be possible to track this issue, the machine has been modified since this issue was created, so this issue does not represent the current state.

**Comment by KarlDunkerley** [comment]
Remember I have a K40 that you are welcome to.


    On Thursday, 8 October 2020, 14:48:30 BST, MatthewCroughan <notifications@github.com> wrote:  
 
 


Sophia has more dooming issues than this, so this issue is looking stale so I'll close it.

**Comment by magman2112** [comment]
As @JackiePease mentioned, please leave this issue open as I don’t believe this has been resolved yet.

From the @DoESLiverpool/laser-maintenance point of view, it is better to have as many issues open as required to better understand how severe the issues are with any particular machine.

And thanks for the offer @KarlDunkerley, but I don’t think we can fit any more machines in the room at the moment.

**Comment by MatthewCroughan** [comment]
@magman2112 Did Sean not modify the machine to make this issue inconsistent in #1468 ?

**Comment by magman2112** [comment]
@MatthewCroughan #1468 is for another issue, the bed levelling is an issue in its own right as this is yet another mechanism in Sophia that it appears is not in good repair due to this issue cropping up again.

One of the useful consequences of using GitHub to log issues like this is that we also get a history of the faults that have occurred. We may actually open another issue that collates all of the outstanding issues for Sophia, like we have for Gerald in the past. This process works, so why would we change it?

**Comment by MatthewCroughan** [comment]
@magman2112 Ah, sorry. I am not suggesting that we do. I was just reading through the outstanding issues and seeing what was stale and asking if it should be closed. This one seemed self evident to me, but it makes sense that these issues should be closed only by the laser team when they have evaluated everything. Thanks for clarifying. :smile:

**Comment by magman2112** [comment]
I had some time to check the bed levelling on Sophia yesterday. I found the bed to be mostly level (but adjusted it anyway]. There was some debris under the honeycomb bed as well though, which likely caused some of the issues. This has all been cleared out now.

I will close this issue, as there are other issues that are still open to comment on for other work I undertook on Sophia
