### ISSUE TITLE
Install OpenWRT on the router in Dinky

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#14]
[migrated from Asana]

DD-WRT (the current option on the Dinky and Workshop routers) has the same MAC address hard-coded.  Putting OpenWRT onto the router instead would fix the conflict (and seems to be a preferred solution these days anyhow)

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by amcewen** [comment]
This isn't an issue at present because we don't have a wifi router in the Workshop (which is what was causing the conflict initially).
