### ISSUE TITLE
Create a spare focusing tool for Gerald

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#140]
We don't have a spare focusing tool for the large laser-cutter.  Before it goes missing we should at least measure what size it is, and ideally design a replacement.

**Comment by amcewen** [comment]
Given that we've got a new focusing tool, I presume we've fixed this now?  @DefProc, was the focus file put in github somewhere?

**Comment by DefProc** [comment]
Yup: https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/LaserCut/Gerald_Ruler_608.svg

The ruler measures from the top surface of the material to the notch between the lens tube and nozzle. And is sized empirically, adjusted from the theoretical ideal position.  

Although it's nominally sized for 3mm material, the new, longer focal length of Gerald's lens means it should work from <1mm up to 6mm without issue. 

This design, which follows the profile of the nozzle seems to be easier for users to understand than the "reference square" design used in Sophia, and we should probably update Sophia's focus tool to be similar.
