### ISSUE TITLE
Gerald not cutting at full power

### ISSUE THREAD

**Issue by dazz-ling** [DoESLiverpool/somebody-should#1400]
Hello. 
I noticed that Gerald is running below power tonight. It's needing a speed of 6 to cut through 3mm. 
I've tried cleaning the lens but hardly any improvement.  
Darran

**Comment by magman2112** [comment]
I was given a hint that a previous user had been banging the X axis on it's limits recently, so on checking the rail, it was 9mm out over it 's length.

With a some help from @goatchurchprime. we realigned the rail and then did a full alignment on the mirrors and Gerald now appears to be working OK.

For future reference, if you include @DoESLiverpool/laser-maintenance in the Github issue, the laser maintenance team will receive an email to notify them of any issues, which will likely speed up resolution of any issues.
