### ISSUE TITLE
EMFCamp Thursday 23 - Monday 26 July 2020 near Hereford

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1404]
Tickets are £180 for 4 days (bring or borrow a tent) and the next round goes on sale on 14 March
 https://www.emfcamp.org/tickets so people need to decide pretty soon if they want to go.

**Comment by DoESsean** [comment]
This has been cancelled, so I'll close the issue.

[https://blog.emfcamp.org/2020/03/25/emf-2020-cancelled/](url)
