### ISSUE TITLE
Order more members boxes

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1406]
We need some more boxes for members to use (there does seem to be some room on the racking for them already!)  From #964, the standard size is 45L Wham Fusion storage boxes (the big ones are 80L). I've ordered [10 more](https://www.ebay.co.uk/itm/292189752748), which might be here for Saturday.

**Comment by johnmckerrell** [comment]
Guessing these turned up, feel free to reopen if we need more by now.
