### ISSUE TITLE
Small bandsaw blade required

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#1407]
I identified that the blade on the Ferm bandsaw is broken - replacement required.

This appears a cromulent choice : 

https://www.solenttools.co.uk/bandsaw-blade-ferm-flz275-10mm-10tpi.html

Worth looking for a cheaper one though.

**Comment by DoESsean** [comment]
I've ordered the one listed. It may have been possible to save a couple of quid, but it seems like the additional time it would have taken for me to find a new one, and get confirmation that it would work would probably have outweighed any savings. It had free delivery as well.

It's addressed to me, but it should be taken as read that, for the foreseeable, any mail addressed to me can be opened.

**Comment by amcewen** [comment]
The blade arrived a while ago and is on @DoESsean's desk awaiting someone getting round to fitting it.

**Comment by JackiePease** [comment]
@epsaul has fitted the new blade
