### ISSUE TITLE
Use Jitsi for online event meetings instead of hangouts as a response to Covid19

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1410]
https://doesliverpool.com/press-releases/does-liverpool-covid-19-plan/

The blog post suggests hangouts will be available to be used instead of attending events, however that would require a google account, which sure most people have, but some people will not quite understand its interface or may not even have an account.

If we use Jitsi, it avoids the need for account creation and is a lot easier to get on with in my opinion. 

All one has to do is go to https://meet.jit.si/bubblino for example. You can create your own room by simply changing `bubblino` in the URL to something else, eg `makernight`. It is instantiated upon use of the URL.

A big benefit of using Jitsi is the fact that people can dial in using just a phone number 

![image](https://user-images.githubusercontent.com/26458780/76933543-4608c200-68e5-11ea-9144-4e7fe4dacabf.png)

**Comment by MatthewCroughan** [comment]
Additionally, all anyone would have to do to join is click the URL, they do not need an account and they can do this on any device, even a phone. No app installation required. This would make it easier to get a wide range of people involved, e.g from around the world who do not have google accounts or do not want to use hangouts.

**Comment by johnmckerrell** [comment]
Ah, something made me think it was self-hosted. I'll stick with the Hangout for now as we've publicised it but if I get anyone joining me at midday we can perhaps then test out jitsi at the end of the call.

**Comment by MatthewCroughan** [comment]
@johnmckerrell It's just a p2p webrtc facilitated webapp, yeah. It's open source so you can host the backend and frontend if you ever wanted to, but that's generally not needed as the service is free and reliable.

**Comment by johnmckerrell** [comment]
Given the hangout wasn't working I've updated the blog post to point at the bubbling Jitsi
