### ISSUE TITLE
How can we help each other during Covid-19

### ISSUE THREAD

**Issue by calcock01** [DoESLiverpool/somebody-should#1411]
Are there any ways that the DoES Community can help each other and the wider community during the Covid-19 outbreak?

**Comment by calcock01** [comment]
The council are looking for volunteers to help support the local community, phone numbers and online link below the text;

“We will be focussing on the following areas to support people across the city:

1.            Urgent Food deliveries - if people are at home self-isolating but need food urgently, we will pass on their details to a food bank or similar organisation to follow up with them

2.            Tackling loneliness - A simple phone call or knock on the door to check someone is ok can make a huge difference

3.            Prescription Collection – collecting and delivering a prescription for someone who finds themselves unable to leave the house

4.            General community support – working with community organisations in your local area, this could be anything from transporting items between foodbanks to helping out in a kitchen

5.            Digital skills & setup to support online shopping – digital skills are going to be a really important way for people to stay in touch with family & friends, as well doing  tasks like online shopping. We are looking for people who can help teach others how to use their tablet, PC or mobile so they can stay connected“

https://liverpoolexpress.co.uk/coronavirus-hotlines-set-up-to-mobilise-community-army/

VOLUNTEER: 0151 233 3068

SUPPORT: 0151 233 3066

**Comment by RussCoty** [comment]
I’m on lockdown essentially but I’ve been trying to help my music industry/recording hobbyist followers/friends work/alleviate boredom.


I’m looking at streaming solutions for music recording in client’s homes. There are existing systems but they are all lacking.

If anyone has any knowledge of FFMPEG love to  pick your brains.

**Comment by RussCoty** [comment]
@matthewcroughan has been helping me on this..

Wondering if I should set up a repo for it? Thoughts?

I figure 
@johnmckerrell @amcewen and @goatchurchprime might have some knowledge on FFMPEG and integrating the libs into Desktop applications too?

**Comment by amcewen** [comment]
Mostly I've used `ffmpeg` as an app rather than as libraries, but can probably help.  I did do some work integrating `gstreamer` from libraries for @ajlennon a while back.  Maybe spin it out as its own issue and then we can always set up a repo later?

There is a [call for pitches to combat isolation, with funding of £25k](https://techforce19.uk/)

**Comment by ajlennon** [comment]
Yeah I saw the tech call from Max. Would like to do something there if possible. 

Have done loads on streaming. The TL;DR is GStreamer is powerful and flexible but very hard work

If what's needed can be done with ffmpeg and wrappers then that's probably the way to go.

Can help if you have any specifics x

**Comment by RussCoty** [comment]
Cool thanks guys I'll start a new issue and put some detail in there

**Comment by ajlennon** [comment]
I setup a scheme down my road to bring people together, based on an idea from a girl a couple of roads along.

Sent a lette to people suggesting we have a WhatsApp group for a neighbourhood support group for the road, with red and green cards people can put in their windows to indicate if they are OK or need somebody to help.

I was a bit worried but the response has been extremely positive and people are chatting away about where local shops have food (bread, pasta), nappies etc. and it seems to be going very well.

I have two template letters here if it's of any use

https://drive.google.com/drive/folders/1tCXo9vGfcTykT1lgtxDeV4uYjDgkDlay

I got the red and green card packs on next day from Amazon

**Comment by ajlennon** [comment]
There's more talk on social media about 3D printing masks and so forth.

There appear to be a lot of shills promoting 3D printed solutions that don't work.

Does anybody know anybody with medical expertise who can advise if this design would help those on the front line (I am particularly thinking of people who are out delivering food and supplies)

Thanks

https://3dverkstan.se/protective-visor/

**Comment by RussCoty** [comment]
I think a lot of these things are ones that cannot hurt except alarm people further which might be what the govt. are trying to avoid. 

@tethig might have an opinion on this, if I can tag him.

Regards the p2p thing I have added an extrememly lengthy issue here https://github.com/DoESLiverpool/somebody-should/issues/1414

**Comment by DoESsean** [comment]
@RussCoty Sorry to butt in, but would you mind if I dropped you an email later on about something else? Don't want to just do it out of the blue, that a) seems rude, and b) is probably against GDPR regs.

**Comment by RussCoty** [comment]
You certainly can :)

**Comment by amcewen** [comment]
I've spun @ajlennon's "make face masks" out as its own issue #1415.

**Comment by jackie1050** [comment]
Something that might fall into the "better than nothing" category, machine sewn fabric facemasks https://www.instagram.com/p/B-IXkhshuXR/?igshid=1tkomtfawfmzg

**Comment by JackiePease** [comment]
Hopefully we've done everything we needed to
