### ISSUE TITLE
Gerald not cutting

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1412]
I came in to do an induction this morning, and Gerald isn't cutting at all.

Attached photo is of the Permission to Make badge. There is  no mark at all from the engraving and a faint engrave with shadow from the cut.
![IMG_20200321_122956](https://user-images.githubusercontent.com/12802256/77226936-f68bf580-6b73-11ea-9383-46bf1634197c.jpg)

**Comment by amcewen** [comment]
I've adjusted the alignment of the last mirror in the sequence, which seems to have improved matters.  I've not tested it fully across the range, but it seems to be cutting okay again now
