### ISSUE TITLE
Cancel our milk deliveries (for now)

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1416]
Just arrived to do some prototyping for #1415, and found two pints of milk waiting for me on the doorstep :-D

We should cancel it for a while...

**Comment by DoESsean** [comment]
Now that's strange  -I called them the other day to put a pause on this. Either the instruction hasn't got through to the milkman, or they're sending us free milk to be kind.

**Comment by DoESsean** [comment]
I've called them again - no-one there, but I left a message.

**Comment by johnmckerrell** [comment]
Are we still getting milk?

**Comment by amcewen** [comment]
We are.  We're using some of it, and I've been taking the rest and paying the milk bill, as it seemed easier than working out how to get them to stop and meant I didn't have to visit the shops so often :-)

I'm happy to carry on with that until we reopen, so we can close this.
