### ISSUE TITLE
Shutter Door won't close

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1418]
The shutter opens using the fob and the inside switch closes them but this morning it wouldn't close  when I left the building (pressing the button) .

**Comment by johnmckerrell** [comment]
Is that the button on the street for the shutter, or the button inside to open the doors? If the shutter one I know you generally have to press and hold the button twice before it pays attention to you, did you try it a few times?

**Comment by Knottyashcreative** [comment]
Tried it a quite a few times (external box) , but it was early. I can't recollect how long I held it in for so maybe that.

**Comment by johnmckerrell** [comment]
Ok, thanks for reporting it.

**Comment by amcewen** [comment]
It seemed okay when I tried it when I called in earlier.  It did take a second press before it went down.  It does need the door to be locked when you try it, I have found that sometimes if you're quick leaving it takes a few seconds before the door locks behind you.  Maybe it was that?

Thanks for reporting so we could double-check it.
