### ISSUE TITLE
Face mask making volunteer required? 

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1419]
I'm available out of hours (6pm  onwards) and Friday, Wednesday and 
Thursday if you need assistance making up the masks.  I'm happy to work alone, once I know what to do for this project.

**Comment by JackiePease** [comment]
Excellent - please see this page. It's being finalised today, but you can add the times you're available to the spreadsheet straight away (starting this evening if you like!): https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/production.md
________________________________

**Comment by JackiePease** [comment]
Also, they're visors, not masks! The masks are the ones that cover your mouth and nose...
________________________________

**Comment by JackiePease** [comment]
@Knottyashcreative has volunteered, updated the spreadsheet, and already started cleaning bands!
