### ISSUE TITLE
Sony HD video camera Firewire connector is faulty

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#142]
We've had a nice Sony HD video camera for ages now, but it's not really usable - the Firewire connector is flaky and so you can't actually get the footage off the camera unless you transfer the tape over to another camera (and we don't have one).

It needs careful dismantling to see if we can solder the firewire connector back onto the PCB (presumably).  At the moment it's in the locked cupboard in the main room, so ask an organiser if you want to try fixing it.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by DoESsean** [comment]
Are we still interested in getting this fixed, or is it something that we can let go of?

**Comment by DoESsean** [comment]
Consider it dumped.
