### ISSUE TITLE
Laser settings confirmation?

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1422]
I'm working with the laser cutting (NHS visors) this evening, David and I noticed the laser is set to 100% power and the advisory sticky note says it should be 70%.

Please could the relevant person confirm the correct power setting?  I will leave the setting at 100% until otherwise instructed i.e. the cuts are coming out fine etc.

Regards

**Comment by Knottyashcreative** [comment]
Jackie said two others have commented on Gir hub but we can't find those replie. So I just provide an to update on the current settings
![15869880306592830917694235007792](https://user-images.githubusercontent.com/58068720/79393281-ee558900-7f6c-11ea-800d-248ceddfda93.jpg)

These seem to be working well however the laser still shows this (see below image) . I have been told this should still be okay
![1586988103997247066585547928239](https://user-images.githubusercontent.com/58068720/79393363-180eb000-7f6d-11ea-99e8-50c469b1fbb8.jpg)

The laser cutter is still working well.

**Comment by dfaligertwood** [comment]
Try doesliverpool/covid19#85

**Comment by johnmckerrell** [comment]
As mentioned on the other ticket (thanks @huffeec !) This is correct, the laser cutter's screen should report 100% while the computer settings should be 70.
