### ISSUE TITLE
Found USB dongle in need of repair

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1423]
![15869859314267580792940851081040](https://user-images.githubusercontent.com/58068720/79390668-0aa2f700-7f68-11ea-8f3a-8c82cbc949a0.jpg)

Working on the laser cutter and found TP link dongle in this state, next to PC. I wanted to let the team know and any feedback if it needs replacing /repairing before my 12pm finish?

The lasee cutter is still performing well..

**Comment by arthurrowland** [comment]
Gerald's PC is connected to the internet via ethernet.

Risking an assumption that no one is missing this dongle after a year without comment, and closing.
