### ISSUE TITLE
Unable to connect to doorbot2

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1426]
Unable to connect to doorbot2, getting the following error:
ssh: Could not resolve hostname doorbot2.local: Name or service not known
lost connection
ssh: Could not resolve hostname doorbot2.local: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]

Still working for existing tags

**Comment by johnmckerrell** [comment]
Can I check you're talking about the right door bot? I've documented them here to make sure (have a feeling you are) https://github.com/DoESLiverpool/somebody-should/wiki/DoorBot

**Comment by JackiePease** [comment]
YesOn 18 Apr 2020 09:33, John McKerrell <notifications@github.com> wrote:
Can I check you're talking about the right door bot? I've documented them here to make sure (have a feeling you are) https://github.com/DoESLiverpool/somebody-should/wiki/DoorBot

**Comment by johnmckerrell** [comment]
It looks like it's up, I can ssh and ping it. Probably mdns being difficult. I've just successfully synced the log cards config if that's what you were trying to do?

**Comment by JackiePease** [comment]
The fob is working now.
________________________________
