### ISSUE TITLE
The tube feeding Gerald's air assist had burned through

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1428]
A clip holding down the tube feeding Gerald's air assist had failed. As a result the tube sprang up and got in the way of the laser beam.
The tube burned though and the air assist failed. One symptom was a small fire when cutting PP sheet.
@Sean-anotherone has replaced two sections of the tube and was able to use cable ties to hold it in place.
![IMG_20200418_172512](https://user-images.githubusercontent.com/12802256/79690695-a461f100-8253-11ea-9289-c8bdfa322382.jpg)

**Comment by JackiePease** [comment]
@Sean-anotherone could you add notes and close issue please

**Comment by Sean-anotherone** [comment]
Fixed it. :)

**Comment by Sean-anotherone** [comment]
It might benefit from a new tube, as each join introduces a crimped spot and they will restrict the airflow.
