### ISSUE TITLE
Buy new scalpels, blades and sharps disposal boxes

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1429]
These are being used at a faster rate than usual due to the COVID19 visor project

**Comment by JackiePease** [comment]
I have ordered:
- 1 Box of 10 Swann Morton No 3 Stainless Steel Graduated Scalpel Handles 0933 / 10 *
- 1 Box of 100 Swann Morton No 10A Surgical Scalpel Blade 0102
- 1 4 x Blade Remover Units Swann Morton 5525
from https://www.scalpelsandblades.co.uk/

**Comment by amcewen** [comment]
They have arrived.
