### ISSUE TITLE
Buy tweezers/forceps for workshop and first aid boxes

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1431]

**Comment by amcewen** [comment]
The ones I bought last time were https://www.aliexpress.com/item/1791152724.html?spm=a2g0s.9042311.0.0.78e24c4d2S7wkl

**Comment by amcewen** [comment]
I've ordered 3 sets (of 6)

**Comment by amcewen** [comment]
These arrived a while back and have been put into the forceps drawer (I left some with @DoESsean too, so we can do an initial restock without having to order more in - not that we should *need* to restock but...)
