### ISSUE TITLE
Felicity misbehaving 

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1437]
![20200427_030512](https://user-images.githubusercontent.com/58068720/80327511-41182600-8834-11ea-8241-c2c82d73002e.jpg)

Tried to print headbands and above image an example of the output. Someone may need to tweak it. 

Adam 3D printer had no such problem

**Comment by JackiePease** [comment]
I've printed a couple of headbands today. I did get the same issue on one of them. I've turned the bed temperature up to 75C and will see if that makes a difference

**Comment by JackiePease** [comment]
Note: Gerald currently has PLA, so easier to print

**Comment by JackiePease** [comment]
I've now changed the settings for PETG so the bed temperature is 75C, as this seems to result in fewer fails.
