### ISSUE TITLE
New laser cutter guidance

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1438]
Closing up for the night /morning but this laser cutter and pump was left on but not active.

I closed it down, and I hope this is the correct procedure as applicable for other laser cutters on exit?
![15879535077631142207871865619320](https://user-images.githubusercontent.com/58068720/80327683-dddac380-8834-11ea-843c-f3ee6f6b54db.jpg)

**Comment by JackiePease** [comment]
That's fine. This is a laser cutter that we've been loaned for the visor project. @Sean-anotherone has just fitted a new tube and it should be in production in the next couple of days.

**Comment by Sean-anotherone** [comment]
This is a well built machine but would really really benefit from one of these :

https://www.ebay.co.uk/itm/Honeycomb-Working-Table-Board-Platform-for-Laser-Engraver-Cutter-Customizable/123334319075

**Comment by JackiePease** [comment]
This laser cutter has been returned to it's owner.
