### ISSUE TITLE
Make something that reminds people to clear the workshop during out of hours

### ISSUE THREAD

**Issue by fjfish** [DoESLiverpool/somebody-should#144]
Currently thinking a PI with a TV that tells the time and starts making noises when it's 20:30, then at 20:50 - screen reminder to finish up because the building will close.

**Comment by DefProc** [comment]
It doesn't really need a screen clock, if all it's used for is outputting audio indications. It could easily be bundled behind a clock face, with audio and warning light outputs from the pi.

**Comment by fjfish** [comment]
Not if I'm doing it and want to get it done quickly

**Comment by DefProc** [comment]
I was thinking it would be quicker if it didn't have the display (the clock doesn't have to be connected), and I'd be happy to help with the physical installation if you'd like. 

I suppose it could also give a reminder for the 5.30pm closing too, so workshop users get a heads up for printing or laser cutting.

**Comment by johnmckerrell** [comment]
Definitely a good idea to warn people at 5pm that they might have to leave at 5:30pm. Seems like that's going to get more important in the near future.

**Comment by johnmckerrell** [comment]
Air horn, it definitely needs to involve an air horn. Perhaps it goes off at 5pm and we have one of Patrick's countdown displays that starts counting down to 5:30. Another air horn blast at 5:15pm and then at 5:30pm it just goes off continuously until an organiser turns it off.

**Comment by amcewen** [comment]
I'm not sure about the going off continually until an organiser switches it off.  However, bonus points if it looks like this - https://youtu.be/gdX6fwfrULI?t=5s :-D

**Comment by amcewen** [comment]
I've printed one of http://www.thingiverse.com/thing:59580  It needs a 3mm shaft motor to test it, and then depending on how loud it is, we might want to scale it down (which would also make it easier to fix to a standard DC motor).

I'm thinking it could be like an end of shift siren at a factory - goes off at 5:30 to signal the end of the day, and then again at 8:30 (8:45?) to signal that the building will be closing soon.

**Comment by johnmckerrell** [comment]
Sweet, definitely think it's worth doing a similar warning at maybe 5pm, just a quick double burst or something.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
@fjfish Francis, are you still planning to do this (you are marked as assignee on this issue since May 2015). If not let me know.

( also, if you are the Francis Fish I think you are... Hi, it's Guy Fraser here :) )

**Comment by fjfish** [comment]
I have an old Pi knocking around but not sure I have the time
