### ISSUE TITLE
Buy some more IPA (isopropyl alcohol)

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1442]
I've ordered 5 litres of 99.9% IPA from Luce Mill (https://www.lucemill.com/) - it should arrive in 2-3 days.

**Comment by johnmckerrell** [comment]
If you can whack the price in here it will help me consolidate later ;-) (also inform our future choices)

**Comment by JackiePease** [comment]
£42.48 (5l and it's stronger so can be diluted, but hopefully this doesn't need to inform our future choices!)

**Comment by JackiePease** [comment]
This arrived
