### ISSUE TITLE
Gerald's air assist tube was dragging across the bed

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1445]
Petra was laser cutting with Gerald when the air assist started dragging the piece of material across the bed.

**Comment by JackiePease** [comment]
Looking at an old photo it seems that the air assist should be attached to the top of the laser cutter head. There was a non-dusty area there too.
It seems that the nut and bolt attaching the air assist had come undone.
I found a new M3 bolt and reattached.

**Comment by JackiePease** [comment]
![IMG_20200508_180011](https://user-images.githubusercontent.com/12802256/81431000-52c4cc00-9158-11ea-851e-e0cbcf10f843.jpg)
New bolt shown - I'll leave this issue open for the time being in case anyone is aware of other steps I need to take.

**Comment by Sean-anotherone** [comment]
I have put an M3 nylock nut in my pocket, next time I'm in the area I'll fit it.

**Comment by JackiePease** [comment]
This came off again today, so looks like the nylock would be really useful

**Comment by Sean-anotherone** [comment]
I'm back at the royal, so will drop in and sort this when I'm done 

Sent from Yahoo Mail on Android 
 
  On Sat, 9 May 2020 at 18:33, Jackie Pease<notifications@github.com> wrote:   


This came off again today, so looks like the nylock would be really useful

**Comment by Sean-anotherone** [comment]
replaced with a small hex bolt and nylock nut - should not come apart again.
