### ISSUE TITLE
Gerald's default copy of Lasercut doesn't work

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1448]
For some reason the copy of Lasercut installed as the default (i.e. if you use the quick launch bar, etc.) fails to work - when you try opening or importing a file into it then it closes the app.

There's another copy in a folder called `Lasercut 5.0 - copy` on the hard drive which seems to work okay.

We should:
  * make a copy of the working copy and keep it safe
  * get rid of the non-working copy and update the quick links, etc. so it launches the working one

**Comment by Sean-anotherone** [comment]
Changed the shortcut and the toolbar icon to point at the new copy.
