### ISSUE TITLE
Order some hot glue sticks

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1450]
There aren't any glue sticks of either size in the drawer with the glue guns.

**Comment by JackiePease** [comment]
I've ordered the following from Amazon:
Hot Glue Sticks Φ 7.0mm, Pack 125 7mm x 100mm Beeway® Mini Melt Glue Gun Sticks, Premium A+, SGS Approved, 
Hot Glue Sticks Φ 11.0mm, Pack 55 11mm x 100mm Beeway® Mini Melt Glue Gun Sticks, Premium A+, SGS Approved
Total cost £21.98. They should be arriving on Tuesday.

**Comment by johnmckerrell** [comment]
Well done! Can we close #1395 too then? ;-)

**Comment by JackiePease** [comment]
Yes :-p

**Comment by JackiePease** [comment]
These have arrived - I've put them in the drawer with the glue guns
