### ISSUE TITLE
Maglock in Events Room is loose

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1451]
The maglock isn't fully secured to the frame and so doesn't always lock properly.

**Comment by amcewen** [comment]
I've re-tightened the hex bolt holding the maglock on, you need a reasonably large cross-head screwdriver (I used one of the black/blue handled Cocraft ones) too, to get access to the hex bolt head.

**Comment by JackiePease** [comment]
The same thing happened again. I've repeated what @amcewen did, but will leave the issue open in case anyone can determine the underlying cause.

**Comment by JackiePease** [comment]
This came undone again. @Knottyashcreative has repeated the same procedure again. He suggested gluing the bolt in - does that seem reasonable?

**Comment by JackiePease** [comment]
This seems to have been fixed - not sure by who - no problems recently

**Comment by amcewen** [comment]
Happened again, as noted by @Robotorium in #1589.  I replaced one of the screws as the head was getting stripped (it's now a hex-head bolt, as that's all I had to hand that would fit) and added some threadlock to the bolt.
