### ISSUE TITLE
Reconfigure the space to make social distancing easier

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1452]
We aren't changing any of our guidance on general use of the space - it's still that you should only come in if you need to use the space for work that you can't do elsewhere.

However, now that visor production is winding down from its peak (although we are still making and shipping out smaller quantities) we're looking at how best to help people use the space safely.

We should make it easier to work out how to maintain social distance.  

 * Certain rooms/areas should be restricted to one person at a time (the laser and CNC rooms, recess, kitchen)
 * Desks facing each other aren't 2 metres apart, so we should zig-zag them so that *if* people are working in a similar area they can keep >2 metres apart

**Comment by amcewen** [comment]
I made some progress on this yesterday.  I'm back in on Tuesday, so should get a bit more done then.

I did some working out of which desks would make most sense for people to use or avoid.  I've stuck "Desk available" signs on the ones to use.  In Room 29 all the desks used by permanent-deskers fit into that pattern too; in the main room it's trickier, so for now the pattern gives the most free desks, given most permanent-deskers are (mostly) WFH.  We can re-jig things as needed in the future.

The desks available to use are marked like this:

![image](https://user-images.githubusercontent.com/108468/82753771-2e0b5e00-9dc0-11ea-9d51-dd6fa3ff072c.png)

I haven't done the bank of workshop desks yet, as that was in use for visor production.  @JackiePease and I were thinking we'd zig-zag it to have the desks nearest the electronics workbench and textile area available for use, along with the middle one on the side furthest from the window.

I also made a start on marking out some of the restricted access areas.  Annoyingly the red vinyl doesn't stick to the floor very well, so I've left the transfer tape on it for now to see how it fares.

Still, there's a "max occupancy 1 person" sign on the kitchen floor, and across the entrance to the recess with the vinyl cutter.  I switched from the floor to the door for the CNC room, as you can see here:

![DSC_0733](https://user-images.githubusercontent.com/108468/82753710-ade4f880-9dbf-11ea-929f-06609e6a2d21.JPG)

**Comment by JackiePease** [comment]
Helen Evans has sent the following PDFs which are being used in communal areas in the Tapestry. I've copied them to [somewheresafe](https://github.com/DoESLiverpool/somewhere-safe/blob/master/designs/covid%20signage/):
Keep Distance Sign.pdf
Hand Washing Sign.pdf
Full Covid Sign.pdfI'
4. Covid-19 Weekly Checksheet.docx

I'll aim to sublimation print some later today.

**Comment by JackiePease** [comment]
Results from sublimation printing weren't great, so I printed some A4 versions at home and have stuck them to brick walls using duct tape - not sure yet whether that is enough to keep them up long term.

**Comment by johnmckerrell** [comment]
There might be some A4 clip frames near Sean's desk

**Comment by JackiePease** [comment]
OK - I'll wait to see if they stay up, then try that.On 3 Jun 2020 13:59, John McKerrell <notifications@github.com> wrote:
There might be some A4 clip frames near Sean's desk

**Comment by amcewen** [comment]
I've just published a new [blog post describing the changes and updating the guidelines on how to use the space](https://doesliverpool.com/press-releases/accessing-does-liverpool-during-covid-19/)

It would be useful to post a shortened version on the main doors into the space and events room.  Then I think we'll be able to close this?

**Comment by amcewen** [comment]
I posted a summary of the rules on the doors into the space (a couple of weeks back), so I think we can close this now.
