### ISSUE TITLE
Entrance phone-in procedure is broken, as audio is only going one way

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1459]
The main phones in DoES are having an issue where audio is only going one direction, from inside to outside. This means that people that are at the entrance call in, we say "Hello DoES Liveprool" and they can hear us, but we cannot hear their response. Seems like something @amcewen or @johnmckerrell would know about. Opening the door from the dial pad still works fine.

**Comment by johnmckerrell** [comment]
Can someone confirm that just calling the phones works as normal, and that it's all phones not just one? Ideally you would call it with both the enquiries number and the intercom number, both of which are on this page: https://github.com/DoESLiverpool/somebody-should/wiki/VOIP-Phone-Setup

**Comment by MatthewCroughan** [comment]
This seems not to be an issue, as I tested it with Jackie outside last night. I believed it was as there were 3 occurrences of delivery drives not responding, so I assumed they could not hear me. False positive, not a problem :)
