### ISSUE TITLE
The laser coolant water needs changing

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#146]
as mentioned in #145

**Comment by amcewen** [comment]
It definitely does need a change.  The flow sensor had disabled the laser on Saturday, because there was a build up of sludge blocking the coolant flow - luckily the blockage was in the curve just before the flow sensor, and working the tube by hand freed things up.

**Comment by DefProc** [comment]
Done, although it needs some ethyl-glycol based coolant and algae inhibitor adding.
