### ISSUE TITLE
Evaluate/buy new glass build plates for both Ultimakers

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1460]
My latest print (which has quite a large surface area) was stuck tightly to the glass bed on Prints Adam. When it was removed quite a lot of glass peeled off with the print. The print bed already had dents in it, which I had thought might have been due to someone using a chisel to remove a print. There is also some damage on the other side, but I think it's still usable for the time being.

Felicity's glass also has a small dent in one side.

It seems that this could be due to using PETG which "sticks agressively to glass", printing too close to the glass, and general wear and tear - the glass is quite old (https://magigoo.com/blog/chipped-glass-what-causes-it/, https://www.goprint3d.co.uk/ultimaker-glass-bed.html).

There's also a suggestion that using the right glue, or a PVA slurry, might help stop this from happening (https://community.ultimaker.com/topic/23974-does-the-glass-build-plate-wear-out/ - this thread also suggests that it's more difficult to get stuff to stick on worn glass which might be why we can't get ABS to stick at all these days).

This seems to be the [official part](https://3dgbire.com/products/ultimaker-glass-plate?variant=7858899091509), but I'll leave this open for a couple of days to see if anyone has any other ideas.

**Comment by ajlennon** [comment]
We seem to have a lot of PETG nowadays. And a lot of that PETG is 1.75mm which won't work on the Ultimakers. So on that basis I've been wanting to find some time to get on top of how (if!) we can do this with the Creality Printers that we have. I need to provide some 3D printed cases for my commercial work so it seemed a win-win to try to get the PETG workflow going to do this. I'm in the middle of things now and have been taking advice from people over the past couple of days on the problems I'm seeing. I'm going to write some of this up on the Wiki but here are bits and pieces that are on my mind...

Creality Stuff

I've taken the Creality CR-10S home for the weekend as I've been having all sorts of general problems with it which I think are related to the bed levelling and the automatic levelling sensor. 

Without the bed being levelled correctly we're off to a non-starter. I'm not confident I can do this right so am hoping I can rope in an expert like @Sean-anotherone to take a quick look. I think it's nearly OK but definitely when the head is close to the base there's less filament extruding on the left hand side than the right hand side so it is defintitely not level as a start. I would try to fix this by turning the handles myself but I have done this before and I made things worse not better (!)

That said, I think it's usable. From @MatthewCroughan 's work we need to run the "mesh bed levelling" once and then store that which I've done (a few times). With that done you then just need to adjust the Z offset to make sure the offset is right and the mesh side of things is supposed to handle everything else as the head moves across the bed, as I understand it.

We can set the Z offset using a command M851 - e.g. `M851 Z-0.5`. One recommendation is to set this in the Octoprint terminal but at least on the Creality we are currently automatically setting it at the start of a print in the settings. So the best thing is to change it here. Negative is closer to the build bed. Change it slowly and don't go crazy as if you go too low you can dig in and damage the bed and probably the nozzle.

![image](https://user-images.githubusercontent.com/1537834/85930165-06714f00-b8b2-11ea-9585-d4871e71b2fb.png)

PETG Stuff

So I spent a lot of time with grey 1.75mm PolyMaker Polylite filament. Whatever I did I simply could not get this to stick to the glass bed I am using on the Creality CR10-S. Now it has been sitting on the printer for some time but @MatthewCroughan feels that this shouldn't stop it sticking to the bed it just causes sagging in the prints.

I tried a lot of different things including

- Changing bed temperature between 80 degrees and 100 degrees. (Creality supports this but I think there's a bug in the Marlin firmware and intermitttently you'll get a thermal runaway error and have to restart the printer. 

- Changing the print head temperature. The Creality with stock hot end and Marlin firmware will only go up to 235C so I've pretty much left it at that.
- Cleaning the bed so there's nothing on it
- Cleaning the bed and wiping down with glass cleaner
- Putting "blue painters tape" down on the bed
- Adding cheap equivalent Pritt Stick to the glass bed and also on top of the blue painters tape
- Spraying "Bristows" hair spray on to the glass bed

None of the above helped. Then under advice I went into Cura and changed some of the settings. I changed the default 50mm/s print speed to 10mm/s for the first layer. I also set the fan to be off for the first layer rising to the default of 50%. This didn't help either.

I then changed the filament to a Reflow filament in mint and this immediately worked MUCH much better on the glass bed with hairspray so there was definitely a problem with the filament.

I'm now seeing that the print I am doing is llifting off the bed so need to investigate that issue

**Comment by MatthewCroughan** [comment]
@ajlennon You do not need to put that in the POST or PRE gcode scripts. When you set M851, if you follow it up with M500 that saves this offset to the eeprom on the board. This would then mean that only one person has to calibrate the machine, then everyone else who uses it afterwards does not have to worry about this setting. Perhaps we do need to make a plugin for octoprint that visualises and exposes this offset so that people can adjust it themselves though.

**Comment by amcewen** [comment]
@ajlennon, @MatthewCroughan this doesn't seem to be anything to do with the Ultimakers, do you want to spin it out as its own issue?

**Comment by MatthewCroughan** [comment]
@amcewen Will leave that up to Alex as I'm not sure what to call it :D

**Comment by magman2112** [comment]
I’ve been doing a bit of internet surfing for replacement glass plates for the Ultimakers. So far, I have only found Original bed plates and the standard price appears to be £34.20 each, these being available from Farnell, RS and a couple of other UK based suppliers. I did find one supplier with an original Ultimaker glass for £31.20 though - https://3dgbire.com/collections/spare-parts/products/ultimaker-glass-plate?variant=7858899091509

I’ve also had a look on eBay, for non original glass plates, they are either more expensive than original or the wrong size. I will keep looking though.

**Comment by ajlennon** [comment]
The PETG comments are relevant to the Ultimakers

**Comment by ajlennon** [comment]
The capture above is going to go into the Creality Wiki page, possibly a new Wiki page capturing what filament we've had luck with and what settings to use on Ultimakers versus Crealities, and possibly yet another page on printing with PETG on the Ultimakers using something based on the above tips although I probably won't be doing that last page as my focus is on making the Crealities work for people with PETG (and PLA of course)

**Comment by ajlennon** [comment]
@magman2112 @MatthewCroughan says that "carborundum" base plates are very good. I have one on order for the CR-10S and will feed back. It might be worth looking if one of these is available for the Ultimakers?

**Comment by ajlennon** [comment]
So I've now replaced the glass plate for the Creality with a "magnetic bed" that I got ages ago. I've been through my calibration procedure and it seems to be printing well, sticking better than it does to glass. @MatthewCroughan 's advice is that glass is not a great surface for a build plate. I'm going to keep on printing and testing but it might be worth looking at a non-glass build surface for the Ultimakers?

see: https://www.amazon.co.uk/Official-Creality-3D-Flexible-Magnetic/dp/B07GXJNK38

![image](https://user-images.githubusercontent.com/1537834/85951797-68d35980-b95d-11ea-8c28-307477dde70a.png)

**Comment by Sean-anotherone** [comment]
A piece of 4mm glass cut to size and toughened should be less than a tenner !


    On Sunday, 28 June 2020, 13:36:31 BST, Alex Lennon <notifications@github.com> wrote:  
 
 


@magman2112 @MatthewCroughan says that "carborundum" base plates are very good. I have one on order for the CR-10S and will feed back. It might be worth looking if one of these is available for the Ultimakers?

**Comment by MatthewCroughan** [comment]
@Sean-anotherone I'd be very interested in what the "micro-porous" coating is on these fancy beds that Creality and others distribute is, and whether we could make it ourselves. Creality sell it as a "carborundum" bed, which they also say is a "Microporous Coating". Anycubic sell a similar bed they call an Ultrabase with the same feature. This surface texture that they're calling the microporous coating is simply applied on top of the same glass panel one would cut to size.

![image](https://user-images.githubusercontent.com/26458780/85959786-575a7380-b996-11ea-9a1f-6e6b6e3b8812.png)

I have one at home that I use on my Ender 3. It adheres far better than any other method, with any other bed, and than with any adhesive concoction, anecdotally.

**Comment by magman2112** [comment]
The bed size for the Ultimakers are 22.9cm x 25.7cm, which is particular to the Ultimakers, so a lot of the cheaper options and alternates on eBay etc. are not the correct size. Also, the standard glass plates are borosilicate, so I’m not sure how this compares to standard toughened glass for reliability in a 3D printer. These are some of the issues I was taking into account when looking for replacements.

As both plates are damaged at the moment, how about a compromise of buying one original, then experimenting with alternates for the other? At least then we have at least one of the Ultimakers capable of being operational as stock, so we have something to compare to, as well as a good chance of at least one of them being operational if the alternates don’t work out as expected.

**Comment by ajlennon** [comment]
I started putting some recommended print settings [here](https://github.com/DoESLiverpool/somebody-should/wiki/Materials:-3D-Printer-Filament#recommended-print-settings). Is there anywhere else in the wiki this is already captured?

**Comment by Sean-anotherone** [comment]
Interesting !
Here is a little thought experiment then..
Take a piece of regular 3mm glass - very cheap.
Fettle the sharp edges etc and then immerse it in a little water that has has some finely ground black enamel power suspended in it (the stuff jewelers use in a furnace).Allow some powder to settle, carefully remove glass from water, allow to dry.  If this does not give a thin even layer could try silk-screening it?
Place enamel-powder coated glass in Gerald and zap it with a dot pattern, i.e. selectively fusing the black powder to the glass.  Rinse well, and print.
An additional step if this does not fuse it well enough to work is to then send the glass back to the shop to be toughened (they do this at high temps) to see if that fuses it better?
I have no idea if it would work, but it would be a fun experiment to try?

Could just try ground glass too, or uniformly etched, or even finely sandblasted.  I feel that the "microporous" might be a bit of a red herring and all that's needed is a bit of texture with just the right degree of roughness.
If you drag a fingernail across one of these fancy beds is any roughness evident?  Or can we look at one under a microscope?  Anyone know of an electron microscope that might be available for a quick look?
Many questions.
Sean-anotherone


    On Sunday, 28 June 2020, 23:24:37 BST, MatthewCroughan <notifications@github.com> wrote:  
 
 


@Sean-anotherone I'd be very interested in what the "micro-porous" coating is on these fancy beds that Creality and others distribute is, and whether we could make it ourselves. Creality sell it as a "carborundum" bed, which they also say is a "Microporous Coating". Anycubic sell a similar bed they call an Ultrabase with the same feature. This surface texture that they're calling the microporous coating is simply applied on top of the same glass panel one would cut to size.



I have one at home that I use on my Ender 3. It adheres far better than any other method, with any other bed, and than with any adhesive concoction, anecdotally.

**Comment by JackiePease** [comment]
I've ordered 2 new beds from 3DGBIRE. 
Cost:
Subtotal 	£57.00
Shipping 	£5.99
Taxes 	£12.60
Total 	£75.59

**Comment by JackiePease** [comment]
These have arrived and I've fitted them to the Ultimakers. As the old beds are still fairly useable, I've put them on the cupboard as spares.
I've put labels on the printers to remind people to use glue, as this might help avoid damage.
I'll close the issue but if anyone prints anything on ABS in the near future, it might be worth adding a comment
