### ISSUE TITLE
We should have a booking system for out of hours laser use

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#147]
It would be less advertised, we could simply email it to all the people that we know have paid for out of hours access. Gives slots on weekday evenings and Saturday. Is very clear that people are responsible for not getting themselves locked in.

**Comment by amcewen** [comment]
It should cover the 3d printers too

**Comment by ReddbridgeMark** [comment]
Can I suggest there is something to cover whole rooms too, with regards to events. While out of the ordinary it should then prevent people turning up to the workshop etc when the space is closed. Even when people are politely understanding, as you would expect them to be, about the space closing/being closed it's still a bit of an awkward situation, as they are expecting use of the facilities and it would be better not to inconvenience/disappoint them in the first instance.

I think perhaps, most simply, the DoES status page could be expanded not just to show operational equipment, but also host the calendars as well as that room availability/special messages, and for this to be pushed as the central place for people to go to book out the cutters. Onus is then placed on users to book, and check availability before setting out.

**Comment by madjake45** [comment]
If we would like to do this then I can come in next week and have a hash at it

**Comment by DefProc** [comment]
Unless there's a pressing issue, it's still not a practical problem is it?
