### ISSUE TITLE
Repair and commission the Cel Robox Dual Material Printer

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#1472]
An initial look revealed some broken off filament in both bowden tubes, plus one extruder drive not working.

The tubes are now clear and both drives successfully load filament as far as the print head/hotend.

All 3 print heads however, give errors.
I looked in one and there's a lot going on in there for a hotend!, there is a mechanism to tilt the hotend so one of the nozzles is positioned for printing, plus there is a valve system that pushes a pin into the back of the nozzle - presumably to prevent ooze when printing from the other one??

The print head internals seem a bit complex and fiddly, but rather than look to buy or try a replacement* I suggest a full strip down and clean out.  There are a pair of dual material print heads plus a dual flow head (for fast infill with a bigger nozzle while maintaining a regular nozzle for walls).  By looking at the selection of filament that is in the box with the machine I'd suggest it has been used to print all sorts of stuff, including materials generally identified as "clogs on a reel", such as wood.  Hence the proposal for a full strip and clean of the heads before anything else.

(* £135 for dual, £120 for dual flow and £160 for a single nozzle hotend ????  - i.e. more than a whole creality costs...)
( the custom filament reels are over £25 for a half-reel, but it seems to load even when they are not connected, plus there are re-programmable reels listed for £13 so it is possible to "load your own")

**Comment by JackiePease** [comment]
Checked with @Sean-anotherone that this wasn't going to be fixed. Karen has taken the filament  for upcycling and I've put the printer on the free stuff table. If no-one wants it we can salvage steppers etc.

**Comment by JackiePease** [comment]
Someone has taken this from the free stuff table

**Comment by Sean-anotherone** [comment]
Good luck to whoever it was...  I found that the printheads (all of them) were blocked solid, the limited control of the machine available meant that it was not a simple matter to heat them and pullback / pushthrough, so probably a lot of dismantling required (dismantling that involves a hot air gun or similar)
Sean


    On Monday, 27 September 2021, 17:41:35 BST, Jackie Pease ***@***.***> wrote:  
 
 


Someone has taken this from the free stuff table

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
