### ISSUE TITLE
Laser safety and Measurement

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1473]
As we may be doing some more serious work on Monty, with a likely replacement tube and new bracketry, I think prudent that we obtain some laser goggles, to allow us to safely work on the laser as we develop these changes. 

I spotted a few pairs on eBay, from around £30 - though you have to be careful to state CO2 glasses, or the glasses won't provide protection at the right frequencies. Also, from personal preferences, at least one pair shoudl be capable of being worn over prescription glasses.

It would also be useful to be able to measure the laser power more precisely than doing sample laser cuts. There are various laser power meters available, but as these can cost in the £hundreds to in excess of £1000 I think our best bet is to obtain a laser Calorimeter. A Calorimeter uses a metal plate that is heated by the laser, which gives a power measurement on a dail gauge. 

I have found Calorimeters on the web in America from around $120, though there would obviously be shipping and import duties to pay - like this one:

https://www.2laser.com/laser_power_meter_probe_and_laser_monitor

Millenium Laser also have these available for £170.

**Comment by amcewen** [comment]
Smoke and Mirrors have [these laser safety glasses](https://smokeandmirrors.store/products/pollycarbonate-10-6) for £25.  From the photo it's not clear they'd go over glasses.  Maybe get a set of those and a set of an over-glasses type, if anyone finds a link for some of them?

**Comment by magman2112** [comment]
I would say go ahead with the glasses from Smoke and Mirrors now, so that we have them for when the tube for Monty arrives.

I have found some laser glasses on ebay which appear to be spectacle friendly :-

https://www.ebay.co.uk/itm/CO2-Laser-Safty-Protective-Goggles-Glasses-10600nm-For-Engraving-Cuttinge-Beauty/223669181124

Apart from the mis-spelling, these may be a good second bet for these goggles.

**Comment by amcewen** [comment]
I've ordered one each from Smoke and Mirrors and ebay.

**Comment by amcewen** [comment]
The ebay glasses turned up today, so I put them into the laser-spares cupboard alongside the Smoke and Mirrors set that arrived last week.

**Comment by magman2112** [comment]
We checked the glasses out last Thursday and both seem A good fit for what we need them to do. 

For the Laser Power measurement, I am now leaning more towards the digital Laser Power Meter, rather than an analogue Calorimeter. These are a bit more expensive than the analogue equivalents, but should be easier to use in the long term.

I have found one from apparently a UK based supplier for £169.99 on eBay at the following link.

https://www.ebay.co.uk/itm/402398950352

At least this should hopefully avoid import duty and VAT on top of the price and with quicker delivery being likely as well.

**Comment by DoESsean** [comment]
I've ordered the Power Meter, it should be here by Tuesday 20th.

**Comment by amcewen** [comment]
@magman2112 @Sean-anotherone did the laser power meter turn up?  Presumably we can close this issue if so

**Comment by magman2112** [comment]
The laser power meter turned up last year and has been successfully tested. It is stored in the laser spares cupboard now.
