### ISSUE TITLE
Buy some more safety glasses

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1474]
We seemed to be running low on (normal workshop) safety glasses, and I was buying myself some, so I bought a few more pairs of varying types: 
  * http://cpc.farnell.com/jsp/search/productdetail.jsp?CMP=i-ddd7-00001003&sku=HE30515
  * http://cpc.farnell.com/jsp/search/productdetail.jsp?CMP=i-ddd7-00001003&sku=HE32664
  * http://cpc.farnell.com/jsp/search/productdetail.jsp?CMP=i-ddd7-00001003&sku=HE33897

I also got some [junior sized ones](http://cpc.farnell.com/jsp/search/productdetail.jsp?CMP=i-ddd7-00001003&sku=HE33055), for our younger makers.  They're on the right in this photo:

![image](https://user-images.githubusercontent.com/108468/89628218-e612b800-d893-11ea-848b-78474c88a1ef.png)

If anyone has opinions for/against the new glasses, it'd be good to hear them so we can get more of the good ones/avoid the bad ones in future.

I haven't put the kids ones into the general safety-glasses drawer just yet, as I think they'd get mistaken for normal ones and possibly accidentally broken as a result.  Does anyone have a space soft glasses pouch or similar that we could keep them in, labelled appropriately?  Or a better idea for how to identify/store them?

(I'll leave this open pending sorting out the junior glasses)

**Comment by DoESsean** [comment]
Kids glasses are in a labelled bag in the safety glasses drawer.
