### ISSUE TITLE
Mug heat press

### ISSUE THREAD

**Issue by anotherrrealm** [DoESLiverpool/somebody-should#1475]
I went to use the mug heat press today, firstly it looked like it was hanging off the work surface, secondly it has a loose bolt which leaves part of it hanging. Tried to tighten it but don’t want to mess with what I don’t know
![257DB18A-2462-470E-AE63-0317340C38ED](https://user-images.githubusercontent.com/51460495/89737787-d0f08180-da6b-11ea-962c-5a3b14c595a3.jpeg)

**Comment by amcewen** [comment]
I've just had a look at it, and that screw seems to be attached now.  I haven't used the mug press, so I'm not 100% sure if it's now looking like it should, but there's nothing that looks obviously wrong now.

I might try putting a mug through a heating cycle to see how it fares, or maybe @JackiePease can have a quick look some time to see if she agrees it seems fully reassembled now?

**Comment by magman2112** [comment]
All fixed.

The heat jacket is held onto the bar by a couple of thumb screws, once these are removed, the Allen screw head is accessible to screw it back on to the lead screw.
