### ISSUE TITLE
Vacuum Former - needs addditional heating elements and/or a smaller frame to hold items in place

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1479]
The vacuum former uses quite big sheets of material but only softens the central part (admittedly a big improvement).
This could be a bit wasteful, particularly when learning how to best use it.
Smaller frames are available, but fairly expensive: https://www.technologysupplies.co.uk/c-r-clarke-725-917-vacuum-former-reducing-frame.html
@Sean-anotherone has suggested that he might be able to make one.
Also perhaps we could add more heating elements to get nearer to the edges.

**Comment by magman2112** [comment]
The heating elements fitted to the vacuum former were not providing sufficient heat over the full area of the bed, so I identified some possible replacement heater elements and managed to pick some up from eBay.

These new elements are 400W ceramic heater elements and I managed to pick up 4 of these several months ago.

Just before Christmas, @Sean-anotherone and I started working on installing these new elements. An 3mm aluminium sheet was used as a mounting plate, with slots cut to take the elements and their associated mounting clips. Ceramic connector blocks and mineral insulated wire was then used to connect all of the elements together and then connected to the vacuum former heater power connections.

Initial tests show an apparent consistent heating across the whole bed and successful vacuum forming of some test pieces.

On the final test, we did have some smoke coming from the heater elements that will need some further investigation. It was likely some contamination burning off, but we need to make sure that something isn’t overheating.

**Comment by amcewen** [comment]
Superb news!  Well done @magman2112 and @Sean-anotherone for getting it up and running, and thanks for the update here.

Given how much trouble we've had sourcing heating elements, can you stick a link in to the ones you bought so we know what we're looking for if we have to get any more :grin:

**Comment by amcewen** [comment]
@magman2112 had any chance to dig out the link to the heating elements yet?

**Comment by magman2112** [comment]
I originally found the elements on eBay:

https://www.ebay.co.uk/itm/Pearlco-FSR-300w-Ceramic-Heater-Element-with-clips-for-Vacuum-forming-Vivarium-/294019053961

But as eBay items can disappear over time, I did a bit of searching and found a retail supplier:

https://www.leisureheating.co.uk/product/400w-full-sze-ceramic-emitter-curved-fsc400/

For completeness, we used 4 of the Pearlco 400W elements in the Vacuum Former.

**Comment by amcewen** [comment]
Lovely, thanks!  Can this be closed now then? (Dare I suggest... ;-)

**Comment by magman2112** [comment]
I would like to keep this open till we have clarified the smoking issue, plus we need to devise a method to fit the guard for the heater elements before the machine is properly safe to use.

**Comment by amcewen** [comment]
We still need to get the guard fitted for this — it's the square mesh for it.  It  doesn't quite fit in the original location as the new heating elements are a bit deeper, but there's a length of aluminium U-channel which should be able to be fitted along the sides to provide a slightly lower channel for the mesh to fit into (if anyone wants to give a hand...).

**Comment by amcewen** [comment]
The guard has now been fitted (not sure by whom), so this is done!
