### ISSUE TITLE
Switch over Sophia server with desktop computer

### ISSUE THREAD

**Issue by ReddbridgeMark** [DoESLiverpool/somebody-should#148]
The server currently being used to power Sophia is very noisy - a desktop computer replacement is located on the floor beneath it ready to swap out.

This was attempted yesterday (including clearing the copious amounts of dust collected inside the desktop computer, which looked more like the insides of a Manchester cotton mill than a computer) however the hard drive in the server has a different connection type - I believe it is a SATA drive while the desktop only has IDE connections? The connection types have to be confirmed, and a converter bought before the HD can be installed.

**Comment by ReddbridgeMark** [comment]
http://www.misco.co.uk/product/173042/StarTech-com-2-5in-and-3-5in-40-Pin-Male-IDE-to-SATA-Adapter-Converter-bidirectional-IDE-SATA-IDE-to-SATA-Converter?fromProductList=1

http://www.misco.co.uk/product/193402/Akasa-Super-slim-SATA-rev-3-0-data-cable-with-securing-latches-15cm-Blue
http://www.misco.co.uk/product/173099/StarTech-com-12in-SATA-Serial-ATA-Cable

**Comment by amcewen** [comment]
Ordered.  I skipped the data cable (I've got a couple too, if the one in the broken desktop machine isn't any good), and got a Molex->SATA power cable instead of the one linked.

**Comment by amcewen** [comment]
Hopefully when this issue gets closed it'll also have fixed issue #82 :-)

**Comment by DefProc** [comment]
That's a surprise, I was sure the motherboard had SATA, though I'd expect
it to need a cable.

**Comment by ReddbridgeMark** [comment]
No I checked the MoBo for a SATA port but none to be seen, also googled for
computer model & says just PATA.

The connector + cable is only a tenner anyway, so should be up and running
inside a week.

**Comment by amcewen** [comment]
Parts have arrived and are with @ReddbridgeMark.  @DefProc did discover a SATA connector on the motherboard last night though, so it might not be needed.  Either way, we should have enough to get things up and running :-D

**Comment by ReddbridgeMark** [comment]
Switch over complete & incredibly noisy server now decommissioned. Corel & Laser Cutter software working and operational, job transmission to laser cutter tested OK. 

Old parts (server, keyboard, mouse and monitor) remain in situ, but are tidied out of the way (in case need to be recommissioned for any reason).

**Note:** Windows 7 may need reactivation.
