### ISSUE TITLE
Buy new tips for the mcqn soldering station

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1483]
Paul H mentioned that all the existing soldering tips are worn out.
We should check and buy some new ones.

**Comment by JackiePease** [comment]
Soldering tips seem to be available here: https://uk.rs-online.com/web/b/thermaltronics/
Could someone please list the ones we should get.

**Comment by amcewen** [comment]
Issue #1111 has details of the last tips we bought, although I didn't get a wide one then.  Looking through my order history, the [wide one is a 2.5mm straight chisel tip](https://uk.rs-online.com/web/p/soldering-iron-tips/8609412/)

**Comment by JackiePease** [comment]
I've ordered all the above (2 x 1mm tips to get over the free postage limit) RS reference number 157773638

**Comment by JackiePease** [comment]
These have arrived - I've put the chisel tip one in the soldering iron and the rest on @amcewen desk

**Comment by JackiePease** [comment]
3 of the tips have now been added to the soldering station - the duplicate one in in @DoESsean drawer
