### ISSUE TITLE
Buy our own PAT tester

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1485]
Reminded by a [PAT tester showing up on a bidspotter auction](https://www.bidspotter.co.uk/en-gb/auction-catalogues/wignall-brownlow/catalogue-id-wi310080/lot-8c6518bb-7270-4507-8b2d-ac2100baace1), it'd be useful to have our own PAT testing capabilities.

Checking to see how expensive the auction one would normally be (about £1k), it seems that in general PAT testers [start around £250}(https://www.pat-testers.co.uk/collections/pat-testers) brand new.

I don't know whether those at the cheaper end are worth getting - it looks like they might be and they *look* to be fairly simple to use.  Maybe @Dowz77 can give us some advice on them?

**Comment by Dowz77** [comment]
A cheap tester would be more than adequate, I had a Kewtech KT71,  https://www.pat-testers.co.uk/collections/pat-testers/products/kewtech-kt71 , and it performed all the required tests. Expensive testers just speed up the process of recording the results. The longest part of PAT testing is compiling the appliance register, manually recording test results and producing the label. 
I would question if you need to PAT test or if a record of visual inspections would suffice, most defects are found by inspection, cable damage, cracked casings, wrong fuse size.

**Comment by magman2112** [comment]
Checking on the website that @Dowz77 mentioned, it appears that the Kewtech KT71 is no longer available, but I suspect that a replacement - the Kewtech KT72 is. 

On its own, the KT72 is listed at £275 +VAT, but is would suggest getting one of the kits available from tis supplier, as they also include additional labels for PAT testing, plus a Microwave Leakage detector and mains socket tester. The Microwave Leakage Detector would be a useful additional tool for use in Repair Cafe's in the future, as will the PAT tester itself. the kits are listed from £309 (or £339 with a bag), so not much more for the extra functionality.

**Comment by amcewen** [comment]
Thanks for that @Dowz77 and @magman2112.  

I've ordered one of the [Kewtech KT72 Kit A](https://www.pat-testers.co.uk/products/kewtech-kt72-kit-a) as the £339 one didn't include the microwave tester and I figured that was more important than a bag :-D

**Comment by amcewen** [comment]
So it turns out that the KT72 is *also* no longer available, so they've replaced it with the [EZPat](https://www.pat-testers.co.uk/collections/pat-testers//products/kewtech-ezypat-pat-tester) instead.

It's all arrived, and I've left the box with it all in on the floor by @DoESsean's desk.  We need to work out where it's going to live (and how to use it, I've opened #1529 for that...)

![image](https://user-images.githubusercontent.com/108468/101629709-ad3d4800-3a19-11eb-91e7-b7c406e49b5b.png)
