### ISSUE TITLE
We need You Can Book Me to avoid public holidays

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#149]

**Comment by johnmckerrell** [comment]
I suppose as there's only 8 bank holidays a year it shouldn't be that hard to do manually, I don't know if we can get the laser calendars to subscribe the public holidays feed on Google and have it mark those days as "busy".

For now I've set 31st August (and 25th May) to busy in small and large laser calendars.

**Comment by DefProc** [comment]
I've just blocked out the week between xmas and new year (after someone booked a laser induction in it!)
We'll almost certainly need to go through next year (2017) to block out the bank holidays

**Comment by DefProc** [comment]
Just done the May bank holiday, but I'm assuming there are some more during the year. And even May. 

https://www.gov.uk/bank-holidays

**Comment by aubergine10** [comment]
There are public google cals of UK national holidays - is it possible to merge one of those in to the google calendar on the website? Then at very least we could display a message stating "Except on public holidays"?

**Comment by DefProc** [comment]
Almost forgot Monday! Just cancelled the bookings we have, although some of those also indicated no laser induction. 

Bank Holidays 2017–2018 that need blocking out are: 

2017 

 - [ ] 29 May	Monday	Spring bank holiday
 - [ ] 28 August	Monday	Summer bank holiday
 - [ ] 25 December	Monday	Christmas Day
 - [ ] 26 December	Tuesday	Boxing Day

2018

 - [ ] 1 January	Monday	New Year’s Day
 - [ ] 30 March	Friday	Good Friday
 - [ ] 2 April	Monday	Easter Monday
 - [ ] 7 May	Monday	Early May bank holiday
 - [ ] 28 May	Monday	Spring bank holiday
 - [ ] 27 August	Monday	Summer bank holiday
 - [ ] 25 December	Tuesday	Christmas Day

**Comment by DoESsean** [comment]
How do you go about blocking out these dates in the calendar? I assume me just putting 'Closed' as an Event isn't enough :)

**Comment by johnmckerrell** [comment]
@DoESsean that's almost enough, just make sure the event shows as busy, that'll happen by default if you put a timed event but not if you do an "all day" event.

**Comment by DefProc** [comment]
The process is to add all day, events set to be busy to each of the calendars we use for booking. I generally set the events as public, so it appears as an explanation to anyone viewing the public calendar embeds on the website.

Events to add: 

 - [ ] Small laser cutter calendar,
 - [ ] Large laser cutter calendar,
 - [ ] (1) Main Room Desk bookings calendar,
 - [ ] (2) Main Room Desk bookings calendar,
 - [ ] (3) Main Room Desk bookings calendar,
 - [ ] (4) Main Room Desk bookings calendar,
 - [ ] (5) Main Room Desk bookings calendar,
 - [ ] (6) Main Room Desk bookings calendar,

**Comment by DoESsean** [comment]
Did some clever script get written, or are we just going to do this by hand? It's no great hardship for me to do at the beginning of the year.

**Comment by DoESsean** [comment]
This is something that isn't actually necessary, and can be done manually. As it's not a vital issue, I'm closing it, but adding labels to make it easy to find should anyone be so inclined in the future.

**Comment by johnmckerrell** [comment]
So long as I can re-open this ~if~ when we forget next time!

**Comment by johnmckerrell** [comment]
@DoESsean or maybe when we find you didn't do it properly! ;-) If you're going to do an "all day" booking you have to manually mark it as "Busy". All day appointments are "Free" by default, whereas appointments with times are "Busy" by default.

**Comment by johnmckerrell** [comment]
@DoESsean Oh and don't forget to make sure the desk bookings calendar is covered too! And the visitors calendar!

**Comment by johnmckerrell** [comment]
See comments above, missed calendars and showing as Free when it should be Busy (spotted at least one next year).

**Comment by DoESsean** [comment]
I was just about to do this for 2021 when a thought occurred - given that a whole lot of people that regularly use the lasers have out of hour memberships, and can access the building whether we're here or not, does it make sense to leave these booking slots open so that people can still use them?

If someone wants to use the laser on Good Friday, for example, but it shows as busy, they might decide not to come oin even though the machine is actually not in use.

**Comment by seanspotatobusiness** [comment]
Would it be possible to mark them as only available to users with
out-of-hours membership?

**Comment by DoESsean** [comment]
I don't know if the system is that smart!

Sounds like a @johnmckerrell question to me.

**Comment by johnmckerrell** [comment]
It's not, but I think we can probably just close this issue now and expect that Optimism ™️  will help, I've added an issue on that project: https://github.com/DoESLiverpool/optimism/issues/30
