### ISSUE TITLE
Ultimaker support

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1495]
I have yet again attempted to use Ultimaker and the top one was originally problematic i.e. would not produce a good flow of melted plastic.  Now the bottom ultimaker just took the feed and travelled around the printer i.e. did not stick to the base etc.  I have recently been told that the machine needs to be reset.  I am not that knowledgable with this but does someone have/create a standard fix methodology AND a how to reset the machine i.e. how to level off the base, check nozzle distance from base etc.  Thank you in advance.  P.s.  I'm happy to watch someone talk me through this and I can then create a handout/ document so we can collectively use this.

**Comment by JackiePease** [comment]
I think you might mean bed-levelling - there's instructions here (https://support.ultimaker.com/hc/en-us/articles/360011848060-Bed-leveling-for-the-Ultimaker-2), or I could show you next time you're in.he printer i.e. did not stick to the base etc.
