### ISSUE TITLE
Point jitsi.doesliverpool.com to my VPS

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1499]
For Maker Night, I'm provisioning Jitsi on `REDACTED`. Can @amcewen or @johnmckerrell make an A record for this?

**Comment by johnmckerrell** [comment]
I've done this now but apparently 34sp take /forever/ to update the DNS, don't try checking locally until this is update:

```
dig @ns2.34sp.com. jitsi.doesliverpool.com
```

**Comment by MatthewCroughan** [comment]
Done.
