### ISSUE TITLE
Improve the RepRap calibration instructions on the wiki

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#15]
http://wiki.doesliverpool.com/RepRapPrusaMendel/Calibration runs out before documenting the with/without cooling instructions.  Would be good to finish them, and expand the instructions to help anyone who isn't super-familiar with the process to be able to install a new filament

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
