### ISSUE TITLE
Arrange an epic trip to FabLab Elesmere Port

### ISSUE THREAD

**Issue by Red-Violet** [DoESLiverpool/somebody-should#150]
Ideally to try out cutting a desk from the Opendesk set and to see how feasible it will be to have furniture made from the Opendesk set for the whole space.

**Comment by jackie1050** [comment]
I saw these shelves that would look great at DoES and might also be suitable for CNC - http://www.instructables.com/id/DIY-Modal-Designer-Shelves-T-Shelves. In any case I would like to see the CNC machine.

**Comment by amcewen** [comment]
As an alternative to Fab Lab, apparently http://www.gocre8.co.uk/ in the Baltic Triangle have a CNC router and are interesting guys, so we could see if they're up for us visiting sometime

**Comment by amcewen** [comment]
As an alternative to (or maybe a more advanced thing to move onto once we've done a few) OpenDesk designs, this Parametric Lace shelving design is really nice http://casajasmina.arduino.cc/casa-jasmina-and-the-parametric-lace-shelving-system/ (not open source though, so we'd have to design our own)

**Comment by amcewen** [comment]
Adding meeting action label as this was mentioned in the Organisers meeting - http://wiki.doesliverpool.com/DoESMeetingMinutes20151029

**Comment by amcewen** [comment]
Quite hard now that Fablab Ellesmere Port has closed :-(
