### ISSUE TITLE
The microwave isn't working

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1500]
The microwave isn't working - no lights are showing.
I've tried using different sockets and swapping out the fuse. Neither had any effect.
Is there a hidden switch somewhere?
A couple of days ago Jade was trying to use the kettle - it wasn't working and we had to reset the switch in the cupboard. Maybe this is related (although I think I've used the microwave since).

**Comment by blancmatter** [comment]
I opened the microwave (6 screws at rear, 1 screw at side, side and top pabel removed).

There is a longer type internal fuse which is blown (beeped it out with a multimeter). Its a 10A 240V ~ rated. Unfortunately we don't have any 10A fuses of this size in the rotary electronics drawers.

![Microwave](https://user-images.githubusercontent.com/45846630/95196701-5a080880-07d0-11eb-8400-b82e0c25c9c0.jpeg)

This is a direct drop in replacement for the fuse. 
https://uk.rs-online.com/web/p/cartridge-fuses/7690079

Image of fuse here;
![Fuse](https://user-images.githubusercontent.com/45846630/95197854-27f7a600-07d2-11eb-8221-d3807937bc27.png)

**Comment by blancmatter** [comment]
I've taped the blown fuse to the top of the microwave

**Comment by amcewen** [comment]
I think there are some fuses in one of the metal drawers in the CNC room too.  I don't know if any are 10A though...

**Comment by MatthewCroughan** [comment]
@blancmatter excellent work disecting that. Brave too, I wouldn't be brave enough to touch microwave internals.

**Comment by amcewen** [comment]
RS were going to charge a fiver P&P, so I've ordered 5 from Farnell instead - https://uk.farnell.com/littelfuse/0314010-mxp/fuse-quick-blow-10a/dp/1453896 - as I've got a trade account so don't pay postage there.

**Comment by blancmatter** [comment]
I popped the new fuse in and all seems to be working with the Microwave. I **very briefly** tested microwave, fan oven, grill and combi modes and the fuse didn't go.

We have 4 spare fuses in the Electronics Carousel (Top left Drawer marked fuses) and these are in a packed marked **Microwave**

CLOSED (for now?)
