### ISSUE TITLE
Please add me to the Does Liverpool Somebody should repository.

### ISSUE THREAD

**Issue by blancmatter** [DoESLiverpool/somebody-should#1504]
Created as per instructions on;

https://github.com/DoESLiverpool/somebody-should/wiki/Joining-DoES-Liverpool-on-Github

**Comment by amcewen** [comment]
You should have an invite now.  Feel free to close this once that's arrived :grin:

**Comment by blancmatter** [comment]
Great. I can now close issues!

CLOSED
