### ISSUE TITLE
Set up the new table saw

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1505]
Tonight I brought in a table saw. I got it for £50 on gumtree. I need this for a personal woodworking project which is going to use french cleats, requiring a tool to perform 45 degree angle cuts.

I only need it for this one project, so I figure it would be useful for everyone else. DoES can have it.

![IMG_20201014_203018](https://user-images.githubusercontent.com/26458780/96041550-e4510c00-0e63-11eb-837f-78bea6d5e513.jpg)
![IMG_20201014_203032](https://user-images.githubusercontent.com/26458780/96041571-ea46ed00-0e63-11eb-8b23-1ef5a728ecd4.jpg)

**Comment by MatthewCroughan** [comment]
Last night Sean and I evaluated that it was not worth setting up immediately. This was echoed by Adrian and Jackie who believe this first needs an induction process and a place to stay. Additionally we need a riving knife for safety.

**Comment by Sean-anotherone** [comment]
The riving knife will be in the box if it isn't fitted already, together with a guard (which is visible in the box).
Sean


    On Friday, 16 October 2020, 15:06:00 BST, MatthewCroughan <notifications@github.com> wrote:  
 
 


Last night Sean and I evaluated that it was not worth setting up immediately. This was echoed by Adrian and Jackie who believe this first needs an induction process and a place to stay. Additionally we need a riving knife for safety.

**Comment by amcewen** [comment]
Just for completeness, @JackiePease and I don't just *believe* that this needs an induction and risk assessment before it's used, it **does** need a risk assessment page on the wiki, and people will need to have an induction before they can use it.

**Nobody should use the table saw until that's in place**

**Comment by MatthewCroughan** [comment]
@amcewen Who do you think is best suited to create a risk assessment?

**Comment by drakard** [comment]
Hello. Just to poke my nose in where it is probably not wanted (these things just come up in my email). There were a few things that weren't obvious to me that might have been nice for an induction (or a poster/checklist etc.) Probably all known to you guys already but just in case.
- What are push sticks and using them.
- What is kickback, why does it happen, ejection. The way it can pull your hand into the blade. Fully finishing cuts.
- Posture and position.
- No gloves/short sleeves
- Dust & safety.

I hope that's a higher % useful than tiresome :)

**Edited:** because I misread some of the previous comments.

**Comment by MatthewCroughan** [comment]
@drakard That's a fantastic idea, not only for this machine but for other machines in the space. Where possible, for each machine we should hang up posters behind the machine with exactly your proposed guidance, warnings, and maybe a link/qr code to the wiki page for the machine. Perhaps we can do this well for this machine first to lead as an example. Possibly relates to #20

**Comment by drakard** [comment]
@MatthewCroughan Feeling guilty now because I _started_ making a poster for the laser cutter.

**Comment by MatthewCroughan** [comment]
By all means, if you're making the posters I'll follow your template and make them in your style for the other machines. The only thing I'd want to add to any potential posters is the wiki url, and contact details for the current maintainer of that machine if there is one. For example, there could be an email address for the laser maintainer team `laser@doesliverpool.com` which auto-creates a github issue, something like this. I outlined my dream here https://github.com/DoESLiverpool/somebody-should/issues/1347.

The latter bit about representing maintainership of machines might take a while, so just having a wiki URL on the posters would be great for now :smile:

**Comment by drakard** [comment]
@MatthewCroughan I'm afraid I haven't really kept on with it since I left the space... actually it turned out to be a bit of a bigger job than I expected to capture everything that is conveyed in face to face inductions.

I just thought, it would be nice to save some work by reusing assets between makerspaces. But I checked online and sadly there doesn't seem to be much out there in the way of safety posters. This was the best thing I saw https://ritz.citl.mun.ca/pluginfile.php/598/mod_page/content/3/Table%20Saw%20Safety%20Procedures.jpg

**Comment by MatthewCroughan** [comment]
@drakard That looks fine for now, ready made.

**Comment by RussCoty** [comment]
Russell Ranting Warning:

Having seen a few generally very sensible people whom I know end up in hospital and at least 3 fingers made about an inch shorter each by a table saw I am VERY VERY VERY wary about using one myself these days, nevermind leaving one in the workshop without considerable hurdles to turn on the thing. 

Yes I know we are meant to all take responsibility for our own behaviour and safety. Including maker night visitors etc. HOWEVER I fear people just don't understand the sheer danger of these particular tools vs let's say a pillar drill. 

One solution to mitigating risk may be an all hands (whatever number people have) must be on the handles alarm for a sled. With clamping. No freehand cutting allowed. Even push sticks or gripper type holders are very very easy to slip with. 

If we do not put in place this kind of system....or saw stop if we can do that legally in the UK....there WILL be a close shave and there WILL almost cetainly be an accident. 

Sorry for the rant but if I don't say these things I would struggle to live with myself.

**Comment by seanspotatobusiness** [comment]
Edinburgh Hacklab put some electronics in place on certain pieces of
equipment (including the table saw) so it couldn't be powered unless
you swiped an NFC tag which had been authorised (by training) to use
it.

**Comment by MatthewCroughan** [comment]
@RussCoty No amount of eyes overseeing the act will prevent someone from losing a finger. I value my ability to play guitar too much to turn it on myself. I'd say if nothing can be done to almost guarantee that finger chopping doesn't occur then it's not worth having in the space at all. All I wanted to do is cut a piece of wood at a 45 degree angle in order to create french cleats, so maybe there's a better way to do this particular task?

**Comment by Sean-anotherone** [comment]
The router table I donated ages ago - I thing there might even be a 45° bit in the box of tools
Sena
    On Tuesday, 27 October 2020, 23:14:13 GMT, MatthewCroughan <notifications@github.com> wrote:  
 
 


@RussCoty No amount of eyes overseeing the act will prevent someone from losing a finger. I value my ability to play guitar too much to turn it on myself. I'd say if nothing can be done to almost guarantee that finger chopping doesn't occur then it's not worth having in the space at all. All I wanted to do is cut a piece of wood at a 45 degree angle in order to create french cleats, so maybe there's a better way to do this particular task?

**Comment by johnmckerrell** [comment]
For angles surely a mitre saw is the thing? I don’t know if it’s definitely safer but it seems like it would be. 

--

**Comment by DoESsean** [comment]
*I've* used a mitre saw.

If that isn't a testament to their safety and ease of use, nothing is.

**Comment by RussCoty** [comment]
> Edinburgh Hacklab put some electronics in place on certain pieces of equipment (including the table saw) so it couldn't be powered unless you swiped an NFC tag which had been authorised (by training) to use it.

This seems very very sensible. 

My main concern is not taht people will not be sensible but that I am going to have to reach under a table to pick up someone's finger one day.

**Comment by RussCoty** [comment]
> @RussCoty No amount of eyes overseeing the act will prevent someone from losing a finger. I value my ability to play guitar too much to turn it on myself. I'd say if nothing can be done to almost guarantee that finger chopping doesn't occur then it's not worth having in the space at all. All I wanted to do is cut a piece of wood at a 45 degree angle in order to create french cleats, so maybe there's a better way to do this particular task?

No I think the table saw is 100% the correct tool for this kind of profile. I'd be happy to help you on that. 

A router table would work but a mitre saw would not.

**Comment by MatthewCroughan** [comment]
@RussCoty there's a video here where someone demonstrates making cleats with all the possible tools. Mitre saw is second best and can manage it, but nowhere near as ideal for making metres of cleat! 

https://youtube.com/watch?v=Nbx3AZvfL-8

**Comment by MatthewCroughan** [comment]
This video is incredible. https://youtu.be/eUx8oTIALmg

I cannot believe this is how kickback works. It imparts so much energy into the remaining piece that it swings it **around** the blade. If you actually were to lean on the piece that experienced the kickback, it would swing your hand into the center of the blade. 

![image](https://user-images.githubusercontent.com/26458780/97636212-ae4d8380-1a30-11eb-92c5-568ce2021f5b.png)

**Comment by reasonPi** [comment]
I've been looking for a safe way to use a table saw recently.In fact, I think the whole work area needs to be rearranged, and in my experience, the large band saw in the laser cutting room is almost damagedThe band saw blade was rusted and worn and the motor had trouble starting. I repaired another small band saw two months ago and unfortunately his blade was damaged last week.

**Comment by reasonPi** [comment]
Sawstop and festool have patent-based safety table saw systems to protect your fingers, but they are very expensive, costing around 2,000 pounds.

**Comment by MatthewCroughan** [comment]
I have moved this physically to the Astral Ship in Wales and am going to use it there, since it seems too much for DoES to provision and train people on at this time.

I have opened a new issue in [#89(astralship)](https://gitlab.com/astralship/snowdonia/-/issues/89) which also contains a cross reference to this page/issue on Github, which will continue to document how we provision it up here in Wales.

**Comment by patlink72** [comment]
Hi @MatthewCroughan as 
![IMG_20200720_110025](https://user-images.githubusercontent.com/4356065/105414042-debb4d00-5c2e-11eb-99d3-4f5fa8300795.jpg)
 I said this evening I am happy to try and spare some time to help set up the saw and safe methods to get the most out of the saw! I had this one for years now a good workhorse for a cheap set up. Jig are easily make to work save

**Comment by patlink72** [comment]
Table saw is mainly only good for ripping material to length or sheet material to size. Cross-cutting is best done on a mitre saw or with a table slide
