### ISSUE TITLE
Consider buying a new k40 laser to replace Sophia

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1508]
During tonight's maker-night on Jitsi, we discussed that Sophia's current situation is leading to a high unmet demand for laser cutters. The approach of Christmas is increasing this demand also. The only laser that is currently fully operational is Gerald, with Monty being provisioned now via #955. Sophia is not going to be operational any time soon #1468 #1399 #1310 

I think it would be a good idea to buy a brand new laser. There are many k40 type lasers available on eBay in the range of £265 - £299 that would put us in a better position than we are now if we simply replaced Sophia with it.

![image](https://user-images.githubusercontent.com/26458780/96927198-9d3fc800-14ae-11eb-874e-b9c1b8353f0c.png)

## Pros 

- Immediately places us in a better situation to handle laser demand
- Immediately available, shipped from Europe
- Will perform much better than Sophia will in its current state
- Comes with better software out of the box (k40whisperer)

## Cons

- Requires setup from member(s) of the community (But so does Sophia in its current state..?)
- Requires a separate purchase and installation of superior mirrors, (default ones don't perform well)
- Users may need to get used to the new software

If possible, could @Sean-anotherone or @LeeCarmichael comment? :smile:

**Comment by Sean-anotherone** [comment]
This might help, but as you say, the machines cheapo aren't much good.
It was suggested this evening that if Sophia is relocated into the event room I'll try and get it working (although we'll be back to a trunk-out-the-window for extraction).
That will also make a full stripdown and bearing replacements for Sophia much simpler (when Tony comes online - something I made good progress on today.)
I still think that fixing the basically pretty good but completely worn out Sophia is a better bet.

Sean


    On Thursday, 22 October 2020, 21:43:10 BST, MatthewCroughan <notifications@github.com> wrote:  
 
 


During tonight's maker-night on Jitsi, we discussed that Sophia's current situation is leading to a high unmet demand for laser cutters. The approach of Christmas is increasing this demand also. The only laser that is currently fully operational is Gerald, with Monty being provisioned now via #955. Sophia is not going to be operational any time soon #1468 #1399 #1310

I think it would be a good idea to buy a brand new laser. There are many k40 type lasers available on eBay in the range of £265 - £299 that would put us in a better position than we are now if we simply replaced Sophia with it.



Pros
   
   - Immediately places us in a better situation to handle laser demand
   - Immediately available, shipped from Europe
   - Will perform much better than Sophia will in its current state
   - Comes with better software out of the box (k40whisperer)

Cons
   
   - Requires setup from member(s) of the community (But so does Sophia in its current state..?)
   - Requires a separate purchase and installation of superior mirrors, (default ones don't perform well)
   - Users may need to get used to the new software

If possible, could @Sean-anotherone or @LeeCarmichael comment? 😄

**Comment by magman2112** [comment]
From the work I completed on Sophia on Saturday, I would say that Sophia is still a better machine than most K40’s. 

The key issue with Sophia is the carriage, which has been considerably modified and improved over the years. I think we can resolve most of the issues with Sophia by designing and making a new carriage, using the CNC machine. The rest of the work is more general maintenance and eventually fitting a new controller.

The other improvement would be replacing the mirror mounts with more modern replacements.

**Comment by MatthewCroughan** [comment]
@magman2112 It was certainly unexpected that you would arrive to save the day so quickly! So thank you for that. 

> I would say that Sophia is still a better machine than most K40’s.

The options available for purchase are only going to get better and cheaper over time, so I think this issue will become relevant again at a later date, when/if repairing/improving Sophia becomes more costly than the alternative. But now that you've done all this work and we have a cheaper path to improvement, that will take a while. 

We can re-open this issue it if it becomes relevant again, I think the appetite for this discussion will now be low.
