### ISSUE TITLE
Increase the amount of storage in the main space

### ISSUE THREAD

**Issue by Red-Violet** [DoESLiverpool/somebody-should#151]
As proposed at the last organisers meeting. I will visit Ikea and measure up and see what I believe to most appropriate and then request approval and budget. #48

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
I'm going to do be doing an inventory on Thursday so I'll see what's in current boxes and try and work out if we could reorganise things to make better use of existing storage.

**Comment by DefProc** [comment]
I believe @Red-Violet is still offering to spec and choose storage for the main space. I think this issue stalled over a proposed epic trip to the now closed Ellesmere Port FabLab to cut opendesk storage which didn't complete.
