### ISSUE TITLE
Get new brush attachment for the Henry hoover

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1515]
The cleaner has reported that we're missing the tools for the Henry hoover, in particular the circular brush.  I did suggest that she could 3D print some, but that would be tricky for the brush attachments :-D

We should see if we can buy spares and get a new set.

**Comment by johnmckerrell** [comment]
They're in the filing cabinet, I spotted the other day.

**Comment by Robotorium** [comment]
I've got a spare set of them, I think. Let me go have a nosey, if they are
where I think they are I'm more than happy to donate.

Op wo 28 okt. 2020 10:16 schreef Adrian McEwen <notifications@github.com>:
