### ISSUE TITLE
Sophia broken

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#1518]
I took a look at Sophia last night (5 Nov) and the tube was filled with water - including the laser cavity.   Not sure how this has happened as there isn't any visible external damage, but there does seem to be some internal cracking toward the tube anode end.

A new tube is required - I believe Jackie is looking in to ordering this today (6 Nov).

I'm not sure about the short-circuit protection on the HV supply, so that may have also suffered damage, but without a tube in the machine it's not a simple matter to test.

A new tube should get the machine back in use, but the poor condition of the axes and bearings still needs to be addressed.

**Comment by JackiePease** [comment]
I've been in touch with Smoke and Mirrors - it's a Yongli 1000-C tube, they don't currently have any in stock and suggested CloudRay, where we bought the tube for Tony.
As this would involve a long lead time, I've asked @magman2112 if he can identify the relevant tube to order from HPC or other UK supplier. If not, I'll phone HPC on Monday lunchtime.

**Comment by JackiePease** [comment]
@magman2112 not sure which tube to buy - recommended phoning HPC and Millenium Laser on Monday lunchtime

**Comment by magman2112** [comment]
The new tube has arrived after being picked up by @JackiePease. @Sean-anotherone has now fitted this and Sophia should now be ready for use, in it’s temporary home in the event room.
