### ISSUE TITLE
Organise a baby and toddler work day in the events room

### ISSUE THREAD

**Issue by Red-Violet** [DoESLiverpool/somebody-should#152]
- [ ] tidy all the wires away from near the door so the area safe for the little ones
- [ ] find a suitable space for the extra chairs
- [ ] look at how child friendly the space is and if there are any  other obvious improvements to make 
- [ ] organise how to have the TV available if necessary e.g. DVD player, Chromecast
- [ ] buy some baby friendly things (further discussion needed)
- [ ] Set a date for a trial
- [ ] spread the word!

**Comment by amcewen** [comment]
Impact Hub Birmingham has been experimenting with this sort of thing too - see https://www.eventbrite.com/e/co-working-creche-tickets-18983634562 and http://www.famalam.org/radical-childcare/ for more details

**Comment by amcewen** [comment]
And for more info, Impact Hub Birmingham have just launched Parent Membership https://birmingham.impacthub.net/2016/12/27/parent-membership-launch/ which is a couple of days of hot-desking plus some "co-creche" hours.

**Comment by DoESsean** [comment]
Drat, the name of that excited me as it sounded like it would be similar in
design to what we had discussed, but it seems like it's just another creche
that runs inside a co-working space. Not that that's not good enough, but I
am starting to wonder whether or not other people have been told that they
can't just have a community creche thing without certified/qualified
leaders and a specific curriculum or something.

**Comment by johnmckerrell** [comment]
I'd like to reopen this, if we don't manage it in Dinky I think we should do it ASAP in the new place.

**Comment by ajlennon** [comment]
Excellent. Something like Amazon Mechanical Turk? What skills can they offer?

**Comment by DoESsean** [comment]
Since Dinky is being carpeted on Tuesday, I'm going to try and get the first of these organised by the end of the month. That way we will also be able to talk about it at the Inclusive Economy Awards.

**Comment by ajlennon** [comment]
Do we have to pay them minimum wage?

**Comment by amcewen** [comment]
We've [successfully run one session](https://doesliverpool.com/weeknotes/week-404-more-prep-for-child-friendly-co-working-plus-connected-3d-printing-and-dance-reactive-lights/) and we've got the [second Jelly Tots session this week](https://twitter.com/DoESLiverpool/status/1111311406350118914), it seems we can close this!  Yay!
