### ISSUE TITLE
Water for laser cooling

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#1520]
As the new tube for Tony has a far longer rated life than the normal ones, the advantages of purified water outweigh the cost.

Deionised water probably still isn't necessary, but good quality reverse-osmosis water is available pretty cheaply from most tropical fish shops (especially if they do marine invertebrates), the nearest I found in a quick search was :  https://www.merseysideaquaticwarehouse.co.uk/index.asp

That one's in aintree, a mile or so from me, so I'll find out their price.

Merseyside tapwater is actually pretty low in TDS / conductivity -  around 300uScm-1

Good RO should be down around 25uScm-1.  Regular DI water is better than 2uScm-1, and lab grade is <0.05 uScm-1 but a plant producing 10 or 20 liters per day can set you back >10k.  

Conductivity is the reciprocal of the resistance, in ohms, measured between 2 platinum black electrodes of 1cm2 area, 1cm apart.  If required, I have a conductivity meter kicking about somewhere.

**Comment by magman2112** [comment]
@Sean-anotherone has picked up some de-ionised water from the fish shop on Long Lane and this has already been used to fill both Sophia and Tony. There should be sufficient water left to change the water on Gerald as well.

Sean also said that now that we have their carboy for carrying the water, we can get a refill for a few pounds when required, it just needs someone to go to the shop on Long Lane to get it.

Closing this issue, as requested by Sean
