### ISSUE TITLE
Plug in the less-accessible toilet has been pushed too far down

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1521]
Somehow the plug has been pushed down into the plughole, so water doesn't drain through it (it will eventually, but only at a trickle)

It isn't usable at the moment.  Maybe we can ask the plumber to look at it when they're fitting the heater?

**Comment by magman2112** [comment]
I had a look at this today and the drain came apart completely when I tried to hand tighten the nut. It looks like the drain was badly corroded and very thin metal, so this is the likely reason for the plug to slip down in the first place.

I’m not sure if maintenance of the toilets is a landlord responsibility or not, so we need to try and clarify this quickly before we obtain a replacement.

**Comment by magman2112** [comment]
I have picked up a replacement sink drain from Screwfix. This one had a captive plug, which is likely to be more reliable than the push type plugs.

I needed some silicone sealant to install it, which Screwfix only had large tubes of, so I will bring some from home and hopefully fit this later today.

**Comment by johnmckerrell** [comment]
Great! I thought I’d answered the question about responsibility but now I see not. It would be the landlord’s responsibility but given its in a bad state anyway and he would pass the cost on to us I’m happy that us (you!) fixing it is a good thing.

**Comment by johnmckerrell** [comment]
@magman2112 did you fix this in the end? A plumber is coming on Friday to look at fitting water heater and replumbing the kitchen, we could ask him to finish this off too if necessary.

**Comment by amcewen** [comment]
This had been done last time I used it :grin:
