### ISSUE TITLE
Kitchen Plumbing

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#1522]
Plumbing in the kitchen is a bit rubbish,  angle of pipe far too steep and under-sink routing terrible, one sink is flowing very slowly and the pipe drips where it enters the stack.

Shopping list to sort it all out :

2 bottle traps
1 S trap 
2 x pipe
3 90° bends
2 swept tees
a few clips

Whatever extras are needed to remake the connection to the stack ( I did not measure how far out from the wall this needs to be)

Everything should be in the same size - the stuff that's there might yield a few of the required parts.

You can delete this template text.

**Comment by johnmckerrell** [comment]
Issue #1425 is tracking the hot water heater replacement which we're intending to get a plumber in to do, I've mentioned the drainage to him as well but he's obviously not going to be able to give us much of a quote without seeing it.

**Comment by johnmckerrell** [comment]
Plumber is going to quote for this so please shout if you think there's anything else he needs to know. I've mentioned that we would want the pipes to exit at the back and we would then move the sinks closer together as I'm aware that's part of @magman2112 's plan

**Comment by Sean-anotherone** [comment]
I don't think there's anything else to mention... but...
While I agree with the rear exit etc., the current gap for the dishwasher looks to be ~600mm wide - this is the width of a standard dishwasher and while the current one is narrower,any future replacement may be full size (I believe they are much more common), so leaving the gap at ~600 and just fixing the worktop more securely might be a better/more versatile way to go?
Sean


    On Tuesday, 24 November 2020, 12:08:55 GMT, John McKerrell <notifications@github.com> wrote:  
 
 


Plumber is going to quote for this so please shout if you think there's anything else he needs to know. I've mentioned that we would want the pipes to exit at the back and we would then move the sinks closer together as I'm aware that's part of @magman2112 's plan

**Comment by magman2112** [comment]
One of the reasons for moving the sinks closer together was to allow room to install some reasonable depth cabinets on the white wall in the kitchen, the extra 200mm makes this much more practical.

Should we need to replace the dishwasher in the future, then slimline dishwashers will still be available that will fit in the available space.

John, it is worth mentioning to the plumber about the dishwasher though, just to be clear that this is to be included in the alterations.

**Comment by JackiePease** [comment]
The left hand sink was leaking today - it seems that the water that had collected in the sink was leaking from the pipe under the plughole. I moved the stuff from the cupboard and put a bucket underneath the pipe. I asked AJ to check whether it was still leaking when he left.
If the plumber is coming fairly soon, perhaps we can just avoid using that sink until then (I've put a temporary sign on the draining board).

**Comment by magman2112** [comment]
The left hand sink was completely blocked, so I managed to drain this but it is still leaking. It appears that someone had put what looked like coffee grounds down this sink, which as it drains poorly anyway, helped to block it completely. The tap was also dripping, which with a blocked sink, could have led to some flooding. 

The connection to the sink was leaking, so I managed to tighten this up. I think it is leaking now from the connection going out of the side of the cabinet.

I will have another look at this today, to see if I can at least stop the leak. This sink definitely needs to be replumbed though, to eliminate the rise in the drain pipe, which is almost certainly causing the poor draining at the moment.

**Comment by johnmckerrell** [comment]
@Sean-anotherone @magman2112 As far as I know the re-plumbing still needs to happen so we'll ask a plumber to quote for this when he's in on Friday morning. Can we confirm that we want to push the left hand sink closer to the right hand one so that they're snug? If we ever get a bigger dish washer I would think the re-plumbing to separate them wouldn't be such a big job. (Of course if we find out tomorrow the dishwasher needs replacing this might be academic!)

**Comment by magman2112** [comment]
Yes please John. I suspect the only reason they were separated so much in the first place is that the drain pipes came out of the side of the cabinet rather than out of the back (as we now want it).

**Comment by johnmckerrell** [comment]
Had a quote back from the plumber of £850 which has me thinking we might be better off "just" doing it "ourselves" after all. What do we think about this then?

**Comment by Sean-anotherone** [comment]
<expletives deleted>  ( a great many expletives ).  
This plumber is planning to replumb the kitchen using solid gold pipe, I suggest (seriously) never even bothering to call them again.

To replumb the 2 sink drains in that kitchen would cost around £40 in parts and take a couple of hours tops, including a connection for the dishwasher.

If someone can measure the clearance behind the tightest gap and confirm that a regular 32mm pipe will fit (noting that it needs to be clipped which will hold it a little off the wall), I'll get the bits and do it next Thurs.
If the gap is tight, it may be possible to warm the pipe up and squish it, as long as it is only slightly crimped it won't impact the flow as only the right hand sink would be affected ( the gap behind the left sink is plenty)
Sean




    On Saturday, 16 January 2021, 12:07:14 GMT, John McKerrell <notifications@github.com> wrote:  
 
 


Had a quote back from the plumber of £850 which has me thinking we might be better off "just" doing it "ourselves" after all. What do we think about this then?

**Comment by johnmckerrell** [comment]
@Sean-anotherone it would be great if you can do it, I may be misunderstanding but you should be able to move the unit forward if needed so clearance wouldn't be an issue? I've updated the hot water heater. I think the short answer is it would be great if you can do it we just need to sort out the bits sometime.

**Comment by Sean-anotherone** [comment]
No problem, I did try to come in this evening to work out what's needed but there has been a disaster at the City Farm (I'm a trustee and do a lot of their maintenance) - they have a sinkhole !  It's under a roadway and I was pumping it out using a pump that discharges through a 3" pipe and was not making a dent - the water leak under it must be huge.
If not before, I'll measure / spec the bits on Thursday, but I have the kids this weekend so it might be another week until I can get in and do the job (some assistance would be good too, as the cupboards will need to be moved to get access behind)

Sean

    On Tuesday, 19 January 2021, 21:17:39 GMT, John McKerrell <notifications@github.com> wrote:  
 
 


@Sean-anotherone it would be great if you can do it, I may be misunderstanding but you should be able to move the unit forward if needed so clearance wouldn't be an issue? I've updated the hot water heater. I think the short answer is it would be great if you can do it we just need to sort out the bits sometime.

**Comment by magman2112** [comment]
I suspect that a significant part of the plumbers quote was for a new water heater. From a bit of research, I expect this to cost in the region of £1-200 depending on quality and flow capacity that we decide to plump for. One with a decent flow for the two sinks would tend to push the price well over £100.

As @Sean-anotherone has indicated, this is very much doable by us and I will work with Sean tonight to figure out the parts we need, which we can likely get from Screwfix. I expect this to be less than £100 for all the parts apart from the water heater. The only slight snag will be getting new drains that fit the IKEA sink and overflow, which may take some finangaling to work out and be leak free.

**Comment by magman2112** [comment]
Ok, Sean and I had a good discussion about this today, here are some of the key points.

There is sufficient space to give a good fall for the drain (30mm per metre for 38mm pipe) to give good clearance. 

We will likely use wooden blocks fitted to the brickwork behind the pipe brackets to give us clearance for the electrical conduits that are currently installed.

It would be a good idea to fit ground fault breakers for both the sockets in the kitchen area, as well as for the water heater.

Sean has suggested fitting individual 3kW water heaters under each sink, this will simplify the overall installation, whilst giving us a degree of redundancy by having two heaters. The existing water heater supply will be reterminated onto two switched fused Spurs to power these heaters. We will likely also run the cabling in conduit to give it some additional protection at the same time.

We are going to try and do some work on this over the coming weekend, though this is dependant on the weather ironically (we both have other things to do if the weather is reasonable).

**Comment by Sean-anotherone** [comment]
Rather than under-sink, I was thinking of something like these :
TINTON LIFE 220V Instant Tankless Electric Hot Water Heater Faucet Kitchen Instant Heating Tap Water Faucet with LED Digital Display(Big Under Inflow)


| 
| 
|  | 
TINTON LIFE 220V Instant Tankless Electric Hot Water Heater Faucet Kitch...

Features: Product Name: Fast electric faucet The main material: H59A level environmental refined copper + ABS en...
 |

 |

 |




or  a better one :
Pudin,220V Electric Instant Heater Tap,Supply Hot and Cold Water,Stainless Hot Water Kitchen Tap with LED Digital Display for Home Facilities(British Plug)(Silver)


| 
| 
|  | 
Pudin,220V Electric Instant Heater Tap,Supply Hot and Cold Water,Stainle...

NOTE: 1.There are two main situations in which our faucet leaking: A. The faucet water pipe leaking, the rubber ...
 |

 |

 |







Sean




    On Thursday, 21 January 2021, 22:30:05 GMT, Mike Gorman <notifications@github.com> wrote:  
 
 


Ok, Sean and I had a good discussion about this today, here are some of the key points.

There is sufficient space to give a good fall for the drain (30mm per metre for 38mm pipe) to give good clearance.

We will likely use wooden blocks fitted to the brickwork behind the pipe brackets to give us clearance for the electrical conduits that are currently installed.

It would be a good idea to fit ground fault breakers for both the sockets in the kitchen area, as well as for the water heater.

Sean has suggested fitting individual 3kW water heaters under each sink, this will simplify the overall installation, whilst giving us a degree of redundancy by having two heaters. The existing water heater supply will be reterminated onto two switched fused Spurs to power these heaters. We will likely also run the cabling in conduit to give it some additional protection at the same time.

We are going to try and do some work on this over the coming weekend, though this is dependant on the weather ironically (we both have other things to do if the weather is reasonable).

**Comment by magman2112** [comment]
After yet more discussion with @Sean-anotherone, we have agreed that the tankless water heaters are likely not a good idea for the DoES kitchen. A 3kW heater is not likely to provide sufficient flow for things like filling buckets for cleaning, etc.

An alternate is a 3kW heater under sink water heater with a 15L reservoir. So I have ordered the following from Screwfix.

https://www.screwfix.com/p/ariston-undersink-water-heater-3kw-15ltr/2371g?_requestid=607303

I also ordered the needed plumbing parts which should be ready for me to collect on Thursday. The total cost was £171.92, including the water heater, so quite a bit cheaper than the plumbers quote. There may be a few more parts needed, but I expect this to be less than £30 total.

Sean and I are planning to start sorting this out on Thursday evening.

**Comment by johnmckerrell** [comment]
I wonder if it's worth throwing a thermometer into the order too so that we can properly test the temperature from the heater (we're supposed to do this periodically). I liked the idea of the Redring heater and mentioned it over on #1425 because, being the one we already have, it's known to heat to the right temperature but given this one has a bigger reservoir that's probably better in a kitchen setting, and is more powerful so hopefully will get hot enough. I don't particularly know about thermometers but this one seems reasonable and has a decent rating https://www.screwfix.com/p/tpi-312c-immersion-tip-pocket-thermometer/82574

Very much appreciated that you've gone ahead and ordered stuff, will be great to get it done (I should really get back to the plumber and say thanks, but no thanks!) Obviously let us know the final cost and we'll repay.

**Comment by magman2112** [comment]
Ok, that is part one completed. @Sean-anotherone and I replaced the drain this evening, though it was quite hard work. We did notice though that the joint to the main down pipe is still leaking, despite a number of attempts to fix it. We suspect that it the seal area to the main pipe is too small an d likely needs to be removed and silicone sealant applied. This leak is only really apparent when it is raining though. All of the other leaks appear to have been eliminated though.

The dishwasher was reinstalled and appears to be working.

We still need to remix the water pipes to the wall and we need some additional plumbing to be able to install the water heater.

I’m afraid we left a bit of a mess in on the carpet as we were basically too tired to clean this up, as it was past 11pm when we finally got things back in place.

We will need to keep an eye out for leaks in the short term, plus we still need to install the water heater. This will likely be next Thursday again before we have a chance to get round to this.

**Comment by JackiePease** [comment]
The dishwasher is failing with error E24 - this appears to be related to drainage. I've switched it off but will need fixing asap as we don't have hot water for washing dishes at the moment.

**Comment by Sean-anotherone** [comment]
I just picked this message up.  When refuting the dishwasher at 1115pm I think I have pushed the drain pipe onto a blank stub.  Fix is very simple,  pull drain off, push onto other stub.  Remove tapd first.  Is 5 min job(literally)

Sent from Yahoo Mail on Android 
 
  On Fri, 29 Jan 2021 at 13:16, Jackie Pease<notifications@github.com> wrote:   


The dishwasher is failing with error E24 - this appears to be related to drainage. I've switched it off but will need fixing asap as we don't have hot water for washing dishes at the moment.

**Comment by magman2112** [comment]
I’ve just spoken to Sean and he thinks that he may have accidentally plugged the dishwasher into the wrong stub on the right hand sink drain.

When testing the flow of the drains before the dishwasher was plumbed in again, I blocked off the correct stub with gaffer tape to stop water flooding out. Sean in a tired state of mind though the stub with tape was blocked from before our work and put the dishwasher hose onto the adjacent stub. This stub is still sealed, hence the error code on the dishwasher.

The hose is on quite tightly, but it is likely only a minutes work to pull the hose off one stub, remove the tape and plug it into the correct stub if someone is capable of pulling the hose off the incorrect stub.

**Comment by JackiePease** [comment]
@Knottyashcreative was able to move the dishwasher to the correct stub yesterday morning - the dishwasher is now working fine

**Comment by magman2112** [comment]
Sean and I made a bit more progress on the plumbing yesterday evening. 

A new drain boss connection to the main down pipe has now been obtained and fitted, along with new sealant. This will hopefully eliminate the water leaking from this joint, though we could do with monitoring this for a few days, as the main leak appears to have been from rainwater coming down the stack.

The Water Heater is now installed on the wall and Sean has reterminated the mains power ready to connect the water heater later. We have identified though that we needed to install a pressure  relief valve and associated plumbing for this unit to work correctly. The pressure reliefs valve was included with the water heater and we have obtained most of the parts needed for this installation, but 2 parts are on order from Screwfix (for Delivery on Monday) and we need to source a reducer to complete this installation (Screwfix apparently don’t stock the part we need).

So a little bit more progress and hopefully one more leak eliminated. With a bit of luck and a following wind, we may even have hot water in the kitchen again, possibly next Thursday evening.

**Comment by magman2112** [comment]
With the arrival of a few critical parts, @Sean-anotherone and I were able to complete the installation of the water heater yesterday evening. 

We found a couple of small leaks that we were able to fix on the night, but we have left the fridge out for now so that we can see if any more leaks should happen. 

Also, we think that the water temperature may need adjusting. I have ordered this thermometer from Amazon that should arrive tomorrow, so that we can set the temperature correctly, as well as for Legionella testing going forwards.

https://www.amazon.co.uk/Brannan-Instant-Thermometer-Digital-Probe/dp/B00070Q8P4

We did notice though that there is a small water leak coming from upstairs. I will raise this as a separate issue.

With the water heater installed and the new drains completed, we can now close this issue.

**Comment by magman2112** [comment]
Opened new issue for water leak from upstairs #1553

**Comment by johnmckerrell** [comment]
Little confused why we're getting a meat thermometer to test the water temperature? I did suggest one from Screwfix, that no good?

**Comment by magman2112** [comment]
The one you suggested from Screwfix is effectively the same style of thermometer, it just doesn’t call itself a meat thermometer, even though it has an “penetration tip”. Other sites also call this model a food and liquids thermometer.

I just picked a similar thermometer with what I thought was a better protection cover for the measuring tip.

**Comment by amcewen** [comment]
That looks similar to this one:

![DSC_1189](https://user-images.githubusercontent.com/108468/107811427-0604c600-6d66-11eb-8f45-06643023c140.JPG)

Which is in the `Electronic thermometer` drawer in the workshop :grin: 

![DSC_1188](https://user-images.githubusercontent.com/108468/107811503-259bee80-6d66-11eb-98de-2facf202920b.JPG)
