### ISSUE TITLE
Clarke belt sander

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1525]
Wheels not moving and smoke appeared to come out. Not sure it was from dust or machine. Disconnected plug

**Comment by spironoo** [comment]
Seems to be the same issue as #1303

Disc seems to be working now but belt isn't. However, seem to be out of sanding discs.

**Comment by spironoo** [comment]
Bought new sandpaper discs, left them in the sanding drawer

**Comment by amcewen** [comment]
Agreed, it seems to b a duplicate of #1303.
