### ISSUE TITLE
Getald etching problems.  Geralds etching looks like it is drunk.  Ive cleaned the lens and tried one direction etching but its not fixed it. Apparently its been like this for a few days. Darran

### ISSUE THREAD

**Issue by dazz-ling** [DoESLiverpool/somebody-should#1527]
Please make your issue:

* Short (Unless required to be long)
* Specific
* Measurable
* Achievable
* Responsible
* Time-constrained

You can delete this template text.

**Comment by dazz-ling** [comment]
![20201205_183237](https://user-images.githubusercontent.com/26006843/101260786-2000a780-372a-11eb-8095-981cccad5672.jpg)

**Comment by JackiePease** [comment]
I did a laser induction this morning and cut a Permission to Make badge. The engraving wasn't as bad as this, but was a little bit uneven (I didn't take a photo at the time and Klara has taken the badge). 
The power seemed down a bit too.

**Comment by magman2112** [comment]
I was in DoES on Thursday afternoon and competed an alignment on Gerald, as well as a check over and another clean.

One of the rear mirrors was slightly out of alignment, which rippled through to all of the mirrors needing adjustment. I also found that the lens was loose in its holder, so this was tightened.

After alignment, i successfully cut and engraved a number of Permission to Make tokens, though I did notice that the bed is slightly out of level - about 2mm left to right across the whole bed.

If folks can try some tests of their own again and let me know if they are still having issues.

Also, please include @DoESLiverpool/laser-maintenance in your issue when raising them, as this automatically sends an email to the laser maintenance team which may prompt a quicker response to the issue you have raised.

**Comment by magman2112** [comment]
I’ve also removed the broken tag, as Gerald is mostly working, with just this engraving issue to resolve

**Comment by magman2112** [comment]
@dazz-ling has completed some further testing, along with a number of other users and this engraving issue is no longer apparent, so closing this issue.
