### ISSUE TITLE
Set up system to track our PAT testing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1529]
Now that we've got a PAT tester #1485, we should set up the systems to log when things are tested and then continue to do testing (there was an external company hired to do it last time, so all we've got at present are pass/fail stickers on things).

There's a log book included in the kit we bought with the tester (as well as a bunch of pass/fail/something-in-between stickers), which probably gives us the set of information that we should track.

This list is to record progress on it.  Any item with sub-items has had everything else in that room tested and it's only the sub-items remaining.

* [x] Events Room
  * [x] the doorbot
  * [x] the Geometric Lights
* [x] Kitchen
* [x] Main Room
  * [x] the doorbot
  * [x] Wooden box of test gear under the electronics workbench
* [x] Vinyl cutting and heatpress area
* [x] CNC room
  * [x] Extension on top of the CNC router
  * [x] Light on the CNC router
  * [x] Checking cases under the router and the cupboard by the router for any power tools
 * [x] Large format Epson printer
 * [x] Christmas decorations 
* [x] Laser-cutter room
* [x] Fibre arts room
* [x] Dinky
  * [x] Ronan's servers
* [x] Network closet
* [x] Snug
* [ ] Room29
  * [x] @johnmckerrell's desk
  * [ ] @ajlennon's desk (and the items under the one next to it too, as I wasn't sure if that was also your stuff Alex)
  * [x] @JackiePease's desk and the flowers
  * [ ] Check more-recently-occupied desks

**Comment by amcewen** [comment]
We discussed this in the Directors' Meeting yesterday evening, and figured this might be a reasonable approach:
* Split the space into sections
* Each section is tested every X months, gives full coverage over a Y year period
* Keep spreadsheet of everything

Seems that it's possible to get [PAT testing online](https://www.onlinepattestingcourse.co.uk/) (there might be better options, that was from a quick search), so maybe we should get a few people trained up to do it?  Anyone interested?

**Comment by amcewen** [comment]
Have been having a look at courses...
* https://www.onlinepattestingcourse.co.uk/ is free (in exchange for your email address, and they charge £30 for a certificate)
* https://www.pat-testing-training.net/course-lancashire.php is an in-person course in Preston, which is £234/person
* https://www.reed.co.uk/courses/pat-portable-appliance-testing-training/264454 is another online one, which is suspiciously 96% off but ending today, so only £10 instead of £299.

While looking, I also found [this PAT testing FAQ on the HSE website](https://www.hse.gov.uk/electricity/faq-portable-appliance-testing.htm), including this [items must be tested every year myth](https://www.hse.gov.uk/myth/july.pdf) poster :grin: 

I've done, and passed :tada:, the free one.  It took an hour or so, and I think it's best done with the PAT tester to try out as you go.

We should set up an online spreadsheet (as a start) to record what's been tested and the details of the test (or see if the free phone app available with the tester is any good) before logging much more, but I did test a couple of devices and IEC leads, which all have their pass stickers on now.

/cc @kayharvey @RussCoty

**Comment by amcewen** [comment]
@paulgeering and I have made a start on the testing now (as we've both passed the online test).  We're logging the results here:
https://docs.google.com/spreadsheets/d/1TUdTJlK5FCumf9jfq-RXyQ1-jTulLGPEBmIIyPqTHUA/edit?usp=sharing

We could do with a cloverleaf-to-IEC adapter cable so that we can test them properly with the IEC test program on the PAT tester.  So I've ordered one of [these C6 to C13 adapters](https://www.ebay.co.uk/itm/391773783794?hash=item5b378986f2:g:B~0AAOSw4KZgjATq)

There are lots of things to PAT test, so if anyone else wants to help out then give me a shout!

**Comment by amcewen** [comment]
The cloverleaf-to-IEC adapter has arrived, and I've put it with the PAT tester.

**Comment by amcewen** [comment]
I've done everything else in the `Recess` now!  :tada:  I've done the black 6-way extension cable that runs *from* the recess round to the bookcase-of-things, but none of the things plugged into it.

For recording extension leads I've taken the worst value from any of the sockets as the one for the (rather than log each one).

I fixed one extension lead that failed its visual inspection (the outer insulation wasn't held in the plug's strain relief), and I've raised #1617 for the one item that failed.

**Comment by amcewen** [comment]
Made a start on the CNC room this evening.

**Comment by amcewen** [comment]
@RussCoty has joined the testing team this evening, and we tested more of the CNC room, including fixing the vacuum cleaner which failed its visual inspection (needed the lead shortening to remove some damage).

**Comment by amcewen** [comment]
During Maker Day I chipped away at some more of this.  Did the electronics workbench, the workshop benches, and the sewing machine area.

**Comment by Knottyashcreative** [comment]
I have now also completed the free PAT testing course

**Comment by amcewen** [comment]
I've done everything in Dinky (bar the TV), and @paulgeering and I have done a few more devices in the main room and all of the snug too.

Notes of some things missed on the way round that still need testing:
* [x] TV in Dinky
* [ ] ~~Wooden box of test gear under the electronics workbench~~ (moved to main issue content)
* [ ] ~~Network closet~~ (moved to main issue content)

@paulgeering and I have tested the first Sonoff device this evening - the one on the coffee machine.  Once @paulgeering had rewired it so it didn't fail its visual inspection because the outer insulation wasn't held by the clamp in it...

We decided that the testing process for Sonoffs is:
1. For the visual inspection, ensure that:
   * the device is secured to a fixed location rather than flapping around in the breeze. 
   * there is no weight suspended just on the cables
2. Test as an extension for RPE (which should be low) and Rinsulation (which should be high) and it must fail on the polarity test (because the live connection will be disconnected).  If the polarity test passes, that will be a FAIL for the Sonoff.
3. Test as a Class II device

**Comment by amcewen** [comment]
Did most of the events room this evening.  

Haven't done:
* [ ] ~~the Geometric Lights~~ (moved to main issue content)
* [x] the PoE injector on the same wall as the lights
* [ ] ~~the doorbot~~ (moved to main issue content)
* [x] Sophia, or her related ancillaries
* [x] the extractor fan for Sheila

We need to get some new AA batteries for the PAT tester as the ones in it are getting low

**Comment by amcewen** [comment]
The batteries in the PAT tester have been replaced.

I've tested the rest of the laser-cutter-related kit in the Events Room; then @JackiePease and I fixed the laser-cutter PC #1639 and @magman2112 and I got part-way to investigating the problems with Sheila #1641.

**Comment by amcewen** [comment]
I tested everything under the Liverbird and on the Bookcase of Things this evening.  Another 24 devices, which all passed.

**Comment by amcewen** [comment]
There's been additional notes about our leakage current testing worked through as part of #1641.  From [this summary](https://github.com/DoESLiverpool/somebody-should/issues/1641#issuecomment-1029341808):
> In particular, https://www.pat-testing-training.net/articles/iet-code-of-practice-5th-edition.php which goes into the leakage limits in more detail. From that, even in the 4th edition the 0.75mA limit for leakage current is only for "handheld and portable", whereas there was a 3.5mA limit for "Class I IT, Movable, Stationary & Fixed". I think the laser-cutters would come under that latter category. In the 5th edition all of the limits have been increased to 5mA.
> 
> So from my reading of that, we're a way below the 4th edition limit even for Sophia's 2.36mA leakage (see https://github.com/DoESLiverpool/somebody-should/issues/1643) and below the 5th edition limit of 5mA for all devices.

**Comment by amcewen** [comment]
Moved on to Room29 this evening.  

Haven't done the following desks.  Wasn't sure what was on or off, so have left everything there to do sometime when each person is around.
* [ ] ~~@johnmckerrell's desk~~ (moved to main issue text)
* [ ] ~~@ajlennon's desk (and the items under the one next to it too, as I wasn't sure if that was also your stuff Alex)~~ (moved to main issue text)
* [ ] ~~@JackiePease's desk and the flowers~~ (moved to main issue text)
* [x] @MatthewCroughan's desk

Aside from the desks mentioned, there's only the devices plugged into the wall on the yard side which haven't been done.

**Comment by amcewen** [comment]
Have done all of the (newest) Dinky meeting room, apart from:
* [ ] ~~Ronan's servers~~ (moved to main issue text)

Did all the things on my desk, but not the extension leads that things are plugged into, as it'll make more sense to do all of the ones under the desks at once.

**Comment by amcewen** [comment]
Got the printers in the main room tested today.

**Comment by amcewen** [comment]
We need to write up the assorted notes for the process and turn it into a Wiki page, which also lists who you can ask to PAT test your stuff.

**Comment by amcewen** [comment]
At the Hack the Space afternoon, with some sterling help from Andy who dug out all the extension leads from under the Eastern bank of desks in the main room, we got a bunch more testing done.

The Eastern bank of desks in the main room is all done; the 3D printers in the server rack are all done; and the 3D printers by the CNC room are also all done.

**Comment by MatthewCroughan** [comment]
I'm coming back to Liverpool this week so if you find any time, I'm happy to test everything on my desk. I'll come and find you @amcewen

**Comment by amcewen** [comment]
We've tested most of the things on @MatthewCroughan's desk, apart from the UPS.  It's not 100% clear how we need to test the UPS.  Is it a class I device? a 5-way extension?  All of the above...?  Any thoughts @paulgeering, @RussCoty, @pkharvey?

Also tested all of Nalini's stuff.

**Comment by amcewen** [comment]
I've written up the (current) PAT testing process on the wiki - https://github.com/DoESLiverpool/somebody-should/wiki/PAT-Testing

**Comment by amcewen** [comment]
At today's hack-the-space I tested the new large-format printer and all the extension cables under the West bank of desks in the main room, and John's desk.

I've also tidied up the list of things-still to do and collected it all into the main issue text at the top.

Annoyingly, it seems that one of the pens I've been using to write the PAT test labels fades after 5 or  6 months, so some of the labels are now basically blank :disappointed: The info is still in the spreadsheet, so we can relabel any that we come across in that state (and/or re-test them anyway...)

**Comment by amcewen** [comment]
Got all of Ronan's servers, etc. tested this morning so Dinky is all done now :tada:

**Comment by amcewen** [comment]
Did most of the rest of the CNC room this evening.  Still need to do the extension on top of the CNC router and the light for it, and any power tools in the cases under the router (and the cupboard?)

**Comment by amcewen** [comment]
I got the rest of the things in the CNC room tested this evening.  The light failed - see #1744 - and everything else passed.

**Comment by amcewen** [comment]
Network closet done today, along with the Christmas decorations and Jackie and Ben's desks.  Moved onto our second roll of passing stickers!

**Comment by amcewen** [comment]
Made a start on the laser room today.

I haven't tested Tony, due to #1709, but did test the extension for the water chiller - as if it was an IEC lead from the plug for Tony.  It failed on polarity, as it was open circuit, but I think that's correct as it'll be turned on when Tony is.  Will double-check with @Sean-anotherone and @magman2112, and make a note on our testing for Tony if so (that we should test the IEC lead for the chiller, but expect it to fail with polarity being "open")

Got most things tested, there's still the polisher and a few things by Sheila - a chiller at least, I think.

Things found under the detritus in the laser room, given I had to tidy it quite a bit to get access to everything, included:
* A metal ruler
* A wooden metre rule
* Five focus tools for Tony
* Two USB sticks
* Somebody's access fob
* An almost new roll of masking tape
* The brush attachment for the Dyson vacuum
* A Stanley knife
* Two craft knives
* A scalpel
* A pair of safety glasses

**Comment by amcewen** [comment]
Mopped up a bunch of newly arrived kit tonight.  Didn't do any of the laser room as it was in use.

**Comment by amcewen** [comment]
@RussCoty and I finished off the Laser Room today :tada: and mopped up a bunch of other recent arrivals, including the new bench power supply and the colour laser printer.

**Comment by amcewen** [comment]
Did the stuff on @ajlennon's desk tonight, apart from the box of smart plugs.  Didn't do anything in the boxes around it, although it looks like there's a 4-way that if it's ever going to be used in the space needs to be tested first :grin: 

There seem to be a couple of other desks in Room 29 which have gained monitors, etc. since the initial list, so we'll need to test anything on those too.

**Comment by ajlennon** [comment]
I better get in and tidy ! There may be DoES 4-way sockets around?

**Comment by amcewen** [comment]
The final bit of "set up system to track our PAT testing" is how to handle re-testing devices.

I had been thinking we could use the existing spreadsheet as the seed for a database, so we could then (a) track previous test dates/results, and (b) start to build a database of what's in the space (so people could search for tools, initially, and then that could be extended to include components, etc.).

However, that's non-trivial, and we need to start re-testing things because some of the stuff was last tested in 2021; so I'm going to propose something simpler&mdash;at least for now.  We currently share a copy of the spreadsheet annually with the landlord, so we can [keep those `somewhere-safe`](https://github.com/DoESLiverpool/somewhere-safe/blob/master/PAT%20Test%20Register.xlsx) as a record, and just overwrite the data in the online version.

We have been tracking whether things are portable or fixed, as initially we thought maybe we'd have different re-testing schedules.  For now, I think it's easier to have a re-test schedule that's location-based: i.e. "let's test everything in the laser-cutter room", so I think we go with that for now.  (If anyone has better ideas, happy to revise plans)
