### ISSUE TITLE
Have a permanent desk holders tidy day - possibly by the end of June

### ISSUE THREAD

**Issue by Red-Violet** [DoESLiverpool/somebody-should#153]
As part of improving the look of the main room it would be good to find a day or if the suggestion is enough to tidy each desk to get rid of any unwanted things and to have ready anything that may need to be stored an on the new shelving so it is easier to see exactly what storage is needed. #48

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
The hotdesk room looks pretty tidy every time I've visited over the past few weeks. If something more needs doing, it would be worth clarifying and then we can handle the rest during organisers' meetings.

**Comment by DefProc** [comment]
We've tidied the hotdesks and some of the permanent desk holders have tidied there desks at various times. Unless there's a specific event or reason to keep this open, it looks complete

**Comment by DoESsean** [comment]
I think it will mutate into a more generic tidying for the entirety of DoES - particularly the workshop and Dinky, both of which get regular use but less regular scrutiny.

With Makefest coming up, and the likelihood that there will be people from outside DoES coming in to see us, it would probably be a good idea to get this sorted out by then. So we'll close this issue, and start a new one with an actual timescale and reasoning.
