### ISSUE TITLE
Dishwasher is flooding the kitchen

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1532]
The dishwasher flooded soon after the start of its program. There were about 2 buckets of water on the kitchen floor and more behind the dishwasher door when it was opened.
I removed and cleared the filter and restarted the dishwasher, but it still wasn't emptying. 
@blancmatter and I cleared the rest of the water from inside the dishwasher, but didn't feel confident to take off the base panel and look at the pump and outlet pipe.
@johnmckerrell is going to try to get a dishwasher engineer. In the meantime please wash dishes by hand (using the kettle to heat water).

**Comment by johnmckerrell** [comment]
Unfortunately the repair man I use has had car problems so looks like he won’t make it until after Christmas. It does sound to me like a broken pump, unless it was draining through the sink which was blocked with coffee grounds!

**Comment by DoESsean** [comment]
Brendan has been in today to look at the dishwasher.

Basically, he says the motor is knackered, and so is the drainage pump. The motor would cost upwards of £80 to replace, and with the number of moving parts that can go wrong, he's suggested it's probably worth just replacing the machine.

Curry's have some for under £200, so it might not be the worst idea. It would also have a door.

He can't do anything about the microwave, unfortunately, it's not his sphere of expertise.

**Comment by JackiePease** [comment]
I have ordered a new dishwasher from ao-business.com for £315 + VAT. It's a Bosch SMS25EW00G and should arrive on Monday. The plumber will plumb it in when he replaces the plumbing

**Comment by JackiePease** [comment]
New dishwasher has arrived - I asked them to leave it by the kitchen

**Comment by JackiePease** [comment]
Brett has fitted the new dishwasher temporarily while we wait for the plumber. It works fine (testing by rewashing the previously hand-washed dishes).
It doesn't need to be registered as it is for a business.
I've put the documents in the petty cash drawer.

**Comment by Markwil12** [comment]
My washer once had a leak and wasn't draining well. A technician came over and fixed the drain pump in no time. Saved me from a mountain of laundry piling up. As for dishwashers, I’ve had problems with mine not cleaning properly and leaking. Getting an expert to fix the clogged filters and spray arms made a huge difference. If you’re in Melbourne and facing similar issues, check out https://melbournedishwasherrepairs.com.au/. They’ve been a great help.
