### ISSUE TITLE
Main room door (Doorbot2) not operating right

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1533]
The door wasn't locking. I SSHed in and it seemed to have got stuck playing Jackie's audio so it didn't send the lock code. `^C` didn't fix, neither did rebooting. Not sure on a solution yet.

root@doorbot1:/home/pi# uptime
 17:23:04 up 241 days,  7:47,  2 users,  load average: 0.89, 1.10, 1.08
root@doorbot1:/home/pi# mem
bash: mem: command not found
root@doorbot1:/home/pi# free
             total       used       free     shared    buffers     cached
Mem:        444536     353660      90876      40652      34452     126280
-/+ buffers/cache:     192928     251608
Swap:       102396      26288      76108

**Comment by JackiePease** [comment]
I had reported this as 'Main Events Space' when I meant 'Main Space'. The problem resolved when I powercycled doorbot 2.
