### ISSUE TITLE
High speed cutting issues

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1535]
I noticed the following issues when using Gerald to make cuts in paper for folding:
- The cutter slows down before the last approx. 3mm of each cut, meaning that even when the corner power was very low it cut through the paper
- When the outline wasn't complete the cutter made a loud "spinning" noise, then jumped about 80mm. This was repeatable, but it stopped happening when I made the outline into 1 path
- When I tried to make folding cuts over a larger area, there was a noticeable difference in depth from one corner to the opposite edge

**Comment by plastictactics** [comment]
Sounds like 3 issues in one to me. I had the middle one recently:

When running a 'scoring' cut last week, the belt was slipping as it jumped into the 50mm diameter circles spaced around 100mm apart at speed 200, and the laser head ended up about 50mm to the right on the y axis when it returned to origin.

Worked fine at slow speeds (~30). Sean and Mike took a look a the belt - the teeth are worn in places. Could be same issue?

**Comment by JackiePease** [comment]
I was cutting circles from card yesterday at speed 150. The edges were slightly wavy.

**Comment by arthurrowland** [comment]
Migrating these issues into #1543 to try and make it easier to keep track of cutting issues. Happy to be challenged on the need to separate them, but feels like a lot of these are related to belt tension, bed levelling, beam calibration, mirror cleaning, and other shared maintenance points.
