### ISSUE TITLE
Get more carpet tape for the CNC router

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1537]
We seem to be out of carpet tape.  I've ordered three of these [48mm x 25m rolls](https://www.ebay.co.uk/itm/DOUBLE-SIDED-MULTI-PURPOSE-STRONG-ADHESIVE-TAPE-CARPET-TAPE-HEAVY-DUTY-48-x-25m/392288467617)

**Comment by DoESsean** [comment]
This has arrived, all spares are in the tape drawer.
