### ISSUE TITLE
The microwave turntable isn't rotating

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1538]
@blancmatter noticed that the turntable on the microwave isn't working. It still heats food, but obviously unevenly.

**Comment by JackiePease** [comment]
The microwave has a number of issues: it is missing an internal plastic cover, the turntable doesn't rotate, and more seriously, it didn't stop when Arthur @plastictactics opened the door yesterday.
@magman2112 who provided it a while ago agrees that it's reached end of life.
If anyone in the community has a spare microwave they'd like to donate that would be excellent, otherwise we should probably buy a new one

**Comment by JackiePease** [comment]
This microwave is £124. It's stainless steel, which I think is a good feature as it's less likely to corrode. It would be good to know other people's views (AO sell microwaves from £60):
https://ao.com/product/nnsd27hsbpq-panasonic-microwave-stainless-steel-48255-50.aspx

**Comment by ajlennon** [comment]
I've always found AO to be very good

**Comment by DoESsean** [comment]
I've ordered a microwave.

Basically, AO were having all kinds of faff with delivery times and charges, so I went to Amazon and found a Russell Hobbs for a tenner less with no delivery fees. Plus it's Amazon, so it'll be here tomorrow. Also, it's a combi, so we can cook an actual lasagne in it apparently.

https://www.amazon.co.uk/gp/product/B07FVNQQBN/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by ajlennon** [comment]
Ah! Brexit eh! Or maybe they are in the Suez?

**Comment by DoESsean** [comment]
@amcewen has suggested they're the EasyJet of electrical operators - good prices, then come the hidden fees...

**Comment by ajlennon** [comment]
Maybe. I have had calls from them about taking extra insurances out. They were very nice when I said I wasn't interested though and haven't bothered me again. I found their install and takeaway services to be good, prices good, delivery and service good. Recommended t them to a few people in fact. That's just me though. I do usually stay away from places I think are "pile em high and sell em cheap then no support". Wouldn't buy from Curry's or PC World or any of them for example.

**Comment by JackiePease** [comment]
We now have new Russell Hobbs combi microwave - thanks @doessean
I installed it and tested  the microwave function
