### ISSUE TITLE
Prints Adam seems to have blocked print head

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1539]
My print failed. On examination the filament was not all the way along the tube. When I tried to feed the filament through the hot end it appeared to be mainly blocked and I wasn't able to unblock it with cold pulls etc.

**Comment by Knottyashcreative** [comment]
> My print failed. On examination the filament was not all the way along the tube. When I tried to feed the filament through the hot end it appeared to be mainly blocked and I wasn't able to unblock it with cold pulls etc.
> 
> 

Took 3D printer apart and cleared out filament build up in the the PTFE tube (no excessive roughness), metal base and cold pulled the interior of the nozzle.  I found smooth filament flow once I had completed. Thanks to Jackie as she guided me through this dissembling process.  Jackie to now check with a test print.

**Comment by JackiePease** [comment]
This is working fine now
