### ISSUE TITLE
Organise how to improve the tidiness of the workshop

### ISSUE THREAD

**Issue by Red-Violet** [DoESLiverpool/somebody-should#154]
The workshop is a very busy space and has a lot of people come in to use various things. I would like to find a way that we can encourage people to tidy up after themselves and that everything has a space it can go back to. Needs to be discussed further, but maybe a sign and as part of importation about DoES and workshop hire?

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
I'll see if I can better organise existing storage boxes - see #151

**Comment by DefProc** [comment]
The workshop storage is definitely a separate issue. The bottom shelf in the workshop is sorely in need of a clear out, and it might be worth trying to move the worship boxes down, so more used storage is more accessible storage

**Comment by stevesparrow** [comment]
Closed, as contained within storage, move tidying and disposal new issues.

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
