### ISSUE TITLE
Felicity’s head seems blocked

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1540]
I tried to cold pull the 3D printer after following the setup procedure but Jackie and I would benefit from some guidance on how to take apart the head or clear the head ie. a demonstration or detailed tutorial. Thank you in advance

**Comment by JackiePease** [comment]
I have taken the print head apart (with advice from @amcewen), removed the excess material that was stuck inside, and replaced the PTFE coupler. The printer seems to be extruding fine now, but the filament isn't sticking to the bed. Now trying some (yellow) painters? tape as recommended at www.matterhackers.com/news/how-to-succeed-when-printing-with-petg-filament (their recommended temps are interesting). Not a total success yet - will try again tomorrow.

**Comment by JackiePease** [comment]
I've temporarily moved the printer into Room 29 and am getting better results, so I think room temperature is part of the issue.
Printing on painters tape works well, @DoESsean has ordered some more.
