### ISSUE TITLE
Gerald laser cutter is not cutting properly

### ISSUE THREAD

**Issue by pkharvey** [DoESLiverpool/somebody-should#1543]
Met Subbuteo Brian last night.  He told me that Gerald was not cutting and described it as if it were the laser.  I was not there to see it myself but I saw the cuts on an acrylic sheet.  The cuts were initially smooth, but gradually became increasingly serrated, until it eventually wouldn't cut through the material, just leaving a weak dotted line on the material.

**Comment by magman2112** [comment]
I checked the alignment on Gerald this evening and there was some misalignment in the laser head.

I will leave this issue open for now though, in case there was something else that caused the anomaly noted.

Also, please include @DoESLiverpool/laser-maintenance in the message to ensure the laser maintenance team are notified, as with this notification we typically manage to fix issues quicker.

**Comment by arthurrowland** [comment]
Although the original issue was likely resolved, the title still stands after recent events!

Jade Noon reported an issue in the covid19 repo after I had some trouble on Friday: https://github.com/DoESLiverpool/covid19/issues/111

**Comment by magman2112** [comment]
I hope to be able to call in to DoES tomorrow, so I will check the alignment then. I suspect that at least 2 of the mirrors may need adjustment, given the issue that Jade has raised.

**Comment by arthurrowland** [comment]
Brett cleaned the mirrors this morning and reports it is working well now.

**Comment by JackiePease** [comment]
Laura and Rhea were trying to cut a large piece of acrylic - Gerald still isn't cutting through properly at the top right hand edge, so it looks as though there still might be a bed levelling problem. 
Adding a broken label so people only cut at their own risk until this is resolved, as large pieces of material could be wasted.

**Comment by magman2112** [comment]
@Sean-anotherone and I spent quite a few hours on this issue on Thursday night. The situation has been improved but it still not ideal. We reached the stage of it being very late and we were tired enough that we were not being productive so we will have to revisit this issue.

We did find though that the carriage fixing screws on the left hand side were very loose, these have now been tightened, which did improve cutting significantly. We also improved the fixing of the primary mirror to give us more adjustment capability.

I will hopefully be back in on Saturday to look at this issue again.

**Comment by arthurrowland** [comment]
Thanks Mike and Sean. If I want to help out with and learn laser maintenance, should I just rock up on Thursday evenings? That happens to be my non-mcqn day based on the other side of town, so I have been reliably missing you!

**Comment by arthurrowland** [comment]
Issue summary from #1535 that may have common causes:

- Laser head jumping high speed cuts
- Inconsistent power across the bed
- Power higher on arcs than straight lines

**Comment by magman2112** [comment]
@arthurrowland, you are more than welcome to join us on a Thursday evening. I am more than happy to expand the team that can help keep the lasers in DoES in a good state.

**Comment by amcewen** [comment]
This is going to either get fixed (I hope) or any information in it will be out-of-date, once #1642 is finished.
