### ISSUE TITLE
No electric in Does

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1546]
Arrived at DoES this morning and there is no electric ie Magnetic doors open and fridge off etc. Fuse board not active (left water off as instructed). However.. Front of building... Still active and working

**Comment by willcrobinson** [comment]
@johnmckerrell has sent a message to the landlord.

**Comment by willcrobinson** [comment]
We're back up and running. Main box downstairs had tripped. West Side Sockets had tripped in our box, maybe related?

**Comment by johnmckerrell** [comment]
Thanks both. If anyone seeing this is aware of anything that might have caused this then please let us know.

**Comment by JackiePease** [comment]
Brian left a message that this happened when he switched off a portable heater in the laser cutter room at 1:30 this morning. I've removed the heater for the time being.
