### ISSUE TITLE
We need to dispose of the remaining oscilloscopes

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#155]
We originally got 6 with the intention that we would keep 2 that worked fully and spread the other 4 to the community. We still have all 6, and now a newer, 4-channel digital scope on long loan. 

How can we find and/or distribute the remaining 4 (which don't all work perfectly and were being thrown away when we got them) or has the time come that we need to bin them?

**Comment by cheapjack** [comment]
I can ask Sam Wiehl & Bob Wass from Hive who have occassionally borrowed them for music video shoots props (not turned on ar actually used artists eh?) if they want one

**Comment by amcewen** [comment]
We actually got given another 2, on top of the original 6, which is why there are still 6 despite two being taken away by DoES members :-)

I'd promised any leftovers to @Cefn for the Morecambe maker community ages ago, and have pinged him to see if he'll be at MakeFest to collect.  I wonder if Blackpool hackspace, or @p0welly at HackOldham would have any use for any?

**Comment by cheapjack** [comment]
Not heard back from bob Wass may have used wrong address; Ive just pinged Sam Wiehl see if they want one; id give them the most broken one as they may just use them as props

**Comment by amcewen** [comment]
From a discussion on twitter, @lesp would like one for Blackpool hackspace, and wants to collect at Make Fest :-)

**Comment by lesp** [comment]
Michael Rimicans from Huddersfield Raspberry Jam is interested too he's https://twitter.com/heeedt

**Comment by cefn** [comment]
God would love one! Nothing in the workshop at all like this.

**Comment by p0welly** [comment]
We'd certainly appreciate one :)

**Comment by amcewen** [comment]
Three went at Liverpool Make Fest - to @lesp and heeedt.  That left two behind, one each for @p0welly and @cefn.  Now we just need to work out how to get them to you...  I'm thinking that we should have UK Maker Belt Association symposiums in Lancaster/Morecambe and Oldham sometime?

**Comment by lesp** [comment]
Adrian/DoES

Thanks very much for them, I will be talking to Preston Hackspace and
giving a spare to them.
Preston Hackspace are starting up again with a meeting in mid July to
discuss arrangements and the two lads behind it are very keen to make it
happen.

Best
Les

On Mon, Jun 29, 2015 at 9:55 AM, Adrian McEwen <notifications@github.com>
wrote:

> Three went at Liverpool Make Fest - to @lesp <https://github.com/lesp>
> and heeedt. That left two behind, one each for @p0welly
> <https://github.com/p0welly> and @cefn <https://github.com/cefn>. Now we
> just need to work out how to get them to you... I'm thinking that we should
> have UK Maker Belt Association symposiums in Lancaster/Morecambe and Oldham
> sometime?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DoESLiverpool/somebody-should/issues/155#issuecomment-116534948>
> .
>



-- 
Les Pounder
http://bigl.es/
@biglesp on Twitter <https://twitter.com/biglesp>

**Comment by newbreed65** [comment]
I'm going to be in Liverpool tomorrow from about 2pm.  Would I be able to grab the one for @p0welly?

**Comment by amcewen** [comment]
Probably... not sure what I'm up to tomorrow, but if I'm around then yes, definitely.  I'll DM you my mobile number - text me in the morning and I'll let you know

**Comment by amcewen** [comment]
And then there was one.  Just the one to deliver to @cefn now.

**Comment by p0welly** [comment]
Thanks guys, much appreciated!

On Wed, Sep 2, 2015 at 4:25 PM, Adrian McEwen <notifications@github.com>
wrote:

> And then there was one. Just the one to deliver to @cefn
> <https://github.com/cefn> now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DoESLiverpool/somebody-should/issues/155#issuecomment-137130927>
> .
>



-- 

Kind regards,


*Andy Powell* | Internet Consultant
STEM Ambassador | Code Club Mentor
Adwords Certified

Mobile. +44 7904 765 331 | Email. andy@caffeinatedprojects.com
Twitter. @p0welly <http://www.twitter.com/p0welly> | Skype. p0welly


*Caffeinated Projects Ltd *| T. +44 161 826 1827 | F. +44 161 826 1827
c/o Hack Oldham, 4 Hardcastle Street,  Oldham, OL1 1SU

www.caffeinatedprojects.com

All prices exclude VAT at the prevailing rate.

**Comment by amcewen** [comment]
@cefn visited yesterday, and took his oscilloscope home with him.  Oscilloscope distribution mission complete!
