### ISSUE TITLE
Ender3 seems to not be functioning?

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1552]
It seems to power up - there's an assortment of whirring and the screen starts showing some temperatures, etc.

However, I can't connect to Octoprint - I've tried the URL and IP address printed on the sticker on the printer, and found an updated IP address (10.0.50.3) listed in the networking info, but can't connect to any of those.  Looking at the network management software it seems that it was last connected to the network on 28/10/2020.

I can't see where the Pi is, so has it been removed by someone?

The scrollwheel next to the display makes a %age value on the display change, but doesn't seem to do anything else...

There's a USB lead coming out from underneath the printer, which isn't connected to anything (was that plugged into the Pi originally?).  If I plug it into my laptop and open a serial monitor I get a bunch of Marlin output, but it's not clear what I should run to talk to it (other than Octopi, but I'd rather not install that on my laptop...)

Does anyone know what it /should/ do, or is it non-functional without the Pi running Octoprint?

**Comment by MatthewCroughan** [comment]
> Does anyone know what it /should/ do, or is it non-functional without the Pi running Octoprint?

It only accepts print commands over USB. Configuring the Marlin firmware to support an SD card takes up too much space on the flash, meaning the code that implements auto bed leveling via the installed probe cannot be used, so it was sacrificed.

This effectively means that an Octoprint instance has to be ran to submit GCODE via USB, you could do this on your laptop via Docker and passing through USB via `/dev` This is a stateless command so anything you do inside will be lost:

`docker run --privileged -v /dev:/dev -e ENABLE_MJPG_STREAMER=false -p 80:80 octoprint/octoprint`

Or you could [install OctoPi on a Pi](https://octoprint.org/download/)

The Marlin firmware configurations for all of the printers that have passed through DoES can be found here:
https://github.com/DoESLiverpool/marlinconfigs/

Related Issues: 
https://github.com/DoESLiverpool/somebody-should/issues/1394
https://github.com/DoESLiverpool/somebody-should/issues/1396

**Comment by amcewen** [comment]
Thanks for that.  Good to know it needs the Pi connected.  I've made a start on a [wiki page for it](https://github.com/DoESLiverpool/somebody-should/wiki/Alex's-Ender)

**Comment by ajlennon** [comment]
I've got the Pi here. It wasn't booting. I've reinstalled from my Balena Docker setup here -

https://github.com/DynamicDevices/octobalena

I'll bring it in and connect it up, hopefully tomorrow if I get a chance, and see if we can get a boaty going on the printer

**Comment by ajlennon** [comment]
What's the host name supposed to be for this one?

**Comment by MatthewCroughan** [comment]
@ajlennon I last had it as `alex-ender3.local`.

**Comment by ajlennon** [comment]
OK so I've been in and got the Ender 3 up and running again. It's printing a 3D Boaty here and seems pretty happy

![image](https://user-images.githubusercontent.com/1537834/107992255-38196080-6fd0-11eb-89ea-7f4367ee5fea.png)

Couple of things:

- It's picked up 10.0.50.3 which is different from the IP on the label
- It's advertising as 'alex-ender3' on mDNS and can be pinged
- The Raspberry Pi is running my current Octobalena containers as above (https://github.com/DynamicDevices/octobalena)
- I think that the wall wart PSU went and then the RPi was booting over and browning out and booting, and I think over time that might have knackered the SD Card. Anyway I reprovisioned everything from scratch

I levelled the bed but there's something wrong with the bed levelling @MatthewCroughan both here and on the CR10S I have at home. The levelling command doesn't work (issues G29 which doesn't work). G29 P1 seems to work a bit but only does about 9 or 10 out of 25 points on the Ender 3.

That said the boaty is printing. The nozzle is slightly too close to the bed so the first layer is only going down partially but it seems to be working for now.

**Comment by ajlennon** [comment]
(oh and I left a reel of yellow PLA of mine in there - you might as well use that - the red stuff that was in seemed brittle)

**Comment by ajlennon** [comment]
Oh also there is a login and password. The user name is `doesuser` and the password is the WiFI one at DoES

**Comment by amcewen** [comment]
The Benchy print had under-extruded a bit, and seemed to be missing the roof from the cabin.  I'm doing a test print, sliced with the default Ender 3 settings in Cura: that had the same first layer being too close issue (as you'd expect) and was under-extruding as you can see here:

![image](https://user-images.githubusercontent.com/108468/108079973-4bc3d600-7067-11eb-9679-a6e8c5508059.png)

I've pushed the extruder temp up to 206&deg;C (from 200&deg;C) to see if that improves matters.  The bridging on that seems really nice though.

**Comment by amcewen** [comment]
The temperature change didn't make any difference, so needs more tuning.

I've swapped the filament out for some PETG, as that's what I want to be printing in eventually anyway.  I also added another bulldog clip to hold the bed on, as I noticed it was shifting a bit during the print - maybe that was why the Benchy roof failed?

Running with the default Cura settings for PETG as a starting point - seems to be okay so far, but we're only a few mm up so far :-)

**Comment by amcewen** [comment]
The initial PETG print also under-extruded (extruder temp 240&deg;C, bed temp 70&deg;C).

I tried a Benchy in PETG, using the default Cura "extra fine" setttings (0.12mm layer height).  That seemed much better (I aborted it before it had finished as a result):

![DSC_0010](https://user-images.githubusercontent.com/108468/108373318-aee47280-71f7-11eb-91b7-64917ff67fda.JPG)

And now I'm printing one of the parts that we want downstairs, so will see how that gets on.  So I think we'd still need to tune things for thicker layer heights, but it works on the finer ones.

**Comment by ajlennon** [comment]
I wonder why it's under extruding - @MatthewCroughan this couldn't be to do with the replacement metal extruder you added could it? Maybe it has different extrusion parameters from the default one?

**Comment by ajlennon** [comment]
How did those prints work out @amcewen ?

**Comment by amcewen** [comment]
The one I'd left printing on Thursday came unstuck from the bed, but the section that did print was still under-extruding a bit.  I kicked it off again yesterday afternoon after some consultation with @Robotorium, and dialled the bed temp up to 75&deg;C to try to help with the coming-unstuck, and the extruder temp to 246&deg;C to see if that helps with the under-extrusion.

Will report back when I'm next in (which will be Tuesday)

**Comment by ajlennon** [comment]
Hummm - this is very interesting!

https://letsprint3d.net/how-to-calibrate-the-extruder-steps-ender-3-5-cr-10/

**Comment by JackiePease** [comment]
![IMG_20210220_115151](https://user-images.githubusercontent.com/12802256/108594480-2f2ee300-7372-11eb-9c2c-6cb46329dbf0.jpg)

**Comment by ajlennon** [comment]
Yikes! Some dialling in to do then!

**Comment by ajlennon** [comment]
Seimon has my other Ender 3. I wonder if he's seen issues

**Comment by seimonw** [comment]
Um, I didn't stray too far from the default petg settings on the slicer program. I experimented a little with the temperatures, too low and the layers didn't stick together well but the bridging was better. I went for higher temps in the end, which was ok as I didn't need any fine detail bits. I haven't had any under extrude issues. Let me know if my settings would be useful, I'll dig them out.

**Comment by amcewen** [comment]
@seimonw That's good to know.  I'm similarly not straying too far yet.

That mass of spaghetti isn't great, but looks like it came unstuck from the bed.  The bit that did print was much more solid, so pushing the temp up to 246&deg;C seems to have improved the under-extruding.  I'm printing a tall thin test print to see if it's the height that's causing the problems with it coming unstuck, or just the amount of time it's running.  I guess it could also be temperature-related, if it's getting too cold overnight...

**Comment by ajlennon** [comment]
>so pushing the temp up to 246°C

What's it getting to? I thought it maxed out at 235 C?

**Comment by amcewen** [comment]
@ajlennon it seems fine at 246&deg;C.  

The first tall test I did came unstuck a few cm in, so it doesn't seem height-related (beyond a taller print taking longer and so having more opportunity to come unstuck).

@JackiePease suggested trying blue painters tape, as we use that for PETG on the Ultimakers.  I wasn't sure about the bed-levelling process if I made the bed thicker (effectively), and the first layer was going down *very* thinly, as noted by @ajlennon initially:
> That said the boaty is printing. The nozzle is slightly too close to the bed so the first layer is only going down partially but it seems to be working for now.

So I set the first layer thickness to 0.3mm in Cura.  That seems to have done the trick for getting things to stick to the base.  This is my test print:

![DSC_0015](https://user-images.githubusercontent.com/108468/109323178-14191300-784b-11eb-91c0-0884bd994b4e.JPG)

Since then I've also completed a print of the part I was originally after.  However, I'm not sure I've got the under-extrusion sorted - it still seemed fairly brittle.  Haven't had chance to try any other settings yet.

**Comment by amcewen** [comment]
Since my last report I've been running prints at 30mm/s speed, which takes a lot longer, but is resulting in prints that succeed and don't seem to have any under-extrusion.

Given that it seems to be a case of working out good settings for it, I've written up [my PETG discoveries on the wiki](https://github.com/DoESLiverpool/somebody-should/wiki/Alex's-Ender#hints--tips) and think we can expand that over time.
