### ISSUE TITLE
Water leak from upstairs in the kitchen.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1553]
Whilst working on installing the new water heater in the kitchen, I noticed that water dripped on my head from upstairs. There also appear to be some damp patches on the ceiling.

The main leak is landing on top of the new water heater. Whilst this is unlikely to damage the water heater, it should ideally be fixed sooner rather than later.

This needs to be reported to Jason methinks.

**Comment by johnmckerrell** [comment]
Thinking about it there's supposed to be a cherry picker coming soon so it might be known already but I'll make sure Jason knows.

**Comment by johnmckerrell** [comment]
I've mentioned it (as I think Mike will see on WhatsApp) and they're not sure of cause, especially given it hasn't rained recently. We've been asked to log times that it happens in the future.

**Comment by amcewen** [comment]
This was fixed a while back and we haven't seen any recurrence of it of late.
