### ISSUE TITLE
Doorbot not working

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1555]
I noticed when I came in this morning that the door was unlocked, and then forgot about it until Adrian had to ring the doorbell to get in as his fob wasn't releasing the lock. Because it wasn't locked in the first place.

We've attempted to reboot the doorbot and maglock, with no joy, and Adrian has had a fiddle in the box that should provide it with power to no avail. He's suggested that we might need to contact Tam to figure out what is wrong. I think @johnmckerrell has his info?

**Comment by amcewen** [comment]
There's a small white box for the door system (inside the larger box which has the Pi in it) - I popped the cover off the end of that and confirmed with a meter that it's getting mains power.  The other end, which has outputs for the Pi and the maglock, etc. isn't providing any power to either of those.

I wonder if we could try to run it off the battery connection?  If that works we could temporarily power it from a 12V supply...

**Comment by amcewen** [comment]
I phoned Tam (who fitted them) and he called out this afternoon and replaced the power supply.  All is up and running again now.
