### ISSUE TITLE
Organise 10th anniversary celebrations 🎉 

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1556]
It's hard to know what we will be able to do but we have to celebrate our 10th anniversary somehow! Ideas welcome.

**Comment by DoESsean** [comment]
Looks like we'll be allowed an actual party. Possibly a shindig. Potentially even a full blown hootenanny.

**Comment by Robotorium** [comment]
All right, but I draw the line at a hoedown.

Op di 23 feb. 2021 09:36 schreef Seán Gleeson <notifications@github.com>:

**Comment by JackiePease** [comment]
We've still got the Xmas wine from Jason, and a bottle in the fridge someone donated in return for visors ...

________________________________

**Comment by rah2501** [comment]
> Looks like we'll be allowed an actual party. Possibly a shindig. Potentially even a full blown hootenanny.

If it is wished, I can bring a decent Hi-Fi system for music.  I have a second system for just such purposes :-)

**Comment by amcewen** [comment]
We had an actual party!  Go us!  And we managed it just before it was our 11th birthday...
