### ISSUE TITLE
New Big Laser

### ISSUE THREAD

**Issue by BrettNewnes** [DoESLiverpool/somebody-should#1558]
The right hand strut that keeps the lid propped open was jammed this morning. I have removed it and it can now be opened. Lid should not be left open unsupported on one strut as it may cause further damage or fall.

No obvious signs of damage to removed strut, replacement likely needed. Closed strut is 30cm long closed and 50cm long eye to eye when open.

Operation of machine is not affected.

Thanks

**Comment by Sean-anotherone** [comment]
/
Tagged with shopping but it is **ESSENTIAL** that someone checks the preload on the existing struts before ordering - I have **guessed** at 100N based on an estimate of the weight of the lid when compared to the 350N ones on my car.

Asuming the load is correct, it's the extended length that matters, so the 500mm ones.

https://www.ebay.co.uk/itm/2X-UNIVERSAL-GAS-STRUTS-SPRINGS-200MM-TO-500MM-BOOT-BONNET-MULTI-PURPOSE-100N/184402326337

**Comment by BrettNewnes** [comment]
Hello

I will be in the workshop tomorrow morning, will check and post the specs.

Cheers

**Comment by magman2112** [comment]
Beat you to it Brett, I am in DoES now.

The strut is a 650N one, with an 8mm shaft and an extended length of 480mm. Compressed length is a bit more difficult, but 300mm appears to be the fully compressed on the existing strut, but I suspect the strut isn’t fully compressed in it’s current application.

The current strut has 6mm threaded ends, which accepts the clips for the ball joints on the frame.

**Comment by DoESsean** [comment]
So does that mean the one linked to on eBay is or isn't right? Remember I'm totally clueless.

**Comment by ajlennon** [comment]
Is it helpful to have a new wiki page LaserCutterLightBurn in the same vein as the others?

![image](https://user-images.githubusercontent.com/1537834/120192498-240e0d80-c213-11eb-913a-e93b12bd0906.png)

**Comment by JackiePease** [comment]
Any further specification info for the strut @Sean-anotherone ?

**Comment by magman2112** [comment]
OK, I've done a bit more digging and took a few more measurements, so here goes with the details.

The currently working gas strut is a 650N force unit with a length of 450mm. The faulty unit doesn't have any labeling but is 600mm in length but apparently uses the wrong couplings for linking to the lid.

After taking a few measurements, I believe we should be using a 500mm length strut, as this will position the lid better for when we later fit the video camera. I have found a UK based supplier which has good prices, at the following link

https://www.strutsdepot.com/product/fixed-force/

We need the following specification to be ordered

Force - 650N
Length - 500mm
Tube End Fitting - Ball Socket
Rod End Fitting - Ball Socket

With this specification they work out at £15.90 each and shipping is free. I recommend that we buy two of these units, as the last one that is working at present is starting to slip, so a total of £31.90.

**Comment by JackiePease** [comment]
I have ordered these

**Comment by JackiePease** [comment]
Struts have arrived - they're on Sean's desk

**Comment by magman2112** [comment]
@Sean-anotherone fitted the new struts on Maker Night, so this issue can now be closed.
