### ISSUE TITLE
Fixing up Creality CR-10S - seems like a hot end problem

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1559]
I took the Creality CR-10S home to try to get it all sorted out printing well.

It was all going well but I have run into problems. Been trying to fix but I am not managing it.

The key problem seems to be the filament stops printing through the head and I am not sure why.

Adrian's #1552 has prompted me to ask if somebody can help me look at this?

WIll bring it into DoES this afternoon!

**Comment by ajlennon** [comment]
ok so "this afternoon" took a bit longer than expected. I brought it in set it up again, levelled the bed and set the BL-Sensor Z-offset.

The first print I did of a little test cube was good.

However then it went back to its behaviour of not extruding the filament properly. I've tried replacing lots of things like the boden tube and that. When I push filament through the hot end directly it looks good. So I am at a bit of a loss.

![image](https://user-images.githubusercontent.com/1537834/113698361-4d576500-96cc-11eb-82b3-cf3546baa6dd.png)

Also there is a fan on the side that is working but the fan on the front doesn't seem to be doing anything

![image](https://user-images.githubusercontent.com/1537834/113698948-e4242180-96cc-11eb-8288-a0859b396953.png)

The hot end bit seems OK from what I can tell, which isn't a lot

![image](https://user-images.githubusercontent.com/1537834/113699027-f8681e80-96cc-11eb-9b13-02d2dcc0e994.png)

And it ends up basically just printing air

![image](https://user-images.githubusercontent.com/1537834/113699061-01f18680-96cd-11eb-8ef5-ab1fb673b1af.png)

Can anybody who knows what they are doing take a look with me? @amcewen @Sean-anotherone @magman2112 ?

**Comment by Sean-anotherone** [comment]
Have you tried a hot end preloaded mod?  I needed to do this on my printer after replacing hot end with very similar one, works great now.  My issue was related to mushrooming inside the cooler block, which jams the filament, so the extruded grinds it and stops extending.  Mod was easy, but does require a 25mm piece of really good quality teflon Bowden tube, cheap stuff dies not work.  I also found that there is more difference than I expected between sizes (internal)of different Bowden tubes.
Sean

Sent from Yahoo Mail on Android 
 
  On Tue, 6 Apr 2021 at 11:42, Alex ***@***.***> wrote:   


ok so "this afternoon" took a bit longer than expected. I brought it in set it up again, levelled the bed and set the BL-Sensor Z-offset.

The first print I did of a little test cube was good.

However then it went back to its behaviour of not extruding the filament properly. I've tried replacing lots of things like the boden tube and that. When I push filament through the hot end directly it looks good. So I am at a bit of a loss.



Also there is a fan on the side that is working but the fan on the front doesn't seem to be doing anything



The hot end bit seems OK from what I can tell, which isn't a lot



And it ends up basically just printing air



Can anybody who knows what they are doing take a look with me? @amcewen @Sean-anotherone @magman2112 ?

**Comment by ajlennon** [comment]
Thanks! 

No - this is news to me. That seems to relate to that picture of the filament?

Where would I get the right bit of teflon bowden tube Sean?

**Comment by Sean-anotherone** [comment]
I have some kicking about somewhere, will find it and bring on Thursday.  In short, you push it in as far as it will go, then unscrew fitting and cut the tube.  You then fit a washer under the tube fitting and retighten, so it pre-loads the short piece tight against the nozzle, then push the tube in normally - the top of the extruder is cold, so never causes any issues.
Does this make sense? :







    On Tuesday, 6 April 2021, 11:55:53 BST, Alex Lennon ***@***.***> wrote:  
 
 


Thanks!

No - this is news to me. That seems to relate to that picture of the filament?

Where would I get the right bit of teflon bowden tube Sean?

**Comment by Sean-anotherone** [comment]
Here's a video describing - a 10 min video for a 2 min description, but I cannot find the one I used when I did this mod myself.
Simple HOTEND FIX for Creality Ender 3, CR-10


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Simple HOTEND FIX for Creality Ender 3, CR-10


 |

 |

 |




Sean




    On Tuesday, 6 April 2021, 11:55:53 BST, Alex Lennon ***@***.***> wrote:  
 
 


Thanks!

No - this is news to me. That seems to relate to that picture of the filament?

Where would I get the right bit of teflon bowden tube Sean?

**Comment by ajlennon** [comment]
Hiya @Sean-anotherone - gonna try to sort this at the weekend I think. Did  you mention a special kind of bowden tubing that can take the heat of the hot end? Were you able to pop in a piece or could  you give me a link to try to get some? Thanks !!!

**Comment by Sean-anotherone** [comment]
It's not any special type, just a decent quality teflon/ptfe one.  There will surely be an office of original creality tubing kicking about somewhere?
The "knack" is to ensure that with the coupler tight the short internal piece is in firm compression, but not so much it buckles.  About 1/2mm worked for me, have had no issues since, but I did make the spacer piece on my lathe rather than use washer(s).
Sean


    On Friday, 14 May 2021, 15:10:35 BST, Alex Lennon ***@***.***> wrote:  
 
 


Hiya @Sean-anotherone - gonna try to sort this at the weekend I think. Did you mention a special kind of bowden tubing that can take the heat of the hot end? Were you able to pop in a piece or could you give me a link to try to get some? Thanks !!!

**Comment by ajlennon** [comment]
(We're still working on this - not dead :) )

**Comment by amcewen** [comment]
This printer isn't in DoES any more, so I'm going to close this.
