### ISSUE TITLE
Discard/sell the myriad plastic component trays "stored" in the workshop

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#156]
As far as I'm aware the two(?) boxes of clear plastic component trays we got a load of stock in from NOC are still unused since the components were sorted, and don't fit in any storage system we have. 

Is it time for us to dispose/sell these?

**Comment by DoESsean** [comment]
If we want to sell stuff, I can put them on ebay. Does DoES have an ebay account actually?

**Comment by amcewen** [comment]
It does.  Don't think we've ever sold anything through it (it was originally set up to try selling Bubblino, WhereDial, etc. but we didn't get that far).

**Comment by DoESsean** [comment]
I could do that too, if you and John wanted to ramp up production on them.

**Comment by shrkey** [comment]
Do you still have them? How big are they / the drawers? I need something for Lego parts storage, so if the drawers are big enough they might work?

**Comment by amcewen** [comment]
We've still got a load.  They're in the Walker's crisp boxes on the woodwork bench.  Have a look next time you're in, and take as many as you want.

**Comment by shrkey** [comment]
The wider ones may well be useful - I'll grab them when I bring a bag big enough in.

**Comment by amcewen** [comment]
During the tidy-up that prompted issue #296 we donated these all to the shed club downstairs :-)
