### ISSUE TITLE
Write Instructions for Laser Cutter Tony

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1560]
Now that Tony is working to a good standard, we need user instructions written for the Wiki site and likely some training guidance as well (User operation is so significantly different, I suspect most aspects of training will need to be updated).

ideally, the user instructions should be written by someone other than @Sean-anotherone and I, as we are likely to be too familiar with the operation of Tony and possibly bypass some of the peculiarities by our existing knowledge. It is these peculiarities that need to be captured in particular.

As with the other lasers, there are two main threads for the documentation, operation of the physical laser cutter and the software operation. 

The laser operation aspects should include the power on routine, safety and basic operations, such as focusing the laser for different material thicknesses and the bed size limits. This should also pick up the material safety aspects common to all the lasers.

The software aspect is all new, as we have not used Lightburn on our laser cutters before. Luckily, there are a number of useful training videos on YouTube that we can likely crib off, as well as to include links to them in our documentation. 

I expect that whoever gets involved in the documentation will have questions for Sean and I, as well as possible machine improvement suggestions, which we are happy to help with.

So looking for some volunteers then.

 @DoESLiverpool/laser-maintenance

**Comment by JackiePease** [comment]
I spoke to @seananotherone this week - thought it might work better if one of you wrote the initial notes, and then someone tried to follow them, but also happy if someone else wants to do themOn 14 Mar 2021 20:38, Mike Gorman ***@***.***> wrote:
Now that Tony is working to a good standard, we need user instructions written for the Wiki site and likely some training guidance as well (User operation is so significantly different, I suspect most aspects of training will need to be updated).
ideally, the user instructions should be written by someone other than @Sean-anotherone and I, as we are likely to be too familiar with the operation of Tony and possibly bypass some of the peculiarities by our existing knowledge. It is these peculiarities that need to be captured in particular.
As with the other lasers, there are two main threads for the documentation, operation of the physical laser cutter and the software operation.
The laser operation aspects should include the power on routine, safety and basic operations, such as focusing the laser for different material thicknesses and the bed size limits. This should also pick up the material safety aspects common to all the lasers.
The software aspect is all new, as we have not used Lightburn on our laser cutters before. Luckily, there are a number of useful training videos on YouTube that we can likely crib off, as well as to include links to them in our documentation.
I expect that whoever gets involved in the documentation will have questions for Sean and I, as well as possible machine improvement suggestions, which we are happy to help with.
So looking for some volunteers then.
@DoESLiverpool/laser-maintenance

**Comment by DuncReid** [comment]
Having had the original laser induction - but never having the opportunity to make use of it before lockdown hit - I'd be happy to act as guinea pig to road test/sanity check a set of initial instructions and see if it makes sense.

**Comment by JackiePease** [comment]
@DuncReid will get back to you - Rob should be updating the Wiki in the next couple of days

**Comment by JackiePease** [comment]
I have updated the Wiki with Rob's instructions. @DuncReid you're welcome to come in any time and try them out!
