### ISSUE TITLE
Internal door sensor fault

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1561]
This morning Paul & I tried to access the building but internal door lock sensor was not responding . All other senses ok- Temporary work around : use fob on external fob sensor to open internal door.

**Comment by johnmckerrell** [comment]
I SSHed into the Pi just now, all looked fine with the last visit being around 22:15 on the 14th. I rebooted but apparently that hasn't helped. Apparently the red light shows up in the reader but the scan isn't showing on the Pi.

**Comment by JackiePease** [comment]
I have re-seated the Dupont connectors (see #1420). The lock now releases.
