### ISSUE TITLE
Get more big black bin bags

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1562]
We're onto our last roll of black bin bags, but they're also only 90L and so not really big enough for the black bins.

From @johnmckerrell's extensive research in #552:
> Aldi/alio 100L, 920mm length by 825mm width are just right for width, not sure about depth but seems ok. Interestingly I notice someone managed to get some other bin bags to fit but I think they just stretched the neck on some of the previous ones I've experimented with!

So if anyone is passing Aldi (or has suggestions for other sources of super-big and sturdy bags)...

**Comment by MatthewCroughan** [comment]
Some more BBBBs, (Big Black Bin Bags). _The alliteration potential is too great._

**Comment by JackiePease** [comment]
@johnmckerrell could you update this issue with where you bought the new bin bags?

**Comment by johnmckerrell** [comment]
Last lot were from Asda. 

--

**Comment by johnmckerrell** [comment]
I've updated #552 as the canonical issue 🙄 but the current best option is  Asda 20 Large Strong Bin Bags - 100 litre drawstring.

I bought two rolls the other day so will close this issue now.
