### ISSUE TITLE
Heat press thermostat faulty

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1566]
The timer and heat setting functions are not working. I advise not to use until repaired.

**Comment by magman2112** [comment]
@Sean-anotherone has identified a faulty relay within the heat press (It let out some magic smoke whilst testing).

It appears that this has been an issue with this heat press before (#369), so the relay that has been identified for this issue needs to be ordered again. As this is a re-occurrence of a previous fault, I would suggest getting a 2nd relay as a spare, to reduce downtime in the future (the spare can be stored within the machine, so it can be found in the future).

![7D485EE7-76BD-4F26-B69D-E318C7347A98](https://user-images.githubusercontent.com/37077154/117354417-32ce0280-aea9-11eb-8242-efc6a340cba8.jpeg)

**Comment by magman2112** [comment]
I was looking into an alternate relay modification for this press, as there is space inside the unit to accommodate a larger relay. I had some octal base relays at home that I was planning to use, but unfortunately these have a 24V DC coil, so won’t work for this application.

So it is back to using the original relay from RS then, though I still recommend buying two, so we have a spare on hand.

**Comment by amcewen** [comment]
I've ordered two relays.  They're on back order but only till the 18th.

**Comment by amcewen** [comment]
The relays have arrived.  They're in the RS envelope on the heat press.

**Comment by magman2112** [comment]
The new relay was installed by @Sean-anotherone last Thursday and this machine is back in operation now. The spare relay has been taped inside the machine for future use.
