### ISSUE TITLE
Consider something like a scholarship scheme for free access

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1568]
We've been discussing in the Directors meetings recently about offering some scheme whereby we would give some free access to one or two people to hopefully kick-start a person's business or career. Some of the thinking for this has come from the idea of "technician in residence" which we had previously, and of course "artist in residence" which would be the more established version. This would be a different concept as we wouldn't really be asking anything of the person (beyond perhaps a bit of social media action!)

Given that DoES doesn't really have many resources to manage things like this we're thinking that it would be simplest to avoid "means testing" and instead simply ask that people only apply if they need to, and then rely on a random selection. This might be considered laziness but then we are mostly volunteer run!

How many slots we would offer is a good question. One idea might be one permanent desk and one workshop space. What we're hoping here is that the person will be able to come in and use the space on a regular basis so flexidesk probably doesn't make much sense, nor does "giving away" a bunch of hot desk days (although please argue otherwise). We might consider offering more places for the first batch, perhaps as a way to get more people in post-COVID, or maybe it makes more sense to just start with one and see how things go.

In theory there should be no "cost" to DoES as it's mostly aimed at people who would like to use the space but can't afford to. In theory someone with an existing membership might apply and we would be down their contribution but as it would be for a limited period we should be able to cope.

I would expect that you could only use the scheme once, or perhaps once per some fixed period like 5 years (of course you could apply many times but once accepted couldn't apply again).

Duration of the access would need to be long enough that someone could make a good start at something new, without being so long that it restricts access for others to the scheme, so I would imagine 3-6 months. If we offered more than one slot perhaps they could overlap, so 6 months total each but they're offset by 3 months.

The hope is that we could launch this as part of our 10 year anniversary celebrations in the summer.

We wouldn't want to do this without the community's blessing. Perhaps people wouldn't like the idea of giving freebies away, especially as many people have very generously continued paying even when they haven't been able to come in much.

One of the benefits to DoES and the community would be that more people in the space makes it feel more lively. Even pre-pandemic the space could be very quiet during the day meaning people coming to see the space would think nobody used it. It could also make for a good promotional tool, especially around the 10 year anniversary and post-COVID re-opening.

There could even be the potential for "someone" (most likely a business, or just a generous benefactor) to pay to cover DoES's "costs" for a scholarship?

I'll leave it at that for now and would welcome any comments! Note that these are all just ideas at this point, if you have suggestions or criticisms we'd love to hear them.

Subtasks that need doing:
 * [ ] Decide on a name (Is Scholarship right or would something else suit better?)
 * [ ] Prepare blog posts and other marketing materials
 * [ ] Prepare Google Form

**Comment by Robotorium** [comment]
I love this a lot, and I'd be happy to help if needed.

Op di 11 mei 2021 14:23 schreef John McKerrell ***@***.***>:

**Comment by ajlennon** [comment]
I think in general that's an absolutely excellent idea. It somewhat intersects with something I have been thinking about during covid.

There is a "Kickstart" scheme that helps people on UCI get a 6 month job placement to get them on the ladder for work.

Small business goes through a "gateway" company to offer a placement and the employee's wages are covered by the scheme. Depending on the gateway that is chosen there may be a small additional sum available to the employer to cover some costs - I would have to investigate.

I view this as "my business offering free training and giving something to the local community" as opposed to "my business getting free labour".

I have been thinking of asking DoES if it would be possible to offer a free or reduced rate desk to such an employee. (I think the grant is about £1500 which it might be possible to use to cover the cost of a desk, but I suspect I'll have to get them a laptop and such out of that, and the gateway agencies are tending to take a lot or all of that grant anyway...)

Would be interested to hear feedback on the idea.

Scheme is https://www.gov.uk/government/collections/kickstart-scheme

**Comment by DuncReid** [comment]
I like the idea, I think it fits in well with the ethos of DoES and having an extra 'body' regularly in & around the place is a good thing (covid concerns apart). I popped in the other day and the usual 'buzz' was definitely missing but that's understandable as so many of us have had to change how, where & when we work.

We need to be careful that we open it as a possibility to all disciplines, not just the electro-geeks & code-heads but the artists, the printers, the weavers and writers too.

Having more people using the place as a base does mean more visitors, more exposure and all the good stuff that we need as we move towards a post-Covid existence so yeah, I think it'd work well and I'm more than happy to support the concept.

In terms of numbers, I'm not clear on how many perm spaces we have now that some spaces have been blocked off - and I suspect social distancing is here to stay - but perhaps one perm desk and a couple of workshop memberships (one tech, one artist/creative? Although there's often overlap) as a starting point.

**Comment by ajlennon** [comment]
fwiw I spotted the FSB are a gateway too - 

https://www.fsb.org.uk/campaign/kickstart-scheme.html

**Comment by ajlennon** [comment]
>We need to be careful that we open it as a possibility to all disciplines, not just the electro-geeks & code-heads but the artists, the printers, the weavers and writers too.

@DuncReid  Not to tangent off (there must be other issues about this) but we talk about this from time to time and it would be great to be able to have a bit more DoES marketing that emphasises DoES is not just about "electro-geeks" and "code-heads" as I think that is still the wider perception.

**Comment by johnmckerrell** [comment]
We're intending to go ahead with this, I've added some subtasks that will need doing. We will initially offer one workshop space & 1 permanent desk space for 6 months and see how it goes. If it goes well we would hope to introduce another two spaces after 3 months. That way we would eventually have 4 people under this program with a rotation every 3 months. This gives us 3 months to decide if there's any major problems before we need to agree to a second round. Aim is to launch it at the end of July, have applications open for a month and start the program at the beginning of October, giving a month from the close of applications for us to pick someone, inform them, and for them to do any preparation they might need.

**Comment by johnmckerrell** [comment]
Still thinking of names, DoES Open Desk Plan was suggested. Desk is a bit specific as we're giving a workshop membership too so maybe DoES Open or Free Membership program. That's almost a bit basic though as it doesn't suggest why we're doing it or why someone would apply. Kick-start or Boost might be other words as we're looking to give people a push to set themselves up in business. @JackiePease and I are liking the word Boost at the moment, should maybe check if it would overlap with anything else.

**Comment by amcewen** [comment]
Kickstart is going to be confusing with the apprenticeship scheme running more widely at the moment, so probably worth avoiding.  Boost sounds good to me.

**Comment by johnmckerrell** [comment]
We've knocked up this blog post/press release. Comments welcome and we'll launch it this week! 

https://docs.google.com/document/d/16lUR61w3JLx1BMuYknT5QMUV9IME_sTERvzUlfIBKMk/edit?usp=sharing

**Comment by ajlennon** [comment]
Made a couple of comments - looks great that.

**Comment by johnmckerrell** [comment]
@Robotorium did you have any thoughts about that blog post? We were interested in your viewpoint.

**Comment by Robotorium** [comment]
Looks brilliant to me! I made the very tiniest change, but already have
some people in mind to link to it!

Op di 16 nov. 2021 21:49 schreef John McKerrell ***@***.***>:

**Comment by johnmckerrell** [comment]
[Winners announced!](https://doesliverpool.com/co-working/first-boost-members-announced/) I'll close this issue now
