### ISSUE TITLE
Kitchen light not functioning properly

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1569]
The light comes on but is very dim

**Comment by johnmckerrell** [comment]
I've reported this to the landlord on their issue management system.

**Comment by amcewen** [comment]
I've installed some temporary lighting in the meantime... https://twitter.com/amcewen/status/1394243177029177350 :grin:

**Comment by johnmckerrell** [comment]
I've called the electrician and he says he'll replace it next week. (I mentioned the CNC room visible "sounder" so we'll see if that gets done too 🤷 )

**Comment by johnmckerrell** [comment]
TIL https://www.amazon.co.uk/s?k=led+garage+light+2+pack+e26+60w+deformable+led+garage+ceiling+lights+6000lm+daylight+lamps+with+4+adjustable+panels+deformable+led+shop+lights+for+garage+warehouse+workshop+basement+barn+lighting&geniuslink=true&tag=boingboing0e-21

Might be a simple option for a replacement to the current bulb.

**Comment by johnmckerrell** [comment]
I bought something from CostCo that fits in a standard bayonet (B22?) socket and has four panels of LEDs, similar to what is in the Amazon link above. Apparently it is 60W so probably brighter than we need but better than the bulb that's in there now. Annoyingly it's also warm white which doesn't really match what we have elsewhere. If anyone feels up to it they could check if they come in cool white and try swapping but I doubt it's worth it.

For the record the socket put in by Mick was a B22 bayonet socket but the lightbulb I removed was actually a screw fitting with an adapter going between the two.

I left the old bulb and adapter by the left sink.
