### ISSUE TITLE
Alcove computer DNS issue

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1570]
Good morning, 

I have tried to access the Internet but the DNS resolution error. Troubleshooter never resolved, so I will set previous restore point tomorrow morning (unless someone prefers me not to our has another solution).

**Comment by amcewen** [comment]
It might just be that someone has removed the WiFi dongle from it.  It hasn't got any networking built-in, so needs a black-and-white USB WiFi dongle to get on the network

**Comment by Knottyashcreative** [comment]
The WiFi adapter was in and identified within the network adapters. The
computer was able to identify and connect to the Does WiFi but the WiFi
would drop and bring up DNS resolution error.

**Comment by Knottyashcreative** [comment]
￼Dns issue identified - Fixed DNs server not reached. I removed fixed DNS address and it all works now.
