### ISSUE TITLE
Repurpose (Cleanse Data and Setup) Laptops from Little Sandbox

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1571]
I am currently erasing all data on the Littlel Sandbox laptops which were kindly gifted to DoES.

This issue captures the information which can be migrated to the wiki as and when time allows.

- They are mainly Lenovo Ideapad 305's (x4) with a G50 (x2)
- All existing data is to be wiped
- Ubuntu 20.04 LTS is to be installed
- Standard user "doesuser" and standard DoES password across all laptops
- Autologin to desktop for ease of use

@JackiePease has provided a list of software to be installed as a starting point (based on what people ask for)

- Universal GCode Sender
- Drawing Bot v3
- Inkscape (latest)
- Inkstitch (installs as Inkscape extension)
- AYAB (All Yarns Are Beautiful)
- Arduino IDE
- Word Processing / Spreadsheet support (LibreOffice)
- Firefox / Chrome
- Zoom

**[Edit: (AJL) This is quite time consuming so I am not intending myself to do another round of installs in the near future. However additonal wanted software can be noted on this issue and we can extend the installation procedure noted below then either myself or somebody else with time can add in the extras]**

Various dependencies are needed for the above. I have all added some scripting to ensure the above can be run from icons on the desktop

Installation procedure

- Set BIOS in laptops to non-secure mode, reset state of any "secure keys"
- Insert installation media. I used a Ubuntu 20.04 LTS USB stick as booting from USB is supported
- Power On and repeatedly click FN-F12 to enter the boot order menu and choose the USB stick
- Boot Ubuntu to the graphical UI and follow the standard Ubuntu installation procedure
- NB. UK language, Hostname does-laptop-X, User "doesuser", Password "b....", Erase anything on disk and reinstall, Allow non-opensource packages to be installed, automatic login

Once installed ensure everything is up to date so

- Open a terminal

```
$ sudo apt update
$ sudo apt upgrade -y
```

- Then install some basics

```
$  sudo apt install terminator gnome-tweaks magic-wormhole default-jre
```

- There is an archive I created of downloads of software from the above list. **WE NEED TO ARCHIVE THIS SOMEWHERE. It's currently on the GOLD laptop**. Copy this across e.g. with magicwormhole

```
$ wormhole receive 1-x-y
```

This will receive the Downloads-DoES-Install-20210518.tgz or similar. Unpack this

```
$ cd ~
$ tar xzvf Downloads-DoES-Install-20210518.tgz
```

This will put a set of files into the ~/Downloads folder. Copy across shortcuts to the desktop with

```
$ cd ~/Downloads
$ cp Desktop/* ~/Desktop
```

Then work through installing the applications that need special treatment

#### Inkstitch (plugin for Inkscape)

You will need to run Inkscape once first... (via the shortcut on the desktop - right click on the "Inkscape" shortcut and "allow launching" to be able to run it. See below)

```
$ cd ~/.config/inkscape/extensions
$ unzip ~/Downloads/inkstitch-v2.0.0-linux-en_US.zip
```

### Arduino

```
$ cd arduino-1.8.15
$ sudo ./install.sh
```

### AYAB

```
$ sudo apt-get install python3-pip python3-dev python3-virtualenv python3-gi
$ sudo usermod -a -G tty doesuser
$ sudo usermod -a -G dialout doesuser
$ cd ayab-desktop
$ sudo apt install libjpeg8-dev zlib1g-dev
$ pip3 install -r requirements.txt
```

### Chrome

```
$ sudo dpkg -i google-chrome-stable_current_amd64.deb
```

### Zoom

```
$ sudo dpkg -i zoom_amd64.deb
```

**This will fail** - then

```
$ sudo apt-get install -f
```
## Finishing

- Go to the desktop and right click on all the shortcut files to run the relevant applications to test.
- On some of them you might need to right click to select "Allow Launching"
- You might have two copies of Arduino launcher, if so remove one
- You can right click and remove unneeded favourites from the left hand bar.

**Comment by MatthewCroughan** [comment]
If you're interested, i can make a Nix configuration that can be deployed to these laptops that's more archivable without having to store a master copy in a tarball, like Yocto but less serious. 

Here's a complex example, of how I configure my laptop: https://github.com/MatthewCroughan/nixcfg/tree/master/hosts/t480

Here's a simple example of how I configure 3 machines on the Astralship https://gitlab.com/astralship/nixcfgs

The concept is that you'd just `nix build github:doesliverpool/sandbox-nixcfgs#system-image`, or better yet, just `nixos-rebuild switch` on the devices themselves and not need a system image, since they're probably all powerful enough to rebuild themselves.

This way, there is no need to do a string of commands in sequence, the system is just what is written in the Nix code.

**Comment by ajlennon** [comment]
You're welcome to come and do all the work I am doing here all over again if you like but I am doing it by hand atm.

You will need to be on hand to maintain it if anything goes wrong of course...

**Comment by ajlennon** [comment]
These laptops have all been done

**Comment by MatthewCroughan** [comment]
> These laptops have all been done

Ah, I see. I didn't realise this had all been done already.
