### ISSUE TITLE
Work out some prices for printing on our new large printer

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1573]
The printer has been tested and works. We need prices e.g. per linear metre? including paper (possibly different types) and ink

**Comment by arthurrowland** [comment]
https://www.liverpool.ac.uk/csd/printing-2013/print-costs/

Here are the University of Liverpool's printing costs. I'm not suggesting we match them, but may be useful as a benchmark - and to show people what good value the DoES plotter is!

**Comment by arthurrowland** [comment]
Have run some calculations based on 90gsm paper and 80% coverage to get ball rolling. Have costed paper by length as even if you're printing A4 on it the whole width is involved.

Possible it would be more like 120gsm and 100% coverage for posters and such.

Price | Spec | URL
------------ | ------------- |  ------------- | 
£0.36/m | 42" 1067mm x 50mtr 90g/m | https://www.plot-it.co.uk/p/hp_designjet_500_designjet_510_plotter_paper
£0.03p/A4 @ 5% Coverage | High Capacity HP 82 Ink Cartridges | https://www.stinkyinkshop.co.uk/hp/ink-cartridges/hp-designjet-510
£0.45p/A4 @ 80% Coverage | High Capacity HP 82 Ink Cartridges | https://www.stinkyinkshop.co.uk/hp/ink-cartridges/hp-designjet-510


Size | Printing Length with Bleed | Paper Cost | Multiples of A4 | Ink Cost @ 80% | Total Cost
------------ | ------------- |  ------------- |   ------------- |   ------------- |  ------------- | 
A0 | 847mm | £0.35 | 16 | £7.20 | £7.55  
A1 | 600mm | £0.22 | 8  | £3.60 | £3.82
A2 | 426mm | £0.15 | 4 | £1.80 | £1.95

**Comment by JackiePease** [comment]
The University prices seem in the right area then 
Currently waiting for some info from Vicky on what paper (weight etc.) we can use to avoid crinkling. 
Maybe we'll be able to offer different papers for different jobs?

**Comment by JackiePease** [comment]
Note: print heads are also consumables

**Comment by arthurrowland** [comment]
[This](https://bizfluent.com/decision-7544909-should-change-printhead-hp-plotter.html) says printheads lifespan is approximately 1000ml or up to 2 years.

Hard to guess how much use the printer will get, but may be a reasonable assumption that each of the 4 printheads need to be replaced every two years on average for a cost of roughly £37ea * 4 = ~£150. Something like £1 over 150 prints?

How to split that across each print involves a bit of guesstimates - maybe a 20% margin on prints to try and cover that cost? Which would end up pretty close to university pricing.

Could have a mix of weights but might get a bit complex pricing that in. I'm wondering how we could remind users to change to the right paper. Am sure there are ways.

Open to smarter ways of pricing this - just throwing out ideas as a starting point.

**Comment by arthurrowland** [comment]
Following offline discussion with Jackie, I had a brief look at software that calculates coverage - which we could use to estimate pricing in bands. Could be too complex of a process to go through.

Anyway, I found [this](https://avpsoft.com/products/apfill/) software via [this](https://printplanet.com/threads/ink-coverage-calculator.18827/) forum post, and a [couple](http://lab.dejaworks.com/ink-toner-consumption-using-calculator/
) of [other](http://www.excourse.com/presspercent/index.html) applications via a web search.

**Comment by LizTaylor404** [comment]
I had my laser induction at DOES on Saturday and Jackie showed me the large printer. I asked if it might be cheaper for printing a dress pattern, which has little ink coverage overall?

**Comment by seanspotatobusiness** [comment]
Is there some kind of software solution to determining how much ink is
being put down and calculating a price accordingly?

**Comment by LizTaylor404** [comment]
I'll see if I can find something.

**Comment by seanspotatobusiness** [comment]
I found something called APfill and another called PrintCalc. There
might be cheaper alternatives.


https://www.printcalc.com/Home/Pricing

https://avpsoft.com/purchase/apfill/

**Comment by DoESsean** [comment]
[Big Printer Costs.odt](https://github.com/DoESLiverpool/somebody-should/files/7218017/Big.Printer.Costs.odt)

Does this work?

**Comment by DoESsean** [comment]
Unfortunately, it kind of leaves people to decide for themselves what %age of coverage they have, but, short of having an arbitration panel, there's not much we can do about that unless we want to shell out for expensive software for something that likely won't be a massive issue.

I'm not against an arbitration panel.

**Comment by amcewen** [comment]
Seems these are the costs we're going with (to see how it goes at least...).  Can someone put them somewhere easier to find than in a document in a comment in an issue? :-D

Somewhere on the page for the printer on the wiki would be good, then we can point people who phone up (like the person who's just done that...) at the wiki to find prices

**Comment by DoESsean** [comment]
I've just attempted to do that, but have absolutely no idea how I would insert a table into the Wiki page. Apparently, just copy/pasting it doesn't work.

**Comment by JackiePease** [comment]
Added to the Wiki page (mainly following https://www.markdownguide.org/extended-syntax/#tables and using LibreOffice Convert - Table to Text - Separate Text at '|', then replacing the '|' with ' | ' to do most of the formatting) and also stuck a paper copy on the printer.

I think we can close this for the moment and open another issue if we need to revise the pricing.
