### ISSUE TITLE
Investigate makerspace pricing for Lightburn software

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1576]
@ajlennon has been looking into how community members could access Lightburn from their own laptops and found the following link.

https://forum.lightburnsoftware.com/t/new-to-laser-lightburn-and-question-about-licences-for-our-makerspace-members/38390

I've emailed them for further details.

**Comment by ajlennon** [comment]
Hi all.

Yes indeed - will be interested to hear the response.

- Firstly the standard license is fixed to a PC but you can have 2 as standard or 3 if you ask nicely
- Secondly you can pay for a floating license or per seat licenses 

To be honest the standard license seems more for a single person rather than multiple users although I might be wrong

That said there looks to be a better/cheaper license for makerspaces, and also a 75% license for makespace users.

My guess is we could get a good price on a license for the 'space and then I as a user would probably be happy to pay 75% off another license just for me (for a year only I think) which would then mean I could work on things without blocking people in the workspace.

Also on top of _that_ if we could install the software on another one or two systems for use by people in the desk area that would seem a really nice thing (instead of having to work in there by the laser cutters as one is prepping one's designs)

(Also from reading their forums they basically seem very decent people who have put a lot of work into their product and want some support from the users but aren't going crazy with their pricing)

Just some thoughts!

**Comment by ajlennon** [comment]
Did they get back to  you on this @JackiePease ?

**Comment by JackiePease** [comment]
Well reminded @ajlennon !
Yes, we've had the following helpful response:

We encourage the learning possible in the MakerSpace/HackerSpace environments and provide significantly discounted licenses of LightBurn to help do so. Our licensing for these types of enterprises is as follows:
 
The HackerSpace buys a single, initial license key which provides two seats. Pricing for these are currently $40.00 USD for the GCode version or $80.00 USD for the DSP version, which includes the GCode stuff. We subsequently provide additional seats to members for 75% off of the base price, $10 GCode, $20 for the DSP version.
 
This is intended to generously provide each active member the ability to utilize LightBurn on their personal computer systems. This way they might do their prep work in a convenient way for them.
 
Once the initial order is processed, we’ll set up a coupon code that can be distributed to members to purchase their own copies.
 
We can also provide additional seats for the space itself at the reduced price, just let us know what you need and which type of machines you are running so that we can determine which license type you'll need.  

Cheers,
Dominic (yes, that Dominic)
LightBurn Software Support

**Comment by ajlennon** [comment]
Well that all seems rather good then?

**Comment by JackiePease** [comment]
Yes it does - shall we leave it a couple of days to see if anyone has any comments?On 17 Jun 2021 19:06, Alex Lennon ***@***.***> wrote:
Well that all seems rather good then?

**Comment by ajlennon** [comment]
When I run up LightBurn I have to add a laser cutter. What should I set up and what size? Thanks

**Comment by magman2112** [comment]
I have just checked the controller on the laser cutter Shiela, it has a Leetro MCP6525 controller. This is NOT currently compatible with Lightburn, according to Lasergods website - https://lasergods.com/controller-dsp-identification/#Leetro_AutoMation_CoLTD_Leetro_DSP. 

There is some discussion of an extension to Lightburn to support this controller in the future, but it doesn't at present. 

To get Shiela to work with lightburn, we would have to upgrade the controller at present, like we have done for Tony and plan for Gerald and Sophia.

**Comment by magman2112** [comment]
@ajlennon Currently, Tony has limits of 900 by 1400 mm. The absolute limits I have just measured are 950 by 1425 mm, though we still need to investigate whether we should allow these full limits or not.

None of the other lasers are currently setup to use Lightburn, so we will set the limits for these when we need to.

**Comment by JackiePease** [comment]
I've emailed Lightburn to see how much we'll need to pay to renew the licence and get the membership benefits.

**Comment by ajlennon** [comment]
Thank @magman2112 what controller should I set into Lightburn for Tony?

**Comment by magman2112** [comment]
@ajlennon from memory, I think it should be Smoothieware for the controller.

**Comment by ajlennon** [comment]
I'll probably get a license if it's a tenner a year. Quite fancy playing with it a bit more on Tony. Is Tony all set up and running now if I just go and use it?

**Comment by magman2112** [comment]
@ajlennon Tony is running quite well at the moment, though not quite 100% yet. 

@Sean-anotherone and I got the homing and limit sensors working yesterday, which was one of the last few jobs outstanding. We still plan to do a full alignment though (hopefully next Thursday) as we are not getting full power over all of the bed - though the front left corner still performs very well.

**Comment by ajlennon** [comment]
I got to tell you guys - @magman2112 @Sean-anotherone - that laser on Gerald is AWESOME HELPFUL. Thanks!

**Comment by JackiePease** [comment]
Dominic from Lightburn got back to me with a discount code DoES Liverpool members can use to get personal copies of Lightburn. I've saved it in the usual place, so get in touch with one of the organisers if you need it.
"this is for a single-seat license of LightBurn, intended as an extension of the license from the space, to allow members without their own hardware to use the software at home. If a member does have their own laser, we encourage them to purchase a full license"
​
He also provided the following information on licencing for our laser cutters. I've emailed @DoESsean to ask him to get the DSP licence as we do intend to upgrade the other laser cutters during the year.
​
_The license you've shared with me: 

Is a G-Code only license and as you say, it expired in January 2021. You'll need to renew it if you want to get the latest version of LightBurn but you can happily run your existing version forever for free. 

If you'd like to run the latest version and request support, you should renew, to renew that license go here:
https://lightburnsoftware.com/products/renew-lightburn-license-key 

I think however given all you've said about the situation with machines at DoES that you should consider also upgrading the license to the full DSP license. The discount code I've provided allows members to purchase  either a discounted G-Code version of the license, to match what you currently have or to purchase the full DSP license, which would allow you to use upgraded machines using a DSP controller. 

Why get a DSP License? 

Gerald and the Blacknose laser cutters will both need their controllers replacing to run on LightBurn, an upgrade I'd encourage. The sort of controller you will need would be a DSP controller. AS LightBurn doesn't (and is unlikely ever to) work with Leetro controllers, due to the security features provided by the software dongle these upgrades would be essential to use LightBurn on all machines. These upgrades are very likely something DoES can manage in house, but of course Smoke & Mirrors can also quote for doing the work. 

If you choose to, then you can upgrade your license to the full DSP license here: 
https://lightburnsoftware.com/collections/frontpage/products/upgrade-gcode-to-dsp-license
The DSP setup will allow DoES to run all 3 machines (once suitably upgraded) on this license. Additionally I've also added a third seat to your existing license, meaning you'll be able to run that license on 3 computers._

**Comment by ajlennon** [comment]
Well that all sounds super. Where is the usual place @JackiePease :)

**Comment by DuncReid** [comment]
> Well that all sounds super. Where is the usual place @JackiePease :)

Yes, Wot he said! :) I'll certainly have a copy.

**Comment by KayaScott** [comment]
Thanks for the code Jackie.   This was quick and simple. I had already downloaded the trial version, which the people at Lightburn kindly extended for 2 weeks while the codes etc were worked out. The link you provide links straight to Lightburn with the generous discount already applied. No messing about. I took out the DSP licence ($20 instead of $80), pay by card or PayPal. Within 5 minutes I had the new key to activate my licence and was able to carry on working on my files. I have found this so useful to be able to prepare my files away from the laser cutting machines

**Comment by ajlennon** [comment]
That’s really strange as I just went to the $80 price. 🥺🤔😳

**Comment by Knottyashcreative** [comment]
Hi Alex,
I initially found this purchase, confusing and had to do the following steps;
First, click on the 'Add to Cart' option for the $80 license. This then takes you to a second page and then click 'Check out'. The code is then automatically applied on the final page, i.e. pays $20. I hope this makes sense.

Once the software key is sent to you the other issue I had to resolve was setting up the software away from Tony i.e. requires knowledge of the controller board and laser bed preferences.  This can be done independently from Tony but found it much easier to wait and then connect the USB from Tony  as it then updated the preferences.  I only had to manually modify the bed orientation from portrait to landscape.

I hope this was of use.

Regards

**Comment by JackiePease** [comment]
@ajlennon - did @Knottyashcreative comment resolve the issue you were having?

**Comment by ajlennon** [comment]
Aaaaah thanks @Knottyashcreative - that explains it!

Yes I am now a fully licensed up "DoES" Lightburn user thanks @JackiePease

**Comment by magman2112** [comment]
I have had a reply from Lightburn Technical Support and it appears that we have purchased an upgrade to the DSP version of Light burn, but this does not include a renewal of the license.

We need to purchase a renewal using the following link.

https://lightburnsoftware.com/products/renew-lightburn-license-key

This appears to cost $30.

**Comment by ajlennon** [comment]
My reading of their responses was that you only need to renew if you want to upgrade to a newer version? Is that wrong?

**Comment by DoESsean** [comment]
I hope not, because I've just renewed it!

**Comment by ajlennon** [comment]
Yeah you paid for a year of updates imho

"No. You pay once, the software will work forever as long as you have your license key."

"If you choose to renew your license to receive another year of software updates, the price is $30.  Renewing your license will add a year of updates from today.  If you renew before your license expires, we'll add an extra two months."

https://lightburnsoftware.com/pages/how-the-lightburn-license-works#:~:text=Is%20it%20a%20subscription%3F,you%20have%20your%20license%20key.

**Comment by ajlennon** [comment]
(But they seem nice reasonable people with a nice product and $30 isn't going to break the bank hopefully and for me although I haven't used LightBurn much it does feel like "the right thing to do"(tm) )

**Comment by magman2112** [comment]
Using a phrase from an old workmate of mine "I Know that, but..."

The license for the Lightburn copy on Tony was one year old in February, so getting on for over 5 months out of date. Given that DoES members will be getting licenses for the latest version of Lightburn, it makes sense for the Master license for our Maker Space is up to date, so that newer capabilities in Lightburn are supported on our lasers for our members. 

As an example, a recent update released a rewrite of the file storage mechanism (saving .lbrn2 files), which are typically half the size of the old files (.lbrn files). This is typical of the enhancements we can expect in the near future which we would miss out on without a license renewal.

**Comment by ajlennon** [comment]
> Given that DoES members will be getting licenses for the latest version of Lightburn, it makes sense for the Master license for our Maker Space is up to date, so that newer capabilities in Lightburn are supported on our lasers for our members.

Aha! Clever!

**Comment by magman2112** [comment]
The renewal for Lightburn has come through and I have confirmed the update on Tony’s PC.

is it OK to close this issue now?

**Comment by JackiePease** [comment]
Yes
