### ISSUE TITLE
Buy new supplies for Threaderic the Embroidery Machine

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1577]
Threaderic is proving popular - we've used nearly all the stabiliser that came with him and are running short of some thread colours (e.g. yellow).

I think we could provide stabiliser at £x per metre as apparently it is a lot cheaper per metre if you buy in bulk, but maybe we could leave people to buy their own preferred thread colours? The issue would be making sure suitable thread is used, as @Robotorium said other threads might damage the machine. Bobbin thread seems to be very specific.

A couple of people, e.g. @LizTaylor404, have mentioned preferred suppliers, so hopefully they can add their views to this issue.

Note: Abakhan do sell embroidery thread and a range of stabilisers

**Comment by LizTaylor404** [comment]
I've had a look at the price of stabiliser. A lot of the stabilisers come in a 90cm wide roll and are about £3.40/m or £65.95 for a 25m roll.  I haven't used plushaddict.co.uk yet but they did have the Vilene stitch and tear by the roll. Abakhan don't have a price per roll, only per metre, however they may sell it by the roll.

This shop on Ebay was set up during the pandemic and appears to specialise in embroidery. It sells the narrower version like you currently have (It might be easier than cutting it down) https://www.ebay.co.uk/usr/refresh-sewing-leominster and it seemed very reasonable priced.

I'm not sure if Abakhan stock the thread for Threaderic. It's a thinner thread than normal thread, possibly 40wt. Jaycotts, a sewing machine shop based in Chester, sell Brother embroidery thread and are well priced. I would agree that other threads would damage the machine.

The bobbins are specific to the machine, not a normal bobbin. 
Replacing the needle should be considered too. 

This is the manual for Threaderic: https://download.brother.com/welcome/doch100205/888g80_g82_om02en.pdf

My go to fabric suppliers are jaycotts.co.uk, Abakhan (shop only), https://www.doughtysonline.co.uk, https://ohsewcrafty.co.uk

**Comment by Sean-anotherone** [comment]
A couple of points from me 👍 


1.  The machine jammed earlier today with a "is the needle bent" error.  Application of a little sewing machine oil (it was very stiff) helped a lot, but it was still sticking at one point in the rotation.  Further investigation found a piece of some very sticky fabric/plastic that was jamming the bobbin mechanism.  (~25mm x 3mm) 
 
Once this was removed the thing now runs like a sewing machine...  I note also that the manual states that users should not lubricate the machine - but this might just be motivation to keep their servicing network in business, a drip or two applied with a cotton bud certainly loosened it up a lot.

The little piece it left on top of the machine in case it came from somewhere important, whatever it is it clearly was not meant to be in the undercarriage jamming the bobbin.

2.  I found some online resources that suggest you can embroider with any thread as long as you sent the tension correctly, this is at odds with the guidance received from Snoof, but might be worth checking out?

**Comment by Robotorium** [comment]
For machine embroidery? You can hand embroider with any thread you like,
but I'd be surprised to read a resource about machine embroidery saying you
can use any thread for that.

Op di 1 jun. 2021 22:56 schreef Sean Jarman ***@***.***>:

**Comment by JackiePease** [comment]
I've ordered this from the eBay contact recommended by @LizTaylor404 -
Embroidery Tear Away Backing Stabiliser 30cm x 50 Mtr For Brother Janome
	
Item price | £21.00 + £3.75 postage, so approx. 50p per metre, should arrive Saturday 12th June

**Comment by JackiePease** [comment]
Stabiliser has arrived - labelled at 50p per metre. General view seems to be that people are happy to buy their own thread. We can look at this again later if necessary
