### ISSUE TITLE
Embroidery bobbin

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1579]
![20210608_081947.jpg](https://user-images.githubusercontent.com/58068720/121140918-5088e180-c832-11eb-806d-487b231b32d7.jpg)

Bobbin collapsed in machine. I have temporarily replaced with metal bobbin. A replacement bobbin needs to be located or ordered.

**Comment by JackiePease** [comment]
I have ordered 10 bobbins from eBay - 
 
10 Pack Brother Bobbins 11.5mm Fits Innov-is Sewing Embroidery Machine SFB
They were £6.99 with no P+P and should arrive Friday 11th June

Note: the manual says that using the wrong bobbins might damage the machine, so make sure that any bobbins you're using in the meantime are the right type

**Comment by JackiePease** [comment]
Bobbins have arrived - I've put them in the box with the embroidery thread
