### ISSUE TITLE
Add a optional interest fee with each subsequent invoice reminder

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#158]
I tend to let these things batch up till I get round to paying them.  This might help me get my debts settled on time.

**Comment by DefProc** [comment]
If you'd like us to increase the size of your invoices, then we can do(!), but otherwise it doesn't cause us enough of a business problem, or really fit well with the ethos of DoES, so we're unlikely to do this in the near future.
