### ISSUE TITLE
Pledge drive for a USB Power meter

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1584]
I'd quite like a USB power meter but don't want to pay full price for a good one, and don't want a rubbish one :-) 

They're £40-50, I could put in £10, anyone else want to join me?

I've seen this on Amazon which has decent reviews:

https://smile.amazon.co.uk/Klein-Tools-ET920-Power-Meter/dp/B07GXZHPVR/?_encoding=UTF8&pd_rd_w=Qo2Vf&pf_rd_p=8dde2346-7e91-4f1b-a111-f838fe0a19b1&pf_rd_r=WWQBH0R7HPFGB2K3P7P9&pd_rd_r=8bd4dbe1-d304-44e2-9dfe-4a87a81802c7&pd_rd_wg=1YX3O&ref_=pd_gw_ci_mcx_mr_hp_atf_m

It's just over £40 (with shipping) although would take a few weeks to arrive, or £49 would get it on next day Prime delivery. I checked eBay and a few other places and the prices are similar, in fact this one comes to around £40 including £12 shipping but not sure where it ships from.

https://www.mouser.co.uk/ProductDetail/Klein-Tools/ET920?qs=rkhjVJ6%2F3EJyRjOgeC1Okw%3D%3D#collapseProductSpecs

**Comment by johnmckerrell** [comment]
I noticed that the price on this has gone down, can get it delivered in a few days for £35.96. Anyone want to go halves?

**Comment by Robotorium** [comment]
Yeah go on, good plan.

Op ma 26 jul. 2021 om 17:36 schreef John McKerrell ***@***.***

**Comment by MatthewCroughan** [comment]
I'll chip in, so it's divided by three now.

**Comment by johnmckerrell** [comment]
Great, it's on the way now, should arrive Thursday. I've got some things I want to test at home and then I'll bring it into DoES. Can arrange payments once I've confirmed it's all working as expected.

**Comment by Robotorium** [comment]
Shout when you know :)

Op di 27 jul. 2021 09:09 schreef John McKerrell ***@***.***>:

**Comment by johnmckerrell** [comment]
It arrived, I've tried it out with various things. I am sometimes left wondering if the device is causing the charger or device to make different decisions. Like when I charge my iPhone X from either a small 30W USB-C charger or my laptop's 80W charger the meter is only reporting 1.5A, so ~7.5W but it should definitely be able to use more and both chargers should be capable of providing it. I do get higher 20v 2-4A (so 40-80W) showing from my laptop charger though so does seem like it should be able to cope with higher.  A few other devices give 8.9V and 1.2A, the higher voltage is interesting but still not reporting particularly high wattage.

One complaint I saw on reviews was that the male cables -> usb sockets do mean you sometimes end up having to plug directly into the charger which is then awkward. I thought "oh just use an extension cable" but of course that then changes the environment and.. who has a USB-C extension? I do have one thing I want to test that terminates on a male plug which then means I can't use the tester. I've found a female - female USB-C adapter that I'm going to try for that one.

**Comment by johnmckerrell** [comment]
I got the female-female adapter but for some reason the meter couldn't use it. Without the meter in place I was definitely getting a charge but when the meter was in-line it didn't even turn on. The meter uses the power from the USB to operate.

I've now taken the meter and an adapter into DoES. It's on my desk for now but we'll want to find a proper labelled place for it to live, perhaps the multimeters draw?

**Comment by Robotorium** [comment]
What do I owe you?

Op di 10 aug. 2021 20:13 schreef John McKerrell ***@***.***>:

**Comment by johnmckerrell** [comment]
£35.96 / 3 = 11.98 - just put it in DoES's account and I'll take it from petty cash (if @DoESsean lets me!)

**Comment by Robotorium** [comment]
Sorted, reference "for john"

Op di 10 aug. 2021 20:19 schreef John McKerrell ***@***.***>:

**Comment by MatthewCroughan** [comment]
@johnmckerrell Shall I pay 11.98 more on my invoice for DoES in order to give you this payment?

**Comment by johnmckerrell** [comment]
I figured a single payment would be possible but thinking about it that might not be the case, if you're in the space you could always leave cash on my desk, I'll be in on Friday.

**Comment by MatthewCroughan** [comment]
In Wales at the moment, so will be a while on that (week or two).

**Comment by amcewen** [comment]
Is this all sorted now?

**Comment by johnmckerrell** [comment]
Going to close this as I assume it was paid but if you remember otherwise @MatthewCroughan please do make payment somewhere!
