### ISSUE TITLE
Screw thread on large embroidery hoop is threaded

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1588]
Karen was unable to tighten one of the large embroidery hoops - on examination the screw seemed to be threaded. She was able to tighten it once an additional nut had been added, so that it tightened on a different part of the screw thread.
We need to buy some new tightening screws. Brother ones are £10 each (inc. nut), so these seem worth trying, as this seems likely to happen again:
https://www.amazon.co.uk/YICBOR-Embroidery-Adjusting-Compatible-BabyLock/dp/B08ZD2XMX7/ref=asc_df_B08ZD2XMX7/?tag=googshopuk-21&linkCode=df0&hvadid=520020701960&hvpos=&hvnetw=g&hvrand=5985874528111621311&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9046551&hvtargid=pla-1269657907336&psc=1
There should also be another large hoop - we couldn't find it.

**Comment by Robotorium** [comment]
Last I saw the other one (the day I talked to you and Terry, was it Monday
maybe?) it was on the desk to the left of Fred.

Op zo 4 jul. 2021 18:39 schreef Jackie Pease ***@***.***>:

**Comment by JackiePease** [comment]
Will wait to order until we have £20 worth of Amazon stuff to buy as would be £4.99 shipping. Using an extra nut gives a temporary workaround (not likely to last long though).
@Robotorium Unfortunately that's the one Karen's using

**Comment by johnmckerrell** [comment]
I have prime and can order for delivery tomorrow if you want.

**Comment by johnmckerrell** [comment]
I have now ordered it, should be at DoES tomorrow, addressed to me but feel free to open it.

**Comment by JackiePease** [comment]
These have arrived. They look very similar to the old one. I've fitted one and put the rest in the thread box.
