### ISSUE TITLE
Separate mailing for people who might open & close up

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#159]
We should move the doodle emails to a separate list so that we can add more people without them having to get all the organisers chatter.

**Comment by DefProc** [comment]
I've set one up, just needs the more people adding to it.

**Comment by DefProc** [comment]
done. John, can you send doodle emails to the keyholders address

**Comment by johnmckerrell** [comment]
This is now happening. For now it's just the weekly "please fill out this doodle" email that goes to the "keyholders" list, the warning emails that go out the day before only go to organisers so as not to annoy the new volunteers.
