### ISSUE TITLE
Blind cord in event room spontaneously(ish) disassembled

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1592]
I tried to close one of the blinds in the event room today (the one just to the left of the centre dividing post). When I tugged on the cord, the entire chain came down. By the looks of it, it's just either a failure of the clasp, or it just wasn't properly inserted/had worked itself loose over time.

Unfortunately I wasn't able to fix it because the disconnected end is all the way up near the blind. Sorry about that.

**Comment by magman2112** [comment]
I’ve re-connected the chain now with the convenient ladders in the nook. 

I also fixed the chain on one of the blinds in dinky, which had come off completely.
