### ISSUE TITLE
Remove ink marks from table in Dinky

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1594]
There are ink marks on the table in Dinky. It looks as though someone has been colouring something on and gone over the edge of the paper.

It would be useful to know what sort of pens were used to help decide on  solvent.

**Comment by JackiePease** [comment]
I was able to remove most of the marks with IPA (https://upgradedhome.com/how-to-remove-sharpie-from-wood/). It did take off the polish too. Last night @magman2112 applied some new polish but it was already water marked this morning, so it looks like we need something more resistant.

**Comment by magman2112** [comment]
Having looked at the table on Sunday, I believe the water marks are the ones that were there before the last application of polish - the polish has just soaked into the wood. Thinking about it a bit more, I believe the water mark was slightly reduced from before the new polish application.

I will try a few more applications of the new polish to see if it just needs a few more coats to improve the finish before trying anything else.

**Comment by JackiePease** [comment]
It looks like Irene has polished the table using the polish @magman2112 bought. The table looks good at the moment, so it maybe we'll just have to reapply polish regularly
