### ISSUE TITLE
Gerald beeping on start-up, and not stopping

### ISSUE THREAD

**Issue by arthurrowland** [DoESLiverpool/somebody-should#1598]
Turning everything on at the wall starts the beeping. Appears not to be the controller as beeping continues if you hit the e-stop on the control panel. I feel like I should be able to diagnose further, but can't figure it out!

Someone was just using the machine minutes ago (now left the space) and I couldn't hear beeping while they were using it.

**Comment by arthurrowland** [comment]
It's the cooler!

Thanks to Jade for explaining it to me this morning.

For anyone not already aware, pausing to let it cool down and topping up the water are two options to resolve it.

**Comment by johnmckerrell** [comment]
I was going to suggest adding this to the troubleshooting page for Gerald, but now I see it doesn't have one that's over on Sophia. I wonder if it's worth moving that into a separate page and linking from them as they have some similar problems. 🤔

**Comment by arthurrowland** [comment]
A troubleshooting guide would be useful!

Common situations that come to mind (that I could write some answers to on the wiki, but not right now):
- The image I want to etch won't load
- It won't send the file from Lasercut to the machine
- It's not cutting the same across the bed (particularly on the right hand side)
- The lines are wobbly
- The laser head stopped moving
- The laser head stopped firing
- The light went out
- There's a second cut line or 'shadow'
- And "The laser is constantly beeping"

I had a momentary search and it looks like there are quite a lot of well-written guides by other maker/hackspaces which presumably we can adapt. For example [Bristol hackspace's guide on LaserCut 5.3](https://bristol.hackspace.org.uk/wiki/doku.php?id=equipment:a0_laser_cutter:prep), [also their pdf](https://bristol.hackspace.org.uk/wiki/lib/exe/fetch.php?media=blacknosemanualv0.2.pdf); [Oxford's operation guide](https://wiki.oxhack.org/wiki/Silvertail_A0_Laser_Cutter); [Leeds with the risk assessment](https://wiki.leedshackspace.org.uk/wiki/Laser_Cutter); [Manchester with some material safety info](https://docs.hacman.org.uk/Workshop_Areas/Visual_Arts/Equipment/Laser_Cutter/); [London hackspace's wiki](https://wiki.london.hackspace.org.uk/view/Laser_Cutter/Instructions) and [inkscape guide](https://wiki.london.hackspace.org.uk/view/Guides/Inkscape_for_Laser_Cutting).

I had been thinking about putting together an Arthur's laser cutting tips and tricks video/guide as it would be good to save others from making the same mistakes and wasting the same amount of time I have over the few years I've been regularly using the machines. But not yet a priority - might be good as a collaborative effort at Maker night now they are resuming, if anyone wants to work on that let me know.
