### ISSUE TITLE
Write down what it means to open & close up

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#160]
We should document some guidelines for what it means for opening up, both to make sure people do what is necessary but also so that they can be confident of what they *don't* have to do too. Relates to, but shouldn't block, #159

Few examples to start with:
 * Don't leave any rooms empty, shut door if you need to leave for a few minutes, or if you're in the Fridge.
 * Don't have to give tours if you don't want to, it's ok to say "sorry, there's no-one around that can help you with that right now" and perhaps suggest Tuesday or Thursday afternoons as Sean's guaranteed to be around then.
 * If there is a fire alarm you need to make sure all three rooms are emptied.

**Comment by DoESsean** [comment]
This has been done, and is at http://wiki.doesliverpool.com/OpeningAndClosing#preview

Once it's been reviewed for what will hopefully be the last time, it needs emailing to the list and then this issue can be closed.

**Comment by johnmckerrell** [comment]
Done, reviewed and sent out.
