### ISSUE TITLE
What To Do With Mail

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1600]
We've a few people that have had mailboxes and then let them lapse, but either haven't picked up the mail that is here, or are continuing to receive mail here.

I think there is a consensus that we should just be putting mail back in the postbox as 'Not Known At This Address,' so I think my question is how long do we leave it before doing so? 

As an example, there is currently a company with a mailbox that has been a prompt payer in the past, and has had their mailbox for quite a while. However, their current invoice is 5 months overdue, and the email address we have for them is returning messages undelivered. As an additional wrinkle, they have mail here, and I know that someone has been in in the last few months to collect mail.

While I do think there should be some leeway, it seems unfair to continually take in mail for companies that haven't paid, whilst others keep up to date and are, effectively receiving the same service.

**Comment by MatthewCroughan** [comment]
Do you think that a personal non-automated notification/prodding would make a few come up to date with their payment? I think some details could be worked out with whoever responds/picks up the phone, if there are humans at the end of the line :smile:

**Comment by DoESsean** [comment]
I've emailed those that are behind, so hopefully that will help.

**Comment by amcewen** [comment]
Mail for people who no longer pay for mailboxes is now returned marked "no longer at this address".
