### ISSUE TITLE
Clean Tony's bed sections

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1601]
Tony's bed obviously hasn't been cleaned for years. Cut items are very dirty as a result and there are also lots of fumes

**Comment by JackiePease** [comment]
I bought Heavy Duty Layflat Tubing Width-4ins/Length 168m from Amazon. 
@kayascott cut 8 lengths, sealed one end of each using the handheld acrylic bender, then tested for leaks by adding a small amount of water.  
We put one piece of honeycomb or one frame in each of 4, then put each into another length. We filled each with oven cleaner, sealed with the acrylic bender and left for 18 hours. We then used a jug to pour tap water through the tubing until they were fairly clean, after which we curved them round and rinsed them in the sink. The frames are now clean and the honeycomb is fairly clean. 

Lessons learned:
- it's probably best to avoid curving the honeycomb as much, and to support it as much as possible in the frames while cleaning
- be careful feeding the frames/honeycombs in to the packages - watch for the plastic being sliced accidentally
- use the hosepipe adapter to get more water going through the tubing
- Mike has bought sodium hydroxide, so we can make up a 10% solution instead of using premixed oven cleaner

**Comment by JackiePease** [comment]
@Kayascott  and @Sean-anotherone made another 20 packages from the layflat plastic. There were a high number of fails when leak testing after using the acrylic bender to seal the packages. After experimentation and further leak testing it was found that using an iron with baking paper gave 100% seal.


They decided to clean 5 units so that  the bed was still useable.  
The frame and honeycomb were put in a single package to protect the honeycomb. Our plan is to  rotate them twice a day for 2 days before rinsing

2.5 litres of 10% caustic soda solution was made up and 500 ml poured carefully into  each packet.  The tops of the packets were tightly rolled and taped over.  The packets were placed on the floor on plastic bin bags with tissue under the rolled ends so we can see if there is any leakage.

Lessons learned:
- Sealing bags with iron and baking paper is much more successful at sealing the end of the layflat plastic.
- Need to buy plastic bag clips to seal the open ends of the packages more securely

**Comment by magman2112** [comment]
The remaining bed sections have now been cleaned and re-installed into Tony. This was a long winded and a little dangerous way to clean these bed, so I think we should investigate alternate cleaning methods.
