### ISSUE TITLE
Large format printing only a narrow (A4-width) band

### ISSUE THREAD

**Issue by arthurrowland** [DoESLiverpool/somebody-should#1604]
Yesterday I tried to print an A1 document. The prints that came off would only print to what looked like and A4's width, on the right hand of the plotter.

I reloaded the reel, tried changing the paper size on the driver and on the plotter, and rotating the image, to no avail.

Setup:
- Windows 10
- SumatraPDF
- File: [Melting-Temperatures_A1_white.pdf](https://github.com/DoESLiverpool/somebody-should/files/6916454/Melting-Temperatures_A1_white.pdf)

I have successfully printed larger PDFs from the same laptop and setup in the recent past.

**Comment by amcewen** [comment]
I've printed larger things since then without any trouble, and it was used for a load of patterns recently too.  Going to close this until anyone spots it happening again.
