### ISSUE TITLE
Tony's extractor 

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1607]
I noticed that Tony's extractor pipe was torn and expelling fumes. I have temporarily taped it up (no fumes could be identified ) and would suggest it needs further exploration, at some stage ie check what I've done is acceptable and any suggest any further alterations.

**Comment by magman2112** [comment]
@Sean-anotherone and I removed the extractor hose last Maker Night and found that the extractor tubing had collapsed and wasn't extracting very well at all. Also, we found that the tubing connecting to the wall mounted extractor piping was too large for the connection to the laser, which likely contributed to the collapse.

Sean used the reducer from Sophia to get a better fitting hose fitted to the extraction point and overall extraction is now working well. We will need to source a new reducer when Sophia is put back in service, but that will be a while in the future.
