### ISSUE TITLE
3d printing issues on Prints Adam

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1611]
Prints Adam doesn't seem to be working very well.

After a print it retracts the filament too far, so that it jams when it starts the next print. It was jammed the last time I looked.

I posted a photo of a failed print on Twitter (https://twitter.com/jackie_pease/status/1436377134704910338) and people responded with the following suggestions (I intend to look into these, but haven't yet):

- look at the minimum time per layer on that, as it looks to be getting worse as it gets higher up
- Z gantry skew or Z axis wobble is a good shout. I've seen similar with dual driven Z with one leadscrew limit switch slightly out.
- If it's an ultimaker style printer  I wonder if its a Z resonance issue also.
- So its unlikely to be leadscrew related on an ultimaker. Could be lots of things... fan/cooling even.
- troubleshooting guide if you're ever stuck (https://simplify3d.com/support/print-quality-troubleshooting/)

**Comment by amcewen** [comment]
I got the bowden tube out, as a first step towards unjamming it, but the nozzle still seems blocked - looks like the filament might have snapped off in the PTFE coupling and nozzle :-/  Needs some more investigation.

**Comment by amcewen** [comment]
I dismantled the extruder on Saturday and extracted the bit of filament that had broken off inside it, so it's now working again.  I've not investigated any of the issues @JackiePease was having with taller prints, but it's back printing so I'll remove the `broken` label.

**Comment by huffeec** [comment]
fixed by #1745
