### ISSUE TITLE
Need to get more solder for the electronics workbench

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1612]
Judging by #1313 it seems we get through ~250g of solder/year :grin: 

It ran out yesterday - my spool of fine solder is on the electronics workbench as a temporary solution.  I've ordered another [500g of lead-free](https://cpc.farnell.com/duratool/d01686/solder-sn99-3-cu0-7-0-7mm-500g/dp/SD01540?st=solder) from CPC, the same as we had before.

**Comment by amcewen** [comment]
This arrived and has been deployed to the solder dispenser on the electronics workbench.

**Comment by magman2112** [comment]
I decided to re-open this issue rather than opening a new one, as we are very low on solder again.

I checked and the order number is still OK and is in stock at CPC.

**Comment by DoESsean** [comment]
I've ordered that for you now.

**Comment by amcewen** [comment]
It's arrived and is on the electronics workbench.
