### ISSUE TITLE
Tony producing skewed output

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1613]
@magman2112 was engraving some large size lettering last week. The letters appeared to lean slightly at the top.
This could also be an issue if you need pieces to be exactly square e.g. for boxes

**Comment by magman2112** [comment]
This issue has been fixed. See #1620 for comments on the resolution of this issue.

Also, this was a cutting not an engraving issue, I was cutting parts for a Book Scanner when I identified the issue.
