### ISSUE TITLE
Small circles cut on Gerald not very circular

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1616]
These are 4 part circles - I haven't united the lines. They're around 2mm diameter. 
![IMG_20211006_122324](https://user-images.githubusercontent.com/12802256/136193716-55b00147-c44b-40bb-9955-a9fb2574af6d.jpg)

**Comment by magman2112** [comment]
We found that the air assist pipe had been melted by someone using the laser in the previous weak, which was significantly reducing the air assist through the nozzle. The damaged pipe was replaced and the air assist is now back to normal operation.

Further testing found that holes on the surface of the material were cut better, not 100% circular, but a lot better than with the faulty air assist. One thing we did find though is that the beam from Gerald's laser is slightly lenticular, so on the opposite side of the small holes cut on 3mm plywood, the holes were more elliptical than those on the top of the same material. This is unlikely to be changed until we replace the laser tube, so I am going to close this issue for now.
