### ISSUE TITLE
The microwave turntable is turning unevenly

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1618]
The turntable is moving round unevenly e.g. as if belt is slipping
@Knottyashcreative reports that it moves round more evenly if he temporarily removes the roller ring
Assigning to @DoESsean to check warranty

**Comment by DoESsean** [comment]
The only transaction I can see for a Microwave in Freeagent is in March of this year. If that's the right one, then it should still be within warranty as the instruction manual (in the Miscellaneous folder in the bottom drawer of the filing cabinet) says that there is a 12 month guarantee from the date of purchase.

**Comment by DoESsean** [comment]
Did this ever get sorted? Because it would be out of warranty now.
