### ISSUE TITLE
Fred not trimming thread.

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1622]
Fred hasn't been trimming thread as he should be. I had him open and picked out a tonne of fluff, which made him revert to trimming top thread but not bobbin thread.

After some back and forth with Brother, because there aren't many comprehensive breakdowns of the insides of an embroidery machine online that I could find, it turns out our bobbin case (or inner rotary hook) needs replacing because the felt mat which holds the bobbin thread in place has gotten ripped off at some point.

Fred is useable if you cut the bobbin thread manually, but if we want a replacement bobbin case that works properly, I've found one here  https://www.bsk.co.uk/brother-genuine-bobbin-case-inner-rotary-hook-for-sewing--f440e-nv800---br029-9410-p.asp which is an official part, or else if anyone finds it (part number XG0871101 for NV800E) cheaper then obviously that works too.

**Comment by JackiePease** [comment]
I have ordered this

**Comment by JackiePease** [comment]
Now fitted and problem fixed. Well diagnosed @Robotorium !
I've put the old bobbin case in the threads box in case it's useful as a slightly inferior spare
