### ISSUE TITLE
Desktop extension on the desk near the coffee machine is broken

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1626]
It's been unplugged for a while, and @RussCoty and I PAT tested it this evening and it failed on its polarity test.

**Comment by magman2112** [comment]
On investigation, the back plate of this socket was broken. As it is hard plastic I tried glueing this at first, but this didn’t provide a strong enough joint. 

At the last Repair Cafe, I made an aluminium plate the same size as the back plate and used slightly longer self tapping screws to fix it in place. This is now much more rigid.

@amcewen re-tested the unit on the hack the space day and this unit now passes the PAT test.
