### ISSUE TITLE
Thermaltronics soldering iron has excessive leakage current

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1627]
The Thermaltronics soldering iron has failed its PAT test due to excessive leakage current.

**Comment by amcewen** [comment]
@RussCoty and @paulgeering have been investigating this more at maker night.  The mains filter has 0.75mA leakage current on its own, so seems the most-likely culprit.

We've ordered [a replacement filter](https://uk.farnell.com/schaffner/fn9222-3-06/filter-inlet-iec-3a-250vac/dp/2336598) from Farnell.

**Comment by amcewen** [comment]
The filter has arrived.  I've left it on the soldering iron for now.

**Comment by epsaul** [comment]
Derek and @epsaul fitted new filter. 
Note: L and N seem to be labelled oppositely on new filter to old but wired as per new. Spade crimped connectors in case it needs swapping.
