### ISSUE TITLE
Change of meeting room rooms, moving whiteboard & TV ?

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1631]
Hi all,

I think I understand that usage of the existing small meeting room is migrating to the room that was being used by Find Out Digital.

(This seems a great idea to me)

If this is the case could we think about moving the whiteboard and/or the display as these are both very useful - imho - for meetings.

What do you think?

**Comment by magman2112** [comment]
A whiteboard has now been installed in the small meeting room. I have also removed/tidied up the video cables to make things a little neater in this room.

I would suggest a wait and see attitude for the TV, as this may still be of use in its current location and @JackiePease agreed with this.

I will close this issue for now, as we can always re-open the issue if needed.

**Comment by ajlennon** [comment]
Brilliant thanks Mike !!!
