### ISSUE TITLE
Events room VOIP phone is not working

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1632]
The phone in the events room is not working properly.

It powers on, which suggests that is connected all the way through, as reported in #1531 it is then connected to port number 12 on the unifi switch. It then goes through some initialising steps and tries to get an IP address but ultimately fails.

I tried swapping it with the phone in the main room which confirmed that the phone works as it worked in the main room, and the main room phone failed in the events room. I then swapped them back.

I tried swapping for another cable which did not improve matters.

Port 12 on the switch is not now showing any issues.

I've then switched it to be plugged into port 7 on the switch which continued to not work, and also then plugged it back into port 12 but using a different patch cable.

Having tried everything else I'm guessing that it's the cabling that's at fault, especially given the potential issues listed in #1531. Next steps might be to try plugging the phone directly into the switch to confirm the switch ports definitely work and then to re-crimp the socket wiring to see if that fixes it.

**Comment by amcewen** [comment]
Plugging the phone direct into port 7 on the switch works fine.

It doesn't seem to work with either of the ports labelled PoE in the events room.  However, now that @ajlennon's bee-cam isn't running, I've temporarily stolen his PoE injector and the phone works with that, and one of the remaining non-PoE sockets.

I had a bit of a look for the network cable tester, but can't find it, so haven't done any  checking of the cabling...

**Comment by ajlennon** [comment]
:scream: that said there are (I think) a bunch of PoE injectors in the "power stuff" box?

**Comment by johnmckerrell** [comment]
Just a note that Alex has taken his PoE injector back. He plugged the phone back in and confirmed that it lit up but there's a decent chance it's not working and I forgot to check on Tuesday.

**Comment by ajlennon** [comment]
I am pretty certain there are more PoE injectors in the "box full of power stuff" ?

**Comment by ajlennon** [comment]
Oh I've said that  ! :laughing:

**Comment by amcewen** [comment]
You have :grin: but that hasn't magicked any PoE injectors into the boxes, at least not that I can find... :grinning:

**Comment by ajlennon** [comment]
Humm. Right then I shall have a hunt around here !

**Comment by ajlennon** [comment]
Had a try of the PoE injector I remembered being in the network stuff box but it doesn't work :(

**Comment by johnmckerrell** [comment]
I've re-patched the leftmost socket on that bank so that it's connected to the PoE switch and the phone is now working.
