### ISSUE TITLE
Save the focus-ruler files for Tony and Sheila somewhere-safe

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1636]
`Tony`'s focus ruler seems to keep going missing.  It'd be good to have the design files for it alongside the ones for `Gerald` and `Sophia`.  Similarly I don't think we've got one for `Sheila` either.

They should live in https://github.com/DoESLiverpool/somewhere-safe/tree/master/Workshop/LaserCut

**Comment by JackiePease** [comment]
I've copied an existing Tony ruler and saved it as Tony_Ruler.dxf (needed to be 14mm to include kerf)

**Comment by amcewen** [comment]
It's available in the [Just Add Sharks software download](https://cdn.shopify.com/s/files/1/2001/4065/files/Just_Add_Sharks_Software.zip?3431042237244346503) but I've saved the relevant file into [somewhere-safe/Workshop/LaserCut/Sheila_Ruler.dxf](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/LaserCut/Sheila_Ruler.dxf)
