### ISSUE TITLE
Blue 10m 4-way extension cable failed the polarity test

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1637]
The two outlets which have a pin obscured by the FAIL label have "open" rather than "good" polarity on the PAT test and so the whole extension has failed.

**Comment by magman2112** [comment]
I have disassembled the sockets on the extension lead and checked their polarity. The pins are actually connected by brass strips, so it is unlikely to be a polarity issue. 

I did though close up some of the contacts that had been forced open. @amcewen has re-tested the unit with the PAT tester and the unit now passes the test.
