### ISSUE TITLE
Doorbot on main door isn't recognising RFID tags

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#164]
Doorbot1 hasn't scanned any RFID tags since 9:30 yesterday.  The red LED illuminates on the reader, and the Pi is still up and running (have tried a reboot) but it doesn't recognise the tag.  Running the opendoor.sh script will unlock the door, so there's nothing wrong with that.

**Comment by DefProc** [comment]
It's now not reading anything because the power wire broke away from the
solder pad on the reader.

**Comment by amcewen** [comment]
I've been running through the doorbot-setup info, and fixing a number of issues with that, with the aim of getting the deployed software to match what we can recreate.

I've got an SD card which has been through the full doorbot-setup steps, including the newly added "install KWeb3, and configure the screen", but it's not recognising the RFID reader at present.  Not quite sure why, as I'm using the Pi and reader from the MFUKLC Registration Station, which works fine under Node-RED.

Once I work out the RFID reader issue, we can deploy it on a 512MB Pi and close issue #85 at the same time :-)

**Comment by madjake45** [comment]
@amcewen We had a few issues with the rcapp, which may be why it is no longer reading the RFID tags. Make sure you have tried rcapp0 and rcapp1, if they both don't work then the latest raspberry pi will need a new version built for it

**Comment by amcewen** [comment]
Yeah, had tried both rcapp0 and rcapp1.  I have rewritten it using the wiringPi library, but although that's happily talking to the RFID reader, it's getting weird values for some - but only some - of the card IDs :-/

**Comment by madjake45** [comment]
You got an example that I can look at? If not I could come in next week and
have a look as I remember messing with that for doorbot3

**Comment by madjake45** [comment]
Also trying to run "i2cdetect -y 1" if it is a rasp 2 will enable i2c as the latest version isn't in the blacklist it seems

**Comment by amcewen** [comment]
It's a Raspberry Pi B+.  i2cdetect was finding it fine, but rcapp wasn't working.  I've rewritten it *again*, using libbcm2835 rather than wiringPi, and that seems to be working nicely.  That code checked into https://github.com/DoESLiverpool/simple_sl030_rfid_reader

**Comment by amcewen** [comment]
Doorbot1 is now operational again.  I've rewired the RFID reader (so it'll hopefully be a bit more robust) and installed everything on a Rev2 Raspberry Pi Model B.
