### ISSUE TITLE
Buy some wall racks for vinyl rolls

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1646]
The vinyl rolls have been moved from a cardboard box to the cupboard at the back of the recess, but this still isn't ideal.

We previously discussed getting some specific wall-mounted racking for vinyl rolls. I can't find the original issue but [this racking from MDP](https://www.mdpsupplies.co.uk/wallrack) looks like it would do the job well. I think we'd want to store about 10 rolls of vinyl. It would be great if someone could check if the walls are suitable for something like this to be attached and which configuration would be best.

**Comment by Paul-PlasticModels** [comment]
Jackie Just thinking about this there is no need to buy any racks as they and be made very cheap with the laser cutter
![image](https://user-images.githubusercontent.com/95288753/149980120-7e161e10-48f5-4902-9005-30e0838dbcd4.png)

Laser cut the sides and broom handles to hold in place.

**Comment by JackiePease** [comment]
We did consider making one in the past (not sure we could make anything strong enough with the laser cutter but the CNC router might be an option).

It hasn't happened and they don't seem too bad value to buy. I've raised the issue so that people can check whether the wall is strong enough etc.

We do like to make stuff for ourselves though, so if you'd like to make a bespoke rack then get in touch or update this issue with your plans.
________________________________

**Comment by JackiePease** [comment]
@Sean-anotherone is going to spec these and then make them

**Comment by magman2112** [comment]
A new storage system using French Cleats has been installed, along with a new cabinet to store the vinyl rolls. This has eliminated the need for an alternate Vinyl storage system now I believe.
