### ISSUE TITLE
Decrease in quality/speed of Baltic Broadband since 2022

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1653]
The broadband speed provided by Baltic Broadband has decreased significantly. We are now being provided an internet connection comparable to a residential line, and in fact worse in some cases. Packet loss is now quite bad for me, and I would be happy to pay for the return of Gigabit and less congestion, if it is required, as I made quite good use of it.

cc: @johnmckerrell 

# 2022 
![image](https://user-images.githubusercontent.com/26458780/151057359-a284b150-4cfb-44bd-a936-da74c32b9cbe.png)
# 2021
![image](https://user-images.githubusercontent.com/26458780/151057450-f182b493-cf2f-47b0-b6e2-55637b6eba26.png)

**Comment by johnmckerrell** [comment]
I just ran a speed test on a Pi in the network cabinet, annoyingly the results are a bit too close to call, my 100MBps is better than yours but you would wonder if it's just not using gig-e:

```
   Speedtest by Ookla

     Server: Hyperoptic Limited - Manchester (id = 40628)
        ISP: Baltic Broadband Limited
    Latency:     7.38 ms   (0.83 ms jitter)
   Download:   104.58 Mbps (data used: 70.9 MB)
     Upload:    72.49 Mbps (data used: 123.2 MB)
```

I'll try to check on another Pi sometime. I looked on the unifi hardware but the "statistics" screen isn't loading properly right now (don't know if that's a sign!) There's updates available for all the hardware which I can install but not sure I should do it while people are using the network.

**Comment by amcewen** [comment]
I get similar results over WiFi just now:

![image](https://user-images.githubusercontent.com/108468/151176977-0183c1ba-c00e-44d3-8663-234d4944bcc9.png)

I have had slightly flaky Google hangouts over the past week (yesterday and last Wednesday, around 1:30/2pm each time)—I wasn't sure if that was just because I was downstairs but on the DoES WiFi, although I haven't had any problems in the past.

Will see how the call goes tomorrow too.

**Comment by johnmckerrell** [comment]
I've sent Baltic Broadband an email and I'll report back when they respond.

**Comment by MatthewCroughan** [comment]
I've tested again today with the same hardware/network, and these are the results. Good timing!

![image](https://user-images.githubusercontent.com/26458780/151283589-978ff8a9-2877-4a44-9a9a-ecf3fe1fb173.png)

**Comment by johnmckerrell** [comment]
Can anyone tell me the earliest date they noticed this? I have a report from Matt on the 21st, anyone want to say earlier?

**Comment by amcewen** [comment]
I can't remember if it was the Tuesday or Wednesday call last week, but (at least) one of those was troublesome, so that would be the 19th at the latest

**Comment by johnmckerrell** [comment]
I believe they’ve made an improvement if someone in the space could try it. From the sounds of things we are no longer on a hard fibre but are served by “radio” so that might be part of the reason we’re seeing a change. I’ll ask more about that when I confirm whether we’re seeing an improvement or not.

**Comment by amcewen** [comment]
As I arrived this morning two blokes from Baltic Broadband were packing away their ladder and getting into their van.

Running a test now I'm getting better results (this is over WiFi, so that might now be the limiting factor):
![image](https://user-images.githubusercontent.com/108468/151529011-b1b45162-8c3f-47f1-90b6-25245767b17f.png)

**Comment by amcewen** [comment]
And from a Pi4 plugged into Ethernet:
```
     Server: Hyperoptic Limited - Manchester (id = 40628)
        ISP: Baltic Broadband Limited
    Latency:     6.12 ms   (0.63 ms jitter)
   Download:   319.53 Mbps (data used: 382.4 MB )                               
     Upload:   477.08 Mbps (data used: 497.3 MB )                               
Packet Loss: Not available.
 Result URL: https://www.speedtest.net/result/c/c9242b29-0f5d-4863-830d-7fd69a3bd2fb
```

**Comment by johnmckerrell** [comment]
Aha, yes I was about to post similar, hopefully mine didn't overlap with yours!

```
   Speedtest by Ookla

     Server: Linix Ltd - Liverpool (id = 15553)
        ISP: Baltic Broadband Limited
    Latency:     8.36 ms   (0.76 ms jitter)
   Download:   268.84 Mbps (data used: 396.1 MB)
     Upload:   416.34 Mbps (data used: 755.8 MB)
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/4911d037-c1f2-4075-b880-f855519685c8
```

Definite improvement then.

**Comment by MatthewCroughan** [comment]
```
user: matthew swordfish in ~ via ❄️  impure (shell) 
❯ speedtest-cli
Retrieving speedtest.net configuration...
Testing from Baltic Broadband Limited (185.135.107.83)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Vodafone UK (Bracknell) [268.18 km]: 25.759 ms
Testing download speed................................................................................
Download: 328.22 Mbit/s
Testing upload speed......................................................................................................
Upload: 355.56 Mbit/s
```
Looks like it.

**Comment by amcewen** [comment]
Had my call today drop out a bit, and @pkharvey and Arkin did too on the downstairs network.

Running a speed test as soon as the call finished I got (over WiFi from downstairs, but on the DoES network):
![image](https://user-images.githubusercontent.com/108468/151990838-c0c230b5-5ee2-410a-b174-a7556ed9dc12.png)

And wired on the downstairs network:
6ms ping; 292.71 down and 266.35 up.
