### ISSUE TITLE
Tony's Y axis is reversed

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1655]
Yasmin was having issues this afternoon with the Y axis on Tony. It's moving the wrong direction (still useable if you take this into account).

**Comment by magman2112** [comment]
I investigated this issue this evening and Tony was indeed moving in the opposite direction on the Y axis. 

On checking the settings in Lightburn, I found one of the settings for Smoothieware clustering was set incorrectly for the firmware currently installed in Tony’s controller, this parameter should be set on.

I have no idea when this parameter has been changed, but on setting this correctly, the Y-axis behaved as it should.
