### ISSUE TITLE
Membership discounts aren't listed on the website

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1661]
At least, I can't find where they are.

https://doesliverpool.com/services/ says:
> All prices discounted with a [£10/month membership](https://doesliverpool.com/membership/)

And the membership page says:
> we also offer our Members reduced prices on all of our services

But apart from on the posters up in the space, I don't know where you'd find out what the discounts are...

I don't *think* we should be hiding them...? :grin:

**Comment by DoESsean** [comment]
Done.
