### ISSUE TITLE
Get Roland EGX-300 mill up and running

### ISSUE THREAD

**Issue by RussCoty** [DoESLiverpool/somebody-should#1665]
I have a couple of CNC machines on my desk. 

Where do people think they should live longterm?

Answers on a postcard to Pebble Mill. PO Box 55

**Comment by amcewen** [comment]
The small, "open air" one, I'm not sure what we should do with, particularly given that we've now got the bigger (but still quite small) enclosed Roland EGX-300 one.

Could the Roland one go next to the CNC lathe over in the corner by the laser-room?  We need to work out how to talk to it, and the rest of the commissioning process, but it seems a decent little machine.

**Comment by amcewen** [comment]
http://archive.fabacademy.org/2017/fablabkamplintfort/students/390/week13.html has some details on the CAM steps in Fusion360 for a Roland MDX40, which isn't the same, but might have some pointers for generating toolpaths for the EGX-300.

**Comment by amcewen** [comment]
@helicalbytes and @huffeec got it moving today!  We found that [the user manual](https://rolanddga.sharepoint.com/sites/dealers/SupportDocumentation/Forms/AllItems.aspx?id=%2Fsites%2Fdealers%2FSupportDocumentation%2FEGX300EN%5FUM%2Epdf&parent=%2Fsites%2Fdealers%2FSupportDocumentation&p=true&ga=1) includes the list of commands to talk to it

**Comment by amcewen** [comment]
I've not looked into it in detail, but [this software to convert GCode to HPGL](https://github.com/ozzyrob/cnc2hpgl/tree/master/C_Source) might be a useful starting point if nothing else for our CAM steps for this machine.

**Comment by huffeec** [comment]
With @helicalbytes we made some progress and managed to etch a 50mm square sending the following over serial
(Set serial port to 4800, 1 stop bit and Xon/Xoff parity.)

IN;SP1;PA30,47; VS40; PU0,0;PD0,0,5000,0,5000,5000,0,5000,0,0;

With Z0 set (cautiously) to -2300 and Z1 -100 Z2 200

**Comment by helicalbytes** [comment]
For the depth there are 3 values: Z0, Z1 and Z2.

Assuming you are working on a flat workpiece:

- Z0 is set so that the cutter is just touching the surface of the workpiece;

- Z1 is the cutting depth. It is set relative to Z0. So if Z1 = -100, this means 1mm below the surface.

- Z2 is the pen up height. It is relative to Z0. So if Z2 = 200, this means the cutter will be raised 2mm above the surface.

Z0 is set using the command !ZO-2300; etc. **Note that it is the spelling ZO**, where O is the letter "O", not the zero character.

**Comment by helicalbytes** [comment]
In general be very careful setting the machine's Z-height, especially when there is a cutter installed. The current bed has 4 posts for alignment which can get in the way of the cutter when it is for example, going to its x,y home position when the machine starts etc.

**Comment by Robotorium** [comment]
Had trouble downloading from the most recent link, so here is [another](https://www.rolanddga.com/support/products/engraving/egx-300-desktop-rotary-engraver)

**Comment by JackiePease** [comment]
Took another look at this today.
picocom -b 4800 /dev/ttyUSB0 useful to send from Linux
I'm trying to find out if anyone's converted one to run with GRBL

**Comment by helicalbytes** [comment]
Am going to close this.

It is still a WIP, but there is now a repo for code to interface from a Python web app (running locally) and the EGX-300.
https://github.com/DoESLiverpool/roland-egx300

The engraver itself seems to be in full working order.
