### ISSUE TITLE
Idea for a Jam Night

### ISSUE THREAD

**Issue by RussCoty** [DoESLiverpool/somebody-should#1666]
After some scheming with AJ Morrison, she has suggested that she would like to start a little jam night. 

We are thinking acoustic instruments, more of a music circle than a performance in front of an audience thing.

Any thoughts, ideas, interest let me or AJ know. I think she is currently signing up for GitHub so will be on here soon.

**Comment by epsaul** [comment]
Tonight?

**Comment by JackiePease** [comment]
Anne-Marie has been running this regularly and successfully on the last Friday of each month  https://www.instagram.com/p/CeI-5K0o01L/?igshid=YmMyMTA2M2Y=
Next one on 24 June
