### ISSUE TITLE
Pen plotter McGraw plotting wobbly lines when they should be smooth

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1667]
Lines drawn by the pen plotter have wobbles in them. These appear in the same position on each row, so it looks to be an issue with the setup, either dirt on the wheels, damage to the belts, problem with one of the stepper motors etc.

**Comment by JackiePease** [comment]
I cleaned all the bearings and tracks with IPA and replaced the 3 toothed belts on the top side (there are 2 underneath as well). I got 3 6.35mm x 1001.8mm MXL pitched belts from Beltingonline (Kesteron Ltd).
The lines produced by the plotter now do seem to be smoother.
However, there is some resistance to moving along the longer axis that wasn't there before. I am going to watch the Youtube video again to see if there are any points I missed (https://www.youtube.com/watch?v=jzn5mif5Ldo), but also happy for anyone else to take a look as well.
I also damaged one of the limit switches, so will order another.

**Comment by epsaul** [comment]
Worked on today fixed a few niggles. Watch out for arduino working loose. Dirt on the rollers produces regular "wobbles" at pitch of roller circumference.

**Comment by JackiePease** [comment]
![IMG_20220313_130252](https://user-images.githubusercontent.com/12802256/158060713-4149f082-718c-49d7-9e6d-4dcb18284875.jpg)
Here is an example of the original issue, for future diagnoses. 
Note: I didn't end up replacing the limit switch, as it worked well enough when reassembled
