### ISSUE TITLE
Extraction Problem

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1669]
Jade has been in the laser room today, and has reported an issue with the extraction - she said it was getting smoky in there and, though she tried to give the extraction system a hoover to clear anything out, nothing helped.

She said there's normally a filter in there which there doesn't seem to be at the moment. I assume the laser is still usable? Or should it be shut until this issue is sorted?

**Comment by RussCoty** [comment]
This sounds, if my instinct serves. Like it might be that the actual grill needs knocking clear on the fan housing. It has an array of little square holes that tends to get clogged every so often. 

The solution that I have found was to remove the hose form the fan input side and then push the buildup out with a brush. Vacuuming might work well too.

I may be about today to have a bash at that.

**Comment by amcewen** [comment]
Indeed, it was the mesh inside the extractor fan.

For future reference, it's the bit you can see here:

![DSC_0708](https://user-images.githubusercontent.com/108468/157237465-e1e7dfa4-ed56-4153-9748-ff9cea6e05cf.JPG)

You need to loosen the jubilee clip with a screwdriver, remove the hose, vacuum (or brush) out the buildup, then replace the hose and tighten up the jubilee clip again.
