### ISSUE TITLE
Jog keys not working since reinstall

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1674]
The number pad jog keys don't work, which mean we also can't do 'some modifiers' and 5

**Comment by amcewen** [comment]
If you log into the Kinetic-NC software as the `Client-Admin` (password is written on the monitor) then you can access the `Hotkeys...`option in the `Configuration` menu.

Then you can choose various operations and teach it which keys to use.

I've set the numpad arrow keys to do the jog movements (and the diagonals also make it move in X and Y appropriately — I can't remember if it did that before).  Numpad `5` raises the Z-axis and `shift`+`5` lowers it (I think that's the same way that it used to be).  And I've set `ctrl`+`shift`+`alt`+`numpad 5` to trigger the macro to zero the Z-axis with the puck.
