### ISSUE TITLE
Liverpool Makefest - 2 July 2022 - DoES Liverpool stand

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1676]
This is to list exhibits and things we need to get ready for Liverpool Makefest, which is on 2 July (please add your name to assignees if you want to help with organising).

@ka81 and Dan have been in touch to confirm we're included (!) and "will be in touch again with more information, risk assessments and probably a few questions as we go along"

**Comment by JackiePease** [comment]
List of display-related stuff to take with us:

    black tablecloths
    display triangles (need cable ties), or alternative
    printed descriptions for exhibits -- Snoof
    stands for descriptions -- Snoof
    vertical display unit (may need some new connecting pieces)
    business cards and flyers
    television to show promotional videos

**Comment by JackiePease** [comment]
List of exhibits (please add details of anything you want to display here):


- MCQN stuff (from Nikki) - My Baby's Got LED; My Bike's Got LED,Museum in a Box; Ackers Bell (Nikki has 
- Snoof - Wormbert
- Aeternum - Air quality sensor
- Sasha - TBA
- Jackie - Flowers, McGraw, Peloton lights?
- Terry - Penguin
- Brian - Subbuteo box
- Mike - Book Scanner, a couple of small synths, small keyboard and monitor speaker.
- Fred the Embroidery Machine (to display, or volunteer needed to operate)
- Phyl the Letter Press (to display only, unless lots of progress made)
- Baroness designs ??
- Emre and Fatih
- Poppy, Karen, Jackie - eco dress
- David R - sugar skull picture
- Paul H - Vintage computer e.g. Apple 2
- Megan - embroided jumper
-!Amy - to be determined

**Comment by JackiePease** [comment]
List of people who are able to help move stuff and set up our stand on Friday evening (please add your name and whether you can provide transport

Snoof (can't provide transport or carry stuff but can help with setting up)

Mike - I will be volunteering at MakeFest, helping set up on Friday, but I should be able to help after this. I should also be able to provide transport as well.

**Comment by JackiePease** [comment]
List of people who are able to help take down our stand and move everything back to DoES immediately after Makefest ends on Saturday (please add your name and whether you can provide transport)

**Comment by NikkiHiggins** [comment]
MCQN stuff: My Baby's Got LED; My Bike's Got LED; Museum in a Box; Ackers Bell. 

I might also be able to bring my shield project if it's finished, hopefully

**Comment by amcewen** [comment]
Aeternum would like to show off one (or two?) of their air quality sensors.

[I also edited the description to fix the date it's happening :-D]

**Comment by NikkiHiggins** [comment]
I  might also be bringing a shield and a wall hanging of my own projects if they are finished in time

**Comment by DoESsean** [comment]
> List of display-related stuff to take with us:
> 
> ```
> black tablecloths
> display triangles (need cable ties), or alternative
> printed descriptions for exhibits -- Snoof
> stands for descriptions -- Snoof
> vertical display unit (may need some new connecting pieces)
> business cards and flyers
> television to show promotional videos
> ```

I've ordered new business cards today, and also asked for a quote for more flyers, using the design from #1289  - I've used the hello@ email address so it can be picked up while I'm away.

**Comment by Robotorium** [comment]
I've sorted the description placards and stands but need the descriptions.
So if anyone wants to display something, drop me a note and I'll sort it
out. May need to cadge some wood though.

Op do 9 jun. 2022 14:59 schreef Seán Gleeson ***@***.***>:

**Comment by goatchurchprime** [comment]
I'll bring my TunnelVR.  (I've got 2 Quest headsets).  It would be great if we got another one with us, because I can network them.  We could also make a pointcloud scan of one of the rooms of the library with an iPhone Pro

**Comment by magman2112** [comment]
Closing this issue now, as MakeFest has passed.

**Comment by JackiePease** [comment]
@DoESsean has got the flyers. They're on the leaflets table if anyone wants to hand them out.
