### ISSUE TITLE
Lightburn failing to communicate with Tony, open files and lagging.

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1679]
A user came to me as they had several issues related to Tony and the use of Lightburn.  The only issue remaining is the laggy Windows and failure of Lightburn to recognise several files.  The system was restarted and this resolved most of these issues but lagging still remains.

I feel the background apps are causing lagging either viruses or excessive software running in the background.  I was wondering if the Administrator rights could be temporarily turned off or given to nominated people.  This would allow power user options and/ or install appropriate software to resolve this etc.

**Comment by JackiePease** [comment]
@Knottyashcreative - the admin password is accessible to organisers. You can ask one of the organisers next time you're in.

**Comment by JackiePease** [comment]
It looks like someone tried to run the update to version 1.1.03 on 11 April and wasn't able to (possibly because they didn't have the admin password).
I've installed the update and it seems to be working now.
I did have to skip one file: c;\ProgramFiles\Lightburn\LBShellExtThumbnailHandler.dll as the system kept saying it was in use, but that doesn't seem to be causing any issues.

**Comment by MatthewCroughan** [comment]
If these machines had been provisioned with Linux and built with reproducibility in mind, they would:

1. Not behave differently tomorrow
2. Not allow users to change the behavior of the system for other users
3. Not require as much maintenance

I don't have the time to do this anymore, but whenever I suggested it in the past year or two, I was shot down on many occasions. Maybe it's time to look at this option again, so we can have reliable, reproducible, known-good software configurations for the machines we own, which do not change without our collective knowledge?

For example, the code that defines the VinylCutter is here, and hasn't changed for 10 months, when I initially created it. It works the same as it ever did. The same is possible for all of our other machines.

https://github.com/DoESLiverpool/nixcfgs/tree/master/hosts/vinylcutter
