### ISSUE TITLE
The vac-former has excessive earth leakage current in use

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#168]
I've done a full power on check with the heating element, and it tripped the RCD after a couple of minutes. This is almost certainly a heating element with reduced insulation resistance (i.e. it's on the way out!). 

[Clarke & Co](http://crclarke.co.uk) do supply parts for older machines. And I'm told the heating element for our 917 model is `HR03` at £30. So I'm ordering one.

**Comment by DefProc** [comment]
Fitted, but the earth still tripped out in testing. Which mesans it's electrically noisy for another reason. I'll invesigate.

**Comment by DefProc** [comment]
As we've had little success with moving this forward in the last 18 months, and there hasn't been a good suggestion broached beyond "take another spur off the electrical supply with a higher rated RCD" (which carries some safety and testing extras that we're not currently set up for); would a replacement vac former (and selling this one) be a suitable alternative?

I did see this one today — [Vaquform](https://www.kickstarter.com/projects/vaquform/vaquform-the-worlds-first-digital-desktop-vacuum-f) — which looks like a nice alternative at first pass and at a little over £550 at todays prices, like something that we could afford from pledges. Delivery won't be before October (*caveat kickstarter*).

I can get the ball rolling, and say that I'd be willing to put in £100 for DoES to buy one. Any other interest?

**Comment by shrkey** [comment]
I'd be interested for another £100 - the forming area is a little small 304mm x 228mm but usable (even if have to tweak designs for multiple parts)

**Comment by ajlennon** [comment]
Dynamic Devices will chip in £100

**Comment by dazz-ling** [comment]
I'm in for £50

**Comment by DefProc** [comment]
Any more takers? the early bird rewards have all gone now, so it's up to £604 and November *expected* delivery. We're currently £254 short with 3 days to the close.

**Comment by DefProc** [comment]
This has now closed, and I know there's work currently going on with the vac former that we have. 

As we didn't have enough support in time, it's now over to pre-orders (currently the same price and time frame): https://www.vaquform.com/products/vaquform-desktop-vacuum-former

**Comment by amcewen** [comment]
@TheGimbalGuy had a look at it last week, and recrimped the connectors on the wires (and generally cleaned them up) running from the main case into the element hood.  Along with a bit more checking over of things, and didn't find any problems.

@paulgeering and I (but mostly Paul) then looked at it more on #makernight, and tracked down the earth leakage to the element itself.  Given that the element is new (well, hardly used ;-) it seems most likely to be a problem with the design of the mounting for the element.  It's held in with metal bolts and is also supported with a couple of metal hooks.  Presumably earth leakage was less of a problem when it was first built.

To get it working properly we'd either have to work out a way to insulate the element mounting, or build a completely different heater unit (maybe we can find a newer heater unit to fit in its place, for example?)

**Comment by amcewen** [comment]
If anyone wants to pursue the "let's buy a new one" approach instead, there are two different ones (both newer than ours, but I've not checked how specs compare otherwise) on ebay at the minute:

[A Formech 300 X in Blackburn](http://www.ebay.co.uk/itm/Formech-300-X-Vacuum-Former-Plastic-formers/172576921176?_trksid=p2047675.c100011.m1850&_trkparms=aid%3D222007%26algo%3DSIC.MBE%26ao%3D1%26asc%3D20140107083358%26meid%3D3b56c47f4b1c4b75925a8e82a378ea1a%26pid%3D100011%26rk%3D1%26rkt%3D2%26sd%3D172576814035) and [a CR Clarke 725 in Kingsbridge](http://www.ebay.co.uk/itm/cr-clarke-vacuum-former-725-/182495190715?hash=item2a7d8f9ebb:g:fq8AAOSw4A5Yzo6V)

**Comment by aubergine10** [comment]
Currently updating the wiki page for this machine and noticed this issue. I've emailed the manufacturer to see if they know any solutions to the problem, plus also requested any documentation they might have archived.

**Comment by aubergine10** [comment]
> Hi Guy
>  
> Thank you for your email, we discontinue this model some 20 years ago, don't have any information I can send on it sorry. The heating element was prone to absorb moisture when not used for a while, this would cause problems on pat testing or if connected to a sensitive RCD outlet. If you connect the machine to a non RCD outlet and run the heater for 5 minutes it would then be ok, we now use ceramic heaters. If you need a new element we can supply that still. 
>  
> If you need any further information please do not hesitate to contact us.
>  
> Regards Ian Rees
> Service & Technical  Department
>  
> C R Clarke & Co (UK) Limited
> Betws Industrial Park, Foundry Road, Ammanford, Carmarthenshire, United Kingdom, SA18 2LS
> Mob +44(0)7970382452
> Tel + 44(0)1269590536
> Fax + 44(0)1269590540
> Email   ian@crclarke.co.uk

**Comment by aubergine10** [comment]
I've emailed back asking if any of their ceramic heating elements would be compatible (maybe with some hacking) with the Model 917.

**Comment by aubergine10** [comment]
> Hi Guy
>  
> No the ceramic heater set up is very different, movement, wiring, power, it’s not compatible. The old style rod element is fixed with two brass fittings and a couple of strips to support it in the reflector. Best I can offer is a part change deal against a new machine.
> ![725flb 2](https://cloud.githubusercontent.com/assets/1386719/25810094/f3d064b8-3406-11e7-8fcd-d915d0a6c1e0.jpeg) 
> Regards Ian Rees
> Service & Technical  Department

**Comment by DoESsean** [comment]
Sweet, thanks for that Guy. I guess there's a conversation to be had then
around the vacuum former, how useful it is and whether it would warrant
spending the amount we would need to to get a new one.

**Comment by aubergine10** [comment]
Only uses I can think of are product packaging prototyping, and art.

We could potentially build one in-house for ~£400: [18"x18" box £104](http://www.ebay.co.uk/itm/18-X-18-Vacuum-Forming-Former-Thermoform-Plastic-Forming-Box-Machine-Table-/162504457465?hash=item25d6053cf9:g:oa4AAOSwYGFUtDTK) + [16"x16" IR heater £297](http://www.ebay.co.uk/itm/INFRARED-HEATERS-16-x-16-VACUUM-FORMER-THERMOFORMING-/272276068832?hash=item3f64eb19e0:g:izIAAOSwd0BVukZp).

**Comment by aubergine10** [comment]
Not sure what heat it kicks out, but could the IR heater from link above be used in a DIY reflow oven? If so, we could make two enclosures (vac former and reflow oven) and make the IR heater easily detachable so it can be placed on whichever base is being used at the time.

**Comment by euanwithersby** [comment]
Thanks for following that up. Don't forget model making (commercial and hobby), POS displays etc for uses. In my experience of having made my own vac-former, the commercial ones are better as they form a better seal, the vacuum works more reliably and the purpose built mechanism makes for a sharper forming.

**Comment by aubergine10** [comment]
> Don't forget model making (commercial and hobby), POS displays etc for uses.

I didn't realise that sort of stuff could be done with vac formers; maybe a portfolio of example projects (for all DoES machines?) would encourage greater use and experimentation.

Related: I've just stumbled upon [Kevo](http://www.creationhardware.com/kevo.html) - a tiny DIY vac former. The old [kickstarter video](https://youtu.be/cS-pt3WlwAo) showcases several uses for a vac former.

> In my experience of having made my own vac-former, the commercial ones are better as they form a better seal, the vacuum works more reliably and the purpose built mechanism makes for a sharper forming.

Are the designs for it online anywhere? I'm wondering if there would be merit to using a dedicated air pump (or two - for extra speed / functionality) to suck air out of the base and pump that same air in to the lid section to create an even stronger downwards pressure. It could be controlled by a microcontroller, thus allowing user to define what rate of pressure change to apply for example.

I'm not sure how viable it is, but part of my brain is imagining a single device that can be configured for use as either a vac former, a reflow oven, or a plastic curer.

**Comment by amcewen** [comment]
http://www.core77.com/posts/65910/The-Industrial-Design-Prototyping-Process-Part-3-Vacuum-Forming shows some stuff being vac formed (in preparation for laser-cutting).

I think we should measure up the hood unit and see if we can find a new heater that'll fit, then we can use the existing frame, vacuum, casing, control system...  We should be able to control a mains heater with the existing regulator, IIRC.

**Comment by aubergine10** [comment]
> .... shows some stuff being vac formed (in preparation for laser-cutting).

Love that!! A few vids like that linked at top of each equipment page would be really inspiring way to showcase what can be done with the machine. I've added a few to our vac former wiki page.

**Comment by euanwithersby** [comment]
Think @amcewen is right about looking at adapting the current housing somehow. It's the old issue of it doesn't get used because it's not working thus it doesn't get enough use to warrant a new one. Chicken and egg? I'll post a pic of my circa 1998 homemade version of the kevo

**Comment by DefProc** [comment]
The vacformer is now out of the workshop and in Dinky.

**Comment by DoESsean** [comment]
Is this something that we're still interested in having? If not, is it worth the space and effort to take it to the new building, or should we just leave it here?

**Comment by Sean-anotherone** [comment]
Looking theough this thread there may be more to the problem...  but, I found the item below, which, with some modifications to the machine lid can be physically made to fit and is _about_ the right power - if it is too big the outer ring can also be removed.

one of these for the shopping list, 

https://www.ransomspares.co.uk/parts/cookers-hobs/grill-element-belling-1900w/120730.htm

Looked across a couple of suppliers and this price is the best I found.

I'll do the mods to make it fit, someone else better wire it up (!)

**Comment by amcewen** [comment]
I've ordered one of those elements.  Should turn up in a few days.

**Comment by amcewen** [comment]
Turns out the spares place can't provide us with one of those elements as they're no longer available, so they've refunded us the money.

Any preferred alteratives, @Sean-anotherone?

**Comment by Sean-anotherone** [comment]
Oh bugger...  it took ages to find that one.
I'll search again.

Sean

    On Tuesday, 2 April 2019, 09:45:15 BST, Adrian McEwen <notifications@github.com> wrote:  
 
 
Turns out the spares place can't provide us with one of those elements as they're no longer available, so they've refunded us the money.

Any preferred alteratives, @Sean-anotherone?

**Comment by DoESsean** [comment]
The vac-former has been hidden away under a desk now for about 6 months, the point of which was to a) free up the space it was using for things that might work, and b) demonstrate that no-one actually realised.

In line with what has been discussed at community meetings, I'm putting a DNoD on it. If no-one has a workable proposal for actually getting it to be useful again, then it will be gotten rid of.

**Comment by johnrcassidy** [comment]
I reached out to CR Clarke via Twitter and also email (copied in hello@doesliverpool.com also).

Twitter thread is here (sort of) https://twitter.com/JohnCassidyGB/status/1164835225802723328

**Comment by johnrcassidy** [comment]
CR Clarkes response

https://twitter.com/Crclarkeandco/status/1164852862662455297

NOTE

The electrode / terminal that is slightly malformed should be placed in the vac-former in the left facing slot as you lift and open the top cover.

![2019-08-23 (1)](https://user-images.githubusercontent.com/40026555/63588366-3539dd00-c59e-11e9-9caa-4e104d2333e8.jpg)
![2019-08-23 (2)](https://user-images.githubusercontent.com/40026555/63588367-3539dd00-c59e-11e9-9e04-95860625b200.jpg)
![2019-08-23](https://user-images.githubusercontent.com/40026555/63588368-3539dd00-c59e-11e9-9f56-71b0169d1078.jpg)

**Comment by Sean-anotherone** [comment]
This is a complete wild-card proposal, but......

How about taking the nichrome & mica plates from a cheap toaster and rigging them side by side in the heater box - this could effect a fix for ~£10 plus some time to manufacture bracketry.  Toasters run at about 300W per "slice" based on the ratings on Amazon, so it might be necessary to do some rewinding of the wire to make sure it is delivering ... say 800W or so in one panel, but this isn't too difficult.

Another possible snag would be that some toasters have a double-sided element between the 2 slices, this would certainly need to be rewound or we would burn the paint off the enclosure.

Just a thought, but this might be a cheap and simple enough hack if an an element continues to elude.  As far as I'm aware, toasters are not susceptible to damp !

Any thoughts?

**Comment by amcewen** [comment]
Sounds like a decent plan @Sean-anotherone, but I cooked the existing element for 4 hours the other night and that *seems* to have improved matters (annoyingly I didn't measure the continuity before cooking, but there's no continuity now).

The element is back with the vac former, so I reckon we should try refitting it and see if that's done the trick, with the toaster dismantling as a plan B?

**Comment by jackie1050** [comment]
We moved the vac-former to Dinky, switched it on and turned up the heater dial. The on light came on but the heater didn't heat up.

**Comment by jackie1050** [comment]
@Sean-anotherone has done some further testing and the vac-former is still tripping out. 
I've posted to the Google Group in case anyone has a spare toaster as we might be able to use the element.

**Comment by amcewen** [comment]
There's the old DoES toaster on the bottom shelf of the racking by the toilets...

**Comment by amcewen** [comment]
Just noting that we turned someone away this week who wanted to come in and use the vacuum former.

**Comment by G0DUB** [comment]
@Sean-anotherone Last Thursday you were looking for a source of around 3m of high temperature wire - would this [ebay link](https://www.ebay.co.uk/itm/HIGH-TEMPERATURE-1-5mm-FIBREGLASS-WIRE-16AMP-APPLIANCE-CABLE-HIGH-TEMP-PER-METRE/221200802046?_trkparms=aid%3D1110006%26algo%3DHOMESPLICE.SIM%26ao%3D1%26asc%3D225075%26meid%3D4eb9188b462b4a33b3187130707d0a56%26pid%3D100005%26rk%3D2%26rkt%3D12%26mehot%3Dpf%26sd%3D321253128516%26itm%3D221200802046%26pmt%3D1%26noa%3D0%26pg%3D2047675%26algv%3DSimplAMLv5PairwiseWeb&_trksid=p2047675.c100005.m1851 ) meet the needs?

**Comment by Sean-anotherone** [comment]
Yes, but not with £10 postage!!

Sent from Yahoo Mail on Android 
 
  On Mon, 16 Mar 2020 at 1:19, Greg Mossop<notifications@github.com> wrote:   


@Sean-anotherone Last Thursday you were looking for a source of around 3m of high temperature wire - would this ebay link meet the needs?

**Comment by G0DUB** [comment]
I have just tried and postage was free through Royal Mail and £4.99 with a courier. The company being in Skelmersdale also offer pick up from the store if prearranged. 
Shall I get some and then figure out how to get it to you?

**Comment by Sean-anotherone** [comment]
Thanks Greg,. I did not click that it's only in Skem.  If you could provide a link to the address I'll head there before Thursday and pick some up, plus ask about the other few bits and pieces required. ( Some sleeving for the joins, etc.).  

Sent from Yahoo Mail on Android 
 
  On Tue, 17 Mar 2020 at 0:30, Greg Mossop<notifications@github.com> wrote:   


I have just tried and postage was free through Royal Mail and £4.99 with a courier. The company being in Skelmersdale also offer pick up from the store if prearranged.
Shall I get some and then figure out how to get it to you?

**Comment by G0DUB** [comment]
The web address is [https://catersparesuk.co.uk/](https://catersparesuk.co.uk/), office number 0169 551 815 and the physical address is;
CaterSpares UK
7 Witham Road
Skelmersdale
Lancashire
WN8 8HP

Just to repeat the caution from their website;
"COLLECTIONS

Buyers are welcome to pick up items in person from our unit if arranged first"
So a browse of the website may help to get a picking list to them first.

**Comment by JackiePease** [comment]
Another suggestion (from my Dad) is to look at elements for pottery kilns

**Comment by JackiePease** [comment]
Could @G0DUB or @Sean-anotherone record the exact type and number of items required from CaterSpares. Then I'll place an order.
Note: it doesn't look as though this option will allow clear plastic to be formed, but could be useful for recycled stuff.

**Comment by Sean-anotherone** [comment]
I think it's just 2m of mineral insulated cable - 10A would suffice, plus about 6" of ~10mm mineral sleeving (plan is to use the the "insides" from a couple of choccyblocks to make the connections, but they need to be covered by some sleeving that can take 2-300°C 
I think that's all it needs, plus a couple of hours.
There is of course some risk that these lamps won't work, but only one way to find out and the cost is probably under a tenner.
Sean-anotherone
    On Thursday, 4 June 2020, 19:02:39 BST, Jackie Pease <notifications@github.com> wrote:  
 
 


Could @G0DUB or @Sean-anotherone record the exact type and number of items required from CaterSpares. Then I'll place an order.
Note: it doesn't look as though this option will allow clear plastic to be formed, but could be useful for recycled stuff.

**Comment by JackiePease** [comment]
@Sean-anotherone has ordered the following parts, which should arrive on Monday:

high temperature 1.5mm fibreglass wire 16amp appliance cable high temp per meter - WHITE | 3 | £4.95
-- | -- | --
4mm BLACK HIGH TEMP SLEEVING COVER Used ON HIGH TEMPERATURE APPLIANCES PER METRE | 3 | £7.41
10MM BLACK HEAT RESISTANT SLEEVING CABLE WIRE HIGH TEMPERATURE  PER METER 500oC | 1 | £2.94

**Comment by JackiePease** [comment]
The new parts have arrived - they're on the table in the events room

**Comment by Sean-anotherone** [comment]
So...
The Vac former has been successfully retrofitted with three copier fuser lamps, and it is fully working ! :) It seems to get plenty hot enough in just a coupl;e of minutes.  A small repair was also needed to the hold-down frame to ensure a good seal, that's done too.  There seems to be no control over the power, so it will need to be controlled on time, and not used unattended, but with lamps instead of an element this  is actually better as they don't like running on reduced brightness - something to do with the halogen regeration cycle.

Some suitable thermoplastic material is now required to determine the "recipies" for successful vac forming.  

Did try briefly with the white sheeting, and some acetate, but both seem to have a very small "plastic" range - i.e. they are either not hot enough, or suddenly they are all holes and fully molten - unsuitable material.

My work here is done !

A suitable risk assessment and some training materials need to be worked up by someone who is familliar with actually using the machine, wheras I know how it works but have never used one.


Closing #168 - long overdue.
