### ISSUE TITLE
Buy new tips for the soldering iron

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1681]
Buy new tips for the soldering iron

**Comment by JackiePease** [comment]
Like #1483

**Comment by DoESsean** [comment]
I've bought exactly the same as last time, right down to doubling up to avoid having to pay postage.

**Comment by JackiePease** [comment]
@DoESsean - did these arrive?

**Comment by amcewen** [comment]
They did.  I threw away the old tips, and the new ones are in use.
