### ISSUE TITLE
Instagram Icon not working on front page of doesliverpool website 

### ISSUE THREAD

**Issue by NaliniMack** [DoESLiverpool/somebody-should#1685]
When clicking on the insta icon on the front page of the doe liverpool website a new web page pops up with the message stating - sorry thsi page isn't available. 

Be good to add all liks to social media in thsi spot such as - twitter and facebook.

**Comment by JackiePease** [comment]
Looks like this had stopped working because the password had been changed. 
Added new credentials and updated the Instagram Feed
