### ISSUE TITLE
Popup banner has broken

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1687]
I'm pretty sure (the events room is in use at the moment so I can't double-check) that the pop-up banner that's usually up in there explaining what DoES is has broken.

IIRC it's the clip that holds the banner onto the top of the pole that's broken, so we should be able to make a replacement so we can get it back into use.

**Comment by mickrick1** [comment]
Spare pole from Jackie's brother used to repair banner. 
Place top of pole into horizontal groove on top aluminium strip before extending fabric to full height then place bottom of pole through hole on base to secure.

**Comment by mickrick1** [comment]
Spare pole from Jackie's brother used to repair banner.
Place plastic top of pole into horizontal groove on top aluminium strip before extending fabric to full height then place bottom of pole through hole on base to secure.
