### ISSUE TITLE
Sophia's pump has failed

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#169]
Sophia died while someone was using it today. We found the fuse on the right by the kettle had blown, replaced with a similar 5A fuse and it blew again. Have not tried anything else.

A little debugging suggests it's the water pump that has died although further testing would be worthwhile.

**Comment by DefProc** [comment]
Yes, the pump motor has a crack in it. We'll need a replacement.

**Comment by DefProc** [comment]
Switched with Gerald's, which now has a chiller.
