### ISSUE TITLE
Make some shelving for letter press type

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1695]
Most of the letter press type is in small trays. Karen Edwards said that these shouldn't be stacked on top of each other as the type could get damaged. @amcewen has some scrap 4mm MDF that should be suitable for making shelves for the type. 

There might be something suitable on [https://www.festi.info/boxes.py/](https://www.festi.info/boxes.py/)

Related to #1693

**Comment by johnmckerrell** [comment]
Duplicate of #1694
