### ISSUE TITLE
Check Queen  Victoria is working ok

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1700]
Melodic were trying to print coloured coffee cards yesterday and these were coming out with a slightly stripey effect, as if one of the print heads was doing something slightly different in one direction than the other, there were also some excess black dots.

This was the first time anyone had tried using it with a Mac, so it might be worth testing with a Linux or Windows machine first  (I have the pdf).

**Comment by johnmckerrell** [comment]
Fwiw I used it with a mac in December and had no issues with colour. 

--

**Comment by JackiePease** [comment]
There was an issue with the driver on my laptop, but I tried this with a different file on one of the Lenovo laptops and the output looks fine. There are a lot of options under the advanced tab in printer properties to do with dithering, print quality etc. I suggested to Danny that he experimented with those. He's going to try again on Tuesday evening.

**Comment by JackiePease** [comment]
There haven't been any further issues, so closing.
