### ISSUE TITLE
PixMax heatpress attachments need investigation

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1701]
The PixMax heatpress has failed PAT testing again. It's also now in a state of advanced dismantlement. However, it has a bunch of attachments for hats/plates etc that could potentially be helpful for other heatpresses.

We need to investigate whether or not they are useable with other heatpresses, and dispose of them if not.

**Comment by JackiePease** [comment]
Someone (Brian?) was asking about this today. The attachments are really useful (we used them to do caps for Peloton for example).

**Comment by magman2112** [comment]
This was repaired at a Repair Cafe session a few months ago. The heavy duty wire to the Heat plate had a broken connection, so this was repaired and the unit safely passed it’s PAT test and has been back in use for a number of months.
