### ISSUE TITLE
Toilet seat broken in more accessible loo.

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1703]
The toilet seat in the more accessible loo is broken again. I'm struggling to stand long enough to investigate if it's a matter of relocating it somehow along the little axle, but it's currently loose on the wall side.

**Comment by johnmckerrell** [comment]
I fixed this yesterday. It's broken before but it's relatively easy to fix, just pushing the parts back together. I'll close this for now but if it seems like it's happening more often we can re-open and consider replacing.
