### ISSUE TITLE
Buy new milling bits for the Roland EGX-300

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1706]
The Roland engraving CNC came with some collets which gave the impression we could use bits from the other CNC.
Looking at this with @helicalbytes we've come to the conclusion that these collets are not the correct size, and wouldn't work even if they were.

Currently we only have an engraving bit for this machine. If we want to be able to mill/drill with it we will need additional bits and range in price from £15-50. 

They are available here;
https://www.techsoft.co.uk/products/millingroutingtoolsaccessories/de3e

**Comment by helicalbytes** [comment]
After more reading about the machine we (@helicalbytes and @huffeec) think that it is unsuited to 3d milling.

It does though look potentially excellent for pcb milling.

We think a good milling bit to get to test this out is available from techsoft (link in previous comment):

Part number: **TA-SD4-0.8**
Price: £27.
This is a 0.8 mm slot drill.

**Comment by helicalbytes** [comment]
I have ordered the TA-SD4-0.8. Will close this issue once it arrives.

**Comment by helicalbytes** [comment]
Slot drill has arrived now. Is stored with the engraver.
