### ISSUE TITLE
Get more blank sublimation mugs

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1707]
We're down to our last blank sublimation mug so we should order some more.

**Comment by amcewen** [comment]
I've ordered 36 from https://subliblanks.com/collections/sublimation-mugs/products/dino-coated-sublimation-10oz-mugs (also got a spray bottle to see if we can fit one of the pump dispensers from the handwash to it, and if so we can make some nice handwash dispensers for the toilets :grin:)

**Comment by JackiePease** [comment]
These were delivered
