### ISSUE TITLE
Refreshment stores should be organised and labelled to make sure people use them

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#171]
It would be organising the refreshments and then labelling the bottom of the cupboards so that it's clear to people where to get replacements from. We can then also improve signage for "please replace what you take".

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
I'm sure I'd seen a ticket or discussion about this recently - from vague memory there's a small patch of astroturf involved?

Also, are the cupboards not already labelled?

**Comment by DefProc** [comment]
I did add stickers to the cupboards in time for the first regular Jelly. But I'm not clear on the current arrangement for under-cupboard stores. @johnmckerrel is there a current best practice for locating stores?

**Comment by DoESsean** [comment]
I'm assuming that this will be addressed in the new space with better signage.

**Comment by DoESsean** [comment]
After discussion with @amcewen, it was suggested we cut some vinyl to go on the front of the fridge asking people to replace what they use. It would also cover the Stella logo.

The main issue is making sure that you can still see in the fridge.

**Comment by johnmckerrell** [comment]
Not sure seeing in matters all that much if it’s clear it’s a drinks fridge. I did wonder if you could scrape the Stella logo off. 

--

**Comment by DoESsean** [comment]
Unfortunately not - it doesn't seem to be a sticker of any kind either on the inside or outside of the door, looks like it's _in the glass_ somehow. Magic or something.

**Comment by DoESsean** [comment]
Another plan was to put labels at the back of the fridge so that once you took the last Coke or whatever, you'd see a little sign saying 'Replace Me!' or something. 

We're not sure how well they'd stay on though as the back of the fridge would obviously be wet.

**Comment by DoESsean** [comment]
Seems like this problem has solved itself to me. So I'll close this issue unless anyone has any objections.
