### ISSUE TITLE
Sheila not cutting

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1711]
The laser head is moving around the bed as normal, but the laser isn't firing. It looks as though it's an issue with the lid switch, but I can't see how to fix it.

**Comment by JackiePease** [comment]
Klara was using the laser cutter this morning and noticed that someone had switched off the cooler unit. She added a label to try to stop people doing this in future.
However, Sheila continued to cut out intermittently. Klara and a couple of other people have noticed that the cooler seems to be  running at 29C which is much higher than they're expecting.
I used the laser cutter this evening. It's worked so far and the cooler is reading 25C.
Wondering if there is still some issue with algae in the cooler unit.

**Comment by amcewen** [comment]
How warm was it in the laser room?  Sheila and Sophia's chillers can only cool to room temperature, so if it's too hot in the laser room then they won't get any cooler.

**Comment by JackiePease** [comment]
@johnmckerrell has lent us a thermometer to measure the room temperature. It currently says 23.34C. The chiller says 24C. The laser cutter works some of the time after being power cycled.

**Comment by JackiePease** [comment]
Tagging https://github.com/orgs/DoESLiverpool/teams/laser-maintenance

**Comment by JackiePease** [comment]
I think this is the lid switch. It wasn't working and I leant on the lid - it started engraving (half way through the engrave obvs)

**Comment by JackiePease** [comment]
There don't seem to have been any recent issues with the lid switch, so closing this
