### ISSUE TITLE
Organise a date for a Futuregazing session so we can work out where we might be going and what we want to do

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#1714]
Wondered if it would be good after another successful MakeFest that we get together and have a group chat about where we think DoES is going in the future or just reflect on things together. Have a look at the notes from our last session which I thought went really well and ended up with the [values document](https://docs.google.com/document/d/1ZO7byuEVA5RDQuoMtwomU2iu4wLDpV1-Oj06eAyrEMA/edit) that is now nicely printed in the space. Makefest is usually a chance to reflect on the strength of the community and think about what we all want from or for DoES. Sorry not to be there this year!

I'm happy to co-host or co-chair with anyone who is up for helping or im just happy to help set the date. Don't think we need do any kind of fancy building block exercise but maybe some kind of post it note warm up - open to ideas! 

Here's some dates, some on maker nights (good/bad idea to clash?) but nothing in event space on the calendar which we used last time?

Wednesday 13 July 2022 6-8pm
Thursday 14 July 2022 6-8pm (maker night)?
Saturday 23 July 2022 10.30-12.30pm
Wednesday 20th July 2022 6-8pm
Thursday 28 July 2022 6-8pm (maker night)?
Saturday 30 July 2022 10.30-12.30pm
Wednesday 3rd August 2022 6-8pm
Saturday 6th August 2022 10.30-12.30pm

There's a community meeting on Thurs 21 July at 1pm so don't know if theres overlap there; I think it should be its own event though and early evening or saturdays seem reasonably good days . 

https://github.com/DoESLiverpool/somebody-should/wiki/Future-Gazing-Notes

https://github.com/DoESLiverpool/somebody-should/wiki/Future-gazing-2019-07-28

cheers @cheapjack

**Comment by cheapjack** [comment]
Wednesday 10th August at 6pm suggested on the [google group thread](https://groups.google.com/g/does-liverpool/c/h0c-e2W6RHs) which would work for me and some of us I think?

**Comment by DoESsean** [comment]
Wednesday 10/8 has been nailed down, 6:30-8:30. There are posters and everything.

**Comment by amcewen** [comment]
Are posters still posters if they're hidden under some stuff on your desk @DoESsean?

**Comment by amcewen** [comment]
@JackiePease and I have put the posters up now.
