### ISSUE TITLE
Hinges on more accessible toilet door pulling away from door.

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1717]
The door to the more accessible toilet is falling off the top hinge and can't be closed effectively (it can from outside but not from inside, or not from inside by me specifically). Jackie tried to tighten the screws again, but it didn't work and the screws pulled out again immediately.

**Comment by JackiePease** [comment]
@arthurrowland and I rehung the door with added rawlplugs

**Comment by JackiePease** [comment]
This might not be a long term solution as the plugs compress the timber.
This Reddit post suggests dowels and filler:
https://www.reddit.com/r/HomeImprovement/comments/3jz1xp/door_hinges_and_wall_plugs/
