### ISSUE TITLE
Commission (or scrap) the Dell laptop

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#172]
In the workshop there's a black Dell Studio 1558 laptop that Richard donated.  I don't think it powers on, but that might just be a case of needing a new power switch - there are a couple of wires hanging out on the right which might just need a pushbutton soldering onto them?!?

Anyway, somebody should spend some time trying to get it up and running again.  If we get it working, we should wipe the hard-disk and reinstall a fresh copy of Windows 7, then maybe it could be a spare machine, or one to run the UP printers?

**Comment by ReddbridgeMark** [comment]
If this is still live, I'll might have a go a this when I have a few moments. Whereabouts in the workshop is this?

**Comment by amcewen** [comment]
If your interest is still live (given my tardy response :-) it's in the green crate on the bottom shelf of racking in the workshop.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
I'll see if I can locate the laptop when I do an inventory on Thursday.

**Comment by ajlennon** [comment]
@aubergine10 

When I was commissioning the other PCs for #356 I made an attempt at some notes on a standard software install base, with associated files which I think @amcewen has archived somewhere.

Might be worth taking a look at

https://github.com/DoESLiverpool/wiki/wiki/PC-Systems

**Comment by aubergine10** [comment]
I wasn't able to find the laptop last Thursday, will try again tomorrow.
