### ISSUE TITLE
Create black and white flyer to publicise latest Boost membership / general DoES Liverpool stuff

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1723]
We need an A5 flyer to print and hand out at Granby St Market on 3rd September, and to have a few copies at Melodic Distraction etc., with an introduction to DoES Liverpool in general, details of weekly Maker Nights and Monthly Maker Day and our [Boost membership scheme](https://doesliverpool.com/co-working/launching-the-october-2022-boost-membership/).

Note: closing date for next Boost membership tranche is 11:59pm on 11th September. 

@zarino are you able to look at this?

**Comment by zarino** [comment]
@JackiePease I won’t have time to do this.

**Comment by JackiePease** [comment]
Thanks for getting back to meOn 27 Aug 2022 17:39, Zarino Zappia ***@***.***> wrote:

@JackiePease I won’t have time to do this.

**Comment by JackiePease** [comment]
I created a simple flyer with some Boost membership details on one side and monthly events on the other. Copied to somewhere-safe/Promo/Flyers/Granby_St_Flyer.doc - may be adaptable for other events.
