### ISSUE TITLE
Queen Victoria cutting off prints

### ISSUE THREAD

**Issue by NikkiHiggins** [DoESLiverpool/somebody-should#1724]
Occasionally while trying to print things on Queen Victoria the print will stop printing and cut off part of the image. 

This doesn't seem to be an issue with the program as it has happened across multiple programs. I don't know why it's happening as nothing appears to be wrong with either the printer or the image. 
![20220901_135402](https://user-images.githubusercontent.com/103120996/187918959-e0a4d17e-4d57-456e-ae93-b1685b74393e.jpg)

**Comment by Robotorium** [comment]
This also happened to me twice yesterday (or maybe a different day, my
grasp on time is a bit casual atm). From ubuntu, once from document viewer
and once from gimp.

Op do 1 sep. 2022 13:56 schreef Nikki Higgins ***@***.***>:

**Comment by Robotorium** [comment]
There was a theory that it might've been caused by some arsery around the black cartridge being empty, but this was not the case. I just tried again and it cut off even earlier than before (printed about 20cm of an A0 size print, then the print head wibbled a little bit on one side for about 10 minutes, then the printer proclaimed itself/the print to be "Ready"). No error messages, no indication of anything gone or going wrong.

**Comment by amcewen** [comment]
This isn't a suggestion to directly fix the issue, but an alternative approach could be to work out how to use the new large-format printer (see #1728) in case that doesn't have the same problem...

**Comment by Robotorium** [comment]
That's a great idea, thanks Adrian!

I did also download the manual for Queen Vic, or the printer I got drivers for which I think is very slightly different. I found this:

_Output contains only a partial print
• Did you press Cancel or Form Feed and Cut before all the data was received by the printer? 
If so, you have ended the data transmission and will have to print the page again (you normally don’t need to 
press Form Feed and Cut to unload the print).
• The I/O Setup > I/O Timeout setting may be too short. From the front-panel menu you can increase the 
I/O Timeout setting to a longer period and then send the print again.
• The file may be too large for the printer’s memory.
Select Send Job as a Bitmap in the driver’s Troubleshooting menu (Services tab). This may slow down print 
speed. Alternatively, you can install extra memory on the HP-GL/2 Accessory Card in your printer, see 
Memory.
• There may be a communications problem between your computer and the printer. 
Check your interface cable.
• Check to make sure that your software settings are correct for your current page size (for example, long-axis 
prints)._ 

I'll have a noodle with her tomorrow.

**Comment by magman2112** [comment]
Just in case it is a memory issue, I did some quick checks. The standard memory is 160Mb, which is what is currently installed in the printer.

An upgrade of 256Mb is possible (up to a total 416Mb). This is in the form of an SODIMM memory module which is a 200 pin module with a specification of PC2700 DDR333. I found some secondhand modules on eBay, as follows 

https://www.ebay.co.uk/itm/123417058263

At £4.99 including shipping, this might be a good option anyway.

**Comment by Robotorium** [comment]
I increased i/o time to 20 minutes from 10, didn't make any difference.
The file size doesn't appear to make a difference either; she's done this on files that were very simple lines and on reasonably high-res photographs.
I'm going to try and find my cable that matches hers and see if that does the trick/the cable is faulty.

**Comment by Robotorium** [comment]
Jackie brought me an alternative cable, but no luck. I think our best bet is to have a look at the RAM next, but not sure where to start without risking a Snoofastrophe.

**Comment by amcewen** [comment]
I've ordered the memory module that @magman2112 mentioned above.  Should be with us by Wednesday.

**Comment by Robotorium** [comment]
@amcewen brought me the memory module, it's on my desk in the drawer marked "nonsense." @magman2112 would you have time to work on this on Thursday night? I'd love to tag along and maybe learn something useful if possible.

**Comment by Robotorium** [comment]
Sorry, drawer marked *rubbish*

**Comment by Robotorium** [comment]
@huffeec put the new RAM in, I verified it had installed properly, but unfortunately the same problem persists.

**Comment by huffeec** [comment]
The belt is very frayed and shedding fibres into the machine. This seems to be the cause of paper jams and might in part explain inconsistent printing. 
![20221117_212521](https://user-images.githubusercontent.com/4748179/202580529-7f487b23-da9c-44dc-bb32-6c830e7efb1d.jpg)

**Comment by JackiePease** [comment]
I've ordered a new belt from Amazon for £16.99. It should be here on Tuesday 13th December.

**Comment by huffeec** [comment]
The service manual is here [https://www.laserexpressinc.com/manuals/HP/hp-dsj-500-510-800-series-service-manual.pdf](https://www.laserexpressinc.com/manuals/HP/hp-dsj-500-510-800-series-service-manual.pdf)
and there is a fairly comprehensive video showing the belt replacement process [https://www.dailymotion.com/video/x18j9cp](https://www.dailymotion.com/video/x18j9cp)

**Comment by JackiePease** [comment]
The belt has arrived - I've taped it to the top of the printer until someone has a chance to fit it.

**Comment by JackiePease** [comment]
@Sean-anotherone has now changed the belt and Jeri was able to print out a complete pattern page (using Windows)
