### ISSUE TITLE
Create a shelf unit for test equipment on the worktop beside soldering bench

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/somebody-should#1725]
The section of worktop to the left of the soldering bench is currently covered with oscilloscopes, power supplies and various other miscellaneous equipment. It is therefore unusable.

It is relatively deep -- about 90cm (3ft).

The proposal is to build a shelf unit on top of the worktop about 40cm deep to hold the test equipment. This would be for both storage **and use** of units like oscilloscopes. I'm thinking of 2 shelves.

The space would then become usable as an electronics test bench.

Any comments?

**Comment by amcewen** [comment]
Sounds like a great idea.

**Comment by magman2112** [comment]
Mike Rush gave me a shelf unit that he found that I have now brought into DoES and fits well in the space under the Test Equipment unit.

@JackiePease has organised most of the power supply test equipment into this unit.

**Comment by amcewen** [comment]
@helicalbytes and @magman2112 did an excellent job of this at the Hack the Space day.  Looking much nicer round that part of the workshop now!
