### ISSUE TITLE
Blue heat press (name pending) 

### ISSUE THREAD

**Issue by ajmorri** [DoESLiverpool/somebody-should#1726]
Hello! 

Just raising as an issue that the blue heat press is not heating up when switched on. It would be appreciated if this could be looked at when possible. 

Many thanks 
Anne-Marie

**Comment by magman2112** [comment]
I checked the unit out and found a broken connection to the heat plate at the heat plate end. The broken connector was replaced and the unit reassembled and tested.

All working OK now.
