### ISSUE TITLE
Order more cartridges for Queen Victoria.

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1727]
Nalini changed the black ink cartridge on Queen Victoria, and found there was only a half cartridge of black ink left (which is now in the printer). 

I've had a nosey around and I found https://www.stinkyinkshop.co.uk/hp/ink-cartridges/hp-designjet-510 referenced by Arthur somewhere in a thread about the pricing. Can we please order more of the black ones? We have one each of the cyan, magenta and yellow.

**Comment by DoESsean** [comment]
Ordered that now.

**Comment by JackiePease** [comment]
This has arrived. I've put it by the printer, with the other cartridges

**Comment by huffeec** [comment]
The magenta ink had run out I have replaced it with a compatible 82 ink from LCL https://github.com/DoESLiverpool/somebody-should/issues/1727 I also got other replacements for black and cyan, these are in the stationary cupboard

[HP no longer produce branded cartridges for this machine.](https://www.hp.com/gb-en/printers/large-format/designjet-supplies-discontinuance.html)
