### ISSUE TITLE
Fred in need(le)

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1729]
Please can we buy some needles for Fred? The last one has just been installed (I think he only came with a couple of spares).

https://www.tysew.co.uk/parts-accessories/needles/schmetz-embroidery-needles-assorted-sizes-75-90?search=Embroidery%20needles has a pack with the two most common types, if we could get that it would probably see us through a nice long while.

**Comment by DoESsean** [comment]
I'll have a look in Abakhan today - paying postage for needles given where we are seems a bit daft!

**Comment by Robotorium** [comment]
Just make sure they're machine embroidery needles please!

Op di 20 sep. 2022 09:49 schreef Seán Gleeson ***@***.***>:

**Comment by DoESsean** [comment]
None in Abakhan, so I've ordered those.

**Comment by Robotorium** [comment]
Cheers Seán!

Op di 20 sep. 2022 12:16 schreef Seán Gleeson ***@***.***>:

**Comment by JackiePease** [comment]
@Robotorium did these arrive?

**Comment by JackiePease** [comment]
These did arrive

**Comment by Robotorium** [comment]
Where did we store these please? I've removed a broken needle from Fred but can't find the replacements (or rather, am looking in all the wrong places)

**Comment by JackiePease** [comment]
They were in the marked drawer in the plastic drawers. Have they all been used?
________________________________

**Comment by JackiePease** [comment]
There was one left, which I've used in the machine. I'll order more tomorrow.

**Comment by JackiePease** [comment]
I've ordered 4 packs of new needles from the above supplier

**Comment by JackiePease** [comment]
@snoof @DoESsean Did the new needles arrive?

**Comment by JackiePease** [comment]
Needles have arrived. I've put them in one of the small drawers and added a label
