### ISSUE TITLE
Fatih reports that line engraving on Tony is inconsistent

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1735]
Line engraving at 15% and getting different depths.

**Comment by JackiePease** [comment]
![IMG_20221103_184318](https://user-images.githubusercontent.com/12802256/199808424-0ba50eb6-f8f5-4e19-ad22-d9d9f8cf4e1f.jpg)

**Comment by magman2112** [comment]
I found a significant mis-alignment of the laser mechanism. See issue #1737 for how this was resolved.
