### ISSUE TITLE
Tony not cutting through 3mm ply

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1737]
Report from the workshop booking this afternoon that Tony wasn't able to cut through 3mm ply using 15/80
The lines seem fairly sharp so don't think it's an alignment issue, possibly the optics needs cleaning?

**Comment by magman2112** [comment]
I investigated this on Maker Night and found that the lens was a little dirty, but not to the extent as was being indicated by the poor cutting. Further investigation found that the laser alignment was off with the final mirror and subsequently it was found that the main laser rail was out of alignment by approx 30mm front to back. 

Once this was re-aligned, laser operation returned to normal.

We do need to buy at least one new lens for Tony though, as we are very dependant on the one lens we have at present. I will raise this as a separate issue.
