### ISSUE TITLE
One of the sockets in the kitchen isn't working

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1739]
The socket that the kettle used to be plugged into is not providing any power.  The on/off switch also seems stuck in the on position for it.

We've moved the kettle to one of the nearby, still-working sockets and taped over the non-working one, but we should get the electrician to have a look at it sometime.

**Comment by JackiePease** [comment]
The socket that the microwave was plugged in to isn't working either (moved the microwave to the next socket)

**Comment by johnmckerrell** [comment]
One of these was fixed today but the electrician didn't have another spare so he will do the other one on a later visit when he also claims he will fix #1050

**Comment by JackiePease** [comment]
Mick has replaced this
