### ISSUE TITLE
Lazer not firing on Tony

### ISSUE THREAD

**Issue by Rorydasilva** [DoESLiverpool/somebody-should#1740]
Booked to use Tony this afternoon but not able to engrave anything. When setting up to cut, lightburn will run thr programme and the lazer arm moves but no lazer is fired. 

All setting correct in lightburn so think there is an issue with Tony, maybe a fuse out or something?

**Comment by magman2112** [comment]
I found a mis-alignment on the laser mechanism, see issue #1737 to see how this was resolved.
