### ISSUE TITLE
Gerald will not cut

### ISSUE THREAD

**Issue by SColley91** [DoESLiverpool/somebody-should#1741]
When I tried to cut with Gerald, it would follow the outline of the selected object but it would not cut.

**Comment by magman2112** [comment]
I found some alignment issues that need some further adjustment. It appears that there some adjustments to the laser tube mounts needed to correct this.

Unfortunately, there was a Plastic Tactics workshop taking place when I found the issue, so I can't proceed further as I need the laser room to be cleared to complete the alignment (laser safety).

I will try to call in during the week to try again.

@DoESLiverpool/laser-maintenance

**Comment by magman2112** [comment]
I had another attempt at adjusting the laser on Gerald. I found some issues with the laser tube mounting which I have now fixed. 

I was in the process of re-aligning the laser when I found that the was a poor contact on the IEC Mains Input socket to Gerald. Eventually this failed completely, stopping any further work on Gerald. I have some spare sockets at home which I will bring in on Thursday, then we can fix this issue and proceed with the laser alignment.

**Comment by magman2112** [comment]
I obtained a replacement IEC socket from Amazon, which was installed by @Sean-anotherone. We then did a full alignment on Gerald and it is cutting well at the moment.

closing this issue as there is another issue open for any other problems with Gerald.
