### ISSUE TITLE
Can we please rehome some chairs?

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1743]
There are a lot of chairs in the fibre arts room. They block the walkways and cause a lot of problems. Today, one of the lucite ones (which are also prone to cracking and don't seem very safe to sit on) got stuck on my wheelchair's anti tipper and I had to text @huffeec in the main room to come free me.

They block access to the table. Currently sitting here and there are six chairs around it, four of which would need to be moved to make sure the cutting mats can be used to their fullest. There are 3 further chairs, which aren't currently at the table. In order for someone to move the chairs so they have full access to the cutting mats, they have no other choice but to make the room inaccessible to others.

Obviously there may be times when we need more chairs in here, but I'm pretty sure there are more than enough chairs in the main space that can be brought in if that happens. In the meantime I can't get around the table without knocking into things/being ensnared by a carnivorous chair/getting stuck, and anyone wanting to use the table has to move chairs around first to make sure they have the access they need/want.

**Comment by JackiePease** [comment]
I've moved the 2 broken Lucite (acrylic) chairs to by the free stuff, and will leave them there for a couple of weeks in case anyone has any ideas for the frames.

I've put the others (5) in Dinky. They're nice looking chairs, but I agree we should dispose of them if we have any more issues.

________________________________
From: Snoof ***@***.***>
Sent: 07 December 2022 15:31
To: DoESLiverpool/somebody-should ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DoESLiverpool/somebody-should] Can we please rehome some chairs? (Issue #1743)


There are a lot of chairs in the fibre arts room. They block the walkways and cause a lot of problems. Today, one of the lucite ones (which are also prone to cracking and don't seem very safe to sit on) got stuck on my wheelchair's anti tipper and I had to text @huffeec<https://github.com/huffeec> in the main room to come free me.

They block access to the table. Currently sitting here and there are six chairs around it, four of which would need to be moved to make sure the cutting mats can be used to their fullest. There are 3 further chairs, which aren't currently at the table. In order for someone to move the chairs so they have full access to the cutting mats, they have no other choice but to make the room inaccessible to others.

Obviously there may be times when we need more chairs in here, but I'm pretty sure there are more than enough chairs in the main space that can be brought in if that happens. In the meantime I can't get around the table without knocking into things/being ensnared by a carnivorous chair/getting stuck, and anyone wanting to use the table has to move chairs around first to make sure they have the access they need/want.

**Comment by Robotorium** [comment]
Thanks Jackie, sounds good.
