### ISSUE TITLE
Tony randomly lost power while cutting

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1747]
I was cutting (a lot of) holes in a sweet tub lid. Tony lost some power and  stopped cutting all the way through but then went back to full power later in the cut.

**Comment by amcewen** [comment]
Is this a different bug than #1742?  (They just sound similar...)

**Comment by magman2112** [comment]
This has been superseded by #1774. The latest issue appears to be a faulty laser power supply, which could have caused the fault in this issue as the PSU was failing.
