### ISSUE TITLE
Felicity (Ultimaker 2) does not extrude

### ISSUE THREAD

**Issue by rah2501** [DoESLiverpool/somebody-should#1750]
When starting a print, the bed and nozzle warmed up, the print head moved around as though printing but no plastic extruded.  I tried to "move material" in the maintenance menu but nothing happened.  I took the filament pipe out of the top of the print head and the end looked unhealthy so I chopped it off (at an angle) and put it back in.  The manual "move material" worked up to the point where the filament went into the nozzle but no more.  No extruding.  I gave up at this point.

**Comment by huffeec** [comment]
This printer still had the original, or at least [original style](https://www.dream3d.co.uk/product/ultimaker-2-hot-end-pack/) hot end block with integral nozzle. With @amcewen and @helicalbytes we swapped in the old block from Prints Adam so it's got a less grotty looking nozzle. It will need a bed level before printing but should extrude better now.
Longer term there is a case for upgrading to an [Olsson block](https://uk.rs-online.com/web/p/3d-printer-parts/1101981?cm_mmc=UK-PLA-DS3A-_-google-_-CSS_UK_EN_Computing_%26_Peripherals_Whoop-_-3D+Printer+Parts_Whoop-_-1101981&matchtype=&pla-337733782523) like Prints Adam has to make nozzle changing easier in the future.

**Comment by huffeec** [comment]
Levelled the bed and tried a print. It's functional but will need further cleaning or a new nozzle before we get good quality prints.

**Comment by huffeec** [comment]
Covered in #1813 and #1815
