### ISSUE TITLE
Power lead to the kitchen bin works intermittently

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1751]
Sometimes the robot bin in the kitchen doesn't open.  Fiddling with the power connector (more the lead near the connector end I think) often remedies things for a bit, but it tends to fail again pretty quickly.

**Comment by amcewen** [comment]
@johnmckerrell, you should check [this comment](https://github.com/DoESLiverpool/somebody-should/issues/806#issuecomment-520414017) from *checks notes* @johnmckerrell about where we got the last extensions for it :grinning:

**Comment by zarino** [comment]
This is going to sound very boring, but before we spend any more money on electrical shenangans, shouldn’t we consider replacing the bin with something simpler, perhaps pedal-operated, so we never have this problem again? How much more would that cost? Would it be worth it?

**Comment by amcewen** [comment]
I don't have any strong opinions for/against the electric bin, but in the interests of avoiding bikeshedding, and as it's only a few quid I've bought:

* [A 2.1mm right-angle adapter](https://www.ebay.co.uk/itm/384482706486) to alleviate the strain on the cable (for £2.30)
* Another [1.5mm extension](https://uk.farnell.com/multicomp/jr8306-1-5m/power-cord-barrel-plug-jack-1/dp/1209175)

It was £8 in total.

**Comment by amcewen** [comment]
Parts arrived and have been fitted.  For some reason Farnell decided to send two of the extension cables, so I've put the spare into the "DoES infrastructure" box on the racking for safe-keeping.
