### ISSUE TITLE
Add the DoES Liverpool Mastodon account to the main website

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1757]
Now that DoES has its own Mastodon account - https://does.social/@DoESLiverpool - we need to link to it from the website, including the `rel="me"` microformat to indicate that this is our official account. I had a look but unfortunately the theme we're using doesn't support Mastodon in its existing list of socials so we will probably need to modify the theme? I'm hoping @willcrobinson can advise.

**Comment by willcrobinson** [comment]
Hi John, the theme that the DoES website uses is using an older version of FontAwesome that doesn't have the Mastodon icon. To get around this, I've added the SVG into the HTML directly. The rel=me attribute is in place now.

**Comment by johnmckerrell** [comment]
Great, thanks, showing as verified now I've edited the link.
