### ISSUE TITLE
Impy/Bernie maintenance

### ISSUE THREAD

**Issue by Justcantstopmakingstuff** [DoESLiverpool/somebody-should#1758]
Both overlockers could do with a service, cleaning, oiling etc. and Impy requires a new blade. 

I'm happy to do the cleaning of both machines but full service needs someone who knows more.

**Comment by Robotorium** [comment]
Jackie is taking the machines to Liverpool Sewing Machines this weekend. The service should take about a week.

**Comment by JackiePease** [comment]
I took the overlockers down to Liverpool Sewing Machines on Saturday. @Knottyashcreative went down to see Emma later and got some useful information on regular maintenance - hopefully will be updating the wiki ;-) 
@Justcantstopmakingstuff is going to collect the machines tomorrow

**Comment by amcewen** [comment]
This has happened, right?  Can we close the issue now?
