### ISSUE TITLE
Bernie died

### ISSUE THREAD

**Issue by Justcantstopmakingstuff** [DoESLiverpool/somebody-should#1759]
Unfortunately my request for a service for our Bernie was too late. The belt has gone so the motor runs but doesn't move the needles. Would love if someone could fix our Bernie :'(

**Comment by Robotorium** [comment]
Bernie (and Impy) is going for a full service at Liverpool Sewing Machines this weekend. Bernie will also be fitted with a new belt in the course of the service.

**Comment by amcewen** [comment]
Is this fixed now?
