### ISSUE TITLE
somebody should fix the broken strip light in the main room

### ISSUE THREAD

**Issue by mdunschen** [DoESLiverpool/somebody-should#176]
It is the one that flickers, in a set of 4 one is working, two are off permanently and one if flickering randomly.

**Comment by johnmckerrell** [comment]
Someone needs to report this to Gostins reception and report back here when it's done.

**Comment by amcewen** [comment]
I haven't reported it to reception, but @mdunschen and I applied a temporary fix just now - we dropped the flickering tube onto the diffuser, so it's no longer connected.  But care needs to be taken whenever the diffuser is removed as there's now a tube resting on it :-)

For whoever reports it to reception, there are four tubes in total in the main room which aren't working at the minute.

**Comment by johnmckerrell** [comment]
Adrian reported it to reception, Dave should be coming to replace them early tomorrow morning, I've left a fob marked "DoES Maintenance" with Sandy on reception. Obviously we need to get that back!

**Comment by DoESsean** [comment]
I had mentioned it to them on Tuesday and was told Dave would come and take
a look. I've told them that we have four lights out at the minute, so
hopefully they'll all get replaced.

**Comment by johnmckerrell** [comment]
Maintenance have been in and replaced tubes. There's still one out but I think that's more permanent problem.
