### ISSUE TITLE
Light switch in the less-accessible toilet isn't working

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1763]
It feels to me like the switch itself has failed, rather than the light (or extractor).

Luckily it's the toilet with the window, so it's mostly still usable, but we should get Mick to fix it when he comes back to fix #1739.

**Comment by johnmckerrell** [comment]
I've emailed Mick.

**Comment by amcewen** [comment]
Mick (I assume) replaced the switch the other day, and this is working again now.
