### ISSUE TITLE
Temp errors with the reflow oven

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1765]
The oven running on the new firmware doesn't seem to follow temperature profiles accurately.
Using an external temperature probe it seems that it there is a lag of up to 40 degrees.

Would benefit from the [cold junction compensation mod](https://github.com/UnifiedEngineering/T-962-improvements/wiki) described.

For now using F3 'Bake/manual mode' is the workaround. 

Set the first temperature point on the profile and hold it for 30 seconds to allow the actual temp to rise.
Then set the peak profile temp and a hold time of ~60s
Let then oven cool

**Comment by huffeec** [comment]
I've ordered a DS18B20 sensor for this mod.

**Comment by huffeec** [comment]
Fitted the sensor using [these instructions](https://github.com/UnifiedEngineering/T-962-improvements) with a 4k7 pull up. This is giving plausible readings.

The final step is to [calibrate](https://github.com/UnifiedEngineering/T-962-improvements/wiki/calibration) , setting left/right gain/offset values. With @amcewen and @helicalbytes we made some progress. The next job is to [collect some data](https://gist.github.com/aep/03db148e01796316018ca241f6825d88) and then try and work out what it means.

'Manual' reflow as described above is still the best approach for now.

**Comment by helicalbytes** [comment]
Serial port on the ISP connector on the reflow oven board has a baud rate of 115200.
Powering on gives the following output:
```

T-962-controller open source firmware (v0.5.2)

See https://github.com/UnifiedEngineering/T-962-improvement for more details.

Initializing improved reflow oven...
Reset reason(s): [POR][EXTR][BODR]
Running on an LPC2134(/01) rev F
Waiting for keys to be released... Done!
Buzzer_Init
ADC_Init called
OneWire_Init called
Scanning 1-wire bus...
 Found 390000001c0f6828 [DS18B20 Temperature sensor]
SPI_TC_Init called
SC18IS602B_Init - No chip found
 bake setpoint values: 0, dc, 220

SystemFan_Init
# Time,  Temp0, Temp1, Temp2, Temp3,  Set,Actual, Heat, Fan,  ColdJ, Mode
 bake setpoint values: 0, dc, 220
```

**Comment by huffeec** [comment]
Ran today with Custom #1 profile and everything works ok.
