### ISSUE TITLE
Prints Adam hot bed not heating up

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1768]
I've tried different temperatures and switching off and on again. Possibly a broken or worn wire (could have happened during my last print, which didn't stick to the bed well)

**Comment by huffeec** [comment]
I looked at this today and it seems to be heating ok.
@JackiePease suggested we leave this issue open in case it is an intermittent fault. 

![20230218_181259](https://user-images.githubusercontent.com/4748179/219882949-241c85af-7599-4fb4-8931-d7a4d07eb238.jpg)

**Comment by amcewen** [comment]
There have been quite a few successful prints since, so doesn't look like this is a continuing issue.
