### ISSUE TITLE
Need to buy more black bin bags

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#177]
Just emptied the kitchen bin, and noticed we're now down to one or maybe two bin bags left in the drawer.

**Comment by johnmckerrell** [comment]
I've been meaning to cycle to CostCo so could get some tomorrow. Maybe Seán can check and buy some if I haven't. 

--

**Comment by johnmckerrell** [comment]
Obviously I mean @DoESsean

**Comment by DoESsean** [comment]
There should be enough to last the weekend at least, so will be plenty of
time for John to get to Costco.

**Comment by johnmckerrell** [comment]
Bought last weekend.
