### ISSUE TITLE
Liverpool Makefest - 1 July 2023 - DoES Liverpool stand

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1772]
This is to list exhibits and things we need to get ready for Liverpool Makefest, which is on 1 July (please add your name to assignees if you want to help with organising).

It looks likely that the loose theme this year will be Retro/Retro Music.

**Comment by JackiePease** [comment]
# To bring

- [ ] ~~black tablecloths (not needed as tables are good quality)~~
- [x] printed descriptions for exhibits (most)
- [x] stands for descriptions
- [x] vertical display unit 
- [x] business cards and flyers
- [ ] ~~television to show promotional videos~~

**Comment by JackiePease** [comment]
# List of exhibits

- @giggoggi, "a couple of things that have been made using the CNC router" including "a cheeseboard which was made in the shape of an audio casette"
- @Spikyflower, some items made with the embroidery machine
- @magman2112, synthesisers and rugs
- @amcewen, Museum in a Box, DoES Tower, My [bike/baby]’s Got LEDs, Ackers Bell
- @MatthewCroughan, nixified.ai speech to image generator
- @Sean-anotherone, arcade machine
- @JackiePease, pen plotter, light-up rucksack
- ~~Leah Moore, "a multiway rucksack made of scrap fabric, and a denim messenger bag made from old jeans"~~
- ~~Eddie Moore, "different styles of wooden spoons all hand carved and made of different types of wood"~~
- Ed Saul, 1960s GPO Field telephone
- ~~Anne-Marie, recycled can art~~
- Barry, chess-like game board
- @ajlennon, Kettle Companion
- Jeri, Mini Sew N Sew, Fred the Embroidery Machine
- Fatih & Emre, engineered paper palace
- @RussCoty Robot - if he finishes the damned thing.

(please add details of anything you want to display here)

**Comment by JackiePease** [comment]
# List of people who are able to help move stuff and set up our stand on Friday evening

- @giggoggi – transport Friday evening
- @Spikyflower – help with Friday evening setup
- @magman2112 – transport and setup/teardown
- @amcewen – setup/teardown, no transport

(please add your name and whether you can provide transport

**Comment by JackiePease** [comment]
# List of people who are able to help take down our stand and move everything back to DoES immediately after Makefest ends on Saturday

- @giggoggi – transport Saturday afternoon
- @Spikyflower – help with Saturday afternoon teardown
- @magman2112 – transport and setup/teardown
- @amcewen – setup/teardown, no transport
- Joe - has a van 

(please add your name and whether you can provide transport)

**Comment by giggoggi** [comment]
For the Liverpool MakeFest 1 July, I offer to include a couple of items that have been made using the CNC router. Amongst these, the cheeseboard which was made in the shape of an audio cassette may (very) loosely fit the retro music theme. I can also assist in moving stuff to/from the venue and have transport. Graeme

**Comment by inflorescencia** [comment]
I can help set up on Friday evening.
I can help taking the stand down on Saturday. 

I could offer some items made with the embroidery machine, but I can't think of a link to the retro music theme.

**Comment by JackiePease** [comment]
Excellent - an update on the theme, it's specifically 1963, but there's no need to have any link to that! Embroidered items will be great.
________________________________

**Comment by magman2112** [comment]
I would like to take something synthesiser orientated, as usual, but these are not really 1963 style if truth be told. 

I do have a new rug design that I am working on that should be mostly if not completely finished for Makefest, so I will be bringing this as well.

On the more practical aspects, I will likely be volunteering again at Makefest, but I will almost certainly be available to transport exhibits and help setup and takedown the display.

**Comment by amcewen** [comment]
I'll be there, and will have Museum in a Box (will see if I've got any of the Apollo cards now, that's as close as I'll get to the 1963 theme :grin:); the DoES Tower; some My Bike|Baby's Got LED boards; and maybe an Ackers Bell if I can get something set up to trigger it.

New DoES business cards arrived over the weekend.  They're on @DoESsean's desk.

**Comment by MatthewCroughan** [comment]
I'll be there with the nixified.ai speech to image generator, hopefully new and improved.

**Comment by inflorescencia** [comment]
I should have 4 embroidery hoops for displaying some things made on Fred. 3x 20cm diameter and 1x 16cm diameter. 

No shortage of pieces to go in them, if I find more frames/hoops there can be more to display.

**Comment by JackiePease** [comment]
![IMG-20230622-WA0005.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/8ae13980-275d-4873-a7e3-06ca958d4e9c)

Layout for Saturday - we have A1-A13

**Comment by Justcantstopmakingstuff** [comment]
What time should we arrive on Saturday morning? 

I’d be really grateful if someone could make sure that Fred is transported along with hoops, coloured threads (and bobbin threads) and interfacing. I’ll put some fabric in from home.

**Comment by inflorescencia** [comment]
> # List of people who are able to help take down our stand and move everything back to DoES immediately after Makefest ends on Saturday
> 
>     * @giggoggi – transport Saturday afternoon
> 
>     * @Spikyflower – help with Saturday afternoon teardown
> 
>     * @magman2112 – transport and setup/teardown
> 
>     * @amcewen – setup/teardown, no transport
> 
> 
> (please add your name and whether you can provide transport)

Hi I can help with setup on Friday evening. 
Will have to leave on Saturday about 6 or 7pm ish.

**Comment by ajlennon** [comment]
I can help drive stuff back on Saturday if it's needed :)

**Comment by JackiePease** [comment]
8am is the earliest we can get in. Joe's bringing his van on Friday so we'll bring Fred and accessories down in that.On 29 Jun 2023 19:00, Justcantstopmakingstuff ***@***.***> wrote:
What time should we arrive on Saturday morning?
I’d be really grateful if someone could make sure that Fred is transported along with hoops, coloured threads (and bobbin threads) and interfacing. I’ll put some fabric in from home.

**Comment by giggoggi** [comment]
Jackie,

I offered to transport stuff this evening – it’s a car not a van.  What time shall I aim to come to Does?

Best regards

Greme

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by arthurrowland** [comment]
Well done team DoES - I was only passing by but it looked great. Closed as everyone should have got their stuff back to the right place by now. (He says... knowing plenty of plastacs stuff is misplaced)
