### ISSUE TITLE
Wirral Makefest - 3 June 2023 - DoES Liverpool stand

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1773]
Several people have shown interest in this [(website here)](https://wirralmakefest.org/), so I've submitted an application on behalf of DoES Liverpool.

The general theme is sustainability. More details to follow when we get them.

Hopefully there'll be a big overlap with the stuff we have to prepare for Liverpool Makefest (#1772).

**Comment by JackiePease** [comment]
Things we'll need (feel free to add stuff);
black tablecloths
printed descriptions for exhibits
stands for descriptions
vertical display unit (may need some new connecting pieces)
business cards and flyers
television to show promotional videos

**Comment by JackiePease** [comment]
List of exhibits (please add details of anything you want to display here):

**Comment by JackiePease** [comment]
List of people who are able to help move stuff and set up our stand date/time tbc (please add your name and whether you can provide transport)

**Comment by JackiePease** [comment]
List of people who are able to help take down our stand and move everything back to DoES immediately after Makefest ends on Saturday (please add your name and whether you can provide transport)

**Comment by amcewen** [comment]
Wirral Makefest was a great success: https://doesliverpool.com/weeknotes/week-626-wirral-makefest/

Thanks @JackiePease for all your work in organising, and everyone else who turned up and helped out!
