### ISSUE TITLE
Stabiliser for Fred

### ISSUE THREAD

**Issue by inflorescencia** [DoESLiverpool/somebody-should#1775]
The roll of stabiliser for using with the embroidery machine is very low. There is enough left for maybe 2 more large hoops max.

Should somebody restock this? 

Does somebody already know a good source?

**Comment by Robotorium** [comment]
I'll sort it, thanks for making the issue!

Op za 4 mrt. 2023 01:30 schreef Spikyflower ***@***.***>:

**Comment by Robotorium** [comment]
Stabiliser has been received and is in the appropriate place.
