### ISSUE TITLE
Fan in more accessible loo making knocking sounds.

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1777]
Flagging this now as an electrician is due soon according to @JackiePease.

The fan in the more accessible toilet is making knocking sounds that vary in speed and loudness. They're not consistent in rhythm and they get louder and quieter.

@huffeec has turned it off with the switch on the ceiling for now to prevent any (further) damage if it's the fan blades knocking into some obstruction.

**Comment by amcewen** [comment]
Seems it's stopped knocking now :wink:  but only because it's totally stopped working.

**Comment by JackiePease** [comment]
Mick has replaced this
