### ISSUE TITLE
Claire vacuum former has failed its PAT test

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1788]
The new vacuum former has failed its PAT test.

The insulation resistance is too low, at 0.24Mohms.

**Comment by JackiePease** [comment]
I messaged Mayku and got the following response. Can't fill in the form as it asks for date and proof of purchase.
Messaged Claire who is going to check whether she still purchase details:

_Beatrice from Mayku here. Thank you for contacting us. I'm really sorry about this but the insulation test is carried out at 500 volts d.c for a period of 5 seconds. All PAT testers that carry out this test do so by shorting together internally the live and neutral pins within the appliance when carrying out the test. This means that there is no potential difference between the live parts. Where an appliance has a suppressor fitted or a surge protection device then the test may indicate a failure. In these cases, the insulation test may be substituted for the earth leakage test or substitute earth leakage test. This is possibly why it is failing…

We've had a few cases where the FormBox has failed the insulation test and have made some local improvements to the outer surface of the temperature sensor and added a packed heat shrinkable sleeve which has now passed the laboratory PAT test.

We are waiting to hear from our factory when the Improvement kits will be ready, let me check on the progress.

Can you please fill in this form so we can create a ticket for you to action once the improvement kits are ready?_

**Comment by JackiePease** [comment]
Can we substitute Earth leakage test? (on either vac former?)

**Comment by amcewen** [comment]
Thanks for getting in touch with Mayku.  We might be able to change the test procedure, we'll need to find out more about the process.  @pkharvey might have more info in the Part 5 manual.

**Comment by JackiePease** [comment]
@chris-1953 got in touch to ask "Hope this can be resolved soon as I have just received a new mould and was hoping to try it this week/ next.
Would have thought Mayku ought to be happy with just the serial number of the machine- it's not as if anyone else makes them, so it has to have come from them even if you don't have the purchase details."

Claire has emailed Mayku to ask for the details. They're talking about a solution they're still developing though. I think in the short term we're more likely to get somewhere if we can use a different test.

**Comment by amcewen** [comment]
Checking @pkharvey's 5th Edition:

> ### 10.6 The insulation resistance test
>
> Insulation resistance is normally measured by applying a test voltage of 500 V DC between the live conductors and the protective conductor and measuring the resistance.  This test may not always be suitable because it may damage equipment containing sensitive circuits and internal circuitry may lead to inaccurate results; the manufacturer's instructions should be checked.  A more appropriate alternative may be one of the following:
>
> (a) conducting the test at a reduced voltage of 250 V DC, or
> (b) measuring the protective conductor and/or touch current as described in section 10.7

In section 10.7 it says:
> The protective conductor current test measures the current flowing in the protective conductor, which may arise from normal operation (for example, the current arising from internal filtering) or from an internal insulation fault.  The test is only suitable for Class I and Class II FE products.
>
> The touch current test measures the current that would flow from the exposed-conductive-parts of accessible conductive parts to Earth via the user.
>
> The equipment should be switched on and hence operating during the time the measurement is made.  Suitable precautions should be taken and the test operative should understand the equipment and its safe operation.  As a basic example, if the item of equipment under test is a kettle, it should be filled with water to avoid damage to the element.  There may also be potential hazards that might arise during powered tests on a rotating/moving machine, for example, an electric drill.
> **Note:** The accessible conductive parts of the equipment should not be touched during these tests.
>
> The protective conductor current or touch current should be recorded after the reading has been stable for longer than two seconds.  The value should not exceed 5mA for AC-powered equipment.

So we should be able to modify an extension cable **for use only during these PAT tests** so that there's a break in the earth wire, which can then be connected to a multimeter to measure the current along it.  I didn't get enough time this evening to make up the cable, so will have a look at it next Maker Night.

**Comment by amcewen** [comment]
@chris-1953 and I built the protective conductor current test box, and used it to test Claire.  The current didn't get above 0.44mA, so was fine.  We then ran it through the PAT tester, just to get the last test done, and it passed without any problems.  So maybe when it's warm it'll pass anyway?  Not that it matters, it passed both tests.
