### ISSUE TITLE
Calibration for Gerald

### ISSUE THREAD

**Issue by hotcuppa** [DoESLiverpool/somebody-should#1790]
Gerald is cutting things slightly too large. A circle drawn with 254mm diameter is cut at 256mm and holes which should be separated by 203.2mm are coming out 206mm apart.

**Comment by magman2112** [comment]
@Sean-anotherone and I have done a re-alignment and adjustment for Gerald and he is cutting much more accurately now. 

Brian also identified an issue with a loose movement on the left side Y-axis drive belt. We found that there was a screw missing on the drive belt mounting and the other screw was loose. The loose screw had a damaged thread and was replaced and a new screw (M4) was installed.

So closing this issue.
