### ISSUE TITLE
Booking Fred 12th April

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1791]
On behalf of @itsinthedetails - 

Hi,

I haven’t been for a while and I’m wondering if I can book the embroidery machine on Wednesday 12th April? Also I will need white thread 🧵 I’m happy to bring some with me as I need a bit but I know it can only be a certain thread. Which one should I get?

Thank you

Megan

**Comment by Robotorium** [comment]
Hi Megan,

I'm not sure how we book Fred, but the thread should be machine embroidery thread specifically. If you go into Abakhan and ask for machine embroidery thread they'll point you in the right direction.

Cheers!

**Comment by itsinthedetails** [comment]
Thank you Sent from my iPhoneOn 4 Apr 2023, at 17:03, Snoof ***@***.***> wrote:﻿
Hi Megan,
I'm not sure how we book Fred, but the thread should be machine embroidery thread specifically. If you go into Abakhan and ask for machine embroidery thread they'll point you in the right direction.
Cheers!
