### ISSUE TITLE
Fred needs white bobbin thread

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1794]
Fred is very nearly out of white bobbin thread. Can we please buy another spool? They do last ages.

https://amzn.eu/d/dFmaAcH

Cheers!

**Comment by JackiePease** [comment]
I've ordered these, as we seem to be short of colours too, and sometimes it's difficult to get to Abakhan (need to come up with an amount to pay per metre?):
[New brothread Set of 6 Fruit&Garden Colors Polyester Machine Embroidery Thread Huge Spool 5000M for All Embroidery Machines](https://www.amazon.co.uk/gp/product/B07X3B1RXK/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)
[New brothread Set of 2 (Black+White) Huge Spool 5000M (5500Y) Bobbin Thread for Embroidery and Sewing Machines ](https://www.amazon.co.uk/gp/product/B075DKQJTP/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)
They should be here on Thursday

**Comment by Robotorium** [comment]
Brilliant, cheers Jackie. I'll have a think about pricing since it doesn't
really go by the metre.

Op ma 10 apr. 2023 14:09 schreef Jackie Pease ***@***.***>:

**Comment by JackiePease** [comment]
These have arrived and are with the other threads
