### ISSUE TITLE
Prints Adam slipping during print

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1796]
- Sounded as though the belt was slipping, and then started to print in the wrong place 
[IMG_20230411_202129.jpg](https://user-images.githubusercontent.com/12802256/231267505-1c38ebb2-763c-4785-b672-5199fbf73dbb.jpg)

**Comment by huffeec** [comment]
When i looked at this the filament wasn't extruding properly, and the nozzle was gunked up. I wonder if the nozzle was binding on the bed?
I've cleaned the nozzle, reloaded the filament and levelled the bed. The test print worked OK. It's a little stringy, the nozzle temperature is set to a default of 245 which feels to high.
![20230412_152921](https://user-images.githubusercontent.com/4748179/231492855-3af6f982-ba82-4e4f-b0c3-c13140070383.jpg)
