### ISSUE TITLE
guide for small laser

### ISSUE THREAD

**Issue by DaveBenji** [DoESLiverpool/somebody-should#1797]
can anyone tell me where the file is for the cutting laser height guide is and i'll make/cut some? 

You can delete this template text.

**Comment by amcewen** [comment]
We don't have a file, annoyingly.  Once we get one we can put in `somewhere-safe` and close #1636 :grin: 

I've emailed Dominic, who used to run Just Add Sharks (which is where the cutter came from), to see if he's got the file.  Will report back when I hear from him

**Comment by amcewen** [comment]
Dominic sent me a link to download it, and I've saved it to [somewhere-safe/Workshop/LaserCut/Sheila_Ruler.dxf](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/LaserCut/Sheila_Ruler.dxf), so if someone can cut one that'd be great!

**Comment by magman2112** [comment]
@huffeec & I found the box with the spare copies of the cutting guide, so there are plenty of guides available for now, plus A user on Maker Night cut one from the file on Somewhere safe. So plenty of guides available now.
