### ISSUE TITLE
Embroidery machine Fred is very tangled and stuck

### ISSUE THREAD

**Issue by inflorescencia** [DoESLiverpool/somebody-should#1807]
Fred broke down with a tangling issue. 
There's a lot of top thread bunched up under the foot plate, that shouldn't under there. 
I'm loath to start unsecrewing the panels to get the thread out. 
Not sure what generated the issue, hopefully due to a problem with the file I was working from, as opposed to a problem with Fred.

Please see photos, that should illustrate the problem. 

 
![fredbroke1](https://user-images.githubusercontent.com/126928691/233494154-19244f2c-4e8c-4355-bfa9-7bc55fdfcf55.jpeg)
![fredbroke2](https://user-images.githubusercontent.com/126928691/233494158-07fc2faf-192b-473c-9579-67dd010667be.jpeg)
![fredbroke3](https://user-images.githubusercontent.com/126928691/233494162-78bb2c83-25b8-40b1-8787-40d02f5d370d.jpeg)
![fredbroke4](https://user-images.githubusercontent.com/126928691/233494166-94266f63-0953-4454-93e2-08e7e7f48e40.jpeg)

**Comment by Robotorium** [comment]
Did you revise the file? I still think you have too many stitches too close
together. I'll have a look with you next time we're both in.

I'll fix Fred tomorrow.

Op do 20 apr. 2023 22:48 schreef Spikyflower ***@***.***>:

**Comment by inflorescencia** [comment]
I hope it is an easy fix. 


I can come in tomorrow afternoon / evening.

**Comment by Robotorium** [comment]
I'm not sure what time I'll be in tomorrow but if there's overlap we can
have a look at your file. Alternatively you can email it to me and I'll
have a nosey.

Op do 20 apr. 2023 23:18 schreef Spikyflower ***@***.***>:

**Comment by inflorescencia** [comment]
Fred is working fine now :-)
