### ISSUE TITLE
Tony y-axis toothed belt broken

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1810]
A user on Maker Night had an issue where engraving was slipping significantly. On further investigation, we found that the y-axis drive belt was damaged by an apparent fire (this was not reported). The belt is damaged enough that it is not good to use at present.

The belt itself is a T2.5 style belt with a 12mm width. This is proving to be quite difficult to locate at the moment. Complete belt loops are available, but so far these are not long enough. The existing belt is 2272mm long.

@DoESLiverpool/laser-maintenance

**Comment by johnmckerrell** [comment]
I believe there was a fire on the 22nd March, was it that one or another later one?

**Comment by magman2112** [comment]
I believe this is a more recent issue than the 22nd March, also that fire was on Gerald. I was there at the time and was able to replace the damaged air assist tube on Gerald so the downtime was very short.

**Comment by amcewen** [comment]
BeltingOnline.com will make a [custom belt to that spec](https://www.beltingonline.com/t25-c-182_38_203_209/t25-standard-breco-jointed-timing-belt-p-1759.html) for £69, or £45 if we don't need it jointing

**Comment by magman2112** [comment]
This one one of the suppliers I was checking out. The belt without joining is appropriate, as we make the join on the laser head. I think we should go for a 2.3m length of 12mm width belt to give us a bit of leeway as well, as in this link:-

https://www.beltingonline.com/tseries-c-182_37_184/t25-standard-breco-open-length-timing-belt-p-1741.html

If this works out, I would suggest buying another one of these belts for stock, to limit future downtime, but not yet - till we have checked this belt type works in Tony.

I’ve added a shopping link if someone could order this please.

**Comment by amcewen** [comment]
I've ordered that belt.

**Comment by amcewen** [comment]
I chased up where the belt had got to, and while they weren't sure why it had gotten stuck at "processing" in their order system, they've sent out another one (and I have since had a notification that their order system thinks it's "shipped")

**Comment by amcewen** [comment]
New belt arrived over the weekend.  I've left it on Tony's bed.

**Comment by magman2112** [comment]
The new drive belt has been fitted and the guide rails cleaned, so Tony is back in service again.
