### ISSUE TITLE
Ironing pad missing from fibre arts room

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1811]
The heat-proof ironing pad, that was attached to the fibre arts room table with velcro, has gone missing. Does anyone know where it's gone? If so, please return it. Thanks.

**Comment by inflorescencia** [comment]
I'm also feeling the lack of the heat-proof ironing pad. 

If it doesn't show up by a certain point in time, should we look to replace it?

**Comment by Justcantstopmakingstuff** [comment]
Hi. My apologies. The ironing pad belongs to me and I needed it on Eurovision. Happy to leave mine in place until a replacement has been purchased. 

I have sent a link to Jackie to purchase one for DoES.

**Comment by JackiePease** [comment]
@DoESsean ordered a new ironing pad, which has now arrived
