### ISSUE TITLE
Maintain or update the Ultimakers

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1813]
Our Ultimakers are into the 'well loved' category now but still decent machines, they just need a bit of tlc.

To unpick (and close) some of the issues I'm opening this one to decide what is the best approach.

Currently Prints Adam is working, and has an Olsson block installed. There are some maintenance jobs that need doing fairly soon. (broken fan, replace 3d printed part as in #634) I'll open a new issue for these.
Felicity is waiting for a bowden tube clip #1798, one fan isn't working #1619 and is using an old original hot end #1750 

If we are going to keep using these machines they are going to need a little investment. Details in #1798 but repeating them here so I can close that one.

As a minimum an [Olsson block](https://uk.rs-online.com/web/p/3d-printer-parts/1101981) for Felicity
Alternatively a [kit to upgrade to 2+](https://marketplace.createeducation.com/product/extrusion-upgrade-kit/)

Unless there are plans to retire the machines I'm more convinced of the value of the second option. Both printer heads need work so this would give us one updated model with a complete new head and we can pick the best bits left to repair the other. It'd also give more scope for fimware updates #1699 Ultimaker 2 series is now [end of service](https://support.makerbot.com/s/article/1667417418634)
These are solid, enclosed machines that produce decent quality prints reliably when properly maintained.

Of course if we want other features such as dual extrusion it's not worth investing too much in them.

**Comment by amcewen** [comment]
I think we should at least get an Olsson block, and I think there's a decent argument for the 2+ upgrade instead.

As you say, they're decent printers still - we're getting nice prints of Prints Adam since the nozzle got replaced.  It'd be good to have dual-extrusion and/or the capability for flexible filament, but I think we'd still keep the Ultimakers as basic workhorses even then, so it's worth spending a bit on them now.

**Comment by amcewen** [comment]
I've ordered the 2+ upgrade kit.  I guess we can choose which printer to fit it to and put the Olsson block on the other one to get them both back up and running.

**Comment by huffeec** [comment]
Upgrade kit has arrived, it's in the printer cabinet

**Comment by huffeec** [comment]
The upgrade kit has been fitted to Prints Adam and has the latest firmware installed via Cura.
UM Extended 2+ machine settings should be used for slicing.
