### ISSUE TITLE
Extra lighting for sewing machines and electronics workbench.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1816]
During the Repair Cafe event in April, I had asked Cathy Reilly what improvements we could make for the Repair Cafe and Cathy suggested that we get some additional lighting for the industrial sowing machine.

Cathy recommended a light from College Sewing which I believe was the following unit.

https://www.college-sewing.co.uk/ds-28k-75cm-flex-clamp-mount-cob-led-light-100-240v-5w.html

We were discussing similar issues for the electronics workbench during the Hack The Space event last Sunday with @chris-does and @JackiePease. It might be worth buying two of the lamps above as the flex mount would appear to work well for the electronics bench as well.

Additionally, we noted that a replacement for the broken flourescent light on the electronics bench should be found. I suggested an LED lamp that I recently bought for my own garage from Costco. I think it cost approx £30 and had a pull cord switch or PIR automatic switching. Might be worth picking one up on the next Costco run if they aren't too expensove

**Comment by amcewen** [comment]
I've ordered one of the lights from College Sewing (given we've now got more lighting on the electronics bench I figured we'd leave any additions for a bit to see how things go)

**Comment by amcewen** [comment]
This arrived first thing this morning!  I've put it on the sewing machine, ready to be fitted.

**Comment by inflorescencia** [comment]
Light fitting over Gertie is great!

**Comment by amcewen** [comment]
Good to hear!  Thanks whoever fitted it :grin:
