### ISSUE TITLE
Network Outage 2023-05-14 12:00

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1819]
There was a network outage today that I noticed and fixed by power cycling the unmanaged switch which attaches to the CPE gateway in the networking cupboard on 2023-05-14 @ 14:26

Steps followed:

1. Surveyed the cables, rj45 and all layer 1 connectivity in the networking cupboard to ensure it was correct, it appeared as if it was
2. Replugged all rj45 ethernet cable connections to the CPE and unmanaged switch
3. Power cycled the unmanaged switch

Step 2 (Replugging the rj45 cables) had no impact

Step 3 (Power cycling the unmanaged switch) fixed the issue however.

This can imply two potential issues:
1. There was an upstream misconfiguration which caused our unmanaged switch to learn the wrong MACs or some other kind of ARP problem
2. The single gigabit unmanaged switch is dying after a long life of service

**Comment by johnmckerrell** [comment]
For the record, the switch was bought in October 2020--Sent from my mobile phone hence brevity and errorsOn 14 May 2023, at 14:47, Matthew Croughan ***@***.***> wrote:﻿
Closed #1819 as completed.
