### ISSUE TITLE
Small CNC mill end stops need setting up

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#182]
The end stops for the small mill aren't working properly at the moment.
- The X axis microswitch isn't fixed into position.
- The Z and Y axes microswitches are in place, and trigger correctly when the carriage hits them (i.e. the motors stop).  However, once any of the limits has been hit, GRBL seems to get to a state where it won't let you recover from that.  (At least, that seems to be the case when driving it from UniversalGCodeSender)

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by amcewen** [comment]
It's still a problem, just that the Proxxon doesn't get a lot of use so people work round it.
