### ISSUE TITLE
Queen Victoria is refusing to load paper

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1820]
One of the attendees at Maker Day yesterday was trying to use Queen Victoria.  They were trying to print on individual sheets, rather than the roll.  Managed to load one page, but skewed; not by much, but enough that they tried reloading it.

After that it failed to find the leading edge of the paper when trying to load.  Feels like the paper sensor isn't working properly, but there's no obvious paper in the way, but presumably needs more investigation.

**Comment by arthurrowland** [comment]
I think this may have been operator error. Closing given I was able to load sheets a few times today without much trouble, and no one seems to have flagged it since May.

**Comment by amcewen** [comment]
No, there was a fix that @Sean-anotherone did, but then didn't update anything here.  Thanks for closing it @arthurrowland.

**Comment by arthurrowland** [comment]
Ah, nice one Sean! The printer is such a good resource but remains quite a challenge - in between everything else I'd like to make it simple for people to use. By people I largely mean me... who can then share what I learn!
