### ISSUE TITLE
DoorBot 4 (ground level, inside the shutter) isn’t working

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1824]
James arrived this morning to find the ground floor [DoorBot](https://github.com/DoESLiverpool/somebody-should/wiki/DoorBot) inside the shutter wasn’t working. Presenting a fob to the reader did nothing.

By the time I arrived at 09:15, someone had put a hand-written sign on the glass door, telling people to use the _external_ DoorBot 5 instead (which _does_ still work).

Aparently Paul from Aeternum is looking into it right now.

**Comment by MatthewCroughan** [comment]
I want to make a reproducible image with Nix for the doorbots, similar to how I've done for the Admin Phone via https://github.com/DoESLiverpool/somebody-should/issues/1756#issuecomment-1539011879. Maybe @amcewen or @johnmckerrell can help transfer some knowledge to me about how the ruby code works on a hack-the-space night or Maker Night? (tonight maybe?)

**Comment by amcewen** [comment]
I'd tried `ssh`ing in, and didn't get any response from it, so have power-cycled it and it came back up okay.
