### ISSUE TITLE
Fred: Threaded connector missing from one of the large embroidery hoops

### ISSUE THREAD

**Issue by inflorescencia** [DoESLiverpool/somebody-should#1825]
One of the two large hoops for the embroidery machine Fred is out of use because it cannot be fixed together.

The missing piece is a theaded nut which sits inside the outer hoop. 

Hopefully the photos illustrate what is missing. The missing part sits inside the plastic frame on the left. 

Fred is still useable however it limits setting up the pieces to be embroidered as you can't prepare a hoop whilst the machine is in use. 

![fred frame 1](https://github.com/DoESLiverpool/somebody-should/assets/126928691/b4e9cd36-8deb-4d39-92ac-0a83f6fa0c57)
![fred frame 2](https://github.com/DoESLiverpool/somebody-should/assets/126928691/3f348bc5-cc22-42a3-af80-9bb702b77ad6)
![fred frame 3](https://github.com/DoESLiverpool/somebody-should/assets/126928691/129b25c2-99ca-48c0-adde-0c20d5822c16)

**Comment by Justcantstopmakingstuff** [comment]
Found on the floor and replaced.
