### ISSUE TITLE
Gertie: needle broken 

### ISSUE THREAD

**Issue by inflorescencia** [DoESLiverpool/somebody-should#1826]
The needle broke on Gertie, and I was not successful in finding the correct replacement needle before I left the space. 

I left the broken needle taped to a piece of paper under Gertie's foot so it should be obvious if someone were to try to use Gertie what the problem is. 

There are various machine needles in the fibre arts room, but they do need to be specific to the machine in length and in the shape of the shaft. 

If we are out of replacement needles we should order some.

**Comment by JackiePease** [comment]
Gertie-specific needles are in the little drawer on the left hand side underneath her table

**Comment by JackiePease** [comment]
I've seen Gertie working recently, so assume this is resolved
