### ISSUE TITLE
Looks like the height of the laser has been adjusted and AGAIN all the guides are GONE!!! Can we please have an EASY link to the drawings for the guides so at least you can make your own. PLEASE

### ISSUE THREAD

**Issue by DaveBenji** [DoESLiverpool/somebody-should#1827]
Please make your issue:

* Short (Unless required to be long)
* Specific
* Measurable
* Achievable
* Responsible
* Time-constrained

You can delete this template text.

**Comment by johnmckerrell** [comment]
Looks like the rulers are all here, not sure which you need https://github.com/DoESLiverpool/somewhere-safe/tree/master/Workshop/LaserCut

**Comment by DaveBenji** [comment]
Hi John will close the issue now. I have made a number of guides now regards David
________________________________
