### ISSUE TITLE
Extract to Laser Machines

### ISSUE THREAD

**Issue by DaveBenji** [DoESLiverpool/somebody-should#1828]
Please make your issue:

the extract to the laser machines has stopped extracting. Thursday 25 @ 2pm

* Short (Unless required to be long)
* Specific
* Measurable
* Achievable
* Responsible
* Time-constrained

You can delete this template text.

**Comment by DaveBenji** [comment]
hoovered out the fan, OMG! much better now but might need a clever person to look again

**Comment by magman2112** [comment]
This is a regular maintenance issue, it just depends how much MDF has been used on the laser cutters, as this clogs the fans quicker.

The laser extract was working well last night, so closing this issue.
