### ISSUE TITLE
Light fitting in the nook isn't working properly

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1830]
We should investigate whether we can replace the LED disk or light fitting before replacing with a bulb fitting

**Comment by LizTaylor404** [comment]
Not sure if it's related, but there was some water coming down the wall where the light switch is in the nook immediately after the first down pour on Saturday.

**Comment by JackiePease** [comment]
Mick has replaced the led fitting with the bulb fitting from the kitchen.
There is a bulb and converter on @johnmckerrell desk which can be used here (needs a ladder).

**Comment by JackiePease** [comment]
The bulb has been fitted
