### ISSUE TITLE
Front shutter door bot

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1831]
Failed to identify the fob and reseated.  This is a temporary fix and seems to be working now.  It may be useful to find a more secure way to seat this device as this issue has been noted several times before.

**Comment by johnmckerrell** [comment]
FWIW this happened again on Saturday 22nd July 2023

**Comment by johnmckerrell** [comment]
Sean suggested putting a piece of foam behind the board a while ago over in #1267 but we haven't tried that yet (AFAIK)

**Comment by amcewen** [comment]
@pkharvey re-crimped the reader and we fitted fresh adhesive foam to hold it in place on the Maker Night before last.
