### ISSUE TITLE
Bed adjustment screws on Prints Adam are working loose during prints

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1834]
The bed adjustment screws are working loose during prints. This is possibly a snag from the recent upgrade  (#1833). It might need to be disassembled to some extent to find out what the reason is.

**Comment by huffeec** [comment]
The bed adjustment screw at the back wasn't tightened enough when the bed was replaced. (This isn't normally adjusted in the levelling process.) I've tightened it and now and levelled the bed, both the front screws are much tighter so this should fix the issue.
