### ISSUE TITLE
Gerald firing but not cutting fabric

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1843]
User reports that Gerald isn't able to cut fabric. 
It looks like an alignment issue. 
![20230719_101053](https://github.com/DoESLiverpool/somebody-should/assets/4748179/79539dfd-9a61-4d71-8f45-bf4e456792d2)

**Comment by DaveBenji** [comment]
Gerald is just not firing at all this morning

**Comment by huffeec** [comment]
@magman2112 and  @Sean-anotherone looked at this last night and discovered that the focal length of the new lens is different.
New focusing tools (clear acrylic rectangles) are hanging on the side of Gerald.
