### ISSUE TITLE
Thread tension on Fred

### ISSUE THREAD

**Issue by inflorescencia** [DoESLiverpool/somebody-should#1844]
I tried a couple of different methods of threading up Fred with the new large spools of top thread. 

Variable results - I've not been able to consistently get it to work this way - it pulls a lot of the bobbin thread up to the top side. 

It might be that the top thread has to be mounted onto the spike which is on the machine, not the separate stand which is used for winding the bobbin thread. 

However thiis not necessarily due to the large spool because the bobbin thread came through when using the small spools from the box of Fred's threads. 

AFAIK it's not possible to adjust the tension on the bobbin side. 

Suggestions: 
Try a different stand for the larger spool, that has a spike for it to sit on which stabilises it more effectively
Compare results with the smaller spools which fit on the spike on the machine
Try winding the thread from the larger spools onto a smaller one and see how that works

Please add a reply here if any method of using the small or large spools solves this issue.

**Comment by Robotorium** [comment]
I've used the larger stand successfully both on Fred and at home. I'll have
a look on Wednesday.

Op ma 24 jul. 2023 13:50 schreef Spikyflower ***@***.***>:

**Comment by JackiePease** [comment]
Seems ok to me but I'll let @Robotorium check again tomorrow.![IMG_20230725_142136.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/6a320ee3-576e-48e3-b3a2-180c6bf4c1d9)

![IMG_20230725_142130.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/b7a2bcc5-c680-430b-bfba-7049d1c02e3b)

**Comment by JackiePease** [comment]
@Robotorium agreed that this is working now.
