### ISSUE TITLE
Improving extraction in the laser room

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1845]
Some people have reported issues with the smell of the lasers when they are particularly cutting mirrored acrylic on Sheila.

I suspect this is due to the temporary adaptor that is missing for the extractor pipe from Sheila.

Looking back at issue #5, it appears we are missing a RC150 150mm to 100mm reducer, from ductstore.co.uk.

This should be the first fix before looking at any further remedies.

We should also add extra signage to encourage people to remember to switch on the extraction system.

Similarly, people should check that the lids on the other lasers are closed, as this significantly affects the extraction efficiency.

**Comment by JackiePease** [comment]
I have ordered the reducer

**Comment by magman2112** [comment]
An additional option that @Sean-anotherone and I have discussed is whether we could install a cyclone, like we use in the CNC room, to capture the bulk of the dust that comes from laser cutting. This would allow us to use filters again without them clogging up too quickly.

I suspect the main candidates for causing high levels of dust are MDF and polypropylene. It would be a useful exercise anyway.

I have been looking for similar devices online and Bofa appear to have one available, but I expect it to be quite expensive.

One key issue for the cyclone is that I suspect we would have to have a metal version, as some of the residue from cutting may still be a hot coal during extraction. There are other plumbing issues to be evaluated as well. 

Secondly, it would be good if we could reduce the noise levels from the current extraction. This is a major issue when undertaking laser inductions for largish groups, typical of maker nights/days, so this would be a useful improvement.

This enhancement could be combined with adding an additional fan, perhaps making a floor level cabinet to house the extractors, with changes to the ducting to accommodate the new location.

**Comment by JackiePease** [comment]
The reducer for Sheila has arrived. I've put it underneath the laser cutter as hopefully it can be fitted this evening.

**Comment by JackiePease** [comment]
@Sean-anotherone has fitted the reducer

**Comment by amcewen** [comment]
It seems like we're happy with the improvement the new reducer made, right?
