### ISSUE TITLE
Buy cleaning materials for the laser cutters

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1846]
I've found a supplier that has recently brought out a new cleaning product for laser cutters that I think we should buy.

https://cutandbuild.co.uk/laser-cleaner-pro/

This can be used to clean inside the machine and hopefully the bed as well - especially on Tony which is very bad at the moment.

I propose that we try their their starter kit, to see if it works for our machines

https://cutandbuild.co.uk/product/cleaner-starter-pack/

**Comment by DoESsean** [comment]
Ordered. It'll come addressed to you, @magman2112

**Comment by JackiePease** [comment]
These have arrived and are currently on top of the laser cupboard.

**Comment by magman2112** [comment]
The new cleaning solution works very well. It will take a while to get all of the lasers cleaned to a similar level, then we may be able to look at adding a step to our induction process to guide people how to clean the machines after use, especially on Gerald with it’s knife-edge bed.

Closing this issue now as cleaning materials obtained.
