### ISSUE TITLE
Ultimaker 2 Extended neither extrudes or retracts material

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#185]
I tried to print last night but could neither extrude or retract material. Tried to heat nozzle to extrude but no effect Did not have time to try a cold pull technique and reassemble [Cold Pull Link](http://support.3dverkstan.se/article/10-the)

**Comment by amcewen** [comment]
Ran the nozzle up to 240 deg C, and let the heat soak in for a few minutes, and could then retract the material far enough (using the "Move material" menu) to pull it out and do a cold pull to clean things a bit.

The feed gear had chewed through the plastic enough to cause a point where it would stop feeding, so cut it off below that and fed in fresh plastic for it.  Seems to be up and printing okay again now.
