### ISSUE TITLE
Sewing Machine Feet

### ISSUE THREAD

**Issue by LizTaylor404** [DoESLiverpool/somebody-should#1850]
Luna asked about sewing machine feet; specifically a button hole foot. There is a lack of feet for both sewing machines.
The Singer uses clip on sewing machine feet which come in sets, some of which would be useful. The sets are cheaper than buying an individual foot.

Here's an option that covers everything
https://www.ebay.co.uk/itm/165542653654?hash=item268b1c6ed6:g:OkAAAOSwAbhisfmK&amdata=enc%3AAQAIAAAA4P%2BMRSqL1McGA38Sf3KbFq6mufme2gCEBDlYas00OG75ywwjDWZZUidjsyo%2B7X2j2h4wyPw7ZaUF0mEnSXMXe3vpFDxbfqQqwXzWoxUMz4eB4bNVv7ovfOmApqBgk2ZZaKGZRap3DGYPTaC5Eri0VbLKji17RMmQ2R5%2BmLwAqHgpSy1fa8J5KlW37dF%2FBgGj8s2qhtkh9PnBXrliRLGCLr3%2B1PUq8fQJ0abV5oaoJDP1TJSUXKDkJI2SF4Lal%2FcffTcsBhx9YXTHlcWRfU1gSrQ8uIzLKBnOne6tqWAxHOAV%7Ctkp%3ABFBM9N_Zqr1i

A cover plate is needed to use the darning/ embroidery foot
https://www.ebay.co.uk/itm/283892453804?mkevt=1&mkcid=1&mkrid=710-53481-19255-0&campid=5338345293&toolid=11000&_ul=UK&customid=CjwKCAjw29ymBhAKEiwAHJbJ8uCub0NFXnM0eTs5W7VU_GcwuTh6Xt91jRcjqYsv3SBdHhC1QuWC-hoCHCAQAvD_BwE&gclid=CjwKCAjw29ymBhAKEiwAHJbJ8uCub0NFXnM0eTs5W7VU_GcwuTh6Xt91jRcjqYsv3SBdHhC1QuWC-hoCHCAQAvD_BwE

**Comment by JackiePease** [comment]
I've ordered both of these

**Comment by JackiePease** [comment]
These have arrived - I've put them by the drawers in the Fibre Arts room.
Attaching photos to help people identify them in future, especially the small cover plate:

![IMG_20230818_151831.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/f0801df1-8928-4769-80b1-c2f19b873ab2)

![IMG_20230818_151859.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/0ec89e16-6200-465d-9795-8972984a4708)

**Comment by JackiePease** [comment]
(the cover plate is in the box with the feet)
