### ISSUE TITLE
Communicate about keeping laser cutters closed while cutting

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1852]
It seems that some people aren't aware that you should keep all laser cutters shut while cutting on one, because the exhaust is all connected. We need to communicate this somehow (probably through signs).

@DoESLiverpool/laser-maintenance

**Comment by JackiePease** [comment]
@DoESsean has made these

**Comment by amcewen** [comment]
So presumably we can close the issue?
