### ISSUE TITLE
Sheila

### ISSUE THREAD

**Issue by DaveBenji** [DoESLiverpool/somebody-should#1853]
Sheila was filthy this morning. It would be good if you showed some curtesy to the following user to clean the machines when you finish? 
![DSC_0061](https://github.com/DoESLiverpool/somebody-should/assets/130652231/919a8add-6ef5-4bb8-9a81-85db6973098b)

**Comment by JackiePease** [comment]
Does this need to be rephrased as an issue of how to improve/monitor the situation, or can we close this?

**Comment by DaveBenji** [comment]
Hi Jackie. How would you monitor it? Its down to self responsibility.

I think we should close the issue.

Regards David
________________________________
