### ISSUE TITLE
Remove the backlash from the carriage on the small CNC mill

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#186]
There's a reasonable amount of play in the x-axis of the small mill.

Andy has measured it, and the backlash is 0.2mm in the x-axis, and between 0 and 0.05mm backlash in the y-axis.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by amcewen** [comment]
There is still backlash in the mill, so adding the "holding out for a hero" label to help someone who cares about getting the Proxxon mill running sweetly to know what needs doing to it.
