### ISSUE TITLE
Thermaltronics pointy soldering tip not working

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1864]
The pointy tip for the soldering iron is not working, the green light comes on.
Both the other bits work correctly (red light)

[https://uk.rs-online.com/web/p/soldering-iron-tips/8609466](https://uk.rs-online.com/web/p/soldering-iron-tips/8609466) compatible with
Thermaltronics TMT-2000S 50W Soldering Station

**Comment by huffeec** [comment]
See also #1681 for details of what we have previously bought.

**Comment by JackiePease** [comment]
I have ordered 2 of these

**Comment by DoESsean** [comment]
These arrived but when @JackiePease tried to fit one, it was wring. So I've got a return processed and ordered the same ones we got last time.

**Comment by JackiePease** [comment]
The tips Seán ordered have arrived. I've checked that they fit and put them in the drawer under his desk
