### ISSUE TITLE
Make advice for disabled limited mobility visitors

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#187]
I've started a page in `somewhere-safe` with a link to a [google map](http://bit.ly/DoESDisabledParking) of closest parking Ive used to access DoES with some notes for each one in response to an email about access. Missed that email somehow so hope this helps. Not comprehensive yet so will leave issue open

https://github.com/DoESLiverpool/somewhere-safe/blob/master/Parking/ParkingAdvice.md

**Comment by goatchurchprime** [comment]
This page is linked from front page of the new github wiki.wiki
    https://github.com/DoESLiverpool/wiki/wiki

Maybe we could port it back and expand it into a proper page with more detailed and clearer information on how to get here that could be routinely used by event organizers

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by stevesparrow** [comment]
It would be good if we could develop this for the new space?

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ajlennon** [comment]
Are there places to look at for best practice on this?

**Comment by johnmckerrell** [comment]
This is being worked on here: https://github.com/DoESLiverpool/wiki/wiki/Accessibility

**Comment by ajlennon** [comment]
There seems to be some confusion about a "refuge". Can we pull this out somewhere - preferably on the the wiki page so we all understand what is supposed to happen in the event of fire/flood/catastrophe.

Pinging @Robotorium in case Snoof isn't on this thread

**Comment by DoESsean** [comment]
How is this looking? As far as I can tell, we seem to have a pretty good handle on mobility issues in the space, and work quite closely with @Robotorium to ensure that any issues that do arise are taken care of.

I appreciate that that's not the be all end all, but it seems to be a good start. 

With that in mind, should we close this issue, or keep it open as a reference point?
