### ISSUE TITLE
Oil heater in annex tripped the breakers 

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1876]
@huffeec and I have been in the annex today. We got a bit cold so we turned on the oil heater which almost immediately tripped the breakers.

Chris found the relevant cupboard to reset the breakers (outside next to the more accessible annex loo) but it might be worth pat testing the heater.

**Comment by amcewen** [comment]
It was last PAT tested on 24/03/2022 (although its pass sticker seemed to have gone AWOL).  I've re-tested it this evening and it passed with no problems.

I wonder if it's pulling too much current for the breaker?

**Comment by Robotorium** [comment]
I guess that's possible, but we only had the standing lamp on at the time -
is Sheila on a different circuit?

Op do 2 nov. 2023 19:10 schreef Adrian McEwen ***@***.***>:

**Comment by JackiePease** [comment]
The heater was working on Saturday when plugged in to a different socket. Do we need to identify the previous socket and get it checked

**Comment by amcewen** [comment]
We're no longer in the annex.
