### ISSUE TITLE
Tony not cutting, Gerard creating flames

### ISSUE THREAD

**Issue by Jade1965** [DoESLiverpool/somebody-should#1878]
Tried to using Tony today and wasted 2 sheets of material as theres barely any output, altered settings no luck!
Wont cut through 3mm mdf just leaving line drawings.

Also went onto use Gerarld a fire started (small fire) and then went onto realise the plastic piple, exhasut pipe that filters the smoke is split in to two oviously causing the fire.

Thanks Jade

**Comment by Jade1965** [comment]
Gerarld all fixed and pipe replaced.

**Comment by JackiePease** [comment]
Closing as Tony was being used on Sunday with no problems

**Comment by amcewen** [comment]
@Knottyashcreative cleaned the lens on (I think) Saturday.
