### ISSUE TITLE
Buy more scalpel blades

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1879]
We're down the last one or two scalpel blades.  We should get some more used blade holders too.

**Comment by DoESsean** [comment]
Ordered these today, [Blade Remover Units](https://www.scalpelsandblades.co.uk/accessory-detail_121_swann-morton-blade-remover-unit-5525-.php) and [Blades](https://www.scalpelsandblades.co.uk/blade-detail_23_no-10a-non-sterile-carbon-steel-scalpel-blade-swann-morton-product-no-0102-or-3002.php)

**Comment by DoESsean** [comment]
These have arrived, and are in the sharps drawer.
