### ISSUE TITLE
11 tubes need replacing in the lights in the workshop

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#188]
There are 11 tubes out for the workshop lights.  We need to report it to reception.

**Comment by amcewen** [comment]
I mentioned this to Rachel on reception yesterday lunchtime, so hopefully it'll be in progress.

**Comment by amcewen** [comment]
I asked Jeanette about it again today.  She's going to get Tony to drop off some tubes (and maybe starters) for us to fit (as the handyman is only in at 7, so too early to get access to the workshop without us arranging something beforehand)

**Comment by amcewen** [comment]
There are now a dozen new tubes and four new starters next to the woodwork bench in the workshop.  Tony asked for the dead tubes to be put into the cardboard sleeves from the new tubes, as the bin men won't take them otherwise.

They just need fitting now...

**Comment by amcewen** [comment]
I've fitted some of the new tubes - basically the ones I could do without needing a ladder & to disrupt the laser-cutters (which are in use right now).

The pair of tubes nearest the door need a new ballast (the starters that we got don't fit these lights), and there are still four tubes out in the two sets of lights above the laser-cutters.

**Comment by amcewen** [comment]
I've replaced the rest of the tubes that are faulty above the laser-cutters.  However one pair, in the fitting above Sophia, needs a new ballast too.  So we'll need to arrange with reception for the handyman to get access one morning to fit two new ballasts.

**Comment by johnmckerrell** [comment]
I've mentioned this to reception and also the two longer tubes that we need in Room 29. The handyman is now around all day Monday and Tuesday so will hopefully be able to get in while we're here.

**Comment by amcewen** [comment]
Well, I can't remember if we ever got the ballasts replaced, but there's now only one tube lit in the set above Sophia, and none in the set above Gerald and one out in the set above the electronics workbench.

So it'd be good to get another six tubes sometime to provide some more illumination over the laser-cutters :-)

**Comment by amcewen** [comment]
Mentioned it to Jeanette when she came to read the meters just now.  She's going to send Dave up to look at it on Friday.
