### ISSUE TITLE
Rear fire door is difficult to close

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/somebody-should#1881]
The fire door in DoES that leads to the outside fire escape is difficult to close at the moment -- it seems to be sticking to some extent against the frame.

It can still be opened reasonably easily.

But it needs adjusting as soon as possible to avoid the possibility of it jamming shut.

**Comment by JackiePease** [comment]
Jason is looking at getting the door painted and planed.

**Comment by amcewen** [comment]
Jason planed it down yesterday.
