### ISSUE TITLE
Should DoES get a modern digital oscilloscope?

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/somebody-should#1884]
Have mentioned this to a few people in DoES over the last few months.
For now, just want to know if there is any interest in getting one of these?

Rigol have recently introduced a low cost 12-bit, 4 channel digital oscilloscope. It has received good reviews on various channels including EEVBlog on YouTube.

It is now available in the UK.

Details can be found here: https://www.rigol-uk.co.uk/product/rigol-dho804-4ch-12bit-70mhz-1-25gsa-s-usb-powered-digital-oscilloscope-copy-2/ This is for the 70MHz unit -- there is a 100MHz one available as well.

Price is around £425 incl. VAT. The 100MHz one is about £530.

**Comment by amcewen** [comment]
DoES should get a modern digital oscilloscope!

@pkharvey and I could have done with a 4 channel 'scope today.  It would be nice to get the 100MHz one if we can.  MCQN Ltd would chip in £150 towards it (maybe a bit more).

**Comment by helicalbytes** [comment]
I'd be able to put about £100 towards it.

**Comment by huffeec** [comment]
Inspired by Adrian discussing experiments in electron flow in twisted
pairs, I'm convinced this is suitably Physics. Happy to match Helicalbytes.

**Comment by amcewen** [comment]
For anyone wanting to see how you can use a scope for cool ways to do physics*, this is the video I was discussing with @huffeec: https://www.youtube.com/watch?v=2AXv49dDQJw

(yes, @huffeec, I realise that *all* ways of doing physics are cool, I'm just trying to sex it up for the unenlightened :grinning:)

**Comment by amcewen** [comment]
@pkharvey has chipped in £50 too.

**Comment by amcewen** [comment]
@ajlennon has also offered to chip in £100 (on the Google Group)

**Comment by amcewen** [comment]
So we were up to £500 in pledges.  At the directors' meeting this week we agreed that DoES should chip in the remaining ~£30 to let us get the [better one](https://www.rigol-uk.co.uk/product/rigol-dho814-4ch-12bit-100mhz-1-25gsa-s-usb-powered-digital-oscilloscope-copy/).

@DoESsean will be in touch to collect pledge payments, or make the payment and let him know the details; then we can get it ordered!

**Comment by amcewen** [comment]
Pledges are all in :tada:  The oscilloscope has been ordered.

**Comment by amcewen** [comment]
![image](https://github.com/DoESLiverpool/somebody-should/assets/108468/24b7f22d-504b-4312-a1f4-d41022891fa4)

It's here!

**Comment by ajlennon** [comment]
How exciting !!!
