### ISSUE TITLE
Loose carpet in the corridor round Room 29 / fire exit

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1885]
The carpet in the corridor by Room 29 and the fire exit seems loose.

Someone (@helicalbytes ?) has added some hazard tape. 

In the short term we need to get some more hazard tape to mark trip hazards, and then evaluate whether we need to use carpet tape or glue to stick the rest down.

**Comment by johnmckerrell** [comment]
I’m sure I’ve stuck this down before with spray glue. Think it worked reasonably well although has clearly come back up again. Wonder if there’s a previous issue. --Sent from my mobile phone hence brevity and errorsOn 10 Dec 2023, at 17:20, Jackie Pease ***@***.***> wrote:﻿
The carpet in the corridor by Room 29 and the fire exit seems loose.
Someone ***@***.*** ?) has added some hazard tape.
In the short term we need to get some more hazard tape to mark trip hazards, and then evaluate whether we need to use carpet tape or glue to stick the rest down.

**Comment by JackiePease** [comment]
Irene reminded me that the carpet was still loose. We've stuck it down with spray glue
