### ISSUE TITLE
Create two more kitchen passes

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#189]
We're currently down to 0 kitchen passes.  I suspect the one with the MDF tag will resurface at some point - we still had it yesterday - but I haven't seen the fluorescent or red acrylic ones for ages.

We should revoke those from the doorbots, and laser-cut two more tags.  I've just added another RFID tag so we've got one to use now, so we'll only need one other tag provisioning.

**Comment by DefProc** [comment]
There are some tags and keyrings for the nerf range that would work
straight away.

Unfortunately they are OOBB compatible though :(

**Comment by amcewen** [comment]
Have cut two new kitchen passes, and saved the cut file in https://github.com/DoESLiverpool/somewhere-safe/commit/5fbd15707178191c453df70ca3dcb63880394968 

The doorbots have been updated with the new tags, and all the old ones removed.
