### ISSUE TITLE
Buy some kitchen supplies from Ikea

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1891]
Breaking this one off #327 as we need some things that would be best bought from Ikea. We need the following:

- [ ] Soup/cereal bowls
- [ ] Cutlery

Please feel free to edit and add more items although be sure to also comment so that I'm notified, I'm going on Thursday and should be able to pick some stuff up.

**Comment by amcewen** [comment]
There's an Ikea box on @DoESsean's desk at the moment.  I don't know if that means someone has already ordered things or not?

**Comment by DoESsean** [comment]
Strangely enough, that's exactly what happened. We'd been talking before Christmas about the stuff that was needed, and it was suggested I just order, as we didn't know when/if someone would be going to Ikea.

So, we've got cereal bowls, and loads of new cutlery. If you wanted to get deeper soup bowls, that would be the only thing 'needed', and even then it's not vital.

**Comment by johnmckerrell** [comment]
I didn't get any more bowls but didn't sound like it's vital so closing this.
