### ISSUE TITLE
Tony isn't cutting even on speed = 5

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1899]
Tony isn't cutting and leaving ghosting on etches. Reported by user booked in today

Suspect it's just mirror alignment.

![20240202_110026](https://github.com/DoESLiverpool/somebody-should/assets/4748179/c65970ea-796f-4f71-8ca2-45f3505e2576)
![20240202_110031](https://github.com/DoESLiverpool/somebody-should/assets/4748179/af8bd87b-e8fc-472d-a3ea-5b253cad80d7)

@DoESLiverpool/laser-maintenance

**Comment by JackiePease** [comment]
@huffeec has this been fixed?

**Comment by huffeec** [comment]
Not that I am aware of.

**Comment by magman2112** [comment]
I should be able to pop in this evening and have a look at this.

**Comment by magman2112** [comment]
Tony was out of focus quite a bit. This has been corrected now and Tony is cutting well again.
