### ISSUE TITLE
3D printer Marcus heating up ok, and moving to start position, but not printing

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1900]
Mohammed mentioned that Marcus wasn't printing, and the same thing happened when I tried at the weekend. I've spoken to @Knottyashcreative, who thinks it's an issue with the SD card reader and is aiming to take a look on Saturday

**Comment by Knottyashcreative** [comment]
3D printer now working as it was tested and ran smoothly.  The issue was with the Card Reader.  It was agreed that a future permanent fix would be moving over to Octoprint.
