### ISSUE TITLE
Entrance Doorbot Broken Again, and the Emergency Number doesn't work?

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1903]
Who is going to take responsibility for the broken doorbots? I've tried and failed, there's a lack of enthusiasm about this issue. I have working code to replace the doorbots which is reproducible, easy to understand and re-deploy. But whenever approaching about it, I never really get anywhere.

@johnmckerrell is busy and barely in the space, so I can't work on this with him unless he dedicates time to it.

@amcewen also is busy and probably doesn't have the time.

@JackiePease just puts up with it.

I pay a membership and it's getting annoying now. I was unable to get into the space tonight, so had to wait around for 20 minutes until Paul was able to let me in, as he was difficult to contact (phone was not on).

In the past when I've encountered this situation, I called the emergency number listed here https://github.com/DoESLiverpool/somebody-should/wiki/VOIP-Phone-Setup#emergency-number---0151-660-6999, but this time it went immediately to voice mail and not through to anyone.

**Comment by MatthewCroughan** [comment]
I would love to hack on this with @johnmckerrell if you can carve out the time one night, since last time I showed you my code, you said it was missing some features such as inserting values into to a Google spreadsheet, or something like that. These requirements are just word of mouth right now. And just in case nobody is interested in my contributions, then I would just appreciate the doorbot being made more reliable in general, by someone.

**Comment by MatthewCroughan** [comment]
The doorbot is still broken, I tried to access via the front this morning, and I am still unable to access.

**Comment by MatthewCroughan** [comment]
Pretty cold out here this morning.

**Comment by helicalbytes** [comment]
I'm happy to look at this. Is there anything known about what is wrong with the current doorbot? And is there any documentation on its hardware and software?

**Comment by johnmckerrell** [comment]
Forgot that I didn't actually get around to commenting on this. To confirm, the issue is a hardware issue. So far it's only been discussed on a WhatsApp group and we've been a bit wary about putting details on a public forum as it relates to the building security but I think the following should be ok.

> doorbot5 is still offline 🙁  I tried power-cycling it and that didn't help; pulled the Pi out and it booted up fine here in the office; however, when I reinstalled it the door latch stuck open (so locked all the doors after it timed out and wouldn't unlock them) and seems to have killed the Pi - I did briefly connect it up off-by-one with the power off, but maybe a cap still had some charge?!? - I've replaced the Pi with a spare Pi 2 but while that isn't preventing the doors from unlocking, it also isn't getting on the network or unlocking the door from the reader

@Sean-anotherone put a multimeter to the RFID reader a few weeks back but it wasn't getting any power.

**Comment by amcewen** [comment]
As @johnmckerrell mentions, from our current investigations this seems to be a hardware issue.

There's a related issue where we haven't done a good job of communicating the problem to the community.  Sorry.

(neither of those are *software* issues though.  IMO the software works well, and we should understand *why* we're replacing it before we do, if we do)

Having more people who understand the set-up and who can work on it would be good.  @helicalbytes, the code is in the [logcards repo](https://github.com/DoESLiverpool/logcards) and there is some documentation of the hardware - the [custom PCB files are here](https://github.com/DoESLiverpool/doorbot-setup/tree/master/hardware) and I have a wiring diagram of the surrounding system, but it's on paper at the moment.

I'm going to do some digging into it this afternoon, if anyone wants to help.  I'll be in DoES (well, likely at the bottom of the stairs on a ladder...) from about 2pm.

**Comment by amcewen** [comment]
@JackiePease and I worked on this this afternoon.  We ended up swapping the Pi, although that didn't really seem to be the problem, and then found a loose ground connection going into shield on the Pi.  Fixing the ground connection seems to have solved the problem and the outside fob reader is now working again.
