### ISSUE TITLE
Sheila failing to cut through 3mm perspex

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#1908]
@DoESLiverpool/laser-maintenance 

Shelia was not cutting very well today, even at speeds of 6-8 she was struggling to get through 3mm perspex.
I did a quick check of the mirrors and they seem reasonably clean/aligned.

I can't see when the tube was last replaced but wondering if this is the issue?

**Comment by huffeec** [comment]
@JackiePease asked me to look for potential replacement tubes.

This machine was originally bought from Just Add sharks (Now Smoke and Mirrors) They don't stock replacement tubes any more, if we can't find something suitable Dominic might be able to point us in the right direction. A lot of hackspaces seem to have these machines but none I could find had a supplier on their wikis.
Fot reference (and eventually the wiki page #1713 ) the manual for this machine is [https://smokeandmirrors.store/pages/just-add-sharks-support-page](https://smokeandmirrors.store/pages/just-add-sharks-support-page)

The last tube I could find an issue for was Gerald #987 but the suppliers HPC don't seem to have anything suitable.

While looking for the specs I did spot the tube was last serviced by JAS in 2018..
![image](https://github.com/DoESLiverpool/somebody-should/assets/4748179/cacc6464-5c69-4f06-a74e-2bb2839deac0)

Machine info
![image](https://github.com/DoESLiverpool/somebody-should/assets/4748179/d7572050-ee70-42d4-acb7-b3913209dd7a)

**Comment by magman2112** [comment]
What length and diameter is the tube? 

The tube in Sheila or the laser cutter that Carl dropped off could possibly fit as a temporary replacement, till we find a long term replacement perhaps.

**Comment by kinselley123** [comment]
I used the laser cutter today and for me it was working as usual, my settings are speed 6, power 45 on 4mm acrylic-. Im back on friday so will use it again and see what its like.

I did notice last week that the industrial cooler was turned off (the cream metal box under the laser)- it needs to be on when cutting. I understand this could effect the laser 

Many thanks Sam

**Comment by huffeec** [comment]
Excellent. Sounds like we don't need a new tube after all then.
