### ISSUE TITLE
8mm collet broken on the Kinetic CNC Machine

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1909]
Last time I was doing an induction on the CNC Machine, we had a lot of difficulty removing the collet and cutter from the spindle motor on the CNC machine. We eventually managed to get the collet loos, but in the process the 8mm collet broke into 2 parts.

As there is already a known issue with the run out on the spindle motor, this is yet another negative with the current Kress spindle motor.

I will do some investigation to find a cost for a replacement for the 8mm collet. I suspect we are also due to replace the 6mm collet as these are looking quite damaged as well.

**Comment by Evans-Luke** [comment]
You can get collets and collet nuts from here:

https://cnc-plus.de/en/Collets---Clamping-Nuts/?view_mode=default&listing_sort=name_asc&listing_count=50

the spindle motor is - Suhner UAD30RF 1050W

I suggest that we get a set of 5 for 60 euro. im happy to chip in.  I use 6mm and 8mm and I think a 10mm with a large endmill to skim the bed from time to time would be useful. That would require getting a 10mm aluminium end mill. 

Im not sure what sizes other people use ? maybe a 3mm and 4mm?

I think we should get another collet nut in the order as a spare https://cnc-plus.de/en/Collets---Clamping-Nuts/clamping-collet-nut-for-kress-6990-6955-suhner-aw-fse.html

**Comment by magman2112** [comment]
Closing this issue as a replacement spindle motor has now been sourced, so there is no further requirement to do anything with the old spindle motor.
