### ISSUE TITLE
Sophia needs a new focus ruler

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#191]
The blue one (https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/LaserCut/Small%20Laser%20Square.svg) has a broken keyring hole, so it won't hang on the hook on the machine; so we kind of need to cut a replacement.

Explaining how to use the "reference square" ruler is less well understood for new users than the new "follows the nozzle contour" of Gerald's new ruler #140, so we should probably make a replacement that fits Sophia the same way.

**Comment by DefProc** [comment]
A rather excellent point from Luke today was that both laser rulers should be attached to the machine (like Sophia's bed tool is) so there's no chance of them walking round the workshop.

**Comment by DefProc** [comment]
This is still outstanding, and should still be completed, either cutting a direct replacement for the damaged (cut by accident) original, or designing a better one similar to the one in Gerald.

**Comment by DoESsean** [comment]
Has this ever been done?

**Comment by magman2112** [comment]
A replacement Ruler has been cut for Sophia now, using the design from "Somewhere Safe". The old one has been placed in the Offcuts draw as a backup.
