### ISSUE TITLE
Liverpool MakeFest - July 6 2024 - DoES Liverpool Stand

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1912]
This is to list exhibits and things we need to get ready for Liverpool Makefest, which is on Saturday 6 July (please add your name to assignees if you want to help with organising).

**Comment by JackiePease** [comment]
### Things to bring with us
- [ ] black tablecloths (not needed as tables are good quality)
- [ ] printed descriptions for exhibits (most)
- [ ] stands for descriptions
- [ ] vertical display unit
- [ ] business cards and flyers
- [ ] television to show promotional videos

**Comment by JackiePease** [comment]
### List of exhibits
(Please add your name and any items you'd like to display)

- @JackiePease - controller box with (something to control)
- pen plotters with maps/dolls?
- Andy - Japanese stuff
- Sasha
- @amcewen Museum in a Box; My Baby's Got LED; Ackers Bell
- @magman2112 - Rug

**Comment by JackiePease** [comment]
### List of people who are able to help move stuff and set up our stand on Friday evening
(Please add your name and whether you can provide transport)

* @amcewen :x: (well, just :bike:)

**Comment by JackiePease** [comment]
### List of people who are able to help take down our stand and move everything back to DoES immediately after Makefest ends on Saturday
(Please add your name and whether you can provide transport)

* @amcewen :x:

**Comment by Sean-anotherone** [comment]
Not sure if I can help out, but arcade machine is available as ever if it's useful.

**Comment by JackiePease** [comment]
Map of the ground floor of the library showing DoES tables:
![makefest map 2024](https://github.com/DoESLiverpool/somebody-should/assets/12802256/4175b457-be34-4123-a675-85e65fa029a0)

**Comment by JackiePease** [comment]
Last year, @Robotorium and @huffeec had A13 and A12 and @amcewen had A11 - assuming you all want the same ones again?
Does anyone else have any preferences?

**Comment by Robotorium** [comment]
Yes please, makes it a easier to access.

Op ma 1 jul. 2024 18:56 schreef Jackie Pease ***@***.***>:

**Comment by JackiePease** [comment]
Sasha A6

**Comment by amcewen** [comment]
Same tables again sounds good to me.

**Comment by amcewen** [comment]
Are A6 and A5 not for ConcreteDog?

**Comment by JackiePease** [comment]
> Are A6 and A5 not for ConcreteDog?

I suppose I meant "showing DoES tables and others", but they are labelled.

**Comment by amcewen** [comment]
I wasn't querying that bit, more that it seemed that you'd assigned one of his tables to Sasha :grinning:  However, I hadn't realised he'd had to pull out.

**Comment by JackiePease** [comment]
Current table plan:
|Table       |Entity                                  |
|--------------|-----------------------------------|
| A1   | Plastic Tactics   |
| A2   | Plastic Tactics   | 
| A3   | Julian  |
| A4   | Matt and Gabby  |
| A5   | Sean's Arcade Machine  |
| A6   | Anotherrrealm |
| A7   | |
| A8   | |
| A9   | 3D Primo |
| A10 | Aeternum (half desk) |
| A11 | MCQN Ltd |
| A12 | Steam Engineers  |
| A13 | Steam Engineers  |

(Mike's Liverpool Waterfront Rug in the Children's Library)
