### ISSUE TITLE
Wirral MakeFest - June 1 2024 - DoES Liverpool Stand

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1913]
This is to list exhibits and things we need to get ready for Wirral Makefest, which is on Saturday 1 June (please add your name to assignees if you want to help with organising).
(Hopefully there'll be a big overlap with the stuff we have to prepare for Liverpool Makefest - #1912  )

**Comment by JackiePease** [comment]
### Things to bring with us

- [ ] - black tablecloths (not needed as tables are good quality)
- [ ] - printed descriptions for exhibits (most)
- [ ] - stands for descriptions
- [ ] - vertical display unit
- [ ] - business cards and flyers
- [ ] - television to show promotional videos

**Comment by JackiePease** [comment]
### List of exhibits
(Please add your name and any items you'd like to display)

-     @JackiePease - controller box with flowers
-     @LizTaylor404 - embroidery machine (unless someone else would like to do this)
-     Sasha
-     @amcewen Museum in a Box; My Baby's Got LED; Ackers Bell
-     Laura's sewn circuit examples

**Comment by JackiePease** [comment]
### List of people who are able to help move stuff and set up our stand on Friday evening

(Please add your name and whether you can provide transport)

**Comment by JackiePease** [comment]
### List of people who are able to help take down our stand and move everything back to DoES immediately after Makefest ends on Saturday

(Please add your name and whether you can provide transport)

**Comment by LizTaylor404** [comment]
> ### List of exhibits
> (Please add your name and any items you'd like to display)
> 
> * ```
>   @JackiePease - controller box with (something to control)
>   ```
> * ```
>   @JackiePease  - embroidery machine (unless someone else would like to do this)
>   ``` I can help with the embroidery machine on Saturday morning. I won't be able to stay all day.
> * ```
>   @zarino - pen plotters with maps/dolls?
>   ```
> * ```
>   Sasha
>   ```
> * ```
>   @amcewen Museum in a Box; My Baby's Got LED; Ackers Bell
>   ```
> * ```
>   @magman2112 - Rug
>   ```
> * ```
>   Laura's sewn circuit examples
>   ```

**Comment by JackiePease** [comment]
The event went really well, thanks to everyone who participated. Alison says that next year's event will only be at Birkenhead Central Library - so there shouldn't be any issue with Steam Engineers, Plastic Tactics and DoES Liverpool being on different sites.
