### ISSUE TITLE
Vacuum Cleaner in the Laser Room

### ISSUE THREAD

**Issue by DaveBenji** [DoESLiverpool/somebody-should#1916]
There is new pre-loved vacuum cleaner in the laser room. It is a 'Henry' type and uses the same bags. The blocked Dyson upright is ready for the repair shop. We tried to remove the blockage but failed so it needs an expert touch. Regards

**Comment by Rosanna19** [comment]
I can look at this 🙂

**Comment by magman2112** [comment]
The blockage in the Dyson cleaner has now been removed (there was some foam type material causing the main blockage). So this cleaner is back in working condition again.

**Comment by magman2112** [comment]
@DaveBenji is the “Pre-Loved” machine on loan to DoES, or does it need to go home at some time?

**Comment by DaveBenji** [comment]
Hello. The hoover now belongs to DoES. Regards

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by magman2112** [comment]
Closed this issue as both cleaners appear to be working well at present.
