### ISSUE TITLE
2024 compare prices with "similar" spaces

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1920]
Subtask of #1919

**Comment by markdhemming** [comment]
Here's what I've got so far:

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
Space | Perm Desk | Flexi | Full Day | Half Day
-- | -- | -- | -- | --
Avenue HQ Mann Island | 210+VAT | 110+VAT | 20+VAT | NA
Spaces - Ropewalks | 155+VAT | - | 25+VAT | -


</body>
</html>

**Comment by markdhemming** [comment]
Here's what I've got so far:

| Provider | Perm desk per mth | Flexi desk per mth | Hotdesk per day |
| --- | --- | --- | --- |
| [DoES Liverpool](https://doesliverpool.com/services/) | £180 | £80 | £12 |
| Avenue HQ Mann Island | £210 + VAT | Flexi £100 + VAT | £20 + VAT |
| [Spaces Works, Ropewalks](https://www.spacesworks.com/liverpool/ropewalks/) | £115 + VAT | – | £25 + VAT |
| [Basecamp, Jamaica St, Baltic Triangle](https://basecampliverpool.co.uk/pricing/) | £200 | £130 | – |
| [NextBigThing, 12 Jordan Street, Baltic Triangle](https://12jordanstreet.com/baltic-coworking) | £175 + VAT | – | – |
| [CoWorkz Liverpool Film Studio](https://www.liverpool-film-studios.co.uk/office-space/) | £125 + VAT | – | – |
| [FACT Artist Membership](https://www.fact.co.uk/studio-lab/artist-membership) | – | £50–120 | £20 |

**Comment by nikdoof** [comment]
Just adding in: FACT Artist membership: https://www.fact.co.uk/studio-lab/artist-membership

Flexi £120/month, £20 per day. No perm desk option.

**Comment by amcewen** [comment]
Thanks everyone for chipping in with info.  Given we've updated our pricing, I think we're done here.
