### ISSUE TITLE
Tony PC not working

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1922]
@davebenji was trying to use Tony - the screen was showing "no signal" although there was a green light on the PC. We tried reseating the cables without success. We've borrowed the HDMI cable from Neil's desk (as he's on holiday this week) and this works fine. 

Somebody should check for issues with the original HDMI cable, and find a replacement if necessary.

**Comment by magman2112** [comment]
This was diagnosed to be a faulty HDMI cable. A cable was borrowed from Neil's PC as a workaround, but I have now sourced a replacement cable and installed it. Neil's cable has been left on his old desk for the next time he comes in.
