### ISSUE TITLE
HP LaserJet Pro M402dn complaining of a (phantom?) paper jam

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1924]
![IMG_8025](https://github.com/DoESLiverpool/somebody-should/assets/739624/59cb9337-6a50-4564-935e-491aa23c00b9)

This morning @pkharvey and I discovered that the HP LaserJet Pro M402dn (probably the most commonly used printer in the space, given it’s one of the only ones that actually works) is complaining about:

```
Jam in cartridge area. Open front door and clear jam.
```

![IMG_8026](https://github.com/DoESLiverpool/somebody-should/assets/739624/17c0faf2-9386-4180-88e0-91fb2bc2bef9)

I tried removing the paper tray, opening the front door, and removing the drum assembly, and couldn’t see any obvious jam.

![IMG_8029](https://github.com/DoESLiverpool/somebody-should/assets/739624/734d45be-1fc8-41ef-a3ef-f8577a346a6a)

Power cycling the printer made no difference.

**Comment by amcewen** [comment]
It was complaining about a paper jam yesterday but that was just that the paper tray hadn't been closed fully.  It printed fine for me once I'd pushed it closed.  (As a datapoint that it was still functioning okay yesterday afternoon)

**Comment by zarino** [comment]
Thanks @amcewen! Weird, I tried the paper tray in all sorts of positions, but to no avail.

Anyway, can confirm this printer is now working again, as I just used it to print out some new bin signs for @JackiePease.
