### ISSUE TITLE
Malfunctioning ceiling lights in the main room

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1928]
The 2 ceiling lights nearest to the alcove and laser cutter room were flashing on and off continuously (but the one nearest the laser cutter room more frequently). Switching the fuse off and on doesn't make any difference. 
I've switched them off for now.

**Comment by JackiePease** [comment]
Apparently this has been happening for a while. The lights stop flashing after they've been on for a few minutes, so less urgent, although they should still be looked at by an electrician in case the issue gets worse.

**Comment by JackiePease** [comment]
The lights don't seem to stop flashing now, so we're not using them at the moment. I've spoken to Mick the electrician, who believes they have reached their end of life and need to be replaced (meaning the whole unit and not just the LED disk). He's coming to take a look tomorrow.

**Comment by JackiePease** [comment]
Mick has temporarily replaced the malfunctioning ceiling lights with bulbs. He will source replacements and get back to us.

**Comment by amcewen** [comment]
I'm not 100% sure how such a feature would be described on the lights, but we should make sure we don't get the flickering type again - see https://github.com/DoESLiverpool/somebody-should/issues/808 for the backstory on that.

**Comment by JackiePease** [comment]
2 new ceiling lights have been fitted earlier today. They are quite bright (brightness can be adjusted but this involves accessing the light fittings directly - probably a job for Mick), but don't appear to have any flickering. It would be good to know if people find them acceptable.

**Comment by JackiePease** [comment]
I've spoken to Mick - the new lights are currently on their minimum setting. He's happy for us to use them for a week from now before deciding whether they should be replaced by something else (he's suggesting tubes) - @DoESsean has already mentioned that they're too bright where he's sitting.
Mick says we could make a diffusing layer ourselves if we wanted too. We did have some (HIPS or polycarbonate?) dfiffusing sheet for panel lights - if we can find this or if it's cheap to buy then maybe this is an option.

**Comment by DoESsean** [comment]
For what it's worth, I can cope. They are very bright, but then I tend not
to look directly at lights anyway. It's just a matter of getting used to
the different light quality I think.

**Comment by JackiePease** [comment]
Closing as people seem to be generally ok with the new lights although they are a bit bright - there is a separate issue #1941 for the fuse tripping.
