### ISSUE TITLE
The bench multimeter isn't working

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#193]
The Thurlby 1503 bench multimeter now has batteries.  However, it only turns on briefly and then seems to die.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
There's no tangible call to action in this ticket. Can we get an update as to the current status of the multimeter? Is it still not working? If so, what are the plans - is trying to fix it a case of flogging a dead horse? Should we get a new one (if so, what specifications should we be looking for)? Do we even need one (I assume we do)?

**Comment by aubergine10** [comment]
Would something like this be better (see specifications tab): http://www.extech.com/display/?id=14823

**Comment by ajlennon** [comment]
I've got a bench multimeter knocking around somewhere I could bring in. You can hook it up to a PC for logging and stuff too. Quite need.

**Comment by ajlennon** [comment]
Apparently a: VICHY VC8145 DMM Digital Bench Top Multimeter Meter PC

**Comment by johnmckerrell** [comment]
Where are we with this?

**Comment by ajlennon** [comment]
fwiw I brought it in Vichy other day and showed it to @magman2112. Red thing. It's on the bench

**Comment by chris-does** [comment]
There is a UNI-T UT803 True RMS Multimeter on the bench (it is a red and grey bench-top style unit), serial number 1110709659. Basic testing has shown this to be functional.
http://www.uni-trend.com/index.php?m=content&c=index&a=show&catid=287&id=181

Does the presence of this device supersede all of the above?

If so, I'll update the Electronics Equipment page accordingly.
https://github.com/DoESLiverpool/somebody-should/wiki/ElectronicsEquipment

**Comment by amcewen** [comment]
@chris-does I think you're right, and please feel free to do updating of the wiki :+1: 

The Thurlby is (I think) still in the multimeters drawer, but maybe we should add it to the [Fresh/Stale/Last Chance pile](https://github.com/DoESLiverpool/somebody-should/wiki/FreshStaleLastChance).

**Comment by chris-does** [comment]
@amcewen Thank you for the update.

I have updated the wiki : https://github.com/DoESLiverpool/somebody-should/wiki/Electronics-Equipment

I will check for the presence of the Thurlby when I am next in (likely Thursday 11th July), and if found assign to the [Fresh/Stale/Last Chance pile](https://github.com/DoESLiverpool/somebody-should/wiki/FreshStaleLastChance) as you suggest.

**Comment by chris-does** [comment]
Took me a little longer to get to this than expected; on the plus side, it meant I went through all the other multimeters in the draw too:

1. I cannot find the Thurlby Benchtop Multimeter, so I assume this must have already been disposed off and therefore this issue can be closed.

2. I found three handheld digital multimeters in the "Multimeters" draw, so I have inventoried them (after performing basic checks to confirm they are working - which all three are).

To capture the outcome of this issue and support its closure, I have updated the wiki : [Electronics Equipment](https://github.com/DoESLiverpool/somebody-should/wiki/Electronics-Equipment)

#### Multimeters
 * [UNI-T UT803 Bechtop Digital Multimeter](http://www.uni-trend.com/index.php?m=content&c=index&a=show&catid=287&id=181) (source unknown) - Serial#:1110709659
 * [Tenma 72-7770A Handheld Digital Multimeter](https://uk.farnell.com/tenma/72-7770a/dmm-handheld-manual-3-5digit/dp/2499508) (long-term loan from @johnmckerrell) - Serial#:H160409699
 * [Mastech 8230B Handheld Digital Multimeter](http://mastechturkiye.com/wp-content/uploads/2016/07/MS8230B-Manual.pdf) (source unknown) - Serial#:20041044227
 * [DT-830B Handheld Digitial Multimeter](http://all-sun.com/manual/dt830_en.pdf) (long-term loan from @DefProc) - Serial#:5564200
 * ~~Thurlby 1503 bench multimeter.  Donated by NOC, needs a power supply.  
   http://www.ko4bb.com/Manuals/09%29_Misc_Test_Equipment/Thurlby/Sinclair_Thurlby_1503- 
   1504_Multimeter_Service_Manual.pdf suggests it'll take something between 6.3 and 15VDC.  Needs 6x C cell 
   batteries, and some probes.~~
