### ISSUE TITLE
Service embroidery machine Fred

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1931]
Fred has been in use since before the pandemic (firstly at Sandbox and then at DoES Liverpool), and is probably due a service.

It hasn't been running as smoothly as it used to and has been a bit unreliable at events.

We should look into how we can get it serviced (and any parts replaced) at a reasonable cost.

**Comment by JackiePease** [comment]
Maker Night visitors suggested trying Weaver Dee, based in Middlewich 

Website has these details: 

FULL SERVICE:
• Most sewing machines, overlockers, embroidery only machines:
£79 + Spare parts

COLLECTION & DELIVERY

Collection & return nationwide:
We can arrange collection and return if you are unable to bring your machine to us. In most cases, this will cost an extra £20 in total. Contact us for more details.

**Comment by JackiePease** [comment]
Bamber Sewing Machines (in Eccles, but recommended by people in Liverpool) charge £98 plus VAT plus any parts

**Comment by JackiePease** [comment]
@magman2112 and I have just visited SewEurope on Rice Lane. They service domestic embroidery machines for £75 inc. VAT (plus any parts). 
We would have to take the machine there then they deal with them in the order they come in.
Details:
Stan Toth (Operations Manager)
88 Rice Lane
Liverpool 
L9 1DD
0151 525 0511
They also service industrials in situ for £65 plus travel costs.

**Comment by Knottyashcreative** [comment]
Would it not be possible for staff from the DOES repair cafe to service then or train then up and do they can service future sewing machines

**Comment by JackiePease** [comment]
I've taken the embroidery machine to EuroSewing (a.k.a. A+A) at 88 Rice Lane. It should take around a week and the standard cost (without any extra parts) is £75.

Note: @Knottyashcreative has suggested asking a technician to do the next sewing machine service on site and asking them to train up one or two of our community members. He wasn't able to arrange this in time for this service, but is still  investigating.

**Comment by JackiePease** [comment]
I've spoken to Eurosew. The embroidery machine isn't ready yet. The person in the shop wasn't sure why, as it has been looked at. The people who were working on it aren't back until tomorrow. He'll phone me then.

**Comment by JackiePease** [comment]
@magman2112 collected the machine last week. It was used for an induction at Maker Night and appears to be working fine.
