### ISSUE TITLE
Doorbell isn’t sounding

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1932]
The small black doorbell next to the front door, on the first floor landing, doesn’t ring when you press it. The blue light comes on, but nothing else.

**Comment by johnmckerrell** [comment]
Is the internal party fully pushed into the socket? I.e. is it actually plugged in?

**Comment by zarino** [comment]
Yes, the receiver inside the main room is plugged in, and pressing the button on the top of the receiver makes an audible chime.

**Comment by zarino** [comment]
Hmmm… I just tried it again on my way out, and now it’s working 🤔
