### ISSUE TITLE
The HVAC in the Fibre Arts room isn't working

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1934]
@Robotorium mentioned that the HVAC hasn't been working since the rendering was done. I phoned Envirocool on Friday and they said they'd try to send someone out today. That hasn't happened so I've just contacted them via WhatsApp to check whether they're coming tomorrrow. I'll get back to them during office hours.

**Comment by JackiePease** [comment]
Envirocool say they're coming tomorrow (Wednesday 7th August) after 1pm

**Comment by JackiePease** [comment]
Envirocool person came in on Wednesday and found that there was no power to the HVAC.

He spoke to Mick the electrician on the phone. 

It seems that this unit was previously connected to the electricity supply on the ground floor and this couldn't be reinstated after the rendering was done. Mick was supposed to find out where it could be connected.

This is with Mick now - he hasn't yet got back to us.

**Comment by JackiePease** [comment]
Mick will investigate further tomorrow

**Comment by JackiePease** [comment]
Mick has identified the lower right switch in the fusebox as the one which supplies the power to the Fibre Arts Room HVAC, and labelled it. He says there isn't a problem with the power supply and that the issue is with the compressor. He's told Rick from Envirocool, and they will arrange another visit.

**Comment by JackiePease** [comment]
I have checked with Mick the electrician who tells me that there is no problem with the electrics and this issue should be with Envirocool. I've messaged Envirocool and will get back to them this afternoon if I don't hear anything by then.

**Comment by JackiePease** [comment]
Envirocool phoned to say they should be round tomorrow afternoon

**Comment by amcewen** [comment]
Envirocool visited.  The power was all good, but there was a problem with the (comms) cable connecting the indoor unit to the one outside.  They've replaced that and the unit is both chilling and heating the room as expected :tada:
