### ISSUE TITLE
Sophia's laser is mis-aligned

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#194]
Sophia isn't cutting through 1.5mm acrylic on speed 10 power 50.  Investigating further shows the laser is barely making it into the hole before the beam is directed down.

She'll need the alignment correcting (http://www.rabbitlaserusa.com/Manuals/BeamAlignment.html is the current go-to procedure for that)

**Comment by DefProc** [comment]
realligned.
