### ISSUE TITLE
Fuse for main room tripped when I switched the lights on

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1941]
Could be related to the new lights. I've messaged Mick to ask him to check when he's next in.

**Comment by amcewen** [comment]
Terry has reported this happening another two times since.

I bumped into Mick just now and mentioned it to him.  He's going to call in sometime on Thursday to check the breaker.

**Comment by JackiePease** [comment]
Mick says he replaced the circuit breaker a few weeks ago. @Knottyashcreative confirms that we haven't had this issue since.
