### ISSUE TITLE
Shelf in kitchen fridge

### ISSUE THREAD

**Issue by SayBeano** [DoESLiverpool/somebody-should#195]
Bottom shelf is broken, making it risky / hard / difficult to open the bottom left salad drawer.

I'm imagining some kind of acrylic could go in there. It could also get etched if that helps with labelling where things could/should go in the fridge too.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.
