### ISSUE TITLE
Hand dryer in more accessible loo has lost the power to blow your hands off

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1953]
I noticed yesterday that the hand dryer in the accessible loo was no longer putting me at risk of terrible peril with its power. I realised at a glance that there seemed to be a part in the wrong place, so I opened it up and found that the funnel concentrating the air downward had fallen off. Two of the three screwholes are broken, and the third is fine but the receiving hole is broken for that one.

![02](https://github.com/user-attachments/assets/3ca89840-ccf5-4684-a084-e0ca078b4446)
![01](https://github.com/user-attachments/assets/bf60bf42-e354-4c95-b279-48bc6b38fdc1)

I took off the rubber gasket that sits between the funnel and the rest of the machine, and I recreated it in Inkscape.

![03](https://github.com/user-attachments/assets/41303d71-6e2d-4e3f-ade5-7c831d3976f1)

@huffeec printed that on paper, so we could hold the gasket up to it and make sure it fit, then I imported the svg into the 3D design and used it as the base. My lovely daughter printed it in PETG for better heat resistance, at 100% infill for extra durability.

![04](https://github.com/user-attachments/assets/8b262932-a359-453d-94ad-4a2ae9148fcf)

I attached it using the two useable screwholes this morning, with the gasket in place.

![05](https://github.com/user-attachments/assets/2718bd5a-3176-4c60-b42d-aafc0258a11b)

It fit and works but it's slightly off kilter because I eyeballed some of the measurements that weren't screw-dependent, as per who I am as a person.

![06](https://github.com/user-attachments/assets/6e20bde5-54b0-4938-89fb-fae9ee21f4b2)

But it does in fact work. I'll get the new version printed and installed soon so it's even better, but your hands will now dry faster than they would if you dangled them loosely behind a flatulent cat. I'll attach the stl in case we need it in future, once I'm sure it's right.

![07](https://github.com/user-attachments/assets/587a035b-bef4-4040-b551-7e87c81fe6ce)

Thanks hand dryer! I WILL feel the air!

**Comment by amcewen** [comment]
Thanks (both for the repair and the write-up! :grinning:)

If you can stick the final STL [somewhere-safe](https://github.com/DoESLiverpool/somewhere-safe/tree/master/designs) that'd be ace.  (I'm not sure which of the "toilets" or the "3dprinter" folders are best, but either will work I'm sure)

**Comment by Robotorium** [comment]
Will do, she's printing mach 2 today and I should be in to install it on
Friday :)

Op wo 23 okt 2024 om 12:11 schreef Adrian McEwen ***@***.***>:

**Comment by Robotorium** [comment]
I came in today and installed version 2:

![08](https://github.com/user-attachments/assets/d40b048d-6c69-4114-8598-1376e5e071cf)
![09](https://github.com/user-attachments/assets/848f87af-2b85-4e99-9a8b-38a667aea8c2)

When I replaced the shell, I was pretty happy with the location of the spout, so I'm closing this thread. I've uploaded the relevant stl to somewhere-safe, imaginatively named [replacement funnel hand dryers.stl](https://github.com/DoESLiverpool/somewhere-safe/blob/master/replacement%20funnel%20hand%20dryers.stl)
