### ISSUE TITLE
Tony not cutting cleanly

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1955]
Sasha was unable to cut earrings on 10/80 on Tony. 

Edges looked a big ragged and the cut didn't go all the way through 3mm acrylic.

**Comment by JackiePease** [comment]
@DoESLiverpool/laser-maintenance

**Comment by magman2112** [comment]
After cleaning a very dirty lens, cleaning the mirrors and adjusting a misalignment on the x-axis, Tony is cutting well again.
