### ISSUE TITLE
doorbot 3 has been offline for ages

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#196]
And it's long enough that it's out of sync with the current RFID key list. 

What's the best method to get it back on the wifi?

**Comment by johnmckerrell** [comment]
Isn't it supposed to be plugged in? If not then plugging Ethernet in would of course be best way to debug. 

--

**Comment by amcewen** [comment]
The ethernet cable wasn't completely securely in, but clicking it into place didn't help.  Neither has rebooting the router.  (Out of time to do any more digging now)

**Comment by DefProc** [comment]
Never mind, I rebooted the pi, and the ethernet came back up.

**Comment by DefProc** [comment]
But it's dropped off the network again.

**Comment by johnmckerrell** [comment]
Rebooted it and it came back online on the correct IP address, will mark this closed for now but feel free to reopen if it continues to have issues.

**Comment by DefProc** [comment]
doorbot reload-all-config today can't find doorbot 3 again.

**Comment by amcewen** [comment]
I've switched it to have a static IP address (...125 still) to see if that makes its networking more stable.

**Comment by amcewen** [comment]
This is still up, so I think we can claim it as a decent improvement.
