### ISSUE TITLE
Heater in Fibre Arts Room - Tripped Fuse Box

### ISSUE THREAD

**Issue by NickB1982** [DoESLiverpool/somebody-should#1964]
I have got around this by using the Hvac, however I ont know whether there is a problem with the plug in heater which may need to be looked at.

**Comment by JackiePease** [comment]
Not sure if this is related to issue #1280

**Comment by Knottyashcreative** [comment]
Happened to me too, needs fixing or recycled

**Comment by amcewen** [comment]
I've moved it out of the fibre arts room, given we've now got (better) heating working in there again.

To try to work out if it's a fault in the heater or if it was just pushing the current too high on that circuit, with the servers, etc., I've plugged it in on the centre sockets circuit in the main room.  We started it around 11am, can't remember exactly when; it's still running okay now.

Will leave it a bit longer and then try setting it to regularly turn itself on/off in case that's what's tripping things.

**Comment by amcewen** [comment]
It's been running okay all afternoon.  The thermostat doesn't seem to work on it any more, so I couldn't set it to turn itself on/off.  I did try putting it under a desk to see if it was something related to it being in a more confined space, but beyond surprising Neil when he sat down next to it, there weren't any other issues.

I think the key thing is not to run it in the Fibre Arts room :grinning:
