### ISSUE TITLE
The Ultimaker isn't extruding cleanly

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#197]
The Ultimaker Extended hasn't been happy for over a week now.  The usual tricks of running it slower/hotter and clearing out the nozzle with the "cold pull" method haven't improved matters.

Raising this issue so we can track what people have tried, and hopefully circle in on a solution.

**Comment by amcewen** [comment]
Tried out Ed's hypothesis that it might be the room temperature causing issues, by moving the printer into the office (and putting the heating on, so Yahms was reporting the room temp as 25 degrees).

Annoyingly that didn't have any effect.

When I did a cold pull, it was really difficult at the previously-easy-to-pull temp of 80 degrees, and even with the nozzle temp higher, some of the old filament being pulled out looked white - and there hasn't (to my knowledge) been any white run through it of late - only the dark blue, smoky black, and pink (I was doing the cold pull with silver).  I don't know if that means the white plastic part (PTFE?) feeding into the nozzle is starting to degrade?

**Comment by DefProc** [comment]
I did a full teardown and rebuild (http://support.3dverkstan.se/article/56-replacing-the-ptfe-coupler) to check the ptfe coupler. It's looking a little black at the hot end, and there did seem to be some deflection there too, but the filament still ran cleanly through. I did trim back the internal lip to make sure it's smooth though. Unfortunately, the Ultimaker robot was still underextruded after the clean out. 

When I did 8 cold pulls last week, I was seeing some copper flakes in the filament (which would account for a blocking nozzle) though I'm not sure where they might have come from. There is some copper grease around the nozzle, but there shouldn't be any inside. 

I did see some brittle white residue, but I didn't find a source for that (and it wasn't clear if there was or wasn't any of that inside the nozzle!).

**Comment by amcewen** [comment]
I've found the troubleshooting guide that I'd used last time there were problems with this - http://support.3dverkstan.se/article/23-a-visual-ultimaker-troubleshooting-guide#underextrusion

**Comment by DefProc** [comment]
I've ordered an Ultimaker Hot End Pack, on the basis that if it's not the nozzle that's a problem now, we'll have a fresh spare later. It's expected tomorrow.

**Comment by DefProc** [comment]
I've fitted the new hot-end pack (including a new nozzle). The inital print is looking good so far, and I could turn the print speed up to 125% without underextrusion.

**Comment by jackie1050** [comment]
😊

Sent from my Windows Phone
________________________________

**Comment by amcewen** [comment]
Seems to be printing very nicely with the new hot end.  Works better with the temperature dialled back to 200 deg C rather than 210.
