### ISSUE TITLE
Light over Russ's desk flickering

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1970]
The ceiling light over Russ's desk is flickering. Sometimes it starts as more of a shimmer but it becomes very dramatically flickery to the point where we're sitting in semi-darkness today.

**Comment by JackiePease** [comment]
This looks like the same issue as #1928 - not surprising as the lights have been there for the same time. Also possibly related to #1941. It's working ok today, but the fault in #1928 was intermittent for a while too.
I've messaged Mick to get him to look when he's in.

**Comment by JackiePease** [comment]
Mick says he'll be in next week

**Comment by JackiePease** [comment]
This has now been replaced
