### ISSUE TITLE
Setup automated doodle pole dooda to assist with personing makernight

### ISSUE THREAD

**Issue by Thingomy** [DoESLiverpool/somebody-should#200]
There exists a system that uses doodle poles and email notifications to assist organisation of general event cover, it would be good if this could be extended/modified to cover makernight also.

Specifically we have a desire for 2 people to provide cover, one of which should be "experienced". If the system aims for getting even the first of those people organised, it would work out fine in the vast majority of cases. Aiming for 2 people from the list could work too.

The makernight list will be a different list from the normal list. However having the "normal" list notified if there is imminent people shortage could be handy as most of the experienced DoES people would have the knowledge to run makernight at a pinch.

In general, it sounds useful, and whatever it does it's going to be better than the (so far 100% successful) some people turn up, or sometimes email if they aren't going to be in, strategy.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by johnmckerrell** [comment]
No longer feasible as Doodle API changed.
