### ISSUE TITLE
Set up email list for makernight

### ISSUE THREAD

**Issue by Thingomy** [DoESLiverpool/somebody-should#201]
An organisers email list for maker night would be handy for internal and external communications.

makernight@doesliverpool.com ... has been suggested.

**Comment by amcewen** [comment]
I've set up that group, and added the people I think should be on it.  Will close once I've checked the full list with @Thingomy.

**Comment by amcewen** [comment]
This needs issue #224 to be fixed before it's much use.

**Comment by amcewen** [comment]
...but the list is there now, and does get used by the makernight organisers from time to time when we're checking availability of the rest of us.

So closing this now.
