### ISSUE TITLE
Set up new internet connection properly

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#202]
We have a new faster internet connection. It is currently an independent WiFi SSID. We need to migrate our network over to it so that we can cancel the old connection. This issue should capture the things we need to do.

Apparently we should have a static IP address and the "modem" is currently "open" so we shouldn't need to do port forwarding, apparently. First step would be to unplug the WAN port from the existing router and plug it into the new one and see if that just works. If not we then need to look at port forwarding etc.

- [x] Turned off TP-Link
- [x] Renamed Fibre-AP to DoESBackup
- [x] Renamed Airport to DoESLiverpool
- [x] Configured port forwarding for corridor camera (now on port 8085)
- [x] Configured port forwarding for doorbot1
- [x] Transferred ethernet cables from TP-Link
- [x] Setup TP-Link in Dinky
- [x] Configured port forwarding for main room camera
- [x] Configured port forwarding for workshop camera
- [x] Configured port forwarding for workshop door camera
- [x] Configured port forwarding for room29 camera
- [x] Configured port forwarding for doorbot2
- [x] Configured port forwarding for doorbot3
- [x] Point hostname at new IP address

**Comment by ReddbridgeMark** [comment]
By modem is "open" I take it this means there is no shared firewall currently in place hence no port forwarding? 

Even though it's something else to have to do to set up PF, I'd suggest it would be worth it to get a central firewall up and rules in place, so that internal traffic is just that and adding an additional layer of protection to those using the connection along with any firewall on the individual bits of equipment they are using.

**Comment by johnmckerrell** [comment]
As the individual computers are NAT-ed I've tended to assume this means they wouldn't be accessible externally.

Just chatted to Efuse and we've got a support email address. It sounds like we'll need to talk to them to get the port forwarding done when we're ready to combine the networks.

**Comment by johnmckerrell** [comment]
I now have the details for the modem so can do this when I get time (or someone else can when they get time).

**Comment by amcewen** [comment]
What's the plan with the TP-Link that was doing the old network?  Is that just going to be retired (or set up as an access point in the Workshop or something)?  Or is that going to be our main WiFi with the new modem as a backup?

**Comment by johnmckerrell** [comment]
We have a few options.

Continue to use the TP-Link in the main room.
 * "Easier" as everything will be setup already and we'd just have to port forward from the fibre modem to the TP-Link.
 * Not as fast as Airport, has had occasional problems.

Use the new fibre AP
 * Makes use of hardware we must have around anyway.
 * Not as fast as Airport, not even 5GHz like TP-Link.

Use the Apple Airport
 * Fastest Wi-Fi hardware we have.
 * Doesn't support setup on linux.

We could even run all three pieces of hardware, or maybe that's excessive and we should just have the fibre modem deal with DHCP reservation & port forwarding then the Apple Airport as the AP.

**Comment by amcewen** [comment]
We could leave the Airport in Dinky as that often gets used for events and so would benefit from the extra capacity, and ditch the WiFi on the fibre modem and use the TP-Link to provide the WiFi in the main room?

**Comment by DefProc** [comment]
@johnmckerrell have you put the login details with the DoES passwords yet?

**Comment by johnmckerrell** [comment]
Discussed a bit with @amcewen, we came to the conclusion that the best option is probably to have the Fibre Modem/AP + Airport in main room and move the TP-Link through to Dinky (which will mean 5GHz in two rooms).

The Airport will advertise a 5GHz and a 2.4GHz AP under the same SSID so will be simpler than the existing setup (assuming it works fine with non-apple devices). The Airport can only be setup from Mac or Windows though which is non-ideal.

Port forwarding and DHCP reservations will need to be copied to the Fibre Modem. The Fibre Modem's SSID could perhaps be left live but changed to "DoES Backup" or something like that with the Airport given the "DoES Liverpool" SSID.

Once complete we can update the hostnames pointing to the old external IP address and cancel our Eclipse subscription!

**Comment by johnmckerrell** [comment]
Current status:

[x] Turned off TP-Link
[x] Renamed Fibre-AP to DoESBackup
[x] Renamed Airport to DoESLiverpool
[x] Configured port forwarding for corridor camera (now on port 8085)
[x] Configured port forwarding for doorbot1
[ ] Transferred ethernet cables from TP-Link
[ ] Configured port forwarding for workshop camera
[ ] Configured port forwarding for workshop door camera
[ ] Configured port forwarding for room29 camera
[ ] Configured port forwarding for doorbot2
[ ] Configured port forwarding for doorbot3

**Comment by johnmckerrell** [comment]
All the urgent tasks now complete, suggest we come back to this next Thursday and if we haven't had any problems go ahead with cancelling Eclipse. I'm fairly sure our phone number is still with Zen but it would be pertinent to check!

**Comment by johnmckerrell** [comment]
Just called them just to make sure, we have to give 30 days notice but it's pro rata so there's no urgent need to do it by any specific date. Maybe we can give it just a few days rather than a whole week but it shouldn't make too much difference.

We will have to pay 30+VAT to stop each DSL line, so we'll have to pay twice, and our line rental and phone line *is* with Zen.

**Comment by johnmckerrell** [comment]
For the record the Wi-Fi had a wobble this morning, seemed to go wrong for all non-Apple users. Restarting the Airport did the trick.

I've also now updated the main hostname to point at the new static IP address (btw @amcewen your CNAME seems to have a typo).

I'll try to get the Eclipse contract cancelled today.

**Comment by johnmckerrell** [comment]
Eclipse now cancelled and broke out the TP-Link task as #223 so now closing this issue.
