### ISSUE TITLE
Put B&W laser printer on the network

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#203]
I've replaced the broken colour printer with a working black and white laser printer. If does not have network functionality but we could look at plugging it into the wifi AP or a TP-Link.

**Comment by amcewen** [comment]
Would a Raspberry Pi as a CUPS server work too?  There's the spare rev1 Model B from Doorbot1 knocking around that could probably run it?

**Comment by amcewen** [comment]
I've got part-way towards the Raspberry Pi solution - the old Doorbot Pi is currently connected to the printer, and on the (new) network, and should be responding to ssh pi@does-printer.local.  However, I'm currently on the old network, so can't SSH into it to finish setting things up (CUPS is installed, but not configured - I was following http://www.raspberry-pi-geek.com/Archive/2013/01/Converting-the-Raspberry-Pi-to-a-wireless-print-server/%28offset%29/2 as a first try...)

**Comment by amcewen** [comment]
Given that we've new printers that are installed and on the network, we no longer need to get this one online.
