### ISSUE TITLE
Set up domain for DoES slack

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#204]
We now have a slack-in instance on heroku. Can we get slack.doesliverpool.com to point at it? You can find it here. 

https://doesliverpool-slack.herokuapp.com/

**Comment by amcewen** [comment]
I think this is now set up.  Suspect it'll need a little while for the DNS to propagate.

**Comment by amcewen** [comment]
DNS seems to have propagated (from 34sp.com to DoES' internal network at least...)
