### ISSUE TITLE
Publicise Slack instance http://slack.doesliverpool.com

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#207]
We have a slack instance at http://slack.doesliverpool.com so we need to talk about it on, at least,  Twitter, Facebook and the mailing list to get people on there.

**Comment by johnmckerrell** [comment]
- [ ] Twitter
- [ ] Facebook
- [ ] Mailing List

**Comment by OddEssay** [comment]
There is an embedable button we can ad to the website:
```<script async defer src="http://slack.doesliverpool.com/slackin.js?large"></script> ```
As per https://github.com/rauchg/slackin

**Comment by DefProc** [comment]
@OddEssay: Ok, that's in the side bar

**Comment by DoESsean** [comment]
Sent a mail to the Group, and tweeted about it, so that goes to both
Twitter and FB.
