### ISSUE TITLE
Fix plasma screen mountings

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#21]
One of the bolts holding the plasma screen up needs fixing.

After investigation by me the best option is probably to use pliers to remove the remaining piece of nut from the mounting bolt, remove the mounting bolt ("somehow") and then insert a bolt that will "permanently" stick out of the tv, and would be secured on the other end by nut/nuts. This assumes there's enough depth to get this bolt in there.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
