### ISSUE TITLE
Revise the General Financial forecast to attempt to make it more accurate

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#210]
We should review our income & outgoings and try to see if we can better capture things to put into the forecast, at the least just updating the hardcoded figures for petty cash etc.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by johnmckerrell** [comment]
@DoESsean and I are meant to be doing this soon

**Comment by johnmckerrell** [comment]
I think this is about as done as it's going to be. There's also this tool for pulling interesting information out of FreeAgent dumps: https://github.com/DoESLiverpool/financial-report
