### ISSUE TITLE
Install secure points to lock bikes to

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#211]
After the recent theft we've decided to install something(s) that will allow us to securely lock bikes up in the corridor.

**Comment by DefProc** [comment]
I had a chat with Jeanette this morning, and we're OK to bolt things to the wall, providing we allow for suitable fire access in the area. 

OK, I've had a look at the available wall anchor solutions that are specifically for bikes (rather than using handles etc.) and there are two main options in the "not ultra high security" category, and that will allow us to remove and take them with us if/when we move: 

 * at £10 each, the functional Master Lock anchor: http://www.screwfix.com/p/master-lock-wall-floor-anchor-steel-small-128mm/59959
 * and the at £25 each, a smiling, UK made, wall hoop: http://www.hbdesigns.co.uk/product/products/bike-wall-anchor/

The smiling one does provide the extra security of keyed anti-tamper bolts, where as the Master Lock one seems to have normal hex headed bolts, so I'd be happier leaving a bike overnight, unattended, outside on the smiley ones.

**Comment by johnmckerrell** [comment]
Delivery included and doesn't look like there's a discount for (small) quantities so perhaps just get one and evaluate?

Quite tempted by "Custom shapes and colours available upon request" but can't quite think what DoES would prefer ;-)

**Comment by DefProc** [comment]
Ask a designer? @redviolet

**Comment by johnmckerrell** [comment]
I'm guessing they'll be pricey, let's just get a smiley, @redviolet can pick a colour? ;-)

**Comment by Red-Violet** [comment]
Hello!

I don't like the horrible bit of metal. I think that the smiley ones are cool and the yellow, white and orange would look great in the corridor. 

I think if you are going to put in secure bike parking it is important that there is enough space for everyone to park their bikes.

I say get 5 and then the job is done and there is no need to revisit it later.

 :-) :-) :-) :-) :-)

On 4 November 2015 20:52:06 GMT+00:00, John McKerrell <notifications@github.com> wrote:
>I'm guessing they'll be pricey, let's just get a smiley, @redviolet can
>pick a colour? ;-)
>
>> On 4 Nov 2015, at 16:30, Patrick Fenner <notifications@github.com>
>wrote:
>> 
>> Ask a designer? @redviolet
>> On 4 Nov 2015 13:48, "John McKerrell" <notifications@github.com>
>wrote:
>> 
>> > Delivery included and doesn't look like there's a discount for
>(small)
>> > quantities so perhaps just get one and evaluate?
>> >
>> > Quite tempted by "Custom shapes and colours available upon request"
>but
>> > can't quite think what DoES would prefer ;-)
>> >
>> > > On 4 Nov 2015, at 12:50, Patrick Fenner
><notifications@github.com>
>> > wrote:
>> > >
>> > > I had a chat with Jeanette this morning, and we're OK to bolt
>things to
>> > the wall, providing we allow for suitable fire access in the area.
>> > >
>> > > OK, I've had a look at the available wall anchor solutions that
>are
>> > specifically for bikes (rather than using handles etc.) and there
>are two
>> > main options in the "not ultra high security" category, and that
>will allow
>> > us to remove and take them with us if/when we move:
>> > >
>> > > at £10 each, the functional Master Lock anchor:
>> >
>http://www.screwfix.com/p/master-lock-wall-floor-anchor-steel-small-128mm/59959
>> > <
>> >
>http://www.screwfix.com/p/master-lock-wall-floor-anchor-steel-small-128mm/59959
>> > >
>> > > and the at £25 each, a smiling, UK made, wall hoop:
>> > http://www.hbdesigns.co.uk/product/products/bike-wall-anchor/ <
>> > http://www.hbdesigns.co.uk/product/products/bike-wall-anchor/>
>> > > The smiling one does provide the extra security of keyed
>anti-tamper
>> > bolts, where as the Master Lock one seems to have normal hex headed
>bolts,
>> > so I'd be happier leaving a bike overnight, unattended, outside on
>the
>> > smiley ones.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub <
>> >
>https://github.com/DoESLiverpool/somebody-should/issues/211#issuecomment-153711934
>> > >.
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> >
><https://github.com/DoESLiverpool/somebody-should/issues/211#issuecomment-153723776>
>> > .
>> >
>> —
>> Reply to this email directly or view it on GitHub
><https://github.com/DoESLiverpool/somebody-should/issues/211#issuecomment-153783742>.
>> 
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DoESLiverpool/somebody-should/issues/211#issuecomment-153861587

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DefProc** [comment]
One fitted, how long should we wait for testing and validation before ordering the others?

**Comment by johnmckerrell** [comment]
Does it work? Is it easy enough to get a bike on? Does it seem like there'd be room to fit 2 bikes to 2 plates on one section of wall? I doubt I'll get in to take a look any time soon (though you never know).

**Comment by DefProc** [comment]
That first one is outside the main door. It definitely worked foe Martin to
D-lock his bike to this afternoon, but I'll have a look at the other
positions for the space.

Patrick

**Comment by DefProc** [comment]
The next 4 are on order

**Comment by DefProc** [comment]
They haven't arrived yet, so these'll go up in January.

**Comment by jamieisboss** [comment]
this is on sale on amazon

http://www.amazon.co.uk/dp/B00FO5TQOC/

It's a lot of money off in the january sale, and it seems like a big solution, overkill? 

I've got prime so it could be delivered on wednesday

**Comment by DefProc** [comment]
I'm not sure that it would work in the corridor if it needs the bikes to be perpendicular to the wall, but either way, I have the remaining 4 smiles to fit.

**Comment by DefProc** [comment]
Fitted.
