### ISSUE TITLE
Improve the CCTV infrastructure

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#212]
Add monitoring to more cameras and upgrade cameras where possible.

**Comment by amcewen** [comment]
Add the meeting action label as it was mentioned in the Organisers meeting - http://wiki.doesliverpool.com/DoESMeetingMinutes20151029

**Comment by jamieisboss** [comment]
~~Another ebuyer special, [4 camera kit (can add 4 more) built in motion detection](http://www.ebuyer.com/737069-homeguard-pro-858041tb-hd-pro-series-720p-camera-1tb-858041tb) so no endless hours of overnight footage, no alarm function but rs-485 control and ethernet so i assume alarm speifically means builing alarms and alerts for out of hours movement would be possiblle if not built in. just shy of £270 and the cameras are ip66 rated so the workshop dust shouldn't kill them~~

God bless amazon 4 poe ip cameras ip66 plus 4ch recorder (add your own hdd) [£140 for 720p ](http://www.amazon.co.uk/dp/B00NZWIZYS?psc=1) or [there's a tonne of them](http://www.amazon.co.uk/s/ref=sr_pg_4?rh=n%3A79903031%2Cn%3A%2179904031%2Cn%3A1939527031%2Cn%3A1939541031%2Cn%3A1939544031&page=4&sort=review-rank&ie=UTF8&qid=1454687734)

i like that you could set the motion detector to trigger heavy bolts on the doors, probably release some window shutters so they roll down and lock, then flash strobe lights and play german club music constantly while streaming the whole thing on youtube. In theory, it'd take a bit of fiddling but the components aren't particularly expensive, the roller shutters would be the most expensive bit. Maybe you could have a servo move a piece of card blocking an exit sign next to a now open window, enough strobes and a plank of wood nailed outside so it feels like a step. No more robbers and vandals.

but then i suppose you'd need extra cameras for the exterior then, and probably some legal obligation to  alert more than one emergency service.

but asterisk is open source and you can run it on an RPi2 and that could easily play a prerecorded 999 message, in fact it would do TTS

**Comment by johnmckerrell** [comment]
Very jealous of how much spare time you have To do all this Jamie ;-)

While i was in today I tried unplugging and replugging the corridor camera and realised the plug had been loose so hoping it will be a bit more stable now. 

--

**Comment by jamieisboss** [comment]
It was a little worrying how quickly that all came to mind but it was a short mental break from a huge sprint of work i assure you, I stopped and got back to it as soon as I caught myself typing the words "large trampoline" into amazon

**Comment by johnmckerrell** [comment]
Notes from meeting 20160614 - New HD corridor camera has been added, pingdom monitoring was set up but is no longer working, me to fix.

**Comment by johnmckerrell** [comment]
Also remove the old corridor camera from the wiki.

**Comment by johnmckerrell** [comment]
Have now fixed the pingdom monitoring although it seems the free plan is going away so not sure how long that will last. Also removed the old corridor from the wiki. Setting this issue closed, we'll open a new one for future work.
