### ISSUE TITLE
The preferred DNS server on the new network refuses requests

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#215]
The new faster Internet connection gives out 79.98.167.69 as the primary DNS server, but that server refuses requests.

I've been getting regular DNS failures in general browsing - refreshing the page a few times will eventually pick up the DNS from the secondary server, but it's not ideal.

Trying to set up the Air Quality Egg that we've been given this evening, that only uses the primary DNS server, and so can't connect out to the Internet at all.  I've tried setting it to use IP addresses rather than hostnames, but it doesn't seem to support that :-(

**Comment by DefProc** [comment]
Can we change the DNS settings on the router? Would it be better to 
switch it to OpenDNS or somewhere else if we're having problems?

**Comment by johnmckerrell** [comment]
I couldn't find a setting for that, I'll ping the support address to see what they say.

**Comment by johnmckerrell** [comment]
Speedy response from Efuse, unfortunately it looks like this is set (or at least specified) downstream (by Metronet?) so they can't do anything in the short term. Annoyingly of course if we'd left the TP-Link in place we wouldn't have this problem! I can try checking if the Airport will let me set alternative DNS settings or you could ask a mac user tomorrow to see if they can (I think at the moment they won't need an admin password).

**Comment by johnmckerrell** [comment]
"It might be a temporary issue on this primary DNS server so we are raising a quick ticket with the host. If by tomorrow pm this is not resolved we will permanently switch 8.8.8.8 to be the primary DNS."

**Comment by amcewen** [comment]
Cool.  I'd also had a poke around to see if we could change it and couldn't spot anywhere that we could.

**Comment by johnmckerrell** [comment]
"Found another DNS specified by the core ISP so we have just replaced the primary DNS with 77.75.184.5. Please feel free to test again. The change is permanent."

Any better?

--

**Comment by amcewen** [comment]
Seems to be working fine today, and the Air Quality Egg has been able to get online successfully too.  Thanks for sorting it out @johnmckerrell!

**Comment by amcewen** [comment]
Hmm, "The change is permanent" until it isn't.  The past couple of days I've been getting DNS failures again.  Checking with wireshark now it seems I'm being given 79.98.167.69 again as the primary DNS, and still getting refusals from it.

It seems that we can set DNS servers in the admin for the router, but that requires a reboot of it.  I'll give that a try when things are quieter in the office

**Comment by amcewen** [comment]
I suspect this will be causing the problem with the heating in issue #251, given that the Arduino DNS client just takes the first DNS server it's given in the DHCP response...

**Comment by amcewen** [comment]
The manual ones were set to (although the manual DNS setup wasn't enabled):
 * 168.126.63.1
 * 168.126.63.2

I've updated them to:
 * 77.75.184.5
 * 8.8.8.8

And that seems to have improved matters for my laptop.  Sadly it didn't seem to fix issue #251 :-/

**Comment by amcewen** [comment]
Spoke too soon - it hasn't fixed issues for my laptop, but I'm still being given 79.98.167.69 as the primary DNS.

So I don't know what the DNS server setting in the router actually does, but it doesn't appear to fix things :-/

I've emailed our Internet provider's support to hopefully get it resolved.

**Comment by amcewen** [comment]
Has been fixed again now.
