### ISSUE TITLE
Pre-prepare digital versons of fliers and advertising materials

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#217]
We need some 1-page ads in the appropriate formats in A4, A5 and A5 landscape.  

Recently we got offered some free advertising in a magazine/programme booklet, but we didn't have anything we could give at that time.  This is a job that needs to be done in advance and the files put somewhere safe where we can find them in a hurry.

Recycle these designs as fliers as well which we can do as a print run, say.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
The issue of access to digital branding materials was raised at the recent organisers' meeting, as well as plans to take a firm look at the vision and marketing of DoES. It would also be good to have a Press (or whatever) section on the website - even if it just links to a wiki page with the files.
