### ISSUE TITLE
DoES Meeting Agendas should go into own repository 

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#218]
Pages like this one:
    http://wiki.doesliverpool.com/DoESMeetingAgenda201512

Going forward it could be done as a wiki somewhere else, or as an single monthly issue page on the somebody should issues tracker that gets closed after the date, or what.  

Once that is decided, we'll know where to put the historical data before decommissioning the old wiki pursuant to Issue #97

**Comment by amcewen** [comment]
Adding the meeting action label so this gets discussed at the next organisers meeting :-)

**Comment by johnmckerrell** [comment]
Notes from meeting 20160614 - Agreed, can write in markdown in-place in github, will go ahead with this. Should copy old ones across to a new repo and put new ones there too.

**Comment by amcewen** [comment]
I haven't done anything on this yet.  Rolled over to next organisers meeting.

**Comment by amcewen** [comment]
They're now in the github wiki.
