### ISSUE TITLE
Create a virtual scale survey of the room size and layout

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#219]
Don't know what's the best format.  

Could do it in Onshape as a floorplan.

Then have some dimensionally correct models of the large objects (eg laser scanner) that can be "assembled" into different parts of the room to show how they fit.

Could be used as a basis for reviewing the space in any future offices

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by amcewen** [comment]
Given for #571 we ended up with a simpler assorted-sizes-of-rectangles approach, I'm thinking we can close this off now.
