### ISSUE TITLE
The RepRap laptop doesn't boot

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#22]
The original (RM?) laptop that we used for the RepRap stopped booting.  As an attempted temporary fix we swapped it for the one Carlo had used, but Pronterface on that crashes as soon as it moves the extruder to the start of the print.

We need to get one of them up and running to be able to talk to the RepRap.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
