### ISSUE TITLE
Setup the TP-Link router as an AP in Dinky

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#223]
Breaking this issue out of #202 so that it can be closed.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by DefProc** [comment]
Add there is an AP in Dinky, this can presumably be closed
