### ISSUE TITLE
We need a way of managing cover for opening and closing

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#224]
It claimed there was an error with the iCal, I'll need to investigate when I get time.

**Comment by johnmckerrell** [comment]
iCal issue was a simple fix but it seems Doodle have discontinued their API too, this is covered here: https://github.com/DoESLiverpool/cover-requester/issues/8

**Comment by amcewen** [comment]
Organisers' meeting notes: We've got a Google calendar for people to use rather than Doodle, but it doesn't send emails if we're short on cover yet.

**Comment by johnmckerrell** [comment]
Updated the title as we need a new system for managing this but we're not expecting it to be a doodle poll. The calendar is turning out not to be much use as only certain people have access to it. A simple fix would be to give more people access but we should really back that up with a script that will email to warn if there is no cover.

**Comment by DoESsean** [comment]
This doesn't seem to be a problem at all anymore. Is it worth this issue still being open?

**Comment by johnmckerrell** [comment]
It’s not an issue when people are in as usual, when I’m away for a week at the end of March I imagine it’ll become an issue again.

**Comment by DoESsean** [comment]
I can't remember if this was a problem when you were away, @johnmckerrell. I think we're pretty good at this now, especially as most permanent desk holders are well versed in being first in/last out.

With that in mind, I'm closing it with the caveat that you're more than welcome to reopen it if you feel something more concrete should be in place.
