### ISSUE TITLE
X axis sometimes getting stuck on startup

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#225]
Twice (that I know of) this week when Sophia is running through her power-on datum, the x-axis has been getting stuck.  It's a similar failure sound to when the little metal tab hits the datum point - a grinding of stepper motor missing steps.

Sometimes turning it off and on fixes it, and one time I also needed to just move the x-axis back and forward by hand when it was off, but we should investigate further.

**Comment by DefProc** [comment]
I'm going to close this one for now as there's been no more reports of this
