### ISSUE TITLE
 Gerald not working 

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#226]
At maker night Gerald wasn't working. Reported that the drive was noisy and the laser not operating.

**Comment by cheapjack** [comment]
The door sensor seemed loose art first and then after testing realised that the chiller had been turned off. Once this was turned on and restarted laser operated OK but seems slightly under powered. 

Main Y stepper  seems to be slightly twitchy and varies speed. Will keep testing on my job and keep issue open

**Comment by cheapjack** [comment]
Gerald is working but the left runner on the y axis is making an unusual noise and was sticking. May have to lubricate the runners but not sure what to use. 

Will keep this issue open and have changed label broken to bug

**Comment by DefProc** [comment]
It's probably because of the amount of poly carbonate that's been going through it the last week or two. I'll lubricate all the sliders after the weekend.

**Comment by DefProc** [comment]
It looks like a mount for the power cable for the internal light was catching in the shaft coupler at the datum corner of the bed. I've relocated that, and greased the x and y sliders, so I'll keep an eye on it today.
