### ISSUE TITLE
DoESLiverpool github pages to host javascript laser cutter generating patterns

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#227]
As inspired by people's use of http://jsbin.com/kadaqapu/1/edit?html,js,output for doing the laser cut hinges, I've recoded it into a slightly more functional page here:
     https://doesliverpool.github.io/jshinge.html 

The underlying javascript and html is in the specially named repository here:
    https://github.com/DoESLiverpool/DoESLiverpool.github.io

This works as a flat set of pages people can clone onto their own computer and learn how to hack and design geometrical things in javascript/svg (eg the 2D folding cut plywood).  

We should start a library of these little apps and link to them from the doeswiki laser cut pages:
    https://github.com/DoESLiverpool/wiki/wiki

**Comment by huffeec** [comment]
This is really good. I'm looking at a script to make the isometric bendy wood pattern, will add that when it's done. Might have another spiral idea to work up too.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by amcewen** [comment]
Organisers' meeting notes: Not sure that this is still an issue, leaving it open for closing at a time when @goatchurchprime isn't away

**Comment by goatchurchprime** [comment]
This has morphed into an ongoing project with its own issue tracker, and should soon be in a state to make available to the laser cutting facilities  https://bitbucket.org/goatchurch/laserplacer/
