### ISSUE TITLE
Build a system to email a reminder to the directors two days before a directors meeting

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#229]
We seem to be regularly surprised that the directors' meeting has come around again :-)

We should build a little system to fire off an email reminder a couple of days beforehand (reading from the calendar to spot any cancellations)

**Comment by ajlennon** [comment]
What about a shared Google calendar?

http://webapps.stackexchange.com/questions/9864/setting-reminders-in-friends-shared-google-calendar

**Comment by amcewen** [comment]
I *think* that's what we'e set up, and just now I *think* I've added a reminder to go out by email two days beforehand.  Guess we'll see next month :-D

**Comment by DoESsean** [comment]
@johnmckerrell isn't sure whether he's receiving reminders or not, but as the Directors' Meetings now have a regularly scheduled date, I'm closing this issue.
