### ISSUE TITLE
The vinyl-cutter needs a roll spool holder

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#23]
For smooth operation of the vinyl cutter you need the roll of vinyl to be able to spool and unspool freely.

We should laser-cut or 3D print two stands for a length of threaded rod, to hold the roll of vinyl.

**Comment by amcewen** [comment]
@Thingomy given it's been in beta for over a year without any complaints, do you reckon we can call this done? :-)

**Comment by DoESsean** [comment]
@amcewen, as your comment has been in beta for nearly two years without complaint, I'm saying yes :)
