### ISSUE TITLE
Buy a new 2D printer

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#230]
The B&W laser printer in the main room isn't on the network, and is also only B&W...

What should our 2D printing capability be?  Colour?  B&W?  Duplex?

I'm thinking that networked and laser-printer are the main minimum requirements (but can be persuaded otherwise...)

Specific model suggestions and recommendations would be especially welcome (as that's likely to be what will stall this issue otherwise...)

**Comment by amcewen** [comment]
We can always race this issue against issue #203 to see which gets us to MVP (Minimum Viable Printing :-)

**Comment by mdunschen** [comment]
Given that we sometimes have requests for a scanner, I'd suggest a combined printer/scanner, I think normally referred to as 'all-in-one' printer.

**Comment by Thingomy** [comment]
I may have a spare hp 2600n colour laser, can confirm next week.

**Comment by ReddbridgeMark** [comment]
I was going to suggest a bog standard HP all in one for 50 quid from John Lewis, which would be perfectly fine to churn out pages and scan, but then saw this

100 pounds: http://www.johnlewis.com/hp-officejet-7510-all-in-one-wireless-wi-fi-wide-format-printer-with-touch-screen-a3-printing/p2213126

A3+ capability could be handy for some (I know I sometimes have the call for it), along with the top feed for the scanner for multi-page scanning.

Not too expensive as and when it eventually dies, HP consumables readily available and OK cost wise, HP typically do decent prints.

**Comment by DoESsean** [comment]
So, Patrick has had a bit of a root around, and come up with the following
solution:

This colour inkjet
<http://store.hp.com/UKStore/Merch/Product.aspx?id=G3J47A&opt=A80&sel=PRN>
(which
is the one Mark had found, but is slightly cheaper direct through HP), and this
B&W Laser
<http://store.hp.com/UKStore/Merch/Product.aspx?id=C5F94A&opt=B19&sel=PRN>,
which also does duplex printing and all that other fancy stuff.

The two of them come in at just under £300, and should fulfil any
requirements we have - the colour one also works as a scanner and copier.

If no-one has any objections, then I'll go ahead and order them on Thursday.

**Comment by DefProc** [comment]
I'll stop writing that message then!

**Comment by johnmckerrell** [comment]
Just a note that the current B&W printer came from my house so I'd like it back when it's replaced ;-)

**Comment by amcewen** [comment]
The colour all-in-one has turned up.  I haven't unboxed it yet.

**Comment by amcewen** [comment]
And the laser has arrived too.  Also yet to be unboxed, both are next to the existing printer.

**Comment by DefProc** [comment]
Is the new equipment big enough that we need a shelf or alternative place
to place them?

**Comment by DoESsean** [comment]
Yes. Kind of.

Working plan at the moment is to put one where the current printer is, and
one where the telephone lives. Whether or not this is a long term solution,
I don't know. Depends how handy you're feeling.

**Comment by amcewen** [comment]
The printers are here and installed and on the network.  The inkjet is turned off, as we figured that might encourage people to use the B&W laser in preference.

We still need to update the wiki with the new details, and presumably also how to scan things (we've only tried printing so far, AIUI)

**Comment by goatchurchprime** [comment]
Oh yes.  Exciting printers to play with!

I've started the wiki page, but haven't got very far with the inkjet.  
    https://github.com/DoESLiverpool/wiki/wiki/OfficePrinters

**Comment by amcewen** [comment]
Adding meeting action label as it was discussed in the Organisers meeting - http://wiki.doesliverpool.com/DoESMeetingMinutes20151029

**Comment by amcewen** [comment]
Looks like @goatchurchprime has filled out (at least the minimum) details of the printers on the wiki, so this can be closed.

**Comment by jamieisboss** [comment]
that's a shame i missed this, we've got a large-ish brother colour laser that doesn't really fit anywhere and actually I'll look, it's an HL4140-CN, got about 10000 pages of toner in it and everything, would consider a long term loan (until we have somewhere to put it which will likely never happen) if it's of use at this point as it can't stay where it is for much longer. So long as I can sill print to it when i need to, i'd be happy enough. It prints nice from Ubuntu as well if that has any bearing.

There's also a wooden stand i made from some leftover 18mm ply which it sits on and has a shelf underneath i think it'd fit 8 reams of paper and still have room, i might be reasonably easily convinced into making and fitting a drawer with full extension rails, that'd make it a bit more practical to use the back of the thing to hold spare cartridges or something. The Base it isn't in the same place but  now, they could be reunited, in a few weeks time though. It looks pretty good, i think i veneered the edges of the ply and everything.

@amcewen as you closed this, just let me know if you want it and  I'll sort bringing it down at the next Makerday or something

**Comment by amcewen** [comment]
Ta for the offer but I think we're covered on our 2d printing requirements now :-)
