### ISSUE TITLE
Organize more DoES epic trips

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#231]
Here's the record of them:  http://doesliverpool.com/category/epic-trips/

Ideas pop up frequently, such as Francis's idea of getting a tour of the Halewood motor car factory.  

I went past Nortons for Scrap on a bike ride yesterday.  They have some big metal shredding equipment and they write on their website: http://www.s-norton.com/background.html :   "By using the very latest Information technology, the new administration centre, based in Liverpool, is already helping to advance the company’s leading position in business analysis and control." 

There's other big infrastructure things, like the water works, the oil refinery, the uranium enriching works, as well as smaller factories around the area.  (I might be able to get us into the hat factory behind the station if it's still in business.)

I think these trips can make a big enough impact on ourselves and in terms of potential links with businesses relating to easy to deploy IoT tech ideas.   Having more of them should be a high priority.  

Epic visits ought to be on the agenda for the organizer's meetings.

**Comment by goatchurchprime** [comment]
How about a visit to the hugest building that just pinged up on the M62 this year?  It's not like it's a ship-builder, and I have no idea why they could possibly need 30m of head that amount of headroom for  just to stack clothes.   
http://www.thehutgroup.com/record-sales-profit-growth-international-expansion-hut-group/

**Comment by amcewen** [comment]
Some additional ideas for trips (some vaguely under way)...

 * A trip to the National Oceanographic Centre in the Uni
 * A visit to Try and Lilley (hat manufacturers over the road) - they can only take 2 or 3 people at a time
 * A visit to Willis Organs (pipe organ manufacturer) - [initial contact made](https://twitter.com/JWwakey/status/1000155031860019201)

**Comment by amcewen** [comment]
Issue #858 seems like it would fall under this category too...

**Comment by RiverMersey** [comment]
According to the earlier link, there doesn't seem to have been any DoES epic trips since 2014

**Comment by amcewen** [comment]
As it happens there was a DoES Epic Trip to N Wales last Friday/Saturday - see #1343 for details (and a few photos).  

There are early plans for a trip over to Belfast sometime in April to see Farset Labs' new space (probably to coincide with their 8th birthday party)

**Comment by goatchurchprime** [comment]
Closing issue as too vague.  Replace with specific trip proposals that it's agreed we should do (eg Farset Labs  Issue #1402
