### ISSUE TITLE
Buy Ethernet switches to improve networking

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#232]
The Ethernet switch by @mdunschen's desk isn't the most reliable.  The switch by the 3D printers keeps getting stolen whenever we go to an event.  The switch under Gerald in the workshop is also flaky.

So, I think we should buy three new at-least-6-port Ethernet switches.

It will let us get the laser-cutter computers back on the Internet, and mean we can move A's build computer (new arrival last week) from the main office and into the workshop where it won't be as noticeable when it's busy building.

Does anyone have any recommendations before I do any digging?  Brands that work well/poorly?  Etc.

**Comment by jamieisboss** [comment]
I think I've got a 5 port gigabit netgear switch somewhere and it's a bit old but I've got a 10/100 Cisco 24 port one too. I think the Cisco switch has pre 802.4af Cisco proprietary power over ethernet.  Would that be of any use?

**Comment by jamieisboss** [comment]
As for Reccomendations id go with this one:

http://www.amazon.co.uk/NETGEAR-GS108PE-300EUS-ProSAFE-Gigabit-Managed/dp/B00LMXBOG8/

the 4 poe ports are increasingly useful to use wifi, and if you wanted, security cameras or arduinos made into anything. If it was me I'd be tempted to get all 8 ports with PoE and use them for wifi, door locks, any other network connected "stays in one place" things that would be handy not to have to run power to seperately

**Comment by jamieisboss** [comment]
Found the 5 port netgear switch, it's [this one](https://www.amazon.co.uk/dp/B0000E5SEQ/ref=cm_sw_r_other_awd_x6wNwbBJTZEPQ) if it'd help out I'll donate it or whatever the words are for you can have it.

**Comment by DefProc** [comment]
I went for the TP-Link switches last time I was looking:

 * [TP-1005D](http://uk.tp-link.com/products/details/cat-4763_TL-SG1005D.html) (I have the pre-facelift version) / [TP-105](http://www.tp-link.com/lk/products/details/cat-42_TL-SG105.html) (front facing ports) @~£15–20
 * [TP-1008D](http://www.tp-link.com/lk/products/details/cat-4763_TL-SG1008D.html) (~£20) / [TP-108](http://www.tp-link.com/lk/products/details/cat-42_TL-SG108.html) (front facing ports) @~£20–30
 * or there's always the big one: [TL-SD1024D](http://www.tp-link.com/lk/products/details/cat-42_TL-SG1024D.html) (also available in rackmount [TL-SD1024](http://uk.tp-link.com/products/details/cat-42_TL-SG1024.html)) @~£75

**Comment by jamieisboss** [comment]
@amcewen or @doessean [These metal 5 port switches]( https://www.amazon.co.uk/gp/aw/d/B00TV4A96Q) are the Amazon deal of the day, reducing them to £11.99 each, I have prime if no one else does and you want some. Offer on til midnight. 

The larger switches seem in line with the price too although it doesn't say they're on offer so maybe they're always that cheap

**Comment by DoESsean** [comment]
One 8 port and one 16 port switch ordered from Amazon today.

**Comment by jamieisboss** [comment]
I have cable pulling rods (though annoyingly not the ends for them but tape seems to work fine) if you want help or to borrow them if you need to pull any cables

I also might have some leftover cat6 when I've finished cabling the house, i'll let you know if i do if it's still relevant when i finally finish it

**Comment by amcewen** [comment]
The switches @DoESsean ordered arrived ages ago and are in use, alongside one that Alex donated (which is under Gerald).  The 16-port is in with the Made Invaders kit as it's most likely to be used for events, but that meant the one by the 3D printers shouldn't get stolen again.
