### ISSUE TITLE
Regularize and document the printing supplies situation

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#233]
Placeholder issue for doing stuff with the new printers and working out how to scan things.  

Scanning ability should definitely feed into the ability to send things to the laser cutter in terms of outlines and bitmaps that can be engraved.  

Put some notes about the how much inkjet ink there is and where to get more.  Are the cartridges recyclable or have we economized on a printer where we're going to be paying through the nose for over-priced units?

Also dig out some supplies that shiny photo-printing paper left from when we used to print our own photos.  

In particular I want to find out more about waterproof paper that works with laser printers to make completely indestructible documents that can be taken down caves.  (I've got some in Becka's office, but I hear it's possible to make it yourself.)

**Comment by amcewen** [comment]
Having a printer that does colour properly would also let us add photos to the "wall of fame" in the kitchen (if we can encourage more people - me included! - to actually fill one in...).  Maybe we could build a twitter-to-wall-of-fame script to simplify it for those of us who get stuck trying to work out how to describe ourselves :-)

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by DoESsean** [comment]
I'll be doing a proper inventory of stationery and office supplies when we move, so we'll have this then, as well as (hopefully) a better organised cupboard.

**Comment by DoESsean** [comment]
We have plenty of A3 and A4 paper, as well as inks available for the colour printer, and Y, M and B inks for the sublimation printer. All of these are in the (slightly tidier and more organised) stationery cupboard, along with the rest of the standard office type supplies.
