### ISSUE TITLE
Stale and last chance sections in the fridge

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#236]
Communal fridges are an age old problem.  If the fridge is in a place where people are hungry, then food gets stolen.  But this fridge is not encountered late at night by teenagers after a pub session, so food gets forgotten and we are all too polite to do something about it.  

No one wants to put named stickers (or their business cards) on their stuff.  And shelf demarcations don't work due to the problem of over-spill, even if we drop-kicked down the hall those stupid plastic bottles of not-smart water.  

All we have now are the gothic script "Eat me" stickers, which are too nice to waste on some half-eaten packet of crisps, so they frequently get placed unstuck onto things and then fall off.  People might be happier to use those tiny red dot stickers, a red marker pen, or a flag on a toothpick in some blue tac that can be stuck on the door when not in use.  Unfortunately these labels don't have a time status.  

There has got to be some kind of miniature slow-clock device the size of a coin cell that can be reset and which changes visibly over the course of a week till it's flashing red and we throw the item out.  How hard can this be to find and try out?

**Comment by johnmckerrell** [comment]
One option might be just to clear out each Monday morning anything without a sell by date or that's open, as most people are in on a weekday, that gives 2 days for the food to go off over the weekend before we then chuck it. We might get people bringing food for Maker Day but then those people tend not to be in for a while so you'd want to chuck their food anyway.

**Comment by DefProc** [comment]
As it is, I go through infrequently and remove things that have obviously been left, forgotten or gone off.

**Comment by DefProc** [comment]
Just adding a date area to the `Eat Me` stickers might solve this.

**Comment by DoESsean** [comment]
I've emptied the fridge of old stuff today.

I'll do this weekly to try and ensure that we don't get a backlog of rubbish in there, and will send out an email or something to let everyone know about the new system. It'll also probably be worth making some 'Do Not Toss' stickers or something for things that people might want to keep.

**Comment by DoESsean** [comment]
We seem to be a lot better these days about keeping on top of this (or at the very least more ruthless!), and the 'Eat Me' stickers tend to have the desired affect.

With that in mind, I'm closing this issue.
