### ISSUE TITLE
Make new kitchen fob keyrings

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#237]
We used to have two kitchen fobs, and these have both mysteriously disappeared (although one will soon be on its way back) so we need some new ones - meaning new keyrings too.

**Comment by amcewen** [comment]
Two new keyrings cut.  Left on @DoESsean's desk.

**Comment by amcewen** [comment]
And they've been in use for a while now, so we must have sorted them out with RFID tags :-)
