### ISSUE TITLE
Add a doorbell to the workshop door

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#240]
Because:
- visitors do knock on the workshop door to try and get in, 
- workshop users frequently lock them selves out and have to knock on the door to get back in,
- you can't hear people knocking on the door when the workshop's noisy (i.e. in use), 
- it might encourage workshop users to keep the door closed, rather than propping it open if they don't have their own key (they should have a key), 
- I found a doorbell chime in the DoES infrastructure box today. 

I've ordered a doorbell button to go with it. (arrived)

There's probably a "good reason" to connect this to the internet too. 

This is somewhat related to #144

**Comment by jamieisboss** [comment]
Well you've already got something but they were in with the alarms you can add as many doorbells and chimes and those have strobe flashes in case something loud is happening when someone presses a bell

- [starter](http://www.amazon.co.uk/dp/B00KVZCMQY)
- [extra chime (plug in with Strobe)](http://www.amazon.co.uk/dp/B00UUPE0F6)
- [extra button](http://www.amazon.co.uk/dp/B00KVZCT5S)
- [record your own chime!](http://www.amazon.co.uk/dp/B00EVNVR4A) (volume goes up to 110dB) actually this one just keeps getting bettter, you can record 4 things

**Comment by stevesparrow** [comment]
This is done, though if I'd have read @jamieisboss comment first, it would have been a more fun one!
