### ISSUE TITLE
Update events page to list the active meetings and link to sign-up type page

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#245]
From the Organisers meeting - http://wiki.doesliverpool.com/DoESMeetingMinutes20151029

As per title.  Help raise awareness of what meetups take place to DoES.

**Comment by johnmckerrell** [comment]
Notes from meeting 20160614 - @DoESsean to ask again

**Comment by DoESsean** [comment]
Emailed. Will wait for responses.

**Comment by amcewen** [comment]
I'm wondering if this issue is mis-named?  Presumably the important bit is that we get some blog posts (or wiki pages) explaining the groups, and @DoESsean emailing is just a step in making that happen?

I've renamed it to hopefully better reflect what we're trying to achieve, and then reopened it because that's not done yet (sorry @DoESsean :-)  If we don't get any responses after a while, I'm happy with us closing it then with a "no-one replied" or "we only got responses from X and Y"

**Comment by DoESsean** [comment]
I just wanted a mention in Weeknotes ;)

**Comment by amcewen** [comment]
Well, I'm sure you can get a delayed mention, once we've got (or given up on waiting for) some writeups :-D

**Comment by jamieisboss** [comment]
There's 4 different Venue API calls in the 2 meetup APIs and none of them seem to be any use, you'd think you'd be able to see what meetups were happening at a venue , then get the group descriptions and recent comments, then arrange them by next meetup date and it'd keep itself fresh. Maybe i'm missing the point of how one or more of them work , you'd think it'd be a reasonably common thing for a venue that hosts these kinds of things to do though.

**Comment by DefProc** [comment]
@DoesSean do any of the groups have meetup/lanyard/twitter/facebook descriptions that we can at least copy-pasta into wiki pages? Would that get this moving?

**Comment by huffeec** [comment]
I've copied through some of the text from the makernight domain for now. 
More to come..

**Comment by amcewen** [comment]
Rolled over to next organisers meeting.

**Comment by amcewen** [comment]
This might be something to feed into when we rework the main website.  Tagging it for issue #19 to look over when that's done.
