### ISSUE TITLE
Develop and implement more formal grievance procedure and safe-spaces policy

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#246]
From the Organisers meeting - http://wiki.doesliverpool.com/DoESMeetingMinutes20151029

Question about banning people for transgressions like leaving the laser-cutter unattended while cutting, leading into general discussion about grievance procedures.

Action: @amcewen to dig out links to other hackspace examples

**Comment by amcewen** [comment]
The London Hackspace version is at https://wiki.london.hackspace.org.uk/view/Grievance_Procedure (although they're in the process of discussing updating it).

And the Nottinghack one is at https://wiki.nottinghack.org.uk/wiki/Grievance_Procedure

**Comment by johnmckerrell** [comment]
Notes from meeting 20160614 - @DoESsean to review above and draft procedures

**Comment by amcewen** [comment]
Rolled over to next organisers meeting.

**Comment by stevesparrow** [comment]
Switching this to a new one for ooh's access...

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by amcewen** [comment]
Reopening this to track the development of the grievance procedure and the safe-spaces policies that we've been drafting in the directors' meetings (and has been discussed in the recent community meetings)

**Comment by jackie1050** [comment]
This new Safe Spaces Policy and Grievance procedure have now been formally adopted and published on the Wiki. If there are any further issues they can be raised separately.

Thanks to everyone who has contributed from 2015 onwards!
