### ISSUE TITLE
Getting a lot of things done

### ISSUE THREAD

**Issue by jamieisboss** [DoESLiverpool/somebody-should#248]
I was speaking to @DoESsean about the different issues listed here and afterwards I came to the conclusion that maybe tackling a bunch of issues at once, "Upgrading the wired network" #232 , CCTV #212 (plus some wifi related ones), "User management" #175, and "Having a does cloud infrastructure" #18, would be more efficient and effective than tackling them separately. At the same time the upgrades could be done at the same time as fixing some broken things, making one big push to get the space to where you want it.

Some that jumped out:  #166 #162 #137 #99 #96 #94 #62 #61 #45 #14 #9 (i have a plan for an extraction system for a workshop at home that turned out to be way too powerful so maybe #5)

The also wraps #101 but makes it into more of a weekend of hacking, fixing and improving the space

_(Given that i have no idea how any of the stuff you have now is set up, feel free to disregard/correct anything here. . I'll check some of the other repos and see if there's info in there and edit this accordingly but that might take a while so i might as well just lay it out...)_

_[Also, I'm just suggesting the best thing I've thought of, disregarding cost and effort as i find it better to work backwards from there as in my experience people tend to remember limitations better when presented with a solution than if you ask for bounds first]_
## Network and Cameras

My suggestion would be to get one proper 24 port PoE switch (maybe even one with some poe+ ports to run smaller switches from, run cables to the appropriate places (I can do this assuming there are already some holes in the walls or we're allowed to make some) and then get PoE Wireless access points for each room (main, workshop and dinky) The security could then be WPA2-Enterprise which requires a username and password rather then just a key, (A second guest SSID could be used which could either use a key or a captive portal asking for a name and logging mac addresses so you have a record of who is on your network, members/regulars then get a username and password guests use the guest). Each Room Plus the corridor bike area gets a PoE ip security camera, and the network gets a recording device, ideally the device can flag where the video has movement.

Then the door access rfid dealies all become poe powered and use the same radius server as the wifi to say whether a person is allowed into a space (useful for stopping people from wandering into places if you book the rooms out to someone who has paid) and logging when people are in a given place.
## Part i don't know is definitely possible

Using opencv (where?, find out in the next section), count the number of people in the space and compare it to the number of people the door readers say should be there, add a flag to the video at times when there are people who haven't scanned into a room in there. Add an oyster style you are now entering DoES reader before Dinky on the corridor and encourage people to beep in to rooms even if some else has already unlocked the door.
### Why?

Then you have a record of every time a person who is unknown moving around DoES, with a timestamp so the video footage can be easily refrenced. This could automatically send an email with a list of the alerts to be checked or ignored if you know that there was a party or event happening. Potentially, some cases could trigger a real time alert, push message, sms or something, just as good for making sure someone comes to help walk in potential members as alerting theft happening
## The cloud bit

Some of this stuff could be offloaded into AWS; the openCV bit seems ideal if the cameras can do something on motion, because they could trigger an Lambda script in aws which could process a couple of frames of video  and do the comparison with the number of people in room 

[Lambda is a service which executes when triggered, uses the appropriate aws resources, then stops; so you only get charged for the 30 seconds or so of usage while the script is running](https://aws.amazon.com/lambda/details/)
### Extra

I think the [AWS Workspaces](https://aws.amazon.com/workspaces/) service is now live in the uk so members could have a virtual workspace which they can use whether they are in DoES, or anywhere else, adding value to a membership (and possibly cost so maybe this is optional {possibly this could be a new type of membership.)

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.
