### ISSUE TITLE
Gerald's beam is crescent shaped

### ISSUE THREAD

**Issue by epsaul** [DoESLiverpool/somebody-should#249]

**Comment by epsaul** [comment]
Re collimated. Checked beam at entry to mobile mirror housing using masking tape found beam to be sharp at this point. Removed final lens housing to check for dirt/debris. Problem persisted concluded mobile mirror needed collimating, used tripod adjustment to bring beam to a point.

**Comment by amcewen** [comment]
By "re collimated" do you mean you adjusted the mirrors to bring the beam back into alignment?  (just checking for us non-optics people :-)

**Comment by epsaul** [comment]
Yep, strictly speaking It's the light that is collimated I think. This is achieved  by the mirror (and other optical components) being aligned; so yes, realigned is probably the word to use. Collimated light is light whose rays are parallel and therefore don't disperse over distance traveled.. I think - I ceremonially burned my physics A lavel notes some decades ago! :-)
