### ISSUE TITLE
There's no easy way for people to create a user on the wiki

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#25]
Since the great spam account purge of *mumble* months ago, creating a new account on the DoES wiki involves ssh-ing into the server and commenting out a line of Python code.

Obviously this isn't ideal, and it would be good if there was a better solution.  Maybe one that (also) automatically created a user-account for everyone who fills in the induction form (so all our workshop and co-working users would get one by default).

**Comment by goatchurchprime** [comment]
This is solved by issue #97

**Comment by amcewen** [comment]
And now all the non-organiser content has been migrated as part of #97, we can close this.
