### ISSUE TITLE
The cheap soldering irons have all stopped working

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#253]
Some of the cheap, Silverline soldering irons that we originally got a couple of years ago to do a soldering workshop have stopped heating up.

Although I haven't systematically been through the all the irons, I couldn't find one of the blue Silverline irons that would heat up so I did a quick disassembly check on one to see if there was any obvious problems.
 
Both the diac and triac both looked fine (though it's all 240V inside, so I haven't done any power-on testing :warning: :zap: :skull:) but the insulaton going to the heater element was brittle and flaking at the element end in the wand. My best guess is that the element and/or the connection is the problem, either failing as a short or open circut, which the controller circuit doesn't notice. 

As the elements are not easily replaceable, we have a few options. 

 * Ditch all these iron because they've all failed within two years, 
 * try and repair/combine the ones we have,
 * just stick to the irons we have that work and bin the dead ones,
 * get some replacement irons. 

As we don't need the large number of irons for anything in the diary, I'd suggest not replacing the dead ones, but to look at if we should add a better iron (I have a temperature controlled Hakko 888D on the way for fine soldering work to try). Discuss.

We do still have two irons in service, the older [Maplin N78AR](http://www.maplin.co.uk/p/maplin-50w-mains-solder-station-n78ar) and the [Weller TCP](http://wiki.doesliverpool.com/ElectronicsEquipment)

 * [x] get some [new tips](http://www.maplin.co.uk/p/50w-solder-station-additional-solder-tips-n79ar) for the Maplin N78AR because the current one is *nasty* and I've been keeping it alive for months now with regular use of tip tinner!
 * [ ] Get some new weller tcp tips as we only have one fine point. 

Does anyone have more familiarity with the Weller temperature controlled tips to be able to choose replacements?

**Comment by makerspaceuk** [comment]
I can deffo offer some good prices on low cost irons and tips, including some advice on the TCP tips.  Will also have a look at what we have in the samples cupboard and see if there are any soldering tools going spare

**Comment by DefProc** [comment]
We have this wand (image below) and it works lovely. However it was donated, and I have very little information on tips and tip compatibility for weller irons.

![img_20160107_123139](https://cloud.githubusercontent.com/assets/343000/12695906/f3ddedca-c753-11e5-8eb8-1778b32fc6bf.jpg)

Any suggestions or advice would be greatly appreciated

**Comment by amcewen** [comment]
As of yesterday none of the soldering irons are working.  The temp-controlled Maplin one was working some of the day, but wasn't later on, and then when I tried switching to the Weller that wasn't getting up to temperature enough for lead-free solder (I didn't try the leaded).  I tried new tips on both, without any improvement :-/

I've ordered a nice expensive Thermaltronics one for myself which will be arriving tomorrow, and don't mind it going into long-term loan to DoES, but I'd want us to still have some cheap(er) ones for general use and the Thermaltronics one for experienced users.

**Comment by amcewen** [comment]
@DefProc Searching for the wand code on Farnell should show up the tips for it.  In the past we've had http://uk.farnell.com/webapp/wcs/stores/servlet/ProductDisplay?catalogId=15001&langId=44&urlRequestType=Base&partNumber=416496&storeId=10151 in it.  At present it's got a PT-08 1/32"x0.8mm long conical tip in it, which I'll have bought from Farnell, but doesn't seem to be listed any more (and the link above is the only one I can find in my past orders right now)

**Comment by DefProc** [comment]
@DoESsean has just ordered: 

 * 1× https://www.rapidonline.com/weller-t0151004199-tcp-temperature-controlled-soldering-iron-85-4850
 * 1× https://www.rapidonline.com/weller-t0051031199-barrel-assembly-for-tcp-series-irons-using-pt-series-tips-85-5504
 * 1× https://www.rapidonline.com/weller-4ptaa7-1-pt-aa7-solder-tip-round-tip-sloped-370-c-1-6mm-85-4616
 * 1× https://www.rapidonline.com/weller-4ptbb7-1-pt-bb7-solder-tip-round-tip-sloped-370-c-2-4mm-85-4621

so we get a replacement TCP wand (with the 3-way Bulgin type plug), which should let us fix the current broken one, and therefore give us a replacement.

As the current one has a PT tip in it, having the barrel assembly will allow us to use the current tip, and the two new tips can go in either — and the newer LT tips (where the magnestat temperature controller is a separate piece) seem to be about the same price as the PT tips that are both tip and temp controller combined, so there seemed like no benefit to switching to LTs. 

The new wand includes the LT adaptor and the correct sleeve, ro that will already be available for the future. 

I'd expect this TCP iron to become DoES's staple soldering iron, because the fixed temperature tip will save any problems of users adjusting soldering iron temperature unnecessarily.

**Comment by DefProc** [comment]
The new TCP wand is fitted amd working. It has a 2.4mm roind sloped tip running at 370°C, so it should be ideal as the main workshop iron.

The old one can be taken apart and checked for it's fault. Based on the long heatup time it had before failure (compared to the new one) I suspect a heating element failure.
