### ISSUE TITLE
Violet the blue 3D printer now broken

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#255]
It managed to extrude its extruder by pushing it out the bottom when it gave up extruding the plastic.  

I think it needs a thorough clean out.  Can I have some help and so I can write it up on the wiki

(The other UP printer doesn't come on when you plug it in.  What's wrong with that one?)

**Comment by DefProc** [comment]
I've reseated the heater block and nozzle into the extruder head. 

Cleaning should mean removing the nozzle (unscrewing it from the heater block) and soaking in acetone overnight.

**Comment by DefProc** [comment]
The nozzle has been soaked in acetone overnight and cleaned out. 

Violet's now ready for testing

**Comment by DefProc** [comment]
Broken Rose's issue out into #256
