### ISSUE TITLE
Rose won't power on 

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#256]
There's no power light or response when Rose is switched on. Swapping the power supply for Violet's had no effect either.
- [x] Troubleshoot why the power won't turn on, 
- [ ] Troubleshoot why the power light on the microprocessor board comes on and then fades out
- [ ] Refit the extruder head
- [ ] Fit a fan to the extruder head
- [ ] Fit in some PLA and mark the head "PLA only"

**Comment by DefProc** [comment]
It's also has no head mounted as that was used to fix violet's extruder — #255 — @JimNixon has reseated the filament heater block so that should extrude properly (as there's no positive centering location the way it's clamped between the heatsink and the motor body). 

@goatchurchprime reported that the fan is missing, which will hamper refitting, but as Rose can't power on, this is moot at the moment. This is likely related to #115 and the new fan is probably with the old one in the 3D printer box, ready to have the wires spliced.

**Comment by JimNixon** [comment]
Borrowed the extruder and hotend assembly from Rose to repair Violet. I'll fix the assembly and the power issue when I have time.

**Comment by DefProc** [comment]
The power light on the microprocessor board comes on during power up, and then fades out. 

While there wasn't any obvious component damage, I'm wondering if this is from a voltage regulator that's died/overheats quickly under load…

**Comment by goatchurchprime** [comment]
opened up both UPs.  Rose has daughter board D82898 and the light dims out when you power it up.  Violet has D82372 and it stays on.  Swapped them round and it shows these boards are the problem (ie D82898 is bad).  

Rose, with the good board, didnt show up with lsusb.  Put the good board back into Violet and lsusb hangs on my computer when plugged in (which is different), but Adrian's computer doesn't register a connection.  

I have raised a support ticket at http://up3dprinters.co.uk/up3dprinters-support/ asking if they can sell us replacement boards because the mechanics are probably still okay

**Comment by goatchurchprime** [comment]
Have reassembled them.  Violet still able to home itself (using the switch on the front) but still does not connect as a USB device (almost as if the wires are cut).  

By the power of closed source design and components, there's basically nothing we can do with either of these now unless we can get a replacement mother board from up3d.  

If this can't be done, the only option is to scrap them and maybe salvage the mechanicals -- either by donating it as spares to someone with an UP, or putting it out as a project to replace the electronics with a Beaglebone unit, like http://www.thing-printer.com/product/replicape/ which could plausibly run this thing without too much faff.  

This ought to be a decision sanctioned by the organizers.

**Comment by goatchurchprime** [comment]
rolled into https://github.com/DoESLiverpool/somebody-should/issues/397
