### ISSUE TITLE
Ultimaker nozzle is blocked

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#257]
The Ultimaker's nozzle was blocked yesterday - running the temperature up to 250degC and then with *lots* of pressure I managed to manually unblock it, and then we did a cold pull to clean it out okay.

It then printed a part off okay, but was blocked again today.  The same approach hasn't fixed it - there's a short section of filament stuck in the nozzle and PTFE tubing.  Looks like it will need more dismantling of the hot end - maybe just removing the nozzle and soaking it? - to fix.

**Comment by JimNixon** [comment]
I'll be in tomorrow and can check it out, fixxed it before on my own Ultimaker. Just disassemble the nozzle, whack it up to 260 and unblock it with a 0.2mm drill bit which I'll bring along.

**Comment by JimNixon** [comment]
Replaced the PTFE tube as it had melted a bit, blocking filament flow. Works again now.
