### ISSUE TITLE
Violet the blue 3D printer broken again

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#258]
It was going really well with the black ABS plastic until someone at makernight decided that we to swap it for the gold PLA filament.  It's now blocked when I tried to swap it back.  Tried it with the nozzle from Rose, and it's still blocked.  I'm out of ideas of what to do.  

If this gets working again, maybe we can reserve one of these UP printers as ABS only, and keep insoluble PLA out of the system.

**Comment by goatchurchprime** [comment]
I'm in a bit of a hurry, so I've left it with the ABS filament still in it, otherwise I'd carry on hammering at this problem.  (Probably lucky I don't as I'd probably just make it all worse.)

**Comment by JimNixon** [comment]
If it's not fixed by Wednesday, I'll check it out while I'm at DoES.

**Comment by goatchurchprime** [comment]
I got it fixed late afternoon by taking out the whole heater and nozzle arrangement to find a broken piece of cold PLA wedged in the intake. Works now.  Recalibrated as well.  Needs a "ABS only please" sticker on it.  The PLA-lovers already have their Ultimaker2 and maybe the other UP printer when that gets fixed.
