### ISSUE TITLE
Small fridge should go in Dinky, meaning the coffee machine needs a new home

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#26]
The small fridge would make more sense in Dinky, or in the storage room off Dinky, but we would then need something to put the coffee machine on in the kitchen.

**Comment by DoESsean** [comment]
@DefProc has just pointed out that there is a set of drawers in room 29 which would be perfect for this, so I'll look into sorting out the moves on Thursday.

**Comment by johnmckerrell** [comment]
IMHO they're a bit small but should do for now. I'd suggest we put a piece of white perspex (hm.. or maybe black to match the cupboards) on the top of it to stop it getting damaged from spills.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
