### ISSUE TITLE
Violet's heating block may have a loose connection

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#262]
The heating block on Violet seemed to intermittently stop heating up, even when the software claimed it was heating (when changing filament).

Wiggling the wire coming from the heating block a little bit seemed to rectify matters, but logging it here so we can keep an eye on it.

**Comment by amcewen** [comment]
After fixing #263 it's failed on the two test prints, so I'm upgrading this to "broken" :-(  It tends to get part way into the print and then showed an error that the extruder wasn't heating.

**Comment by JimNixon** [comment]
Managed to get Violet working today by taking the extruder and hotend assembly from Rose and bolting it onto Violet. Prints perfectly now.
