### ISSUE TITLE
Leaflets by the door are outdated 

### ISSUE THREAD

**Issue by jamieisboss** [DoESLiverpool/somebody-should#264]
There are quite a few from january on the side and board,  i tidied them a bit so they weren't all covering each other up while i was eating but they probably want replacing with fresh ones if they exist or binning/creatively recycling

**Comment by amcewen** [comment]
Thanks for the tidying.

We don't do anything to collect them, we just provide a place that the people who want to distribute them can leave them for DoES members/visitors to find.

So, if any are out of date, you (and anyone else) should feel free to put them into the cardboard recycling bin opposite the kitchen :-)

**Comment by jamieisboss** [comment]
Fair enough, I was tempted but then they wouldn't have anything there at all, but I guess they'll drop new stuff down when they have it. For a second I thought about some kind of notification device but then I really couldn't be bothered, unless maybe the leafleting bodies want to commission one, even that sounds like a hassle, sweet shops sometimes do that thing where they write who they are and how long the thing is valid for, that might make it easier to flush  the outdated stuff and knowing that might encourage fresh stuff, I dunno, adding complexity or making sure that it's  useful? Both probably. 

I found a couple of good things going through it but I've never bothered before because it didn't look up to date, prompting writing this thing. 

Meh, I propose "Wallace and Grommet"-ing the shelf so one end drops and everything slides into a bin on the 1st of the month  or the next working day at 2pm. This should be announced by a ship's bell pealing twice. 

Purely for mild shock and amusement, as I'm probably not going to be there then, maybe the cctv can broadcast it. 

If there are two appropriate solenoids in the bins , I will procure a bell and donate a trinket and 1A 12v power source. If not, I'll bin em if I remember when I'm next in.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
I've gotten rid of all the outdated flyers - it might be worth operating a one-in-one-out policy or something similar to make sure we don't get as swamped with them again.
