### ISSUE TITLE
Move doorbots 1 and 2 to static IP addresses

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#265]
Doorbot1 had fallen off the network again just now, but from issue #196 it looks like moving to a static IP improves matters.  So we should switch them both to it and update the how-to-bootstrap-a-doorbot instructions

**Comment by amcewen** [comment]
All the doorbots have been regularly offline whenever I've wanted to connect into them of late.  

I've set up a screen on doorbot2 running 
```ping -D -i 60 mcqn.com > /home/pi/network-connectivity-check.log```
to see how often *it* thinks it can't see the network, as a step towards tracking down the issue.  Will do similar with doorbots 1 and 3 when I can log into them...

**Comment by madjake45** [comment]
This reminds me that I should expand on the logcards application to do the ping to http://status.doesliverpool.com/ so that the information is correct on there.

**Comment by amcewen** [comment]
Added to doorbot1.

**Comment by amcewen** [comment]
Okay, this ran until May 23rd (presumably doorbot2 got rebooted then).  Doing some quick analysis of it, in the time from Fri Apr 15 10:45:05 to Mon May 23 08:07:29 (first ping to last ping in the file) there were 54536 pings sent, but there are only 49729 lines in the log file, so 4808 pings went missing in that time (the first line of the log file isn't a ping response)

That's ~9% of the time :-/

I've not looked into whether that was a single period or spread across the time, but we could plot it if that's useful.

doorbot1's ping log only lasted for 73 minutes, but didn't lose any pings in that time :-)  I don't think that's very useful info though...

I've kicked one off on doorbot3 now, and restarted the one on doorbot1, given both of those seem more often offline than on at the moment.

**Comment by johnmckerrell** [comment]
This looks like an old issue that can be cleaned up, maybe @amcewen could confirm he's seen no recent issues with IP addresses?

**Comment by amcewen** [comment]
This is an old issue, but now none of the doorbots are configured with static IP addresses (as we've completely reinstalled doorbot3).  They still fall off the network, although I don't think static IP addresses are likely to fix it, so we can probably close it.
