### ISSUE TITLE
Radiator in Dinky is leaking a bit

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#267]
The radiator under the whiteboard in Dinky is dripping a bit from the end nearest the window.  I've reported it to Sandy on reception, and Dave should be having a look at it in the morning.

**Comment by johnmckerrell** [comment]
FWIW I did turn it down the other day as the room was quite hot. Perhaps turning it all the way on again will stop the leak.

**Comment by amcewen** [comment]
The plumber (who deemed the boiler dead) tightened the nut on it, to see if that would fix it.  Now that #268 has been fixed and there's water in the system again, it seems that it hasn't been fixed.  We need to let reception know that it's still a problem.

**Comment by DoESsean** [comment]
I've just spoken to Rachel on reception and let her know about this, so
she's going to tell the plumber and hopefully get it fixed.

**Comment by amcewen** [comment]
No evidence of any leak now, so I think the plumber's work has done the trick.
