### ISSUE TITLE
The central heating boiler is leaking

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#268]
The heating hasn't been working at all today.  I tried topping up the boiler pressure as usual, but when I checked on it later (as it still wasn't working) noticed a row of drops of water along the underside of the boiler where some of the water is leaking out.

I've reported it to Sandy at reception (alongside issue #267) and Dave should be looking into it in the morning, but until then we're on the oil-filled radiator in the main room (though luckily it's fairly mild out at the moment)

**Comment by DoESsean** [comment]
Dave has just been out and had a look. He says that the boiler has blown right in the middle, so it's a mechanical thing that's going to require an actual engineer to come and fix it.

He's going to call one in, and reception will let us know when they should be along.

**Comment by amcewen** [comment]
The boiler has been replaced.  Yay!

Sadly they just cut the wires to the yahms controller, so it's not longer controllable from the Internet.  It's now controlled by some sort of RF thermostat, although @DoESsean and I couldn't spot where it was installed.

I think maybe we should leave it as is for now, and see how things go - then look at better remote control for it if that isn't good enough.
