### ISSUE TITLE
Show last visit per person on hot desk summary

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#27]
Can probably just add this as column in the spreadsheet.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by johnmckerrell** [comment]
I had a go, it's throwing up some zeroes that I don't really understand but think it'll do, result was:

`=ARRAYFORMULA(min(if('Days Ordered'!C:C=A3,'Days Ordered'!A:A)))`

From https://webapps.stackexchange.com/questions/40005/min-max-of-a-row-only-if-value-in-other-row-is-x
