### ISSUE TITLE
Gerald is still struggling!

### ISSUE THREAD

**Issue by 5x5Stuido** [DoESLiverpool/somebody-should#270]
Ello folks, I know this is probably the last thing you want to hear considering the effort to get Gerald back up and running but after using him last Tuesday and yesterday (Easter Monday), am really struggling to get clean cuts out of him. 

I've been cutting 9mm MDF (1200x800 and 600x800mm sheets) and Hobarts 6mm LaserPlyLite (600x400) and on both occasions I had to do several passes to get close to a total cut through the wood. 

The depth of Gerald's cuts diminish from left to right by a good few mm. I ended up having to change the laser's distance to the material on the right to ensure it cut deeply enough. 

It seems like recent efforts have got him close to where he was before xmas but not quite there, at least with the larger sheets am working with! 

I still have a large sheet of MDF, if you want me to pop in with the files I've been trying to cut so you can get a look at the issues am having am quite happy to :) 

Settings for the MDF were 5 and 70, for the ply 8 and 70

JohnH

**Comment by DefProc** [comment]
closed in favour of #288
