### ISSUE TITLE
PC not connecting to UP printer when connected through USB

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#274]
Its not seen from the UP printer software (in Windows) and no USB is seen with lsusb in linux.  

Have tried different cables to check.  Had just been working moments before

**Comment by amcewen** [comment]
Seems to be an intermittent fault - sometimes it works fine, sometimes not...

**Comment by jamieisboss** [comment]
You've most probably already seen this project but people, including myself with the uni printers, would possibly benefit from being able to start a print before DOES is open or leave but keep an eye on longer prints, assuming that it doesn't need the broken USB port, [octoprint]( http://octoprint.org) could be a fix and an upgrade?

**Comment by amcewen** [comment]
Does octoprint work for the UP printers now?  It didn't last time I checked, but that was a year or more back.

I don't think we should allow unattended starting of prints though.

**Comment by jamieisboss** [comment]
Assuing the UP printers are the makerbot ones, yup, ~~just~~ needs [a plugin](http://plugins.octoprint.org/plugins/gpx/) and there are [some features that dont work](https://github.com/markwal/OctoPrint-GPX/blob/master/README.md#known-issues). But thats no the case with the ultimakers, and there's authentication and a rest API, so in theory, you cold have a 3d printer page somewhere which let you choose the printer, upload your file, and hae it run from anywhere, maybe not so much for unattended prints but handy if someone is in and you wanted to start a print from home so it could be printing while you travel, or leave a long running job after closing up and be able to use the webcam to check it's not gone wrong, and stop the print if it does. You could even have a booking system and a print queue with emails when the jobs are done if there was demand for it.

**Comment by DefProc** [comment]
@jamieisboss the UP printer is an UP Plus 2 from PP3DP.com: https://www.up3d.com/?r=plus

**Comment by jamieisboss** [comment]
It doesn't mention that r any of the printers UP 3D make in the "works" or "dosnt work" lists, though  I did find[ this bit of addon software](https://github.com/ForsakenNGS/FixUp3D) which seems to muck about with everything he main software is sending, so could be an approach to making it work if someone was so inclined (im not, windows device drivers are not my bag) or might just be something handy to add on.

The ultimakers definitely work though and if octopi will run on a Zero, they've got camera ports now and Pimoroni still had some half an hour ago so long as you bought a pibowZero (£12  all in i think), that sounds like a tiny amount for the functionality you'd add to the workshop, you can still only buy one but if there's a few people about it might be doable to get a few, i think PiHut should have stock at 9am too in case you're going for this idea. Even a single one would change the way people use the workshop, Start a print and pop out for lunch, checking the webcam feed of the print on your phone, get an email when it's done, as does the office co-ordinator, who can put it to one side so someone else can begin. 

It'd be just like that film with the blue fella without legs who gets dragged on a rug by that beggar boy with an ego issue,

**Comment by jamieisboss** [comment]
Would it be ridiculous to ~~rip out~~ carefully remove their controller board and replace it with a RAMPS board, [even the fancy ones dont seem dear](http://ooznest.co.uk/RAMPS-14-Controller-Board-Premium) and then a mega clone for a fiver and you're back in open source land where octopods can control all

**Comment by DefProc** [comment]
If you're interested in doing this, then Rose is currently out of action because of a controller board "issue" #256 and *could* make a suitable starting point.

**Comment by jamieisboss** [comment]
@DefProc I'd quite like to but can't commit the time _right_ now, if it's not fixed in a couple of weeks I should be much less busy and will happily sit and swap a brain out. I don't mind having a go at a new extruder at the same time if that's not already resolved.

In fact, probably the cheapest source for the parts will mean 20+ shipping days anyway so if you've got a favourite overseas retailer with cheap enough bits in stock, don't mind the wait and you're happy for me to try; I'm interested, just let me know when things arrive and i'll come and tinker.

**Comment by goatchurchprime** [comment]
rolled in to https://github.com/DoESLiverpool/somebody-should/issues/397
