### ISSUE TITLE
Filament line is broken in the Ultimaker Extended

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#275]
Not been having any luck with the printers today.  

It's snapped just by the feed wheel at the back and I can see no way to retrieve it.  It might require removing the tube and poking it out.  When you select the change material option the wheel feeds so fast there's no way to ease it into its teeth.  

I've set my print going on Jim's printer with the red material.  Home this is not a problem.

**Comment by JimNixon** [comment]
Detached the bowden tube and poked the filament through.
