### ISSUE TITLE
Develop an iPhone/Android app to open and close the new bin

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#278]

**Comment by ajlennon** [comment]
It has been suggested to me that it would be better to have it voice activated on certain phrases such as "open sesame"

This could be the first member of a new class of embedded device - the Internet of Bins #iob

**Comment by amcewen** [comment]
I think you'd find it would be the second member of the #iob, although the first was also developed in @DoESLiverpool.  See http://github.com/frabcus/binduino :-D

**Comment by ajlennon** [comment]
Marvellous. The #iob is with us!
