### ISSUE TITLE
Signage for available desks

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#28]
A sign that shows when a hot desk is available.

**Comment by DefProc** [comment]
in progress, thanks to Ben

**Comment by DoESsean** [comment]
Ok, we've spent actual money at this point on cards saying whether or not a desk is available. We just need someone* to make the stands. 

My desk currently sports a rather fetching little robot holding up a sign to indicate whether the desk is free or in use, and one of these for each desk would work. Either that or, and this is my preference, some of the bent acrylic DoES signs like the one on @DefProc 's desk. We can do these for permanent deskers too, and encourage them to leave business cards out.

* This is not me volunteering.

**Comment by DefProc** [comment]
And worth pointing out that there are now a bunch of these stands with the MakerFaire/MakeFest events equipment (in the cupboard in Dinky?) that could be used for this day to day

**Comment by johnmckerrell** [comment]
This needs a photo adding as this issue is linked elsewhere.

**Comment by johnmckerrell** [comment]
![2017-08-15 12 10 06](https://user-images.githubusercontent.com/27243/29317480-04a7bf6a-81c4-11e7-91ea-9e3f1e25ea7f.jpg)

We've settled on these cards without any holders. Also the power sockets help to identify the hot desk desks.
