### ISSUE TITLE
Make a soft materials section for the laser cutter information pages

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#280]
This would consolidate the DO NOT CUT vinyl information here:
    https://github.com/DoESLiverpool/wiki/wiki/LaserCutterGerald

And all the materials experiments here:
    https://github.com/DoESLiverpool/wiki/wiki/CutEtchSettingsSophia

I am interested in doing some caving equipment pattern making and want to know if it is allowed to laser cut neoprene (is this as bad as vinyl) and more in particular kevlar fabric which is too tough to cut with ordinary scissors (so you have to buy a pair form £32).  
    http://www.easycomposites.co.uk/#!/fabric-and-reinforcement/kevlar-aramid-diolen-etc/kevlar-protective-textiles

I'll be having some samples of this material soon, so knowing if it is allowed will be good.  

I imagine most of these materials are ephemeral so will be cut by the minimum setting, whatever that is.  The results would need to be reported, as is some guidelines of how to do it (eg is it best to put the fabric onto a flat board of wood and hold it down with weights?)

**Comment by goatchurchprime** [comment]
More details here, which suggests a protocol of obtaining a Material Safety Datasheet before doing something unknown:  http://support.epiloglaser.com/article/8205/30188/material-safety-and-your-laser

Also, comments threads here suggest there are safe and dangerous kinds of neoprene (depending on quality)
http://www.sawmillcreek.org/showthread.php?209178-neoprene
http://www.instructables.com/answers/Is-neoprene-suitable-for-laser-cutting/

One of the risks (apart from the health risk) is it corrodes the mirror, which then burns out as it absorbs rather than reflects the laser.  

Given how nasty this HCl gas is, you'd think it would be easy to detect.  Maybe we ought to finish one of our gas sensor arduino projects and build it permanently into the box of the laser cutter.

**Comment by goatchurchprime** [comment]
There's a good table here which we can summarize and link to:  
    http://atxhackerspace.org/wiki/Laser_Cutter_Materials

**Comment by DefProc** [comment]
There's a lot of good information in that table, and I'd recommend using a copy (if that's allowed) or using it as a basis (if copying is not allowed). My own research has found some different recommendations for some of the materials they have (eg. @cheapjack cuts foam frequently in Gerald; polycarbonate produces trace amounts of benzine when cut, but not chlorine), and some of their recommendations are inconsistant (eg. polycarbonate is both a "NEVER CUT" and "Safe" material).

It would be ideal to collect the materials data sheets for the laserable material, I have the start of a file on my desk, but it's far from complete.

**Comment by DoESsean** [comment]
Is someone likely to take this on, or should we close it as a 'never gonna happen'?

**Comment by arthurrowland** [comment]
Closing with the suggestion that anyone experimenting with soft materials adds their results to the wiki as they go.
