### ISSUE TITLE
Need to order some new PTFE couplings for the Ultimakers

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#283]
While fixing #279 yesterday we couldn't find any new spare PTFE couplings.  We did find a used one, which isn't in terrible shape, but we should order a couple of spares.

I couldn't find mention of where we got them from last anywhere in the issues... @DefProc, any chance you could do the honours and make a note here for next time?

**Comment by DefProc** [comment]
I was sure ordered a pair (as they're consumables) from [imakr](https://www.imakr.com/en/spare-parts/303-ultimaker-2-ptfe-glass-filled-coupler.html?search_query=ptfe+coupler&results=3) in February. As I recall, Jim decided that the current one didn't need changing at the time, so both those *should* still be with the 3D printer parts.

**Comment by DoESsean** [comment]
Do these still need ordering, or were the last lot still there?
