### ISSUE TITLE
Make a github wiki page for each recurring event group and add links to it from the events calendar

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#284]
eg I spotted this issue when producing this page:
   https://github.com/DoESLiverpool/wiki/wiki/Wearables-group

Organizers could get into the habit of keeping the pages fresh before a meeting and linking to the relevant meet links etc.

**Comment by amcewen** [comment]
Most meetups have a website, which is linked from the events calendar - that's where the #weeknotes script expects to find it.  Most of those links go to meetup.com (the subsequent fragmenting of the community across multiple meetup groups is a bigger and more intractable issue...) and I think the wearables group was one of the few without a website elsewhere.

Using the wiki for such cases is a great idea, and I see @jackie1050 has fleshed out the Wearables page.

I don't think there's much value in recreating the existing meetup.com, etc. websites (is there?) on the wiki.  I'll tend to spot any events that have been added without a link when I'm checking over the weeknotes, so in future I'll raise a new issue for any that I spot are missing.
