### ISSUE TITLE
Liverpool sewing club should list their sewing equipment

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#289]
Here's the page which consolidates links to their various places
   https://github.com/DoESLiverpool/wiki/wiki/Liverpool-Sewing-club

And they can state the conditions for induction before use of said machines.  

Reviews about the quality and capabilities of the machines would be good.  I tried a swiss £900 machine belonging to someone in Bristol last week and it was stunning how well it worked compared to anything else I'd tried.  I want to do more sewing it it feels like that.  (This would include the capability of using the laser cutter to produce the fabric patterns.)

**Comment by aubergine10** [comment]
The sewing club have moved to new premises, closing ticket.
