### ISSUE TITLE
Signage for permanent desks

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#29]
To make sure people don't sit at people's desks, person's name or maybe business, or both.

**Comment by DefProc** [comment]
in progress thanks to Ben

**Comment by DefProc** [comment]
Is this now a stale issue? The power supplies and hotdesking signs now clearly show what's a free desk —
 compared to the desks occupied by *stuff*.

**Comment by DoESsean** [comment]
I would say so. We seem to be getting better at keeping open desks free of
clutter too.
