### ISSUE TITLE
Software error on Sophia

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#292]
Error message when students trying to open laser cutter software: "Plug in softdog and restart the software!" - presumably there's a dongle somewhere?

**Comment by cheapjack** [comment]
@jackie1050 This can happen from time to time, reboot normally fixes. The red dongle is at the back of the PC shuttle (as far as Im aware) to prevent it being mistaken for USB memory

**Comment by DefProc** [comment]
The dongle is (should be) around the back of the computer and needs to be
plugged in at all times.

It's red, tapers towards the end, has a keyring on, and looks for all
intents and purposes like a USB key.

**Comment by jackie1050** [comment]
Adrian found it (by the 3d printers). It's blue and white. Now working.

**Comment by amcewen** [comment]
Yeah, @cheapjack and @defproc's descriptions are both for Gerald's dongle.  Sophia's also has "LASER" printed on the side

**Comment by huffeec** [comment]
Hi Jackie,

Sorry I think my pocket might have tried to call you while I was having a
fag. Hope you're having a good trip!

Chris
