### ISSUE TITLE
Gerald's extractor fan's filter is blocked(?)

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#294]
At the end of an evening of cutting tonight the workshop was full of smoke.  The person in cutting hadn't really noticed as he was in the room at the same time.  

Checking the pipe out of the window, there wasn't any noticeable airflow, despite the fan definitely being on.

**Comment by DefProc** [comment]
Oh, I fixed this the other day. Even thought it has a more coarse filter on the inlet, the big fan will still fur-up over time and needs vacuuming out infrequently (ie. when the airflow is noticeably reduced)
