### ISSUE TITLE
Check legal aspects of first aid

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#297]
As per issue #242.

**Comment by johnmckerrell** [comment]
I have now emailed Francis Davey

**Comment by DoESsean** [comment]
@johnmckerrell Was there ever a reply from Francis?

**Comment by amcewen** [comment]
Rolled over to next organisers meeting.

**Comment by johnmckerrell** [comment]
"some non-professional advice"

> The HSE's own website is, I think, really helpful.
> 
> http://www.hse.gov.uk/
> http://www.hse.gov.uk/firstaid/
> http://www.hse.gov.uk/firstaid/legislation.htm
> 
> and so on. Have a read. I think there's plenty of material there which is very practical and probably all you need. In short: you do not need to provide first aid for members of the public, but the HSE strongly urges you to make some provision.
> 
> Your duty to the public will include your duty as occupier of your premises under the Occupiers' Liability Act 1957. This is all about risk. I.e. it doesn't prescribe specifics, but looks at the effect of what you do. Your duty is "to take such care as in all the circumstances of the case is reasonable to see that the visitor will be reasonably safe in using the premises for the purposes for which he is invited or permitted by the occupier to be there."
> 
> The 1957 Act is quite short and contains some helpful clarification.
> 
> The idea is to take a common-sense approach.
> 
> For example, there's no obligation to keep an accident book, but you can see how it makes sense. You can pick up any systematic problems and keep a record of what happened. Risk assessment is also good.
