### ISSUE TITLE
Buy a CO2 fire extinguisher

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#298]

**Comment by DoESsean** [comment]
Done.

**Comment by amcewen** [comment]
Pah.  This is the point (after #335) where I want to know where we bought the last fire extinguisher so I can quickly and easily order a replacement.  @DoESsean, if you remember in future it's handy to have a link to the one we bought, in issues like this :-D

**Comment by DoESsean** [comment]
Touché.

The place I have ordered them from is [http://www.safelincs.co.uk/ultrafire-redline-2kg-co2-fire-extinguisher/](url)

There is a company on Regent Street that will refill a 2kg CO2 extinguisher for £15.50 +VAT, and they can be found at [http://www.hroberts.co.uk/](url)

**Comment by DoESsean** [comment]
New extinguisher ordered from same store as last time.

**Comment by stevesparrow** [comment]
Slightly delayed.  Gonna be shipped next Thursday.

---
