### ISSUE TITLE
Move private stuff to gitlabs

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#299]
Organisers stuff from wiki.doesliverpool.com and stuff currently in bitbucket

**Comment by DefProc** [comment]
gitlab.com/DoESLiverpool exists, but I'll need your gitlab.com accounts to add you.

**Comment by amcewen** [comment]
Rolled over to next organisers meeting.

**Comment by amcewen** [comment]
So, we're moving to gitlab for private stuff because we've hit the limit of users allowed for the free version of bitbucket.  Still ongoing.

**Comment by johnmckerrell** [comment]
Destroy bitbucket when complete

**Comment by DefProc** [comment]
The bitbucket repos are there (and have been for 5 months now!). I've just updated the doorbots to the most recent version and invited some organisers.

**Comment by johnmckerrell** [comment]
You mean gitlab right?

**Comment by amcewen** [comment]
Dunno what @DefProc means but he hadn't updated the doorbots to point to gitlab.  As I discovered when I tried to add a new card :-/

I've added a DoESDevices user to Gitlab.com, which has Doorbot1's ssh key set up, so doorbot1 can pull code down.  I've cloned the gitlab.com repo onto doorbot1 (and it's then copied over locally to doorbots 2 and 3, so I've not updated their git repos) and deleted the _config.yaml file from the bitbucket repo as a quick-and-dirty way to make it obvious to people that they should move to the gitlab.com repo :-D
