### ISSUE TITLE
Review financials

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#300]
We're very busy but the total funds line is quite flat, why?

Ideas:
- People paying late and in lumps
- Rates just been paid

**Comment by amcewen** [comment]
Rolled over to next organisers meeting  (i.e. neither @johnmckerrell nor @DoESsean could make this organisers meeting, so I'm commenting to show we looked at it but couldn't do much on it :-)

**Comment by amcewen** [comment]
Generally good.  Seeing some churn of desks.  Net down on desks.  

Do we know why we're not getting new people along?  Should we track how new people come along?

Can @DoESsean list what data we'd like to track, and then we can decide on the simplest way to gather it.

**Comment by johnmckerrell** [comment]
Closing as this is something we generally need to keep an eye on.
