### ISSUE TITLE
Email community about Derby Mini Maker Faire

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#305]

**Comment by DoESsean** [comment]
@DefProc Can you give me a bit of info about what you want this to say please, and I'll put together a mailchimp.

**Comment by johnmckerrell** [comment]
Reckon this is more a mailing list one?

**Comment by DoESsean** [comment]
Happy to do it whichever way people think is best, ditto Manchester.

**Comment by DoESsean** [comment]
Done.
