### ISSUE TITLE
Create doodle for next organisers meeting

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#307]
Include evening slots, around 14th July.

**Comment by DoESsean** [comment]
Ah, it appears I've done this slightly differently, and sent out Doodles
asking for days rather than specific dates. The plan is just to then
schedule a meeting for the day that seems best and see who turns up.

I can change it if you'd like?

**Comment by johnmckerrell** [comment]
Yeah I'm wondering how clear that was from your email, I have a feeling people won't realise that's what you meant. I'd already written the ticket when you suggested just getting feedback on the best day of the week but it's fine if you do that so long as people definitely understand that's what you mean!

**Comment by amcewen** [comment]
Aim for a 6:30pm start for evening ones so @jackie1050, and Wednesday might work better as a day to hold them, given that @huffeec would be able to attend then (although it could clash with other events...).  We'll let @DoESsean schedule the next of each - day and evening, and then close this with the info about when they are.

**Comment by johnmckerrell** [comment]
Sean to update on schedule and close issue

**Comment by DoESsean** [comment]
Meetings will be regularly scheduled from here on out, so there'll be no need for Doodles in the future.

Current suggestion is the first Tuesday of the month, will update once this is confirmed.
