### ISSUE TITLE
buy new ink cartridges for the colour printer

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#308]
It's reporting that they are empty

**Comment by DoESsean** [comment]
Ordered for delivery early next week.

**Comment by DoESsean** [comment]
Original order came, cartridges were incompatible despite being sold as compatible with the model.

New cartridges have been installed today, ordered from Cartridge People. They are printing fine but, as they are refurb (which I don't recall seeing listed on the website), the ink levels are not showing, and I got a pop up from HP saying that they could not report ink levels on non-new cartridges, which is a pain. They were considerably cheaper than buying direct from HP though, so it's worth weighing up the pros and cons of going official/unofficial in future.
