### ISSUE TITLE
Document how to access the DoES entry on coworker.com

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#309]
We'd like to edit the entry so that it more accurately reflects what we offer here in terms of amenities - at the moment, we only have two listed, and there are plenty more that we could claim - and to make sure the opening hours are correct.

**Comment by amcewen** [comment]
I don't.  I'd guess it was one of @johnmckerrell, @osfameron or @OddEssay but I don't know for sure.

**Comment by OddEssay** [comment]
I couldn't get in with either my DoES, or personal email addresses via the "Reset Password" option, so I don't think it's me. 🤔

**Comment by osfameron** [comment]
Not me either (I don't remember championing it, nor is there anything in my
Lastpass list.)  I'd have guessed this was something Sean ran with, but
presumably you already checked that.

H

**Comment by OddEssay** [comment]
Have you tried using the "Contact Space" option and seeing where the message ends up?

**Comment by DoESsean** [comment]
Tried using the 'Contact Space' button, and got a message through saying they'd blocked it as spam, but it would normally go to hello@. 

However, hello is not the registered user, so I can't use that to reset the password. It's also not sean@, so I was at least right about it not being my fault!

**Comment by DefProc** [comment]
Sorted, @DoESsean has the access.

**Comment by amcewen** [comment]
I've reworded the issue title to a more useful problem definition, and am reopening it now as "someone who might leave once knew about it" isn't a good way to pre-empt having to solve this issue again in future :-D

**Comment by DoESsean** [comment]
The password for coworker.com is now in the Passwords page of the wiki.

It's attached to my account, and everything can be changed and updated from the user control panel.
