### ISSUE TITLE
update doorbot 3 because it's very out of sync

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#310]
There are now a noticeable number of users who don't have their key on doorbot 3 because it's always down when key updates are run.

**Comment by madjake45** [comment]
Would this be better if this could have the doorbot itself pull the
updates?

**Comment by DefProc** [comment]
It would, although there's currently no testing on the validity of the YAML config file after upload (they sometimes have missing colons or other similar errors), so it's possible that the doorbot could be left unusable on reboot. The current strategy is to use a script that has the user check the upload to doorbot 1 in screen, before choosing whether to deploy to the other bots. 

Is there a yaml testing process we could use?

**Comment by amcewen** [comment]
Doorbot3 has been updated.  Having the doorbots update their own config feels like something that #175 should take care of (as in, such functionality should be discussed and implemented as part of that, rather than as part of this bug :-)
