### ISSUE TITLE
Arrange next viewing

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#317]
Arrange another viewing for Village employees, Telecoms Cloud,  Aidan and Rob & Lawrence. Ideally before the 29th July.

**Comment by johnmckerrell** [comment]
Any update on whether this can go ahead?

**Comment by amcewen** [comment]
Don't know anything about how it's progressing, but @goatchurchprime and Martin would like to attend too.

**Comment by johnmckerrell** [comment]
Ok we were aiming for tomorrow 28th July as that was what Village suggested but I don't know if @DoESsean has managed to guarantee the keys.

**Comment by DoESsean** [comment]
Yes, it's on, spoke to Brian yesterday. He can't be there, but the keys are
back.

**Comment by johnmckerrell** [comment]
Great, and Village have confirmed? 4pm is that right?

**Comment by mdunschen** [comment]
4pm should work for me. Are we meeting there or at Gostin's?

**Comment by DoESsean** [comment]
Village have confirmed for 4.

I'll be collecting the keys at about 3:30, so anyone who wants to is
welcome to walk up with me then, or I can just meet people at the building
at 4.

**Comment by johnmckerrell** [comment]
Marking this as complete as that visit occurred. We can have a new issue if we do another viewing.
