### ISSUE TITLE
Get full measurements of Castle House

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#318]
A lot of questions we have revolve around the available space so getting full measurements will be a great help.

**Comment by amcewen** [comment]
Dimensions of the lift door would be handy (and any identifying marks in case it's a standard size?) and guesstimates on size of the lift itself

**Comment by johnmckerrell** [comment]
[Castle House Overview, Liverpool, Castle Street.pdf](https://github.com/DoESLiverpool/somebody-should/files/393804/Castle.House.Overview.Liverpool.Castle.Street.pdf)
[Castle House, North Street, Liverpool.pdf](https://github.com/DoESLiverpool/somebody-should/files/393803/Castle.House.North.Street.Liverpool.pdf)

First PDF has the dimensions of the top two floors if we knocked out the walls for the meeting room. The second has dimensions of the rooms as they currently stand. The 2nd Floor is in twice as I wasn't sure about the accuracy of the first measurement so "Floor 2" is the (hopefully) more accurate one.

**Comment by johnmckerrell** [comment]
No longer relevant
