### ISSUE TITLE
Redesign DoES flyers and business cards

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#32]
This came out of the DoES Promotion Meeting last week - http://wiki.doesliverpool.com/DoESPromotionMeetingMinutes20141006

Our current flyers don't have much information on them.  It would be good to have a redesign that does a better job of selling what we are.  Plus it would be good to get some business cards designed and printed at the same time, as they're easier for people to carry with them.

One suggestion was for the card/flyer to count as a "1st day free" voucher too.

What other information should it include?
 * Website
 * Details of desks
 * Details of workshop
 * One or two lines of description of what DoES is (i.e. the community side of things)
 * Mention of events?

**Comment by amcewen** [comment]
bump (on the advice of @DoESsean :-)

**Comment by amcewen** [comment]
Okay, so I realised that it'd be handy to have something to hand out at the International Women's Day even that we're running on Sunday 8th March.  So, in a "will this do as a start" approach, I'm thinking that maybe getting some Moo cards printed so there are business cards at least - and they can have nice photos on them to make them more interesting (without us having to do too much design work :-)

I've fleshed out some copy to go on one side, along with the DoES logo - comments/improvements/etc. welcome, see http://piratepad.net/HB8qCsfi8i  I'll arrange it on a Moo card this evening so we can order them tomorrow if that sounds like a plan. @DoESsean (and anyone else who wants to), can you pull together a collection of interesting photos we can use for it - I'm thinking we'd want at least one of each room, and then plundering the weeknotes and our Flickr stream for photos of projects, people, etc. for the rest...

**Comment by DoESsean** [comment]
I'll have a look for some pictures today. I assume we're not wanting any
with non-organiser people in them? Just in case anyone gets annoyed.

**Comment by osfameron** [comment]
Re non-orgas, that's probably a good guiding principle -- but if you find
an otherwise perfect photo, check it with an organiser, as there are
"Friends of DoES" who we can probably volunteer for being fine with it :D

**Comment by DoESsean** [comment]
I've just dropped a folder called 'Moo Photos' into the DoES dropbox. How
many of them will be good enough, I don't know, but there's a fair few in
there for you to choose from, John. If anyone else wants to add some, have
at it.

**Comment by amcewen** [comment]
Thanks Sean - for future reference, I had to find hi-res versions of most of them as Moo prefer bigger photos for print - but have designed a business card (in Dropbox/DoES/Logos Flyers and Posters as DoESLiverpool-PromoBusinessCard.[svg|png]) and ordered 200 moo cards in time for IWD.

**Comment by amcewen** [comment]
The cards have arrived.  I've taken some and left the rest on @DoESsean's desk (for him to stash somewhere and then make a note of where here :-)

**Comment by amcewen** [comment]
Oh, see https://www.flickr.com/photos/amcewen/16110088224/ for a look at what they're like

**Comment by djyldyz** [comment]
The link doesn't seem to be working.

By the way, I'll be at the Geek Girl event on Sunday so see you there!

**Comment by amcewen** [comment]
Ah, sorry, had forgotten that my tablet uploads things to Flickr as private by default.  Have made it public now.  See you on Sunday!

**Comment by amcewen** [comment]
Given that the business cards have been well received, we can probably count them as redesigned now (and whenever re-ordering consider adding some new pictures to the set).  So that leaves the flyers to be reworked...
