### ISSUE TITLE
Work out detailed financials

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#320]
Castle House is looking likely but we need to make sure we can afford it. Compose some more detailed financials including costs to refit, rates, rent, internet etc.

**Comment by mwnw00359** [comment]
I'm happy to help create these with you John or whoever...

**Comment by johnmckerrell** [comment]
Not relevant for Castle House but I'm going to leave this one open, if possible it would certainly be useful for @mwnw00359 to take a look at what we drew up and highlight any problems.

**Comment by stevesparrow** [comment]
Matt provided some useful notes on the financials we have, and the structure.  A couple of people will be taking another look at these shortly, as we look for new buildings.
