### ISSUE TITLE
The long VGA cable for the projector is missing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#323]
Has anyone seen the long VGA cable to go with the big projector in Dinky?

There's a short one on @paulfurley's loan monitor which we can use if need be for meetups, but that means the monitor can't be used at the same time.

We need to either find the one we used to use, or buy a new one so the projector can easily be used whenever.

**Comment by paulfurley** [comment]
Also I wrecked one cable already  by plugging it in and out lots of times :(

Sent on the move.

**Comment by epsaul** [comment]
I may be the guilty party here! I seem to recall having acquired a pretty long lead round about the time I used my desktop in Dinky to run a virtual mixing desk for the Karaoke after Make Fest. When was it last used? If before Make Fest it could well be me.
I think it's still plugged into the back of my desktop next to my desk if you need it urgently. If not I'll check and if I've got it, put it back when I'm in next (tomorrow, Thursday).
Ed.

**Comment by amcewen** [comment]
Ah cool, that could well be it.  I'm not sure how long it's been awol, but over a week.  It's not needed urgently, Friends of the Earth had a workaround last night.  I was just raising it while I remembered.

**Comment by amcewen** [comment]
All sorted by @epsaul, but as he doesn't seem to want the credit from closing the issue, I'll tidy up for him :-)
