### ISSUE TITLE
Register for data protection

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#326]
I don't think we've registered for data protection and we probably should. The main thing is the CCTV, that's an instant "yes" but I think even without that we would need to because we're keeping people's data indefinitely (beyond them being a member, though we don't have membership so I'm not completely sure how that would work).

**Comment by DoESsean** [comment]
All done. John is listed as the officer in charge (mainly because he has access to the cameras), and the relevant paperwork will be sent out.

**Comment by DoESsean** [comment]
Issue reopened as, as @amcewen so astutely points out, 'Has the paperwork arrived already?'

One day I will close one of these correctly.

**Comment by johnmckerrell** [comment]
I've just received a "Security number" by email.

**Comment by DefProc** [comment]
@johnmckerrell does that mean it's complete?

**Comment by amcewen** [comment]
Organisers' meeting notes: paging @johnmckerrell

**Comment by johnmckerrell** [comment]
Yes we are, there's no paperwork but I have 3 emails including one that confirms we're on the register, I found our listing here:

https://ico.org.uk/ESDWebPages/Entry/ZA207178

**Comment by ajlennon** [comment]
Am I right in thinking it's a requirement to have a set of policies for this?

**Comment by euanwithersby** [comment]
Yes! The GDPR supersedes the DPA as of 25 May 2018. It's a regulation rather than a directive and is very different from the DPA. The ICO website has done good guidance on what you need to do as an organisation.

**Comment by euanwithersby** [comment]
DoES will also need a retention policy for data, an organisation can't keep personal information ad infinitum as this breaches the 'not held longer than necessary' principle. Perhaps categories of involvement ought to be introduced? Do have a look at the exemptions, though. It may be that some of the data doesn't require notification (although DoES should still aim to abide by the principles).

**Comment by ajlennon** [comment]
So... I'm assuming there is no official DoES policy (please somebody correct me if I'm wrong).

If that's true does it mean DoES is currently in compliance but will not be in compliance from May 2018 @euanwithersby  or would DoeS not be in compliance now?

**Comment by euanwithersby** [comment]
Check out the small business compliance checklist, it lists a policy for dealing with data protection issues: https://ico.org.uk/media/for-organisations/documents/1558/getting_it_right_-_how_to_comply_checklist.pdf . I'd just spend a bit of time on this and start looking now how this changes for GDPR. For the latter, for instance, you are required to ascertain and monitor that any 3rd party processors are also compliant - this could even be the booking forms website used for the workshop (I.e. Customer data for DoES being processed by the third party company)

**Comment by ajlennon** [comment]
@DoESsean can you comment on the current status wrt this?

**Comment by euanwithersby** [comment]
I've had a look at the notification. I know you're just using the 'General Business' profile that ICO provide for notification, but I'm assuming that DoES isn't actually processing sensitive data?

**Comment by johnmckerrell** [comment]
It's pretty much just the names and addresses that get collected from inductions and used on invoices, then also the CCTV which gets stored.

**Comment by ajlennon** [comment]
Interesting mail just came in on GDPR and what Wetherspoons is up to:

"Join major companies on the path to compliance
Pub chain J.D Wetherspoons announced this week that they are deleting their entire customer email database, and ceasing all their email newsletters. 

This action follows a recent data breach suffered by the company, in which it is reported over 650,000 email addresses were affected. 

Major companies are sitting up and taking action, with the May 2018 deadline for the enforcement of the General Data Protection Regulation looming, and the Information Commissioner’s Office (ICO) gearing up to hand down significant fines for those found in breach. 

GDPR will overhaul the way data will need to be collected and processed, handing the power back to the user. The new directives will have a substantial impact on any organisation with operations in the UK and EU – making it pivotal that companies take action.

Wetherspoons’ decision is certainly a drastic one, as businesses are not required to delete their customer email databases under the regulation, but it demonstrates the true scale of the impending GDPR and serves as a signpost of things to come. Your customer email database may be a millstone around your neck at the moment, but deleting it entirely is not an option for most businesses."
