### ISSUE TITLE
New kettle in the kitchen is bogus

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#328]
The lid is tiny and under the handle so your fingers are in exactly the right place to be in the way of removing the lid, getting burnt by steam when you get the lid off, and then they block up the hole when you try to fill it.  

Can we have something like this instead:
http://www.telegraph.co.uk/money/ask-a-money-expert/i-want-an-instant-boiling-water-tap--will-it-cost-more-than-usin/

How about teabags in the laser cutter water?

**Comment by johnmckerrell** [comment]
Lamenting the loss of the eco-kettle from years past. We'll need to expand our Kickstarter stretch goal to get one of these in the new place.

**Comment by DefProc** [comment]
It is possible to fill the kettle via the spout. Thereby negating any requirement to lift the lid. 

@goatchurchprime Does that solve the problem for you?

**Comment by stevesparrow** [comment]
In the interests of a middle-ground solution (£22 shouldn't stop us spending a lot more at some point...), I've bought a new quick boil kettle, that won't regulary burn me!

As well as being rather slow, the water level indicator in the current one is broken, which means opening the lid and well, Julian put it best.  The new one is the same one I have at home, a 3KW fast boil, clear sided jug kettle kettle, that works rather well.

Steve

**Comment by aubergine10** [comment]
Closing this ticket as the current kettle seems to be the good clear-sided one mentioned in last comment.
