### ISSUE TITLE
Take lots of photos of Castle House for planning

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#329]
If you're aware of anything specific that needs detailed photos list it below

- [ ] Lots
- [ ] Steps (or similar accessibility issues) on upper floors (at least), to aid in getting quotes for reworking things
- [ ] Light fittings / ceiling treatment for investigations into replacing/improving them
- [ ] Damaged areas, similarly for quotes on repair (in case we negotiate for us to repair them)
- [ ] Lift area, motor room.

**Comment by johnmckerrell** [comment]
I had hoped to get these on Thursday 28th July but didn't get time so this is still outstanding.

**Comment by mwnw00359** [comment]
I'm happy to do this and bring my camera along at the next visit.

**Comment by johnmckerrell** [comment]
No longer relevant
