### ISSUE TITLE
We should Internet-of-Things-ify the business address pigeonholes

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#33]
Now that we offer a mailbox service, and have some (almost assembled ;-) pigeonholes for people's post, it would be nice if they were connected to the Internet and could automatically notify people when they've got post.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
