### ISSUE TITLE
Find out cost and accessibility details for 110-114 Duke St

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#332]
One building we've not had on our list before, but which could work as a new DoES venue, is 110-114 Duke St.

We should find out how much they want for it, and ask them what the accessibility is like (it seems to have a few steps up to the main door)

Details below...

http://wwww.keppiemassie.com/Properties/CommercialAgency/110-114-duke-street-duke-street-liverpool-l1-5ag
http://wwww.keppiemassie.com/uploads/pdf/499_51016_0.pdf

**Comment by mwnw00359** [comment]
Called them today and was told its gone, plus the guy who deals with it is on annual leave for two weeks and he appears the only person in the entire company that knows anything about it. Keep looking I suppose!

**Comment by franticorang** [comment]
I hadn't spotted Matt's comment when I phoned the agent last week.  Sorry about that Matt. 

Agent was away but he called me back today.  The landlord is re configuring the whole space - putting in a new lift, putting in a separate entrance etc.  

They think they should know more in about 6-8 weeks with a possible completion of works by Jan/Feb 2017.   I asked them to keep our details on file and send us plans when they have them.

**Comment by johnmckerrell** [comment]
Bumping this as relevant, @DoESsean will hopefully give them a call on Thursday unless someone else particularly wants to.
