### ISSUE TITLE
How much do other spaces charge round the city?

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#333]
There's a reasonable chance we might need to register for VAT with a new building, which we'll need to work out how that affects our prices.  Plus the price for a full-time desk hasn't changed at all since we set it five years ago.

It'd be good to get an idea of how much similar places charge, round the city, as that might well have changed since we last looked at it when first setting up DoES.

Not to say we're definitely changing the pricing, but it's one of the many, many factors to weigh up in working out how we afford a move.

**Comment by johnmckerrell** [comment]
Not Liverpool but I hear of a company in Norwich paying £150+VAT per-desk. Sounds very similar to DoES as it includes rates, tea&coffee, wifi, use of shared meeting rooms and is per-desk in a shared space.

London however is multiple-k for a 3m x 3m room that reasonably fits 4 people (facing the walls).

**Comment by amcewen** [comment]
Ziferblat at the Albert Dock is 8p/minute.

Launch 22's details are at http://www.launch22.co.uk/liverpool-membership - £120+vat/month for full-time hot-desking, £200+vat/month for a desk to call your own.  They've also got part-time (up to 10 days/month) and evenings (4pm-8pm) for £60+vat/month.

**Comment by johnmckerrell** [comment]
Cotton Exchange is £130 + VAT 24/7 full time for a month.

**Comment by mwnw00359** [comment]
None has the fab workshop doES has, making it less comparable. Compulsory VAT registration is currently £83K, I assume DoES is nowhere near that? and therefore its the rental side of things that VAT needs to be charged for.  If the lease DoES signs includes VAT, then DoES would need to charge or absorb the VAT back to customers, unfortunately that would mean that all of the non-rental activities would need the prices changing also, unless (and its to investigate) you keep the property in a separate company to just hold the lease.

**Comment by aubergine10** [comment]
If you do need a VAT company, keep it separate from the other stuff as mentioned in last comment.

[Accelerate Places](https://www.accelerateplaces.com/manchester-coworking-office-space) in Manchester:

    * Reserved desk £295/mo + VAT
    * Hot desk £20/day + VAT
    * They offer bolt-on services such as access to in-house legal, marketing, etc services (not sure what charges are for those)

I've not seen any offerings that bring a group of makers in to the equation like DoES does. Are there any?

A goal, IMO, should be to have highest possible utilisation of the desks 24/7. I imagine evening/weekend availability will be very useful for anyone already in full-time employment who is seeking to start their own business. Thus an "Evenings + Weekends" package would be worth investigating.

I assume someone has asked the existing DoES desk users what they want and what made them choose DoES, etc., and compiled the results somewhere?

**Comment by euanwithersby** [comment]
That's mostly more expensive than Liverpool. Launch22 is £10+VAT / day and Ziferblat is/was capped at around £14 something. There are some very different places around the city but none have the unique feel of DoES. There's an increasing amount of competition and a lot of it is quite slick about how the place operates for the people spending their cash. Some of the other places are a bit style over substance but I think that DoES has come a long way by keeping desks clear and a more welcoming approach (the cake garden!) - just needs more in the way of marketing.  Oh and a clear meet n greet too (or a 'talk to me!') sign as people are still hovering in the doorway looking for the right person to talk to.

**Comment by ajlennon** [comment]
Where is this cake garden, pray tell ‽‽‽

**Comment by euanwithersby** [comment]
Ah, it hasn't made it to fruition then?

**Comment by johnmckerrell** [comment]
Not yet, I have some astroturf in an envelope on my desk though! https://github.com/DoESLiverpool/somebody-should/issues/472 <https://github.com/DoESLiverpool/somebody-should/issues/472>

**Comment by johnmckerrell** [comment]
Could this be closed now as I think we have a good general idea how much other spaces charge?
