### ISSUE TITLE
Sophia is slipping when doing engraves and cuts on both axes

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#334]
Not had 5 mins to look at it in detail but Stephen had issues with it today

**Comment by saghul** [comment]
Can confirm. It's specially noticeable on engravings.

**Comment by amcewen** [comment]
It's been getting worse and now at the point where she's basically unusable.  Marking her as broken until we get chance to investigate further.

**Comment by amcewen** [comment]
It seems worst on the x-axis, and easiest to provoke either when running a datum from the far end of the bed (thus having the most time to gather speed before hitting the left-edge) or when running a test in the middle of the bed.

I've had a bit of a poke around but not found too much.  The targetting laser wires looked like they **might** be fouling things (and are just lose wires now), so I moved them out of the way.  That seems to have improved the "datum grinds lots at the left edge" problem, and it seems to be stopping for the datum slightly further right than it used to.

Running tests in the middle of the bed still causes just as much trouble though, so this isn't sorted.  I'll try giving the rails a bit of grease in the morning (couldn't find any grease in the workshop just now)

**Comment by amcewen** [comment]
I greased the rail this morning, but it hasn't made any difference :-(

I think we'll need some more in-depth investigating.  I'll take a look at Maker Night on Thursday.

**Comment by huffeec** [comment]
With further dismantling it looks like the two x axis belts may need replacing. 

They are part 456MXL 1125 x 10mm

**Comment by amcewen** [comment]
I've ordered 2.5m of the 9.53mm wide belt from http://www.beltingonline.com/mxl-open-length-rubber-belting-10002 (there were cheaper suppliers on ebay, but only ones shipping from China)

**Comment by amcewen** [comment]
The belts arrived today.  @saghul, Paul G and I spent makernight fitting them.

The belts are fitted, and seem to have stopped the grinding problem :-D

However, the y-axis datum has started triggering early - especially if the x-axis needs to move too.  It's most obvious if the head is positioned in the bottom right corner and then datum is performed, but doesn't only happen then.  Running datum twice - once to get the x-axis homed, and then a second time will usually home the y-axis, but there's obviously something wrong and that's not a *good* solution.

Given that the bed still needs to be bolted back into the case, the fan duct and fan refitted, and the mirrors aligned, for now it's still out of action.  To get back to testing, it needs the kettle lead on the right-hand-side to be plugged in.

**Comment by johnmckerrell** [comment]
I've updated the calendar to show Sophia out of action inclusive of Monday.

**Comment by DefProc** [comment]
As the datum error happens less than half the time, I've refitted the bed and aligned the mirrors so Sophia is now back in service.
