### ISSUE TITLE
Need new fire countermeasures for the laser-cutters

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#335]
There was an acrylic fire in Gerald now - after the cut had finished, so presumably the protective film on the acrylic underneath had caught fire out-of-sight and then set fire to the rest of the sheet of acrylic.

Laura deployed the fire blanket, but that had little effect, and some acrylic had dropped through the bed and set fire to the scraps below.  So we used the CO2 fire extinguisher to put out the fire under the bed and then also the fire still running quite nicely underneath the fire blanket(!?!)

So, CO2 extinguisher seems to be better than fire blanket.

We need to get a second fire extinguisher to replace the fire blanket, and get the current fire extinguisher re-charged.

There's still some CO2 in the current extinguisher, so it's still available while we get the new one, but everyone should pay even more attention than usual, in order to catch fires before they take hold as much as possible.

Thanks to Laura's prompt action, there wasn't any damage to Gerald.  I cleaned his mirrors and lens in case there was any smoke on them, and he's still in service.

**Comment by amcewen** [comment]
There's still some CO2 in the fire extinguisher next to Gerald's computer BUT BE CAREFUL IF YOU PICK IT UP AS THERE'S NO PIN IN THE HANDLE, so if you squeeze the red handles together you'll squirt VERY COLD CO2 out of the end.  I've positioned it with the nozzle facing away from anyone who might get hold of it to mitigate the risk from that.  (And we'll get it recharged and with a new pin in as soon as possible).

**Comment by johnmckerrell** [comment]
This suggests we'll get 10s of discharge time so I doubt there's much left:

http://fire-extinguisher-information.co.uk/discharge-time.htm

**Comment by amcewen** [comment]
The new CO2 extinguisher has arrived and is next to Sophia's computer (although @DoESsean hasn't posted a link here to where he ordered it from for future reference... :-).  

We still need to get the half-empty one recharged.  @DoESsean found that [H. Roberts & Son](http://www.hroberts.co.uk/) on Regent Street can refill that, for ~half the cost of a new one (£15.50+vat).  Does anyone with transport want to offer to take it along and get it refilled?  Obviously DoES will reimburse the cost.

**Comment by amcewen** [comment]
Mea culpa.  @DoESsean did post a link, but over on issue #298 :-)

**Comment by cheapjack** [comment]
Wonder if it's worth getting a fire blanket also? alot of cardboard fires just need patting down so a quick 'blanket throw' could avoid the need for the extinguisher in first instance then we could advise people to use that next if the blanket fails? In most cases doubt it would be needed.

**Comment by DoESsean** [comment]
It makes some sense, and I would have no qualms about having one as another precaution, but I'm not sure if everyone agrees - when we last bought fire safety equipment, it was decided that a second extinguisher would be of more use than a blanket, so we didn't replace the one that had been used.

**Comment by DefProc** [comment]
After a quick discussion IRL in the office, the blanket has been dropped in favour of just a CO2 extinguisher because when used in anger, the blanket has been thrown over the moving arm, creating more of a fire tent. Which doesn't extinguish anything. 

As the CO2 extinguisher has been shown to be more useful in practice, we'll stick with just that for the time being. Although it's still open to review.

**Comment by amcewen** [comment]
Does anyone know what happened to the needs-to-be-recharged fire extinguisher?  It doesn't seem to be in the workshop any more.  Is someone in the process of getting it recharged?

The remaining extinguisher now needs to be recharged too, as there was an acrylic fire in Gerald just now.  It was caught before any real damage was done - I've cleaned the lens and replaced the short length of air-assist tube that had melted enough to have a few holes in it.

**Comment by amcewen** [comment]
Can anyone do a run to Regent Street to get the three extinguishers in the workshop refilled for us?  DoES will pay for it, obviously, but we could do with someone with transport who can take them over there.

**Comment by amcewen** [comment]
From organisers meeting, @DoESsean to chase up.

**Comment by johnmckerrell** [comment]
I've used the extinguisher next to Gerald today, obviously still had some in but we should refill (or report back here if the previous refill happened!)

**Comment by DefProc** [comment]
Did this refill happen? @DoESsean

**Comment by DoESsean** [comment]
It has not yet happened, and is something I think about regularly.

It's going to need a vehicle to make the trip, so I'll see if I can sort
out getting the car one day.

**Comment by johnmckerrell** [comment]
Just given them a call and they mention that they won't do it there and then, you need to leave the extinguisher(s) with them and they'll call when filled. I'm wondering if it's possible to do on a bike, I forget how heavy they are (and of course they will be heavier when filled!) Obviously if we do this we have to make sure we don't take *all* leaving no protection back in DoES.

**Comment by johnmckerrell** [comment]
I performed a test with one of the extinguishers last week. Both of ours weighed 4.6kg even though they'd both been used, they claim to have 2kg of CO2 in. I then discharged one of them completely, it lasted for more than 20s until you could say it wouldn't be effective anymore. At that point it weighed 2.6kg. I also briefly tested the one that was here originally and it did discharge.

I have since taken the emptied extinguisher to be filled (and commissioned) so will pick that up shortly.

**Comment by ajlennon** [comment]
I'm working with some people on fire prevention and we have an idea for a proximity sensor that switches off the power if a person leaves the vicinity. Is that something interesting? (i.e. might I test that out on some laser cutterers?)

**Comment by johnmckerrell** [comment]
Could be interesting. 

--

**Comment by johnmckerrell** [comment]
Filled extinguisher is now down the side of Sophia. Interestingly its weight was 4.4kg and the existing one seems to have dropped to just under 4kg. Probably the scale isn't too good at that end of the range as its max allowable is 5kg. Was £15.50+VAT and receipt is on @DoESsean's desk.

Closing this ticket as we now have the countermeasures for the lasers. I'd be interested in @ajlennon 's idea but would expect it needs a warning buzzer, like "RETURN TO THE LASER, YOU HAVE 10 SECONDS TO COMPLY".

Obviously the other extinguisher should really be recommissioned but we also need a full fire assessment done on the new space so I'm happy to wait for that.

**Comment by amcewen** [comment]
Just a note on @ajlennon's suggestion, in case someone is reading through this issue in future and implementing it - it would be better to tap into just the laser firing circuit rather than pulling power on the entire laser cutter.  There's already a safety cut-off for the flow sensor and lid open sensor which turns off the laser - adding the "not attended" sensing as a thing that turns off the laser to that would work best.  That would allow someone to pause the laser mid-job and, for example, go to the toilet, without coming back to a completely ruined job.

**Comment by DefProc** [comment]
Although it's probably worth looking at what's practical vs the risk of
damage. If it's very difficult to get good cut jobs from the cutter, and
no-one wants to use the machine (eg dead man's handle), that's worse for
DoES.
