### ISSUE TITLE
Postal/physical address on website mobile

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#337]
There is no way to look up the postal-physical address of DoESLiverpool when you open it from the phone.  

There's some kind of mobile setting that strips off all this useful stuff.  This makes it tricky for people who trying to find the building to look up the details again.

**Comment by DefProc** [comment]
It has always been there on the page — although the phone view puts those links right at the bottom. 

I've added `location` as a menu item so you can now find the location page from the menu button at the top of the page too. 

There's probably a larger discussion around the ordering and display of links on the website as part of #19
