### ISSUE TITLE
When datuming Sophia, the head sometimes stops out of the corner

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#339]
From @amcewen in #334:

> However, the y-axis datum has started triggering early - especially if the x-axis needs to move too. It's most obvious if the head is positioned in the bottom right corner and then datum is performed, but doesn't only happen then. Running datum twice - once to get the x-axis homed, and then a second time will usually home the y-axis, but there's obviously something wrong and that's not a good solution.

It's possible that the sensor it's self is worn and damaged where the head sometimes makes contact with it.

**Comment by amcewen** [comment]
As we've not had any complaints about it (that I'm aware of - feel free to reopen if I'm wrong) from any of the users in the past month, I'm going to close this off as "invalid" (i.e. not really a bug, if no-one's seeing it)
