### ISSUE TITLE
Create the DoES Showcase on the bookcase in Dinky

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#34]
The bookcase in Dinky has somewhere between 12 and 16 spaces for showing off things created by the DoES community.

We should curate an ongoing showcase of things.  Each one should have a little museum-/gallery-style display card explaining what it is, like the ones we had for the Internet World showcase (basically a print-out on paper spray-mounted onto some foamcore).

What things could we show off initially?
- Bubblino
- WhereDial
- Red-Violet made laser-cut book?
- One of Djyl's origami lampshades?
- Patrick's laser-cut Doodlebot?
- Guard-o-Tron 3000
- Shrimp weather station
- Designing the Internet of Things?
- Housahedron kit?
- Some of Ross' Minecraft kit?

It'd be nice to write a blog post for each item that gets added to the showcase, so (a) we can show on the website the sort of things that get made here, and (b) it lets things stay in the online showcase even after they've been superseded in the physical showcase

**Comment by aubergine10** [comment]
As there's now a bookcase in Dinky filled with various curiosities, I'm assuming this issue can be closed.
