### ISSUE TITLE
The clock on the wall in Dinky needs a battery(?)

### ISSUE THREAD

**Issue by OddEssay** [DoESLiverpool/somebody-should#340]
The clock on the wall in Dinky needs a AA battery.

I wasn't sure if we have a store of them anywhere. 🤔

**Comment by amcewen** [comment]
We do have a store of AA batteries - they're in the multimeter drawer in the workshop, IIRC.  I replaced it a couple of weeks ago but wanted to check it was working before closing the issue and then forgot to check the time had advanced :-)  Till now, anyway.  All running fine now.
