### ISSUE TITLE
Create a DoES Liverpool chores list on the wiki

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#341]
Nottinghack have a good list of chores that everyone can do to help keep the space running smoothly and be a nice place to work/play - https://wiki.nottinghack.org.uk/wiki/Chores

We should have something similar on the DoES Liverpool wiki https://github.com/DoESLiverpool/wiki/wiki

**Comment by johnmckerrell** [comment]
I've made a start https://github.com/DoESLiverpool/wiki/wiki/Chores

**Comment by DoESsean** [comment]
Closing this as it crosses with #556
