### ISSUE TITLE
Sophia has a slight wobble in one direction on the y-axis

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#342]
Rather than re-open #334 Ive raised this to look into when we next look at the datum issue (which incidentally has not yet re-occured). Jim noticed it this afternoon while cutting some of his model railway houses

**Comment by amcewen** [comment]
That's good - I don't think it's the same issue as #334 (or maybe that #334 was two issues rather than one).  It could be that its a recurrence of #198...

**Comment by amcewen** [comment]
Organisers' meeting notes: Assuming this is a duplicate of #198 (assuming it's still an issue).
