### ISSUE TITLE
Get details for more possible new-DoES locations

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#344]
I ended up doing some wandering round the city centre over the weekend, and spotted a few potential venues...

A few round Derby Square:
- [ ] [Merchants Court](http://propertylink.estatesgazette.com/externalsearch/3355184?UserID=hwandp&action=external_search&controller=third_party_search%2Fhtml&fullUrl=http%3A%2F%2Fwww.hitchcockwright.co.uk%2Fsearch.html&liPropertyState=10315%2C10313&module=third_party_search&page=3&sTown=liverpool&third_party_params[CurrentPage]=&third_party_params[MaxRecords]=20&third_party_params[PropertyStates]=10315%2C10313&third_party_params[SizeRange]=&third_party_params[Town]=liverpool&third_party_params[UserID]=hwandp&third_party_params[WithImagesOnly]=&third_party_params[fullUrl]=http%3A%2F%2Fwww.hitchcockwright.co.uk%2Fsearch.html&third_party_params[page]=2&third_party_params[sTown]=liverpool&third_party_params[third_party_params][CurrentPage]=&third_party_params[third_party_params][MaxRecords]=20&third_party_params[third_party_params][PropertyStates]=10315%2C10313&third_party_params[third_party_params][SizeRange]=&third_party_params[third_party_params][Town]=liverpool&third_party_params[third_party_params][UserID]=hwandp&third_party_params[third_party_params][WithImagesOnly]=&third_party_params[third_party_params][fullUrl]=http%3A%2F%2Fwww.hitchcockwright.co.uk%2Fsearch.html&third_party_params[third_party_params][sTown]=liverpool)
- [ ] [Victoria House](http://www.downing.com/office-retail/victoria-house/ground-floor-victoria-house/)
- [ ] [Queens Building](http://www.propertypilot.co.uk/pdf/160+544.pdf)
- [ ] [Crown House](http://www.propertypilot.co.uk/pdf/160+1489.pdf)

A couple around the Met Quarter:
- [ ] [42-44 Stanley Street](http://www.propertypilot.co.uk/pdf/160+2347.pdf)
- [ ] [1-3 Temple Court](http://www.corepmc.com/home/properties/liverpool-l2-1-3-temple-court.aspx)

And a few others:
- [ ] [State House](http://www.propertypilot.co.uk/pdf/160+710.pdf)
- [ ] [North House](http://www.corepmc.com/home/properties/liverpool-north-house.aspx)
- [ ] [14 Cook Street](http://www.corepmc.com/home/properties/liverpool-l2-14-cook-street.aspx)
- [ ] [31 Castle Street](http://www.propertypilot.co.uk/pdf/160+1694.pdf) (Possibly just for sale rather than let)

**Comment by mwnw00359** [comment]
Just seen this advert on 10 Duke Street 
![img_20160912_132005](https://cloud.githubusercontent.com/assets/20774743/18442562/2eef3588-7909-11e6-90ae-8e38cdb88cdf.jpg)

**Comment by DoESsean** [comment]
Merchants Court - looked after by Brian Ricketts, who also dealt with North Street. He doesn't think it will be suitable for us.

Victoria House - sent a message to arrange a viewing. Will update.

Queens Building - contacted Mason Owen to arrange a viewing. Will update.

Crown House - contacted Mason Owen to arrange a viewing. Will update.

42-44 Stanley Street - contacted Mason Owen to arrange a viewing. Will update.

1-3 Temple Court - contacted Core to arrange a viewing. Will update.

State House - contacted Mason Owen to arrange a viewing. Will update.

North House - contacted Core to arrange a viewing. Will update.

Cook Street - already seen. Not suitable - the available space is split in ways which would not work for us, and there are accessibility issues.

**Comment by DoESsean** [comment]
Visited the property at 10 Duke Street with @johnmckerrell and Jen Fenner. That office was not suitable, but they have another premises at 71/72 Tradewind Square (in the East Village complex). We have arranged a viewing for 10am on Monday 31/10.

**Comment by DoESsean** [comment]
Contacted Cushman & Wakefield re: [90 Duke Street.](http://office.cushwakeproperty.co.uk/property/display/176647-90-Duke+Street-Liverpool-Merseyside-L1+5AG-United+Kingdom) Will update.

**Comment by amcewen** [comment]
Shame about 10 Duke Street, given that 109 years ago it was the first factory for a certain maker-friendly toy... http://www.liverpoolpicturebook.com/2012/09/MeccanoLiverpool.html :-)

**Comment by DoESsean** [comment]
The Tradewind Square property was interesting, but probably no good for us. It was much too small for a start.

90 Duke Street was great, but incredibly expensive.

I'm putting together a sheet which will consolidate all the places we have so far seen into one location, so that we can know what has and hasn't been written off, and why.

**Comment by mwnw00359** [comment]
How about this? just come onto the market... 

[90 Duke Street.pdf](https://github.com/DoESLiverpool/somebody-should/files/774313/90.Duke.Street.pdf)

**Comment by ajlennon** [comment]
+1

**Comment by shrkey** [comment]
Looks very shiny and new - too shiny for laser cutters and workshop?

**Comment by willcrobinson** [comment]
Sean's comment on 5th Jan in the thread above says that 90 Duke Street was incredibly expensive so it probably isn't an option. :disappointed:

**Comment by johnmckerrell** [comment]
@mwnw00359 yeah we were told £17.50+£5 /sqft (rent + service charge), I believe Francis Irving has talked to them some more.

As an update to this ticket we recently looked at a property on Williamson Square which looked decent but it seems like the agent didn't think we'd be able to afford it. We've also looked at a property at 88 Church Street which looks quite promising. Over the Lloyds TSB bank.

**Comment by frabcus** [comment]
90 Duke Street have (to me at least!) now come down to £14 + £5.79 / sqft (rent + service charge). So a bit better.

I really like the location, as if we can get the ground floor it would be nice and visible, and I think good for people finding out about DoES. My instinct is that the publicity benefit of being there would be quite high, but I could be wrong.

I've followed up to double check it isn't too shiny for the kind of workshop equipment we have, and to see if we could get the ground floor (assuming of course that's what we want).

Meanwhile, anyone know the exact rent + service charge for 88 Church Street? And what does the service charge include - i.e. is there security and is there 24 hour access?

**Comment by johnmckerrell** [comment]
Francis is that for a specific number of sqft then? Any rent free period? What lease length?

Church Street should be 24 hour access (agent says "they'll give you as many fobs as you want" but obviously we might test that slightly). No security although there's a bank on the ground floor if that helps! Don't know what the service charge is, pretty sure it's less but we should know better when they send through sample contracts (although that's taking a little while now).

**Comment by frabcus** [comment]
@johnmckerrell 5 year lease. Don't think a rent free period, guess could ask!

Regarding workshop machinery - "The current planning consent granted is B1 (Office) use. We may require a change of use and a little additional information as we wouldn’t want it to detrimentally impact on the neighbouring occupiers (as I am sure you can appreciate)."

Is that typical?

Ground floor is currently available. 

They claim service charge is typical for buildings of this nature - new build has cheaper running costs he says, implying that makes up for it.

**Comment by mwnw00359** [comment]
27 Mathew Street,  too small?

[Uploading 160+2051 (1).pdf…]()

**Comment by johnmckerrell** [comment]
"VIBRANT CITY CENTRE LOCATION" sounds... interesting, but yeah probably a bit small as it's not much more (if any) than our current location.

**Comment by aubergine10** [comment]
IMO something to consider is the amenities in the immediate vicinity that will be of benefit to the people using the co-working / hotdesking... Shops, restaurants and stuff like that. In particular places where they can have lunch with prospective clients/suppliers, investors, etc.

I think DoES has missed a trick with the current location in not highlighting what's on first floor of Gostins Building and also the surrounding area. People who go there will know, but someone just browsing the internet looking for a space to work might not realise what's in the area.

At the organisers meeting on Thurs 20th April there was a lot of discussion about how we can get better at marketing, and I think proximity to amenities should be an important consideration. For example, imagine something like the aerial image of 90 Duke Street (in pdf linked above) as part of the DoES website and marketing materials.

> Random note: If a space includes parking spaces, those can sometimes be rented out = another source of income.
