### ISSUE TITLE
webpage has no link to the equipment wiki

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#346]
And this page even points to the wrong wiki:  
    https://doesliverpool.com/laser-cutting-workshop/

A link of "equipment we currently have" should link to: 
https://github.com/DoESLiverpool/wiki/wiki/Lots-of-Equipment

**Comment by amcewen** [comment]
I've given you a login on the website, so you can fix it if you get time before any of the rest of us :-)

**Comment by DefProc** [comment]
Added under the `Services` menu item
