### ISSUE TITLE
Kitchen doorbot is mostly unresponsive

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#347]
The kitchen doorbot hasn't really been responding to RFID cards for a day or so.  It will eventually work, but takes a lot of attempts - so is effectively useless.

We've tried a couple of reboots, to no avail.

The wiring to the RFID reader does look a bit frayed, but it's definitely getting power - the red "card detected" LED works fine, it just doesn't then detect anything.

**Comment by amcewen** [comment]
There was a UTF-8 problem (possibly just the presence of UTF-8) in Radames' name in config.yaml that was killing it whenever the script tried to start.

Have fixed that - just needs the lock reattaching (as that was removed as a temp workaround)

**Comment by amcewen** [comment]
Hmm, lock reattached but it's unresponsive to cards now :-/

**Comment by amcewen** [comment]
The wire to connect to the relay has fallen off the Pi, so it probably just needs reattaching.  I can't remember exactly which one it connects to, and am busy soldering to sort it out now, if @johnmckerrell can maybe fix?

**Comment by johnmckerrell** [comment]
Fixed by plugging the relay into GPIO 25 which is pin 22 on the Pi as can be seen on this image:

http://www.raspberry-pi-geek.com/var/rpi/storage/images/media/images/raspib-gpio/12356-1-eng-US/RasPiB-GPIO_lightbox.png
