### ISSUE TITLE
The junior hacksaw is broken

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#348]
The junior hacksaw hasn't got a blade in it, but more importantly, one end of the blade holders is bent such that it won't hold the blade. 

It'd be useful if whoever left it in that state had raised an issue about it here rather than leaving it in the saws drawer for whoever next wanted to use it to find it broken.  Ordering a new hacksaw isn't a big deal, but having to interrupt your work to head out and buy one (luckily the shops are open at the moment) is annoying.

**Comment by amcewen** [comment]
New junior hacksaw bought, and some extra blades.  All in the sawing drawer.

**Comment by goatchurchprime** [comment]
I feel I have to fess up to this one.  Sorry, Adrian.  I owe you one, so feel free to send me out to the shop next time you need an errand run of any kind.

**Comment by amcewen** [comment]
Hehe, thanks.  Just raise an issue about it next time :-)
