### ISSUE TITLE
Build a bigger wire-spool holder for the electronics workbench

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#35]
At present we have a nice single-spool holder on the electronics workbench.  It would be good if we had one which held a lot more spools of wire - maybe a top row of 4 or 5 spools of single-core wire, and a second row with another 4 or 5 spools of multi-strand wire.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by DoESsean** [comment]
Since the only interaction with this issue in forever was from Sean, and it wasn't responded to suggesting that it's not really an important issue anymore, I'm closing the issue.
