### ISSUE TITLE
Vinyl cutter not cutting (properly)

### ISSUE THREAD

**Issue by Kate2000** [DoESLiverpool/somebody-should#350]
Vinyl cutter was only just cutting through the vinyl at Maker Night.
Might need a new blade.

**Comment by cheapjack** [comment]
Ta @Kate2000 Someone is interested in using it next week so meant to look at this tonight. Not had time to change today so Ive taped a box of the 2 remaining spare blades directly to the right side of the cutter so they dont disappear and in case anyone in on Saturday :) and hope to look at it on Monday 3rd Oct if I can.

Meantime the manual is here which you must read if adjusting/refitting the blade
https://wiki.nottinghack.org.uk/wiki/File:CX-12-24_Use_manual_r5.pdf

And our guide for it is here but will check over that also :)
https://github.com/DoESLiverpool/wiki/wiki/RolandVinylCutter

**Comment by jackie1050** [comment]
Changed blade following instructions in manual - Saúl has cut out some stickers which have worked fine. Should we order more blades?
