### ISSUE TITLE
Lock up your bikes thefts have occurred here sign in the hall

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#351]

**Comment by stevesparrow** [comment]
Yeah, if we could do that for yesterday. :)

---

**Comment by goatchurchprime** [comment]
Or after the first theft last year.  

Maybe wallhookups at waist height would be less of a hassle than down by the ankles.

**Comment by stevesparrow** [comment]
I spoke to Patrick about this.  The wallhooks we have are movable, and so we agreed to move half of them much higher, for ease of use, especially with U-Locks.  I could move them all, but half seems like a good compromise.  I'll bring in a drill etc tomorrow.

**Comment by stevesparrow** [comment]
I never did put the signs up, but I moved the locks.

Closing this due to the move.

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
