### ISSUE TITLE
Review procedure for supporting/attending external events

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#352]
Given we only just managed a presence at Manchester MakeFest, we should see what we need to do to make it less stressful.

Might be helped if we get an events team as part of #244...

**Comment by johnmckerrell** [comment]
Suggestions:
 * Prepare a stock checklist
 * Create a new issue for any new event, assign to people involved, copy and paste checklist in.

**Comment by DefProc** [comment]
The current procedure (based on what I've been doing) is: 

 - [ ] 
 - [ ] 
 - [ ] 
 - [ ] 
 - [ ] 
 - [ ] 
 - [ ]

**Comment by DefProc** [comment]
Here's how I see it: 

 - [ ] Create an issue for applying to the event.
 - [ ] Apply the [Meetup: Events](https://github.com/DoESLiverpool/somebody-should/labels/Meetups%3A%20Events) Label.
 - [ ] Create a [Milestone](https://github.com/DoESLiverpool/somebody-should/milestones) if many tasks are required. 
 - [ ] Assign/choose/volunteer a champion to co-ordinate the event for DoES (it helps if they commit to going) — assign that person(s) to the event issue.

Using the main event issue as a progress tracker, the coördinator should: 

 - [ ] Apply for the event as applicable (ideally from a DoES email, but from the event champion if suitable).
 - [ ] Recruit attendees.
 - [ ] Collate the exhibition.
 - [ ] Recruit/organise transport (as appropriate).
 - [ ] Help attendees find hotels (if appropriate).
 - [ ] Create a packlist.
 - [ ] Reply to any H&S and risk assessment requirements.
 - [ ] Liaise with the event organisers regarding any drop-off and pick-up requirements.
 - [ ] Go to the event.
 - [ ] …
 - [ ] Come back
 - [ ] Unpack
 - [ ] Report any necessary information and close any issues for the event.

**Comment by johnmckerrell** [comment]
Have you copied the steps onto the wiki?

**Comment by DoESsean** [comment]
I have not. My assumption was that, since we've attended quite a few events since this issue was raised, the people that were running DoES' presence had them internalised.

Probably should do that, to be fair.
