### ISSUE TITLE
Get the free desks from Telecoms Cloud

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#354]
We've been offered some free desks by Telecoms Cloud, who are moving offices.  However, we'd need to let them know we want them ASAP and then have collected them by this Friday!

In the organisers meeting we reckoned the key issue is whether the desks can be dismantled (for transport and then storage when they get here).

If they can be dismantled, then we need to find people who can help with doing the dismantling, and someone who can provide some transport before Friday.

**Comment by ajlennon** [comment]
I can lend a hand

**Comment by johnmckerrell** [comment]
Matt reported that the desks can be dismantled.

**Comment by mwnw00359** [comment]
Hi everyone, desks are at Elevator Studios awaiting collection..you have till 21st Oct to collect, they are in an empty office, if someone can come and dismantle and take to the loading bay, I'm happy to transport door to door, PS do you want any chairs to go with these desks? I need to get rid of a load also...

**Comment by ajlennon** [comment]
Hey @mwnw00359 I'll pop along. Any thoughts on what I need to take the desks apart? Will a trusty philips suffice?

**Comment by mwnw00359** [comment]
hey @ajlennon yeah, I think the desks are allen keys by the sounds of it, best to bring a tool kit just in case..when do you want to come?

I'm there at 4pm today if anyone wants to have a look to see what is on offer, there is lots more furniture and office equipment going, all FOC...all going...going..gone! ;)

**Comment by ajlennon** [comment]
Can't do it today @mwnw00359. I'll have to bring the car in. Maybe tomorrow?

**Comment by mwnw00359** [comment]
Hey @johnmckerrell @ajlennon any chance you can sort the desks next week?  Quite a lot of the stuff has gone now, quicker than expected, and I could do with emptying the room next week, you guys can come anytime 9-530 next week as I can get someone to open up for you...

**Comment by ajlennon** [comment]
@mwnw00359 I'll pop in tomorrow

**Comment by ajlennon** [comment]
Thanks again for that @mwnw00359. I'll close this off now.
