### ISSUE TITLE
Commission new PC for Gerald

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#356]
@goatchurchprime has freed up a spare PC in sorting out the Arcitype mill (although he's going to double-check it is available for us to reuse, and that there's nothing important on the hard disk before we wipe it...)

It's faster than the one currently in use for Gerald, so we should replace the one in use for that.

Plus it'll let us install the fresh copy of Windows 7 that I bought for Gerald back in January, but hadn't got round to installing as it would mean taking Gerald out of action while we were getting things set up.  Once we locate the disc for that...

And it'll need Dropbox installing, plus Inkscape and the laser-cutter software (@cheapjack do you know where the install software for that is?)

**Comment by euanwithersby** [comment]
If the PC isn't available for reuse I have a quad core i5 unit with 6gb ram in a tower case available. Needs an HD and OS and hasn't run for a while.

**Comment by amcewen** [comment]
Even if it is available for reuse, the one you're offering is better spec than any of the current laser or vinyl cutter PCs, so I'm sure we could put it to good use.

**Comment by madjake45** [comment]
If you would like someone to transfer it over I'm free next week to pop in and do this?

**Comment by ajlennon** [comment]
@johnmckerrell  @DefProc do either of you have any idea where the Corel Draw X4 install DVDs are for a Sophia box? Thx

**Comment by johnmckerrell** [comment]
No, and can't really think of any obvious suggestions, cupboard in The Fridge perhaps but it could be in the locked cupboard.

**Comment by DefProc** [comment]
I'm not aware that we have install CDs for it. I'll see if I have access to
a copy to bring in.

**Comment by johnmckerrell** [comment]
Actually looking at various open tickets it seems like we haven't had much luck with getting a copy! We've generally just moved the hard drive from the existing machine.

**Comment by ajlennon** [comment]
Made some progress guys. I have installers for Corel Draw X4 and X5 now. I have X4 installed, activated and running OK. I don't have a serial for X5 although with X4 going this is perhaps a non-issue. There seems to be a suggestion there may be an account with Corel we could look at to dig out the X5 serial? Cheers.

**Comment by ajlennon** [comment]
With a bit of luck Sophia, Gerald and Roland (sic ?) are all up and running now as needed with Inkscape, DropBox, Corel X4 and LaserCut where applicable.

Sophia - the new box thanks to @euanwithersby 
Gerald - the Dell box that was driving Sophia
Roland - the cube that was driving Gerald

**Comment by ajlennon** [comment]
First pass at some notes: https://github.com/DoESLiverpool/wiki/wiki/PC-Systems

@amcewen is finding a place to store the installer files for future reference

**Comment by amcewen** [comment]
That's great @ajlennon!  (Both the work installing things and the making notes :-D).  I see you've already added the link to the installer files too.

Is the only outstanding point on this the Corel licence issues?  If so, I think we leave that running under issue #100 and can close this one... (I'll let you get the #weeknotes credit ;-)

**Comment by ajlennon** [comment]
Yes indeed @amcewen Closing up... :)
