### ISSUE TITLE
Consolidate all the laser cutting pages

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#357]
They're sitting on the wordpress, the wiki and booking.  Needs to be all deduplicated and trimmed down

**Comment by huffeec** [comment]
I've made a start on this. I've added https://github.com/DoESLiverpool/wiki/wiki/LaserCutting as a landing page with the general info from https://doesliverpool.com/laser-cutting-workshop/
and moved the info about materials suppliers from LaserCutterSophia to a new page LaserMaterials referenced by both cutter's pages.

On the website https://doesliverpool.com/calendar/ has a link to https://doesliverpool.com/calendar/laser-cutter-calendar/ This page only shows the calendar for Sophia. Can someone with access to edit the website add Gerald's calendar too, or remove the page altogether, I've added links to both calendars to the LaserCutting page on the wiki.

**Comment by johnmckerrell** [comment]
The Laser Cutting Workshop had the right laser calendar embed so I've updated the link on /calendar/ and edited the /laser-cutter-calendar/ page to just say "Moved"

**Comment by goatchurchprime** [comment]
This looks pretty done.  And I've deleted the out-of-date pages for laser cutters off the old wordpress site

**Comment by DefProc** [comment]
Ah, this is the cause of #459
