### ISSUE TITLE
Get a better computer for the vinyl cutter

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#358]
The laptop for the vinyl cutter is on its last legs.  It would be good to replace it with something better.  @cheapjack is there any reason why we can't upgrade it?

**Comment by cheapjack** [comment]
The only reason could be finding correct drivers for the cutter for whatever replacement OS we get: it's an old machine that I've never had drivers or manual for. I've only ever tried to use it on my mac unsuccessfully: needs further investigation. @jackie1050 and I are investigating a sizing issue on it later at maker night so will have a look at that to of we can.

**Comment by huffeec** [comment]
I've started setting up the IBM machine for this.
It's got Inkscape installed now, and the appropriate driver from here.
http://support.rolanddga.com/_layouts/rolanddga/productdetail.aspx?pm=cx-24

**Comment by ajlennon** [comment]
The cube that was driving Gerald is now ready for some testing against the vinyl cutter. It has the printer driver installed and the printer is shared. My hope and expectation is the cutter can be driven locally from Inkscape or (e.g.) a network connectsd laptop (ref #356)

**Comment by DoESsean** [comment]
@huffeec or @ajlennon did either of the above options bear fruit?

**Comment by johnmckerrell** [comment]
Going to close this as the machine we have now is certainly better than the laptop we had previously.
