### ISSUE TITLE
Get a acrylic strip heater

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#359]
Copying this pledge out of the old page

A strip heater, to let us bend acrylic (and similar thermoplastics) into more interesting shapes.  Should complement the laser-cutter nicely.

Not sure if we could get one second-hand, but http://www.ebay.co.uk/itm/Hotline-Minor-Acrylic-Sheet-Bender-Strip-Heater-/261298129632?pt=LH_DefaultDomain_3&hash=item3cd6950ae0 is for a brand-new one

**Expected cost:** £460

| Who | How much? | Paid? | Comments |
| --- | --- | --- | --- |
| AdrianMcEwan | £40 | No |  |

**Comment by jackie1050** [comment]
We now have a strip heater
