### ISSUE TITLE
Get some diamond needle files for the workshop

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#361]
@jackie1050 knows of a good set to get.

**Comment by jackie1050** [comment]
Maybe not - Looks like my brother, who recommended paying at least £30 for a set, paid a lot more for these: https://www.cromwell.co.uk/shop/abrasives/diamond-files/16cm-diamond-file-set-120-140-grain-6pce/p/KEN0330500K
They were very good for smoothing 3D prints, but may be over the top for this - do we need to file harder materials such as glass and hardened steel?

**Comment by amcewen** [comment]
Yeah, most of the time probably not - I expect it'd be wood, 3d prints, and acrylic they'd be used on mostly.  There is this set on that site too https://www.cromwell.co.uk/shop/abrasives/needle-files/16cm-cut-2-assorted-needle-file-set-6/p/SEN0316980K and that's only £15, on sale from £30...  Maybe get that one?

**Comment by jackie1050** [comment]
Sounds good

**Comment by DoESsean** [comment]
I've ordered these from Cromwell, should be here in the next couple of days.

**Comment by amcewen** [comment]
They've arrived, and are in the filing drawer in the workshop.
