### ISSUE TITLE
The blue network switch in the main room has stopped working

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#363]
It just seems to have stopped powering up, so we'll likely need to order a replacement. 

I've replaced some of the connections with a 5 port switch so we do have *some* of the wired network on-line, but some ethernet devices may still be offline at the moment.

**Comment by DefProc** [comment]
Replaced with the spare "events switch" (the 10 port one from the maker faire box). But we should look to replace the switch with something permanent (or replace the events ethernet switch…)

**Comment by johnmckerrell** [comment]
@mwnw00359 had some spare networking gear from the office move, dunno if that's still the case

**Comment by mwnw00359** [comment]
Yes I do, but unfortunately, someone came yesterday and took a load of it, what is left is a 10/100MB Hub, 24port I think (Layer 2), plus some smaller older ones of the same, nothing 1GB, although if you can wait, I may have a 1GB HP Switch coming off production in London soon, it's due to be replaced only due to it's age, but it works fine I'm told...what size are you looking for first, i.e number of copper/fibre ports and what speeds etc? and do you need Layer 2 or Layer 3 devices...

**Comment by DefProc** [comment]
Hmm, I'm not sure if fully understand the "layer" options. But if we were going to buy a replacement for the one that died, I'd tend towards something like this: [TP-LINK TL-SG1024](https://duckduckgo.com/?q=TP-LINK+TL-SG1024&ia=products). This is just based on mounting, number of ports, fanless and gigabit (because why go slower if you're already paying for new equipment).

**Comment by mwnw00359** [comment]
Hey @DefProc some info here on Layers http://www.itpro.co.uk/88699/layer-2-and-layer-3-switches I do have a used hub, see below....would this be of help to save you guys buying one?
![img_20161020_092812](https://cloud.githubusercontent.com/assets/20774743/19552772/34e39070-96a9-11e6-949d-4521f66ff45a.jpg)

**Comment by mwnw00359** [comment]
If you guys are going to buy something, depending on what it is for, I would consider either this for the smaller version of this Netgear managed switch, meaning you can manage it, and provide POE power to devices along the network and dump all the power supply's everywhere...I have two of these, both interconnected via fibre and they handle a lot of traffic...

http://www.broadbandbuyer.co.uk/products/16680-netgear-gs728tp-100eus/

**Comment by DefProc** [comment]
@mwnw00359 yes, if that would work for us living as a switch behind the main router, then DoES would probably like to have that hub. And if it's fanless.
