### ISSUE TITLE
Buy some heat shrink tubing for the workshop

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#365]
Which is the best sort for general use?

**Comment by DefProc** [comment]
The last lot I got was to shrink down to 1 or 1.5mm. That might be around 2-3mm original diameter. But if its for general workshop use, a few different diameters might be useful.

**Comment by ajlennon** [comment]
I've got a bag of tubing here in my magic box if anybody wants it

**Comment by ajlennon** [comment]
@jackie1050 I've put a bag in the electronics components draw in the workshop for you :) Closing this for now
