### ISSUE TITLE
Demo prosthetic hand needs a few replacement parts

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#367]
The blue and yellow eNable prosthetic hand is missing a tensioner pin and a wrist pin cap.

It's the trite-keeps hand from https://github.com/cheapjack/buildyourown/tree/master/cad/hands/trite-keeps

**Comment by amcewen** [comment]
I've printed the parts and fitted the wrist pin cap.  The tensioner pin still needs fitting.

**Comment by DoESsean** [comment]
Did the tensioner pin get fitted? Can this now be closed?

**Comment by amcewen** [comment]
Given that FACT never got round to returning our demo hand, we should find out which parts are missing from one of the other hands in the Desktop Prosthetics box, print them off and then assemble a hand to keep on the "bookcase of things" just inside the main door.

**Comment by N-Sinnott** [comment]
After much faffing, I've successfully reassembled one of the prosthetic hands. It lacks a strap, but that doesn't really matter as it is now just a display piece. Its home is now next to Bubbilino.
