### ISSUE TITLE
Fix the tall heat press

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#368]
We've been given two heat presses but neither of them work.  One to fix and keep, one to fix and return.

This issue is to track the problems and fixes for the taller of the two.

It would be really good if we could get at least one of them working before Sat 29th Oct 2016 so it can be used at the Make:Shift:Do open day.

**Comment by amcewen** [comment]
From an initial inspection at makernight, one of the live wires to the heating element is almost broken (and possibly only connected by insulation rather than any copper).  So replacing that would be a good first step.  I've brought in some heavy-duty 3-core cable that I had at home which we can use to rewire things.

**Comment by Thingomy** [comment]
Flex from relay to heating element has been replaced. 

Cable routing to avoid any cables being chewed through by the mechanism again is still required.

Heat shrink/insulation on ends of heating element still needs some attention.

**Comment by DefProc** [comment]
I've placed the heat press in the location where the vacuum former was (as that is still out of action, with no upcoming fix date, and the table is ideal), @Red-Violet has marked the area, so there's a clear area to work in. It just needs "caution: hot" signs installing.
