### ISSUE TITLE
Fix the shorter heat press

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#369]
We've been given two heat presses but neither of them work.  One to fix and keep, one to fix and return.

This issue is to track the problems and fixes for the shorter of the two.  Fixing the taller one is being tracked in issue #368.

It would be really good if we could get at least one of them working before Sat 29th Oct 2016 so it can be used at the Make:Shift:Do open day.

**Comment by paulgeering** [comment]
**PART REQUIRED**
Inspection and testing has shown this to be a failed relay.

Relay part number:
JQX-105F-4 **012D-1HS** ([Datasheet](http://www.hawco.co.uk/en/media/bluelogic/legacyproducts_uploadfiles/h/f/hf105f-4_en_1.pdf))

Current Rating: 30A
Coil Voltage: 12vdc
Coil Terminal Width:2.8mm
Contact Arrangement: 1Form A
Construction: Plastic Sealed



Steps During Testing:
0. Noted that Temperature readout showing room temp.
1. Check resistance of element - OK
2. Check output of controller at relay - OK 
(12vdc present when controller trying to heat the press)
3. Bridge output terminals of relay - OK
(Element began heating press, Thermocouple reporting temp to controller, Temp readout seems sensible)

**Comment by amcewen** [comment]
I've ordered one from RS (http://uk.rs-online.com/web/p/non-latching-relays/1218070/).  I expect it'll be here on Monday.

**Comment by amcewen** [comment]
The part arrived today, and is tucked into the handle of the heat press (in a white paper bag) ready for fitting.

**Comment by paulgeering** [comment]
New relay fitted and press run up to operating temp.
