### ISSUE TITLE
Sort out power surge issue on Reprap.

### ISSUE THREAD

**Issue by Thingomy** [DoESLiverpool/somebody-should#37]
Occasionally when devices nearby are turned on or off, power issues cause the RepRap to freeze, killing the print. I believe I've seen it happen 3 times.

It's highly intermittent, so gathering more information would be difficult, a few ideas are given below though:
1. replace the PSU with another one -- anyone know the voltage requirements?
2. add a mains surge guard (though I'm not convinced those actually do anything)
3. attach oscope to PSU output and try to make it occur, to work out what's going on.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
