### ISSUE TITLE
Order vinyl roll from MDP for Make:Shift:Do

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#371]
We should order vinyl for the TShirt making asap. [MDP](http://www.mdpsupplies.co.uk/categories/clothing-vinyl.asp) is best supplier I think; they also do t-shirts and actual clothing vinyl which I think is what we need? @jackie1050 @huffeec 

Im not in DoES tomorrow, but prob best to order it tomorrow latest really if depending on post, failing that I could drive over and pickup Thursday if we need to ask their advice? Maybe we dont need actual clothing vinyl like [hot-flex](http://www.mdpsupplies.co.uk/hotflex.asp) and heat press if we are making stencils with normal sign making vinyl and painting on top? Im a bit mixed up with how we are making the tshirts with hot press or without to be honest!

**Comment by huffeec** [comment]
@jackie1050 and Kate are arranging the MDP order.

I think plan A is hot-flex vinyl and a heat press, with normal vinyl/mylar stencils as plan B.
It depends if #368 or #369 are complete in time. (There is also an outside chance we could borrow a press from http://thenerdygiftcompany.co.uk/ if we get really stuck and I can work out how to get it back to them first thing Monday morning.)

**Comment by jackie1050** [comment]
We have (a quantity of?) Mylar sheets and some fabric spray paint from last year – the Mylar sheets are in my drawer and the paint is in the solvent cupboard, if anyone wants to try it out before Saturday. There seems to be plenty of standard vinyl too.

**Comment by Kate2000** [comment]
We have budget for 16 t-shirts and 4 or 5 m of vinyl depending on which type we get.
Would be good to get some normal (not garment) vinyl too but we've got £62 I think.

The plan is to go and get it from MDP tomorrow.  
Currently we're getting black, purple and 3 other colours.  Any preference?
I can probably pick up some extra Ts as well but the budget is tight.

**Comment by huffeec** [comment]
We have bought a selection of t-shirts and vinyl now so closing this.
