### ISSUE TITLE
change the batteries in the kitchen bin

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#372]
[insert sarcastic comment about #hackspaceProblems here]

**Comment by DoESsean** [comment]
Done.

**Comment by DefProc** [comment]
And it looks like it's time again. The bin has stopped opening fully. It's either low batteries, or it's just feeling really lazy this morning!

**Comment by aubergine10** [comment]
Batteries looked fine when I used bin last Thursday.

**Comment by johnmckerrell** [comment]
For the (incredibly important) hysterical record, the batteries were changed on the same day this was last opened, I obviously forgot to close it.

**Comment by johnmckerrell** [comment]
I just had to change the batteries again having only changed them a week or two ago. Philips batteries - bad, Duracel Ultra hopefully good.
