### ISSUE TITLE
buy a small 19" rack for the main room

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#373]
The networking equipment _has_ been attached to the legs of the red Lack table in the main room where the modem plugs in, but that rackmount switch is now 2 units ago ( #363 ) and there's a growing pile of networking equipment and cable spaghetti in that area. 

As were _expecting_ to get some rackmount equipment (again from #363 ) I'm proposing we buy (or acquire) a small rackmount cabinet (aroun 12-15U high) that we can use in place of the red table, plus some rackmount, surge protected power strip. 

New, this equipment would be around £300.

This should replace the table that the printer is on (and still carry the printer), hold the cable router and allow some tidier (hidden mess) cable routing.

Any objections, questions or equipment offers?

**Comment by DoESsean** [comment]
I'm closing this as different solutions will likely be needed for the new space, and will be addressed then.
