### ISSUE TITLE
We need more glue sticks for the hot-glue guns

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#375]
The hot-glue guns are down to their last glue stick.  We need to get some more (mostly of the fat ones, although we seem to have a smaller hot-glue gun now, which also doesn't seem to have any glue sticks, so some thinner ones would also be handy)

**Comment by DoESsean** [comment]
Bought large and small. They're in the Glue Gun drawer.

**Comment by DoESsean** [comment]
From Clas Ohlsen.
