### ISSUE TITLE
buy some more filament for the Ultimakers

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#378]
There isn't much left at the moment.
Black is always useful. 
I was impressed with the results from "Space Marine" (blue metallic), and "Glacial Blue" is good if you need something translucent.
Colours here: http://www.faberdashery.co.uk/products-page/

**Comment by goatchurchprime** [comment]
Any updates about ordering should go here: https://github.com/DoESLiverpool/wiki/wiki/Ultimaker

(eg costs, where stocks are to be kept, what colours we like)

**Comment by goatchurchprime** [comment]
Some additional colours to get: Robot silver, Jade green, Squeeze orange, Storm grey, Firetruck red

(as well as space marine and glacial blue)

Some are slightly dearer than others, so we might want to mark the reels if you are making scrap -- as I am

**Comment by DoESsean** [comment]
I've ordered all the colours suggested. Will be delivered to me here in DoES, so feel free to open any PLA looking parcels that get here if you need them before I'm next in.

**Comment by goatchurchprime** [comment]
It's arrived
