### ISSUE TITLE
Kitchen cupboards need labelling

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#380]
We should label the kitchen cupboards & drawers to say where things are (or where they should be).

**Comment by stevesparrow** [comment]
We have a Label maker somewhere?  (Presumably in a well-labelled place!)

**Comment by johnmckerrell** [comment]
We have a hand held label maker in the stationary cupboard in Room 29 and a bigger one attached to the laser computer.

**Comment by aubergine10** [comment]
There are printed labels on cupboards so closing this issue.
