### ISSUE TITLE
Gerald's laser won't burn through masking tape

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#381]
Gerald has been cutting all day, but power tailed off markedly just now.  Doing some tests (after cleaning some of the mirrors, but not the lens) the laser is hardly marking some masking tape I put over the middle mirror.

Maybe time for a new tube?

**Comment by johnmckerrell** [comment]
I was trying to see how long it would be since we had a new tube (March) as listed in #266 but then that also describes a sudden loss of power followed by a potential fix so might be what's happened here too? That issue also mentions that the previous tube should be wrapped up somewhere in the workshop?

**Comment by amcewen** [comment]
Ah, I knew we still had a spare tube knocking around, but I'd thought it was the new one and not the old one.  If the tube in Gerald is only ~8 months old then maybe it's not the tube that needs replacing :-/

It's not the same problem we were seeing there - putting masking tape over the mirror it wouldn't burn through, so that's before it gets to the cone by the lens.  It could be that the first mirror is misaligned, but that's tricky to get to to test on Gerald.

(It's also possible that my initial troubleshooting has missed something else, but I won't have time to check till this evening or maybe only tomorrow)

**Comment by DefProc** [comment]
The laser is relatively wide before it goes through the lens, so I'd 
normally expect only a small mark on the masking tape. It's set for a 
short pulse, and I've been doing 3 pulses to get a mark when doing 
alignment.

As the tube is only 8 months old, poor alignment is the second most 
likely cause of a drop in power (after cleaning the mirrors and lenses).

**Comment by DefProc** [comment]
I've removed the broken label for now, as Gerald is currently functional. 

It could still be alignment. If the laser is striking the aluminium cone when exiting the head, instead of leaving cleanly, then it gradually heats it, expanding it and then occludes more of the beam. Leaving it turned off then allows it to cool, and the apparent power output increases.

**Comment by amcewen** [comment]
Have you tested it?  I haven't heard of anyone getting decent results with it today.  Adding the Broken tag back.  Tonight at #makernight Laura was trying it with card and it wasn't cutting through at all.

**Comment by huffeec** [comment]
Mohammed was using it in the afternoon and didn't get anything usefully
cut. Cuts weren't getting through 3mm acrylic and straight line etches came
out noticeably wiggly**

** I think that's the SI unit

**Comment by cheapjack** [comment]
It looks like it *may have* been a combination of alignment and power settings...
Alignment was generally ok (so if doing a few test pulses would look fine) but the second mirror (the one on the 'Y' axis at the left of gerald if facing the front) was 'loose' ie moving around inside the support thread, so I'd imagine a fast moving cut would make it jiggle around making the alignment vary wildly but inconsistently.

It looked like the mirror's rubber o-ring that holds it in place against the inner thread of the mirror support was not present; and the mirror was terribly dirty and marked. What I've done is replace the mirror with a spare (now back in an envelope in the organisers keys cupboard) which was in a much better state after cleaning it. I uses a slightly over-sized fresh clear rubber o-ring which held the replacement mirror in place against the mirror supports inner thread in a much more secure way. 

Once re-assembled the mirror did not shift and was held nice and tight in the mirror support. I've re-aligned it now (just the second mirror, did not have time to clean and re-align the other mirrors) and it successfully cut DoES stock 3mm Laser ply in the bottom left corner of the bed on settings `power 50` `corner power 45` `speed 10`

Then when I checked the last cut settings Alessandra had put it on `power 70` `speed 6` but had not noticed corner power was set to `5`. Dont know at what point (or how the machine calculates it) during a cut the corner power would begin to drop to reach the desired corner power but I guess this could have contributed to the loss of power.

So taking broken tag off and closing 👍
