### ISSUE TITLE
Strip-Light covers in Room 29

### ISSUE THREAD

**Issue by stevesparrow** [DoESLiverpool/somebody-should#382]
Hey,

The strip lights in Room 29 are a bit flickery for my eyes.  Sitting in there more or less full time, I'm noticing the effect.

I'd like to fit covers over the florescent fittings, and if no-one objects, a couple of daylight tubes for good measure, and to keep the same brightness (£5ea).  Total cost around  £25.  I'll sort this out in the next few days unless anyone has any other suggestions / comments.

Cheers
Steve

**Comment by johnmckerrell** [comment]
Are they LED tubes you’re looking at, just interested to see how good they are? I think we always had issues getting new tubes for that room as they’re different length to the main room but yes we should probably just replace ourselves, won’t cost that much. If we moan to reception they may even reimburse. Might be worth checking with Richard Foulkes what the correct lighting was for use with VDUs.

**Comment by stevesparrow** [comment]
The LED ones are a little more, but they did sound good.  I'll pop out the site and take a look.  I bought some new ones for an old office that were very good.  I'll see if I can dig out the link.

**Comment by stevesparrow** [comment]
I think I used TLC.

[Daylight Tube] [https://www.tlc-direct.co.uk/Products/LAFLT70DL.html?ad_position=1o1&source=adwords&ad_id=45425533757&placement=&kw=&network=g&matchtype=&ad_type=pla&product_id=LAFLT70DL&product_partition_id=174055563427&test=finalurl_v2&gclid=CjwKEAiAr4vBBRCG36e415-_l1wSJAAatjJZMBFYiWEKPDI8j6UG_i-cRSS8bP0Fe9faf_LMIv6s3RoCQU_w_wcB](url)

Diffuser: [https://www.tlc-direct.co.uk/Products/TNPPC26.html](url)

The LED ones cost a lot more at £28 each for 6 foot (I'll measure and check tomorrow.)
LED Tubes:  [https://www.tlc-direct.co.uk/Products/LAFLT70DL.html?ad_position=1o1&source=adwords&ad_id=45425533757&placement=&kw=&network=g&matchtype=&ad_type=pla&product_id=LAFLT70DL&product_partition_id=174055563427&test=finalurl_v2&gclid=CjwKEAiAr4vBBRCG36e415-_l1wSJAAatjJZMBFYiWEKPDI8j6UG_i-cRSS8bP0Fe9faf_LMIv6s3RoCQU_w_wcB](url)

I'm inclined to go for the standard florscent unless you think otherwise.
