### ISSUE TITLE
We should have a photography consent form template for events.

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#384]
Would've been handy for Make:Shift:Do.

**Comment by DoESsean** [comment]
I've put a form together, if anyone wants to make changes, please feel free.

It's in Dropbox in the DoES Admin folder as Promotional Permission (I can't see any way to attach a file to a Github issue, if anyone knows how to do so, then please let me know!)

**Comment by ajlennon** [comment]
@DoESsean does it need an option for parents to give consent for minors?

**Comment by stevesparrow** [comment]
Yes,.  I edited it a few weeks ago but must not have posted it.  I'll see if I can find it.  Normally they also specify possible useage, which I added.  Give me a day.

**Comment by DoESsean** [comment]
This form is stored in the DoES Dropbox (Drobox -> DoES -> Admin -> Logos, Flyers and Posters

I've changed it slightly so that it gives permissions for 'me and my family' for parents.
