### ISSUE TITLE
Unpack the DoES Tower for December

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#385]
As it makes a nice light up decoration, and the Cheertree is still out of action, we should:

 - [x] put the DoES Tower out somewhere for the Christmas period,
 - [x] change it to listen to cheerlights (or another compatible protocol)?
 - [x] step 3…
 - [x] profit
 - [x] check it has a RPi, 
 - [x] check the MQTT service is still running,

**Comment by amcewen** [comment]
Is there an issue for the Cheertree?  What's wrong with it?

**Comment by DefProc** [comment]
The wifi shield was not working when I plugged this in, looks like the onboard voltage regulator died (burned out). I've replaced this with one borrowed from @amcewen, although that may be where the original came from too.

**Comment by DefProc** [comment]
Installed in the main room
