### ISSUE TITLE
We should display the names of companies that are registered and resident at DoES

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#386]

**Comment by stevesparrow** [comment]
Do we have a list?

**Comment by DoESsean** [comment]
I don't think we have an actual list, but it would be very easy to pull one together.

**Comment by johnmckerrell** [comment]
Indeed, I guess the action would be deciding where to put it, as this is supposed to be something we should make public I’d guess a wiki page would be a good, perhaps separating them into “These companies have registered addresses here” with “these companies are just resident here” (although maybe not bother separating that out as I think without looking on companies house we don’t actually know!)

**Comment by DefProc** [comment]
How about: registered companies go on a website page (we add them) and associated companies go on a wiki page (they add them)

**Comment by stevesparrow** [comment]
That sounds good....

---

**Comment by johnmckerrell** [comment]
TBH that sounds like too much work to me, could just use the wiki and keep an eye that no one is sneaking anything on. 

--

**Comment by goatchurchprime** [comment]
I've started a table that links from the membership and access page.  I'll put the note out for people to fill stuff in.

https://github.com/DoESLiverpool/wiki/wiki/partial-list-of-members

**Comment by ajlennon** [comment]
Can we have a column for a corporate logo?
