### ISSUE TITLE
Advertise that DoES offers mailboxes

### ISSUE THREAD

**Issue by paulfurley** [DoESLiverpool/somebody-should#39]
I happened to see this mentioned on the mailing list, but I didn't know about it otherwise. It's really useful for lots of reasons, and a good price. I imagine it's quite cheap to run too, so scalable. Let's capitalize.

The keywords I've found when looking around include:
- business address
- postal address
- mailbox
- forwarding address (even if they don't actually forward!)

**Comment by DefProc** [comment]
It might be worth changing the address on that page; someone did send us post to "Awesome Sauce c/o DoES Liverpool" instead of "DoES Liverpool CIC"!

**Comment by DoESsean** [comment]
I've changed it to 'Your Company Name Goes Here.' That should hopefully make it a little clearer!

**Comment by johnmckerrell** [comment]
Closing this issue as the problem is solved and any redesign will simply need to catch everything on the existing site

**Comment by DefProc** [comment]
And it's on https://doesliverpool.com/services/ #460
