### ISSUE TITLE
Roll the PLA filament that's arrived issue #378 onto reels

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#390]
Some of it has diameter 2.85mm and some 3mm.  Is this right?  (If so, please note this at bottom of https://github.com/DoESLiverpool/wiki/wiki/Ultimaker )

All of it comes in bags without the reels, so do we need to wind them on ourselves so they don't flop out all over the place and get spaghettified  when we try to use them?

**Comment by goatchurchprime** [comment]
There are at least 6 more coils to roll up before use.  I've put instructions here
    https://github.com/DoESLiverpool/wiki/wiki/Ultimaker#getting-more-filament

**Comment by DefProc** [comment]
@goatchurchprime Yes, rolling on to reels is better for having good feed into the ultimakers.

**Comment by amcewen** [comment]
I think pretty much all of the filament for the printers is on reels now (or rolled up when it's needed).

For general info, I've started buying my filament from http://http://shop.3dfilaprint.com/ again (we used to use them lots for the 1.75mm for the UPs) as they've started stocking 2.85mm and theirs comes on reels.
