### ISSUE TITLE
Wall mount our 3D printing filament stocks and samples

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#391]
There's a very boring white wall above the ultimakers.  It would look great if we decorated it with our stocks of colourful filament by screwing on shelf-brackets and hanging the spare reels over them.  

Separate the expensive from the cheap colours on the shelves so folks know which to use for test parts. 

We could also be a place to exhibit colour and speed test samples.  Maybe a test part of an Xmas tree or reindeer horns showing what it looks like when the element is too hot/cold fast/slow thin/thick etc and so you can diagnose what the issue is.

Is there a nice looking poster about print failure conditions we can put up on the wall, akin to the Bristol Poo Chart?  https://en.wikipedia.org/wiki/Bristol_stool_scale

**Comment by DefProc** [comment]
I'd suggest extending this to actual shelves, then reels can be stored end-on, so users can see the colour of the filament. #392

**Comment by aubergine10** [comment]
Here's another way to store spools: [3D printable wall-mounted spool holders](http://www.thingiverse.com/thing:2119644). They need a few nuts, bolts, etc. (details on that thingverse page) and it might be worth printing them out of clear plastic so people can see what's in them and how much is left, etc. Could potentially adapt the design to allow a small sensor to be embedded within them to monitor a) how much spool is removed and b) warn when spool is running low.

![1ba6a34f833c2d95a72a43bcbe517ff1_preview_featured](https://cloud.githubusercontent.com/assets/1386719/26028181/e93e4d70-3812-11e7-8966-dedacd27125d.jpg)

**Comment by aubergine10** [comment]
[3D printable spool rack](http://www.thingiverse.com/thing:111172):

![photo_jun_30_7_02_22_pm_preview_featured](https://cloud.githubusercontent.com/assets/1386719/26028784/225fef76-381f-11e7-9a43-5f5c75d5be31.jpg)

**Comment by DoESsean** [comment]
These are both properly nice solutions.
