### ISSUE TITLE
Sophia not cutting well

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#395]
Sophie isn't cutting well, we've had a few recent reports of people trying to cut through thin wood or cardboard and it either won't cut through or thoroughly chars.

I was hoping to cut something myself from 3mm ply so if I get chance to do that I'll report back how it goes.

**Comment by johnmckerrell** [comment]
I cut something on 7/50/45 with 3mm ply, it managed to cut maybe 50% of the cuts, not a great experience but then just about usable, quite charred though.

I forgot to report earlier I took out and cleaned the mirror and lens from the head (to no avail).

**Comment by stevesparrow** [comment]
Kirsty cut today with no issues at all.  Did this get fixed by someone?

**Comment by Thingomy** [comment]
I did some work on Sophia on the evening of the report, and she was as happy as I have ever seen her, no issues at all. Job wasn't too intense though, could it have been overheating?

3mm ply 12/50 cut was perfect (perimeter 200*250ish rectangle)
250/13 kiss cut was the sharpest only-just-etched line i've seen her do, and was very consistent across a moderaly long job, though duty cycle was low with many short lines and moves between.

**Comment by amcewen** [comment]
Given that no-one has complained about this of late, despite plenty of use in the run up to Christmas, I'm assuming we can close it?
