### ISSUE TITLE
Doorbot isn't working - Main room

### ISSUE THREAD

**Issue by stevesparrow** [DoESLiverpool/somebody-should#396]
It stopped working as John left, and fixed on reboot.

It locked me out a little later though, and a reboot hasn't fixed it.  Shows the red light but does nothing.  

Key is in the keysafe.  I should be first in tomorrow, at 8:30, but if anyone's early they'll just have to wait!

Leaving this here so someone might fix it!

**Comment by johnmckerrell** [comment]
Try rebooting it again when you can get to it, the relevant script is sometimes not starting, but sometimes is. There’s a chance someone will be able to start the script remotely though.

**Comment by stevesparrow** [comment]
Great, I'll try again first thing.  Thanks.

**Comment by amcewen** [comment]
Script seems to be running at the moment, and did scan a card (the red kitchen pass) at 8pm - though hadn't scanned any since 5:35 before then.

**Comment by stevesparrow** [comment]
Worked this morning, and all day...
