### ISSUE TITLE
Review material charging for Vinyl cutter. What about 3D printers?

### ISSUE THREAD

**Issue by stevesparrow** [DoESLiverpool/somebody-should#398]
Hey,

From a conversation with Adrian yesterday.  Now that the Vinyl cutter is being used more, it would be good to supply well for it.  All of the vinyl we have for the vinyl cutter are scraps left over (I think) from when Ros bought it to DoES.  It would be nice to buy some more rolls for it in various colours. so that people can use it more and have a good choice, without having to buy 5 metre rolls themselves.  Unlike the Laser cutter materials, we don't have a good way of recouping the cost though.

We also don't do this for the 3D printer either , and so I wonder if it's worth adding that to the same principle as the Laser cutter?  It may be a different user case.

Vinyl - roughly by the metre or half meter for rolls used (standard and speciality rolls) - just recouping the cost.  Simple note on the wall and the same honesty pot as the laser.  I think £2 a metre, £1 a half metre but I'll check.

3D printer, either by the length used (is that feasable), or roughly by weight?  Is there another better way?  Is it worth doing for these?

Thoughts?

Thanks
Steve

**Comment by johnmckerrell** [comment]
Sounds reasonable, pricing per metre of vinyl seems like it would work, label the old box as “Free Offcuts” (if Ross is ok with that).

Not so sure how we handle 3D printing, actually if we just put a little £10 digital kitchen scale next to the 3D printers doing it by weight would probably be fine.

**Comment by stevesparrow** [comment]
I spoke to some people and did some maths.  I suggest.

**Vinyl Cutter**

Exactly the same as the laser...
1) All the current material that shouldn't be thrown out is labeled as offcuts, and is stored somewhere, and is free.
2) We buy a bunch of new regular gloss and matt vinyl, and charge £1.80 a metre for regular vinyl, or £90p a half metre.  Delivery is expensive, and so this allows for us normally buying 2 at a time with delivery.
3) Specialty vinyl (clothing, reflective, florescent etc, if we have it) £3.50 a half metre.
4) Simple note on the cutter/holders giving prices, the same as the laser cutter.

**3D printer**

The same as now, but easier to know how to contribute
The 3D printer is much cheaper to run for smaller prints, because it uses a precise amount of material.  A very small print (1m of printed filament) might only cost 16p, but a larger one could easily be £2, putting it in the same field as the laser vinyl cutter materials.

It would be weird though to ask people to pay 16 pence for something, so I suggest we simply do what we do already, but make it easier to know how much you've used and contribute. We'll pop a cheap mini-scales next to the 3D printers, with a note giving the price by weight, and asking people to contribute.  The same as we have now, simply adding a sense of scale. ;)

Talking with various people at makernight and in the office, this seems a fair reflection of feeling.  Any comments?

(On Haberdashery, 100 metres (pre-print), or 840g of regular filament costs £28.  Dividing the delivery by two lots of filament, it means that basic filament costs £3.57 per KG delivered, or £3.60 per 100 gram.)

**Comment by johnmckerrell** [comment]
I was going to say you could check prices for laser materials to see how much "profit" to make but it wouldn't be a bad idea to confirm the prices are still good to cover costs. 

--
