### ISSUE TITLE
Replace bent rod on the Ultimaker 2 extended

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#399]
There's also a grinding noise in the back left corner (not the filament, must be the motor) when it is working, that may have something to do with it.  

I'm going to take it out and reseat it to see if it sounds any different.

**Comment by goatchurchprime** [comment]
The back cross shaft is bent and causing resistance in certain places.  You can see this by pushing it forward and back when the machine is off.  This is almost certainly causing the tolerance issue. 

I'd recommend a full stripdown of all those poles to see if any others are bent before making an order.  It probably happened when applying huge forces to get the filament to run through when it didn't want to go.

**Comment by DoESsean** [comment]
Has there been any movement on this issue? I've not heard of their being any problems with the printer, and it seems to have been working fine for the prints I've seen, so has it been sorted?
