### ISSUE TITLE
There isn't a DoES logo on the reception sign board

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#40]
There's space on the sign board in reception to add our logo, so "Somebody should: cut a vinyl DoES logo and add it to the board"

The available area on 4th Floor section is 101cm high × 110cm wide, though we should probably leave room for someone else in there too…

**Comment by amcewen** [comment]
Right, making a start on the business names on the 4th floor to put on the board...

Future Concessions (Room 12)
DoES Liverpool
Kreative Kaos
Byzantine Atelier (Stefan)

**Comment by amcewen** [comment]
There's also HOTA (Health On The Agenda), which is the woman in the boiler room who runs courses for the WEA.

**Comment by amcewen** [comment]
Reassigning it to @DoESsean so he can complete the list of companies (and then give it back to @Thingomy to cut stuff :-)

**Comment by DoESsean** [comment]
No-one else seemed to join in with this, and, given the likelihood of us leaving relatively soon, it seems daft to get everyone's name for the boards now.

Since the initial issue - to get a DoES logo on the reception board - has been completed, I'll mark this as closed.
