### ISSUE TITLE
print name labels for "Prints Adam" and "Felicity"

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#400]
We need to vinyl cut labels for the Ultimakers' names

**Comment by aubergine10** [comment]
I'm currently updating info about the various tools (see #488 ):

* Were the labels ever printed (I didn't notice any on the machines)?
* Which machine is Adam?
* Which machine is Felicity?

**Comment by DoESsean** [comment]
Labels weren't ever actually printed, as it was assigned to me and I have
no idea how the Vinyl Cutter worked. Funnily enough, it was something I
asked Steve about last week.

I don't know which was which though.

**Comment by aubergine10** [comment]
@amcewen Can you remember which name refers to which machine?

**Comment by johnmckerrell** [comment]
I suspect it won't matter until you put the stickers on. 

--

**Comment by aubergine10** [comment]
Well, let's call the U2 Extended "Adam" and the smaller U2 "Felicity". Ok?

I want to get the labels and wiki pages completed for these printers as - as far as I know - they are the only generally operable 3D printers in the workshop.

**Comment by huffeec** [comment]
This is done, and I've updated the wiki page to "Prints Adam"
