### ISSUE TITLE
Gerald needs aligning

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#402]
I've just taken the air-assist cone off Gerald in order to get any output (well, on speed 7, power 70 you could just about make a mark on some paper...) from him.

So the alignment isn't too bad up to the final mirror, but hits the air assist nozzle when that's fitted.  Obviously we need to refit the air assist nozzle and align things properly.

**Comment by cheapjack** [comment]
I've taken apart the lens inside the air-assist cone and cleaned it : the 'inner' side of the lens had a big build up of particulates. I've re-aligned the 2nd Mirror and the final mirror (and cleaned the final mirror) and made sure it cuts as expected at power 60 speed 10. Ikram was having issues with it today but seems ok now so I'll close this :)
