### ISSUE TITLE
Make it even more obvious somewhere that you can't book lasers more than one day at a time

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#403]

**Comment by DefProc** [comment]
Are there any suggestions on a good place to do this? 

It currently forms part of the induction, is listed on the website page about laser cutting, is on the booking form, and on the few occasions that someone does multi-book, I explain in the cancellation why it's not allowed. 

The ideal situation would be to disallow it programmatically as part of the booking process, but I'm not aware that youcanbook.me has the option.

**Comment by cheapjack** [comment]
Yes you can book me doesn't seem to do it. Only came from someone insisting that they didn't know but it does say clearly on website. You can't make all the people read properly all the time I guess. MAYBE BIG SHOUTY LETTERS YOU CAN ONLY BOOK ONE DAY AT A TIME

**Comment by goatchurchprime** [comment]
Done https://github.com/DoESLiverpool/wiki/wiki/LaserCutting#booking and made quicklinks to the relevant calendars from the individual laser cutter pages
