### ISSUE TITLE
Make some tree decorations for in DoES

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#404]
DoES now has a Christmas tree this year. @Red-Violet will be putting the tree up on Monday (12th December) in good time for the Christmas Party (17th December).

However, because we haven't had a tree before, we're a little short of Maker decorations. There's still a Maker Night before Monday, so we should try to make (3D print / laser cut) some tree type, hanging  decorations. Or bring in any that you might have made in a previous year. 

Somewhat related to #385 and #389

**Comment by shrkey** [comment]
There were, I think, some off-cut acrylic circles in my box in the workshop that may be of use for engraving, hole cutting and hanging on the tree.

If they are still in there (can't remember if I did a clear out a while ago or not) and you think they'd be of use then then feel free to grab them and use them for whatever you want.

**Comment by jackie1050** [comment]
I've got some acrylic sheet - blue and orange though - I'll bring it in for tomorrow's maker day (10 Dec) if anyone would like to use that
