### ISSUE TITLE
Upgrade the toaster

### ISSUE THREAD

**Issue by stevesparrow** [DoESLiverpool/somebody-should#405]
In the spirit of being more githubbable, a heads up that I'd like to upgrade the toaster, for one which is a little more lunchalicious, as it also boils eggs.  

Does anyone have any objections?  While it looks a little gimmicky, I've used it and it works very well, and it's easy to keep clean.

[Toaster](https://www.amazon.co.uk/gp/aw/d/B0013KEDKY/ref=mp_s_a_1_1?ie=UTF8&qid=1481667482&sr=8-1&pi=SY200_QL40&keywords=tefal+toast+eggs&dpPl=1&dpID=41T5iussVXL&ref=plSrch)

The current one does have a croissant warmer, which I know Adrian once used.  :). If needed we could rig one up, we're good at that.

Shout if you have any objections, or want to suggest an even more singing dancing option. I've heard some cook a full breakfast and deliver it by drone.

**Comment by ajlennon** [comment]
Perhaps this

[Toaster](https://www.ted.com/talks/thomas_thwaites_how_i_built_a_toaster_from_scratch)

**Comment by stevesparrow** [comment]
Love that...
