### ISSUE TITLE
The Ultimaker 2 is missing a bowden tube clip and a screw

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#406]
During reassembly in #393 I noticed that we're missing the little blue clip to keep the bowden tube properly seated in the extruder, and are also missing one of the small hex-head screws to hold the fans onto the extruder.

It seems to be running okay without either, but it'd be good to get replacements.

**Comment by DoESsean** [comment]
If you can find the particular pieces we need, I'll be happy to order them,
unless you want to do it.
