### ISSUE TITLE
Someone has dropped an E in the main room

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#407]
The E from the large black-painted laser-cut DoES over the whiteboard in the main room has come loose.  It needs reattaching to the pipe.

**Comment by johnmckerrell** [comment]
We also have a problem with "pee" around the DoES Tower

**Comment by stevesparrow** [comment]
Pretty sure they are all held up with glue-gun glue. Nice big blob, then onto the pipe.

**Comment by johnmckerrell** [comment]
Added a bit of wood for stability, now glued back up.
