### ISSUE TITLE
We should (should we?) get a wheelie bin

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#408]
I've been thinking we should get a wheelie bin for taking bin bags down to the main bins (and potentially storing them short-term). They're actually not so expensive as I thought and you can get them on eBay:

http://www.ebay.co.uk/itm/Wheelie-Bin-240-Litre-Standard-Household-Council-Bin-240L-Green-colour-logo-/182268023344?hash=item2a70055230:g:RCYAAOSwxg5XzHnz

http://www.ebay.co.uk/itm/240L-Grey-Wheelie-Bin-Council-Approved-EN840-CK9200-/152309199741?hash=item237655f37d:g:zSMAAOSwXeJYGdzu

Might be worth paying the extra £1 not to have a logo on it (and grey probably better colour than green for refuse).

**Comment by stevesparrow** [comment]
Sounds like a great plan, and a much better look than the bags hanging around.

**Comment by johnmckerrell** [comment]
Ordered, I was thinking of waiting until after Christmas but then it'll be more useful to have it before the holiday as Tony the cleaner won't be around so much. Looks like it's "24 hour delivery" but should turn up Tuesday or Wednesday.

**Comment by DoESsean** [comment]
We have a wheelie bin now.

**Comment by johnmckerrell** [comment]
The wheelie bin was lost for the past two weeks but turns out it was hidden around a corner by the fire exit double doors, FYI.

**Comment by cheapjack** [comment]
Sorry that was me. Somebody complained at me 2 weeks back for the corridor being a 'mess' and seemed to object to bin where it was so I moved it by the old goods lift and brushed up then forgot to report here! She then started going on about everyone on 4th floor should club together to get carpet at which point I said we were unlikely to either want, need or pay for carpet and it didnt make sense to the majority of tenants on this floor anyway... and even less point if building being sold :) She was based in the office opposite workshop and it was first time Ive ever seen anyone in there!
