### ISSUE TITLE
Get a bottle opener

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#409]
Why do we not have a bottle opener? The Christmas party is a bust, how is this not available?!!!!!!!

**Comment by stevesparrow** [comment]
The number of exclamation marks make it sounds like you managed to find something to drink. ;)

I've ordered a waiters friend for £3.  Be there tomorrow, ready for the next Birthday party, or a quiet  afternoon before Christmas....

Why can't I close this?

**Comment by johnmckerrell** [comment]
Because the bottle opener has not yet turned up (if only GitHub was that clever).

**Comment by amcewen** [comment]
It's arrived and is in a (red) wine-coloured box in the cutlery drawer in the kitchen.
