### ISSUE TITLE
Commission the new acrylic bender

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#410]
So, we won the ebay bid for the [CR Clarke Model 500 acrylic bender](http://www.ebay.co.uk/itm/CR-Clarke-Model-500-strip-heater-for-plastic-etc-/232170177238?hash=item360e6bc2d6:g:yX0AAOSwB09YQIbd).  Yay!

We need to...
 * [x] Collect and pay for it
 * [ ] Name it
 * [x] Create a page for it on the wiki, explaining how to use it

**Comment by amcewen** [comment]
Assigning to @ajlennon initially as he's offered to collect it.

**Comment by amcewen** [comment]
It's now in the Workshop.  (The seller generously dropped it off for us).

**Comment by shrkey** [comment]
In the spirit of name requests - Bendy McPlastic or Bendy MuhPlastic?

**Comment by huffeec** [comment]
Has to be now doesn't it, who's going to want to settle for the Sir David Attenborough now..?
Bendy McBendface maybe..?

**Comment by DefProc** [comment]
Is there a Futurama reference? And we had been choosing female names to
improve the Dave-ratio-for-equipment.

Leela?

**Comment by drfraz** [comment]
How about Yazz if we want a female name? The only way is up!
Fraz

**Comment by DoESsean** [comment]
If it's going to be a female name, it has to be Coilette

[https://en.wikipedia.org/wiki/Bend_Her](url)

**Comment by jackie1050** [comment]
I've started a wiki page here: https://github.com/DoESLiverpool/wiki/wiki/StripHeater
There's a link to a manual and some initial notes, but needs further experimentation.
It would be useful to download the manual somewhere.

**Comment by jackie1050** [comment]
Copied the manual to the new somewhere-safe area

**Comment by jackie1050** [comment]
Wiki page exists and has been updated recently by Guy. There are still a couple of areas to fill in if anyone wants to take a look
