### ISSUE TITLE
Make an adjustable former for the acrylic bender

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#411]
so we can bend stuff to specific angles

**Comment by jackie1050** [comment]
CR Clarke (manufacturers of the strip heater) make an interesting folding jig (http://crclarke.co.uk/products/LB/FJ01.html)

**Comment by amcewen** [comment]
Ah, that looks totally like something we could make in-house.  My set of dies goes up to M12 if that's useful for putting threads onto some bar stock... mightn't need anything that thick I guess (the set has smaller than that too, obv.)  Then it'd be a case of some laser-cut plates and careful measurement, no?  Maybe a 3d printed knurled knob for the adjuster, if you want to pull in another tool... :-D

**Comment by DoESsean** [comment]
Is this still something we'd like/need, or has it slipped by the wayside?

**Comment by DoESsean** [comment]
Given that no-one responded 18 months ago, I'm assuming wayside.
