### ISSUE TITLE
Commission the hot-air gun

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#412]
Paul G has given us a hot air gun for Christmas!  Yay!

It's in its box on top of the reflow oven on the electronics workbench.  It needs...

 * [ ] Unpacking and setting up
 * [ ] Naming(?)
 * [ ] Adding to the wiki

**Comment by amcewen** [comment]
On the naming front, I'm wondering about Farage or Trump, as it'll generate lots of hot air...

**Comment by johnmckerrell** [comment]
Lol, but let's not. I guess at least Trump has multiple connotations.

**Comment by DefProc** [comment]
Best not, it only benefits them to talk about them!

How about a singer that's notable for their verbal capacity?

**Comment by huffeec** [comment]
Is 'Montgolfier the hot air gun' too much of a mouthful?

**Comment by drfraz** [comment]
It would get shortened to Monty which could work.

**Comment by paulgeering** [comment]
Agreed! 
I herby name the Hot Air Workstation "Monty".
Where possible the quotes should be included as part of the name. 
(Air quotes optional in spoken communication.)

If anyone asks which Montgolfier brother it is named for, the answer is Joseph-Michel.

**Comment by DoESsean** [comment]
'Monty' is in use and even has a wiki page, so this is being closed.
