### ISSUE TITLE
Investigate wifi versus wired throughput

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#413]
Has anybody else been seeing issues with wifi performance?

For the past 3-4+ weeks it seems I've had really bad throughput on wifi, even accounting for sitting in the little room off to the side of the main office. When I plugged in a wired cable performance leaped markedly so I'm wondering if there might be something up with the AP/router/channel selection?

Could be just me though of course :)

**Comment by johnmckerrell** [comment]
Feel free to pull the power on the Airport (DoES Liverpool) or even reboot the wifi/modem (DoES Backup), especially if you're the only one in.

**Comment by ajlennon** [comment]
I'll give it a go. Thanks @johnmckerrell

**Comment by amcewen** [comment]
I've spotted it being a bit slow of late, but not dug into it at all.  Just now, however, it seems pretty decent.  Just tried a Speedtest and I'm getting 48Mbps down, 13Mbps up and 31ms ping time - http://www.speedtest.net/my-result/5926290869

**Comment by ajlennon** [comment]
fwiw doing some testing here with @amcewen and here are the values I get which seem pretty good

wifi - down 8.92 Mbps, up 8.13Mbps
wired - down 48.58 Mbps, up 62.94 Mbps

**Comment by stevesparrow** [comment]
I gave up on the wife in Room 29 shortly after moving in.  It seemed patchy for anything more than browsing.   My  speed tests looked very similar for wired and wireless, but the wireless seemed to struggle with voip quite often.

S

**Comment by ajlennon** [comment]
Good point @stevesparrow - I find the Skype over wifi is unusable
