### ISSUE TITLE
Bring in the new year's Panettone

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#415]
It's traditional, and 11am on the first day after new year marks the point at which I could go for a nice piece of cake!

**Comment by ajlennon** [comment]
I was hearing on the news today that post-festivity cake culture is making us al unhealthy and that bosses need to ban this practise from the work-place.

(Needless to say this is not a viewpoint with which I concur - roll on chocolate panettone!)

**Comment by ajlennon** [comment]
@DefProc  Better late than never. In the kitchen. Happy New Year!

![cake](https://cloud.githubusercontent.com/assets/1537834/22285008/c36442f2-e2e1-11e6-97b6-64913b9a5aa2.JPG)

**Comment by johnmckerrell** [comment]
ENOTAPANETTONE

HTTP Status 419: I am not a panettone

I had been meaning to make one in the bread maker but had forgotten about this issue. Now that you've reminded me I'll try to bring one in next week.

**Comment by ajlennon** [comment]
In the spirit of the new American administration I am using alternative facts here.

**Comment by DefProc** [comment]
I can confirm that this is not a panettone, 'tho it is tasty!

**Comment by johnmckerrell** [comment]
Procured but not transported

**Comment by ajlennon** [comment]
When will the Panetonne be gracing us with its presence?

**Comment by johnmckerrell** [comment]
I'll probably save it for the Christmas party though I'll try to bring it in earlier. I can confirm it's genuine Panettone.

![2017-11-25 14 42 06-rotated](https://user-images.githubusercontent.com/27243/33231591-90f903cc-d1ef-11e7-8522-1d06503f7b89.jpg)

**Comment by ajlennon** [comment]
Look what I just found on the #forDoES shelf of the local ALDI

![panetonne](https://user-images.githubusercontent.com/1537834/34543445-ba72a890-f0d8-11e7-9bb2-ed2a8967e087.JPG)

**Comment by johnmckerrell** [comment]
Very nice. I’ve still got one at home. It’s quite big for the bike!

--

**Comment by johnmckerrell** [comment]
Brought in, was tasty, all done.
