### ISSUE TITLE
Extend the travel on the small CNC mill

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#416]
http://www.thingiverse.com/thing:21890 has some 3d-printed stepper mounts for an MF70 mill.  They'd move the couplings between the stepper motors and the carriage leadscrews outside of the carriage travel, which would give us a few more centimetres of travel and let us mill larger things.

**Comment by DoESsean** [comment]
Did any of these get printed? Were they added if so? Do we still want them if not?

**Comment by amcewen** [comment]
We can mill bigger things on either the Arcitype or the CNC router, so I reckon we park any of the Proxxon issues as `holding out for a hero`.
