### ISSUE TITLE
Train the hippos to tweet

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#418]
As mentioned in https://twitter.com/DoESLiverpool/status/817012840141901824 there are no hippos that can tweet in DoES Liverpool.

**Comment by amcewen** [comment]
I think @DoESsean saw them last, so am assigning it to him to progress.

**Comment by DoESsean** [comment]
I'm on it.

**Comment by amcewen** [comment]
It's not clear if @DoESsean is behind https://twitter.com/internethippo but I think we can close this issue now...
