### ISSUE TITLE
Notepad for noting down really long jobs on ultimakers

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#419]
I just pulled the plug on a 37hrs-to-go job on the Ultimaker2 because it had run out of filament and wasn't doing anyone any good.  

I don't know who to tell or whether they want someone to try and restart it in an different colour.

**Comment by jackie1050** [comment]
Good idea, but don't worry about this particular print. Joe was trying to print a base for a clock - I noticed there wasn't enough filament but there wasn't time to wind another reel. Left print running as he might add a laser cut part ...

**Comment by DefProc** [comment]
Is the idea of the notepad to say who's job is running, or to communicate with the owner of a failed print when they return?

Would a whiteboard do either of those jobs?

**Comment by goatchurchprime** [comment]
Yes a whiteboard with the line "Call ____ when this is done/broken".  and "Put ____ print on next"

**Comment by DoESsean** [comment]
Assigning this to myself to buy a whiteboard for the printers when we move.
