### ISSUE TITLE
Doorbot screen should not show duplicate events

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#42]
Such as during IoT Boost, when the both laser calendars and the events calendar had the same events on them so the doorbot read: "Welcome IoT Boost, IoT Boost and IoT Boost"!

I can't think of a reason for keeping duplicates (even if two people with the same name visit on the same day, that's still OK for there to be one name). Can the screens code be changed to parse out exact duplicates?

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
