### ISSUE TITLE
Sticky label printer not responding

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#420]
I've rebooted the machine, opened the Dynmo software and tried again.  

I've even rewritten the instructions ( https://github.com/DoESLiverpool/wiki/wiki/Sticky-Label-printer ) 

but nothing seems to help

**Comment by ajlennon** [comment]
On 13/01/2017 14:00, Julian Todd wrote:
>
> I've rebooted the machine, opened the Dynmo software and tried again.
>
> I've even rewritten the instructions (
> https://github.com/DoESLiverpool/wiki/wiki/Sticky-Label-printer )
>
> but nothing seems to help
>
>

When I installed the software I checked and it printed out my test label
without a problem...

**Comment by goatchurchprime** [comment]
I'm sure there's something obvious, but I can't find it.  When we get to it we can put it in the instructions.  

Have documented the other label printer in the meantime.

**Comment by ajlennon** [comment]
On 13/01/2017 14:56, Julian Todd wrote:
>
> I'm sure there's something obvious, but I can't find it. When we get
> to it we can put it in the instructions.
>
> Have documented the other label printer in the meantime.
>


I'm out in meetings until Wednesday but unless it resolves itself in the
meantime I'll take a look then :)

Cheers, Alex

**Comment by goatchurchprime** [comment]
Fixed by plugging the USB in.  

First label I printed was "Check USB plugged in if not working"
