### ISSUE TITLE
official book exchange shelf

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#424]
Do less work.  Spend more time reading stuff.  

Book exchange shelf should be handy for a label printer.  

Two types of books:
    1) Take this away, we don't need it back
    2) This is a good book (property of...), please borrow and read and bring it back if possible.
Anything in the former category gets binned if longer than X-months.  

We've got 2 unofficial locations right now: in Dinky and in mainroom.  

Requires some instructions to be made and the word to get out.

We could do the same with a box of arduino sensors/components -- esp if there is some descriptive labeling on each one to make it useful.

**Comment by DoESsean** [comment]
As we have shelves that people can take and leave from, and seeing as how @ajlennon brought a load of books in for people to take as they saw fit and they didn't exactly fly off the shelves AND given how little space we have just for 'stuff' I'm closing this issue.
