### ISSUE TITLE
Get a banner/pull up board for exhibits

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#427]
We're often fairly light on large scale DoES Liverpool specific branding. 

Something like a pull up banner would go well at one end or behind a stand.

**Comment by amcewen** [comment]
I think we need to make some progress on it rather than raise a new issue about it each January... :-D

This is a duplicate of #254...

**Comment by DefProc** [comment]
Ah, I only did a text search for banner!
