### ISSUE TITLE
Tea composter

### ISSUE THREAD

**Issue by stevesparrow** [DoESLiverpool/somebody-should#428]
It would be good to replace the tea bag and coffee composter tub in the kitchen with one that's a little more.... pleasant looking.

It's been doing a good job for a while, and Julian does a great job composting the results.  It would just be good for it to look a little better.

Any suggestions for a replacement.

1) Two sealable containers, which can be swapped.

2) A teabag bin which can be emptied into something else.

**Comment by DefProc** [comment]
Sounds like a good idea. 

One of the advantages of the current tub is that it gets taken away to be emptied. If we had a container, that might mean having to also carry compostable bags for inserts, so the current disposal route will still run (ie. @goatchurchprime can still take it home in the bags for composting).

**Comment by DefProc** [comment]
@stevesparrow has put a compost bin in the kitchen. I've just ordered some biodegradable 5litre bags to try and keep it a little cleaner over the longer term.

**Comment by aubergine10** [comment]
I had no idea there was a compost bag - where is it? I've just been binning my teabags but will seek out the compost bag next time.

Also, where will the compost be going? There are a growing number of permaculture and food growing groups in Liverpool that might be interested...

**Comment by stevesparrow** [comment]
Julian provided it a year or two ago, probably longer, and has been emptying it into his compost ever since. 
 Thanks Patrick.
