### ISSUE TITLE
Gerald is jumping along the y axis

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#429]
At make night Gerald was working fine for most of the evening,
In the last hour it started jumping along the y axis, in use and setup. 

We had a look and the belts don't seem to be lose, and there wasn't anything else obviously wrong.

As it is it's unusable.

**Comment by amcewen** [comment]
I think (I'll reopen this if there are more reports of problems with him today) that this is a duplicate of #287.  The remaining screw for the shim had worked loose again, so I've re-tightened it.
