### ISSUE TITLE
Complete update of the things going on page

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#430]
Intended to be the exhaustive index of the past and present happenings
https://github.com/DoESLiverpool/wiki/wiki/Things-going-on

Part of the purpose is to clear out the 
https://github.com/DoESLiverpool/wiki/wiki/Unorganized-administrative-content
page I quickly salvaged from the old wiki

**Comment by aubergine10** [comment]
Can this ticket be closed?

There will be a full scan of the wiki when the website gets updated in a few weeks at which point some further housekeeping can be performed.

**Comment by DoESsean** [comment]
I'd leave it open until the housekeeping has been performed, that way it
doesn't slip though the cracks.
