### ISSUE TITLE
Room layout drawings and photos

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#432]
The page here is a little bit short of pictures/diagrams.  
    https://github.com/DoESLiverpool/wiki/wiki/Rooms

We could do with a scaled drawing of any kind of the room setup to link from here.  Ideally mocked up in SVG so we can change labels and links into it.

**Comment by johnmckerrell** [comment]
Is this any good? I'm not sure what got exported but it should be room outlines for most rooms and a few corridors in DXF (mm units).

[DoES Liverpool.dxf.zip](https://github.com/DoESLiverpool/somebody-should/files/727189/DoES.Liverpool.dxf.zip)

**Comment by johnmckerrell** [comment]
Ok that definitely looks a bit weird. Attached a PNG of the same thing, hopefully someone should be able to do something interesting with the DXF though.

![img_96e96944be10-1](https://cloud.githubusercontent.com/assets/27243/22255795/720aa1b2-e250-11e6-9baa-0ee8d960e9b9.jpeg)

**Comment by goatchurchprime** [comment]
That brown thing is awful.  And missing dinky and labels for elevator
(where people first come in) and windows

It would be lovely for it to be like this:
    http://wiki.makespace.org/File:WIP%2BMakespace-dan.png

Julian.

**Comment by euanwithersby** [comment]
That looks like an AutoCAD 3D extrusion. If this file is a DXF, does anyone have access to AutoCAD with that plugin / extension?

**Comment by johnmckerrell** [comment]
@goatchurchprime the "brown thing" is demonstrating what is in the DXF, the DXF does have Dinky but it became "disconnected" so doesn't show up in that render. I'm sure someone will be able to do something nice with the DXF, I can also export PDF but I imagine the DXF is best really.

**Comment by euanwithersby** [comment]
I've had a look at extruding the DXF in an isometric diagram using Corel, but it's too time consuming to be practical. It will need to be something like AutoCAD, Sketchup or something similar.

**Comment by aubergine10** [comment]
As DoES will be moving to new premises in next few months, can I suggest this ticket is closed for now and we can start a new ticket after the move if a floor plan is still desired?

**Comment by aubergine10** [comment]
What about a "London Tube Map" approach - simplify the layout to improve legibility:

![does floor 4](https://cloud.githubusercontent.com/assets/1386719/25556200/8f77b06a-2cf0-11e7-8bce-9ab186908222.png)

**Comment by aubergine10** [comment]
Labels for key equipment could be added too...

![does floor 4](https://cloud.githubusercontent.com/assets/1386719/25556787/49972750-2cfb-11e7-8913-20a333b3986a.png)

**Comment by DoESsean** [comment]
While it's lovely to remember Gostins, this is kind of obsolete now.
