### ISSUE TITLE
Get an HDMI solution for projecting

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#433]
Both our projectors are VGA rather than HDMI.  More laptops only have HDMI outputs.  There is an HDMI<->VGA cable knocking around, but it doesn't appear to work (didn't on either my or @goatchurchprime's laptops)

We should either get an adapter or maybe even a new projector that's HDMI?

**Comment by ajlennon** [comment]
I've had trouble with HDMI->VGA cables with digital to analog (I think)

If that proves to be an issue another option might be a USB VGA adapter perhaps

e.g

http://www.ebay.co.uk/itm/USB-3-0-to-VGA-Multi-Display-Video-Graphic-External-Cable-Adapter-for-Win-XP-7-8-/231503628247?hash=item35e6b107d7:g:05QAAOSwpDdU7vLK

**Comment by DoESsean** [comment]
Happy to look for a new projector if someone gives me a) an idea of spec, and b) a rough budget.

Never having dealt with projectors before, I'd be a bit lost without a little guidance.

**Comment by goatchurchprime** [comment]
Historical scavenged from old doeswiki here: https://github.com/DoESLiverpool/wiki/wiki/AV-setup-in-Dinky.  Delete that page when done with it and in-line info about the projector (brand, capabilities, etc) either in the Rooms#Dinky page or from the Equipment page.

**Comment by DefProc** [comment]
Something like this: 
https://www.amazon.co.uk/Adapter-Converter-Charging-Raspberry-Chromebook/dp/B00NBUTHJG

**Comment by DoESsean** [comment]
The adaptor cable posted by @DefProc has been ordered. It should be here by the end of the week.
