### ISSUE TITLE
We've lost the 3D printed vacuum cleaner nozzle and its design again

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#436]
I'm really missing it.  

When we have the design again, link to it from the cleaning up page:
    https://github.com/DoESLiverpool/wiki/wiki/Waste,-recycling-and-cleaning-up

**Comment by amcewen** [comment]
Its design is still somewhere-safe... https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/3Dprints/DysonVacuumAttachment.scad

I've added a link to the wiki page, but haven't generated an STL or printed it yet.

**Comment by amcewen** [comment]
New one printed and fitted.  I tweaked the dimensions so that it fits nicely when printed on the Ultimakers (the last one was printed on the Up)

https://twitter.com/amcewen/status/826011667565780992
