### ISSUE TITLE
calendar links to makernight.co.uk bad

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#437]
I've been fixing up the https://doesliverpool.com/calendar/ page with links of stuff I want to see (eg to the liverpool digital calendar as well), and note that the links in the Calendar(s) for makernight to http://makernight.co.uk/ is no good.  

The makernight.co.uk website doesn't work.  And anyway I don't even think it was up to date.  And the URL is a little too non-specific to the fact that it is here in one place, rather than some confusingly global movement, like halloween night.  

It needs changing or redirecting either to: https://github.com/DoESLiverpool/wiki/wiki/Maker-night or to a holding page on the doesliverpool.com website.  In the current state it puts people off by giving the impression that it might be a zombie recurring event in the calendars.

**Comment by johnmckerrell** [comment]
I've updated the calendar, might be worth getting maker night.co.uk redirected (would at least be a handier, shorter URL), I'll make a separate ticket for that.

**Comment by goatchurchprime** [comment]
That's a start.  Not considered done-done as the old links are still there (and in the defnet calendar) and no determination has been made about that makernight.co.uk website

**Comment by Madscouser** [comment]
Hi, 

Could someone please update (or tell me how to do it) the Liverpool Sewing Club info so it links to our Facebook page (http://Facebook.com/LiverpoolSewingClub) rather than Twitter account as there's loads more useful info on FB than twitter? 

Thanks, Beth

**Comment by johnmckerrell** [comment]
Beth that should now be updated for all future events.

Julian I've updated the defnet calendar too, possibly your client hasn't synced yet? Also originally I didn't edit past events but that should be done now. Feel free to leave this open until makernight.co.uk is under our control again.

**Comment by Madscouser** [comment]
Thanks 😊

**Comment by aubergine10** [comment]
Closing ticket as this appears to be resolved.
