### ISSUE TITLE
Doorbot2 is slow to recognise RFID tags

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#439]
The kitchen doorbot sometimes takes a while (up to a minute) to recognise the tag and unlock the door.

A reboot didn't help (it had fallen off the network).  Can't spot anything obvious with the wiring, and the RFID reader (not necessarily the pi, I mean that the red LED lights up on the reader when you put a card in front of it) is recognising tags okay.

**Comment by johnmckerrell** [comment]
Is this still valid? Seems pretty speedy these days.

**Comment by amcewen** [comment]
Not sure.  It was slow at the end of last week (admittedly a, different, completely different hardware/software combination).  I wonder if it's slow when the Pi isn't on the network?  Maybe close this and reopen if it recurs.
