### ISSUE TITLE
Add Ebola detection to Doorbots

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#441]
ref: http://www.digitaltrends.com/cool-tech/flu-breathalyzer/

**Comment by drfraz** [comment]
Just checking temperature might be easier, could hook up an FLIR infrared
camera to stop any one with a high temp getting in.
I think it would have a higher sensitivity, cover a wider range of bugs & a
lower chance of catching whatever the person before you has left on the
mouth piece

**Comment by aubergine10** [comment]
Bunch of other medical sensor stuff on this hackaday project if anyone is interested: https://hackaday.io/project/4693-medical-tricorder

**Comment by amcewen** [comment]
Think this is going to have to wait until there's some decent bio-sensing-hackers experimenting with things around here ;-)

**Comment by ajlennon** [comment]
I'm sure you're right. I think this will be the short term plan to take us to the Ebola testing goal -

https://www.sciencealert.com/mit-is-working-on-colour-changing-tattoo-ink-that-can-monitor-your-health-in-real-time
