### ISSUE TITLE
Ask questions to Williamson Square Agent

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#443]
These questions *have been asked*:
- [ ] Is lift maintenance covered by service charge?
- [ ] Are we definitely ok subletting? We would need to ensure this is in the lease rather than having a verbal confirmation.
- [ ] Will VAT be added?
- [ ] Can we have an automatic door opener? (And how will doors to the building work in general?)
- [ ] Can you confirm who the landlord is and will this give us access to the loading bay?

**Comment by aubergine10** [comment]
Any update on this ticket?

**Comment by johnmckerrell** [comment]
Let's close this, the agent shut us down.
