### ISSUE TITLE
Put the coffee machine on an S20 esp plug

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#444]
Developing code here:

https://bitbucket.org/goatchurch/esp8266cavelogger/src/27e7c7b73e64c61dcbbe78aea265338ffc1e5629/s20endpoint/?at=master

Features: 
1) Press button for coffee machine on
2) Goes off in evening && after more than 4 hours of on-ness (so you can put coffee on in the evening without it switching off immediately
3) Does not come on in the morning before someone's made the coffee (like it does now)
4) Records when last coffee was put on -- and puts it into doorbot
5) Has mode for pre-made coffee that turns on after 6am when first use of doorbot is detected
6) Allows info to be seen from webpage, incl turning on and off

To do this, we need doorbot to be documented with some API endpoints and fixed IPaddress (issue 265) to state when coffee is done and disclose when person has arrived -- either by polling every 30seconds in the morning or doorbot calling the S20

**Comment by goatchurchprime** [comment]
Current code on the S20 (which is plugged into the fan) is here: https://bitbucket.org/goatchurch/esp8266cavelogger/src/c3c6a22d1a77c399c66918e5995245742071eff9/s20endpoint/?at=master

It connects to DoESLiverpool wifi, last known at 192.168.0.162  -- (how do we find that?)

The interface is [plug/led]=[0/1]

**Comment by ajlennon** [comment]
On 11/02/2017 17:35, Julian Todd wrote:
>
> Current code on the S20 (which is plugged into the fan) is here:
> https://bitbucket.org/goatchurch/esp8266cavelogger/src/c3c6a22d1a77c399c66918e5995245742071eff9/s20endpoint/?at=master
>
> It connects to DoESLiverpool wifi, last known at 192.168.0.162 -- (how
> do we find that?)
>
> The interface is [plug/led]=[0/1]
>
> —
>

Fantastic idea. I had a lot of fun with these little beauties last year
when I needed to switch things on and off for a board test

Code was commited here: https://github.com/DynamicDevices/orvibocontroller

In historical spirit surely we have to put a RPi Cam on and do some kind
of analytics for the tweets?

Cheers,

Alex

**Comment by ajlennon** [comment]
https://www.youtube.com/watch?v=JUDyvGDsUw

**Comment by goatchurchprime** [comment]
done with a sonoff pow2 now
