### ISSUE TITLE
get a proper solder fume extractor

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#446]
I saw Tom, the not normally very clean living, caver electronics person using one of these at the weekend:
    http://www.maplin.co.uk/p/solder-fume-extractor-n33ch
He said maplins is the cheapest one at £17

It could be an improvement on our plug-in four-fan wall that merely blows the problem elsewhere around the room.

**Comment by DefProc** [comment]
The key benefit of the fans are that they move the rosin fumes away from the person soldering, so (over longer periods of time) it doesn't cause dry/red eyes or throat irritation (lead free solder has a higher rosin flux content than leaded). As the essential effect is to reduce the smoke concentration for the person soldering, blowing the problem elsewhere (mixing with a much greater volume of air) is the intended operation. 

We don't do enough soldering in the workshop to require full extraction.

**Comment by DefProc** [comment]
Unless there's a good reason to keep this open, I'm going to *tentatively* close this one.
