### ISSUE TITLE
Fasten in the speaker on doorbot2 properly

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#450]
As part of #426 we've added audio playback on doorbot2 (the workshop/kitchen door).  The speaker isn't particularly well secured at present, so it'd be good to work out something better (so it doesn't fall off and pull half the wires out of the Pi... :-)

**Comment by DoESsean** [comment]
Speaker is currently standing on a box, and seems fairly safe. 

Obviously a nicer solution will be desirable in the new building, but for now this can be closed.
