### ISSUE TITLE
Create a morse code tweeter

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#453]
I've sourced a WW2 morse key from eBay. The plan is to connect this up to a GPIO input on an ESP8266 running MicroPython

![image](https://cloud.githubusercontent.com/assets/1537834/23167672/404be200-f83d-11e6-872c-e7fc72dfb5d3.png)

I have hacked together some Morse encoding/decoding code which is in GitHub [here](https://github.com/DynamicDevices/morse)

There are a couple of Python scripts, one that'll run on Windows, encode a string to a custom format I've created and beep as it does it. Then it reads back the format and outputs the decoded characters.

There's a second one which runs under MicroPython on the ESP8266, encodes, decodes and publishes via MQtt up to a server running node-red which then tweets from @ddmorsetweeter

The encode format I'm using is basically a timestamped '1' and '0' to emulate press/release of the key when I have it attached to a GPIO.

Where I'm likely to get stuck is with the timing of the decode, which is currently hard coded.

There are probably good adaptive strategies to manage this and if anybody can advise I'd appreciate it? 

Maybe something a bit like auto-bauding on RS232 UARTs where it samples bit times on a few characters to work out what the baud rate is?

@DefProc @amcewen tells me you are an expert at morse? Could you offer any advice? (Maybe generate some test files for me to work with once I have the key?)

**Comment by DefProc** [comment]
I wrote an arduino library to do the stream encoding and decoding of morse pulses called [Lewis](https://github.com/DefProc/Lewis)

**Comment by johnmckerrell** [comment]
I'm not sure how this is a DoES Liverpool task so going to close it, hope that's ok. I would expect issues on here to be around tasks to help organise or enhance the space rather than just general projects that people are thinking of.

**Comment by ajlennon** [comment]
Fair point :)
