### ISSUE TITLE
make hotdesk power access easier to use

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#456]
A most of the available desks in the main room have ad-hoc extensions at or near them, but nothing that makes them comfortable for an easy "sit down, plug in and work" usage. 

I've ordered a few desk mounted [power and usb supplies](https://www.kenable.co.uk/product_info.php?products_id=8058) to see if fitting them will satisfactorily improve this — and as they clamp on the back lip of the desk, they should fit on any of the desks we have.

**Comment by DefProc** [comment]
I've fitted 3 and tidied the desks. As they seem to fit nicely, I've ordered 3 more to cover all the currently available hotdesking spaces in the main room. 

Fitting all these should quite handily cover #28 too, by allowing us to indicate which desks are available as they'll each have a set of empty sockets.

**Comment by johnmckerrell** [comment]
Bit late but that's a fair whack to provide 2 sockets per desk. And I assume it needs N sockets at the other end to plug these into? There's no clever daisy chaining or anything like that?

Also not sure it really covers #28 as if there's stuff on the desks they'll still look busy even if the sockets are free.

**Comment by johnmckerrell** [comment]
Makes me feel less guilty about wanting  [these](http://cpc.farnell.com/click/cl036/mc-2-gang-d-p-13a-switched-socket/dp/PL14833) or maybe [these](http://cpc.farnell.com/pro-elec/ss2213u/socket-twin-13a-sw-with-usb-ss/dp/PL15150).

**Comment by DefProc** [comment]
I think I'd argue that if there's stuff on the desks, it indicates that they are not free anyway. And that desks which are available for hotdesking should be clear of any other stuff, otherwise they are not ready for someone to come and just sit down and start working. 

I'm assuming that when a desk gets taken as a permanent desk, that person is likely to want more sockets, so we'll need to change them to a 4-way extension (sort of like the ad-hoc selections we have now). At which point, the hotdesking sockets are then not on the desk. Hence the desk is not available for hotdesking…

**Comment by DefProc** [comment]
6 fitted and initially tested yesterday. All seemed to work fine :smile:
