### ISSUE TITLE
Sophia is down on power

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#457]
Today Sophia is struggling to cut through 3mm birch ply.  Running with speed 5 and power 50 will *just* work, a speed of 6 leaves lots not cut through.  The whiteboard suggests 7-10 for the speed...

**Comment by DefProc** [comment]
As it was working great yesterday (speed/power(corner power) of 7/50(40) 
for a heavy cut), with no ghosting (ref #198 ), this suggests that 
carriage misalignment is the most likely cause, and the laser is not 
hitting the final mirror in the centre as it should.

As I'm not in atm, has the carriage slipped down on the wheels?

**Comment by amcewen** [comment]
Not that I can see.  Have fiddled with the carriage to check how well its running, and that doesn't seem to have improved matters at all.  It's failing to cut even at speed 5 now (temp is running at 24 degrees, so that might explain some of the tail off during the day), so I'm giving up for the day.

**Comment by amcewen** [comment]
I've not heard any problems with Sophia since then, maybe it was a poor batch of wood or something.  I'll close it until there's something more concrete to go on.
