### ISSUE TITLE
Have a 6th birthday party

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#458]
We should have a 6th birthday party, especially as we missed our 5th!

**Comment by johnmckerrell** [comment]
Random idea I just read about, ask guests to bring a present of their "favourite thing", presents are then distributed back out ideally at random.

**Comment by ajlennon** [comment]
Would these be "internet things" ? :)

**Comment by stevesparrow** [comment]
When is the does birthday?

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by johnmckerrell** [comment]
4th March 2011 does liverpool.com was registered

10th June 2011 DoES Liverpool CIC was incorporated

18th July 2011 we declared we were ready for visitors:

https://twitter.com/mcknut/status/92970053171032064 <https://twitter.com/mcknut/status/92970053171032064>

22nd July 2011 we had our first free open day (and this is, accidentally, generally what I've personally considered our first day of opening)

https://twitter.com/mcknut/status/93986921268789249 <https://twitter.com/mcknut/status/93986921268789249>


So personally I aim around the mid to end of July but it can easily be as early as June.

**Comment by ajlennon** [comment]
If you did something akin to the Queen and had a couple then there would be double the cake. 

Just a thought...

**Comment by stevesparrow** [comment]
What about Friday August 18th or Saturday August 19th for the (first) DoES 6th party?

**Comment by amcewen** [comment]
@ajlennon you can see how much trouble we have arranging *one* birthday party.  What makes you think doubling the number we need to organise would work better...? :-)

@stevesparrow The 19th (and 20th) August are Manchester MakeFest, which will make even the 18th difficult for some of us.  How about the 25th or 26th?

**Comment by stevesparrow** [comment]
Sounds good to me.  Unless there are objections, i'll get it underway, hopefully with @DoESsean. :)

**Comment by stevesparrow** [comment]
- [ ] invites
- [ ] Decide on / include: Bring a favourite thing (value limit)
- [ ] Order keg
- [ ] Clean out dinkynand workshop in prep
- [ ] decide on food
- [ ] other drinks

What else?  Do edit to add more.

**Comment by ajlennon** [comment]
- [ ] mime artists ?

**Comment by drfraz** [comment]
Paint ball guns for when the mime artists are performing?

**Comment by DoESsean** [comment]
Mailchimp invite has gone out today. I'll stick something in the Google
Group too for anyone that isn't on the Announce List (although I don't know
why you wouldn't be. You sure would miss out on some prose).

**Comment by SayBeano** [comment]
Is this this Saturday? I'd forgot until weeknotes digest.

**Comment by johnmckerrell** [comment]
It is.

**Comment by SayBeano** [comment]
Sound, hoping to make it (involved in the KLF 3dayer though so might be flakey)!
