### ISSUE TITLE
Restore the two laser cutter calendars to the laser cutter page

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#459]
I think this happened as part of the move towards github wiki pages over website pages, but the page that originally described about using the laser cutters and showed the free/busy status of both laser cutters has gone. It's been replaced by a pair of links that go off page to show the availability of each cutter separately.

I've had mention that it's difficult to find out when the cutters are available by a new user, and was surprised to find that the overview calendar had gone (I must have missed the page updates). One of it's key benefits was that a user can visually search that page for when the cutters are available, and then click through to make a booking at the time of their choosing. 

Here's the embed code for both Sophia and Gerald (organisers with access will see the booking details, anonymous access shows free/busy):
 
```
<iframe src="https://calendar.google.com/calendar/embed?title=Laser%20cutter%20availability&amp;mode=WEEK&amp;height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=doesliverpool.com_3a7t1mug53qbloackgno6u2mqk%40group.calendar.google.com&amp;color=%2329527A&amp;src=doesliverpool.com_uf4b6b79iq6dd7to8rsm8egpgs%40group.calendar.google.com&amp;color=%23B1440E&amp;ctz=Europe%2FLondon" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

A quick look at editing [that wiki page] (https://github.com/DoESLiverpool/wiki/wiki/LaserCutting) suggests that github wiki pages don't allow iframe embeds. 

To get around this, I've put the calendars back on a [doesliverpool.com/laser-cutter-calendar/](https://doesliverpool.com/laser-cutter-calendar/) page that already existed, but was unused, and tidied up the top bar menus as they had turned in to a proper show.

**Comment by DefProc** [comment]
Rather than just having the laser cutter page on the wiki, and the calendars on the website; I'd prefer to have an overview page on the website including the calendars, plus a wiki page of more detailed, but more easily update-able information.

**Comment by aubergine10** [comment]
I've got a login on the main site now so I'll take a look at doing this (won't link them in to the menus until people have had chance to review).

**Comment by aubergine10** [comment]
Do you want me to have a go at adding the page to website? I could leave it unlinked initially so people can provide feedback before making it live.

I've also got transparent background pics of the laser printers (maybe not exact same make and model, but close enough for people to recognise instantly when they visit workshop):

![gerald](https://cloud.githubusercontent.com/assets/1386719/25879800/9f1f81a8-352b-11e7-8ad8-c7e61036b7e8.png)
![sophia](https://cloud.githubusercontent.com/assets/1386719/25879799/9f1eabac-352b-11e7-8ecf-97363c56d47e.png)

I'll also be tackling the wiki pages for the two printers tomorrow (Wednesday), updating them to the same template as other equipment (unless anyone objects).

**Comment by DefProc** [comment]
@aubergine10 There is already a laser cutting page. How about changing the page on staging.doesliverpool.com instead?

**Comment by aubergine10** [comment]
Yes, I'll do that now. (I had no idea the staging site existed until now).

**Comment by aubergine10** [comment]
I've updated staging: http://staging.doesliverpool.com/laser-cutter-calendar/

I think the images of the lasers are getting in the way of the calendar (I assume a lot of people go to that page specifically to view the calendar?) - what do you think?

Maybe remove the images and just leave the sentence above that links to the wiki pages?

**Comment by aubergine10** [comment]
Also, would it be worth putting a colour key above the calendar? I assume red = sophia, black (dark blue?) = Gerald?

**Comment by amcewen** [comment]
Organisers' meeting notes: @DefProc states this has been done.
