### ISSUE TITLE
3 Minute wait before opening laser cutter lid

### ISSUE THREAD

**Issue by fjfish** [DoESLiverpool/somebody-should#46]
Just had workshop full of smoke (again)

Talking to Ross, said maybe we put a timer on the lid of the cutter that starts counter when power falls off - laser has stopped cutting.

In the interim nice big sign "Wait 2 minutes after cutting has finished"??

**Comment by amcewen** [comment]
Given the new improved extraction, I think the current 2 minute warning sign suffices.
