### ISSUE TITLE
The Wordpress blog doesn't appear to accept image uploads

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#461]
I've tried uploading small and large photos to no avail, had a poke around on 34sp and in the Wordpress settings but I don't see what's wrong.

**Comment by DefProc** [comment]
`Admin → Media → Add New`

Just uploaded something now to test and it appeared. And you're the same role as me. 

How are you trying to upload?

**Comment by johnmckerrell** [comment]
Looks like it's an issue with Safari ¯\_(ツ)_/¯
