### ISSUE TITLE
Create an IoT device resource / hub

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#462]
I have an ever increasing number of little eval / development boards sitting around in boxes.

I'm sure others have the same situation.

I was thinking it might be useful to have a location somewhere to put them, QR code them back to some descriptive text in the DoES wiki and then people could borrow them as needed for evaluation or play.

e.g. BLE boards, LoRa boards, WiFi boards, etc. etc.

Does that seem useful?

**Comment by jackie1050** [comment]
Yes

**Comment by amcewen** [comment]
There's the "Microcontroller library" box in the workshop, which mostly has ARDX kits for playing with Arduinos, but also has a few other boards in there too (a couple of Launchpad modules, some plug Linux computers, etc.)

That would seem the obvious place to put them, and finding a better way of documenting/advertising what's there would be good.

**Comment by ajlennon** [comment]
Is there an existing page on the Microcontroller Library on the Wiki or maybe I'll create one?

**Comment by huffeec** [comment]
Had a look through the Microcontroller library box at Maker tonight,
It currently contains;

5 x Sheeva plug
1 x Arduino Uno
1 x Beaglebone green
1 x MSP430
1 x Olimex development board
1 x AT90USBKey
3 x partial Ardx kits (No Arduinos)

**Comment by aubergine10** [comment]
There's also a bunch of wearable MCs in the wearables box - Flora (v1 and v2), Gemma, etc.

In particular, as a newbie, I don't really know what the ownership status of the devices is - do they belong to specific groups, can they be used by any of the groups attending DoES, do they need returning after use, etc? Answers to those questions would be useful on the wiki page also.

I'd be happy to spend a few hours on-site organising the boxes and building an initial list (with pics and links to vendor sites, etc) in the wiki if no one objects?

**Comment by ajlennon** [comment]
@aubergine10 I have a load of boards I'd like to itemise and put in a box for people to borrow and play with. Maybe that's something you'd like to take a look at?

**Comment by amcewen** [comment]
Documenting/better explaining that sort of stuff would be great @aubergine10!  The general idea behind the "Microcontroller Library" box was that it had stuff people could borrow while in DoES to play around with things - particularly to get started playing with Arduino before working out what to buy themselves.

However, it's probably only the ARDX kits that aren't in a "free to a good home" category, and they could do with tidying up and re-stocking so they're ready for people to use.  I've probably got bits to restock most of them, if someone wants to work out what's missing.  (I'm happy to go through it and help categorize at #makernight some time).  

For the stuff in the wearables box, @jackie1050 or Laura would be the people to ask.

**Comment by aubergine10** [comment]
@ajlennon Yes :) Let me know where they are and I'll make a start on them.

@amcewen I've already organised most of the wearables box so fairly familiar with that.

As for the other stuff, I'm planning to spend an afternoon at DoES some time this coming week (Thursday?) to search through the other boxes and list what's where.

**Comment by DoESUser** [comment]
@aubergine10 @amcewen 

I had a fun afternoon putting something together here in the workshop:

https://github.com/DoESLiverpool/wiki/wiki/IoT-Lending-Library

**Comment by aubergine10** [comment]
That is officially epic shit. Kudos.

**Comment by ajlennon** [comment]
Closing this issue for now

**Comment by huffeec** [comment]
We've had a donation of an Estimote beacons Development kit.
How do I add this to the library?

**Comment by ajlennon** [comment]
I added some provisional notes to the wiki

https://github.com/DoESLiverpool/wiki/wiki/IoT-Lending-Library#how-to-add-your-own-items-to-the-lending-library
