### ISSUE TITLE
Allow users to book desks

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#464]
@euanwithersby suggested being able to book desks in the main room, so as there's some security for someone coming in that there will be a desk available. 

I've mocked up a working process using youcanbook.me at [doesdesks.youcanbook.me](http://doesdesks.youcanbook.me) that should work fine by filling the 6 available slots on a calendar (like we do for laser bookings) and should allow us at the very least to know how many pre-booked desks we have each day. 

@euanwithersby has generously (!) "volunteered" to see if there's anything we can do to show the number of available desks programatically. ie "x desks available today" by pulling the number of events in each session of the day. 

I'm going to add this straight to the main page on doesliverpool.com in a lean approach of gauging interest in prebooking as a feature.

**Comment by DefProc** [comment]
For lack of a better option in the wordpress theme, booking direct from the website is now on *every page* in the sidebar, and there are links to booking from the main menu.

If there's enough interest, we *could* allow pre payment of hotdesks by credit card: 

 * add a reaction to this comment of :+1: if you would like pre-payment adding,
 * add a reaction of :-1: if you think that's a bad idea,
 * add a reaction of :confused: if you don't care or don't understand.

*reactions are at the top right of the comment area*

**Comment by johnmckerrell** [comment]
How is the payment handled and what cut is taken?

**Comment by DefProc** [comment]
The "just tick the box" option is stripe, so 1.4%+20p https://stripe.com/gb/pricing 

That would be 34p on a £10 day or 27p on a half day

**Comment by DefProc** [comment]
Scratch that, there's a 1% fee from youcanbook.me, so 44p and 32p respectively.

**Comment by johnmckerrell** [comment]
Does using stripe allow us to more generally take CC payments? Is that cheaper than PayPal? sounds it. I'd suggest not just ticking the box unless we get ~5 ticks tho

**Comment by DefProc** [comment]
It does need a little more thought before just ticking, specifically things like the process flow for taking payments, how do we deal with pre-paid/post-paid/cake-days, and do we need to confirm bookings etc.

**Comment by DefProc** [comment]
I've just changed the booking emails so they go to hello@, so all the organisers can see initially. This isn't set in stone, just then we can see how it gets used to start with.

**Comment by johnmckerrell** [comment]
That's good, I had considered that, thought it might get a bit noisy but definitely better that way for now, if it's too much we can obviously change it.

**Comment by euanwithersby** [comment]
The count of items (i.e. desks) remaining from a fixed number in a specific calendar is pretty simple in JS, but I'll need to be there when someone with access to the DoES Google account is around for setting up auth, checking the logic for how the calendar is working and so on.

**Comment by johnmckerrell** [comment]
@euanwithersby You may be able to make use of the proxied calendars that the main door screen uses (or even the calendar parsing code too) https://github.com/DoESLiverpool/doesscreens

Wouldn't hurt to add "Number of available desks: N" to the screen either ;-)

**Comment by euanwithersby** [comment]
Looks like a good plan although the desks calendar isn't on the lists unfortunately. The code will still need to end on the DoES site too. I'd thought about the context, but a timely reminder. Am I that famous for my lack of nouns? ;-)

**Comment by DoESsean** [comment]
We have a desk booking system that sees decent usage, and has brought us people that liked its ease (nice work @DefProc )

However, the CC payment stuff is talked about in other issues, so this can be closed.
