### ISSUE TITLE
refit the bed drive belt on Gerald

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#467]
Although the bed is now more level, the drive belt came off today. 

I can't get move the motor mount on my own to move it to get the belt over and tensioned, it needs two people to do.

I've set the bed to be correct-ish focus for 3mm sheet, so Gerald has a bug, rather than broken, but it will only work if the focus is already correct for the material.

**Comment by helicalbytes** [comment]
Belt was slipping when we tried to cut out Tosca parts tonight - had to use Sophia

**Comment by amcewen** [comment]
John Cain and I have just refitted the belt.  The bed seems to be moving freely now (it had been juddering when you tried to lower it more than a cm or so).
