### ISSUE TITLE
Sophia not cutting circles accurately

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/somebody-should#468]
We used Sophia to parts for Tosca - larger circles are slightly non-circular

![wp_20170314_20_17_48_pro](https://cloud.githubusercontent.com/assets/17219493/23920935/878bcadc-08f4-11e7-80a7-2c0b5d2ed132.jpg)

**Comment by DefProc** [comment]
This is almost certainly caused by #198
