### ISSUE TITLE
Paint chalkboard paint on walls and other surfaces

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#469]
We're planning on doing this on a wall at home and it struck me it might be interesting in the workshop?

I found this product which you mix with paint so we could have our own coloured patterns?

See: https://www.ebay.co.uk/itm/252811318324 

Good idea? Terrible idea?

**Comment by shrkey** [comment]
Make sure you open a few windows when painting - the chalkboard paint smells really bad. It's fine once it's dry though.  I painted all of my desks with chalkboard paint. Very handy for making video animations :)

https://youtu.be/Qkxcq7YFJ5M

**Comment by ajlennon** [comment]
On 04/04/2017 12:15, shrkey wrote:
>
> Make sure you open a few windows when painting - the chalkboard paint
> smells really bad. It's fine once it's dry though. I painted all of my
> desks with chalkboard paint. Very handy for making video animations :)
>
> https://youtu.be/Qkxcq7YFJ5M
>
> —
>

Thanks for the advice. Love the video!

**Comment by aubergine10** [comment]
I'd like to poop on this idea; chalk creates lots of messy dust and airborne particulate.

Could we use whiteboards and applicable marker pens instead?

**Comment by ajlennon** [comment]
Would chalk pens work better?

**Comment by aubergine10** [comment]
Anything involving chalk creates particulate, even if the chalk stem is wrapped in paper.

http://aaqr.org/VOL15_No7_December2015/9_AAQR-15-04-OA-0216_2596-2608.pdf

**Comment by ajlennon** [comment]
Right Ho. I shall close this down :)

**Comment by stevesparrow** [comment]
Chalk markers are purely liquid imitation challenge.  Right?
