### ISSUE TITLE
We should have some good photos of the space

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#47]
As @rcostello said in a Google Group thread:
"Doing some quality photos of DoES would be good. Dinky looks well in the photos on the website but the main room not so much...."

**Comment by amcewen** [comment]
@DoESsean says that really all we'd need is to dress the space.  I think we'd want to at least remove the space/Mersey sign (because it's obviously incomplete at the moment).  Going to give it a bit more time to clear out issue #48.

**Comment by jamieisboss** [comment]
I have a bunch of photo that ive taken for the new website, I'll find a way of sharing them..
