### ISSUE TITLE
What could a Food and Technology day entail?

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#470]
Had a chat with @ajlennon today about the idea of a Food Technology day (based off us having bread machines).

Now, I have no idea what that might entail, but as more and more technology is incorporated into the making of food in people's homes, it seems like it might be something that would be worth at least investigating. Not only would it be fun, but it would be something very new for us, and so could be a way to get new people into DoES.

Does anyone have any ideas for what could be included? Or even any points that could shut down the idea before anyone spends too much time thinking about it?

**Comment by ajlennon** [comment]
@DoESsean #BeerSense comes to mind :)

https://twitter.com/embedded_iot/status/844191041020444673

**Comment by ajlennon** [comment]
Also @epsaul and others seem to be doing all sorts of interesting things monitoring allotments...

**Comment by DoESsean** [comment]
Hmm, something that monitors a prove on a dough could be useful (I have no
idea if I've phrased that right).

We could make utensils and things too, and it could be set up to be a very
kid friendly event, which would be good for the holidays.

**Comment by cheapjack** [comment]
@epsaul @ajlennon and me did talk about doing some Low Power Barbecues once the 'summer' kicks in (and various proposed LoRaWAN gateways kickin) hosted at our allotments just as nice family friendly days to eat and try out some things. @amcewen mentioned a nice thingiverse wind turbine which Mersey winds could take advantage of...

**Comment by cheapjack** [comment]
bread, beer, LoRaWAn, 4G, wind, burger temperature monitors?

**Comment by DoESsean** [comment]
Some kind of internet connected meat thermometer..?

**Comment by aubergine10** [comment]
Surely 3D-printed pizza has to factor in to this somewhere?

http://boingboing.net/2013/05/22/open-source-hardware-3d-printe.html

I think that project is now called http://beehex.com/

**Comment by huffeec** [comment]
I've given more thought than is probably reasonable to a pizza robot since one the kids from Little Sandbox suggested it. [https://www.instagram.com/p/BQ5S68EFMsf/](https://www.instagram.com/p/BQ5S68EFMsf/) I think the last suggestion was a mangle and a dough hopper to create infinite pizza.

So +1 from me!

**Comment by DoESsean** [comment]
A pizza robot seems to me like it should be some kind of Rube Goldberg
machine <http://coolmaterial.com/roundup/rube-goldberg-machines/> with
various layers added throughout the process. Maybe with the base being
delivered to each stage by toy train or something.

Get working, Chris.

**Comment by huffeec** [comment]
Cheers Sean.
I've added whippet, gun and midget to the BOM..

**Comment by DoESsean** [comment]
Seems like this idea might be a goer then.

Would anyone be interested in getting together one evening to work out what
format it could take, as it seems to have floated a considerable distance
from the original idea of 'let's bring a breadmaker in, and call it a food
and technology day'.

Could just do it over a beer or something if people were interested, rather
than anything more formal, and then stick a day in the diary to actually do
whatever we decide it is.

**Comment by ajlennon** [comment]
Wondering whether it could link to health. Food, Exercise, calories, carbs/fats/proteins, FitBits,... Node_Red flows, Acker's Bells...

**Comment by ajlennon** [comment]
@DoESsean some more thoughts to add into the mix for a new wider on a DoES Food Tech day

Health... Obesity... Calorific intake and outgoing.

e.g. Nutracheck / MyFitnessPal and so for to monitor intake
       Fitbit, Nike's band and so forth to monitor calories burnt.
       And of course internet connected scales...

How all this kind of thing - tech, statistics, data-visualisation, closing the information loop, psychology, nudge theory, can help us achieve our goals

Then moving onto the wider picture such as the economic drivers for obesity

http://www.naturallyintense.net/blog/diet/how-the-food-industry-makes-you-overeat/

Maybe we could get a few people to talk about the science as it relates to the tech?

**Comment by DoESsean** [comment]
Now that I'm back, I can have another look at this and see what we might be
able to put together.

**Comment by ajlennon** [comment]
Maybe we could get a speaker in to talk about low carb versus low fat diets, about ketosis and the science behind it all #does #biohacking ?

**Comment by ajlennon** [comment]
This looks pretty awesome. Might fit in there somewhere with Food Tech @DoESsean  ?

http://www.instructables.com/id/Online-Herb-Hydro-Grow/

**Comment by goatchurchprime** [comment]
see #613

**Comment by DoESsean** [comment]
Over two years old, so I'm closing this as a going concern, and sticking on a 'Holding out for a Hero' label.

I still think it's a good idea that can be brought back in future, but, right now, it's a long way down the list.
