### ISSUE TITLE
We should highlight the food sharing area

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#472]
It would be nice to have some sort of signage around the food sharing table so that people know what it's about. I'll post an idea in a follow-up comment.

**Comment by johnmckerrell** [comment]
I had an idea around laser cutting a picket-fence, I've knocked up an SVG, attached (as an example PDF as GitHub won't let me upload SVG).

[picket-fence.pdf](https://github.com/DoESLiverpool/somebody-should/files/913493/picket-fence.pdf)

Would appreciate comments on whether this is a ridiculous idea or we actually like it.

I may have requested some free astroturf samples too. ☘️🍀🌱🍃

**Comment by DoESsean** [comment]
I like this idea a lot. We can make a little park on the table.

I may have started thinking about a barbecue area now, which I'm going to
acknowledge is getting ahead of myself.

**Comment by aubergine10** [comment]
What about "Food is Free" - widely used term in sharing communities worldwide, and tweets about it would get better exposure due to well known trope.
