### ISSUE TITLE
Gerald needs a new exhaust

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#474]
I think we could do with a fresh exhaust for Gerald (quite hard to extend reliably without leaks) as it wont make it to the top of the window any more without venting back into the room. Not sure where we got it from last time or if we've any spare?

**Comment by euanwithersby** [comment]
If it can use standard extractor flexible trunking, I picked 5m of that, a spigot pipe adaptor and a large jubilee clip up from eBay to make an extractor pipe for my spray booth for less than £10. I was thinking that a laser cut wooden panel to fit in the open window aperture with two spigots mounted in it with hoses attached might make a good and steadier solution than propping hoses in the window?

**Comment by euanwithersby** [comment]
http://m.ebay.co.uk/itm/Plastic-5-inch-125mm-Ducting-Pipe-Ventilation-Extractor-Fan-Bath-Kitchen-Toilet-/181428466133?var=&hash=item2a3dfab1d5%3Am%3AmOAIUv7M10HX5mKgSAL3wyg&_trkparms=pageci%253A52753941-1efe-11e7-84f6-74dbd180c480%257Cparentrq%253A5eee5c1815b0a5e2b51a66d4fff95ef6%257Ciid%253A1

**Comment by cheapjack** [comment]
@euanwithersby sounds like a good plan I'm just picking up some temporary ducting today in interim to extend Gerald exhaust to to of the window at least :)

**Comment by jackie1050** [comment]
There was a strong smell of acrylic while Gerald was in use earlier. Chris Fairie has added even more tape to the ducting, but it definitely needs to be replaced, even if we're going to come up with a more permanent solution later.

**Comment by DoESsean** [comment]
@amcewen has ordered some new pipe and fittings, which I assume will fix this issue, so it can be closed once that is installed.

**Comment by amcewen** [comment]
Not only have I ordered them, but they've arrived and are awaiting fitting.  That's all covered in issue #1165 though, so I'm closing this as a duplicate.

**Comment by magman2112** [comment]
A few weeks ago, @Sean-anotherone and I worked through a few websites and came up with a kit of parts we think we will need for a permanent installation for the extractor system.

The basic idea is to use steel Air Conditioning piping, mounted on the wall just below the windows, which is then routed round the room to a high level mounted fan - which then ducts the exhaust through the gable end wall. All pipes are 150mm in diameter. Flexible pipe will be used to connect the lasers to the piping, with reducers and Y couplings where necessary. We also plan to install a filter box next to the blower, to allow easier cleaning of the exhaust.

We have chosen to run the exhaust up the gable end wall using one additional 3m length of pipe, as this is about as high as we can reach with a ladder on the outside of the building. We would lileky need a cherry picker and safety gear to go any higher.

The shopping list is as follows:

From DuctStore.co.uk

2 x SR 150mm - 3m Lengths Spiral Tube @£18.04 each
2 x B90 150mm 90 degree bends @£7.78 each
1 x TCP45-150 150mm 45degree T-Piece @£38.60
1 x Y45 150mm Y Piece @£10.13
1 x RC150 150mm to 100mm Reducer @£5.80
1 x FILB 150mm Filter Box @£31.75 (includes 1 filter)
1 x EU3 150mm Filter @£4.55
6 x SPR150mm Split Ring Supports @£2.45 each
12 x BHP-8 M8 Back Plate Threaded Rod Holder @£0.75 each
2 x THRD1 M8 studding  - 1m Lengths @£1.70 each
1 x AFT 50mm Aluminium Foil Tape @£3.04
1 x NUT M8 Box of 100 @£2.21
5 x HC 60-170mm Hose Clip @£0.94 each

For the outside parts, we would add the following few items:-

1 x SR 150mm - 3m Lengths Spiral Tube @£18.04
1 x B90 150mm 90 degree bends @£7.78
3 x SPR150mm Split Ring Supports @£2.45 each
6 x BHP-8 M8 Back Plate Threaded Rod Holder @£0.75 each
2 x THRD1 M8 studding  - 1m Lengths @£1.70 each
1 x HU 150mm Roof Cowl @£35.78

**Comment by johnmckerrell** [comment]
I'm fairly sure Jason said we'd be ok running it further along the bottom of the gable wall, i.e. away from Kempston Street in the direction of Constance Street, so if that helps we'd obviously want to keep it in mind when deciding the height to go through. I imagine if there's cutting being done from the outside there might be a different height limit too.

**Comment by DoESsean** [comment]
Right, am I ordering all this stuff then?

**Comment by magman2112** [comment]
I have just updated the list with one 90 degree bend that I had missed out. This should be good to order now methinks, unless anyone has any objections.

**Comment by DoESsean** [comment]
Excellent, everything has been ordered now.

**Comment by amcewen** [comment]
Not quite sure why this was still open, given I [said I was going to close it back in July](https://github.com/DoESLiverpool/somebody-should/issues/474#issuecomment-510558771).

Anyway, I've migrated the relevant comments over and we should continue this discussion on the venerable issue #5 :-D
