### ISSUE TITLE
Ultimaker 2 has a broken filament guide

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#475]
Possibly related to #393 

While starting a print off on the UM2 today, I noticed that the filament feed motor was skipping excessively.
It seemed to be a combination of problems; dirty nozzle (fixed with 6 cold pulls), ground filament in the bowden tube (removed and reloaded) and the filament guide piece that the filament loops through between the filament spool and the feed motor had broken off and fallen down the back.

I've recovered both parts, and it looks like this is a known problem that someone has tried to fix before, as there's evidence of super glue on the fracture surfaces, although it's not clear when.
 
The break point on the part is at the perpendicular join, where the main force on the part in use would not be well resisted by the super glue, so I've re-glued the part using polyeurathane, and tried to add an internal fillet to each side, to improve the robustness of the repair. 

While that dries, I've **borrowed the equivalent part from the UM2Extended, which will need replacing**. 

And it is entirely possible that the repair will not be sufficient, and we'll need a replacement anyway. Especially as the original shows signs of wear in the filament guide areas, so it's possible that the sideways force on the part is increased just because of normal wear in use.

**Comment by amcewen** [comment]
Organisers' meeting notes: @DefProc to check.

**Comment by amcewen** [comment]
Seems to be holding.  Closed.
