### ISSUE TITLE
Put together a training session around MicroPython and ESP8266

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#476]
@DefProc - following on from your comments in the organisers' meeting yesterday.

I made a start on a rough outline of what a MicroPython / ESP8266 training session might look like.

https://github.com/DoESLiverpool/wiki/wiki/ESP8266-Micropython-MQtt-Node-Red-Training-Session

Would value input on what else should go in there.

Cheers, Alex

**Comment by ajlennon** [comment]
Correct link -

https://github.com/DoESLiverpool/wiki/wiki/ESP8266-Micropython-MQtt-Node-Red-Training-Session

**Comment by aubergine10** [comment]
I'm very much interested in this - I'm currently starting to experiment with a Pycom LoPy board which uses it. I'll take a look this evening and provide feedback from complete newbie perspective :)

**Comment by cheapjack** [comment]
Im also well up for this really good to share all the stuff going around like the work we've been doing with @cefn for [cockle](https://github.com/ShrimpingIt/cockle) and cheap [screens for micropython](https://github.com/ShrimpingIt/micropython-st7920) for text adventures that @goatchurchprime helped me wire up last night and of course the stuff he was doing with the mains plug. All of us are building up quite a bunch of interesting resources that could be shared especially to non-programmers like me that can still enter into this stuff as easy as arduino/pi 👍 

Will watch this and try think of what would be nice to add to such a course; maybe different members of community could lead different sessions to demo stuff they've built and get people to make their own, if we did it like an ESP makerday or maybe a paid course? Maybe get a few people mistaking it for discovering your third eye...

**Comment by ajlennon** [comment]
Separately I'd also like to start putting together something similar but focussed on Embedded Linux (my experience being mainly with Yocto over the past decade).  I'm thinking maybe a similar starting format with background -> building something -> interesting use cases. Would be interesting to see what else we can pull in.

Will document that elsewhere at some point

Perhaps all of this also feeds into Liverpool MakerDay. I was chatting with @jackie1050 and am thinking of what boards might be fun to demo?

Maybe something out of the grab-bag here

- ESP8266 based E-Ink display running Micropython over wireless
- Small MQX RTOS Kinetis based display with image slideshow
- NXP i.MX6DL based larger display running Linux or Android with a spinny DoES logo?
- Kinetis MQX RTOS based Bin (depth) Sensor?
- i.MX6Solo based Camera module running Yocto Embedded Linux and streaming over Wifi (I'd really like to get this doing 360 video as there are two cameras on there but time may not allow)
- Something involving BLE and Beacons and phones/pads as that's always fun
- Can we do something with LoRA and The Things Network. @DefProc do we know if the Library will see TTN gateway at DoES?

**Comment by amcewen** [comment]
In relation to issue #462, would it be useful to have a couple of ESP8266 boards with Micropython on them in the Microcontroller Library box?  We could repurpose a couple of the ARDX kit boxes to give people some sensors/LEDs/etc. to work with too, if the training materials have a suitable parts list?

**Comment by aubergine10** [comment]
I've got several sensors and other bits and pieces (rotary switches, motors, etc) that I can donate.

I've taken the liberty of setting up a place to share example code: https://github.com/DoESLiverpool/code

I'll be popping in to DoES for an afternoon sometime in coming week to start going through the boxes to list what's in them.

What's the ARDX stuff about? There was mention of that in #462:

> However, it's probably only the ARDX kits that aren't in a "free to a good home" category, and they could do with tidying up and re-stocking so they're ready for people to use.

**Comment by amcewen** [comment]
Ah, sorry, the [ARDX kits](http://www.oomlout.com/a/products/ardx/) are ARDuino eXperimenter kits from .:oomlout:.

Basically a beginner's Arduino kit - Arduino Uno, breadboard, wires, LEDs, servo, temp sensor, etc. and a nice booklet with 10 starter circuits/code to get you up and running.

**Comment by goatchurchprime** [comment]
I could do this pretty efficiently now based on: 
    https://github.com/goatchurchprime/jupyter_micropython_kernel

It makes it possible to cover a lot of ground.  

But maybe the actual issue is a process for easily escalating a proposal like this into this kind of formal training event.  Either scheduled for a makernight, or a day.  Might provide more of a publicity hook to draw folks in on the regular scheduled nights.  I mean, I'm often in the other room carrying on with my hacking, and I quite like teaching people about something reasonably advanced -- if they are actually interested in it and are going to do it later.  

I'll put this up as a ticket.

**Comment by ajlennon** [comment]
Excellent. I think this would do very well under an IoT Liverpool meetup banner @DoeS

**Comment by amcewen** [comment]
Now there's an idea.  @goatchurchprime, would you be up for running it on Oct 25th?  We don't have anyone booked in for this month's IoT Liverpool yet... :-D

**Comment by ajlennon** [comment]
That's ages away. By then you'll have uLisp + Jupyter to show us I guess?

**Comment by jackie1050** [comment]
I had been thinking about a hack day using the ESP32s and lights etc. - but maybe we could get some extra volunteers for make:shift:do if we run something first as well ...


On 10 Oct 2017 11:41, Adrian McEwen <notifications@github.com> wrote:

Now there's an idea. @goatchurchprime<https://github.com/goatchurchprime>, would you be up for running it on Oct 25th? We don't have anyone booked in for this month's IoT Liverpool yet... :-D

**Comment by ajlennon** [comment]
We should build this into the forthcoming workshop @goatchurchprime

**Comment by goatchurchprime** [comment]
We got something done for the sensor-city presentation.  I think things are now gravitating around MQTT systems, where the individual nodes can be esp32 (or sonoff things)
