### ISSUE TITLE
wiki.doesliverpool needs deactivating

### ISSUE THREAD

**Issue by aubergine10** [DoESLiverpool/somebody-should#478]
Just randomly found this (via handbook on github which I'll update shortly):

http://wiki.doesliverpool.com/FrontPage

Can that be deactivated and the subdomain redirected to the main website (or a page on github that links to all the other wiki spaces)?

I don't have access to the server or DNS so can't do this myself.

**Comment by aubergine10** [comment]
@amcewen is the old wiki still on your personal account?

**Comment by johnmckerrell** [comment]
It has occurred to me that we don't actually need @amcewen to shutdown his system, rather we just need to change the DNS settings. I'll do something with this tomorrow morning if I get no complaints.

**Comment by DefProc** [comment]
I've just noticed that this will break a link on the somebody-should readme that directs to a page that hasn't been transferred: 

from [DoESLiverpool/somebody-should/README.md](https://github.com/DoESLiverpool/somebody-should/blob/master/README.md)
> Also check out the legacy "Somebody Should" list on the [wiki](http://wiki.doesliverpool.com/HackTheSpace) to see how we got started.

Link directs to: `http://wiki.doesliverpool.com/HackTheSpace`

**Comment by johnmckerrell** [comment]
I added a new pack to the wiki to reflect that hack the space page, updated the readme and have now taken over the wiki.doesliverpool.com domain, I've also put the does screens "api" onto that domain now. Waiting for DNS to propagate and make sure everything works before closing this.

**Comment by johnmckerrell** [comment]
Seems to be working, FWIW I've set up SSL on the domain too now.
