### ISSUE TITLE
Do a customer satisfaction survey

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#482]
We did one in 2011, I think we've done one since on survey monkey but not currently finding it, perhaps @DoESsean can help locate it.

**Comment by johnmckerrell** [comment]
Questions from 2011:

Timestamp	
What involvement have you had with DoES Liverpool so far?	
How often do you work from DoES?	
How often do you attend events at DoES?	
What do you think of the cost of a permanent desk?	
What do you think of the cost of a hot desk?	
What do you think of the cost of workshop membership?	
 [How important is a city centre location to you?] 
 [How important is parking to you?]
[What do you think of our current location?]	 
[How important are kitchen facilities to you?]	
[What do you think of our current kitchen facilities?]	
[How important are toiilet facilities to you?]	
[What do you think of our current toilet facilities?]	
[How important are reception services to you?]	
[What do you think of our current reception services?]	
[How important is internet connectivity to you?]	
[What do you think of our current internet connectivity?]	
[How important are hot desk facilities to you?]	
 [What do you think of our current hot desk facilities?]	
[How important are permanent desk facilities to you?]	
 [What do you think of our current permanent desk facilities?]
[How important is our suitability as an event space to you?]	
[What do you think of our current suitability as an event space?]	
[How important are meeting facilities to you?]	
[What do you think of our current meeting facilities?]	
What would you like us to do to improve our co-working (permanent desk & hot desk) facilities?
What would you like us to do to improve our workshop facilities?	
What would you like us to do to improve our event space facilities?	
Anything else you'd like to tell us?

**Comment by aubergine10** [comment]
If a survey hasn't been done recently, it needs doing again... Some other questions for consideration (all free-text answers):

* What's the main reason you keep coming back to DoES?
* If you were telling a friend why they should consider DoES, what would you say?
* What are the main challenges you are currently face in respect to your work?
* If DoES could provide them, what extra services would you be interested in?

Also, the order of the questions on the big list posted by John seems to be a bit chaotic. Could they be categorised in to sections? - eg. keep all the event-related questions together, keep all the hotdesk-related questions together, and so on.

I have time on my hands - if there's anything you want to offload on to me let me know. I'll be onsite from roughly lunchtime tomorrow (Thurs 27th) if you'd prefer to discuss in person.

**Comment by johnmckerrell** [comment]
Last done around November 2014, here's the link to that one: https://www.surveymonkey.com/r/TDG39JK?sm=%2bZLnw1kcD7biADukLNMAnQ%3d%3d

Yes definitely time for another.

**Comment by aubergine10** [comment]
Right, I'll have a bash at coming up with the 2017 edition this evening and post proposed questions in this ticket as I'm sure there will be other things people want to add or change.

Suggestion: Once question list is complete, review it at next organisers' meeting to give go-ahead to mailchimp and send.

**Comment by johnmckerrell** [comment]
Possibly more useful to get it out and review responses at the next meeting but I don’t know when that’s planned for.

**Comment by aubergine10** [comment]
**_First draft - based on 2014 mailchimp survey_**

> DoES are planning to move to new premises within the next few months, which means we have an opportunity to make some big changes that aren't feasible in the current location. As we exist to serve the community, we'd love it if you could help guide us to a future that's better for you by answering the questions below.

### Discovering DoES

**How did you first hear about us?**
* Internet search
* Facebook -- do we even have an fb page?
* Twitter
* Instagram
* From a friend
* At an event
* Other? _specify_

**If you were encouraging a friend to join or visit DoES, what would you tell them?**
_textbox_

**How do you rate our online presence?**
_Each item has 4 options: Epic, Meh., Grim, Not seen it
* Search engines
* Facebook
* Twitter
* Instagram

**Any suggestions for improving the way we promote ourselves?**
_textbox_

### Using DoES

**Which DoES services do you use (select all that apply)?**
_Options for each item: Previously, Currently, Considering_
* Hot desk
* Permanent desk
* Workshop
* Business registration
* Event hosting
* Event attendance

**What is the main way DoES benefits you or your business?**
_textbox_

**Are there other services or assistance that DoES should provide?**
_textbox_

**Is there something stopping you from using one or more of our services?**
_textbox_

### Improving DoES

**Is there anything you found out which you wish you knew about sooner?**
_textbox_

**We should start doing:**
_textbox_

**We should do more of:**
_textbox_

**We should do less of:**
_textbox_

**We should stop doing:**
_textbox_

**How do you rate the following:**
_options: Good, Needs improvement, Indifferent._
* Location
* Opening hours
* Pricing
* Look & feel
* Networking opportunities
* Internet speed
* Social interactions
* Hosting meetings
* Hosting events

**If any of the items above need improving, please elaborate...**
_textbox_

**Comment by aubergine10** [comment]
I think give it a few days for others to suggest edits.

**Comment by aubergine10** [comment]
Things that probably need adding to the draft above:

1. Ask about preferred payment methods as per #481 
2. Get more feedback on location wants

**Comment by stevesparrow** [comment]
Thanks Guy,

Sean and I had just agreed to do this, so it's great timing.  My contribution would be, that we;ve found generally that the shorted things are, the higher the quality of information we tend to get.  I'd quite like to shrink it to just a few things?  Some of that can be done, simply for example by bringing the 'Improving does' section from four questions to one with some prompts.

Don't let me stop this.  I'm just urging easy access for more and better results.

**Comment by aubergine10** [comment]
I'll shrink it down some more on Friday (or tomorrow if I can get access to a computer at DoES... and remember my github password...)

Can we target middle of next week for completion to give a little more time for edits and minification?

**Comment by aubergine10** [comment]
Trimmed survey:

> **What is the main way DoES benefits you or your business?**
> _textbox_
>  
> **If you were encouraging a friend to join or visit DoES, what would you tell them?**
> _textbox_
>  
> **Are there other services or assistance that DoES should provide?**
> _textbox_
>  
> **DoES is planning to move; do you have any concerns or suggestions?**
> _textbox_
>  
> **Any suggestions for improving DoES?**
> _textbox_

I know text boxes are a PITA to summarise when reviewing results, but in this instance I feel it's valuable to let people enter freeform responses.

**Comment by DoESsean** [comment]
I think it's probably worth revisiting this since the move, and, as @aubergine10  did a really good job on the questions, I don't see too much point in meddling unnecessarily. However, the move will have changed things slightly (or hugely in the case of the question about our upcoming move!), so does anyone have any questions they'd like to add or things from the above that they would definitely remove?

I'll give it till the end of the month and get this sent out via mailchimp.

**Comment by DoESsean** [comment]
I didn't give this till the end of the month.

So I'm giving it till the end of this month, and then sending it with whatever changes people deem necessary.

**Comment by DoESsean** [comment]
Done, sent to the Google Group, and posted on Facebook and Twitter.

For anyone that is really weirdly not on any of those, but is on here, [here's the link](https://www.surveymonkey.co.uk/r/NRS8GBF)
