### ISSUE TITLE
Give DoES a nice sprucing up before Makefest

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#485]
Although the main room has recently been organised better, and so looks a lot more welcoming, there is still work that could be done on improving the look of both the workshop and Dinky.

Would people be willing to give up time either on a weekend or an evening to help make this happen? And, if so, which is best?

Once we have an idea of when we might be able to get the most people to help, then we can get something in the diary.

Makefest is on June 24th, so that gives us a fair bit of time to get this done, but also a definite deadline - which is something we need!

**Comment by aubergine10** [comment]
I'm up for this. Weekend would be better IMO - I'm not sure how much can get done in a single evening. But it depends when people are available.

There's potentially a group from Transition Liverpool visiting on the 30th May as well (personally I doubt many will attend), but it's another good reason to tidy stuff up.

**Comment by aubergine10** [comment]
Cleaned the solder station this afternoon, will try and get back in tomorrow to tackle another part of the workshop.
