### ISSUE TITLE
build a printer to dispense "Eat Me" stickers in response to external stimuli

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#486]
On the basis that otherwise I have to print some more on Sophia's computer. Like a caveman. 

We do have an SLP thermal sticker printer, with a linux driver (thanks to @paulfurley): http://tinyurl.com/slp-linux-driver which could match to a RPi and a button, so a label would print with `Eat Me (since <date>)` ­— related to #236

**Comment by ajlennon** [comment]
What's the model number?

**Comment by ajlennon** [comment]
There's got to be a way of driving this with an ESP826 and Micropython

http://www.doss.com/Docs/SLP%20Command%20Interface%20Specification%20v2_4.pdf

**Comment by ajlennon** [comment]
Have no dear @DefProc. I have a plan which requires QR codes!

![image](https://cloud.githubusercontent.com/assets/1537834/25501195/c5b6d2a4-2b89-11e7-8b43-dd6853a8fe9f.png)

**Comment by ajlennon** [comment]
I can't see me having time to do this so closing
