### ISSUE TITLE
get a card machine for DoES

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#491]
breaking out the original issue from #481 

Set up the iZettle card reader I have with an account for DoES to try being able to take card payments on-site as a method of payment for desk/workshop/materials usage.

 - [x] get an iZettle account for DoES
 - [x] try an initial transaction
 - [x] make any recommendations based on usage
 - [x] get a contactless reader?
 - [x] procure a more permanent "till" device for any organiser to use (instead of re-pairing with each person's phone)
 - [ ] advertise that we have card payment as an option

**Comment by DefProc** [comment]
Initial usage worked fine. I've set up the set of products and services that DoES offers.

It does appear that to correctly match up any hotdesks/workshop/inductions, the cashier will need to add their name to the comments before taking payment, otherwise we have no integrated way to match these purchases with the actual user in our records.

**Comment by ajlennon** [comment]
You can use this link to add a custom QR code with any text you need....

http://nodered.dynamicdevices.co.uk:1880/qrcode?text=Alex%20Lennon

**Comment by DefProc** [comment]
![](http://nodered.dynamicdevices.co.uk:1880/qrcode?text=ValueChain)

**Comment by DefProc** [comment]
DoES now has a POS device (thanks to @DoESsean) which is paired with the iZettle reader, and set up for taking payments by card.

As the device is then handling payment information, and has the option to issue refunds, the device is pin-locked to limit the number of people with access (typically organisers). Pin unlock code in the usual place.

**Comment by DefProc** [comment]
We have a contactless payment device, and a phone paired to it for normal use. From usage, it's not recommended to use machine to process cash payments, as it's as much paperwork for @DoESsean as writing things down with the cash!

The only thing left to do now is to advertise that we accept card payments.

**Comment by DoESsean** [comment]
I've put this out a while ago when advertising our social streams and so on.
