### ISSUE TITLE
Deep clean or replace Sophia's lens after checking

### ISSUE THREAD

**Issue by euanwithersby** [DoESLiverpool/somebody-should#493]
Sophia's lens has a large deposit on the focal (convex) part of the lens that isn't coming off with isopropanol and cotton bud cleaning. I'm not sure if this is something that has been there a while and that the cutting problem isn't just an issue with temperature (the coolant was running at 26), but it appears to be preventing the laser from cutting through material correctly and there is also has an odd halo just behind the point of cutting.

The lens will need something more heavy duty to clean it (if appropriate) by someone with experience of this and, if this doesn't work a replacement ordered.

Timescale is ASAP if we have people booked in to use Sophia.

**Comment by DoESsean** [comment]
I'm not sure, but I _think_ we might have some lenses - we definitely have bought some before, and I seem to remember getting spares at the same time. Although there is every chance that I'm very wrong.

I imagine @DefProc will know better than anyone, so I'll assign this to him to make sure he sees it.

**Comment by DefProc** [comment]
Especially a worry, as I just did a clean #489 yesterday.

I'll check for a spare lens, otherwise it might be time to replace it.

**Comment by amcewen** [comment]
Organisers' meeting notes: Migrate this to a service list issue in same was as we have one for Gerald.

**Comment by johnmckerrell** [comment]
I cleaned the lens today and noticed the deposits, it seemed to do a decent job of cutting (almost mostly going through on 10/50, just needed popping out and leaving slight rough edges) and etching. Theres a small scratch on it too, I did wonder about just leaving it in some alcohol overnight to get rid of the deposits but don't know if that might damage the lens ultimately.

**Comment by cheapjack** [comment]
Old issue but we do now need to replace this lens as having cannibalised it to get Gerald up post move it's possibly causing issues.

We need to establish the focal length so we can order from smoke and mirrors or eBay as noted in issue #749

**Comment by amcewen** [comment]
The focal length for Sophia's lens is 50.8mm (and 20mm diameter).

**Comment by magman2112** [comment]
A new lens was obtained months ago and has been fitted. Closing this old issue.
