### ISSUE TITLE
Support RFID implants on the DoorBots

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#495]
Please make your issue:
* Specific

Initially the xNT tag which is 13.56MHz ISO14443A & NFC Type 2 NTAG216 chip

ref: https://dangerousthings.com/shop/xnti/

Q. Is this currently supported?

* Measurable

Success criterion will be using the implanted xNT tag to gain access to the office and workshop reliably

* Achievable

May require additional hardware and/or software on the doorbot(s)

* Responsible

Me (if it's allowed)

* Time-constrained

6 months (by end October)

**Comment by ajlennon** [comment]
Did some testing with @amcewen's Museum In A Box items and these tags are already supported with the DoorBots. Just need to find somebody foolish enough to get tagged now...

**Comment by aubergine10** [comment]
IMO it should be tweaked to specifically not work with RFID implants. ;)

**Comment by DefProc** [comment]
It uses the unique ID of the tag, so there's no specific mechanism for that. It works with any 13.56MHz RFID, including implants, credit cards, and mifare tags, stickers and cards.

**Comment by ajlennon** [comment]
Ignore any tag prefixed with 666 ?

**Comment by DefProc** [comment]
@ajlennon, but 0x029A isn't quite so obvious in hex

**Comment by ajlennon** [comment]
That was in hex :p

**Comment by ajlennon** [comment]
Wondering if we could have a brain wave reader in the new place so I don't have to be injected?

http://www.independent.co.uk/life-style/gadgets-and-tech/news/hackers-passwords-steal-using-brainwave-signals-a7817661.html
