### ISSUE TITLE
Is Sophia really an LS3040?

### ISSUE THREAD

**Issue by aubergine10** [DoESLiverpool/somebody-should#498]
On the Sophia wiki page: https://github.com/DoESLiverpool/wiki/wiki/LaserCutterSophia

It states:

> The DoES Liverpool Laser Cutter is an LS3040 from HPC Laser

According to HPC Laser website: http://hpclaser.co.uk/index.php?main_page=product_info&cPath=1&products_id=128

The 3040 looks like this:

![ls3040](https://cloud.githubusercontent.com/assets/1386719/25793043/1d306366-33c2-11e7-9718-f1cfa2075804.png)

Our Sophia looks like this:

![sophia](https://cloud.githubusercontent.com/assets/1386719/25793057/2e7ce306-33c2-11e7-9ab2-cae1c5069abd.jpg)

Which to me looks much more like the 3020:

![sophia](https://cloud.githubusercontent.com/assets/1386719/25793071/3e1fd692-33c2-11e7-87f7-196aabf09b2b.png)

See HPC website here: http://hpclaser.co.uk/index.php?main_page=product_info&cPath=1&products_id=92

**Comment by DefProc** [comment]
Yes, it really is an LS3040. It's about 6 years old now and the case has likely changed in the mean time.

The 3020 only has an A4 cutting bed and Sophia has a nominally A3 area

**Comment by aubergine10** [comment]
thanks!
