### ISSUE TITLE
Build a rack to store vinyl

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#50]
We should have a rack like the one in https://twitter.com/Dukestudioleeds/status/471749260049141760 to store the vinyl for our vinyl cutter - would make the workshop more colourful (and encourage more use of the vinyl cutter...)

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by goatchurchprime** [comment]
Vinyl now stored end on in two shelves under the vinyl cutter.  Seems to work okay,
