### ISSUE TITLE
bring the tea towels back

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#500]
Somebody (me) took the tea towels give to wash, washed them and forgot to bring them back today. There was one left in the kitchen yesterday, but it seems like it was used in the laser cutter somehow, so it's no longer food safe until it's washed, leaving us with no tea towels in the kitchen.

**Comment by DefProc** [comment]
Yay, 500 issues #weeknotes

**Comment by DefProc** [comment]
Phew, brought the clean tea towels back. We can now close this highly critical issue.

**Comment by ajlennon** [comment]
I can't wait to see what issue #1000 brings...
