### ISSUE TITLE
Gerald needs a 15mm belt fitting

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#501]
There was a fire in Gerald this afternoon.

He'll need:
 * [x] lens and mirrors cleaning,
 * [x] new tubing for the air assist fitting,
 * [x] new belt on the x-axis,
 * [x] checking to see if there's anything else,

We'll need to check through as to what else needs sorting, but wanted to raise an issue on it ASAP so that people were aware that he's out of action for a while.

 * [x] a thorough clean
 * [x] clean the bed of melted blue acrylic,
 * [x] review the fire extinguisher approach,
 * [x] refill/replace the CO2 extinguisher in the workshop,
 * [x] replace the window in lid (1040×640mm, 2mm thick polycarbonate(?)),
 * [x] unlock the power switch (when ready for service), 

1/6/17:

 * [x] Replace the 10mm, temporary x-axis belt with a 15mm belt

**Comment by DefProc** [comment]
Ok, I've done the check of the damage. It was our largest fire to date, and the CO2 extinguisher was deployed successfully to stop the fire. I've added the new tasks from my inspection to the list above.

Gerald will be out of action for at least a week while we replace some of the parts. I've blocked out the days so there's no booking slots available until next week, and @cheapjack is contacting and cancelling current bookings that are already made.

**Comment by DefProc** [comment]
I've ordered a 10mm wide open belt to replace the x-axis belt — there wasn't a 15mm option in the UK, so I still have to order a replacement for the slow boat from China to replace later.

**Comment by amcewen** [comment]
Any update on how things are going with this?

**Comment by DefProc** [comment]
Fixed (ish). We're still waiting on a 15mm drive belt that's on order from HPC. 

In the mean time, I've made a belt link for the 10mm MXL belt that was the widest I could order in the UK, and wasn't quite long enough for the axis.

![](mtp://[usb:001,011]/Internal%20shared%20storage/DCIM/Camera/IMG_20170601_115340.jpg)

This does mean that the travel of the x-axis is *slightly* reduced, although it doesn't reduce the practical area, as the red join (above) doesn't hit the drive cog until after the limit switch would trigger (if it was working). I've tested running in to the drive cog, and it doesn't seem like it will cause any damage, although I wouldn't like to do it for very long.

But Gerald is open for bookings again, and the belt joiner that I made is now [somewhere-safe](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/LaserCut/belt_joiner.svg).

**Comment by DefProc** [comment]
We diagnosed the cause of this fire as being because of having no air assist. 

As a result of the buildup of waste sheets under the cutter, some at the top had slipped off the back, and pushed the air pump plug (a US 2-pin plug vertically in an adaptor) out of the socket. 

With no air assist, the cutting produced more than the normal amount of flaming, causing the acrylic to burn.

**Comment by jackie1050** [comment]
The new belts are in the laser spares cupboard

**Comment by magman2112** [comment]
The new 15mm belt was fitted last month. Also, the current CO2 extinguisher in the wood shop has a reasonable charge at the magazines moment.
