### ISSUE TITLE
Event: Manchester MakeFest (19-20 August 2017)

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#502]
http://msimanchester.org.uk/whats-on/activity/makefest-2017

If we're going, then the application must be submitted by 11.59pm on Friday 26 May 2017

**Comment by DefProc** [comment]
Applied. I'll be away for the event, can anyone take ownership of organising getting DoES to this so it doesn't end up all last minute like last year? @jackie1050?

**Comment by jackie1050** [comment]
OK

**Comment by jackie1050** [comment]
@DefProc Could you attach a copy of the application please

**Comment by DefProc** [comment]
I don't have a copy (it was an online form) but I was vague enough that you should be able to take what you want. I asked for: 

 * WiFi required,
 * 2 plug sockets for mixed arduino/raspberry pi projects and laptops/networking equipment — max 10A
 * 2 tables with space for a 3m×3m gazebo

**Comment by jackie1050** [comment]
Thanks Patrick

________________________________

**Comment by SayBeano** [comment]
Is this still happening - just noticed it's closed, @stevesparrow ?

**Comment by stevesparrow** [comment]
Sorry, I was tidying up and misread the date as July.

**Comment by amcewen** [comment]
It happened.  We went.
