### ISSUE TITLE
Buy some new plastic weld solvent 

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#504]
There's only a small amount left. The stuff we've got at the moment is here: http://www.directtrainspares-burnley.co.uk/chemicals.html

**Comment by DefProc** [comment]
I think I got it originally on eBay

**Comment by euanwithersby** [comment]
Rennies on Bold St stocks Plastic Weld

**Comment by DoESsean** [comment]
Did this actually get bought? Or should I be looking to get some?

**Comment by goatchurchprime** [comment]
Nope, not been bought.  And the syringe that used to be in the carboard box with it has also gone missing.

**Comment by goatchurchprime** [comment]
@DefProc Do you have any info about that metal straw-ed syringe that was very good for applicating it?  We need a replacement.

**Comment by goatchurchprime** [comment]
This one comes with an applicator, but can't deliver.  https://www.amazon.co.uk/Plastic-Cement-Perspex-Acrylic-Styrene/dp/B01I5ORS1Q/ref=sr_1_8?keywords=plastic+weld+syringe&qid=1554456742&s=gateway&sr=8-8

**Comment by DoESsean** [comment]
This is ordered, should be with us early next week.

**Comment by DoESsean** [comment]
This has arrived and is in the solvent cabinet.
