### ISSUE TITLE
Report any instances of Sophia slipping

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#505]
Tried to cut out shapes, there was a slight grinding noise and the 2nd set of outlines moved by about 4mm from the first.

**Comment by amcewen** [comment]
Organisers' meeting notes: need to gather when it's happening, so leave comments here if you see it.

**Comment by amcewen** [comment]
I've had it happen quite a bit this evening.  It's the x-axis (when you're looking at the cutter) that's skipping.  Seems to happen only in certain places on the bed, so probably the belt being worn(?).  I've saved the problem file on Desktop/Problem-Cut-Files/505-skipping.ecp, it fails if you start it about a third of the way into the window, but is okay further over to the right.

**Comment by DefProc** [comment]
I'll remove the "broken" tag now status.doesliverpool.com is back online #515

**Comment by amcewen** [comment]
It was happening - between layers from the example I saw - to Alex T yesterday.

**Comment by huffeec** [comment]
I was getting a ghosting effect today on etches. 
![image](https://user-images.githubusercontent.com/4748179/30116413-6298740e-9315-11e7-90fe-24a8f685266a.png)

Possibly related to the belt issue from #565 ?

**Comment by jackie1050** [comment]
Slipped around 50mm last night on a line engraved drawing around 150mm in height

**Comment by Dowz77** [comment]
Drive belt has been replaced so i'll close this

**Comment by johnmckerrell** [comment]
Think we're best off re-opening this. @magman2112 was taking a look today and is going to order some V-gap wheels to try instead, it seems the wheels currently aren't connecting right so at speeds one of the wheels is dropping down and catching causing the motors to skip steps.

**Comment by magman2112** [comment]
A number of changes have been made to Sophia in recent months, including fitting a new idler wheel which is compatible with the new belt, along with replacing a faulty bearing on one of the carriage wheels - along with re-aligning the carriage.

With all of these changes, there have been no recent issues with Sophia slipping on the X-Axis, so I am closing this issue.
