### ISSUE TITLE
Finish the single line fonts

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#506]
The file to do it is in here:
    https://bitbucket.org/goatchurch/bbhquad/src/e91885ebc00d2fb3ecd8e6a5f964b3705bcf1d07/polarcode/svgizingtext.js?at=master&fileviewer=file-view-default#svgizingtext.js-92

**Comment by amcewen** [comment]
https://github.com/DoESLiverpool/wiki/wiki/LaserCutterInkscape#laser-friendly-fonts has links to an assortment of single-line fonts (and the link to http://imajeenyus.com/computer/20150110_single_line_fonts/index.shtml also talks about removing duplicate lines in them, which I think we've encountered as a problem in the past)
