### ISSUE TITLE
Add the 'What is DoES?' link to top nav of site

### ISSUE THREAD

**Issue by willcrobinson** [DoESLiverpool/somebody-should#510]
Last week, somebody asked me what DoES was and, in my infinite laziness, I was just going to send over a link to the about page on the website. However, it took me a few seconds to realise that the 'What is DoES?' link is tucked away in the side nav of the page.

To me, it feels like such an important page should be linked in the top nav, whether it's as 'What Is DoES?' or simply 'About Us'.

Anyone have any thoughts?

**Comment by SayBeano** [comment]
I think About pages as front pages.
One of the seminal websites that adopted this attitude is https://happycog.com they used to have a bit more information, "under the fold" so to speak. I think it was recent blogs / articles but it seems they've reduced the copy on the front even more howver you can still navigate the whole site from the links in the text block.

Theres a task to sort the website out #19 (I hope it's this one)- maybe the OP is related.

**Comment by DoESsean** [comment]
Is everyone else reading the title of this email to the tune of Haddaway?

**Comment by amcewen** [comment]
I am now...

Is this you offering to produce the parody song to that tune explaining what DoES is? :-)

**Comment by DoESsean** [comment]
Do we have a good music engineer? I'd actually do this so long as it ended
up sounding good. The last thing we want is a Montgomery Flea Market vibe...

**Comment by cheapjack** [comment]
Look at @epsaul 's desk he's got all the kit and a good voice

**Comment by willcrobinson** [comment]
In the spirit of DoES, I've produced a prototype http://vmashup.com/SflOi1ZG

**Comment by cheapjack** [comment]
I told adrian to wear waistcoat and no top for the ethos film but would he listen? Like the way the breakdown at 2.50 coincides with Julian coding with a head torch. Very 90s orbital.

**Comment by amcewen** [comment]
There will be a karaoke session at the #MakeFest afterparty, if anyone wants to practice... #justsaying

**Comment by shrkey** [comment]
> There will be a karaoke session at the #MakeFest afterparty, if anyone wants to practice... #justsaying

Suddenly glad I'll be far enough away to not be able to hear this :)

**Comment by ajlennon** [comment]
On 06/06/2017 11:41, Will Robinson wrote:
>
> In the spirit of DoES, I've produced a prototype
> http://vmashup.com/SflOi1ZG
>

My word that's good. Makes me want to take another desk.

**Comment by DoESsean** [comment]
This ties in to #19 so it's useful that @willcrobinson is part of the team heading that up :)

**Comment by johnmckerrell** [comment]
This this was pretty well covered by the web site redesign.
