### ISSUE TITLE
Keep Track of Payments Made in the Workshop

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#512]
There has been some discussion around how we can be more aware of when and if payments for workshop sessions are made by leaving money in the jar by Sophia.

Although we don't want to take away this option for people, as we like to offer as many ways for people to pay as possible, we do need to be able to manage it better to ensure that payments are logged against individuals accounts.

We currently have a couple of ideas about how this might happen, although they tend towards either making it slightly less convenient for users, which isn't something we'd like to do, or to needing technology building in.

Any ideas anyone has will be considered, so feel free to be creative!

**Comment by Pezmc** [comment]
Low tech pad of paper next to the box? With a few columns "name/what/cost"? 

Then if we ever needed that information digitally, someone could type it up and pair it with payments from other sources? Perhaps into a single central google spreadsheet.

**Comment by DefProc** [comment]
I've upgraded the collection points in the kitchen and workshop with the new collection tins, labelled "Food kitty" and "laser kitty" respectively. In addition there is now one each in the workshop and Dinky labelled "Event donations" which should hopefully separate out some of the usage. Although it doesn't stop workshop days being included in with the laser materials money.

**Comment by DefProc** [comment]
As an organiser, when I'm taking payments for @DoESsean to process, I record: 

 * Date
 * Person's name
 * Service
 * Total price
 * My Name

And include this with the cash. Although I don't know if all this gets recorded when it goes into the accounts.

**Comment by amcewen** [comment]
Generally I think all of that (bar your name) gets entered into the accounts.  That lets us match payments up against the door logs so we don't chase people for money they've already paid :-)

**Comment by DoESsean** [comment]
We now have a sign in sheet in the laser room which says to note down any payments you may make in the pot so that we can reconcile accounts. Very analogue, but hopefully it will bear fruit.

**Comment by DoESsean** [comment]
This _seems_ to be working so far. As their is no pressing need for an all singing, all dancing, technical solution, as well as no real drive behind creating one, I think we can consider this matter sorted.
