### ISSUE TITLE
Reorder labels for the Dymo printer.

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#514]
I have used the last label in the Dymo label printer.

Can we order replacements. 
89mm x 36mm (S0722400 / 99012)

**Comment by johnmckerrell** [comment]
Good chance there's some in the stationery cupboard in The Fridge. 

--

**Comment by huffeec** [comment]
@amcewen looked but there weren't any.

**Comment by DoESsean** [comment]
I've ordered labels from http://www.megalabels.co.uk/

They're compatible, rather than the Dymo proprietary labels, but are much
cheaper so worth a shot.

**Comment by DefProc** [comment]
Arrived yesterday, they're currently on Sean's desk, but I did find 2 rolls of dymo ones in the stationary cupboard.

**Comment by johnmckerrell** [comment]
Think that was a different size.

**Comment by amcewen** [comment]
What @johnmckerrell said :-D
