### ISSUE TITLE
status.doesliverpool.com throws "No route to host"

### ISSUE THREAD

**Issue by Pezmc** [DoESLiverpool/somebody-should#515]
It appears that the [node service](https://github.com/DoESLiverpool/status) hosting the status page is down. Nor does it (5.135.173.168) respond to pings.

- The server needs restarting/fixing
- We'll know we're good when the page loads again
- Is this @skos-ninja's responsibility?

```console
wget status.doesliverpool.com
--2017-06-13 09:42:54--  http://status.doesliverpool.com/
Resolving status.doesliverpool.com... 5.135.173.168, 2001:41d0:2:8c73::
Connecting to status.doesliverpool.com|5.135.173.168|:80... failed: Operation timed out.
Connecting to status.doesliverpool.com|2001:41d0:2:8c73::|:80... failed: No route to host.```

**Comment by skos-ninja** [comment]
Ah yes this is due to me forgetting to restart that service. Will sort that today.

**Comment by skos-ninja** [comment]
Fixed.
