### ISSUE TITLE
order new colour printer cartridges

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#519]
As it refuses to print unless *all* the colours have ink…

We have black replacements, bu the colours are empty too.

Ordered 3 sets to arrive tomorrow.

**Comment by amcewen** [comment]
Where from?

**Comment by DefProc** [comment]
Amazon: https://www.amazon.co.uk/gp/product/B06XSGS27Q

**Comment by DefProc** [comment]
Done, fitted, print heads deep cleaned. works lovely.
