### ISSUE TITLE
Dinky RFID reader not working

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#520]
Swiping RFID tag didn't release lock, although the red light came on (I did strip the blue wire before looking at the diagram and realising it didn't need to be connected).

**Comment by johnmckerrell** [comment]
I've just done some minimal debugging. The door wasn't online but a reboot has fixed that, RFID scanning is not showing up in the SSH session but manually opening the door does, so it's definitely a problem with the RFID reader.

Using the actual key which is in the locked cupboard continues to work.

**Comment by DefProc** [comment]
Have the wires come off the back of the reader again?

**Comment by amcewen** [comment]
If it turns out to be the reader I've got one we can put in service, as long as it gets replaced :-)

**Comment by johnmckerrell** [comment]
The wires are connected to the reader, I couldn’t check the other end at this time. As mentioned the red light still shows on the reader so it has power at least.

**Comment by amcewen** [comment]
@johnmckerrell and I had a look at it again this evening.  Seems that the green wire isn't connected properly - holding a new wire on both ends of where the green wire connects fixes things.  We haven't had chance to try any proper fixes yet.

**Comment by johnmckerrell** [comment]
I stripped and re-soldered the green wire and it's working again. I've made a replacement RFID cover as the old one was a bit small, it's yellow and gluing in the kitchen. Will fit it on Thursday if no-one else has.

**Comment by johnmckerrell** [comment]
When I got in on Thursday (29th June 2017) the door had stopped working again. I physically rebooted it at which point it started working again, I then also re-fitted the RFID cover.

Today (3rd July 2017) it's stopped working again, I can't SSH in so will have to physically reboot again, I'll try to check logs to see what's happened too but I doubt I'll get much, possibly the Pi is on the way out.

**Comment by johnmckerrell** [comment]
Quick update, it seems to be going offline repeatedly, I've rebooted a few times this week but not had chance to look at why. It did seem to be off the network but that shouldn't stop it functioning.

**Comment by amcewen** [comment]
Plugging a keyboard and screen into it, it isn't getting on the network.  Digging into it there wasn't any configuration for eth0, it was set to manual but without an IP address.  Changing it (in `/etc/network/interfaces`) to:

```
auto eth0
iface eth0 inet dhcp
```
seems to let it get on the network okay.  It did manage to forget that info once, but has been up for 20 minutes or so now.  So, something to keep an eye on before declaring this fixed...

**Comment by amcewen** [comment]
It survived a few hours, but was inoperable again today.

Looking at the screen that we'd left connected and tailing `/var/log/syslog` there'd been a kernel panic.  Rebooting the Pi it didn't get on the network, and didn't seem to have stored the log file with the kernel panic details anywhere :-/

So, running `sudo dhclient` seemed to get it back on the network okay, and I've left a `screen` running with `tail -f /var/log/syslog | tee /home/pi/paniclog`, in the hope that next time the kernel panics at least we'll have a log of it saved.

It's running at present, hopefully that'll be long enough for the cleaner to be able to get in.

**Comment by ajlennon** [comment]
Have you got reboot on kernel panic set? 

https://unix.stackexchange.com/questions/29567/configure-reboot-on-linux-kernel-panic

**Comment by amcewen** [comment]
I'd rebooted the Pi recently, and found that it came up okay but would kernel panic if you tried to do something complicated, like, y'know, typing the username in at the login prompt... :-D

So, I wondered if it was some corruption on the SD card.  To try that, I've written a new image to a new SD card (it's also built upon the latest Raspbian (Stretch).  That seems to come up cleanly, I've not tried logging in at the console, but the networking seems to work nicely.

Going to tentatively close it, and hope it's not reopened with a "this isn't working still" in a couple of days... :-)

**Comment by ajlennon** [comment]
So I should be able to get into Dinky now? Fantastic! If it's still buggering up I will take a look (promise this time)

**Comment by amcewen** [comment]
Yes, I updated the config file a week or so back, so all the recent tag IDs have been on it since then.  Assuming the networking holds up with the new build, once your implant is on the system it should get copied over just fine :-D

**Comment by ajlennon** [comment]
I think we tested it before didn't we so with a bit of luck it should "just work"(tm) !

A week or so ago. Shows how often I've been in recently! *cough* *cough*
