### ISSUE TITLE
run more courses from DoES

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#523]
eg. 

 * Laser cutting,
 * 3D design,
 * inkscape course,
 * …

**Comment by jamieisboss** [comment]
Are you talking about DoES running stuff as part of CIC things, or just courses being run by people, who might be charging the delegates? 

If it's the latter (or both) I've been thinking about doing some different stuff when I start working again and writing and delivering training courses is something I've done before (for Cisco and Cluster Learning) and I think I'd enjoy teaching DoES stuff a lot more.  

If you wanted it delivered "by DoES" , (or even delivered by DoES)   I'm sure we could work something out. Maybe the training could also be online, which I can also do. 

So yeah, I'm interested in being involved with this somehow, you should check I'm not making all that up I guess so If I were to give you a reference, it would be Sean, who probably arranged the final third of the work I'm referring to.  😉

**Comment by DoESsean** [comment]
Closing this issue as it is basically replicated, but more up to date, in #1248.
