### ISSUE TITLE
Create and employ DoES NoDs (Notices of Disposal)

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#524]
Please make your issue:

## Specific

DoES is moving premises in the not too distant future. 

There is a significant amount of kit which has accumulated over the years and some of which it would be helpful to skip or repurpose away from DoES to make the move more manageable.

Discussions with @amcewen indicate that best practice is to put a "Notice of Destruction" on items scheduled for removal. 

I suggest the following:

- We buy a sticker format in which is noticeable (e.g. hazardous waste or something)
- We go around items which can be scheduled for removal and stick these on where they will be seen 
  (initially the suggestion is the wall of boxes in the workshop as this seems low hanging fruit re: the move)
- We note down the date of each en-stickering and the item 
  (could be achieved with QR codes and a GitHub issue list as per the IoT Lending Library)
- After a period of time - suggest 2 weeks - the item is removed and placed in a "free for all location" for a period of 1 week. At this time people can take what they want, e.g. to repurpose
- After another week the item is disposed

In addition we could advertise the "free for all" location more widely for people from the wider community (e.g. upcycling and repurposing) to come and take a look

## Measurable

- Items to be removed will be seen to have stickers
- Items will be gone within 3 weeks or owners will have asserted items are in use

## Achievable

- The above is all achievable in short order

## Responsible

- (suggest) Alex and anybody else who wants to raise a hand

## Time-constrained

- If agreed can start immediately and first stickers to appear within the week

Thoughts?

**Comment by ajlennon** [comment]
So I designed a notice to print out and stick on things.

Can people feed back to me on anything that needs to be changed or added (yes I know it is missing a QR code (for now) )

Otherwise I'll start slapping these on things willy-nilly some time next week.

Ta.

![image](https://user-images.githubusercontent.com/1537834/28125734-65511b32-671f-11e7-89d4-bee075146b90.png)

**Comment by ajlennon** [comment]
@amcewen @johnmckerrell @DefProc @stevesparrow 

Ready to go with these now. Any thoughts, or shall I just put a 2 week hence (or more?) date on a batch and start sticking them around the workshop?

**Comment by DefProc** [comment]
It feels very important that the notice should have a link that explains what's going on and why. 

While I'm happy with the look of it, it's a bit like a parking ticket, and if someone finds one of these on their property without and reason of explanation, they are likely to be somewhere from "taken aback" to "really upset" that an unknown agent "just" stickered their mcguffin and so it's going in the bin...

**Comment by ajlennon** [comment]
A link to an explanation sounds a good plan.

I was going for something like the effect you describe so am quite pleased I've achieved that. fwiw my belief is that 

- it needs to be noticed immediately
- it needs to be acted upon quickly
- it needs to be understood that if it's not acted upon their kit is going to disappear.

Now I wouldn't want anybody to be "really upset" but I do think they definitely will be "blazing" if their stuff disappears without trace and they didn't know...

So that sort of comes back to the will to implement this policy in the first place...

If it is decided that it should be implemented then my vote remains for something that is quite in peoples' faces as a preference to being hauled over the coals for a softly softly disappearing act.

**Comment by ajlennon** [comment]
<thinks> QR codes !!! </thinks>

**Comment by ajlennon** [comment]
* Also I believe it would be incumbent to push details out on every avialable channel to existing DoES clientele to ensure they know what is going on and have a chance to act.

**Comment by amcewen** [comment]
Looks good.  Would "Disposal" be slightly less scary than "Destruction"?

There definitely needs to be a comms campaign to let people know that we're starting to enforce the "don't leave stuff lying around unlabelled or it'll get binned" rule.

To accompany the NoD signs, we should have "Do Not Hack" signs which people can attach to things that they don't want to be NoDed.

Nottinghack has [details of what info is on their DNH labels](https://rules.nottinghack.org.uk/en/latest/do-not-hack.html) (and for more background, this is the London Hackspace [dispoal process](https://wiki.london.hackspace.org.uk/view/Guide/Tidying_items_from_the_space))

**Comment by stevesparrow** [comment]
I saw this today and love it.  I'd like to start using them right away.  I'm sure we've agreed before that we need to have a clear out - so the how is the only issue.

Could we add a short-url perhaps to it, and and have a pdf so we can print some?

We discussed today that once I/we tag a bunch of stuff, we'll post them all up in one go on the mailing list, and here etc, to give people plenty of opportunity to see.

**Comment by ajlennon** [comment]
Glad you like it @stevesparrow.

Yes the file is an SVG for Inkscape and I'll put it into somewhere-safe.

Yes I can add a short URL and provide a PDF. I'll put that in somewhere-safe too.

I take on board @DefProc and @amcewen 's comments and it's clear that going about this the wrong way has the potential to upset a lot of people.

Is there an upcoming DoES meeting where we could add this issue to the agenda and come to a consensus as to what needs doing if this is to move forward in the best way possible?

**Comment by stevesparrow** [comment]
Thanks Alex,

That sounds good.  My concern about waiting for a meeting is that it delays, and we're good at the long gentle suffocation of good ideas that simply need to be done in some way.

Perhaps we could mitigate simply by

1) Making sure everyone know's the 'notice of destruction' is really part of the DoES, 'Don't be on fire' type approach, as well as a practical thing - and - 
2) Letting people know as widely as possible with pictures and some commentary on why, and what's happening - together with the link as Patrick suggests.  Maybe something like - 'Don't be alarmed - find out more here.
3) - A little courtesy in trying to work out who things might belong to and emailing them directly where possible (merging a little with my post about storage I guess.)

Would that answer/mitigate the concerns here @DefProc @amcewen?

Thanks :)

Steve

**Comment by ajlennon** [comment]
OK - I know what you mean wrt delay.

Actions:

I'll make changes to the SVG as per the comments above:

- change "destruction" to disposal
- create a page on the wiki explaining what is going on (unless somebody else wants to!)
- add a short link somewhere to that page
- check in and provide links to SVG and a corresponding PDF for people to use

Can somebody else own

- changes/improvements that will need to be made to the explanatory page I create
- informing the DoES community what's going on as you outline above

?

**Comment by amcewen** [comment]
All sounds good to me, and I'm on the "we should be moving towards this rather than waiting for a meeting" side.

Some people will have seen it in here, we should also post to the Google Group, and can send something out to the mailing list (mostly for party invites, but we'll have to disappoint people this time ;-) too.  Beyond that, there's not a lot we can do apart from try to ping people directly if there's anything especially valuable-looking

**Comment by ajlennon** [comment]
I've redesigned the D-NOD. 

- SVG is in somewhere-safe at [tr.im/21DId](tr.im/21DId)

- There's a single A5 PDF at [https://tr.im/1vgjT](https://tr.im/1vgjT)
- And a double A4 PDF at [https://tr.im/1evVJ](https://tr.im/1evVJ)

- There's a new informational place-holder wiki page [here](https://github.com/DoESLiverpool/wiki/wiki/Storage-&-Disposal-of-Items) waiting for somebody who knows what they're talking about to edit.

When I get a chance, and assuming somebody else hasn't, I'll put together a Do Not Hack (DNH) notice as @amcewen suggests above.

**Comment by ajlennon** [comment]
@stevesparrow 

> Could we add a short-url perhaps to it, and and have a pdf so we can print some?

I printed some out for you on the new colour laser and left them on your desk in case our ships don't cross for a while.

**Comment by DoESsean** [comment]
These have been (ironically) sitting around for a while, and I think it's worth starting to get them used. We can tie it in with a New Year's purge before moving.

Does anyone have any objections, and does anyone want to start slapping stickers on things?

**Comment by johnmckerrell** [comment]
These are in use generally and most of the stuff has now been moved anyway!
