### ISSUE TITLE
replace the toner cartridge in the laser printer

### ISSUE THREAD

**Issue by designfunction** [DoESLiverpool/somebody-should#529]
The small white printer is running low on ink. I didn't get a chance to look for a refill, so there may be one about!

**Comment by DefProc** [comment]
As we're happy with off-brand ink for the inkjet, I've ordered an off-brand toner cartridge for the laserjet.

The LaserJet M402dx takes:

 * HP 26X (CF226XD) - high capacity (nominal 9000 sheet capacity)
 * HP 26A (CF226A) - normal capacity (nominal 3000 sheet capacity)

I've ordered one of the high capacity replacements from Amazon, due tomorrow: 
 https://www.amazon.co.uk/Cool-Toner-Compatible-Cartridge-replacement/dp/B01BN566GC

**Comment by johnmckerrell** [comment]
Apparently the recycling people will take toner and ink cartridges so we can keep them handy for their next visit.

**Comment by DefProc** [comment]
Replaced.

Took me a little while to figure out that the error message `jam in the cartridge area` really meant `close the rear door` tho!
