### ISSUE TITLE
replenish the scalpel blades

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#530]
We're down to a low level of scalpel blades in the sharps drawer in the workshop. I've ordered 200 new 10A blades, and two more blade remover, sharps boxes from ebay.

 * http://www.ebay.co.uk/itm/280748721072,
 * http://www.ebay.co.uk/itm/201098520719

**Comment by DefProc** [comment]
Arrived, and in the drawer

**Comment by goatchurchprime** [comment]
Ran out of handles.  Have ordered 4 of these ones:  https://www.ebay.co.uk/itm/272304611682

**Comment by goatchurchprime** [comment]
@amcewen the order has come and has been tossed in the drawer
