### ISSUE TITLE
calculate pre-move & predict post move income

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#531]
Calculate the current income and per service type, to be able to model the effective income changes when adjusting the pricing structure. 

This is required to calculate out how any prospective price change adjusts DoES's income and predict how many service users, and at what level, DoES needs to afford any prospective new space.

**Comment by stevesparrow** [comment]
We've been on this for the last couple of weeks, looking at what we may need to do to sustain a move (see the recent blog posts). We'll email out the options we're looking at to members of the community shortly for comments.

Thanks.
