### ISSUE TITLE
Print some more tube clips for the UM2s

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#533]
In changing the filaments in the last week, it looks like the custom printed clip (#402) for the UM2 extended (Prince Adam) has got misplaced. Rather than just print one, I've just set off a print to make a set of replacements (both large and original size), so there are a few in case this happens again.

**Comment by DefProc** [comment]
Printed, fitted 2 and placed the rest in the "Ultimaker Parts" box. There are 5 each of the standard and increased thickness versions, all in orange.

**Comment by DefProc** [comment]
We've just lost another pair of these from the printers (on the head end, one from each printer) @amcewen and I have now replaced them, so we're down to 4 of each size. 

As we've had a few new users on the 3D printers over the last week or so, I'm wondering if this is a training issue. Although it's probably good that we can print replacements, as the actual cost to replace is negligible.

**Comment by huffeec** [comment]
@jackie1050 replaced broken one today (head end, Gerald)
