### ISSUE TITLE
The vinyl-cutter PC needs a mouse

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#535]
One of the workshop users has found just now that there's no mouse on the PC for the vinyl cutter.  Presumably it's been borrowed for something or other.

We need to either track it down and restore it to its rightful home, or get a new one.

**Comment by amcewen** [comment]
As a temporary fix we've borrowed @goatchurchprime's.

**Comment by ajlennon** [comment]
There are some cheap wireless ones in Home Bargains 'round the corner. There's a wireless keyboard + mouse for a tenner that I am using for things. Mouse even has a little dongle holder which makes me smile

**Comment by DoESsean** [comment]
Did the mouse ever turn up or are we still in need of one?

**Comment by johnmckerrell** [comment]
The PC appears to have a mouse, I just used it.
