### ISSUE TITLE
Open an online T-shirt shop to sell DoES merch

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#540]
Please make your issue:

Specific

- Sell T-shirts for money online to contribute to the DoES cake fund.
- Leverage an existing service for a start, e.g. [Spreadshirt](https://partner.spreadshirt.co.uk/register)
- We could upload designs to the shop as a collective (maybe also putting them in somewhere safe)
- Then makers could use them and/or remix them at DoES if they want to print, or elsewhere
- And people who just want a cool T-Shirt can pay online and it gets delivered.

Measurable

- Online shop set up 
- Some initial t-shirt designs in it
- New folder in somewhere-safe

Achievable

- Easy to set up
- Will people wish to put their designs up there? (I think so)
- Will people wish to buy t-shirts (I think so - there's no cost / downside to DoES )

Responsible

- Alex and/or anybody who fancies it
- @jackie1050 is this something you'd be interested in working with me on?

Time-constrained

- If people like the idea I'll set it up within 1-2 weeks

~~You can delete this template text.~~

**Comment by ajlennon** [comment]
![screenshot from 2017-07-20 21-39-09](https://user-images.githubusercontent.com/1537834/28437832-ff0c884a-6d93-11e7-8bfb-313912cc99b2.png)

![screenshot from 2017-07-20 21-33-28](https://user-images.githubusercontent.com/1537834/28437755-b4c785f0-6d93-11e7-8467-f5ac8eaf8ecf.png)

**Comment by willcrobinson** [comment]
"I went to Maker Night and all I made was this crappy T-Shirt"

**Comment by ajlennon** [comment]
I'm on it...

**Comment by ajlennon** [comment]
This issue has sparked a number of positive avenues of investigation, one being that [Sandbox Digital](https://www.sandboxdigital.co.uk) have a lot of experience with printing onto items at their maker space, and also offer a commercial printing service

> Just a little thought on the selling of tshirts. The Liverpool Print Company / the Nerdy gift company offers a service for selling tshirts / designs on their website for designers, artists, etc. They'd print them on demand and pay you your chosen mark up on a monthly basis. 

>http://liverpoolprintco.co.uk/merchandise-handling-service/ 

This seems far preferable to using an unknown online service so will note this in the upcoming wiki entry needed for #545 and I am closing this issue up for now.

**Comment by ajlennon** [comment]
![does do epic shit](https://user-images.githubusercontent.com/1537834/28821047-de49219c-76ab-11e7-960f-980eea11aef7.png)

**Comment by ajlennon** [comment]
I thought it stood for "really cool" ?
