### ISSUE TITLE
Improve the electronics parts-holding capabilties

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#542]
The "helping hands" on the electronics workbench were never great, and more and more are losing their crocodile clips.  We should have better tools to hold things while we're soldering.

We should make some of the [coolant pipe versions](https://www.thingiverse.com/thing:1876684) to replace them.

As a stretch goal we could redesign the pipe holder base so that it attaches to the PCB vice.

Once they're deployed, we can sort through the existing helping hands and bin the worst ones.

**Comment by amcewen** [comment]
I've ordered the pipes and clips for this.  

There are six hoses, so maybe if we 3D print one of the bases (from the link in the main description), we can look at a different design (either from a hunt round Thingiverse or from designing something to attach to the PCB vice) for three of them?

**Comment by DefProc** [comment]
And I do actually have the correct size tap for cutting/cleaning up the M14 threads that match the coolant pipe threads (I got part way through making a laser cut base with adjustable board clamps in the middle).

**Comment by amcewen** [comment]
The clips have arrived.  I've put them in the crocodile clips drawer in the metal drawers next to the electronics workbench.

I've also kicked off a print of the base.

**Comment by amcewen** [comment]
The hoses have turned up too, and screw nicely into the base.  However, the crocodile clips don't fit into the end of the hoses, so we'll need to work out a way to fit them (or if need be get some better crocodile clips - @DefProc has used some with a threaded mount rather than push-fit on the helping hands he's built).  They're currently in the corner of the electronics workbench (with three screwed into the 3D-printed base).

@goatchurchprime has offered to mill an aluminium base for some - with some dished areas on top to hold components.

Some 3d-printed mounts that go onto the base of the PCB vice would still be nice too.  I'll see if I can persuade any of the #makernight 3D-print designers to make something up for us.

**Comment by DefProc** [comment]
I used these [sparkfun crocodile clips from pimoroni](https://shop.pimoroni.com/products/sparkfun-third-hand-parts) for mine. It looks like they are an imperial screw fitting, but it fits exactly with the hose ends.

**Comment by amcewen** [comment]
I've ordered some of the clips from Pimoroni.  @Emmaemmaline is looking at designing the aluminium base for us (and hopefully we can steal some of @goatchurchprime's left over aluminium slab)

**Comment by Emmaemmaline** [comment]
Hi Adrian

Thanks for that! No pressure at all then!!! Actually Tom has taken over &
is printing out a base idea now!

Emma

**Comment by amcewen** [comment]
No pressure at all @Emmaemmaline!  Just acknowledgement and recognition of work :-)

The clips have arrived and are fitted to the hoses.

**Comment by Emmaemmaline** [comment]
Helping hands completed thanks to Tom Smith for 3D printing a pattern, & casting it  in aluminium. For information the screw threads are 1/4" BSP. not 14mm as in previous posts.
