### ISSUE TITLE
Create inventory for Made Invaders

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#544]
We could do with a list of everything that's needed when we take Made Invaders to events

**Comment by DefProc** [comment]
The canonical version of the pack list is at https://github.com/DoESLiverpool/made-invaders/blob/master/pack-list.md and I've just gone through and checked that it's up to date with this year's loadout.

You will also need a layout for the targets, which I haven't done yet.

**Comment by amcewen** [comment]
Made Invaders no longer lives at DoES Liverpool
