### ISSUE TITLE
Create wiki instructions & agree a consumables pricing model for the Ricoh sublimation printer

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#545]
Please make your issue:

# Specific

[Dynamic Devices Ltd](http://www.dynamicdevices.co.uk) is leaving a Ricoh 3110DN A4 sublimation printer at [DoES Liverpool](https://doesliverpool.com) on extended loan.

e.g. see [video here](https://www.youtube.com/watch?v=0dSnBXDIm3A)

It's anticipated that this will primarily be of use to the #wearables group and users of the workshop space, and should compliment the existing facilities for vinyl cutting and heat pressing for t-shirts.

The printer may be used for t-shirt printing with the heated press already available in the workshop. In future it may be worth considering purchase of equipment to support printing onto other items e.g. mugs.

## Process:

- design artwork
- print reversed image of artwork using 3110DN using the special sublimation ink in the printer onto the special sublimation paper that is needed
- place onto sublimation compatible t-shirt (i.e. high polyester content) in heat press
- close heat press for X seconds (probably about 40 but this will need checking)
- wear t-shirt proudly and follow [DoES Core Process](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Notices/DoES-3StepPlan-A1-stencil.svg)

> 1. Do Epic Stuff
> 2. **Tell People About it**
> 3. Go to Step 1

## Consumables

- CMYK ink cartridges see [here](http://www.mdpsupplies.co.uk/sawgrass-inks-ricoh.asp)
- Sublimation paper see [here](http://www.mdpsupplies.co.uk/sawgrass-paper.asp)
- T-shirts [here](http://www.mdpsupplies.co.uk/categories/dye-sublimation.asp)

Note that t-shirts must be sublimation compatible, i.e. **cotton t-shirts will not work** T-shirts must have a high polyester content for the process to work.

## **For discussion**

The ink costs are high. We may want to pursue an arrangment like the 3D printing charging model. As a start I need to try to work out an average per t-shirt printing cost, unless somebody has knowledge on this.

Also it may be unworkable to try to maintain a stock of different sizes, colours and styles of t-shirt. It may be better to try to organise a collective agreement for users to purchase and a trip to MDP in Bromborough (or delivery is free for > £100 orders)

# Measurable

- printer will be commissioned into workshop space somewhere or other

# Achievable

- commissioning should be easy.
- charging model needs discussion and thought.

# Responsible

- AlexL + ?
 
# Time-constrained

- printer in place by next week
- plan on consumables some time during next week or two

~~You can delete this template text.~~

**Comment by johnmckerrell** [comment]
I think it’s quite reasonable for us not to supply the t-shirts, so just a per-print price on ink and sublimation paper would do for this I guess.

How big is the printer? Is it much different (in appearance and operation) to a normal printer?

**Comment by ajlennon** [comment]
It's basically a normal smallish ink-jet. It does non-sublimation printing jobs but also supports sublimation inks. I don't anticipate we'd want to use it for any non-sublimation printing jobs though.

Details [here](http://www.mdpsupplies.co.uk/ricoh-printers-3110DN.asp)

**Comment by ajlennon** [comment]
To cover DoES we perhaps also need a sticker on the machine (with obligatory QR code pointing to wiki page) explaining clearly that DoES Liverpool does not countenance any use of this equipment that may infringe 3rd party intellectual property rights. (e.g. printing and selling t-shirts with unlicensed commercially copyrighted designs)

**Comment by ajlennon** [comment]
I found some details on working out ink pricing [here](http://sawgrasseurope.indigofiles.com/technical_support/costs/Cost_per_Print_Ricoh_3110.pdf)

**Comment by ajlennon** [comment]
Printer is installed and running on the network. 

The process was a bit more involved than I expected and more error and trial is needed.

But there is a placeholder wiki page up here to enable people to get going.

https://github.com/DoESLiverpool/wiki/wiki/Ricoh-3110DN-Sublimation-Printer-(T-Shirt-Printing)

NB. Discussions with @DefProc have shown there's a clear need to make sure anybody using the heat press or in the workshop when it is being used has had an appropriate workshop induction as it is potentially quite a dangerous piece of kit.

**Comment by aubergine10** [comment]
For wiki page, here's template: https://github.com/DoESLiverpool/wiki/wiki/Template---Equipment-Page

**Comment by ajlennon** [comment]
Hmm. Maybe you should add tags to pages which could be reformatted in the against a template, in the style of the way wikipedia does things

**Comment by ajlennon** [comment]
Hi @johnmckerrell. The IP address for the printer keeps hopping about. Could somebody have a look at the router and set it to something to something that doesn't change? Thanks!

**Comment by ajlennon** [comment]
Found an opensource coverage calculator [here](http://www.pykota.com/software/pkpgcounter/) which looks a useful starting point.

$ pkpgcounter -c CMYK bod_wordcloud.png
C :   8.352576%      M :   9.590505%      Y :  11.207828%      K :  80.487432%

**Comment by ajlennon** [comment]
IP address has been jumping around a bit but should be fixed now at 192.168.0.15

**Comment by johnmckerrell** [comment]
Could this be considered done now? It seems like we have some prices and a wiki page?

**Comment by ajlennon** [comment]
Has anybody managed to figure out if anybody paid for any consumables?

**Comment by jackie1050** [comment]
I asked around and believe that people have put money in the laser kitty for the consumables they've used (there is an allowance in the Make:Shift:Do budget for stuff used then).

Is there any way we can check the original assumptions against actual ink usage?  We can work out how many sheets of paper we've used - although a few did have to be used twice.

**Comment by ajlennon** [comment]
Hmm.  That sounds like a plan. I wonder if we can print a stats page? We should be able to see something shouldn't we.

Is it worth putting a money jar beside the printer to ensure consumables are funded out of printer use in future? And updating the wiki accordingly?

**Comment by DefProc** [comment]
There is a spare blue money jar that you could use. Probably somewhere
around Seán's desk.

**Comment by DoESsean** [comment]
The spare money jar was put in place next to the printer.

We also have a mug press and mugs now, so need to work out pricing for that. @jackie1050  also ordered some t-shirts, although she has said that she is happy to pay for them and sell them at cost if people want them, or use them herself.

It might be an idea to start thinking about charging a total price per item, so say £3 for a mug, which would cover the mug itself, the printing, and leave a little left over. We could look at a similar pricing structure for t-shirts and any other consumables we have.

People could still bring in their own stuff to print on, but it would give a very easy starting point for pricing and, if we do start to worry that people aren't paying correctly (which is a concern for me with regards to everything in the workshop), we could make it so that those consumables are kept elsewhere and are purchased as you receive them.

**Comment by ajlennon** [comment]
Can this be closed @jackie1050 ?

**Comment by jackie1050** [comment]
I don't think we have done this yet
________________________________
