### ISSUE TITLE
Website usability update

### ISSUE THREAD

**Issue by stevesparrow** [DoESLiverpool/somebody-should#548]
Will Robinson and I are taking a look at the usability of the website, and will be re developing the workflow over the next few weeks.  This would involve some limited content alteration, and mostly make use of what already exists.

We are not planning to make any significant changes to the design, and are focusing only on having an outward facing site, which more easily provides information people need as they arrive.  We're hoping this will make it easier to achieve as a limited goal. :)  We'll work first on the staging site, and will seek comments as we go.  One change we will be making, is to ensure that major internal links stay within the site stay on the site rather than github, and that github links are clearly labelled.  This is as a result of feedback, and I believe conversation on here.

There are two or three other open issues for the website, and I'm uncertain whether to close them and bring them here, and so I'm simply leaving them for the time being.  We'll use this thread to post updates and links as appropriate.

Please can I ask that no one make any structural changes to the site, whilst this is happening, as they will be lost when we upload the staging site, and will complicate and possibly delay the process.  Instead please feel free to make comments on here, or email Will or I.

Thanks
Steve

**Comment by DoESsean** [comment]
As there has been no discussion on the thread, and updates appear to have moved to #19, I'm closing this thread.
