### ISSUE TITLE
Fridge shelf has broken

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#549]
The bottom shelf has broken in half now making the drawers quite difficult to use.

I'm going to see if I can find the part to replace it (and the shelf in the door if I get that far) but if I can't then we might want to find some alternative, or may just need to remove it.

**Comment by johnmckerrell** [comment]
Looking on here:

http://www.espares.co.uk/search/ma466pt1545/fridges-and-freezers/shelves/daewoo?page=2

Found a few possibilities that are discontinued, would be best to confirm the model of the fridge first though.

http://www.espares.co.uk/product/es188471/fridge-vegetable-drawer-cover?pageNumber=3&PartTypeId=1545&ManufacturerId=466
http://www.espares.co.uk/product/es188472/fridge-vegetable-drawer-cover?pageNumber=3&PartTypeId=1545&ManufacturerId=466
http://www.espares.co.uk/product/es641849/fridge-freezer-door-shelf?pageNumber=2&PartTypeId=1545&ManufacturerId=466

**Comment by SayBeano** [comment]
I had this idea years ago but seems to have been sacked off #195

**Comment by johnmckerrell** [comment]
Ah yes, I searched for fridge but forgot to search old issues. I think it was only cracked before whereas now it's in two pieces.

**Comment by DoESsean** [comment]
And, as the old saying goes, if it ain't properly, completely broke, like
literally smashed in at least two pieces broke, don't try to fix it ;)

**Comment by johnmckerrell** [comment]
Hm.. finally got the model number, and even found part numbers were actually printed on each part but looks like most of them are discontinued anyway, have made an email enquiry so waiting to hear back on that one.


![img_5655](https://user-images.githubusercontent.com/27243/34484916-c8a6edb4-efbf-11e7-92e5-4c0908d9fb78.JPG)
![img_5086](https://user-images.githubusercontent.com/27243/34484917-c8c9d658-efbf-11e7-859c-e2b2807300e7.JPG)
![img_8835](https://user-images.githubusercontent.com/27243/34484918-c8f8b39c-efbf-11e7-89f7-c8b8141a4609.JPG)

**Comment by johnmckerrell** [comment]
Yes. I heard back from my email enquiry and doesn’t sound like replacements are possible. 

--

**Comment by DefProc** [comment]
A piece of a polycarbonate sheet from the workshop would be a more robust solution than acrylic. Although it won't cut in the laser.

**Comment by jackie1050** [comment]
Rob has cut 2 new shelves from a piece of10mm acrylic I had in my drawer. Hopefully they'll be strong enough

**Comment by jackie1050** [comment]
Note: We used acrylic because Rob didn't think we'd get a good result with polycarbonate using the existing tools. There should be less risk of breaking due to the thickness, and if it scratches badly we can replace with polycarbonate when we get a router.
