### ISSUE TITLE
Determine whether semi-skimmed milk or whole milk is healthier for coffee

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#550]
These guys have been looking at whether coffee raises blood pressure.

https://www.dietdoctor.com/does-coffee-raise-blood-sugar-conclusion

It might fit with a #FoodTech event @DoESsean to look at this type of thing, including whether semi-skimmed milk is better for us than whole milk (although ideally we might be looking at whether homogenised milk was better than pasteurised, or indeed raw milk)

**Comment by Xandertr0n** [comment]
Don't forget to include plant based milks as they lack Cholesterol and the saturated fats which are directly linked to high blood pressure.

**Comment by ajlennon** [comment]
Great point. I'm on the almond milk with my cereal
