### ISSUE TITLE
Investigate if anybody in the Liverpool area offers access to CE / UL emissions testing kit

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#551]
Please make your issue:
* Specific

Business generally needs to CE and/or UL approve devices for sale.

This can be a costly exercise. In particular if the device fails testing and then must be retested.

The facility to perform self pre-testing at a location would be a valuable service for innovators to assist them in bringing product to market.

Thus the first question is whether anybody in the Liverpool area offers this service (e.g. Sensor City)

If not, a next question may be whether DoES or Sensor City or a.n.other may wish to offer sucha  service.

A related question is what the kit would cost

* Measurable

Posts to be provided below from research

* Achievable

Yes

* Responsible

Alex and anybody who fancies investigating

* Time-constrained

Couple of weeks

**Comment by ajlennon** [comment]
A little more research.

There is a place in the south that SMEs can attend to do their own testing

The EMC Test Club - http://www.emctestclub.com

£495 + VAT to join or £107 a month.

From conversations with colleagues it can cost about £1000 a day to do approvals testing, for which you get a technician to help with the tests.

That will likely take at least a couple of days and if you run into any problems it can take much longer and become much more expensive.

It appears something of a black art.

To me a facility for SMEs to access equipment and a knowledge-base to perform CE, FCC, CCC, UL testing on an informal basis prior to formal testing could be a major benefit to the IoT and embedded engineering community.

Whether that is something it would be appropriate for DoES to offer, Sensor City to offer, or some other place I don't know, but I would like to explore this further a see a lot of upsides.

**Comment by ajlennon** [comment]
This is the kind of kit that is needed - http://www.laplace.co.uk/product/1/

**Comment by martimorta** [comment]
Maybe you could ask for prices to UK Electronics in Royton [www.ukelectronics.co.uk/emc-testing](http://www.ukelectronics.co.uk/emc-testing/)

**Comment by DefProc** [comment]
As far as I'm aware, pre-testing is a service that's accessible through sensor city (using one of the uni facilities). SMEs may be eligible for cost support through LCR4.0.

**Comment by ajlennon** [comment]
Yes I was hearing from Prof. Joe Spencer that this is something which can be done at Sensor City...

**Comment by ajlennon** [comment]
@DefProc do you know who I can talk to do get a complete list of what's available in the labs at S.C. ?

**Comment by DefProc** [comment]
@ajlennon I'm not sure who the first point of contact should be, I'll check for you.

**Comment by de14n** [comment]
So say we somehow get kit to do emissions testing, does that person need to be specifically trained and accredited to be able to approve and certify a product for the market.

I'm just wondering whether it's worth the cost of buying equipment when we'd need someone to issue a Declaration of Conformity. Surely the costs comes mostly from having an accredited expert interpreting the results in a controlled lab.

**Comment by ajlennon** [comment]
@de14n There is a talk coming up on this at Sensor City in Jan or maybe Feb. With a bit of luck the people from EMC Test Club (http://www.emctestclub.com/) may be coming up to discuss.

**Comment by de14n** [comment]
That's quite cool. I did three optional  modules on RF at uni and one was
specifically about EMC, but it was all very very intense theory. So it
would be cool to attend this. Is it free?

**Comment by ajlennon** [comment]
I would expect so but @DefProc is probably your best first port of call for info :) I'm hoping one of my colleagues will come up to sunny Liverpool to share his war stories about the black art of RF design...

**Comment by de14n** [comment]
Its not so bad once you sit down and digest the maths. It just gets quite
mathematically creative. I did Antenna design too, that's the blackest of
magic. Again, totally digestible with a lot of patience.

If anyone wants a book recommendation, the guy who taught me Antennas and
EMC in Uni wrote a book about Antennas that's pretty digestible. The EMC
course was basically application of the the same formulae we we got taught
in RF Engineering and Antennas but optimising for the EMC standards. It
becomes very nasty at times.

**Comment by martimorta** [comment]
Hi @de14n I am interested in the book. Thanks!

**Comment by de14n** [comment]
It this...

https://www.bookdepository.com/Antennas-Yi-Huang/9780470510285

The module was basically most of the book. And the exam questions were
based on the questions in the book.

I can borrow a copy from the uni library if you want (i have alumni
membership) a look. It's a bit pricey isn't it. Or you can have a copy of
my lecture notes which I kept.

**Comment by ajlennon** [comment]
Awesome. Would love to have a chat with you about this some time

**Comment by de14n** [comment]
I'm at the maker night now if ur still about.

**Comment by DoESsean** [comment]
As it appears we won't be looking to do this ourselves, and the question posed in the thread title looks to have been answered, I'm closing this thread.

If anyone wants to revive it to continue the discussion, or take that to the Google Group where it might enjoy wider notice, please feel free :)
