### ISSUE TITLE
publicise the upcoming pricing changes

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#554]
* Specific

As DoES is set to move, and is expecting to adjust it's pricing model at the same time, DoES should distribute the pricing model in good time to let current and prospective users know what their use of DoES will cost. 

Although work has been going on behind the scenes (reviewing pricing options, modelling pricing changes, and seeking input from the community), as a prospective move draws closer, DoES needs to create a clear pricing model in good time to allow current users to budget their access to DoES, and to be able to tell new users how they will be able to access the space in the future. 

* Measurable

Send pricing information out by website post or email announcement or website updates.

* Achievable

Yes

* Responsible

Directors

* Time-constrained

As a move is very likely in the next few months, this should be done as soon as possible to allow time in case of user feedback.

**Comment by stevesparrow** [comment]
Thanks Patrick,

Obviously we've discussed this at length a good few times and so you'll know the process and intentions, which are exactly as you say.  It feels like you're asking for an update?

We're currently on track.  We've had some useful responses (thanks everyone) which we discussed at a directors meeting on Tuesday, making some initial decisions, based on feedback, consistency and income.  We're asking the next organisers meeting to discuss these, and then we'll have a final decision, which can then be publicised as part of the move.  We're on the verge of signing the agreement to lease, which will allow us to be much more certain about everything, and so we'll confirm and broadcast these as part of that. 

Hope that helps everyone. 
Steve

**Comment by DefProc** [comment]
Reopening: I might have missed the announcement, but I haven't seen any public information about any price changes yet. It's probably best to leave the issue open if it hasn't been done yet, as it's a change associated with the move.

**Comment by stevesparrow** [comment]
By all means leave it open.  I closed it as 1) it's (as you knew) all in progress  and probably didn't need a 'somebody should' issue in the first place, and 2) as everyone else had had an opportunity to read it.  

I am little tired of the passive aggressive control games - it's gets in the way of doing real stuff.  Maybe we could find a better way.

Hope all is well.
Steve

**Comment by DefProc** [comment]
This is absolutely not a "passive aggressive control game", and I'm incredibly disappointed that I would receive and ad hominem attack, in a public arena, to what I believed to be a clear, reasoned response — particularly one where I had included a statement that I might be wrong to reopen the issue. :disappointed: 

As a flat organisation where the needs of the makerspace are shared with the community, isn't this exactly what the somebody-should issues list is for? "Publicise the upcoming pricing changes" is a task that is:

 * needed as part of the DoES Move, 
 * showed current progress and a upcoming intentions, 
 * wasn't yet complete. 

I'd much rather be able to point people asking questions like "what is happening to DoES's prices when you move" (which I was getting near daily by the end of July) at an open *somebody-should* issue with up-to-date information.

**Comment by stevesparrow** [comment]
I've only just seen this, apologies.
I think it is.  We should talk about this, as I'm really very tired of the whole approach.
Steve

**Comment by stevesparrow** [comment]
That said, you are right about this not being the appropriate forum, and I do apologise for that.

**Comment by DoESsean** [comment]
A suggestion at the organisers' meeting was that we give people an introductory sheet which would explain to people how much the space costs to run, and encourage them to donate if they can. This could also include an easy way for people to sign up to mailing lists, and tie in to any kind of welcome pack - find out people's interest, hidden skills, what they can offer to DoES.

**Comment by johnmckerrell** [comment]
Blogged here:

https://doesliverpool.com/co-working/announcing-our-new-home-and-does-membership/

We should send this to the MailChimp list and Google Group too, I'll do the latter and leave the former for @DoESsean

**Comment by DoESsean** [comment]
Mailchimp sent to the Announce List.
