### ISSUE TITLE
remove the swear word from the abbreviation that makes: DoES

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#555]
DoES currently stands for ***Do Epic Shit***, to be (and I'm paraphrasing @amcewen here) "a challenge to the city". However using a common swear word as part of DoES's description limits it's usage to time and company where swearing is acceptable. 

As DoES's intention is to be open and accessible to everyone, using swearing as a core part of DoES's identity goes against this intention and, as there is already a "work safe" version of DoES's meaning that is in common use: ***Do Epic Stuff***, I believe that it would be better to change the official version to match that.

As the usage of the original meaning is already limited based on situation (I prefer using *Do Epic Stuff* when explaining DoES to newcomers, and even new signage in the workshop uses *Do Epic Sh***) DoES should adjust the wording to be more welcoming and inclusive. And it would still possible to use the original by explaining that it "originally stood for Do Epic Shit" if necessary and appropriate in the situation.

*As an aside, the original also occasionally throws up some interesting misinterpretation when not heard clearly, I've had people mis-hear the original as **Do a pig shit** and **Do an epic shit** on occasion!*

**Comment by goatchurchprime** [comment]
I mis-read the title of this issue as part of some form of advertising.  "DoESLiverpool.  It's a place safe for work.  Not just for hacking and playing in the evening times."

**Comment by stevesparrow** [comment]
I never use the official name, and wouldn't want to be explaining it to anyone.  I've always assumed it's culturally appropriate for a community I've not really been a part of, but would happily not use it.  

Sounds like an opportunity for a conversation.

**Comment by jackie1050** [comment]
If all the letters were in the same case, they wouldn't have to stand for anything, but could still keep the history

**Comment by ajlennon** [comment]
DoES is pretty cool though compared to DOES ?

**Comment by jackie1050** [comment]
I know, and I’m definitely in favour of it staying as it is if possible

**Comment by stevesparrow** [comment]
Looking at it another way, we've never had any negacomments,

**Comment by stevesparrow** [comment]
Negative comments, we've had no complaints, and it's perfectly workspace in most workplaces.

I think it does have a cultural background, it comes from a context, and even if it's not mine, I have no issue with it being true to itself, especially, as we've said already, because there are lots of different ways to use it.

The only other comments here are in favour of the status quo, and no-one else is speaking up in favour of change, or giving reasons why it should. 

Does anyone else want to add anything in favour of change?

**Comment by stevesparrow** [comment]
Sorry, hitting enter on my phone.

Want to say anything in favour of change, before someone closes it?

**Comment by euanwithersby** [comment]
I've never had a problem with it. If an element of decorum was required, the S could always temporarily stand for Stuff - which is what @amcewen actually said to me the first time before correcting himself!

**Comment by stevesparrow** [comment]
Thanks Will, that's the fairly common practice - it seems to be a good
alternative. :)

**Comment by amcewen** [comment]
For the record, not overly surprisingly, I'm in favour of keeping it as is.

I'm also liking @stevesparrow's newly coined word "negacomments" :-D

**Comment by DefProc** [comment]
I did open this issue because it's a problem I have: I don't like to, and avoid where possible, using "Do Epic Shit" when explaining DoES to new visitors. This has been built up over the time I've been doing that, because it makes me feel unprofessional to use swear words when explaining a community and business to people I've never met before. #negacomment

I particularly brought this up now because:

 * the [Ethos Magazine video](https://youtu.be/h97Nzks-eDc?t=10s) which features Adrian (apparently) unhappy with describing what DoES stands for on video (I'm aware that this could be nerves, but it's not how it appears to me). The transcript (from 0:10 to 0:20) is:

> The kind of… the friendly one is: Do Epic Stuff. And the real one is… is a bit… erm… is is… Do  Epic Shit.

 * The [new instructional sign](https://twitter.com/amcewen/status/889772304267448320/photo/1) in the workshop — created by members of the community for use inside the space — uses asterisks in the swear word. 

If a founder of the community isn't comfortable using the swear word to explain DoES's meaning in promotion for the space, and community members have chosen to omit use of the word inside the space, shouldn't we follow the community's lead, and adjust the "official" meaning to match the current use?

**Comment by drfraz** [comment]
if you go back to the proto-Indo-European roots do can be seen as put, place or make & shit as skeyd or shed. 
So 'Make epic shed!' 
although stuff is derived from *(s)tewp- (“to push; prod; jab; stun; be amazed; hesitate; be irritated; stomp” which is also a good description of what goes on

**Comment by stevesparrow** [comment]
It'll sounds like it'll be decided tomorrow  - though the balance looks fairly clear.

**Comment by euanwithersby** [comment]
From my perspective, this is unnecessarily difficult. Simply have the external facing version as Stuff, I agree that it is a big professional hurdle to use a profanity when you don't know the recipient, the moment of decorum that I mentioned previously. For the community, why not stick to the original, asterisked if people want? It does reflect the DoES ethos and is unlikely to be a shocker for anyone who's spent any time around the community.

**Comment by ajlennon** [comment]
Couple more ideas...

Doing ebrious stuff (Drinking a tad too much - happy birthday to you!)
Doing ecclesiastry stuff (Church thing - we're not all Aetheists)
Doing ecdysiast stuff (Striptease - not whilst I'm in the office please)
Doing éclaircissement stuff (enlightening people, some of the people, some of the time)

The list goes on but I think you can see we have options :)

**Comment by amcewen** [comment]
The official name has always just been "DoES Liverpool".  There were ways you could find out where it came from, but they're not the name.

People are free to use whichever formation they prefer, or jokingly claim that it's "top secret" and you have to become a trusted community member before you find out.

@DefProc, to clear up your uncertainty over my performance in the Ethos video, how I played that was entirely deliberate.  Likewise, as the "community member" who laser-cut the sign in the workshop, I was completely aware of the option of "do epic stuff" and chose "do epic sh**" instead.  So in that sense the "official" line **is** following what the community does.

"Do epic shit" is a call to arms to work on meaningful things and to strive to do your best work.  It is a tiny bit controversial - it was chosen to be.  That doesn't mean it can't ever be changed, but also that it wasn't chosen on a whim.

**Comment by amcewen** [comment]
We discussed this briefly at the organisers meeting and agreed to leave things as is.

**Comment by DefProc** [comment]
OK, it was certainly worthwhile to bring this up from my point of view — and to know for sure that it's entirely reasonable to use the explanation that's most suitable for the situation; if (when) someone asks. 

Thanks.
