### ISSUE TITLE
MadeInvaders maintenance

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#559]
[ ] One cube needs a new acrylic panel
[ ] One cube isn't working
[ ] The RFID reader needs to be reattached to its box
[ ] Get some garage-type LED panels that could be attached to the inside of the gazebo during setup
[ ] Buy more RFID tags?
[ ] Buy more stickers? (none left)
[ ] Update the code to ask for event details on log on so we don't tweet old details
[ ] If possible, update the code so that the score depends on the Invader being shown

**Comment by amcewen** [comment]
MadeInvaders is no longer kept at DoES (and has been at events, so presumably the various issues with it have been fixed)
