### ISSUE TITLE
Gerald's computer needs Corel installing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#56]
At #makernight last night we couldn't use the vinyl cutter because Gerald was in use and so there wasn't a computer set up for it.

We tried getting a printer driver for it set up on Jackie's laptop, without any joy.  Next step is going to be trying hooking it up via a USB serial adapter (although we need to find the DB9->DB25 adapter that's currently fixed to the thermal printer).

In our playing around with it I happened upon http://www.securetech-ns.ca/camm-linux.html which looks like it might be a solution for getting it working with Linux.  Seems to only work with slightly older versions of Ubuntu, although it also seems there's a new version in the works which will presumably fix that.

**Comment by ajlennon** [comment]
@DefProc I installed X4 on Gerald-PC over the break and this is working from what I can see. I've made it more obvious by placing a short cut on the desktop. X5 is on there too but would need the license serial number to be found.

**Comment by ajlennon** [comment]
I'll close this down - please open up again if I have the wrong end of the stick
