### ISSUE TITLE
Investigate DoES merchandise for shows

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#560]
(From the organisers meeting)
Look into t-shirts, etc. for people at shows to wear.

**Comment by DoESsean** [comment]
@jackie1050 has had an idea about keyrings which would be combined with a QR code that would link to information about the move, etc.

**Comment by ajlennon** [comment]
Did somebody say QR code ?!?!

**Comment by DoESsean** [comment]
Since we now have our very own heat press, should we be looking at getting polo shirts or something that can be used at events?

**Comment by DoESsean** [comment]
Superseded by #891
