### ISSUE TITLE
Mill a soldering stand out of aluminium

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#562]
It's about 200mm x 150mm with a few recessed tray pockets and tapped screw holes.

It's a job to get the arcitype mill getting together on. (Currently the BB SD card is corrupted and I've mailed it off to Tom to get it fixed.)

**Comment by DoESsean** [comment]
Did the SD card get fixed?

**Comment by DoESsean** [comment]
We're a long way out from anything having been done at all in this issue. Is it still a concern?

**Comment by amcewen** [comment]
If you look at the electronics workbench (or see [the octopus in @zarino's tweet](https://twitter.com/zarino/status/1147819132160811008/photo/1)) you'll see that Tom cast us a nice one (which he's hammerited in blue) so this is fixed already :-)

**Comment by DoESsean** [comment]
I have no idea what anything is on that bench! Excellent stuff.
