### ISSUE TITLE
Create an advert to go on the 1st floor of the Tapestry building

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#564]
On Thursday there's the opening of the [Dead Pigeon Gallery](http://www.artinliverpool.com/liverpool-artists-cultural-leaders-come-together-exhibition-celebrating-coming-homes-first-great-year-reclaiming-homes/) on the top floor of the Tapestry building (the one we're moving to).  That means there'll be a load of people going up the stairs and past our new location.

It would be good to have some sort of sign announcing that we'll be moving there.  The easiest way would be to reuse the big A0 panel with the huge DoES Liverpool logo on it that we took to MakeFest.  That's in the storeroom off Dinky at the moment.

I'm thinking we should vinyl cut some text to go round the logo - there's room above and below it, or we could trim the foamcore with the logo on down and then hang another panel of foamcore with the vinyl-cut text on it below the logo.  I think that'll depend on how much room it takes, but we can play that by ear when prepping the cut files.

The opening is on Thursday evening, so we'd need to get the sign installed before then.  I'm working out a time we can get in to put it up with Jason, but having it ready to go before Wednesday would be ideal...

Copy-wise, I think something like...

Coming soon, the new home for...

DoES Liverpool logo

We're relocating and expanding our co-working and 
makerspace.  We'll be bringing our desks, laser-cutters,
3D printers, vinyl-cutter, sewing machines, soldering
irons, and awesome community here in November.

Join us!

http://doesliverpool.com           @DoESLiverpool

**Comment by amcewen** [comment]
Have spoken to Jason and it looks like a Thursday afternoon install will be best (which gives us a bit more time to get the sign made :-)

**Comment by johnmckerrell** [comment]
Worth installing the pull-up too? Would be good if the language made it clear we weren't some new upstart but a going concern moving in. 

--

**Comment by amcewen** [comment]
@johnmckerrell Agreed on wording it to show we're an existing org moving, rather than a new thing.  I'm not sure about the pop-up (although it hadn't occurred to me at all before you mentioned it) because (a) the exhibition runs for a week and I don't know how well it'd survive (/be out of the way enough) for that long, and (b) it feels a bit corporate in tone (which is okay next to a table full of more representative things, but on its own...?)

@huffeec has cut most of the text for it, but it still needs the contact details cutting from the blue vinyl (the file is on the vinyl cutter PC) and the rest of the vinyl picking out and then attaching.

Then @huffeec and I are going to install it tomorrow afternoon, around 3pm (in case anyone else wants to come along)

**Comment by huffeec** [comment]
The file that still needs cutting is on the desktop of Roland's PC, called comingsooncontacts.svg
I saved comingsoonblurb.svg there too because I lost an 'l' and and 'r' when I was weeding this text.
I'll be in to finish tomorrow before we install, unless some benevolent soul is able to share my weeding pain before then..

**Comment by SayBeano** [comment]
Looked good btw

**Comment by DoESsean** [comment]
Are there any photos of this? It looked good in the workshop, would be nice
to see it in situ.

**Comment by amcewen** [comment]
Don't you read the #weeknotes @DoESsean? ;-)

It was on Twitter and Instagram - https://www.instagram.com/p/BYv7y38Btbl/
