### ISSUE TITLE
Plan the room layout of the new space

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#571]
We need to get the room layout planned so that the contractors working in the space can prepare things like fire detectors in advance.

**Comment by johnmckerrell** [comment]
![tapestry-does-layout1-coloured](https://user-images.githubusercontent.com/27243/30856599-c2f904f8-a2b0-11e7-997a-2159e9085cd8.jpg)

Following intensive discussions we came up with this design. Ideally all walls would be full height solid stud-wall and plaster but the colour coding suggests:
 * Red & Yellow should be "secure" (full height, can't climb over them, will have a locked door)
 * Yellow should be see through in some way
 * Blue had the potential to be not full height
 * Green need to be sound proofed

This has been rejected as difficult to meet building regs, the rooms at the bottom left and right being within another room, so two doors to go through before you get to a fire exit, was highlighted as an issue.

**Comment by johnmckerrell** [comment]
[DOES.pdf](https://github.com/DoESLiverpool/somebody-should/files/1332858/DOES.pdf)

This was the first response from the project manager.

Features
 * Windows in all the rooms
 * Larger co-working area
 * Meets building regs
 * Five meeting rooms - Two small meeting rooms in the light well, two other rooms and the larger "private events" room.

Negatives
 * Doesn't consider the workshop
 * Only a single larger events space
 * People attending events have access to / go through the co-working space that will have people's property in

**Comment by johnmckerrell** [comment]
![does-floorplan](https://user-images.githubusercontent.com/27243/30857158-a7d42e6c-a2b2-11e7-9ac8-8164767dd786.png)

This plan came from opening the ideas out to the wider community at an "organisers meeting", it also responded to some of the project manager's building regs comments.

Features
 * Window in the events room which is also larger than previously
 * Lockable office that opens onto the central area, hopefully meeting building regs
 * No rooms within the co-working section, hopefully meeting building regs
 * Allocated smaller workshop and walls within the main workshop to break up space without blocking into separate rooms.

Negatives
 * "Town square" area has been downgraded to just a larger kitchen area
 * Pillar in middle of lockable office ;-)

**Comment by zarino** [comment]
> Pillar in middle of lockable office ;-)

Yeah, I only noticed that after I’d sent you the image! The office is probably big enough that it could stand losing a metre of length, to incorporate the pillar into its wall.

Do you think the two meeting rooms directly behind the office are big enough for one to serve as the user research lab?

**Comment by zarino** [comment]
Another iteration, based on discussions in the space yesterday:

![screen shot 2017-10-13 at 13 49 28](https://user-images.githubusercontent.com/739624/31546942-5d81a3ee-b01d-11e7-9d5d-0b071eacfe48.png)

There are no rooms within rooms. All rooms open out onto an open circulation area with a fire exit.

Dashed lines indicate some sort of light-permeable wall (like glass, perspex, translucent plastic, or wire mesh, dependent on the requirements of the particular wall) or a stud wall with a light-permeable section.

The event space is smaller than previous plans, but I’ve suggested sliding/folding doors between it and the meeting room behind, allowing us to combine the two rooms for large events.

Creche has been renamed "Private meeting room", for avoidance of confusion ;-)

Questions:

* Are the dimensions of the soundproof room (user lab), and lockable office sufficient?
* Is there sufficient walkway space between the soundproof room and the lockable office? By my reckoning, it’ll be about 130cm wide.
* Is the coworking space large enough? If we re-use the existing desks from Gostins, how many will fit into this new space? Is there space for _more_ desks?
* We didn’t mention it at all yesterday, but I’ve assumed there needs to be a lockable door preventing access from the open circulation area and toilets, to the workshop (eg: when events are happening in the main space). Is that correct?

**Comment by jackie1050** [comment]
Spoke to Bob about storage yesterday - I'm a bit concerned that with nothing specifically planned, stuff will get piled up against walls that really need to be kept clear.

But generally this seems to fit most requirements ...

**Comment by DefProc** [comment]
@zarino From the conversations that happened earlier in the year, there is a ballpark figure for area per desk at the current density in the main room of 50sqft per desk. Although it's not accurate, it might give a guide to possible desk numbers for a room.

Although I've not been active recently in discussions, I have been following the layout emails and issue, and there are a few things that have caught my attention:

 * I'm quite intrigued that the main entrance to the space - and the first thing that a new visitor would see when they first come in - has consistently been the kitchen in presented layouts (which in the current space has not always the most visually impressive part of DoES) is there a reasoning behind that?
 * I'm a little concerned about the amount of unused (not chargeable - ie. not desk or workshop space) that remains, is there enough space in the office areas to hire out and enough space in the workshop to have the tools to attract users to pay the rent? 
 * Is there a list of requirements that DoES needs/wants to have in the new space? Something we can objectively compare the effectiveness of a layout against? eg. How many desks in the main room, how many meeting rooms, what amenities etc.

**Comment by johnmckerrell** [comment]
@DefProc requirements can be found here: https://docs.google.com/document/d/1zmGn30pPTwisNk8IgmCJ_wVjZblk_ZMFJqx_cHmnGgU/edit?usp=sharing

We've pretty much hit all the "essentials" and not done too badly on the "desirable" and "good" (although I haven't specifically checked the numbers for the desks, that's more of a hunch that would be good to test).

It's definitely an interesting point about the kitchen, the idea with that is that it's a break-out/relaxing space that can be used by people who are there for an event. It needs to be on the "less secure" side of the space (i.e. accessible by people in the workshop or at events, who can't get into the more secure desk area). We've considered putting it in one of the light wells at multiple times but generally the feeling has been that these would be more useful as meeting areas. Also people end up hanging around and chatting in the kitchen, we don't necessarily want it tucked away (or tiny).

This most recent layout is certainly a bit corridor heavy but at least in the workshop we were trying to wall off space for metal work and wood work and with the shape of the spaces and the size of the windows there's not a huge amount of choice (although happy to consider alternatives).

@zarino I don't know if you noticed that on the 2nd plan I posted on this issue it does actually show the doors for the toilets so putting the sink in the location you've put it will work.

@jackie1050 yes, definitely need to be careful about storage, for non-workshop related there's probably plenty of walls, especially on the bottom right, for stationary cupboards and similar. Perhaps much of the "DoES" storage on the 2nd racking off Dinky could be moved into these areas in closed cupboards. Within the workshop, there's definitely room for 2 sets of racking, so that would be double the amount of paid-for storage that we currently have. We'll probably also need to be more careful about what we let hang around.

**Comment by zarino** [comment]
Spurred on by @DefProc’s kitchen comments above, I had a few attempts at putting the kitchen on the _back_ wall (next to the emergency exit) since that was one of the other areas that would be fairly easy to bring pipes to (from the toilet block), and wouldn’t result in a kitchen tucked inside a small room of its own. But whatever I tried, I couldn't hit on a layout that didn’t result in either 1) a windowless event space, 2) windowless coworking space, or 3) a coworking space no bigger than the main room in Gostins.

If someone else can think of a way to move the kitchen to another wall, without compromising other requirements, then let us know! 

Alternatively, we could leave the kitchen behind you and to the left as you walk in, but build a small wall between it and the entrance, for notice boards and stuff, that would double up as a way to shield the kitchen from sight until you’re properly in the space…

![screen shot 2017-10-16 at 09 20 47](https://user-images.githubusercontent.com/739624/31601920-54e6dfdc-b253-11e7-8674-da7ce4040895.png)

**Comment by johnmckerrell** [comment]
Just while I think of it, discussing it with Bob just now it occurred to me that having "user stories" for this might be useful. It would probably be best to put them on a wiki rather than here but I'll just drop an example here for now, e.g.:

As a Monthly Desk User
In the evening
When Maker Night is on
I want to be able to access the toilet and kitchen without having to perform any extensive locking up of the co-working area.

(This was an example to resist the idea of a drop-down shutter) (I don't really know if this is the right language for user stories!)

Just wondering if this language could be more illustrative than the simple requirements list of, e.g., "lockable co-working area".

**Comment by zarino** [comment]
Knowing _why_ somebody wants something is often the most useful thing. So:

**As a** permanent desk renter
**I want** my desk to be out of public reach when events are happening
**so that** people attending events can’t just walk over and steal stuff off my desk

Often the "I want" will be a solution the user themselves have come up with, and might not _really_ be the most effective solution to the problem. Which is when the "so that" comes in handy, because at least then you can see what the underlying problem is.

Danger here is that we’ll just end up with a hundred user stories, and be no closer to satisfying any of them. But if you think we’ve got time for this, then I guess we can give it a try.

**Comment by johnmckerrell** [comment]
I was just writing down the idea because I definitely didn’t have time to do anything further about it right now ;-)

**Comment by DoESsean** [comment]
@DefProc Since I think the main driver behind the kitchen being out in the open was originally me, I should probably explain my thinking.

It seems that, like with any good party, there tends to be a lot of congregation in the kitchen, and that can lead to a) congestion, and b) it feeling a bit awkward if you walk in there and people are having a slightly more private discussion. The kitchen is an area that everyone needs to be able to access, no matter what you're in DoES for. With those things in mind, I thought it made sense to have a more open plan kitchen/gathering area with a table, some nice chairs, etc, that both opened out the space to alleviate congestion, and gave people somewhere a little bit nicer to congregate and chat. My thinking is that, rather than stand next to the cupboards, people would move to the seating area and have their conversations there.

My thinking has always been that this would double up as both a nice relaxing place for people to hang out, and also somewhere where we could have displays of the work that is produced in DoES, making it a nice place to greet guests, and also something interesting as your first impression of the space. 

I do appreciate what you say about it not being the most visually impressive area, so we'll have to police the tidiness and cleanliness a little more, although hopefully that will happen organically* as it won't quite have the same 'out of sight, out of mind' thing that it does right now.

*You've got to have dreams.

**Comment by johnmckerrell** [comment]
![img_9751](https://user-images.githubusercontent.com/27243/31673578-7ec2477e-b357-11e7-9517-aa538479f013.jpg)

This is an alternative that Bob is working on (with further updates to come). Having the events room in that top right space could work quite well for security, at a push (e.g. an evening event that we can't cover) there would be no reason for members of the public to enter the main space (they would use the toilets downstairs, perhaps the event organiser is allowed to go into the kitchen and serve drinks through a hatch).

I think it's unlikely that we will be able to put a corridor through the left hand light well but we'll look at that more tomorrow.

I'll probably post a further update on this one later today.

**Comment by huffeec** [comment]
This is a list of the measurements I have for the larger workshop items that will need to fit.

Gerald - Including frame and chiller 1830mm x 1600mm
Sophia - On the current set of drawers 980 x 1330
Large band saw - 660 x 500
Heat press desk - 880 x 800
Metal storage shelves - 2530 x 900
Component carousel - 650 dia
Metal drawers - 350 x 460
Metal framed cupboards/drawers (under worktops)  1000 x 550
  6 in total. 3 as single cupboards, 2 as a double cupboard and one as drawers
3d printer x2 - 500 x 350
Knitic 900 x 400
Desks 1600 x 1200 (shorter depth after curve 800) 2 left hand sided 2 right hand sided.

(I thought I'd seen a reference to this somewhere but can't find it now, this feels like a useful place for it to go)

**Comment by johnmckerrell** [comment]
Noticed I said I'd post a further update. We need to get a more prepared version together but we're thinking something based on that last drawing could be the one. We won't break through the light well, instead sticking with the corridor on the left and we'll probably keep the kitchen out of the light well too. This is not to say we've hit the final plan and no changes are coming but this it looks like this is a strong direction we're heading in.

**Comment by zarino** [comment]
> We need to get a more prepared version together but we're thinking something based on that last drawing could be the one.

@johnmckerrell Something like this.

![screen shot 2017-10-19 at 09 35 02](https://user-images.githubusercontent.com/739624/31761726-da0b387a-b4b0-11e7-865f-9a2ab438fcaf.png)

Apologies to Bob if I’ve got some of the finer details wrong, but this is roughly how it was looking in my head when I left you two yesterday afternoon.

I’m just guessing at the arrangement of the dirty workshop spaces in the top left, but it sounds like Bob was thinking of two rooms, connected to each other, and also to the open space leading from the toilet corridor. I’ve also just guessed as to the position of all the doors.

For those following along at home, the 4 staggered lines between the kitchenette and the co-working space are large, full-height sliding doors, which will be opened up first thing in the morning, and then locked again at the end of the day.

The lockable door between the kitchenette and the office is a fire exit, to satisfy the "no rooms within rooms" requirement. We expect most day-to-day traffic will instead flow through the door into the co-working space.

**Comment by DoESsean** [comment]
So how would these 'Clean Workbenches' work? As far as I can tell, you
would have 3d printers and electronics bench in that area, as everything
else (at least that I can think of) would have to go in the 'Dirty'
workshop as they create dust/mess. The problem being, there are no walls
for these benches to go along - it would seem really strange to me to have
workbenches on the meeting room/soundproof room, and there wouldn't be
space anywhere else. Meaning everything would just be loose in the middle
of that space which people would have to walk through to get to a) those
two rooms, and b) the toilets.

On top of that, it massively eats in to the communal space that has been
part of every plan so far, and which would be in use for events, parties,
etc.

I'm willing to go with whatever consensus ends up being, but this just sits
really weirdly with me.

**Comment by SayBeano** [comment]
I liked Bob's plan from the photograph above. Where the kitchen (I appended appliances) was in that small room and there was the square.

Any grease, steam etc from the kitchenetteis going to spread around the space. Think openspace appartments where the livingroom and kitchen and dining are one. They're gross. Remotes end up clogged. Smells settle into materials. I'm concerned about the "clean workbenches".

Most of the spaces I've been stash the kitchen away. Although they usually have hot beverage facilities, not kettles per se, out front in the co-working area.

**Comment by johnmckerrell** [comment]
@SayBeano I'd expect grease to only be a problem if you have a full kitchen, we're still only expecting to have similar equipment to what we have now, microwave, sink, kettle, coffee maker, hopefully a dishwasher and we don't have issues with grease in the current kitchen.

**Comment by zarino** [comment]
Another version, where the permanent desks go in a large lockable room, across from the (also lockable) event space on the south-facing side, and everything else goes into the north-facing side:

![screen shot 2017-10-24 at 14 13 51](https://user-images.githubusercontent.com/739624/31945019-e00f0c88-b8c5-11e7-98c5-792c39369e21.png)

**Comment by zarino** [comment]
Good suggestions from @DefProc and Bob:

* Put the 3D printers in a *super visible* location, so you can see them as soon as you walk into DoES. They’d look super cool.
* Put the laser cutters out in an open area (rather than in a small room) – they’re constantly busy, they don’t generate much dust, and they’re a big selling point for DoES, so again, it’s good to have them visible.

**Comment by johnmckerrell** [comment]
And it’s the ventilation fan that’s noisy on the lasers but it can be anywhere along the ducting so doesn’t have to be in the main room.

**Comment by johnmckerrell** [comment]
My feeling is that we should send this to Jason soon at the least for a check-over that we're not missing any building regs issues, but I'm actually pretty happy that this could be the final plan. (And for the record I'm still not convinced on sliding doors on that wall!)

**Comment by jackie1050** [comment]
Get Outlo<https://aka.ms/ghei36>

**Comment by ajlennon** [comment]
I like the idea of visibility for the equipment. 

But I do worry about potential noise issues for people trying to concentrate?

Also we to tend to set things on fire in the laser cutters from time to time. The fire risk and a cross-office post fire haze would be a potential worry for me here...

**Comment by johnmckerrell** [comment]
I've been thinking about how originally we didn't have Dinky and we would actually hold meetings in the main room, at the time Martin, myself and Adrian would just try to keep our desks tidy (lol) and accept the small level of risk. This is definitely different as people can come into the workshop when there's no organisers around but then these people also have a level of trust so perhaps we can get monthly/permanent people into that main room.

Yeah I see acrylic or as you say, inappropriate, fumes could be an issue, we don't have much luck enforcing the "2 minutes before opening" rule". I'd imagine we would put the lasers in a room with a bandsaw (or the CNC) for now and when we get more equipment re-evaluate. Yes I know we might be getting a 3rd laser now but I think this can go to Jason now even if rooms need to grow.

**Comment by jackie1050** [comment]
Me too
________________________________

**Comment by johnmckerrell** [comment]
This was a potential arrangement of desks, it tries to get the maximum number of desks into the corner room.

[DOES - No4_with Desks.pdf](https://github.com/DoESLiverpool/somebody-should/files/1437639/DOES.-.No4_with.Desks.pdf)

**Comment by johnmckerrell** [comment]
"Having now had an opportunity to review the Building Control Officer’s comments we can confirm that he had no comments to make on the Does layout"

🎊🎉🎂🚀

Closing this ticket, and will shortly spawn many more!
