### ISSUE TITLE
OfficeJet-7510 needs new ink cartridges

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#572]
The error message was not clear about what colours it's down on, where to get the ink from, or how to fit it.  

I have updated the broken link (thank you HP) to the printer on this page:
    https://github.com/DoESLiverpool/wiki/wiki/OfficePrinters

Need to insert details of what cartridges it needs, how much they cost, where they are stored, and how to replace.

**Comment by goatchurchprime** [comment]
There's even racks of ink cartridges for sale in the Tescos next door, but I don't know which one to buy if I am in a hurry and can't wait for a cheaper internet supply

**Comment by amcewen** [comment]
This issue list is your friend :-)  

Searching the closed issues for "ink", I found #519 which is when we last ordered cartridges, which includes a link to where we got them.  So we can order some more.  (This is why we record such details, people :-D)

However, given we bought a few sets last time, there could be some spares.  In the stationery cupboard maybe?  Updating the wiki will be a good idea once we've located where they're stored (I can't remember exactly, and am not in the office to check)

**Comment by ajlennon** [comment]
You could use QRCodeifier to print a label to stick on the cartridge with a comment and a QR code on it pointing to the Wiki page that links to the consumables details... :-)

**Comment by amcewen** [comment]
There are two more full sets of cartridges (in brown cardboard boxes) on top of the letter trays on @DoESsean's desk.  @johnmckerrell is replacing the black cartridge (there was a spare one of those aside from the two full sets).

**Comment by amcewen** [comment]
Wiki updated to note that the spare cartridges are stored in the stationery cupboard.
