### ISSUE TITLE
Install new doorbot PCBs on doorbots 1 and 3

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#576]
Now that we've (mostly) successfully deployed the new Doorbot PCB to Doorbot2 (see #162 for details), we should install them on the other doorbots.

It would be good to try the soundcard install on one of them at least, to verify that that part of the PCB works correctly.  And if we get it working, we could use that PCB on Doorbot2 and re-deploy Doorbot2's PCB onto one of the others.

So, tasks to do...
 * [x] Solder up another PCB with the i2s DAC/amp soundcard and test it
 * [x] Install the new PCB on Doorbot2 (Workshop)
 * [x] Install the current PCB from Doorbot2 onto Doorbot3 (Dinky)
 * [x] Solder up another PCB, without the soundcard
 * [ ] Install that PCB on Doorbot1 (main room)

**Comment by amcewen** [comment]
The i2s DAC/amp board has been happily installed on Doorbot2 for a few months now (I had hoped @helicalbytes would update this issue, given it was his soldering work to get us there).

Both of the other PCBs we'll need have been soldered up too.

Today we deployed one of them to Doorbot3 (Dinky), although we need a Molex/hard-drive extension cable so the power supply can go back on the floor (we should get two more too to solve the same problem on the other two doorbots), and also need to buy some Dupont sockets to crimp onto the RFID reader wires (at present we're using the old relay board and some jumper wires on the Dinky doorbot).

We also still need to fit the last PCB to the main room doorbot.

**Comment by amcewen** [comment]
I've ordered 4 of [these Molex power extension cables](https://www.ebay.co.uk/itm/380474739201) and a [multi-pack of Dupont crimp connectors and shrouds](https://www.ebay.co.uk/itm/302501755810) to let us fix the Dinky doorbot (and give us a decent starting stock of Dupont connectors)

**Comment by amcewen** [comment]
The power extension cables and crimp connectors have arrived.  I've used two of the cables on the Workshop doorbot, and the rest of the stuff is on my desk atm.

The PCB on the workshop doorbot failed today - seems to be the transistor has failed, if it's base is grounded (rather than pulled high, didn't check that behaviour) then it conducts (which is shouldn't do) and so always turns the relay on.  I've swapped it for the PCB that was waiting to go on the main room doorbot for now, and put the failed one in the tub on the electronics workbench where the parts for that are.

**Comment by amcewen** [comment]
I've installed the power cables on the Dinky doorbot (ended up using two on there too, so have ordered two more for the main room doorbot).  And I've crimped connectors to the RFID reader, so the Dinky doorbot is done.

I tried replacing the transistor on the failed PCB, which didn't make any different, and there's some sort of short on the board, which has lifted the ground trace from the PCB now, so we need to solder up an entire new board (with the i2s DAC connectors, which will replace the PCB on the workshop doorbot and free that one up for installation on the main door).

**Comment by amcewen** [comment]
The new power cables arrived yesterday.

**Comment by amcewen** [comment]
The kitchen doorbot failed again today.  Upon investigation it's because the 12V line from the Molex connector to the screw terminal had burned out.

As a short-term fix I've replaced/augmented the 12V traces with extra wire, and have raised [an issue on the logcards repo for a proper fix](https://github.com/DoESLiverpool/doorbot-setup/issues/23)

**Comment by johnmckerrell** [comment]
All doorbots using PCBs
