### ISSUE TITLE
Replace blade on small band saw and order a spare

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/somebody-should#577]
There is a blade by the bandsaw - we need to check that it is the correct type

**Comment by jackie1050** [comment]
Bob has replaced the blade - still need to order a new one. Packaging by band saw "Axcaliber" 950655 BAND SAW BLADE 1420mm X 3/8" X 10 REG 0

**Comment by DoESsean** [comment]
Ordered a new spare from
http://www.axminster.co.uk/axcaliber-high-carbon-bandsaw-blades-up-to-1-790mm-70-1-2-ax876133?sel=950655

**Comment by amcewen** [comment]
Excellent @DoESsean, and you included a link to where to get it from too :100: (I got as far as finding that you'd bought the last one after it took us a while to track a source down, but you hadn't included the link then, so I couldn't easily get an order placed)

**Comment by amcewen** [comment]
Spare has arrived and is now in the sawing drawer in the workshop.
