### ISSUE TITLE
Send a DoES member on a LibraryOfThings tour and report back as to the potential

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#578]
I heard of this about this Library of Things setup in London, who are trying to reproduce by offering training events:
      https://www.libraryofthings.co.uk/tours/

(In the news-story they said that one of the most popular items to borrow is the ukulele, which only costs £2 to borrow.)

It appears that the underlying tech they use is http://www.lend-engine.com/ and it uses QR codes (perfect for @ajlennon ).  There's a free version as well as subscription, but it's unclear as to where the team who makes it is based, whether it is Bristol or West Wales.  

You can see some of the stuff the LibraryOfThings has here:
    https://borrowing.libraryofthings.co.uk/products?tagId=13

Mmm.  Double waffle maker.

**Comment by ajlennon** [comment]
Cor. I'm down at the Scientist Quantum Mechanics event in London over the weekend. Maybe I can pop in...

**Comment by amcewen** [comment]
There has already been some discussion about a Library of Things here in Liverpool (and some initial spit-balling about DoES Liverpool being one of the locations).  George McNamara (who used to hot-desk, working on his book) has been working on something like that with Transition Liverpool.  If anyone is interested in following up with him, let me know and I'll make an intro.  Or you could head along to the [Transition Liverpool annual symposium](https://www.eventbrite.co.uk/e/just-do-it-a-transition-liverpool-symposium-tickets-37220348063) on Saturday.

**Comment by jackie1050** [comment]
Edinburghtoollibrary.org.uk looks good too

On 10 Oct 2017 13:04, Adrian McEwen <notifications@github.com> wrote:

There has already been some discussion about a Library of Things here in Liverpool (and some initial spit-balling about DoES Liverpool being one of the locations). George McNamara (who used to hot-desk, working on his book) has been working on something like that with Transition Liverpool. If anyone is interested in following up with him, let me know and I'll make an intro. Or you could head along to the Transition Liverpool annual symposium<https://www.eventbrite.co.uk/e/just-do-it-a-transition-liverpool-symposium-tickets-37220348063> on Saturday.

**Comment by jodischneider** [comment]
This looks amazingly cool (and I'm in London today so I wish I could be the person to go. Alas, the schedule doesn't flex the right way, it's Weds PM that I've got the odd half-day). 

@ajlennon per https://www.libraryofthings.co.uk/contact/ they're open Tuesdays, Thursdays and Saturdays 10am–4pm at

Library of Things
Community Shop
Vale Street
Gipsy Hill
London
SE27 9PA 

Please update here if you get/got to go!

**Comment by paulfurley** [comment]
Different but related, I recently signed up for [streetbank](https://www.streetbank.com) which facilitates lending and giving things to people in your neighbourhood.
