### ISSUE TITLE
Arrange phone service for new venue 

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#581]
I suspect we should move to voip. If so then we can probably do it before the move.

**Comment by SayBeano** [comment]
Recently grabbed a wireless Yealink and its base station to set up with 3CX. 

Yealinks are cheap as VOIP goes (to buy new) but they're the easiest I've found to set up despite other handsets being supported and they're just as functional. 3CX runs for free too as you won't miss not having any premium features.

Worked so well three more were bought. Total cost about 250notes, not including a local VM to run it off (windows or linux) of course.

**Comment by ajlennon** [comment]
On 11/10/2017 20:16, Mark Sabino wrote:
>
> Recently grabbed a wireless Yealink and its base station to set up 
> with 3CX.
>
> Yealinks are cheap as VOIP goes (to buy new) but they're the easiest 
> I've found to set up despite other handsets being supported and 
> they're just as functional. 3CX runs for free too as you won't miss 
> not having any premium features.
>
> Worked so well three more were bought. Total cost about 250notes, not 
> including a local VM to run it off (windows or linux) of course.
>

No idea if it's of any use but I was chatting pre-Eastern Europe with 
the Dutch guy who was @ DoES who does lots of VoIP.

He was recommending a "Cisco Small Business Pro SPA3102 Voice Gateway 
with Router" to me. I got one in and I think it's languishing in a box 
somewhere waiting to be used.

If anybody wants to see how it works out prior to going the whole hog on 
a VoIP PABX in-the-cloud I'd be keen to have a play with it.

Cheers,

Alex

**Comment by johnmckerrell** [comment]
Alex that would be useful. Also we've now "acquired" 3 Yealink phones, no idea what we need to do to them to make them work, also @DoESsean says he's got a bunch of Cisco ones too, so looks like we're not short of hardware!

**Comment by johnmckerrell** [comment]
And @mwnw00359 has suggested Vonage and their "Free Vonage Box" which would allow us to use the existing cordless phone, £8.50/month £15 total setup:

https://www.vonage.co.uk/home/call-plans/talk/

I just looked at AA ISP, looks like they could be much cheaper although we'd have to sort out all the hardware, £1.20/month, £15 setup cost (+hardware)

http://aa.net.uk/telecoms-prices.html

**Comment by johnmckerrell** [comment]
Oh Vonage did mention that it can take a while to transfer a "BT" number so we probably do want to start this process soon.

**Comment by mattwilsondotuk** [comment]
We (Baltic Broadband) won't have any static IP's from day one but will be adding them later on, so try to avoid services that need static IP's!

**Comment by SayBeano** [comment]
Just to add to the list of solutions- metronet / m24/7 are doing 5000 minutes, install and hardware for 13quid a month, includes support plus they already run your existing microwave link so maybe speak to their sales department (presuming the metronet link is going the Tap.) for a round of negnotiating.

https://m247.com/business-can-voip/

**Comment by johnmckerrell** [comment]
Found these bits of hardware which will do the same job as the Vonage box but should mean we can use AA instead:

https://www.amazon.co.uk/Gigaset-N300-DECT-VoIP-Station/dp/B0063QY4NY
https://www.amazon.co.uk/gp/product/B005FSTM0G

Actually the Gigaset is just a dent base-station now I read the descriptions so unless I hear otherwise I'll go with AA and the OB/100 thing in the next few days. AA don't require a static IP so that's fine.

**Comment by johnmckerrell** [comment]
Almost there, I've got the hardware set up and can make outbound calls on it. The number should port in tomorrow at which point everything will be complete.

For the next 24 hours we should be on the yellow phone and then the cordless phone should become active when the port completes.

**Comment by johnmckerrell** [comment]
We now have VOIP service with A&A. Voicemail is activated after 30 seconds and the voicemail is emailed to organisers@does

**Comment by johnmckerrell** [comment]
Just had to get this set up in the new building and it was a bit fiddly. Basically I had to log in to A&A and change the IP address that we're connecting from (on the Outgoing tab) *and* I then had to turn the OBi100 off and on so that it tried reconnecting.
