### ISSUE TITLE
Buy new paper and inks for the sublimation printer

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#585]
Needed urgently:

We seem to have run out of paper, so need as soon as possible.

We also need to make sure we have both spare paper and inks for Make:Shift:Do on 28 October 2017

Existing supplies come from mdpsupplies.co.uk in Bromborough.

@ajlennon says that he @DoESsean has details so I'm assigning this to him for the moment.

**Comment by DoESsean** [comment]
I've ordered new inks
<http://www.mdpsupplies.co.uk/sawgrass-inks-ricoh.asp#> and new paper
<http://www.mdpsupplies.co.uk/sawgrass-paper.asp> from MDP. I also got some
heat tape while I was at it.

**Comment by johnmckerrell** [comment]
Closing this as I think we got more at the time and we've also got #595 covering the same thing.
