### ISSUE TITLE
Free extra-large laser cutter

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#586]
A laser cutter (without software) is available if we can get it:
It's 1270mm wide and 2250mm long and weighs 445kg and is currently at a school on the Wirral (I have contact details). It needs to be collected as soon as possible as they need the space.
I have discussed with @cheapjack and when moving Gerald they hired a mid size luton style van with tail lift. It would be great if anyone has access to one or could recommend a rental company.
Some things we'll need to do are:

- [ ] Check weight limits on lifts in Gostins building and the Tapestry
- [ ] Find out if there is anywhere to store it in the Tapestry
- [ ] Hire/borrow van
- [ ] Arrange collection (@cheapjack recommendation is that we'll need around 4 strong people to help out

**Comment by cheapjack** [comment]
I'd add a strong wheeled platform dolly of some kind or you'll need more than 4 and risk injury! 
We used something homemade way under spec'd but not quite as flimsy as [this](https://www.toolstation.com/shop/p99817) and it survived gerald. For £25  a day you could get one of [these from HSS](https://www.hss.com/hire/p/15t-machine-moving-skatesset-4) which is way over spec'd (15 Tonnes!) and expensive but at least we know what to google/look for: Dolly or skates for lifting/shifting

For van we used [KVS](http://www.vehicleman.co.uk/) in knowsley, cant remember which  one, cheap but bit far out of city centre 👍

**Comment by johnmckerrell** [comment]
There’s a skate in the workshop and I have a matching one at home. I’d have to confirm but I think it’s this one 

http://cpc.farnell.com/duratool/d00324/tool-cart-300kg/dp/TL10580

Little concerned about the “without software” but if we can get it working I can see another laser would be useful. 

--

**Comment by ajlennon** [comment]
I’ll help if I’m around but you may need another of me to make one strong person

**Comment by johnmckerrell** [comment]
External dimensions apparently 1270x2250

**Comment by goatchurchprime** [comment]
This has been obtained https://twitter.com/goatchurch/status/931937388645019648
