### ISSUE TITLE
Streaming Solutions for Meetings 

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#589]
@ajlennon to look into solutions for live streaming future meetings.

**Comment by DoESsean** [comment]
@ajlennon is this still something you're interested in doing? Is it worth trialling it to see whether there is much/any interest?

**Comment by ajlennon** [comment]
Yes definitely interested

**Comment by DoESsean** [comment]
We currently use Google Hangouts, which seems to have worked well so far. Given that we have a solution that works, I'll close this issue.
