### ISSUE TITLE
Olsson Block for 3d Printers

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#592]
In order to hopefully solve some of the problems with the 3d printer, make future maintenance easier, and on the recommendation of Jim Nixon and @DefProc, we've ordered an Olsson Block.

It came from [https://www.3djake.com/3d-solex/olsson-block-upgrade-kit-with-nozzles](url)

**Comment by DoESsean** [comment]
This is currently sitting on @DefProc's desk waiting to be fitted.

**Comment by gamesquest1** [comment]
Olsson block installed, and replacement thermostat left inside Olssonn block box in 3d printer supplies cupboard

**Comment by jackie1050** [comment]
Reopened as we will need to:
- update the wiki (including identifying which nozzle is being used)
- find a place to store the extra nozzles so they are easily accessible but can't get lost. @gamesquest1 is looking at printing a holder to fit on the inside of printer box
- find out which nozzle is the best default

There are some instructions for changing the nozzle here, including the need to change Cura settings:
https://ultimaker.com/en/resources/50623-change-the-nozzle 

Printable wrench here:
https://www.youmagine.com/designs/nozzle-torque-wrench

**Comment by jackie1050** [comment]
I've added a note to the Wiki, with link to the instructions for changing the nozzle.

The new nozzles (0.25, 0.6, 0.8mm) are in a black cardboard box in the 3DP supplies cupboard, along with the old nozzle and replacement thermostat.
