### ISSUE TITLE
Apply for Maker Faire UK 2018

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#594]
The call for makers has opened for 2018 event on the 28th/29th April at the Newcastle Centre for Life:

https://www.surveymonkey.co.uk/r/MakerFaireUK2018

And tthe deadline for submissions is 5:00pm on Monday 15 January 2018.

Assuming that this is not a questionable subject, DoES would need to apply before that date.

Would anyone like to lead on this?

 - [ ] Apply for MakerFaireUK 18 online

**Comment by SayBeano** [comment]
How quick are MFUK to reply/confirm their applicants?

JR has tweeted about booking hotel rooms for a DoES contingent. I've not long read this will be done on or near 15th November. Thought it was worth mentioning.

https://twitter.com/thingomy/status/925302303959212032
https://groups.google.com/forum/#!topic/does-liverpool/ynfuZf9b4HM


I can't commit to leading this issue (nor commit to accomodation) though I don't think I'm presently "DoES-present (in the physical sense)" enough anyway. However thought it was worth associating these two items for us should the two become a collab. with JR and the person leading on this one.

Inabit

**Comment by DefProc** [comment]
@jackie1050 I noticed we got 10 day warning till applications close, has we submitted an application yet?

**Comment by jackie1050** [comment]
Hi Patrick – I'll be applying this weekend.

________________________________

**Comment by jackie1050** [comment]
I've made separate applications for "Play the Tree" and "MadeInvaders".

**Comment by jackie1050** [comment]
We were at MakerFaire UK this weekend
