### ISSUE TITLE
Cable holder and air assist tube on Gerald need replacing, is stiff/fire damaged

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#596]
The cable holder (snakey thing) on Gerald, the thing that loops up as the head moves left and right is stiff and damaged after a fire today. It now drops down, stopping it from moving too far to the right. I'm not sure if it was already stiff before the fire. We had issues recently where it seemed to be too powerful so perhaps it was getting caught, so not moving and therefore firing the laser in one place too much. It's definitely stuck and possibly broken as I tried to un-stiffen it. I've "fixed" for now by duct-taping a piece of MDF underneath to make sure it doesn't fall below the rail, definitely not an optimal solution.

![2017-11-02 09 30 37-rotated](https://user-images.githubusercontent.com/27243/32325257-20ccb8ae-bfc6-11e7-854c-84b120662690.jpg)

**Comment by amcewen** [comment]
Rob and I replaced the MDF with cardboard "splints" that allow some flexibility and so mean that more of the bed area is usable.  It's still doesn't work to the rightmost 20cm or so.

Some of the cable holder is a bit melted now, and there's definitely damage to the air assist tube running through it - you can feel the air blowing out of the holes in it.  There's still air getting to the laser nozzle, but obviously not as much as should be.

**Comment by DefProc** [comment]
There's a good length of replacement hose - for just such an occasion - in
the laser spares cupboard. Hopefully just the section from the tube
connector to the laser head can be replaced, otherwise there are spare
male-to-male hose connectors.

**Comment by DefProc** [comment]
Scratch that, I misunderstood the location. The PVC pipe we have will be
enough to replace any pipe, but the *cable drag chain* might be due for
replacement if it's damaged as well as worn.

Although it's a specific part on the cutter, they are made in standard
sizes by a number of manufacturers. Assuming it's 1m long, it should be
enough to measure the height and width of a link to find a full length
replacement chain.

**Comment by johncain39** [comment]
Hi guys, well I’m finally up and running on github??!!! 🙈 I have just ordered some spare parts for Gerald (drag chain and hose). I’ve ordered them direct to DoeS under my name. Please feel free to open and use if need be. I’m more than happy to fit once they arrive.

**Comment by amcewen** [comment]
Yay!  Lovely to see you here @johncain39 :grinning: I've just invited you to the @DoESLiverpool organisation (I think Github will send you an email about that) which will mean you can close issues as well as comment on them.

Thanks for getting that ordered (and for reporting back on it here!)

Any chance you could stick a link to the drag chain and hose that you ordered in a comment on here?  Just so that if (/when) we need to order another in future we'll won't need someone to measure up and find something again.

**Comment by johnmckerrell** [comment]
I saw some hose turned up recently, not noticed the drag chain, I put the hose in the laser spares cupboard.

**Comment by amcewen** [comment]
Gerald's drag chain is increasingly made up of hazard tape :-/  A number of people have added more tape to it over the past few weeks and now it's not very flexible and was dragging on the bed and moving work (so ruining cuts) this morning.  I've added more tape (after trying refitting it better to no avail) and further reduced the workable cutting area.

We really need to get a new one and get it fitted.  @johncain39, do you have any details of where you ordered it from?  Can we chase up where it's got to?  Can you even share a link to what you bought so someone could maybe find an alternative supplier to buy some more - if it's not that expensive (£10s rather than £100s) it'll soon pay for itself if it keeps Gerald in use...

**Comment by johncain39** [comment]
Hi guys, sorry I’ve been off the grid been mad busy with Xmas stuff. I have just contacted supplier of drag chain and said should be with us the 11th Dec. If we can’t wait then happy to find someone who can get us some here quicker. Probably cost between £20/£30.

**Comment by DoESsean** [comment]
I'd suggest seeing if it's possible to get some here quicker - if it's not,
no problem, but it's better to get this fixed as soon as we can. And then
we'll have a spare should we have this issue again.

**Comment by johncain39** [comment]
Hi Sean, that’s fine. I will get on the case now and get back with update.

**Comment by amcewen** [comment]
Thanks @johncain39.  And don't worry about being busy :-D that's generally a good problem to have, but that *is* why it's good practice to leave comments with details of what's been ordered or where you've got to on any of these issues.  It then means that someone else can pick things up if they're not busy (and also not order a duplicate from a supplier that's already slow to deliver!) and between us all we can get things sorted quicker.

**Comment by johncain39** [comment]
Hi Team, I have just ordered another drag chain from eBay and should be with us by Thursday 7/12/2017. I have paid for first class delivery which was the best option they had to ensure this. Please also find attached the items I had previously ordered again this issue. I do believe the hose has arrived??!!


![hose](https://user-images.githubusercontent.com/33912241/33610772-411bb5c0-d9c4-11e7-9fd6-f07e57e8e785.JPG)
![drag chain new](https://user-images.githubusercontent.com/33912241/33610777-41a73f28-d9c4-11e7-88b8-258510ad4ffd.JPG)
![drag chain 2](https://user-images.githubusercontent.com/33912241/33610778-41d2ee52-d9c4-11e7-952d-c45c8c08e79f.JPG)

**Comment by DoESsean** [comment]
That's great, thanks @johncain39 

Are those prices the final amounts including shipping? If so, I'll sort out the money for you and leave it somewhere you can grab it when next in/with Adrian for Maker Night.

**Comment by DoESsean** [comment]
Unfortunately, the chain that arrived today is just too wide.

I've ordered a new one from [here](http://ooznest.co.uk/Cable-Drag-Chain-Carrier) which should be here by Saturday.

**Comment by johncain39** [comment]
Hi Sean,

How wide is it?! Should be 20mm wife by 10mm deep??!!

**Comment by johncain39** [comment]
Wide even??!

**Comment by DoESsean** [comment]
Unfortunately, the 20mm is the internal width rather than external - 20mm external would have been ok, I think.

**Comment by johncain39** [comment]
Ah bugger!!! Sorry !!

**Comment by DoESsean** [comment]
No problem, it's a really easy mistake to make, especially when the eBay ad isn't super clear.

**Comment by amcewen** [comment]
Thanks for the updates @johncain39!

The chain @DoESsean ordered has arrived and fits into the channel for it (yay!).  I've put it in the laser-spares cupbpard (on the left hand side) ready for when we come to fit it.

**Comment by amcewen** [comment]
I'm aiming to fit this at the weekend, most likely Saturday lunchtime-ish, before the meeting and party.  In case anyone wants to help out.

**Comment by johncain39** [comment]
Hi adrian,

I’m sort of available if we could push it forward to 10am?! Got stuff on in the afternoon that’s all.

Cheers

John

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by huffeec** [comment]
This has now been fitted at makernight my @amcewen, Nigel and myself and appears to be working fine.
