### ISSUE TITLE
Gerald's belt is loose

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#597]
In this morning's fire (and possibly other fires) the plastic belt joiner warped and loosened. I created a new one and attached it but it's a bit loose so needs re-fitting. Expecting this to be done at Maker Night tonight.

**Comment by DefProc** [comment]
There is a complete 15mm wide belt to replace this in the laser parts
cupboard too it should be long enough (just over 3m long) to fit without
the joiner.

Last time I folded the end of the new belt over the old and used a zip tie
to hold then together. Then pulled the new belt through the centre of the
gantry tube.

**Comment by amcewen** [comment]
I've refitted it to the existing belt and the cutter is back working now.  The existing belt is a bit frayed where the fire was, but not so much it'll be a problem.  Might make sense to replace it when we're fixing the rest of the fire damage (comment incoming on #596 about that...)
