### ISSUE TITLE
Clean the inside of the Laser Printer

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#6]
To fix the printer's inability to print red, it needs deconstructing and cleaning: [http://www.reeves-hall.net/tech-gadgets/fixing-washed-out-colour-on-hp-color-laserjet-2605]

See also: http://wiki.doesliverpool.com/LaserPrinter

**Comment by johnmckerrell** [comment]
Upgraded the priority on this as the printer is currently non-functional, and as far as I know this is the solution.

**Comment by amcewen** [comment]
Given we've bought new printers (see #230) we don't need to fix this any more.
