### ISSUE TITLE
Youcanbookme Account Needs Updating - Urgent

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#600]
We've had an email that someone is unable to book the laser through the website. I thought it might have been user error, so tried to use the form on our site to book, and got a page with our logo and the following error message:

'Sorry, the owner of this calendar needs to make a change to their account before this page can be used.
As soon as the owner of this calendar upgrades their YouCanBook.Me account, this will start to work.'

There is no indication as to what upgrades need to be made.

Could someone check this as a matter of urgency? It may be linked to the recent changes we've made to the calendar as regards who can update or add induction slots, or the timing may just be coincidental, but it's preventing people from making bookings as of right now (9/11/17, 3pm).

**Comment by johnmckerrell** [comment]
I've sent them an email, I suspect it's because the main credit card has expired but I don't actually see how to now upgrade manually.

**Comment by johnmckerrell** [comment]
They've responded and reactivated us, looks like emails were going to our app control account but no-one was monitoring it. They will contact us for payment so I'll leave this open until that's done.

**Comment by johnmckerrell** [comment]
To confirm we're now back to paying monthly but the service we're using will be decommissioned by August. We should really aim to replace this by then.
