### ISSUE TITLE
Check whats causing the broken security lock for https://doesliverpool.com

### ISSUE THREAD

**Issue by de14n** [DoESLiverpool/somebody-should#602]
Just to let you know. The green lock doesn't appear for the main Does web address of https://doesliverpool.com. It seems to be that mixed content are used because the certificate is within date until 2018. So it's usually external media or static files not being served over http://. The https://doesliverpool assumes a wildcard certificate, suggesting it's not a sub-domain mismatch.

I'm not involved with the website in anyway and I'm only starting to get involed with DoES. So maybe something to cover in the next website meeting.

**Comment by de14n** [comment]
Had a scan over the source code. Seems to be some Twitter links are using http://, other Twitter links are using https://. One or two other using http:// too. Changing them to https:// should sort it.

**Comment by johnmckerrell** [comment]
I've posted a bug on the week notes generator https://github.com/DoESLiverpool/weeknote-generator/issues/23 <https://github.com/DoESLiverpool/weeknote-generator/issues/23>

 I also tried using a couple of search & replace plugins to fix these but both failed so leaving it for now!

**Comment by de14n** [comment]
It's working now on my side... which is funny because some of the those Twitter links I thought was causing it are still there.

Maybe you need to wait for the server to refresh it's own cache. I think new visitors would get the green padlock now.

**Comment by johnmckerrell** [comment]
I did suspect there was some caching going on, looks like the search & replace actually worked! I'd leave this open until the week notes generator is fixed though.

**Comment by de14n** [comment]
Ok. I'll leave it open until you give the nod.

**Comment by amcewen** [comment]
I've found the problem that was causing the Twitter images to not be https, and fixed https://github.com/DoESLiverpool/weeknote-generator/issues/23, so it should now all be sorted.  At present it doesn't have the padlock, but that's because the older weeknotes on the front page don't have https images in them.
