### ISSUE TITLE
Easy pop-up physio section in the workspace

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#603]
It would be a reasonably secluded area near the tea where you can do some stretching exercises while waiting for the kettle to boil or your 3D print to finish.  

The area would have a couple of yoga mats, perhaps a stock of resistance bands and some posters of exercises.  
    http://www.theraband.com/theraband-professional-non-latex-resistance-bands-sets.html
    https://www.bhf.org.uk/heart-matters-magazine/activity/resistance-bands

I've just had a couple of sessions of sports physio to deal with slightly bad back from too much seated programming.  (I wanted to deal with it before it got properly bad).  

I got some simple exercises that I'm supposed to keep doing -- even when it's no longer hurting (common mistake: stopping the exercises when it stops hurting).

If popular, we could get one of those big balls and add some lasers, check-in timers (so you can't kid yourself about what you're doing), orientation sensors and EMG muscle sensor tech.

**Comment by ajlennon** [comment]
+1 from me. I would like to perhaps do some meditation sessions with people from time to time there.

**Comment by johnmckerrell** [comment]
Seems like we'd struggle to permanently allocate an area to this as space is at a a premium even in our bigger space. There's talk of a weekly yoga session going on in the top floor though!

**Comment by goatchurchprime** [comment]
Changed title from "permanent" to "pop-up", which is actually more what I had in mind.  The materials would be stowed on a shelf

**Comment by ajlennon** [comment]
Who is in the top floor doing the yoga stuff?

**Comment by DoESsean** [comment]
We have the kids stuff, which is stored away when not in use. I see no reason why this couldn't follow a similar route, with Dinky being used for people to do their thang in.

If someone wants to organise bringing things in, fantastic.
