### ISSUE TITLE
We need a plan for Pigeon Holes in the new building

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#606]
Currently, the mail boxes are sat on my desk, which is fine as it is at the back of the room, inobtrusive and would be very obvious if anyone started looking through them.

However, in the new space my desk is likely to be in the main reception area, and, as such, much more accessible for people coming into DoES. This will mean that we need a more secure solution for the mail.

On top of this, we currently have far more mailbox subscribers than we do spaces for mail, so we're going to need to considerably beef up the number of holes we have.

I think we might need to move away from the current 'letter rack on a desk' solution to something more permanent and solid, so any ideas are appreciated.

**Comment by johnmckerrell** [comment]
I think a decent enough improvement might be to get some more inboxes that match the existing ones, label them and, ideally, put them in room 29.

**Comment by DoESsean** [comment]
I've ordered another set like the ones we have now, will be with us next week. In lieu of any super pretty or super technical alternative, it will work just fine.

**Comment by johnmckerrell** [comment]
I've labelled the new mailboxes, we currently just have 1 free slot although that is taken up currently by "post to return to Gostins" so we might need another. Also if we get post that isn't for a labelled mailbox please label one or put it in Miscellaneous if it's not a current paying customer.
