### ISSUE TITLE
Buy some new solder

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#608]
We have run out of 1mm lead-free solder
e.g. from Maplin 
Code: N31AR
Composition: Sn 99.3%, Cu 0.7%
Diameter: 1mm
Weight: 500g

**Comment by DoESsean** [comment]
Solder has been ordered from Farnell.

We've also added a new tip to try. You can find it at:[http://uk.farnell.com/weller/pt-bb7/tip-soldering-iron-round-sloped/dp/416344?ost=416344&iscrfnonsku=false&ddkey=http%3Aen-GB%2FElement14_United_Kingdom%2Fsearch](url)

**Comment by johnmckerrell** [comment]
Think I placed this in the drawer of the soldering station yesterday.

**Comment by amcewen** [comment]
You did, and I've put it onto the dispenser and into use.  Do you remember if you put the new soldering iron tip in there too @johnmckerrell?  I can't spot it from a rummage in there...

**Comment by johnmckerrell** [comment]
I didn’t see one, was it on the same order?

**Comment by amcewen** [comment]
AFAIK it was, @DoESsean can confirm (and maybe check the order in case it was out of stock and is going to be delivered separately?)

**Comment by johnmckerrell** [comment]
Ok, I think I was efficient at binning the box so if it did come we’ve most likely lost it :( I’ll pay for a new one if we need to reorder.

**Comment by DoESsean** [comment]
I've ordered a new tip this afternoon.
