### ISSUE TITLE
Document library for important notices

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#609]
@jackie1050 kept pointing out how I'd not read the important blog by John about the new space and desk rates:  https://doesliverpool.com/co-working/announcing-our-new-home-and-does-membership/ 

I said I can't follow all blogs all over the place, and that important notices about the space should be printed out and put on the wall of the space rather than deposited on a server in California available on the internet where too many other distractions get in the way. 

So I've pasted his post into a document, printed it on three pages and stuck it on the whiteboard.

[doesmovingannouncment.docx](https://github.com/DoESLiverpool/somebody-should/files/1503834/doesmovingannouncment.docx)

There are a few other documents we need to have, like the new members manual, and any other important notices, news flashes, closing times, rent rates, statements of accounts, days of action, incident reports, apologies, official thanks for donations, door key access policies, building or equipment maintenance notes and stuff that could be pinned to the wall near the kettle or on the door of the bog where your mind is open for reading and you should not be holding your computer.   

This relates to issue #243 about signs

I've looked for other documents at other hackspaces, and can only find some docs here:
    http://bristol.hackspace.org.uk/wiki/doku.php?id=a0_laser_cutter

Probably the best solution is to have some sort of shared google-document account, which is an effective interface for producing printer-ready documents without all this download, save, edit, save, find the file on disk, upload to the right file type work-flow which we all hate.  Google-docs, edit, layout, then print, possibly from a public terminal near the printer would have the least frustration.

**Comment by DefProc** [comment]
While I applaud the idea of deciding what approach DoES should take to make it's member's aware of important announcements, I'm not quite convinced that an additional workflow is automatically the *best solution*. However, I do think that it's worth working out *what* the best solution is for DoES. 

At the last count, DoES's digital domain is becoming expansive (website, github repos, github issues, google group, mailing list, wiki, gitlab repos, gitlab wiki, etc), and it's starting to collect a number of physical notice points (kitchen notice board, main room notice board, main room white board, posters on the wall). 

@goatchurchprime Am I right in thinking that your key point here is:

 > If DoES has (what it considers to be) an important announcement, then it should *make an effort to send that information to you* rather than just *put it somewhere that you might find it*.

If so; then there is some overlap here with consolidating DoES's online footprint, which have come up as part of discussions in the website working group. #19

**Comment by DoESsean** [comment]
I do like the idea of having notices in prominent places though.

Since we are going to have an open coffee area in the new building, having a noticeboard or two there isn't the worst idea. I'm also a fan of using the 'frames in the toilet' tactic that pubs use.

**Comment by DefProc** [comment]
@DoESsean And as per the style guide (broken link in #20?) that would cover the "don't just stick up printed A4 sheets on the wall"* if we're using snap frames or poster frames.

*_I'm paraphrasing_

**Comment by DoESsean** [comment]
We have snap frames, they're all over the place and have important things in them. More's to the point, anyone _can_ put important things in them. Hence...

Closed!
