### ISSUE TITLE
Put Kindle into Dinky door

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#61]
This is basically done now but we should consider painting the back of the mounting and fix it more securely, it's currently a "friction fit". Would be worth updating the pictures too, there's three currently. It shouldn't have fixed content, that would be better on paper, so I suggest:
- Door Closed: "Welcome, scan below for entry"
  - /mnt/us/does/close.png
- Door Open: "Door open, come in!" or similar.
  - /mnt/us/does/open.png
- Screensaver: Same as door closed but with some brief text to say that the screensaver is activated (which is a bad thing and requires intervention)
  - /opt/amazon/screen_saver/600x800/Kindlehome.png

Paths for files are above, existing images attached to this issue. IP address and password for kindle can be found in the doorbell's config file.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by DoESsean** [comment]
Closing this, as it will be part of the fit out in the new building.
