### ISSUE TITLE
Efficient way of declaring small debts to DoES

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#610]
For  those who have accounts with DoES, we need an efficient way to disclose debts (like when I have visitors working with me for the day) to the accounting system for subsequent invoicing -- other than just telling Sean when he's in the office.  

This becomes more of an issue when paying for storage space (usually on return of an excess storage box, having multiplied its rating by the number of days counted on the calendar from the day I marked as having borrowed it off the shelf).  

The minimum viable system would be a version of doorbot where I typed in a number in pounds, swiped my card and it automatically got added to my bill.  This works for food stuffs, laser cutting supplies, and so forth, so we don't need to use the kitty and nobody has the excuse about paying later and forgetting about it.  A negative value could be added when buying authorized communal supplies.  

A more advanced version could have a kind of drop-down menu for what it is you are in debt for -- or use a special set of rfid keys with the type of debt that you swipe before you swipe your personal rdif key.  

It's got to be super quick and painless to enter and to add up, so it can be used for smaller supplies worth pennies, like mugs, sublimation ink and 3d prints.  The kitty could have its own rfid key that you can use only if you are pay in coins into the kitty at the time the debt is run up.  

The point of charging for these small things is so you are happy with taking stuff away because you know you're not denying it to other people as you have left enough money to restock.

**Comment by johnmckerrell** [comment]
A better way and a simple start is to email organisers at hello@doesliverpool.com <mailto:hello@doesliverpool.com> because telling one person is never the solution.

**Comment by goatchurchprime** [comment]
If email is the interface, it would best be structured and perhaps go to debts@doesliverpool.com where it could be processed systematically.  

The best answer would be if the freeagent expenses app (https://www.freeagent.com/tour/expenses/) had a setting that allowed any person to create a "Negative Expense", because then it could transfer onto my monthly invoice seamlessly without wasting anyone's time.  

This would also make it a lot easier to collect money from people who wanted to pay cash for laser cutting (so we didn't leave it lying around on Sean's desk) for the week.  

Workflow: I would take £5 from person X and immediately log a message to the effect: "On [datetime] Julian owes DoES £5 for X's afternoon of laser cutting."

**Comment by DefProc** [comment]
Fun as the technical processes are… this could be prototyped on paper. For transferable debt slips: 

> I `debtor` owe DoES `£amount` for `service or goods` (used by/on behalf of) `service user` on `date`. 
> Signed `debtor`: `date`

Although I don't like the idea of processing transferable debts this way for DoES. 

I'd rather go with an IoU/debt slip: 

> I `debtor` owe DoES `£amount` for `service or goods` on `date`. 
> Pleaes 
> Signed `debtor`: `date`

And a paying in slip for cash: 

> I `payee` paid DoES `£amount` for `service or goods` on `date`. 
> Signed `payee`: `date`

And by going with paper, the authentication is then on the signature.

**Comment by ajlennon** [comment]
What about an email address people can sent notification of their debt to which gets rolled up into a web page list of debtors? Bonus points for block-chain-ifying it.
