### ISSUE TITLE
Add some scientifically-formulated-to-be-beneficial foodstuffs to the shopping list

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#613]
At the moment we only have boring old crisps, coke and chocolate bars that have been scientifically formulated to be as addictive as possible, available, imperishable, and with completely disposable packaging -- where absolutely no account is taken for how much harm these products do to you.   

These days there's a whole community of life-questioning meal replacement packages designed to claim back those hours in the week wasted hand-preparing meals, socializing, chewing, washing up dishes and shopping, such as these crowd-funded substances:
    https://en.wikipedia.org/wiki/Soylent_(meal_replacement)
    https://huel.com/  <--- this one is British

We need to get a couple of these brands in stock (including their SF-themed brochures and sales materials), instead of the unhealthy crisps, for hackers to broaden their culinary life-hacking experiences.  Indeed, if widely deployed in society, this tech could be taken back to the production lines and offices in order to cut down the lunch hour to a four minute gulp and therefore drive up productivity by 12% on an eight our day -- not even counting the work wasted by the labour hoarding of canteen staff and the unnecessary promotion of unhealthy products which cause a burden on the NHS.

**Comment by goatchurchprime** [comment]
The stock of Huel has been bought.  Now we need a taste testing and review.  People are free to try and write reviews if I'm not here (subject to, say, a £2 donation to DoES per portion)

The rule is you can't drink the meal replacement substance unless it **replaces a meal**.  It's not dessert.

**Comment by ajlennon** [comment]
#HFLC foodstuffs for those of us back on the #ketosis diet

**Comment by johnmckerrell** [comment]
Given that we have the Huel now and anyone is welcome to eat it if they can bring themselves to do it can we close this now?
