### ISSUE TITLE
Clean (possibly replace) the 0.4mm nozzle

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#614]
Somebody changed the printer nozzle and appears not to have tightened it up properly. It then came loose while printing and the thread got covered with PLA etc. 

I have currently replaced it with the 0.6mm nozzle which seems to be working OK.

**Comment by DoESsean** [comment]
Given that Adam has been running for the last 18 months, I'm going to assume we're all good :)
