### ISSUE TITLE
Investigate possible issue with clips on bed

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#615]
Prints weren't sticking to the bed. Eventually I noticed that the glass was not secured properly. It seems that the clips have become loose (not sure if somebody damaged them while taking the glass out to clean). I've temporarily stuck the glass down with heat proof tape and the printer is printing OK now

**Comment by DefProc** [comment]
It has seemed like the clips at the back of the bed get pushed back when someone pushes against them when using the scraper to remove a print from the bed. And when they get pushed back, that opens up the clip to the point where it doesn't grip. 

In the past, with the bed at the bottom to minimise the risk of bending the bed, I've placed the scraper blade vertically behind the clip and pulled forwards to bend the clip. This does take some care, as the clip is sharp (hence using the scraper as a lever) and it's possible to cut yourself on it.

**Comment by JimNixon** [comment]
To stop this happening, I'd advise taking the build plate out before
removing the print. Puts a lot less strain on the printers.

**Comment by jackie1050** [comment]
Comments by @DefProc and @JimNixon appear valid - we now advise people to remove the plate before using the scraper.
