### ISSUE TITLE
Add details of the sewing machine(s) to the wiki

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#617]
We can't be in the tapestry quarter and not have a sewing machine in use with its own Tool wiki page, induction system and a https://hackaday.com/2017/05/23/the-textile-bench/ .

I threw away an old one in frustration last year, and would like to get one that works and doesn't jam up continuously.  I know someone who tried out many brands and noticed that Bernina stood out.  Of course it is the most expensive.  

I wouldn't complain if one of these fell off the back of a truck:  https://www.youtube.com/watch?v=1XiVyakHzY8

**Comment by johnmckerrell** [comment]
The one you through out, was that in DoES? I thought we already had a sewing machine but perhaps it’s gone now.

**Comment by johnmckerrell** [comment]
Also worth noting that there’ll be a specialist fabric co-working space next door which might lessen the need for us to have specialist equipment.

**Comment by amcewen** [comment]
We have at least one sewing machine already.  It is hidden behind a load of other stuff in the storeroom in Dinky though.

I'm pretty sure we've got one normal and one overlocker.  I've changed the title of this issue to documenting what we've got.  It would be handy to have at least one of them set up somewhere in the new space so they don't get similarly forgotten about.

**Comment by goatchurchprime** [comment]
Experimenting with "Room: specialized area" label -- eg place to pool and store and catalogue lots of general purpose materials supplies, like zips, velcro, neoprene, fleece.  

I'll go try and dig out the machines and log what they are.

**Comment by goatchurchprime** [comment]
https://github.com/DoESLiverpool/wiki/wiki/Sewing-machines
