### ISSUE TITLE
Dinky Kindle should be more intelligent

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#62]
Dinky Kindle should show information about current/next event.

Doorbot3 could check calendar every 5 minutes for an event that's on now or within the next hour ( / past hour), if there's an event then place information into an SVG file, generate a PNG and use it for the "close" file instead (if it overwrites the close.png file on the kindle then this can be independent from log cards code).

SVG solution would be nicest but we can also have a bunch of pre-generated PNG files to start off with.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by DoESsean** [comment]
@johnmckerrell I've added the Move tags to this issue as it seems like it might be something that you'd want to play with in the future. If this isn't the case, and you're not too fussed about it anymore, please feel free to close the issue.

**Comment by johnmckerrell** [comment]
Giving up, if we install it again and want to make it more intelligent, we can reopen this.
