### ISSUE TITLE
Create a glue and solvents section on the wiki and in a shelf

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#620]
Following on from the embarrassment of sticking @jackie1050 's shoe together with hot-glue last night, I realized we've got some different kinds of specialized glue in the cupboard (eg for gluing perspex and/or wood), but we don't use them because we don't know about them (and they look scarily toxic).  

Plus I've got at home things like Black Swan PVC cement and Bostik 2402 for neoprene rubber that generally go off by the time I get to the bottom of the can.

**Comment by cheapjack** [comment]
The big brown smoked glass jar contains an acrylic welding glue that is brushed in and taken up by acrylic via capillary action. Cant recall actual name of chemical. It is scarily toxic, evaporates in air and must not be breathed in. When next in I can find out about it and amend a wikipage happily. Possibly at xmas party :)

**Comment by goatchurchprime** [comment]
Put info here:
    https://github.com/DoESLiverpool/wiki/wiki/Glues-and-solvents

**Comment by goatchurchprime** [comment]
The necessary pots (disposable if they need to be) and allocated application brushes should be considered an essential component of the glue station.

**Comment by DefProc** [comment]
This has to fit in with #243, as any substances that were storing (especially when they're described as "scarily toxic" :warning: ) need to have an MSDS with them, need to be labelled with the risk they contain, and they need to be stored appropriately.

**Comment by de14n** [comment]
Maybe someone (I will, unless someone does it before me) make a simple adhesive/material matrix to show what glues work with what materials. All I know about glues are:

- Superglue isn't all that super unless it's used with the right materials.
- Superglue isn't always the same stuff, but often still sold as 'super'.
- Glue-gun glue is quite limited in it's uses, it's better for holding prototyping bits together than for any long term use.
- There's this stuff called JB Plastic Weld, it's incredible stuff; unless we have some, I'll buy a bottle for DoES. Reading back, it's probably what cheapjack is on about? I always use it to fix broken plastic toys and car interior bits.

**Comment by DefProc** [comment]
To save restarting from scratch, there's a set of advice at: [thistothat.com](http://thistothat.com/)

**Comment by goatchurchprime** [comment]
It's done anyway.  https://github.com/DoESLiverpool/somebody-should/wiki/Glues-and-solvents
