### ISSUE TITLE
Investigate Viability of Continuing Make Shift Do Under DoES Umbrella

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#622]
There is a chance that the Crafts Council will not be funding M:S:D in the future.

Would it be possible for DoES to arrange a similar event - not funded, obviously, but bringing lots of spaces together to run events with a similar theme on the same day.

**Comment by DoESsean** [comment]
Looking at this, @jackie1050 (and this is assuming that the Crafts Council didn't run this last year), was there a list anywhere of all the spaces that took part in the last M:S:D? First steps would be just to reach out to them and see if they'd be interested in doing something later this year.

I guess corporate sponsorship could be an option, although I've no idea how we'd go about that...

**Comment by jackie1050** [comment]
There's a list of names (not contact details) inn Appendix A of the 2017 Evaluation summary - download at the bottom of this page: -https://www.craftscouncil.org.uk/what-we-do/MakeShiftdo. I haven't checked the whole site.

We could discuss at next Community meeting.

On 18 Apr 2019 16:51, Seán Gleeson <notifications@github.com> wrote:

Looking at this, @jackie1050<https://github.com/jackie1050> (and this is assuming that the Crafts Council didn't run this last year), was there a list anywhere of all the spaces that took part in the last M:S:D? First steps would be just to reach out to them and see if they'd be interested in doing something later this year.

I guess corporate sponsorship could be an option, although I've no idea how we'd go about that...
