### ISSUE TITLE
Arrange a Community Visit to the Tapestry in Early January

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#626]
We're looking to allow members of the community to see the new building before we move in, and get any comments or ideas that people have.

**Comment by DoESsean** [comment]
I've emailed Jason about whether or not it will be possible to arrange a visit for January 11th. It seems like that date will be fine, although Jason won't be there.

I'm waiting to hear back as to whether or not we will still need hard hats and hi-ves gear at that point, as that will limit the number of people that could attend at a time, so we might need to have a booking system.

**Comment by DoESsean** [comment]
The visit is happening on the 11th.

I've sent out an email (and a mailout to the mailing list) letting people know, and asking them to tell us if they want to come. Current plan is for me to go over for 10, and stay there for a little while to take people round. Of course, if there's not that much interest, I can do everyone at the same time.

**Comment by amcewen** [comment]
The visit happened.  I'm sure anyone who missed out will soon enough have the opportunity to visit again while carrying stuff during the move :-) so I'm going to close this.
