### ISSUE TITLE
Can we get a hackspace hamster

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#629]
They're very practical, and kids love hamsters so it would make the space more child-friendly.  

Also, there are many fun projects:
    https://hackaday.com/2017/05/27/esp32-hamster-wheel-tracker-tweets-workout-stats/
    https://technabob.com/blog/2007/04/10/the-hamster-powered-paper-shredder/

(I used to have a pet rat, but they're big and like to chew wires.  A hackspace cat might be necessary if there are wild rats, but they can be a bit snooty.)

**Comment by ajlennon** [comment]
Could we wire it up for control via a Raspberry Pi? #InternetOfHamsters

**Comment by drfraz** [comment]
I don't see how a hamster is practical but I do like this idea https://www.youtube.com/watch?v=A3iP0NGDDao

**Comment by DoESsean** [comment]
Thanks to this, I have just found out that hamsters can run up to six miles
a night in a wheel, and can actually become paralysed if they don't have
enough space to run around.

**Comment by DefProc** [comment]
And I have a little bit of a worry for the potential hamster's well-being, based on how much we neglect plants in the space… :skull:

**Comment by DoESsean** [comment]
Plants aren't cute though...

I have long been an advocate of an office fish tank, particularly if we're going to have a nice area to relax in.  I've just floated (ha!) the idea of having a full height one that would require someone to go in in SCUBA gear to clean, something like [this one](https://www.youtube.com/watch?v=w09uZQnGtXo) in Heron Tower.

**Comment by de14n** [comment]
We can attach a dynamo to the hamster wheel and they can recharge batteries for us overnight. I'm really not joking, we could even make gears to make it easier for them.

**Comment by ajlennon** [comment]
How many hamsters to we need to power a DoES cloud infrastructure?

Can I volunteer to be that person in SCUBA gear? Although for bonus points I might try freediving it...

**Comment by drfraz** [comment]
If we estimate that it will take about 150 W/h to run the cloud and that the average hamster weighing 120g contains about 627600J that will give us about 4000 seconds. 
This is assuming 100% efficiency more realistically 30%  would mean that we have to burn 3 hamsters an hour or 72 a day.
However with a gestation of 21 days & ~10 pups per litter we would only need to buy about 152 female hamsters to start it off. 
I suspect that it would be easier, cleaner, quieter & take less work & room just to burn hamster food at about 12,500KJ per Kg (£1.25).

**Comment by goatchurchprime** [comment]
We're not making a spud server.  This is one of the cases for vegetarianism -- that eating hamster food consumes 10x less resources than eating hamsters.  Unfortunately, less resources mean less profit, and in this economy profitability is the determining factor of what gets mass produced and promoted.  The very expensive branded hamster food should be available in accordance with ticket #613

The purpose of hamsters is to neutralize the energy of visiting children, not create energy.  

Does anyone know of one belonging to a child who's bored with it which we could borrow to see if it's popular?  Hamsters come with lots of accessories, like hamster balls.  Never put a hamster ball in a room with a staircase.

**Comment by ajlennon** [comment]
I'm not convinced hamsters neutralise children. In my experience it's electronic devices that neutralise children?

**Comment by drfraz** [comment]
I noticed about 90% of the reviews for hamster related products were from women aged 35-44. I reckon that a giant wheel powered by them would easily meet requirements.

**Comment by de14n** [comment]
So... if we can use the hamsters to charge the batteries, those batteries will then be used to power the electronic devices that neutralise the children... hence the hamsters are actually used to neutralise the children in the end.

So whichever way you look at it, it's still a closed energy cycle, albeit via electronics .. because children have lost the will to play with proper toys.

**Comment by ajlennon** [comment]
We may need to insure ourselves if we are going to bring in 35-44 year old UK citizens off the street and ask them to run...

**Comment by DoESsean** [comment]
Just to follow up on what @goatchurchprime has said, I had a hamster as a young teenager, and a room in the attic of our house. There's nothing quite like the rhythmic thudding of a hamster ball hurtling down a flight of stairs.

(For the record, the hamster was shaken but survived. The ball had obviously come slightly apart on its journey as his fur was caught between the two halves of it, but that was the only ill effect.)

**Comment by amcewen** [comment]
Not to condone throwing hamsters (or elephants) down stairs, but [this video explaining what happens if you throw an elephant from a skyscraper](https://www.youtube.com/watch?v=f7KSfjv4Oq0) shows that the fall isn't as big a deal for a hamster as it would be for us.

**Comment by drfraz** [comment]
**Hamster Pirate Radio / Numbers station**
We could use the wheel to charge a battery which when it has enough power broadcasts a short burst of recorded hamster sounds from a short wave transmitter. 
10 W is apparently more than enough! https://www.hfunderground.com/wiki/Grenade  
We could also start and end the transmission with a string of pseudo-random numbers (how many times the fridge has been opened this week) to confuse the GCHQ and Numbers station guys http://priyom.org/number-stations

**Comment by DoESsean** [comment]
I want to do that.

If we can make a Buzzfeed list about weird broadcasts sometime, my life
will be complete.

**Comment by DoESsean** [comment]
Sadly, I think this is quite a way down the list of our priorities right now, and I'm not even sure where a hamster would fit, so I'm going to close it.
