### ISSUE TITLE
Check first aid boxes

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#630]
We haven't checked the first-aid boxes in a while, we should do so (or at least no-one has documented it).

**Comment by DoESsean** [comment]
I've checked both of these - the office one is behind the coat rack, and the workshop one is on top of the little drawers next to the entrance.

Both are well stocked with plasters, sterile wipes, sterile dressings, bandages and so on, with no glaring omissions.
