### ISSUE TITLE
Buy/find/print the tube coupling collet on the Ultimaker 2

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#632]
While clearing a blockage on Prints Adam by taking off the nozzle and feeding in filament from underneath, I displaced the white plastic part that the orange clip is attached to. I wasn't able to find it, and used the one from Felicity.

**Comment by DefProc** [comment]
Or it might be possible for us to print a replacement: https://github.com/Ultimaker/Ultimaker2/tree/master/1069_Tube_Coupling_Collet_(x2)

**Comment by amcewen** [comment]
Heh, editing the comment to add the onshape link isn't any use when the emailed comment has already gone out :-D  So there's another onshape model of it too, and I've stuck the resultant STL into Somewhere Safe for future reference - https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/3Dprints/ultimaker_parts/Ultimaker-TubeCouplingCollet-1069-Z1P-A%20-%201069-Z1P-A.stl

Currently printing one off.

**Comment by amcewen** [comment]
While I'd dismantled the top of the extruder to remove the couple of cm of grey filament that was rattling round in there getting in the way of the tube going in, I also fished out the collet that had fallen in there and refitted it :-D

**Comment by jackie1050** [comment]
Great - thought it might have fallen in there, but couldn't see anything

On 20 Dec 2017 12:10, Adrian McEwen <notifications@github.com> wrote:

While I'd dismantled the top of the extruder to remove the couple of cm of grey filament that was rattling round in there getting in the way of the tube going in, I also fished out the collet that had fallen in there and refitted it :-D
