### ISSUE TITLE
Felicity needs a new tube grip clip

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#633]
The orange clip to hold the tube collet in place on Felicity is the thicker type that we modified to take up more slack on Prints Adam.  We need to fit a standard tube grip clip instead - https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/3Dprints/ultimaker_parts/Tube%20Grip%20Standard.stl

**Comment by DefProc** [comment]
Worth checking the 3D printer spares, as I did print a number (in each size) last time we needed some.

**Comment by amcewen** [comment]
Yeah, I hadn't had chance to check that when I raised the issue (and wasn't in the workshop).  There are still plenty of spares, including some of the thinner ones, so I've swapped the thick one that was on Felicity with a thinner one.
