### ISSUE TITLE
Prints Adam needs a new replacement replacement top head part

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#634]
The green plastic part at the top of the extruder on Prints Adam (which was fitted to fix #276 in April 2016) has broken.  We should print [a new one](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/3Dprints/ultimaker_parts/1320-B2P-B_1-5mm.stl) (high infill/solid maybe to see if that lasts longer, although it could be a "PLA gets brittle over time" issue)

**Comment by DefProc** [comment]
Is there a spare one around in the workshop? I seem to remember that I printed a second one, when I was trying to adjust the internal slope height for the tube clip.

**Comment by amcewen** [comment]
Hmm, dunno.  Have already kicked off a print of one, which will also check that Prints Adam is working okay with his collet refitted.

**Comment by jackie1050** [comment]
There's some new ABS in the cupboard if you waned to restart the print ...
