### ISSUE TITLE
How Can We Let People Know That They Can Do 'To-Dos'

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#638]
While there is an ever growing list of people that know about and respond to the issues in this repository, it's still sometimes seems like a closed group, and shouldn't be.

The more ideas we have, and the more hands we have to do the work, the better things will be for everyone. We need to work out how we can encourage people both to participate in discussions, and also to take on tasks autonomously and complete them.

Everything that is raised as an issue here can be taken on by anyone, so it may be worth coming up with a workflow (or something less formal) to let people know that they're not treading on toes by picking an issue and working to close it, and also how they should go about doing so (how to document things, for example).

**Comment by DoESsean** [comment]
I've added a 'How To Tackle' page on the wiki, and linked to it from the 'Make Things Better' page on the website.

**Comment by amcewen** [comment]
In case anyone else is looking, the new page is here -> [How To Tackle A 'Somebody Should' Issue](https://github.com/DoESLiverpool/somebody-should/wiki/How-To-Tackle-A-'Somebody-Should'-Issue)

Excellent work @DoESsean :100:
