### ISSUE TITLE
The storeroom in Dinky should be tidier

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#64]
You have to fight your way into the storeroom in Dinky these days.  We should tidy it up.

Things that need doing are:
- [ ] Tidy the boxes on the racking
- [ ] Get rid of the wardrobe
- [ ] Get rid of the CD racks
- [ ] Buy a new bit of plasterboard to repair where the roof caved in in the flood

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
