### ISSUE TITLE
Sell items we don't need e.g. on eBay

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#640]
While sorting through stuff to be moved to the new DoES space, we might come across items we don't need, but potentially have some value. We should look into getting some money for these, especially if anyone in the DoES community has experience of  selling on eBay etc.

We can keep a checklist of items to sell under this issue - items can be removed from the list if people think of good reasons for keeping them.

- [ ] **Cigarette vending machine** This was bought several years ago with the aim of vending Arduinos and other electronic components. Similar machines are on eBay with prices upwards of £150

**Comment by jackie1050** [comment]
Note: DoES has an eBay account - can provide details

**Comment by amcewen** [comment]
No-one will have time to get to this before we move, and we're definitely *not* taking things with us for that :-D
