### ISSUE TITLE
Reassemble Extra Large Laser Cutter

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#641]
We have disassembled the Extra Large Laser Cutter to get it upstairs in The Tapestry. It is currently in in the event space and will need to be reassembled once it is moved to its final location, so after the move.

This issue is so that I can attach some photos of the disassembly process. There has also been some discussion about whether we want to reassemble it as a laser cutter or use it as the basis for a CNC router.

**Comment by jackie1050** [comment]
I've zipped all the photos and copied them to somewhere-safe/HugeLaserCutterMove. They're on OneDrive as well though, so it could be easier if I can share that

**Comment by magman2112** [comment]
As I helped take this apart, put me down for helping to put it together as well.

**Comment by amcewen** [comment]
Given we seem to have two labels for the new cutter, I've reassigned this one to the one with the right colour-coding (as otherwise I'd have to edit the other label :-) and I'll delete the extra label.

**Comment by jackie1050** [comment]
Discussed with @magman2112 - we should partially reassemble the laser cutter to take up less space (and as a first move to recommissioning!). It would be great if people could come along to help with this at Maker night this Thursday, so it looks tidier for the party.

**Comment by magman2112** [comment]
Closing this issue as most of the discussion is now taking place in #955.
