### ISSUE TITLE
Establish a virtual textile bench with everything you need for sewing neat and tidy

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#642]
We've got two interesting sewing machines:   https://github.com/DoESLiverpool/wiki/wiki/Sewing-machines

...and a lot of disorganized fabric related stuff in the ex-sewing-club box and wearables, such as thread, zippers, pins, velcro, elastic, and so forth.  Also the laser cutters can do fabric, and there is wads of the stuff around.  

Just as there is a solder station, there is also such a thing as a textile bench:  https://hackaday.com/2017/05/23/the-textile-bench/

Textiles take up more room and require things to be laid out flat, so we can't have the whole thing out permanently.  Everything (including the sewing machines) should be packed away in a couple of shelves/drawers where they can easily be pulled out into a nearby flat area where you can do the work.

**Comment by DoESsean** [comment]
We pretty much have a textiles area now, and it seems as if those that need stuff know where it is, so I'm closing this.
