### ISSUE TITLE
Fix Inkscape on the vinyl cutter PC

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#652]
I updated Inkscape to 0.92. Now it won't load dxf files and is asking for the lxml wheel to be installed. There seem to be lots of prerequisites. I'll look at this on Thursday if nobody needs it before then.

**Comment by zarino** [comment]
@jackie1050 says this can be closed because @ajlennon is getting new PCs.

**Comment by ajlennon** [comment]
I shall take a look. I have a new Gerald here but haven't yet had the strength of character to brave the weather. @jackie1050 have you got an example dxf it won't load or do all dxf files fail?

**Comment by ajlennon** [comment]
I'll reopen this for now so I don't forget

**Comment by jackie1050** [comment]
All dxfs!

On 2 Mar 2018 08:28, Alex Lennon <notifications@github.com> wrote:

I shall take a look. I have a new Gerald here but haven't yet had the strength of character to brave the weather. @jackie1050<https://github.com/jackie1050> have you got an example dxf it won't load or do all dxf files fail?

**Comment by ajlennon** [comment]
You think this is a problem with Inkscape?

**Comment by ajlennon** [comment]
I get this with a random DXF on my laptop with Inkscape 0.92. What do you see?

![image](https://user-images.githubusercontent.com/1537834/36891326-21cbf8d2-1df9-11e8-93e7-5a7a5e64207a.png)

**Comment by jackie1050** [comment]
I don't remember - I'll be at DoES this evening for a bit, so can check then.

On 2 Mar 2018 09:07, Alex Lennon <notifications@github.com> wrote:

I get this with a random DXF on my laptop with Inkscape 0.92. What do you see?

[image]<https://user-images.githubusercontent.com/1537834/36891326-21cbf8d2-1df9-11e8-93e7-5a7a5e64207a.png>

**Comment by ajlennon** [comment]
Closing
