### ISSUE TITLE
Make a cable hanging place for shared public cables

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#653]
There are lots of spare USB, ethernet, headphone and power cables we'd like to share out, but they go in a drawer and get completely tangled up.  

Can we glue some clothespegs to a wall or pillar so we can dangle them all under gravity, perfectly straight, easy to see and fetch out when you need them?  

We could mark them with a bit of coloured tape near one end to indicate they are public property.

**Comment by Dowz77** [comment]
What about a tube wall in the new place, plastic tubes tho

![tube](https://user-images.githubusercontent.com/36996732/36935160-f603b480-1eeb-11e8-85ff-259cecd45178.jpg)

**Comment by goatchurchprime** [comment]
Can't see lengths, and they're kind of tangled when they've been rammed in there.  

The point is our cables don't need to be portable (eg in a bag).  They just need to be all out there hanging on the wall like a row of vines.  

Simplest option (which I saw in Madrid) are pegs you can hang the cables over.  But this doesn't work for short ones.  

Maybe pairs of pegs that are one cable width apart which the cable head can't get through.  Stack cables only of the same type there.  Also might be able to take spare USB mice.  Not so good with spare keyboards as the heavy end would look hung badly, though might look weird.  The 20 mains extension leads we have could hang down like an Xmas tree from one socket, and each one dangling 4 further leads plugged into their outlets.

**Comment by goatchurchprime** [comment]
I'm printing a simple openscad design for trials.  These could be screwed into any wallspace.


```

cablediameter = 3.2;
pronglength = 12; 
prongwidth = 2; 
prongheight = 4; 
backdepth = 3;
backheight = 15;

difference() {
union() {
rotate([10,0,0])
 linear_extrude(height = prongheight) {
  translate([cablediameter/2,0,0]) 
    square([prongwidth, pronglength] );
  translate([-cablediameter/2-prongwidth,0,0]) 
    square([prongwidth, pronglength] );
};

 linear_extrude(height = backheight ) {
  translate([-cablediameter/2-prongwidth,-backdepth,0]) 
    square([cablediameter+prongwidth*2, backdepth] );
 }
 
}
 
translate([0,1,backheight-4])
  rotate([90,0,0])
    cylinder(r=3/2,h=backdepth+2, $fn=30);
}



```

**Comment by zarino** [comment]
Here’s where I got to:

https://www.tinkercad.com/things/8wJbUQF5eus-cable-tidy-curved-2

![t725](https://user-images.githubusercontent.com/739624/49328360-21110400-f567-11e8-8c5d-f1ee39629731.png)

I was aiming to design a single clip that would handle everything from very narrow (lightning/usb-c style) cables, all the way up to chunky VGA/HDMI cables, all in a single design. Hence the curved "U" shape when viewing from the top. It’s almost there, but not _quite_ right yet.

It’d be interesting to see hooks like these modified to include clips on the reverse, so they could be clipped onto the wire grids we’ve been talking about in #979.

**Comment by DoESsean** [comment]
There are currently shared cables hanging next to the electronics bench, so I'm closing this issue with the caveat that it can be reopened if someone feels like they want to create something more aesthetically pleasing.
