### ISSUE TITLE
check the electronics on the workshop doorbot

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#656]
It wasn't working earlier - had to use the key

**Comment by johnmckerrell** [comment]
Rebooted but then tried the connections on the RFID board and that seems to have fixed it. It looks like the lock is actually broken though. Did someone try to force the door? I'm surprised you got it open to be honest, I can't open the latch enough that it'll shut.

**Comment by johnmckerrell** [comment]
Had a poke around in the lock, nothing seemed bent and it all seemed to work fine, I tried to refit it but it still caught so that 2-3mm of the latch hung out and the door wouldn't shut. I poked at it again and tested a bit more and this time it seems to be sorted.

**Comment by jackie1050** [comment]
No force was used by me!

I'd left my stuff in the workshop, but had been using the main room (because it was warmer). When I tried to get into the workshop again using my tag, the light came on but the door didn't open.

I suppose it's possible that an unknown person had tried to force the lock before I came back.
