### ISSUE TITLE
Help Chris and Helen with crowdfunding ideas

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#659]
I know this is kind of spammy, but it's also a way I can make sure that people see it rather than relying on anyone checking the Google Group...

@huffeec and @Helen-8 are heading up the crowdfunding effort for the move, and they're looking for ideas for reward levels. I know we have a lot of super talented people, so I'm hoping some of you might be able to offer services or ideas that can be translated into donations.

I've assigned 10 people, which is the most you're allowed, to this issue and will mention everyone else below (hence the spammy nature of it, for which I apologise, but that way I know everyone will get a notification about it) but please feel free to unassign or remove yourself if you can't help.

@fjfish @gamesquest1 @GeoSpark @goatchurchprime @helicalbytes @jackie1050 @jamieisboss @jdcormack @JimNixon @johncain39 @ka81 @Kate2000 @Madscouser @mattwilsondotuk @OddEssay @osfameron @paulfurley @paulgeering @Red-Violet @ReddbridgeMark @SayBeano @shrkey @skos-ninja @Thingomy @willcrobinson @xj25vm @zarino @DefProc @amcewen

**Comment by DoESsean** [comment]
Forgot to mention, the initial call to arms by Helen is in the Google Group, [https://groups.google.com/forum/#!topic/does-liverpool/U9J4ntMzls0](url)

**Comment by ajlennon** [comment]
I was chatting to a pal of mine earlier today. She's very active in media. The students she's current lecturing are embarking on a "comporate video" style project and I was asking her if she/they would be interested in working with DoES on some kind of promotional video. 

I'm not entirely sure in my own mind on the focus but I would expect it would bring out the positives of the new location in the Tapestry and provide a call to action to get people along...

Soraya is very enthusiatic about the idea as she perceives it as a win-win for all concerned.

So I'm bringing the idea to the table - is that something we'd like to put effort into?

**Comment by DoESsean** [comment]
That seems like a good idea to me. Not quite sure how it fits in with the crowdfunding, but it's good to hear anyway ;)

Might be worth breaking out into a separate issue so that we can discuss it there.

**Comment by euanwithersby** [comment]
Did start to reply but it seems to have disappeared! Apologies if you get this twice. If someone were to donate £100, say, to the move, what would they get in return? 10 days laser cutting, for example? They can book this already and DoES would prefer the income, I’m sure. You would need something that they can’t get already. Bespoke master class on equipment or technique (in a shorter package), perhaps, or even development time by the DoES team to prototype an idea that someone doesn’t necessarily have the skills for. This does, of course, require people’s time. On another tack there are many talented people knocking around DoES. How about getting a group together to come up with some unique products (or variations on ones that people have already done) that incorporate tech, manufacturing, wearable etc that are relatively straightforward to produce as a team but add significant value to a crowdfunding offer because of their limited run nature? IoT would seem to be interesting place to start, things that people could receive and use pretty much straight away.

**Comment by SayBeano** [comment]
Just a core list of pledge ideas taken from the GG.

- keyrings
- totebag
- mug
- 3d print
- laser cut / etch "thing(s)"
- wall of immortalisation
  - etched something on a wall/ acrylic
  - etched kitchen tiles
  - your tattoo on Adrian
  - your etch on John's fingernails
  - milliondollarhomepage (pay a dollar per pixel advertising)/ wall of bits
- Merchandise
  - could be continued to be sold
- class / masterclass
- sponsor a brick / get a certificate

I think the issue with garments are the production. The pledge should be double the cost to produce so DoES raises cash, as such if all pledges were garments, then 5K turns into 10K...maybe not quite but you see what I mean I hope.

Similarly, with classes, those delivering will either need to be an indirect cost, i.e. someone DoES employs, or a direct cost i.e. a freelancer is paid to do something.

I'm more inclined to think a pledge bank might work from the lowest cost items.

£1 (minimum) - your name on the website
(unlimited)
£10 - all the above plus a totebag
(100 only)
£15 - all the above plus a DoES mug with your name on
(100 only)
£23 - the above plus your name in vinyl in the space (random position / font / etc - DoES must maintain the design)
(50 only)
£50 - all the above plus sponsor a tile (name etched onto a kitchen tile)
(how ever many tiles, 50???)

What do the totals above means for how many mugs need doing, etc????

Then let the pledges aimed at companies...

£100 - your company on the website and your logo etched on a special Guild of Makers wall
(one dozen only)
£150 - your company logo on the website, your logo etched on a special Guild of Makers wall, 4 x 
DoES tote bags with you company logo
(one dozen only)
£200 - company logos in those places, 4 bags, 4 mugs and private view of the new space

Then consider classes...if something can be arranged...I think a master class is best...full tour and use of the equipment...includes inductions...(should include a years membership to DoES)

£300 - masterclass weekender
(limit to a dozen)

It's all held together very loosely this...but it's more of a framework than anything else...

**Comment by euanwithersby** [comment]
These are great ideas. I can see these would work well with people who know about or support DoES’ activities (I’m a big fan of the masterclass ideas). I would also advocate a plan for attracting funding from people outside of the DoES community who could have an alternative if they wanted something unique or limited edition but who weren’t necessarily makers, coders or whatever or live too far from DoES to make a visit viable.

**Comment by ajlennon** [comment]
I found this OpenSCAD plugin for 3D printing bricks. Might be of use perhaps...

https://www.thingiverse.com/thing:197171

![image](https://user-images.githubusercontent.com/1537834/36351289-5cdfe676-149f-11e8-8409-883aa4db6dab.png)

**Comment by Helen-8** [comment]
Hi everyone,

We're getting very close to launching this now! Thanks for all of your ideas and help.

One of the top levels is going to be a masterclass level, as suggested earlier.

So is anyone prepared to offer some of their time in a masterclass format or skills share workshop? Either post here or drop me an email at helen.campbell50@gmail.com with some details. It would be around 2 hours, and I think we can be pretty broad in terms of what skills we offer.

I'm a real github n00b so if this is best going somewhere else / as a separate issue let me know

Thanks

Helen

**Comment by ajlennon** [comment]
I could have a look at some kind of workshop to build and use embedded Linux

Probably based around one of my articles

https://www.codeproject.com/articles/774826/adding-rd-party-components-to-yocto-openembedded-l

https://www.codeproject.com/Articles/777108/Building-and-running-embedded-Linux-NET-applicatio

It might be too heavy for people though. We might look at something a bit more accessible perhaps?

Ideas?

**Comment by DoESsean** [comment]
The Linux idea seems bob on to me, @ajlennon - the kind of thing that people may genuinely be interested in. It might be that no-one takes it up, but it doesn't hurt to offer.

**Comment by ajlennon** [comment]
Thanks for the vote of support! I’ll expect to see you in the front row cheering me on!

A/

**Comment by goatchurchprime** [comment]
I'm much more in favour of awarding things.  The following are not my projects, so it's not up to me, but here are some examples of things that we could (finish off) manufacturing and put up a limited number of as an award with a serious profitable markup (prices in the £hundreds):
  * ackers bell, goodnightlamps, wheredial
  * doorbot + installation in another building
  * xmas tree decoration with capacitive touch game
  * made-invader boxes, optionally upgraded with an stencil to turn it into the kind of wordle clock that's on the shelf in the main room.

Another idea is sell tickets to a dinner in a restaurant.  Or it could be some kind of pre-opening dinner and party in the space with limited numbers, maybe 2 hours before the main party (so it's not obnoxiously exclusive). 

Finally, if DoESCon happens, you can sell a couple of guaranteed 15 or 30 minute keynote speaker slots at it.  I know it's like making money out of vanity publishing, but who cares?

**Comment by goatchurchprime** [comment]
I'm much more in favour of awarding things.  The following are not my projects, so it's not up to me, but here are some examples of things that we could (finish off) manufacturing and put up a limited number of as an award with a serious profitable markup (prices in the £hundreds):
  * ackers bell, goodnightlamps, wheredial
  * doorbot + installation in another building
  * xmas tree decoration with capacitive touch game
  * made-invader boxes, optionally upgraded with an stencil to turn it into the kind of wordle clock that's on the shelf in the main room.

Another idea is sell tickets to a dinner in a restaurant.  Or it could be some kind of pre-opening dinner and party in the space with limited numbers, maybe 2 hours before the main party (so it's not obnoxiously exclusive). 

Finally, if DoESCon happens, you can sell a couple of guaranteed 15 or 30 minute keynote speaker slots at it.  I know it's like making money out of vanity publishing, but who cares?

**Comment by jackie1050** [comment]
Crowdfunder has now finished and lots of great ideas were suggested, so this must have been done!
