### ISSUE TITLE
Buy a new collet for Felicity

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#662]
The tube coupling collet and clamp clip for Felicity are currently missing. If nobody knows where they are, there is a kit which contains both, along with a Bowden tube: https://3dgbire.com/products/bowden-tube

There are some downloads to print your own collet, but the originals have metal parts which might mean that they work better. The other parts would also be useful.

**Comment by DoESsean** [comment]
Is it worth me ordering one of these?

**Comment by jackie1050** [comment]
Hi Seån

As nobody else has commented, I'd say yes - this is my understanding of what's needed to get the printer working again

**Comment by DoESsean** [comment]
Great, I've ordered this from the link provided above.

**Comment by jackie1050** [comment]
Ming was able to retrieve the old collet from behind one of the cupboards while we were moving stuff around this weekend, so Felicity is back in action. Leaving the issue open until we get the new one, which will be a useful spare.

**Comment by jackie1050** [comment]
@DoESsean - Do you remember if we received the spare collet?

**Comment by DoESsean** [comment]
No idea, I'm afraid - do we need to get a new one?

**Comment by jackie1050** [comment]
This issue was only being left open so we could document the spare, so no longer relevant.
