### ISSUE TITLE
Work out how to secure new lockable coworking area

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#666]
Sliding door might be nice and take up space. Swinging door could open into the corridor if it wouldn't take so much space. Accessibility issues with sliding?

**Comment by Robotorium** [comment]
The main thing in terms of accessibility is that if your hands are occupied
with crutches or a wheelchair, holding open a door is difficult or
sometimes impossible (it is less frustrating if you hum the Krypton Factor
theme, but better if the door doesn't shut on its own).

For fire safety some doors have to be self-closing I think, so automatic
opening and closing would be brilliant for those.

The aim for doors in an ideal world is "opening and closing takes little or
no muscle strength, and one hand or fewer. Keeping it open takes none."

Op 22 feb. 2018 12:51 p.m. schreef "John McKerrell" <
notifications@github.com>:

**Comment by Robotorium** [comment]
(I am not sure what you might need in terms of visually impaired users, but
I can check. Again the aim in an ideal world is to make all things
accessible to all people, which isn't always possible but is a great goal
to strive for. Let me know if you want me to check in with the VI
community.)

Op 22 feb. 2018 1:30 p.m. schreef "Snoof Snoofington" <snoofers@gmail.com>:

**Comment by johnmckerrell** [comment]
Thanks for the prompt response!

**Comment by Robotorium** [comment]
No worries, just... Please be aware that when I say "in an ideal world" I
still know that isn't the world we live in, and compromises might have to
be made. I've had no shortage of help with the doors at Gostins, I'm sure
I'll find a way into the Tapestry :)

Op 23 feb. 2018 10:38 schreef "John McKerrell" <notifications@github.com>:

**Comment by johnmckerrell** [comment]
Thanks, the door mentioned in this issue will mostly only be an issue for people who have permanent desk access and are visiting out of hours so is probably not the highest priority for accessibility. During normal hours we'd expect it to be left open.

**Comment by zarino** [comment]
I don't have much to add about the door, but want to say @Robotorium it's super useful having your input on stuff like this 👍

**Comment by Robotorium** [comment]
My pleasure - it's novel and exciting to have them asked for and considered!

Op 23 feb. 2018 13:51 schreef "Zarino Zappia" <notifications@github.com>:

**Comment by amcewen** [comment]
Have we worked out what we're doing with this?  The builders are running low on things to be getting on with (particularly as the networking #598 might delay them boarding up the second side of the walls).

**Comment by drfraz** [comment]
As this is issue #666 how about a giant Pentangle? It would allow easy access to those with mobility issues or visual impairment while excluding those with evil intent. I'm sure Hex Ceramics & Chris Zombieking could come up with something.

**Comment by zarino** [comment]
In my head, I’ve been imagining a nice big industrial-looking sliding door. I'm under the impression that the door will likely be open 9–5 most days (as long as someone’s in the room), so having it slide open, flush against the wall, seems like a nice way to reduce its impact on space when it’s open.

The difficulty, as a few of us mentioned before, will be working out how to lock it (magnetic pad?) and how to strengthen it against brute force, since sliding mechanisms feel intuitively less solid than a single-asix rotational hinge.

If all of this is sounding way too complex, I guess we could just get Dave to build a doorway into the end of the corridor space, and fit one of our existing fireproof doors there.

**Comment by amcewen** [comment]
We're going to put the glass door (with a wood frame) into this doorway.  I've just discussed it with Dave and agreed that it should open into the short corridor, as that's effectively dead space anyway.
