### ISSUE TITLE
Work out the spec for the doors between the events and secure co-working space

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#668]
Aiming to have studwork walls on hinges rather than doors.  What height do we want the opening to be?  What door furniture (if any) do we want?

Aiming to have no skirting along the wall on the event space side, and have the doors open out to fold fully against the wall.  Architrave around the opening on the co-working side, which will help with soundproofing as well as providing a stop for the doors.

We should build supporting studwork into the doors so that they could support handles in future, if we decide not to install anything beyond some bolts.

**Comment by magman2112** [comment]
I’ve been brainstorming this for a little while, here are a few thoughts.

1. If using studwork frames use a ledger and brace design, for rigidity in multiple doors (limits sagging).
2. Cladding for doors must be fire proof.
3. Perhaps use fibreboard and cloth for cladding - can easily pin things to it. Need to ref 2 above, plus watch the overall weight.
4. Fill the door frames with sound proof padding cf 2 again.
5. Perhaps use Bi-fold door hardware, but need to check overall width required.
https://www.bullerltd.co.uk/hercules-plus-bi-folding-system.html
http://www.barrier-components.co.uk/folding-door-hardware/internal-folding-door-systems.html
6. What height do the doors need to be to provide proper sound isolation - they may even need to be full height or perhaps a studwork fixed upper wall to allow a compromise between open space/door size.

**Comment by johnmckerrell** [comment]
"These doors between the two rooms have no requirement to be fire rated"

**Comment by amcewen** [comment]
Chatting to Dave today, the current status of this is...
 * Making the doors out of studwork and plasterboard will make them too heavy (likely to sag, hard to move)
 * Using MDF or ply or similar would make them light enough, but because they're bigger than 8' x 4' there'd be some visible seams, which isn't going to look great
 * We could just board it in with plasterboard - i.e. turn it back into just a wall, but as the studwork is already built for an opening there, it'll be a bit easier to add doors later if we decide we need them

It seems to me that, given the doors there were more of a "this will help future-proof things", the best option would be to just turn that into a wall.  Then we'll have a better surface to project against (in the short term at least, until we can afford a nice big screen), and likely better sound insulation between the spaces.

We said we'd let Dave know a final decision by tomorrow (AIUI), and it looks like we'll be going with a wall.

**Comment by johnmckerrell** [comment]
A wall is fine by me. Might want to consider what is currently stored either side of it before its built. 

--
