### ISSUE TITLE
Take measurements and photos on next visit to The Tapestry

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#669]
- [x] Two RSJs in the light well, measure height, inset and overall size.
- [x] Walls around the toilets, try to measure these to improve the layout plan.
- [x] Photograph the existing skirting
- [x] Photograph the windows from the inside looking out.

**Comment by johnmckerrell** [comment]
If there's any aspect people would particularly like a photo of then feel free to make requests.

**Comment by johnmckerrell** [comment]
Internal PVC window frames are white.
![2018-02-23 09 50 12](https://user-images.githubusercontent.com/27243/36590210-d0c2394c-1885-11e8-800b-122c9a0e8265.jpg)

Photos of existing skirting and lack of architrave on main door:

![2018-02-23 09 50 00](https://user-images.githubusercontent.com/27243/36590233-e200ac16-1885-11e8-9597-e5c313fe5999.jpg)
![2018-02-23 09 49 55](https://user-images.githubusercontent.com/27243/36590234-e21bd996-1885-11e8-959d-0fb0a49683fa.jpg)

Hatch:

![2018-02-23 09 47 48](https://user-images.githubusercontent.com/27243/36590246-ede13a28-1885-11e8-8bde-36a0862da2bd.jpg)

**Comment by johnmckerrell** [comment]
Measurements around the toilets, unfortunately I didn't actually measure the slanted wall, or the opening at the other end of that corridor, I'll try to do that another time. I've shown the distances to the RSJs in the light well then the lower diagram shows a side on version to get the width and height, and height off the wall. The numbers should be accurate but the diagrams are not to scale.
![tapestry-measurements](https://user-images.githubusercontent.com/27243/36591086-b02f2a52-1888-11e8-81a5-a495ef859932.png)

**Comment by johnmckerrell** [comment]
I just updated the previous comment having got the missing measurements.

**Comment by zarino** [comment]
@johnmckerrell What’s the distance *between* the RSJs?

![rsjs](https://user-images.githubusercontent.com/739624/36808998-a3cc16b4-1cbe-11e8-8a49-ab7b34c4478d.png)

**Comment by johnmckerrell** [comment]
That's a very good question @zarino. I was assuming you could work it out from the diagram, and I think you would be ok to do that, but it wouldn't hurt to ask someone to check. I wouldn't be able to do so before Friday morning but I imagine someone else can.

**Comment by zarino** [comment]
@johnmckerrell By my very crude calculations off the architect’s map, the gap between the beams would be 1.4 metres. Seems much wider than I remember, though.

I see you’ve asked Dave to send us a measurement. Once I’ve got that, I can have a go at putting together a solution for the kitchen wall / meeting nook seating.

**Comment by Dowz77** [comment]
Have you thought about using tube clamps for building walls, screening and furniture. I used some to build a modesty wall in front of toilet doors, panelled with 18m OSB, easy to change about as the space evolves. Just thinking for the nook space.

![20180304_124536](https://user-images.githubusercontent.com/36996732/36948560-900a87e6-1fd4-11e8-967c-db809275b694.jpg)
