### ISSUE TITLE
Write up how to sign up to github and get issue notifications

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#672]
For the move we'll need to be getting as many people in the community involved in getting things done as we can, as easily as we can.

So, it would be good to get as many people as possible signed up on here, and receiving notifications.

It'd be great if someone could write up the steps needed to sign up for Github and then set the appropriate watching settings to get emails about issues (with explanations of the how the settings differ).

 * [ ] Write up process (somewhere sensible like the wiki).  Assume you're talking to @DoESsean (as a stand-in for someone who understands computers but isn't a techie and so won't know what source control is) to get the tone right.
 * [ ] Email the Google group to encourage people to follow the process

The sooner the better, given how much stuff we'll be organising in the coming weeks.

**Comment by zarino** [comment]
Thanks to @jackie1050, there is a new "Make Things Better" page at https://doesliverpool.com/make-things-better/ (also accessible via the "Community" dropdown in the main nav).

It explains what the "Somebody Should" issue tracker is for, and how you can sign up for the various levels of access required to create and manage issues.

It also links to [a new page we created on the Wiki](https://github.com/DoESLiverpool/wiki/wiki/Joining-DoES-Liverpool-on-Github), explaining how to sign up to Github, and how to request access to the DoESLiverpool Github organisation.

Before we email the Google Group, maybe a few other people could just check these new pages make sense? @amcewen @DoESsean?

**Comment by johnmckerrell** [comment]
Looks reasonable
