### ISSUE TITLE
Colour code items being moved

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#673]
We will soon be co-ordinating lots of people moving lots of things from Gostins to the Tapestry.  Not everyone will know what things are and where they should go.

We should split the area in the Tapestry into colour-coded zones and then mark everything with suitably coloured electrical tape so that it's easy to get it to roughly the right place, ready for unpacking.

 * [x] @DoESsean Can you buy as many different colours of electrical tape as you can (easily) find.  (Wilkinson and Clas Ohlson are probably the best bets if you're looking locally)
 * [x] Print out two (at least) A3 copies of the floorplan, with a brief explanation of what it's for (URL of this issue for more details, for extra credit...)
 * [x] Annotate all the floorplan copies with electrical tape
 * [x] Stick one floorplan up in the staging room for people to refer to.  
 * [ ] Stick electrical tape on all the things in the staging room at present (and do the rest as it gets packed)
 * [ ] Leave the electrical tape in the "Possibly useful for fit-out" area of the staging room so everyone can find it
 * [ ] Once we're moving things to the Tapestry, we'll also stick some up there so people know where to leave things.

**Comment by DoESsean** [comment]
Just bought two rolls each of five different coloured tapes, they're in the Staging Room with the packing materials.

Wilkinson have the colours I got at £1 each (10m per roll). Clas Ohlson had some other colours - mainly blue, to be honest - but they're much more expensive, around £5 a roll for 25m.

If we need other colours, I'm sure that will be possible, but those were the only ones that were available in Wilkinson, and Home Bargains only had normal masking tape.

**Comment by amcewen** [comment]
We've got 6 colours in total (I did an extra tape run today), and have printed out two copies of the floorplan and stuck different colours in the different areas.  If you know where something needs to go (or can make a best guess at that) then please label things with some tape when it gets put in the staging room.

![39885169104_b5946fd32d_k](https://user-images.githubusercontent.com/108468/36937330-7fbd87b0-1f09-11e8-8f98-04d66e813c77.jpg)

**Comment by amcewen** [comment]
The electrical tape didn't stay stuck on, so this hasn't been as useful as I'd hoped.
