### ISSUE TITLE
Paint all the plasterboard walls white

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#675]
Issue #650 will cover the more colourful/decorative aspects of the fit-out, but as a minimum there'll be a load of walls that just need painting white.

Any volunteers?  Anyone want to be "painting team organiser" to liaise with volunteers and arrange painting sessions once there's something to paint?

**See [painting progress whiteboard in the Tapestry](https://www.instagram.com/p/BguIvvnh6DC/?taken-by=doesliverpool) for the definitive list of things still to do** but if this issue is open, then there are still walls to paint white.

**Comment by amcewen** [comment]
@zarino Can we start to build up a list of walls here that will need painting?
@DoESsean Want to start getting some of the stuff we need ordered?

**Comment by zarino** [comment]
@amcewen Green lines here show the _sides_ of walls Dave is building, with the exception of the _inside_ of the soundproof room (because I'm not sure whether we’re finishing that?)

![walls-that-need-painting](https://user-images.githubusercontent.com/739624/36836199-9ef537ca-1d30-11e8-9846-3a8147227852.png)

I haven’t included any walls built by the landlord. I _think_ they’re all already painted? But let me know if I'm wrong on that.

By my count, it’s circa 75 metres of wall _width_. Minus a few metres for all the door holes and the windows in the workshop walls.

**Comment by DoESsean** [comment]
I've ordered the masking tape from Amazon ( [https://www.amazon.co.uk/gp/product/B01BWVLPDG/ref=ox_sc_act_title_1?smid=A13EQVWUGJ8MWB&psc=1](url) )

I don't know much about rollers and brushes, and have always just bought them locally when I've decorated at home, so if anyone can tell me otherwise I'm happy to listen and learn, but it seems that the brushes and roller sets on Amazon are more expensive than we could just pick them up for in Clas Ohlson or Home Bargains. Is there a particular reason we should be looking for a certain type of roller/brush, or will buying locally work for everyone in this instance too?

**Comment by Dowz77** [comment]
Have you thought about just sealing the bricks and plaster, good industrial look and if the plaster walls are going to be covered in art then it will be quicker, poss cheaper as opposed to a mist coat and 2 coats of emulsion.

I use these rollers for emulsion, leave a very smooth finish

https://www.toolstation.com/shop/Painting+%26+Decorating/d150/Rollers+%26+Poles/sd3171/Prodec+Advance+Roller+Sleeve+12%22/p63446

I wouldn't use vinyl emulsion on fresh plaster as it doesn't breath and cheap paint never covers as well as the big names in my experience. I would use eggshell over gloss as its easier to apply for a good finish, easier to touch up when it gets damaged and looks better in my opinion.

**Comment by jackie1050** [comment]
@Dowz77 Is this paint any good? https://www.screwfix.com/c/decorating/paint/cat850142?cm_sp=managedredirect-_-decorating-_-paint. Otherwise could you recommend some (Toolstation or Screwfix would be convenient as near to the new building)

**Comment by Dowz77** [comment]
@jackie1050 Link brings up painting section for me, https://www.screwfix.com/p/leyland-trade-contract-matt-emulsion-paint-brilliant-white-10ltr/33680 This gets good reviews, definately worth a try to see how it covers. Toolstation seem to have stopped listing 10L paints.

For masonry paint I've used this inside on bricks and concrete,  https://www.screwfix.com/p/sandtex-ultra-smooth-masonry-paint-pure-brilliant-white-10ltr/23771

**Comment by amcewen** [comment]
It seems (from spotting a tin of it in the staging room) that we've used the Leyland stuff in the past, and I don't remember it being terrible.

We aren't going to be painting any of the brick walls, etc. - we need to leave those as-is (thanks for the suggestion @Dowz77, I'm just commenting so everyone knows we aren't painting those walls :-)

**Comment by amcewen** [comment]
Just had a chat with Dave (the contractor) about painting, etc.

He's bought pre-painted skirting board, etc., so there should only be bits of touching up to do on the gloss side of things.

Once the plasterboard is up, he'll need to tape and fill the joints before it's ready for painting.  He'll only be doing that once both sides of the walls are boarded.  Which means that getting the networking sorted  #598 and doing the electrics #664 will be the critical path for letting that work proceed.

**Comment by magman2112** [comment]
Last time I was in Costco, they had large tubs of white emulsion (Crown I think) at a reasonable price. I will check in the next few days if someone doesn't beat me to it.

I should be able to make some time to help with the painting as well, after Saturday 10th.

**Comment by magman2112** [comment]
We discovered yesterday that all of the skirting and architrave is pre-primed, so will need painting, ideally before the walls are emulsioned. The new door surrounds will also need priming and painting as well.

I would see the progression as ::-

Primer on door surrounds
Gloss on door surrounds, architrave and skirting
Emulsion walls.

**Comment by johnmckerrell** [comment]
Given the amount of "character" in the space, would "only primed" add a bit more? Does finishing it add anything functionally?

Talking to Dave today he has the plasterers booked in for Thursday/Friday and he thought we'd be better off waiting until Monday before thinking of painting walls (to give the plaster time to dry off). Possibly as it's just skimmed it would be possible to do some over the weekend but it'll be pretty tight.

**Comment by Dowz77** [comment]
Spoke to a painter and decorator mate before asking for his advice on an emulsion to cover unskimmed plasterboard. He said if it requires more than two coats then unibond it first, as mentioned by John earlier. I've painted straight onto p.board previously without sealing but it was standard grey finish board and covered easily.
 He also recommended matt for walls as it hides blemishes/high spots and didn't have a good word to say about vinyl paint as apparently it will peel like skin when sanding it, doesn't recommend it for wood work. 
 This guy's been a painter longer than I've been alive and I've seen his work, it's first class, and from previous conversations i know he only ever uses Dulux, Matt for walls, eggshell for wood work.
  Place looks amazing and will regardless of what go's on the walls

**Comment by johnmckerrell** [comment]
I’ll try to pick some up and give it a go in the meeting room today. 

--

**Comment by Pezmc** [comment]
Yesterday Andy, Zarino, and I masking taped, and painted [these](http://c.pez.io/3f290D462K1g/Image%202018-03-23%20at%2010.38.37%20am.png) walls white. They've had two coats so far, but will likely need at least a third. The roller is sealed in a plastic bag with the tray.

![](http://c.pez.io/3f290D462K1g/Image%202018-03-23%20at%2010.38.37%20am.png)

Unfortunately, I neglected to take a good photo, but you can see in the right-hand side of this panorama how it looks after two coats:

![img_5911](https://user-images.githubusercontent.com/507155/37825240-05582dbc-2e87-11e8-83d6-89d59910cb7a.JPG)

**Comment by johnmckerrell** [comment]
I bought some PVA, mixed it with water and painted it onto the internal wall of the meeting room, the one adjoining the soundproof room. That’s all I had time to do today but it would be good to get some white paint on there and see if it needs fewer coats. I used a big brush and one of those big flexible buckets has the pva mix in, in that room. 

--

**Comment by johnmckerrell** [comment]
Copying Jackie's comments from the other painting story (#698):

>We have started painting the woodwork. We’re using Leyland Trade Vinyl Silk Emulsion Brilliant White. Bare wood was primed with Ronseal Knotblock primer and undercoat. The window frames and skirting boards were preprimed.

>The skim plaster between the wall panels has been slow to dry due to the cold weather. The builders will be sanding it on Monday, and then we can start painting the walls. We have some Leyland Trade Acrylic Primer Undercoat Paint White.

>Ian is bringing a platform to help with painting higher areas, probably on Tuesday evening.

I think at this point all the rooms on the Kempston Street side should be sanded as the guy was in all day yesterday doing the small workshops.

**Comment by amcewen** [comment]
Good updating @Pezmc!  Much appreciated.

Today @jackie1050 created the ["Painting Progress Chart"](https://www.instagram.com/p/BguIvvnh6DC/?taken-by=doesliverpool) on a whiteboard in the Tapestry.  That's the **definitive list** of what's still to be done.  Please update it with any progress you make.

There's white eggshell paint to be used on woodwork, and matt emulsion to use on the plasterboard.

We painted all the walls we can with diluted PVA today, and did two coats of eggshell on the woodwork in the meeting room and the East side of the main space (the walls @Pezmc marked).

**Comment by johnmckerrell** [comment]
We have ended up employing a decorator who has worked full time for 3 days to get things mostly there. A few snags are left which he'll hopefully do tomorrow (Tuesday).

**Comment by johnmckerrell** [comment]
I believe all the walls are now done. Any snags can be caught in a new issue.
