### ISSUE TITLE
Sophia not cutting

### ISSUE THREAD

**Issue by Dowz77** [DoESLiverpool/somebody-should#676]
Laser is not firing, pressing the laser button brings the led on on the HV power supply and makes a hiss noise but no output from the laser.

Today myself and Paul tested the supply to the HV (240v) ok
Tested the flow switch for continuity and when unplugged the laser will not attempt to fire. This appears to be a low voltage input direct into the HV psu.
Tested guard circuit, direct input to HV psu ok.
Electrical connections to laser tube are secure.
Electrical connections in panel are all secure.

We assume the problem lies with either the HV psu or laser tube. Does anyone with more experience know of test procedure for the HV psu to rule this out.

**Comment by Dowz77** [comment]
Myself and Paul tested the output from the tube today, looking for around 30mA DC (according to various online sources). Only measured 0.5mA when laser button pressed and 1.28mA when laser trying to cut. We conclude to HV psu is at fault.

![20180307_123219](https://user-images.githubusercontent.com/36996732/37105165-66e6c8bc-2226-11e8-94e9-d567dead3ab2.jpg)

**Comment by amcewen** [comment]
Serendipitously, Dominic from Smoke and Mirrors (who supplied the laser-tube) is in Liverpool next week and was planning on a social visit anyway... and [he's got a PSU that should do the trick as a replacement](https://twitter.com/ChickenGrylls/status/971743340659204097).

**Comment by Dowz77** [comment]
Great, perfect timing!

**Comment by amcewen** [comment]
Dominic couldn't check the PSU when he called in, as no-one was around with a key to open up the panel on Sophia.  However, he's going to post the PSU to us and we can see if it fits.  So fingers crossed we'll have it in a couple of days.

**Comment by amcewen** [comment]
We've now got the PSU.  @Dowz77, do you want to have a crack at seeing if it fits sometime?

**Comment by Dowz77** [comment]
Yeah definitely. Possibly free Monday morning or more likely Wednesday
morning if you can wait that long.

**Comment by Dowz77** [comment]
Update, New PSU fitted today but laser still failed to fire. We fitted an old tube and had an output putting a hole in a piece of masking tape when pressing the laser button. Re-fitted original PSU and laser still firing. 

To get Sophia back in action we need a new laser tube and optics.

Currently the bed and PSU are removed for spring cleaning

**Comment by amcewen** [comment]
I've just ordered a new tube and lens (50.8mm x 20mm) from Smoke and Mirrors.

**Comment by amcewen** [comment]
Dominic from Smoke and Mirrors is going to bring these with him when he calls in to have a look at the old failed tubes next Tuesday.

**Comment by amcewen** [comment]
We have the new tube and lens, but they need fitting.

**Comment by johnmckerrell** [comment]
@magman2112 installed these yesterday (with a tiny bit of help from me). I'm going to close this as the laser is now cutting but I've applied the broken tag to the wheels issue instead.
