### ISSUE TITLE
Printed materials for display at events (eg: Young Makefest, 23rd March)

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#677]
It's been suggested that DoES should have some re-usable promotional materials, to display during events.

eg: we're going to have a presence at the upcoming Young Makefest, and the Library is letting us leave stuff set up for the rest of that weekend, so it'd be good to have some posters or banners that explain:

* What DoES is (community, makerspace, co-working space)
* Something about the DoES ethos?
* How to join DoES (membership pricing, social media handles)

@jackie1050 says DoES has a black metal display we could maybe re-use for this. It has space to accommodate a large poster in the centre.

![display](https://scontent-lht6-1.cdninstagram.com/vp/e4c2c2c524111e2dfe904ecc804a99ca/5B4119EE/t51.2885-15/e35/19379853_1781582022172651_7267964106630496256_n.jpg)

It has been agreed that we can spend some money on this - especially if the stuff we make is reusable.

**Comment by zarino** [comment]
Here’s a potential pull-up banner layout, that builds on text provided by Helen:

![banner-preview](https://user-images.githubusercontent.com/739624/37564471-9182cb14-2a8e-11e8-8634-0bfa71af65c7.jpg)

Pull-up banners are super cheap these days, and easy to carry around. We should be able to get one printed and shipped in a few days.

**Comment by jackie1050** [comment]
This looks ideal for Young Makefest. If everyone's happy with this, could we order one asap.

**Comment by DoESsean** [comment]
Not to pour cold water on anything, as I like the design, but do we have
permission to use everyone's image in the header? I know the likelihood is
that no-one is going to mind, but it would be useful to know for certain.

**Comment by zarino** [comment]
@DoESsean I am ashamed to say, no, I’ve not saught permission, mostly since the photo has already been public on the DoES flickr account for 6 years https://www.flickr.com/photos/doesliverpool/7687413932 😟

**Comment by zarino** [comment]
The banner was delivered on Thursday, and used at Young Makefest on Friday.

**Comment by jackie1050** [comment]
Thanks @zarino

On 25 Mar 2018 19:40, Zarino Zappia <notifications@github.com> wrote:

The banner was delivered on Thursday, and used at Young Makefest on Friday.
