### ISSUE TITLE
Work out best use of space in lightwell between call nooks and kitchen

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#680]
The original plans showed a single wall separating the call nooks and the kitchen, in what used to be the "lightwell" in the centre of the space:

![inaccurate](https://user-images.githubusercontent.com/739624/36980246-aa5e9fc6-2081-11e8-94a1-28cfb0221757.png)

This plan wasn’t strictly accurate, as there are two structural beams crossing the full 180cm of the lightwell, roughly 35cm from the floor.

Viewed side-on, the elevation of the space, therefore, looks something like this:

![empty](https://user-images.githubusercontent.com/739624/36980353-f65772ea-2081-11e8-9009-84262075ae04.png)

(black line near the bottom is the foor, pink grid lines are 10cm apart, grey squares are the beams, orange thing is a soil pipe that runs up the wall with the windows, and dotted lines on the left and right are indicative of the extent of the brick walls on the _near_ side of the lightwell space, ie: either side of the entrances to the kitchen and the meeting nooks)

While we can happily build the left-most beam into the base of a seat or bench (perfect for the "I just need somewhere to take a quick call" use-case), the beam on the right limits what we can put against that wall of the kitchen. For instance, if we’re going to use one of the existing sink units (120cm wide, 60 cm deep, 90cm tall) then it’ll need to go _in front_ of the beam, unless we want to cut holes in it to fit the beam _inside_ the unit.

With a bench built against the left-most beam, and a sink unit propped in front of the right-most beam, that leaves us approximately 1 metre of wasted length in that space (1.8m wide). I wondered whether we could make that into a full-height storage cupboard, accessible via doors fitted above the bench, doubling up as a seat back for the bench:

![option1](https://user-images.githubusercontent.com/739624/36980750-27e12ca6-2083-11e8-9931-8d0a153ac31c.png)

The sink unit would go _beside_ the soil pipe (the sink unit is 120cm wide, in a ~180cm wide space, so there’s plenty of room) with the beam built into a stud wall behind it.

Things I’m not sure about here:

* Raised "floor" in the cupboard? It’s almost deep enough that you’d expect to be able to stand inside it. Do we want to support that?
* We’re overlapping the windows on the right. These are the windows right at the far end of the event space. Do we want to block out those windows? What finish do we use for that?

**Comment by amcewen** [comment]
Just to add another constraint to this... :-)  I happened to see @mattwilsondotuk when I was just at the Tapestry to talk through door access and #598, and we agreed that the Internet would come in and be terminated on the North side of the kitchenette in that area.  It'd be coming in over the doorway, so will be at that sort of height (but with a metre or two of cable coiled up to let us fine-tune exact positioning).

**Comment by zarino** [comment]
Would some interesting vinyl-cut patterns work as a way to treat the obscured window panes?

The way Dave is planning on building this cupboard is that the side wall will butt up to the _brick_ below the windows—rather than touching the windows themsleves—meaning there’ll be a gap of about 2 inches between wall and the glass. I have a feeling, if that wall is painted a nice shade of dark grey (to roughly match the grey on the ceiling joists) it will become mostly invisible when viewed, through the glass, from the events space. At the very least, it’ll be a lot _less_ visible than if we had something literally _blocking in_ the windows. So we might find we don’t need _anything_ on the other side to finish it off.

**Comment by zarino** [comment]
For those following along at home, here’s a rough plan (probably not to scale!) of the cupboard we’re talking about:

![screen shot 2018-03-12 at 12 13 15](https://user-images.githubusercontent.com/739624/37283161-df025444-25ee-11e8-8b79-f823bd76b072.png)

**Comment by amcewen** [comment]
As it's been built, it's _slightly_ different from your diagram @zarino - the soil pipe effectively forms that corner of the cupboard (though is still outside it), so there'll be ~10-15cm gap between the windows and the wall.  Not 100% sure how we'll get at it to paint it, as you won't be able to reach.  Will try to get hold of some grey paint so we can paint it before it gets installed.

@magman2112 also suggested we should paint the orange soil pipe in that grey too, which would also need to get done before the wood is installed.

**Comment by ajlennon** [comment]
NB. @jackie1050 and I have ordered 5m of 5cm wide frosting from these people, in the name of @DoESsean to arrive at the Gostins building in 4-5 days

https://activewindowfilms.co.uk/57-white-frosted-privacy-window-film-frost-etched-glass-sticky-back-plastic-vinyl-covering-opal-tint-sold-per-metre.html

**Comment by SayBeano** [comment]
The KPMF etch vinyl is decent - 610mm wide can be cut. Five metres minimum order would probably cover all the glass that's being thought about?

It can also be removed so it's not forever etching the glass.

It could also be put through the plotter with some designs, DoES logo in a pattern, mayber.

http://www.mdpsupplies.co.uk/etched.asp

Optionally pre-patterned could be used then just use the plotter to cut tem to size.

http://www.mdpsupplies.co.uk/decorativewindowfilms.asp

cross ref. with #714 as there was some talk IIRC in there about similar solutions to the glass by the cupboard.

Will probs want to get some application fluid and a sqeegee for these, to reduce / remove bubbling

**Comment by SayBeano** [comment]
Ack. Too late!

**Comment by ajlennon** [comment]
That looks a lot of fun @SayBeano !!! Perhaps not too late ...?

**Comment by DoESsean** [comment]
Just as a heads up, @ajlennon, I'm not going to be here after today, so you (or at least someone) will have to keep an eye out for parcels being delivered.

**Comment by ajlennon** [comment]
I'll try - where will you be?

**Comment by amcewen** [comment]
Is there anything more to do with this @zarino?  Should we break any remaining tasks into new, more specific issues?
