### ISSUE TITLE
We should have some waterproof flooring in the kitchen area

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#684]
The kitchenette area currently just has floorboards for flooring.  @magman2112 sensibly pointed out yesterday that having a floor covering that copes better with spills would be good.

It's not a huge area, and there's an obvious demarcation from kitchenette flooring to the floorboards for the rest of the space, so some vinyl or something makes most sense.

We should obviously get it in before the kitchen units get moved across...

**Comment by johnmckerrell** [comment]
FYI we've had a complaint about the noise of the fit-out from the ground floor tenants. They're being very nice about it but if you're working in the building please try to limit the noise you make between 10-3 Monday-Thursday and Saturday 9:30 - 4:30. Thanks!

**Comment by johnmckerrell** [comment]
We should do this asap, as soon as the plumbing is in we'll want to get this fitted (and before the units go in)

**Comment by ajlennon** [comment]
I’ve been to Bogan’s Carpets today. I have arranged for somebody to comes out Monday. I will attend. I will call the place over the road on Monday too (they are closed today)

I looked at Vinyl in the store. Dark grey and light grey. Costs come in at between 8 and 18 pounds per square metre not including fitting. We dicussed we need something hard wearing. 

They also showed me safety flooring which is imho much better. It comes in different colours and looks the business for what we need. £35 per square metre including fitting but I think this will last. 

They will have examples of this on Monday. I will update then 

@zarino - thoughts? 

NB size was measured at 2m 4cm x 5m 53cm

**Comment by ajlennon** [comment]
We don’t like these because of the pattern 

![265e671f-9962-442a-9878-b9b4900fc670](https://user-images.githubusercontent.com/1537834/37865430-41b305f0-2f74-11e8-8032-0cd85896679d.jpeg)

**Comment by ajlennon** [comment]
NB. We need to ensure that the network cabling #598 etc. is tested out before we put a floor in the kitchen on top of it (vinyl / safety floor) as it will then be hard to take the floor back up if there are problems

**Comment by johnmckerrell** [comment]
When are the people from Bogans coming? I can probably be around.

**Comment by ajlennon** [comment]
Expecting a call from them after 11am. 

Also I went to Beers and had a look at flooring but couldn't work out the sizing. Could go along later if you want to come?

**Comment by johnmckerrell** [comment]
We do now have a price from Bogans, just determining if it's achievable. They could fit it on Tuesday 3rd at the earliest so it will be while we're in.

**Comment by zarino** [comment]
@jackie1050 if you’re in the space this evening for Maker Night, could you check whether the edging strip has been fitted in the kitchen, and if so, close this ticket?

**Comment by johnmckerrell** [comment]
It has not, flooring guy is being pretty rubbish.

**Comment by DoESsean** [comment]
We have an edging strip now, so I'm closing this.
