### ISSUE TITLE
Put in a rack for hosting Internet connected systems / IoT systems

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#687]
Breaking this out from the wider discussion in #598 as it came up over the weekend

I am interested in the idea of DoES hosting a rack of Internet connected computer equipment as a service for DoES members and as an ongoing revenue generator for DoeS. 

Given all the work going on to put the Internet / Networking in place now seems a good time to have that discussion. Also given the work @mattwilsondotuk and co are putting into IXLiverpool.

This would need to be physcially contained and operate on a basic level of service where people manage their own problems with their own devices as DoES is not a data-centre. That said I'd be happy to help with managing the inevitable problems that crop up with any project.

I have hosted a "Linux Build Box" at DoES for some time. In fact it was one of my initial needs when I met with @amcewen on my first visit to DoeS. That's worked very well for my business needs, for me, and I think that model could be/is relevant to others.

In a similar vein, I believe the need for Internet connected IoT systems for testing is only going to increase. A space that can provide this type of facility is useful to SMEs in the IoT world. We could potentially offer connectivity through to LoRA/SigFox/NB-IoT networks and so forth. 

This leads into Liverpool being a destination of choice for people wanting to develop or test or just talk about excellence in making IoT devices work. For example today everybody in the UK has to go to Newbury to try out their NB-IoT devices. We surely want to be in a position to invite people doing interesting things with wide area IoT to visit us at DoES to try things out?

This came to mind through something I read a while ago on some guys who are co-locating your RaspberryPis. I could see this being attractive to schools for STEM and for hobbyists alike

@see https://www.raspberrypi.org/blog/raspberry-pi-colocation/

Thoughts appreciated

**Comment by ajlennon** [comment]
@amcewen when you get a chance can you remind me who that chap is who has kit that might be relevatn here? Thanks

**Comment by Pezmc** [comment]
I have an old 1U server I can donate, currently located in Manchester Universities CompSoc server room. It's not much performance wise though! 

> IBM eServer XS x336 Intel Xeon 3.6GHZ 16 GB RAM

**Comment by ajlennon** [comment]
That sounds great thanks @Pezmc

**Comment by amcewen** [comment]
Does it?  It sounds noisy.  (Not intending to look a gift horse in the mouth @Pezmc, good of you to offer it! :-)  I'm not convinced we should be hosting "proper" servers in the space, especially next to an area where we're expecting people to be taking calls :-/

**Comment by johnmckerrell** [comment]
Yes, need to remember that ventilation will be limited and the cupboard certainly won't be climate controlled too.

**Comment by ajlennon** [comment]
A server is noisy because of a noisy fan surely? Is fan replacement not an option?

**Comment by amcewen** [comment]
The numerous noisy fans, IME.  One in the power supply and a row of them across the case last time I was worrying about that sort of thing.  I think quiet servers would be okay, but they're not usually optimised for that (I think the 1U sizing doesn't help, that's optimised for packing in servers, not for providing room for air circulation and heat dissipation, so you're trying to cool something through a letterbox :-)

I think quiet servers would be okay, and room for hosting some Raspberry Pis sounds good (the MQTT server for general use that's sat by my desk would be much better suited to storing in the data cupboard :-)

I suppose I'm in favour of waiting till we know the requirements of the people using the machines (so your build box is a good example of that, and maybe having space in the data cupboard for some desktop format machines makes sense), rather than starting to collect semi-random servers :-D (if anyone wants some semi-random old servers, we're about to leave a couple that haven't ever been used behind...)

**Comment by ajlennon** [comment]
I took the noisy fan out of my build box to make it water cooled for just this reason :)

**Comment by Thingomy** [comment]
I am extremely interested in this -- i am currently paying for a fairly
expensive virtual server, which this could completely replace.

I have also considered subletting server space in the past and running my
own small scale hosting business. If anyone has a basic wordpress site etc
and needs somewhere to host it, let me know, i could organise something.

JR

**Comment by johnmckerrell** [comment]
We would need to charge for any colocating hosting that we provided of course. With membership discount we may end up cheaper than what you're getting elsewhere but we also might not be able to provide the same level of service.

Worth putting this in here too that the internet service we get on day one is unlikely to support this.

**Comment by ajlennon** [comment]
@Thingomy - as we discuss what we might be able to put in place here it would be good to get a feel for what's wanted. Perhaps you and I can have an offline conversation to discuss what "self-managed rack space" might look like in the future?

**Comment by mattwilsondotuk** [comment]
Hi everyone, hosting small servers is what IX Liverpool already does in its data centre in the Baltic from £10 a month and will soon offer it in the tapestry, see https://www.ixliverpool.net/products-services/

One of the major differences in a proper Data centre type setup it's things like UPS, standby power, redundant internet connections and cooling so your server does not overheat, and from £10 a month, it's hardly worth the hassle to bootstrap it yourself and try to build out something similar.

That said, if DoES want to offer hosting we may be able to help offer a ups for the job while Baltic Broadband can offer IPv4 and IPv6 address on demand, and more importantly access to ix liverpool's dedicated LAN for IOT devices as we want to remove as many barriers as possible from providing internet access to people and things.

**Comment by ajlennon** [comment]
Where are you hosting in the Tapestry @mattwilsondotuk ?

UPS sounds helpful - thanks!

**Comment by ajlennon** [comment]
Significant concerns have been raised regarding this idea and these would need to be addressed in order for it to be possible to move forward:

- Noise. Noise is an endemic problem in workspaces and we would need to be sure that any installed computer systems did not impact the space in a significant way.

- Heat dissipation. We would need to be convinced that heat could be dissipated safely (in which case it would be a benefit to the space) but that there would be no danger of overheating in any space in which a rack was installed.

**Comment by mattwilsondotuk** [comment]
@ajlennon we are hosting services in the basement Internet Exchange once it's built

**Comment by mattwilsondotuk** [comment]
I have a UPS for free to donate to doES if someone wants to come and collect, its heavy! but I have all of the batteries etc.  Its an APC Smart-UPS RM 5000VA XL
![8f5afed3-9a06-4e91-a745-8be980cc698d](https://user-images.githubusercontent.com/20774743/38147852-e842f3b8-344b-11e8-9d75-bea95ee24211.jpg)

**Comment by ajlennon** [comment]
Let me know when works for you @mattwilsondotuk and I'll come pick it up. How noisy is it?

Thanks! A/

**Comment by mattwilsondotuk** [comment]
This weekend? It's slient . It's a big brute and heavy so you need two
people at the other end to lift. Text us with preferred time.

**Comment by ajlennon** [comment]
Perfect. @amcewen loves silent!

Let me find a big brute for the lift and will let you know. 

Thanks Matt.

**Comment by ajlennon** [comment]
@Thingomy I picked up that UPS from @mattwilsondotuk yesterday (many thanks again!). Are you about some time to take a look at it with me?

**Comment by ajlennon** [comment]
This doesn't seem to be going anywhere so am closing
