### ISSUE TITLE
DoES Bread Machine

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#691]
After a brief discussion today, @Helen-8 and I have decided that we should get (whether that be through buying or acquiring) a breadmaker.

People eat bread every day here, and it quite fits in with our ethos to make our own. Not only that, but it would be a cool little selling point - if you come to DoES, you get fresh (and if you're there at the right time, warm) bread - and would also make the place smell fantastic, which is a brilliant first impression.

They can be bought relatively cheaply, and it might be that someone in the community is getting rid of one. It would tie in with the idea @ajlennon and I have discussed about a Food and Tech day (#470), and would surely be the centrepoint of all kinds of weird experiments.

**Comment by ajlennon** [comment]
I have one here. I need to get back on Keto. Most happy to loan it to DoES on an extended loan

**Comment by ajlennon** [comment]
Spoke to @Helen-8. I can bring in mine as and when the new space is ready and it's wanted

**Comment by ajlennon** [comment]
@johnmckerrell I think it's this one which also has the 13 hour timer limitation! :'(

https://www.panasonic.com/uk/consumer/home-appliances/breadmakers/sd-zb2512.html

**Comment by goatchurchprime** [comment]
https://arch.icte.uowm.gr/projects/breadmaker2015/  Obviouslty

**Comment by amcewen** [comment]
Ah, that's handy @goatchurchprime, but more because I've recently replaced my bread machine because the motor had gone on the old one.  And I'm intending doing some experiments in hacking the old one to see if it can be repurposed as an HDPE recycling machine (shred old plastic milk bottles; use bread machine as a convenient heating chamber to melt them into a block; use resultant blocks on the CNC mill)

**Comment by ajlennon** [comment]
Maybe a toaster first?

https://www.ted.com/talks/thomas_thwaites_how_i_built_a_toaster_from_scratch

**Comment by DoESsean** [comment]
@ajlennon, do you still have a machine that you're happy for us to take on loan? Or should I look into picking one up elsewhere?

Seems like this should be a relatively easy issue to close :)

**Comment by DoESsean** [comment]
My bad, @ajlennon - it turns out you brought this in ages ago, and no-one had told me. 

Told you this one would be easy to close!

**Comment by ajlennon** [comment]
Yeah - it's on top of the cupboard on the right hand side. Go for it @DoESsean !!!

**Comment by ajlennon** [comment]
If somebody clever could work out how to extend the timer on it that would be really useful so we could have fresh bread in the morning...

**Comment by DoESsean** [comment]
I've bought bread flour and yeast, so will make some bread on Thursday.

If anyone wants to have a go before that, the instructions are on top of my drawers, under my desk.

**Comment by ajlennon** [comment]
I brought in a book of bread recipes this other week which I think I left with @Helen-8. Might be worth a look 🍞 🍞 🍞

**Comment by DoESsean** [comment]
Also on those drawers :)

**Comment by ajlennon** [comment]
You got me wondering 💭 if we could combine this with the kombucha 🍵 experiment?

https://www.kombuchakamp.com/kombucha-recipe-sourdough-kombucha-bread-starter-plus-more-recipes

**Comment by DoESsean** [comment]
I mean, that definitely sounds gross, because whatever is in those jars _looks_ gross, but if someone else wants to do all the dirty work, I'm sure it will turn out brilliantly!

It's very 'DoES' to use all the excess bits too. Possibly start a new issue for that?

**Comment by jackie1050** [comment]
Lets not - no intention of consuming anything kombucha-related after reading the wiki article. Basically seems to have the same risks as drinking moonshine but without the upside.

**Comment by ajlennon** [comment]
The voice of reason triumphs :smile:

**Comment by DoESsean** [comment]
Told you it was gross.

**Comment by jackie1050** [comment]
Can I use that as a character reference? 😋

On 4 Sep 2018 13:05, Alex Lennon <notifications@github.com> wrote:

The voice of reason triumphs 😄

**Comment by ajlennon** [comment]
Absolutely! 🤣

**Comment by mdunschen** [comment]
This is on a slight tangent, but still relevant to bread recipes:

I've been making my own sourdough breads for some years now, and I never
use a bread maker, just an ordinary oven. In fact I don't think a bread
maker where you toss in the ingredients and then have the little paddle at
the bottom of the pan to mix it, then prove, would work. I mix in a bowl
and prove in bannetons, or if I make a very grain rich danish style loaf (
*Rugbrød*  ) I use a loaf tin. If anybody would like to know more or have a
share from my sourdough starter or a chat about how I make bread, let me
know.

**Comment by ajlennon** [comment]
I didn't want to mention as I didn't want to overcomplicate but this breadmaker has a starter recipe so you can make your starter, keep it in the fridge then use as and when needed for a loaf

**Comment by ajlennon** [comment]
Or presumably we could use your starter with the appropriate loaf recipe :smile:

**Comment by DoESsean** [comment]
![img_20180906_135612](https://user-images.githubusercontent.com/9075760/45158946-5c589c80-b1dd-11e8-807b-30814d076a18.jpg)

The first loaf has rolled (ha!) off the assembly line. Basic white to begin with, but we can get fancy in future.

**Comment by ajlennon** [comment]
Beautiful! And how did it taste?

**Comment by DoESsean** [comment]
It was good, needed a little more salt but the next loaf will fix that.

Might make some on Thursday afternoon for the Community Meeting.
