### ISSUE TITLE
Lighting review

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#694]
Someone should review the lighting as is limited in some areas e.g. “corridor-type” areas. Before the electrician finishes his work.

**Comment by amcewen** [comment]
As the electrician is on holiday until after we've moved in, juggling the labels.

**Comment by johnmckerrell** [comment]
Any thoughts on this @jackie1050 ? They've fitted a super bright light by the door to the events room. Do we need any more? I guess in the corridor to room 29 would be the obvious one. ISTR the emergency light by the emergency exit is pretty bright though.

**Comment by jackie1050** [comment]
I suppose that ideally there should be a light immediately outside the door, but given the brightness of the emergency light I'm happy to close this.
