### ISSUE TITLE
Review of flooring

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#696]
We should check all the flooring and decide whether any action is required:

- We’ll need some new floorboards in meeting rooms as they were damaged when pulled up for cabling.
- Flooring between the main door and fire escape is in poorer condition than the rest and may need action
- We should vacuum under the floorboards

**Comment by jackie1050** [comment]
One of the new floorboards in the co-working space has been put in with its grey painted side upwards

**Comment by johnmckerrell** [comment]
Closing this as a duplicate of #696
