### ISSUE TITLE
Paint fire doors

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#697]
- varnish needs stripping before painting
- ideally done before doors are hung but can be done afterwards if necessary (the builder intends to hang these very soon, and has brought other doors across, as some of the ones we brought weren’t suitable)
- @magman2112 has some sanders which he’ll bring in

**Comment by amcewen** [comment]
The sanders are in the Tapestry, and @jackie1050 sanded down two of the doors today.  @magman2112 has put one coat of grey primer on one side of one.

**Comment by amcewen** [comment]
Progress on this is being tracked in more detail on the whiteboard by the accessible toilet.  At present two of the doors are primed and awaiting top coats and the rest are awaiting priming.

**Comment by amcewen** [comment]
Sound proof room has two coats on the outside, one coat on the inside.

Laser room has one coat on both sides

Dinky needs oil paint cleaning off and then painting.

**Comment by magman2112** [comment]
Dinky now has the old paint removed and one coat of new paint on each side. 

The Laser room has now had it’s second coat of paint and is effectively finished. It even has the final hardware installed.

**Comment by johnmckerrell** [comment]
I feel like this should be considered done now? We didn't paint the door to room 29 but I don't think that was intended anyway?
