### ISSUE TITLE
Painting 

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#698]
We have started painting the woodwork. We’re using Leyland Trade Vinyl Silk Emulsion Brilliant White. Bare wood was primed with Ronseal Knotblock primer and undercoat. The window frames and skirting boards were preprimed.

The skim plaster between the wall panels has been slow to dry due to the cold weather. The builders will be sanding it on Monday, and then we can start painting the walls. We have some Leyland Trade Acrylic Primer Undercoat Paint White.

Ian is bringing a platform to help with painting higher areas, probably on Tuesday evening.

**Comment by Pezmc** [comment]
The builders were still sanding yesterday (Thursday), IIRC, he has about half of the walls left to sand, which I believe are the ones on the left as you enter (Sink/Metal Workshop/Wood Workshop).

He'd definitely done the sound-proof room in and out, and the meeting room in and out.

**Comment by johnmckerrell** [comment]
There's more discussion in #675 so I'm going to close this issue as a dupe.
