### ISSUE TITLE
List of building snags

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#700]
We need to make sure the following are dealt with:

- [ ] There are lots of gaps in the floor/ceiling of the floor below, allowing draughts, sound and light to get through.
- [ ] Some holes to the outside haven’t yet been filled e.g. above fire door and at corner of office window
- [ ] Gaps around the wall to the corridor in the woodwork room
- [ ] There’s a leak in the front left corner of the woodwork room
- [x] There are broken panes of glass in the internal glass partition
- [x] Cable to external key box on front roller shutter needs securing, as it is snagging on door as it opens
- [ ] There is an area in the less accessible toilet area that appears to be damp. Need to have an expert confirm and possibly treat.
- [x] The water heater in the accessible toilet is plumbed and wired in (and you can hear the relay click in when you run the tap) but the water doesn't get heated
- [x] Smaller toilet door is missing a handle
- [x] Water heater in toilets is not functional although is wired in (may need upgrading)
- [x] The ~ancient~ antique fuse boxes need removing as they have possible traces of asbestos
- [x] Water from the air conditioning outlet is soaking into a large area on the outside wall, and also pooling on the fire escape, causing rusting
- [x] Air-con in Room 29 is dripping
- [x] Air-con in main room still ices up

**Comment by magman2112** [comment]
There don’t appear to be any lights in the toilets on the DoES floor. Is this a landlord issue or something DoES needs to provide?

Also, the bathrooms themselves aren’t quite finished - broken toilet seats and loose taps etc.

**Comment by johnmckerrell** [comment]
Damp in non-accessible toilet.

**Comment by magman2112** [comment]
The window in the non-accessible toilet is not sealed. The tap in this room is also loose.

The new window in the co-working area has not been fully sealed.

There are a couple of cables going through the external wall in the meeting room and co-working area’s that need confirmation if they are still required and removal if not required.

**Comment by johnmckerrell** [comment]
I believe original contractors will be back on our floor this week working on snags as well as air con. 

--

**Comment by johnmckerrell** [comment]
Pushed this to blocked as there's not really anything we can do about it but we want to keep the issue around and visible.

**Comment by johnmckerrell** [comment]
@magman2112 the cables can be removed although feel free to wait until I'm in the space to confirm with me before clipping!

**Comment by magman2112** [comment]
The non-accessible toilet does not have a door handle. At least one person has been stuck in this toilet already (needed help from someone outside to get them out).

**Comment by magman2112** [comment]
There appears to be a damp section of the brick wall in the meeting nook adjacent to the toilet. I’m not sure if this is recent, as we had some heavy rain prior to today, or is an older leak that has already been fixed.

**Comment by huffeec** [comment]
It was mentioned to me tonight at Makernight that there are gaps between the partition walls that form the workshop. Anyone speaking in the woodworking room can be clearly heard in the stairwell to the upper floor.

**Comment by johnmckerrell** [comment]
Jason mentioned that the damp in the toilets is due to a leak that has now been fixed but the damp in the walls won’t fully dry out until we get some warmer weather but that they will keep an eye on it and repaint as necessary. I imagine this is the same but we should report it all the same. 

--

**Comment by Thingomy** [comment]
Has someone reset the "days since last flood" timer?

**Comment by amcewen** [comment]
Mick has wired in the water heater and although you hear the relay click when the tap is turned on, the water doesn't get heated at all.

**Comment by johnmckerrell** [comment]
Any evidence of the leak in the corner of the wood workshop today? Was raining quite a lot.

**Comment by johnmckerrell** [comment]
I believe I've made sure that every comment above this one is covered by the checklist in the issue description.

I mentioned the water heater to Jason's contractors yesterday and they commented that there's a reset button which might need pressing and he'd do that very soon. I have a strong feeling he forgot. Possibly we can try that although I have a feeling Mick the electrician would have known about this and tried it. Seems like something we can manage to try ourselves (be careful, live electricity, find the fuse!)

**Comment by amcewen** [comment]
Mick did know about reset buttons, but couldn't see one on that heater and hasn't pressed it.

I've since found the [user manual for the DHM 6 water heater](https://www.stiebel-eltron.co.uk/content/dam/ste/cdbassets/current/bedienungs-_u_installationsanleitungen/DHM_6_-_220__e7a4f71e-4785-11e7-af5f-005056a95add.pdf) which doesn't mention anything about reset buttons.  I followed the "initial setup" instructions in that, which are just "turn on hot tap, then switch on power to the water heater" but that hasn't made any difference.

There's definitely 240V getting to the heater (checked with a meter) and the safety pressure limiter seems okay (low resistance across it) and you can see the pressure differential switch work as you turn the tap on and off (and the resistance across it changes accordingly too).

So I can't see anything wrong with it either, apart from the lack of hot water from it...

**Comment by johnmckerrell** [comment]
Jason's been told there's a trace of asbestos in the antique fusebox next to the kitchen. It will be safe so long as no-one does anything to it and it will get removed as soon as possible along with a few other "antiques".

**Comment by johnmckerrell** [comment]
Smaller toilet door has a handle!

**Comment by amcewen** [comment]
We have hot water in the toilets!  A first for DoES in seven years!  New hot water heater fitted and functioning.

**Comment by amcewen** [comment]
The fusebox issue is covered in #831

**Comment by amcewen** [comment]
I've told Jason about the water outlet and rust/pooling issue, and the problem with the units still icing up.  The new aircon engineers are in today fitting the aircon in the events space (and will then move onto Room 29), so Jason will get them to sort the aircon in the main room too.

The unit in the events space is a central room one (like the main room) rather than against the wall, and they're going to run the pipework for the one in Room 29 out under the window on the end wall, rather than through the partition wall.

**Comment by johnmckerrell** [comment]
Added air con snags to the list.

**Comment by johnmckerrell** [comment]
Room 29 air con should now be sorted, needs leaving off for the rest of the day and then testing sometime to confirm. PVC pipe joint had simply been missed.

**Comment by amcewen** [comment]
The air-con engineers are going to be working on the North side (main room) air-con units sometime soon to fix both the water on the fire escape and the icing up issues.

That'll take two days - one day outside moving the unit there to below the fire escape; and one inside to sort out the problems with the install.  I expect that'll mean we have no heating in the main space for those two days, so we'll need to decamp to Room 29 during that time.  They've suggested 14th/15th November to do it, so unless anyone shouts that those aren't good days, I'll confirm with them later this afternoon.

**Comment by amcewen** [comment]
The air-con things are done.  The gaps are all covered better in #1034 and #1070, and I've spun the painting-the-damp-patch as #1099, so I think we can close this now.
