### ISSUE TITLE
Investigate obtaining more ladders for use in Tapestry.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#702]
As the new space in Tapestry has fantastic high ceilings, it may make sense in the future to use storage space at higher levels. This will require the use of ladders, obviously. 

There are a set of folding ladders already in the space, but it may be useful to obtain something like library ladders or some taller step ladders to safely use any higher level storage.

**Comment by DoESsean** [comment]
No current super high storage (and, ironically, big ladders would be a pain to store too) so, for the time being, I'm closing this issue.
