### ISSUE TITLE
Promote our Crowdfunder campaign far, wide and often!

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#704]
To help pay for the move we're running a Crowdfunder campaign.  You can find it at http://bit.ly/DoEpicFunding

@Helen-8, @DoESsean and @huffeec have done a great job of pulling it all together, along with some sterling super-quick-turnaround audio and video work from Simon Derwent and Andy Goodwin.

Now we need to get the word out and keep being noisier than us geeks are comfortable with ;-) for the next four weeks while the campaign is live.

We've hit the ground running with over a grand raised in the first 12 hours, but there's plenty still to raise, and we can always blow through the initial target and raise even more money to make the new space even more epic :-D

We should look for a *minimum* of one post per week to each of these channels, and the more the merrier.
 * [x] Post on our own website
 * [x] Post to the Google Group
 * [x] Post to the mailchimp announcements list
 * [x] Post to Twitter
 * [x] Post to Instagram
 * [x] Post to Facebook
 * [x] Post to LinkedIn

Please share any/all of this with your friend, relatives, neighbours, people you pass in the street... It's even better if you can post something *in your own words* and tag @DoESLiverpool in it because (a) it'll show the breadth of interests and (b) it gives the DoES Liverpool accounts something more that _they_ can share too.

If you contact specific individuals or organisations that might be contacted by others then list them below so that we don't end up spamming people too much:
(Would also be worth checking first if they've already promoted us anyway)
 * [x] Gary Millar - https://twitter.com/DoESLiverpool/status/976424629815463942
 * [x] Village Software - @johnmckerrell contacted Johnny Read 21/03/2018
 * [x] @IndpndtLiv Independent Liverpool
 * [x] @ohthisway on Twitter
 * [x] @FACT_Liverpool
 * [ ] @MakeNorthDocks
 * Other Makerspaces, hackspaces
  * [x] Hack Oldham
  * [x] MadLab
  * [ ] Cambridge Makespace
  * [x] UK Hackspace Foundation Mailing List
  * ...
 * [ ] Sensor City
 * [ ] Liverpool Science Park (hey they've promoted stuff for us way back in the past)
 * [ ] Ethos Magazine
 * [ ] Social Enterprise Network
 * [ ] Social Enterprise UK
 * ...

**Comment by amcewen** [comment]
And if you're offering a course for part of the `Evil Genius` reward level, posting details of what you'd offer would be great for us to share those more widely.  They're a bit hidden away at the moment as there are too many of them to list as separate rewards

**Comment by johnmckerrell** [comment]
I've tweeted at Gary Millar asking for a retweet/promotion (from the DoES twitter account), he's in China at the moment though so might be a bit busy!

**Comment by johnmckerrell** [comment]
We obviously need to do one (or more) of those hideously spammy "@<seventy five different people> please RT our campaign!1" tweets

**Comment by amcewen** [comment]
Yes, there are plans for that but we ran out of time getting the campaign itself live before @DoESsean left yesterday.  I think @Helen-8, him and I are going to be building some lists of people to contact tomorrow (but don't let that stop anyone from contacting people from your personal accounts!  A request from someone you know rather than an organisation you know is going to be better in getting a response, IMHO)

@Helen-8 is also looking at pulling together some images that people can use when sharing things, as that makes them stand out more.

**Comment by johnmckerrell** [comment]
I think it's worth posting here if you contact any organisations so that we don't spam them from multiple angles. In fact I'll edit the post above.

**Comment by ajlennon** [comment]
Tweeted :

[] Open Data Manchester
[] The Federation Manchester

**Comment by zarino** [comment]
Closing this, as the crowdfunder has now ended (and we raised over £7500!) 🎉  So I’m guessing there’s nothing to promote any more.

Reopen if you feel otherwise.
