### ISSUE TITLE
Clear out staging room and Dinky ASAP

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#705]
Gostins have managed to rent out our rooms already. I spoke to Janette and she suggested if they could have Dinky and maybe the staging room that would help them get their stuff moved over so we should try to clear those two out. Room 29 and the Fridge aren't really doing much at the moment so I'd think we could move stuff into those.

**Comment by jackie1050** [comment]
Could you wait until tomorrow to move stuff into room 29 please, as Ive go a couple of things in there for Young Makefest

On 22 Mar 2018 09:37, John McKerrell <notifications@github.com> wrote:

Gostins have managed to rent out our rooms already. I spoke to Janette and she suggested if they could have Dinky and maybe the staging room that would help them get their stuff moved over so we should try to clear those two out. Room 29 and the Fridge aren't really doing much at the moment so I'd think we could move stuff into those.

**Comment by amcewen** [comment]
@johnmckerrell informs me that everything has been removed from Dinky and the Staging Room now, so if you think you'd left anything there then double-check it before Monday.

The doorbot still needs to be removed, so I'll leave this issue open until that's done.

**Comment by amcewen** [comment]
Doorbot has been removed, and everything else apart from the Things Network gateway are out.  I assume that @DefProc is taking care of that, so there's nothing left for us to do on this.

**Comment by DefProc** [comment]
The ttn-liv gateway is out, and the temporary Things Gateway is running in the main room. I'm all cleared out from Dinky now...
