### ISSUE TITLE
Record a time-lapse of the painting

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#706]
Bit late now but thought I'd throw this in. If anyone can manage to get something set up it might be interesting to have. The built in iOS camera will do it these days so that could be an option, you'd just need to make sure it stayed plugged in, and we'd need a tripod and mount (both of which we have I'm just not sure where). Other suggestions welcome. I'm not going to be there today though so can't do much about this.

**Comment by drfraz** [comment]
If only someone had a camera that took a photo on a regular basis & maybe uploaded the image ....
Fomocam could do with a test run so I'll try & sort it out today.

**Comment by ajlennon** [comment]
Brilliant. I love #FomoCam. I can't wait to see the end result. Do we need to keep it charged? Can we tell when it's out of juice @drfraz ?

**Comment by drfraz** [comment]
It will need a bit of power now & again. There are 3 blue lights on the big black battery showing the charge when it is on. It just needs connecting to a USB from the small free port on the battery.
If the last to leave / first to arrive just press the black button on the battery that would be great!
flashing lights = on     no lights = off

**Comment by amcewen** [comment]
I turned it off before I left earlier.  7ish, I expect.

**Comment by DoESsean** [comment]
If this isn't already done, it's too late now as the painting is finished. I'll close the issue.
