### ISSUE TITLE
Flooring for the quiet coworking room (Room 29)

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#707]
We need to review the current state of the flooring in the quiet coworking room and make a plan for what we need to do with it and when. There will be small fixes needed but we need to decide if a bigger change is needed and when?

**Comment by ajlennon** [comment]
As with meeting room and events room we are suggesting

- carpetting the events space
- there are a lot of knots which may need to be sanded down
- a decent underlay and putting in mid-grey hard-wearing airport lounge standard carpet (RAL7016 ish)

**Comment by johnmckerrell** [comment]
We will probably have a better idea what we'd like to do in here once we clear some stuff out. The floor in here seems worse than in Dinky but then the floor in there seemed bad until we cleaned it up and fixed it down. Obvious options again are to scrub and varnish or ply and carpet.

**Comment by johnmckerrell** [comment]
Looks like we should go ahead with this as soon as possible really. I'll talk to the contractors about where the aircon is going and if they can safely install it without damaging a new floor or if we should wait until they're done. It might be worth having a further thought about where desks will go, my thoughts have always followed @zarino's diagram with banks of desks coming away from the wall, and so we haven't put floor boxes in here. If we might want floor boxes we'll want to decide before carpeting!

**Comment by johnmckerrell** [comment]
This is now blocked by #816

**Comment by johnmckerrell** [comment]
I've requested an updated quote from Bogans, intending for work to begin as soon as they can manage (although no sooner than the 16th due to #967).

**Comment by johnmckerrell** [comment]
Carpet is being fitted on the 19th! We need to clear the space before then but won't be able to do that until the air con work mentioned in #967 is completed.

**Comment by mdunschen** [comment]
I can help clearing out Room 29 on 17th and possibly on 16th in the evening
after work.

**Comment by johnmckerrell** [comment]
I’m hoping to get some done tonight at maker night. I’ll report back what needs doing tomorrow. 

--

**Comment by johnmckerrell** [comment]
The room has now been cleared, just @mdunschen's stuff for him to move out and Paul Furley's for.. someone to move out, just hoping to hear back from him that his computer is safe to reboot.

**Comment by ajlennon** [comment]
Great job! How are my tables? Do you need me to do anything?

**Comment by johnmckerrell** [comment]
Everything went through the door without deconstruction (or damage to doors or walls!) No you’re all good.

**Comment by ajlennon** [comment]
Oh fantastic 👍

**Comment by johnmckerrell** [comment]
This is now done! 🎊 🍾 🚀

**Comment by ajlennon** [comment]
It looks like I'll be in for MakerNight on Thursday if anybody needs help moving anything back in
