### ISSUE TITLE
Flooring for the events room

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#708]
We need to review the current state of the flooring in the event room and make a plan for what we need to do with it and when. There will be small fixes needed but we need to decide if a bigger change is needed and when?

**Comment by ajlennon** [comment]
As with meeting room and quiet work area we are suggesting

- carpetting the events space
- there are a lot of knots which may need to be sanded down
- a decent underlay and putting in mid-grey hard-wearing airport lounge standard carpet (RAL7016 ish)

**Comment by ajlennon** [comment]
What's the process for determining if the pricing is achievable @johnmckerrell ? Can I ask that we make a decision collectively soon so we have a chance of getting the work done for 9th, or alternatively give ourselves breathing space to do something else

**Comment by johnmckerrell** [comment]
In a private chat I think we'd (directors) largely come to the conclusion that it might be but were discussing colours a little. I had wondered about calling a carpet company I've used before though to at least get a comparison quote. If I can determine basic square footage hopefully they'll give me something useful over the phone in the morning.

**Comment by ajlennon** [comment]
I just had a call from Peter at Bogan's @johnmckerrell just checking that we had the details.

I confirmed you'd received them and he asked that, if we want any work done next week we let them know today or tomorrow as with the bank holiday weekend they'll otherwise have trouble getting stock in in time.

**Comment by johnmckerrell** [comment]
Yeah, I'm basically happy to go ahead with this. @magman2112 might want to go ahead and wire in some ethernet to the floor boxes first and this room will take second priority after Room 29.

**Comment by johnmckerrell** [comment]
Also this room will have more of the air-con work in (at least it will have trays running across the length of its ceiling) so we might want to delay until that's done.

**Comment by johnmckerrell** [comment]
I've requested an updated quote from Bogans. We're pretty much ready to do this as soon as possible but have a regular booking Tuesday - Friday which will make it tricky. I've asked about whether we'd be able to do it during the Christmas holiday period as the regular booking won't be occurring.

**Comment by johnmckerrell** [comment]
This has been booked to be fitted on the 27th and 28th December.

**Comment by jackie1050** [comment]
The floor has now been scrubbed ready for varnishing later this week, and the larger knots have been sanded down. 
Might be worth disconnecting the neopixel lights temporarily to clear this area of the floor.
There's still a small amount of paint that needs to be scraped off.
@magman2112 intends to fix down the trim round the edge of the room, and also to seal any gaps (although this could be done later).
We have 2 cans of the varnish we used in the main space - may need more?

**Comment by jackie1050** [comment]
The floor has now been varnished with 2 coats of Screwfix No Nonsense Quick-Dry Floor Varnish Satin 2.5Ltr (95447)
