### ISSUE TITLE
Should we create pre-loaded RFID fobs?

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#71]
Spinning out this question/discussion from issue #68, because it's a different topic :-)

@DoESsean said:

As a future thing, is it possible to preload an RFID tag with a certain amount of credit? Might be a good idea to offer that to workshop users who don't have a membership so they can pay in advance the way that Main Room hotdeskers can.

To which @johnmckerrell replied:

Hm.. I quite like the idea of pre-loaded RFID, this would be fairly easy as we'd just assign the days to "PRELOAD1", "PRELOAD2", .. "PRELOADN" and then set the name for that RFID ID in doorbot to "PRELOAD1" etc. I don't quite understand the second part of your suggestion though, workshop people can pay in advance the same way that main room people do, but I see that this might be easier for some people to deal with as they can just pay money and get a card/fob without having to be invoiced. In fact this might make charging easier for people who are less au fait with FreeAgent, they can know there's a box of fobs for 2 days, 4 days, etc. that they can simply sell. We do need to remember to always induct people so that we know they're aware of the safety precautions! Perhaps the fob comes in an envelope with a link on saying "You must fill in this form before using this fob". One issue with this though is that when the person goes into negative numbers there's no actual warning and unless they do induct (and we add a field for "your fob's ID") we won't actually know who to chase.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by amcewen** [comment]
Yeah, filing this in the nice idea but not going to happen bucket...
