### ISSUE TITLE
Flooring for the meeting nooks

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#710]
We need to review the current state of the flooring in the meeting nooks and make a plan for what we need to do with it and when. There will be small fixes needed but we need to decide if a bigger change is needed and when?

**Comment by ajlennon** [comment]
The floor boards in the meeting nook area are fine.

The wood needs to be "caulked" and "sealed" (varnished or painted) 

Same as issue #713

**Comment by johnmckerrell** [comment]
Carpet is covered by the quote mentioned in #712

**Comment by amcewen** [comment]
The meeting nook has been covered in plywood and then carpeted.
