### ISSUE TITLE
Flooring in the main room

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#712]
We need to review the current state of the flooring in the main part of the space, beyond the part between the emergency exits, and make a plan for what we need to do with it and when. There will be small fixes needed but we need to decide if a bigger change is needed and when?

**Comment by magman2112** [comment]
The space towards the central wall appears to be the most damaged area of the floor at present. This is 11.3m by 3.8m (or 4.1m to the next joist). This is the area that most likely needs replacement. The current floorboards are 25mm thick where not badly worn.

Options are:-
1. Use modern tongue and groove floorboards (which are normally 18mm thick), to replace the damaged area’s. This may require additional strips of 7mm thick wood on the joists to bring the floor up to its original level.
2. Find reclaimed floorboards of the same thickness and replace the area’s that are most damaged.
3. Use sheet material, such as plywood, that is 25mm thickness to replace the damaged area.

Open to other idea’s that people may have.

**Comment by ajlennon** [comment]
I was thinking that the advice from the builder sounded very sensible. Unless we take up the whole floor in the main area then fixing the damaged floorboards is inevitably going to result in an area that looks different from the original.

If we try to make the replacement look similar then we’ll end up with some thing that looks crap (imho)

Thus I agree with his thinking that we make a feature of it. Visitors will walk through the main door into the space and be confronted by this strip. So let’s make it nice for them to se

**Comment by ajlennon** [comment]
I am going to be involved in talking to people about the vinyl and feeding back.

I am happy to talk to people about costs and timescales for the replacement to the floorboards (and happy not to!) 

What do we need to know to agree a course of action as this seems to be in the critical path? 

@magman2112 @jackie1050 @johnmckerrell ?

**Comment by johnmckerrell** [comment]
Yes I’d definitely say we shouldn’t try to make them the same. The height difference could even potentially be ok (maybe, I could be wrong). Can we find a price for new floorboards and ply panels and decide from there? Might be worth deciding the area to cover based on the size of the material, saves on some cutting?

--

**Comment by ajlennon** [comment]
I can't see pricing on floorboards so unless somebody has already looked at this I am going to head to B&Q on the way in and investigate (now).

Any specifics on what I should look into would be appreciated.

In the meantime I'll go with @magman2112 's analysis of

"This is 11.3m by 3.8m (or 4.1m to the next joist). This is the area that most likely needs replacement. The current floorboards are 25mm thick where not badly worn."

**Comment by ajlennon** [comment]
Recapping meeting with @zarino this afternoon.

- there are really bad floorboards near the rented quiet room. These need to be replaced.

- if we replace these floorboards the area will look pretty bad so we're thinking of putting down carpet

- this would partially cover the main space, go into the meeting nooks area, go around into the quiet working area which we are talking about carpetting.

Zarino has hatched out an area for carpetting in mid-grey, airport quality hard wearing material, with a decent underlay. We would need some "beading" to separate the main area carpetting from the remaining wooden workspace area. This seems unavoidable.

- although the meeting room area is hatched in this diagram we have since discussed, as noted in #709 that we may **not** wish to carpet the room, but will get a quote

However there are concerns about how much this will cost (@johnmckerrell) and we may need to prioritise...

![image](https://user-images.githubusercontent.com/1537834/37876587-6af67ec4-3046-11e8-9442-390c6b579fe7.png)

**Comment by johnmckerrell** [comment]
We now have a price from Bogans to carpet the section in the main room shown there and vinyl the kitchen. That also involves plying that section so no further work would be needed on those floorboards. We're just determining whether or not the price is attainable.

There will still be repairs needed in the rest of the space but this is the workshop so floorboards is a decent option there (and they mostly don't have gaps given it's tongue & groove).

**Comment by johnmckerrell** [comment]
They could fit it on Tuesday 3rd at the earliest so it will be while we're in.

**Comment by johnmckerrell** [comment]
62sqm emergency exits area and meeting nook, 14sqm kitchen nook (vaguely) = 76

Calculating from the Bogans quote this area should be 90sqm though so not sure why I get it lower, taking another metre from the main space adds 10sqm so maybe that's it. Just taking some notes for a comparison quote.

**Comment by johnmckerrell** [comment]
Just requested 90 square metres of plywood to be fitted, then 15 square metres of vinyl flooring and 75 square metres of carpet from Woolton Carpet Centre but they were a few hundred more then the non-discounted price we were offered.

Regarding colours, I was originally thinking the Anthracite to match.. everything else, but there's been a suggestion that a lighter colour would be better. There's not a lot of options though in the cheap versions. The light grey feels too light to me but I'm not holding my opinion strongly. Anyone fancy taking a photo and photoshopping? I'm not sure we've made a choice for the vinyl.

I did get a bit worried yesterday that the carpet would be ruined by people walking from the boards in the rest of the room onto the carpet and tracking a lot of dust in, but it sounds like we might be able to wash the dust off anyway. More discussion of that on #709. We should have a section of welcome matting to clear dust off shoes as you enter the space, whether that's inside or outside our space.
 
![2018-03-26 15 42 49](https://user-images.githubusercontent.com/27243/38020418-13721644-3272-11e8-9dac-1cdd449209db.jpg)
![2018-03-26 15 42 43](https://user-images.githubusercontent.com/27243/38020419-13a951e0-3272-11e8-8266-66b5bce10eb4.jpg)

**Comment by johnmckerrell** [comment]
@ajlennon That's correct (tbf it was an estimate but seemed high enough that they probably wouldn't be able to come down to the same price)

**Comment by magman2112** [comment]
A man from the flooring supplier across the road from Tapestry called in this afternoon. He seemed very keen to provide a quote and said he would likely beat any local quote as he is looking to build up his business.

He said that he will call in again tomorrow afternoon to drop off some contact details, unless someone wants to contact him a little quicker by calling him tomorrow morning.

**Comment by amcewen** [comment]
**Lots** of scrubbing done today from a load of volunteers (thanks so much everyone!) and we've got over half of the floor cleaned up.  There's a variety of levels of old paint on the floor, so once we've got it all clean we can make a decision on which will look best - varnish or painting it.

We've made sure the strip running alongside where the carpet will be fitted is clean, so we won't be lifting loads of grey gunk right next to some new carpet.  The aim is to get that fitted sometime this week.

**Comment by amcewen** [comment]
We're over 3/4 of the way through the scrubbing (ta @jackie1050 and @paulfurley last night), so starting to reach a point where we can get a feel for what the floor looks like.  The boards have been painted white at some point on the East side, and are bare on the West side, with the occasional new board following a repair, so there's a variety of finishes.

It feels like we've got three options:
  1. Paint all of the floor, as that will obviously make it all a uniform colour/finish
  1. Varnish it as is, which will seal it and generate less dust and make it easier to clean
  1. Sand/scrub the paint off, then varnish.

@jackie1050 did a test of option 2 in a small area last night, which looks like this (the rightmost 6 boards, from the wall to in line with the grey pillar):
![](https://c1.staticflickr.com/1/811/40330453755_7f41176d41_b.jpg)

And option 3, which would be the most work, should get us nearer to the finish in the wood workshop, which looks like this:
![](https://c1.staticflickr.com/1/863/40512777804_63539ed6b0_b.jpg)

**Comment by amcewen** [comment]
@zarino, @jackie1050 and I pondered the options for this in the space last night (where we could see the test area, and the state of more of the floor, and decided that we should go for option 3.

This morning, Ste suggested paint stripper, and so is testing that out now.

**Comment by amcewen** [comment]
Paint stripper didn't do much, so we gave up on that fairly quickly.

Over the weekend we've had lots of great help, and all (bar a couple of sq ft under a wood pile by the window) of the floor has been scrubbed.  Most of the floor South of the central pillar has had the white paint scraped off (Zombie Chris in particular has grafted on that today, finding that damping the surface down and then scraping with @magman2112's scraper).

The recess and area next to it over to the pillar have been washed down and then varnished too, and look great.    @jackie1050 also varnished most of the way along the edge that'll abut the carpet too, before that goes down tomorrow.

**Comment by zarino** [comment]
I think, when this ticket talks about the "main room" it means the open workshop space (ie: everything infront of you and on your left as you enter the main door into DoES, excluding anything inside its own room with a door).

In which case, this ticket is complete now, right? As I understand it, the floor in the workshop has been scrubbed and varnished, and the carpet along the central "landing strip" has been laid. Right @jackie1050 @johnmckerrell?

**Comment by johnmckerrell** [comment]
There's some finishing needing by the fire escape which the carpet guy is supposed to be doing so we'll need to keep it open to keep an eye on that.

**Comment by johnmckerrell** [comment]
Called the original fitter today and he's going to come and take a look this week.

**Comment by DoESsean** [comment]
Can we close this yet @johnmckerrell

**Comment by amcewen** [comment]
I've spun the remaining flooring-in-main-room-related issues out as #1056, #1057 and #1058.
