### ISSUE TITLE
Flooring in the metal workshop

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#713]
We need to review the current state of the flooring in the small workshops and make a plan for what we need to do with it and when. There will be small fixes needed but we need to decide if a bigger change is needed and when? Feel free to split this into two if that seems necessary.

**Comment by ajlennon** [comment]
Floors 

- floors need caulking to fill in holes
- "caulk" or whatever filler we use may need staining to fit in with floorboards
- need sealing so water or other things doesn't soak / go through e.g. either with varnish or with floor paint (pale grey?)
- we aren't staining them

Becka's parents have noted a technique to caulk in the referenced issue above #689 

A quick google shows other options 

http://www.diydoctor.org.uk/projects/fillinggapsinfloorboards.htm

Draughtex and Stopgap seem too expensive

Thus the remaining options are "Flooring Filler" or "Decorators Caulk"

There are tubes of "caulk" with different colours here

https://www.sealantsandtoolsdirect.co.uk/product.html/search=caulk/

**Comment by magman2112** [comment]
In the woodwork room, the floor has been cleaned by several people (a lo5 if work) and now appears good enough to possibly varnish to seal it. 

The joints on the loose boards have been caulked with brown silicone. These ideally should be sanded where the caulk has spread outside of the joint.

It could be possible to leave these as bare boards, but the preference now appears to be to varnish these boards with something hard wearing, such as an epoxy varnish or yacht varnish, to both seal them and colour them to a darker colour (similar to when they are wet - when they appear to look their best).

These could possibly be dry enough to varnish on Monday ( a heater was left in the room after the last wash today, to hopefully dry them enough for varnishing).

**Comment by magman2112** [comment]
For the metal workshop, I would suggest plywood on this floor, as metal filings would be hard to clean up from a rougher floor.

**Comment by zarino** [comment]
![img_7197](https://user-images.githubusercontent.com/739624/37878701-f4dac884-3064-11e8-843e-7a76e9662d50.jpg)

**Comment by amcewen** [comment]
I've renamed this issue so it can focus on the metal workshop, and spun the remaining task for the wood workshop out as #732.

So, we need to get enough 12mm ply (any particular type @magman2112?  Just whatever is cheapest, presumably?) for a 320cm by 331cm room.  And some 12mm triangular edging to provide a bit of a ramp up at the entrance to help with accessibility?  (@Robotorium, I'm assuming a tiny tiny ramp will be better than a hard step, or does it not matter?  Thinking about it, that might be more useful for non-wheelchair users... :-)

**Comment by Robotorium** [comment]
12mm is all right for chairs. If there's a colour difference between the
two floors, I think you can minimise tripping by providing a visual guide
for walkers, but maybe a ramp would be better - or an Ackers Bell that
notes whenever someone stumbles on it :)

Op ma 2 apr. 2018 10:17 schreef Adrian McEwen <notifications@github.com>:

**Comment by zarino** [comment]
I assume you'll need to raise the door too, since it opens inwards and will need to clear the floor?

**Comment by zarino** [comment]
Oh, also note my measurements above were wall-to-wall, not skirting-to-skirting, so the actual floor will be slightly smaller.

**Comment by johnmckerrell** [comment]
Any particular reason for 12mm? I thought we were getting 6mm with the carpet. 

--

**Comment by magman2112** [comment]
I suggested 12mm, as the 6mm will have carpet on top of it as the wear surface.

There is an offcut from one of the doors which is actually mahogany. I can re-purpose this as a threshold/ramp.

**Comment by amcewen** [comment]
So by my reckoning we'd need 4 sheets of that (or whatever thickness we got).

@Robotorium thanks for that.  The colour change is a good idea, and @johnmckerrell and I were discussing whether painting it a colour rather than varnishing might look better just earlier on.

**Comment by johnmckerrell** [comment]
FWIW I have no opinion on thickness was just checking given what the carpet guy was doing. 

--

**Comment by magman2112** [comment]
I think it is actually 12mm ply @amcewen, the carpet fitters accidentally loaded 15mm yesterday, then had to unload and reload with 12mm when they found out.

The ply they are using is softwood, so I also agree that painting may be a good idea. Any suggestions on a colour? Red or grey are the easy choices from Screwfix.

https://www.screwfix.com/c/decorating/floor-paints/cat850170

We will need to check, when we get the floor paint, whether the bare boards need to be primed before painting. We already have some grey primer that may be OK for this.

**Comment by zarino** [comment]
> Any suggestions on a colour? Red or grey are the easy choices from Screwfix.

At the risk of sounding like a broken record, I’d probably go with grey.

**Comment by jackie1050** [comment]
We'd better be adding some neon orange later!

On 4 Apr 2018 10:55, Zarino Zappia <notifications@github.com> wrote:

Any suggestions on a colour? Red or grey are the easy choices from Screwfix.

At the risk of sounding like a broken record, I’d probably go with grey.

**Comment by zarino** [comment]
> We'd better be adding some neon orange later!

OMG YES PLEASE.

**Comment by magman2112** [comment]
So who is going to start looking for neon orange safety tape, so we can tape a safe work area around the machines, like they do in factories?

**Comment by amcewen** [comment]
Having measured the boards, I can confirm that @magman2112 is right and they're 12mm.  I'd misunderstood the mix-up yesterday.

@zarino, in general I'd agree with the grey, but I guess it depends if we end up painting the main room grey #712, then as @Robotorium mentioned earlier, a different colour would provide a visual indicator of the change in floor level (or we have an edging strip for that, or maybe paint the ramp @magman2112 is talking about neon orange... ;-)

**Comment by Robotorium** [comment]
Yeah, or just a line at the edge where the height change is could do, just
as a reminder that it's there. If there's orange tape, could just put down
a strip of that right at the edge?

Op wo 4 apr. 2018 11:10 schreef Adrian McEwen <notifications@github.com>:

**Comment by magman2112** [comment]
We are going to need a threshold on entry to the metal workshop, precisely because of the level change and to make wheelchair access easier - though we may need to find an agreeable slope for this threshold whilst not also making a trip hazard. This threshold can also be coloured to signify the change in levels. 

@Robotorium, have you any guidance on what would be an acceptable slope, for example a 1:4 slope will need a 48mm width to go up 12mm? I suspect though, we might need a slope of 1:10 or better.

**Comment by Robotorium** [comment]
The recommendation for ramps is 1:12 (1:10 for assisted use) but 12mm is a
really, really small difference and I'd hesitate to call it a ramp rather
than, say, a threshold. I did some ferreting around and found this
https://www.designingbuildings.co.uk/wiki/Accessible_threshold which
describes an accessible threshold as "A threshold that is level or, if
raised, has a total height of not more than 15mm, a minimum number of
upstands and slopes and with any upstands higher than 5mm chamfered."

That said, it would be more pleasant and probably less of a trip hazard
with some sort of slope (and it's definitely worth keeping in mind that
accessibility isn't just for wheelchair users and some people may be
unsteady on their feet but not use a chair). Seeing as it is a threshold
and a very small height difference, I think 1:4 sounds reasonable, but I
might have to defer to folks who spend more time than I do walking in
unfamiliar environments.

**Comment by johnmckerrell** [comment]
Tony caulked the floor (as the flooring people failed to turn up and feather it) and did a coat of paint. It could probably do with another coat, there's plenty of paint and I thought Tony would be in today to do that but I don't think he turned up.

**Comment by johnmckerrell** [comment]
Unfortunately Tony's off work for a few days so if we do want another coat we'll have to wait (or do it ourselves).

**Comment by johnmckerrell** [comment]
This has now had a second coat and we've started using the room.
