### ISSUE TITLE
Propose a VR room / area at the next DoES community meeting

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#716]
@jackie1050 took along my VR setup to the Liverpool Library last Friday. It seemed to generate a lot of intersest and was well received.

As preparation for that event I had the system set up in Dinky for most of the week and various people had a play with it, and seemed impressed.

The response was more positive than I expected tbh. 

As a result, and because of the general and increasing level of VR activity I see in Liverpool and further afield I propose leaving my system in DoES-Tapestry for an indefinite period.

So I'd like to propose a vote at the next community meeting on whether we want to find space for a semi-permanent installation (i.e. in a room or cordoned off area) for people to use for relaxation and/or development.

@DoESsean can this be added to the agenda please?

**Comment by goatchurchprime** [comment]
Nobrainer. Easy to remove. Hopefully we won't have as much spare space in
the future as we do now, so spread out and take up the room.

**Comment by johnmckerrell** [comment]
It would be nice if our meeting rooms don’t end up as cluttered as the old ones were. 

--

**Comment by ajlennon** [comment]
From my perspective I hope that the new DoES building will contain elements of a professional space which is uncluttered and enjoyable to work in. High on my list of priorities is an ability to bring prospective clients and business partners to DoES for meetings and to feel proud of the space.

I will hold my hand up now and say I am as bad as the next person for mess, but do hope that we can find a way to significantly improve the working environment and not bring bad old practices from the Gostins building.

I don't believe that a suggested VR space would contribute to mess, and if I were to be convinced it would negatively impact the space I would withdraw the suggestion :)

**Comment by DoESsean** [comment]
I think this is a great idea, and will add to the space, although do think
it's worth having a designated area. Also, having that set-up will also
look pretty cool for people coming in. Depending on how much space it takes
up (and also what else is going to go there) could it go in the open area
next to the workshops, where the sink was supposed to go?

**Comment by Pezmc** [comment]
That could be ideal! For VR, you ideally want 'real walls' and a clear boundary so people don't get in the way! If we're doing room scale, you also want some carpet/rug to help provide some tactile feedback that you're in the middle of the space.

**Comment by johnmckerrell** [comment]
Easy to work out how much it'll cost now that we have the £3/cubic foot pricing model too, right? ;-)

**Comment by johnmckerrell** [comment]
This issue refers to proposing, are we any closer to working out what would be needed for this, and/or where would make the most sense now that we're living in the space. The VR kit is fairly inconspicuous where it is now but that's probably not the best place for it really, if we wanted to move it against the wall in one of the meeting rooms that might work better?

**Comment by goatchurchprime** [comment]
Related tech which might ride on this is use of telepresence robot tech (as we have such good bandwidth) 
   https://www.bbc.co.uk/news/business-45332710

This might even be easier to implement than @concreted0g's idea of VR versions of hackspaces that you can check out before visiting -- simply allow people to connect to our telepresence robot and wander around the space with it from a distance, before they commit to travel 100s of miles to come all the way over here.

**Comment by ajlennon** [comment]
Haven't we got a load of motor controller boards and suchlike in that Arduino drawer?

**Comment by DoESsean** [comment]
Are we happy with the VR set up as it is now? It seems to have found a permanent home, is used as a display when we want it to be, and keeps Anthony happy when he's in :)

@ajlennon is it good for you? Also, is it on permanently, or is it switched on as and when? If the former, it might be a cool thing to just have on the tv all day, as it wouldn't be drawing much more power and would be something interesting for people to see when they come in the space.

**Comment by ajlennon** [comment]
I am very happy with the situation and very grateful the community allows my boy to play with it.

I am cognisant this that may be inappropriate for the space and I hope if there is any concern that somebody will have a quiet word with me.

It was and is my hope that this will be a resource for everybody to use and I have been pleased that a couple of younger visitors have taken advantage of the resource. 

So in brief I’m happy. I’ll also be happy to move or remove it if it’s not a net benefit to the space

**Comment by ajlennon** [comment]
Oh and on the power. A couple of things.

- Matt has been using the machine as a processing resource for routing CNC stuff. I don’t pretend to understand what’s going on but it seems to be useful and is sitting there for that purpose when not being a VR PC

- John (?) had some really neat space videos going on and I was thinking it would be great to have more of that kind of thing if it wasn’t a distraction 

- Julian and I have been beavering away instrumenting devices for power consumption. We have the data being published on the internal network now so when Julian has time to work his magic we’ll have a better understanding of what’s contributing to power costs

**Comment by DoESsean** [comment]
Since @ajlennon is happy, and no-one else expressed unhappiness, I think we can say that this can be closed.
