### ISSUE TITLE
Do something about smoothing OSB before painting

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#717]
There are a couple of areas of exposed OSB. These have a rough texture. We need to look into how they can be made smoother before painting. One suggestion is to use lining paper.

### Above the “hatch” in the kitchen

![img_7246](https://user-images.githubusercontent.com/739624/38353236-c8c1a9a6-38ad-11e8-8678-70e01de9a7c6.jpg)

### Opposite the toilet

![img_7240](https://user-images.githubusercontent.com/739624/38353247-cd3866c8-38ad-11e8-88bd-3f0a89968b0a.jpg)

### Behind the toilet, in Room 29

![img_7242](https://user-images.githubusercontent.com/739624/38353249-d098f206-38ad-11e8-981a-90976bb3de8c.jpg)

**Comment by ajlennon** [comment]
@zarino talking with @jackie1050 here: Shall we just paint these as is. Or what shall we do?

**Comment by DefProc** [comment]
It's unusual to paint exposed OSB. 

The surface texture is difficult to remove (as in "use another board instead"!), and when exposed, the surface pattern and being already pre-sealed are considered benefits, along with the low cost per sheet. 

See also: the single storey bit of The Tapestry.

**Comment by zarino** [comment]
@DefProc – OSB looks ok when used _for everything_ (see, as you say, the ground floor of the Tapestry, or pretty much any Baltic Creative building) but it looks super sketchy when there’s just one or two patches of it, which is the situation we’re in. We currently have a pathetic three panels of OSB:

* Inside the kitchen, above the "hatch" through to the events space
* Inside the new Room 29, to your immediate left as you enter, forming the back wall of the regular toilet
* The bannister / half-height wall beside the fire exit, opposite the door to the regular toilet.

There are others here who dislike OSB more than I do, but I think we probably all agree that having OSB visible for a few weeks after we move isn’t a deal-breaker. Maybe we keep this one low on the list of priorities and revisit once the moving madness has died down a little?

**Comment by johnmckerrell** [comment]
I’d be interested in picking one and painting white to see how it looks. Quiet coworking room probably?

--

**Comment by amcewen** [comment]
If you want to see what white painted OSB looks like we've already got some - in the toilet near the fire escape. presumably the other side of the panel in Room 29.

It's not *terrible* but I think the unpainted OSB looks better.  I agree that it doesn't seem super high priority before the move.

**Comment by DoESsean** [comment]
Stick some push pins in it and use it as notice boards/poster boards.

I'm not even kidding, it doesn't look that dissimilar to cork, would remove
the need to paint it, and could create something interesting to look at.

(I appreciate that, for example, the half height wall isn't in prime
reading territory, but a load of posters for past events or whatever would
look pretty cool).

**Comment by johnmckerrell** [comment]
I can confirm the painted OSB looks awful.

**Comment by Robotorium** [comment]
If there are posters for past events, can they not be stuck on with
wallpaper paste or something? Turn it into a sort of découpage feature?

(Disclaimer: I haven't been to the space yet so this could be a useless
suggestion)

Op di 27 mrt. 2018 11:17 schreef John McKerrell <notifications@github.com>:

**Comment by zarino** [comment]
@Robotorium – @DoESsean’s suggestion of pinning stuff up immediately made me think "Yeah, go all-out, cover the whole thing" – sort of like those walls you get with layer upon layer of gig posters, or stickers on the back of a laptop 😉

**Comment by Robotorium** [comment]
Yes, exactly! Down to thinking about gig posters and laptops!

Op di 27 mrt. 2018 11:47 schreef Zarino Zappia <notifications@github.com>:

**Comment by johnmckerrell** [comment]
+1 sounds awesome, just a shame that most of the OSB is out of the way, although.. there’s the big panel in the events room if we think we can do a good job of this

**Comment by Pezmc** [comment]
It would be nice to invite visitors to stick stickers/business cards on the wall, could cover up the OSB and make some 'art' at the same time!

**Comment by DoESsean** [comment]
Gig posters was exactly my thinking, but we don't really have gigs here!

I love the effect in places like Bar Cava with all the film posters, so
that image is what I had in mind. If anyone wants to take a field trip
there to check it out, I'd happily tag along :D

**Comment by Robotorium** [comment]
I was thinking, how much of a gap/wobble is there between the OSB and the
surrounding wall? Because where if it isn't too much, then maybe there
could be a designated area of the wall, so it isn't just the OSB being
covered, to make the entire thing a more suitable shape/area? If it's low
down, just expand the poster/sticker space up until you get a more pleasing
area?

Op di 27 mrt. 2018 12:06 schreef Seán Gleeson <notifications@github.com>:

**Comment by amcewen** [comment]
We don't have gigs, but we do accumulate posters.  We already have a bunch...

![](https://c1.staticflickr.com/1/873/27176787518_0c7962a0e1_b.jpg)

And we can print out the latest update to the [Maker's Bill of Rights](http://makermanifesto.com/) too.  Plus we *do* have a load of business cards with pictures on to use up... #721 (if we want a quick base layer to cover with more posters in future...)

In the past I've suggested slowly filling an area of wall with [Girih tiles](https://en.wikipedia.org/wiki/Girih_tiles) (or something that similarly tessellates) cut from random offcuts from the lasers - I think that could look good on the OSB on the half-height wall by the toilets.

**Comment by zarino** [comment]
For those following along at home, I’ve updated @jackie1050’s post, above, with photos, so you can see the three areas we’re talking about.
