### ISSUE TITLE
Stencil the DoES Logo on the front door

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#719]
Does the front door need repainting as the first point of contact visitors have with the new space?

Should we stencil the DoES logo in white on a black door?

**Comment by zarino** [comment]
> Does the front door need repainting as the first point of contact visitors have with the new space?

I doubt it needs painting. Could do with a good clean though, once all the messy painting/sanding/moving has been completed.

> Should we stencil the DoES logo in white on a black door?

Could we cut the logo out of white vinyl, instead, using the DoES vinyl cutter?

(Vinyl will be easier to peel off, if we ever change the logo 😉 )

And if so, could we also do the same with signs for the toilets? Something [gender-neutral](http://itspronouncedmetrosexual.com/2014/04/gender-neutral-bathroom-sign/) on the standard loo, and a [wheelchair icon](http://accessibleicon.org/) for the accessible loo.

**Comment by drfraz** [comment]
We could etch the DoES logo onto the internal kitchen window with the Laser cutter when we replace the grout/ broken panes see #714
or even the directors portraits?

**Comment by ajlennon** [comment]
>Could we cut the logo out of white vinyl, instead, using the DoES vinyl cutter?

Yay!

**Comment by ajlennon** [comment]
>We could etch the DoES logo onto the internal kitchen window with the Laser cutter when we replace 

@jackie1050 was suggesting very much the same thing I believe? Sounds an awesome idea. Could we do that as a stretch goal ?

**Comment by amcewen** [comment]
@zarino lots of vinyl-cut signage for all round the space sounds good.  I have been hoping to get you (with some vinyl-cutter driving/applying assistants) to churn through a load of signage (see #20 for a bigger starting point on what we'd need)

**Comment by DoESsean** [comment]
Toilet vinyl got done, does anyone know when they'll be able to sort the door vinyl? It would look good, particularly as we just have a paper sign up there which seems to be doing a good job.

**Comment by amcewen** [comment]
We've now got a 610mm wide roll of matt white vinyl (thanks @DoESsean!).

I'm thinking we should cut this for the main door.  I think 50cm wide and 107cm high, so it takes up most of the door - going to mark up the door with some masking tape to see roughly how big that would make it...

![main-door-sign](https://user-images.githubusercontent.com/108468/61994112-4a3e5180-b06e-11e9-923a-857f94d0c712.png)

**Comment by amcewen** [comment]
Door now marked up, does that seem the right size?  Should it be a bit bigger?

![DSC_0012](https://user-images.githubusercontent.com/108468/61994481-aa36f700-b072-11e9-90c9-6827f6b872e2.JPG)

**Comment by johnmckerrell** [comment]
Yeah. I think bigger. Same margin as it currently has on the right should be in the left too. Not entirely sure but I think the margin would be to the door handle not the edge of the door (on the right)

--

**Comment by zarino** [comment]
How about reversing the logo rather than putting it in a white rectangle? So, when it’s cut out of white vinyl, the logo would be a big white square, with the letters "DoES" cut out of it, and then the letters "Liverpool" below in white just like all the rest of the text.

Obviously, then, you’ll want to increase the overall size of the logo, so it still lines up with edges of the text above and below it.

You might also need to increase the vertical space between the logo and the top of the "Co-working…" section below it, just so it’s clear where the logo ends and the text starts.

I also wonder about putting "Welcome to" on a single line? The "to" looks awkward on a line of its own.

**Comment by johnmckerrell** [comment]
I agree about "Welcome to" but not about switching the logo around, although would be good to see it. @amcewen that picture you did was that supposed to be actually proportions? If not, why not? :-)

**Comment by amcewen** [comment]
What about this for the "extra" door on the events room?

![events-door-sign](https://user-images.githubusercontent.com/108468/61994584-38f84380-b074-11e9-80c2-5c8c2497886b.png)

Taking up this sort of room when installed...

![DSC_0013](https://user-images.githubusercontent.com/108468/61995137-fb97b400-b07b-11e9-9877-0c490eb77099.JPG)

**Comment by amcewen** [comment]
@johnmckerrell The picture isn't "supposed to" be the actual proportions, it *is* the actual proportions :-p (modulo minor variations in me measuring out masking tape).

I'd initially thought having the "Welcome to" all on one line would make it too wide, but it does look better.  Also pondered the logo colour inversal, @zarino, but I prefer the current option myself.

How's this?

![main-door-sign](https://user-images.githubusercontent.com/108468/61995222-4ebe3680-b07d-11e9-964e-6482f217c995.png)

**Comment by johnmckerrell** [comment]
@amcewen but the photo of masking tape looks a lot smaller than the picture does, that's why I asked about proportions, "Welcome to" looks great.

**Comment by amcewen** [comment]
The background of the picture *isn't* the size of the door (IIRC it's width is the size of the roll of vinyl and its height is arbitrary)

**Comment by johnmckerrell** [comment]
Right, yeah, that's what I meant, without wanting to tell you what to do, could you knock that up please? ;-)

**Comment by amcewen** [comment]
Okay, how about that?  (text, etc. also resized to be bigger - I'm assuming you mostly meant leave the right edge where it is and make it bigger into the left-hand space @johnmckerrell?)

![main-door-sign](https://user-images.githubusercontent.com/108468/61995445-a6aa6c80-b080-11e9-8b13-8f9e77903ce5.png)

**Comment by zarino** [comment]
@amcewen Still think the logo inside the box thing looks wrong, but happy to be out-voted on that. Otherwise, this looks good to me :+1: Make it so!

**Comment by ajlennon** [comment]
Dunno but the Co-working line seems to start too low to me?

**Comment by johnmckerrell** [comment]
Think I'm happy with the latest mock up. 👍  Also the events room looks good.

**Comment by amcewen** [comment]
These have been cut, but it seems that whoever used the last of the clear transfer tape didn't inform anyone or replace it, so this is blocked until #1195 is resolved :-(

**Comment by amcewen** [comment]
Vinyls applied!  Many thanks to @Helen-8, @zarino and Liam for their assistance in the application.

The view from the top of the stairs...

![DSC_0059](https://user-images.githubusercontent.com/108468/62413162-86405c00-b604-11e9-8e38-b10de7b0f875.JPG)

**Comment by chris-does** [comment]
>Vinyls applied!  Many thanks to @Helen-8, @zarino and Liam for their assistance in the application. ...

@amcewen @Helen-8 @zarino : Both of these doors look great, and collectively create a fantastic impression on arrival.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
