### ISSUE TITLE
Google map search to The Tapestry puts pin at wrong location

### ISSUE THREAD

**Issue by mdunschen** [DoESLiverpool/somebody-should#720]
Searching the location of "The Tapestry" on google comes up with this link:

https://www.google.ch/maps/place/The+Tapestry/@53.4106945,-2.9722571,17.6z/data=!4m5!3m4!1s0x0:0x8519ca499a04acfe!8m2!3d53.4105271!4d-2.9715126

It shows the pin in the wrong location, wrong side of Gildart Street.

**Comment by Pezmc** [comment]
I moved it further up Kempston Street, will take ~24 hours to confirm!

**Comment by zarino** [comment]
Can confirm a google.co.uk search for "The Tapestry, Liverpool" now shows the pin at the correct location:

<img width="1187" alt="screen shot 2018-03-29 at 09 29 11" src="https://user-images.githubusercontent.com/739624/38078294-b44a4642-3333-11e8-95cb-42e27fed42f9.png">

**Comment by amcewen** [comment]
You are allowed to close issues @zarino :-)
