### ISSUE TITLE
Get business cards with the new address and prices

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#721]
We need to get updated business cards.

We've already *almost* done that, as we got a load of Moo cards printed with the new address on.  Sadly, as I noticed when opening them up when they arrived, they've got the **old prices** on.

/me considers opening a "what can we do with a couple of hundred business-card-sized pictures of DoES" issue...

**Comment by DoESsean** [comment]
Oh my.

Mea culpa on this one. I've done the job I was asked to rather than making
sure I was doing the job that needed doing.

**Comment by amcewen** [comment]
There are some now stored in the leftmost drawer of the black desks between the kitchen and meeting nook.
