### ISSUE TITLE
Prepare toilets

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#726]
We need: 

- [x] toilet roll
- [x] toiler roll holder
- [x] soap
- [x] bin
- [x] mirror
- [x] fold up chair x 1
- [ ] hooks
- [x] spray air freshener
- [x] sanitary bin (see #782)
- [x] to clean the toilets
- [x] to hang the door on the accessible toilet
- [x] signs for the doors

**Comment by Pezmc** [comment]
I'd tidy, but I don't have the required permissions!

**Comment by zarino** [comment]
Is there space above the sinks to have a mirror? If so, we should have mirrors :+1:

**Comment by johnmckerrell** [comment]
I'm not going to prioritise mirrors for Tuesday but I'll keep it in mind (i.e. if they have them in the shops I go to then I'll pick up, if there's room).

**Comment by magman2112** [comment]
There is room above both sinks for a mirror, or even a bathroom cabinet.

**Comment by zarino** [comment]
The toilets will need a **serious clean** too.

**Comment by ajlennon** [comment]
Could we not do it in a light hearted manner?

**Comment by zarino** [comment]
I just visited a loo that reminded me of this ticket. It had no mirror (super weird!) and no hook to hang my bag and coat on (super annoying!)

I can't remember whether the toilet doors already have hooks on, but if not, that's something else to add to the list.

**Comment by johnmckerrell** [comment]
Definitely need hooks, possibly even a lot of hooks, I'm thinking a chair too to facilitate getting changed in here.

(I did start wondering about getting a washing machine in the small toilet but think it would be a squeeze)

**Comment by zarino** [comment]
A folding chair could hang on hooks when not in use. Saves floor space. (Maybe that's what you were already suggesting!)

**Comment by johnmckerrell** [comment]
Apparently I can get none of this from Costco

**Comment by johnmckerrell** [comment]
Tweaked the original description

**Comment by johnmckerrell** [comment]
If anyone is doing the signs for the toilets, Gary Millar is interested in some too. Fashion hub has 4 toilets of which 2 are accessible. He has said he would pay for them too. Perhaps we do ours first and then send him a photo with a quote. I think he'd like them sooner than later FWIW (I might actually be able to do myself on Saturday morning).

**Comment by cheapjack** [comment]
Just about managed to cut and hang signs for our toilets using annoying work around of a version of corel draw (4). It's a trial that runs out in 14 days so far from ideal. Not had time to do Gary's or take a picture unfortunately :(

**Comment by ajlennon** [comment]
Something up with the PC installs @cheapjack?

**Comment by zarino** [comment]
> Something up with the PC installs @cheapjack?

@ajlennon – yes, possibly some weirdness to do with the SVG we were trying to cut. See #788.

**Comment by johnmckerrell** [comment]
Mirrors in the Tapestry toilets are: https://www.ikea.com/gb/en/products/decoration/mirrors/nissedal-mirror-white-art-30320316/ (but black). Argos have this: http://www.argos.co.uk/product/6249353 which is a little narrower and shorter but I think the frameless perhaps on the back of the door could look better (actually the fixings on the Argos one look awful now I look closer). Probably worth checking the nearby shops too for decent options although the above sets a budget of just a few tens of pounds per mirror.

**Comment by johnmckerrell** [comment]
Also Home Bargains have something like this but in pine which would be a reasonable option for the hooks, unless we want something more modern.

https://www.homebargains.co.uk/products/2994-diy-5-hook-coat-rack-mahogany.aspx

**Comment by amcewen** [comment]
Ben from Find Out has two mirrors that they're happy to donate to us (and happy not to, if we don't want them) for the bathrooms.  One of them is in the less-accessible toilet, so we can see if we like it.  The other is a more modern one with a silver frame AIUI.

This one is pretty big, so wouldn't fit above the sinks in either toilet.

![](https://c1.staticflickr.com/5/4841/32144856148_b6ffa7d1d5_b.jpg)

Do we want it?  Where should we put it?

**Comment by zarino** [comment]
@amcewen It feels like we should go for matching mirrors in the two bathrooms. Looks like  @johnmckerrell has just donated a £7 IKEA "FULLEN" mirror, which fits nicely above the sink in the small toilet. Perhaps we couod buy a second one of them, and then the two bathrooms would match?

![fullen-mirror-with-shelf__0380542_pe555441_s5](https://user-images.githubusercontent.com/739624/49328102-93331a00-f562-11e8-91a9-24759d7fb779.jpg)

**Comment by johnmckerrell** [comment]
This was interesting, suggests multiple ways in which our accessible toilet is not so accessible unfortunately.

http://www.topbc.co.uk/uploads/pdfs/Accessible%20Toilet%20Diagram%20and%20Advice%20Article.pdf

**Comment by johnmckerrell** [comment]
FYI we got two large sheets of 4mm ply that were left over from getting the carpet fitted in Dinky. These could be used to go on the walls behind the mirrors (and probably for other tasks).

**Comment by johnmckerrell** [comment]
I've fitted the mirror in the accessible toilet. Had to do it twice as I got the hole in slightly the wrong place first time and when drilling a second hole ended up with a big hole in the mortar. The bumpy brick wall does make it tricky to get the shelf flat so it probably would be better to put plywood behind. I'd actually be tempted to use the laser to etch a guide to make sure the holes go in the right places but not sure the plywood we have is flat enough.

**Comment by johnmckerrell** [comment]
In case it's useful.

[mirror-template.svg.zip](https://github.com/DoESLiverpool/somebody-should/files/3183231/mirror-template.svg.zip)

**Comment by johnmckerrell** [comment]
Mirror is up! Still needs a shelf really. Can probably do something with acrylic if we can find a big enough piece.

**Comment by DoESsean** [comment]
WRT hooks, will [these do?](https://www.amazon.co.uk/Adhesive-Beeway%C2%AE-Stainless-Kitchen-Bathroom/dp/B077TSCTWY/ref=sr_1_8?keywords=bathroom+hooks&qid=1563464302&s=gateway&sr=8-8)

I can look for a couple of folding chairs afterwards.

**Comment by johnmckerrell** [comment]
I wouldn’t think they’d be strong enough. The ones @magman2112 got for the accessible loo would do the trick

**Comment by johnmckerrell** [comment]
https://www.ikea.com/gb/en/p/gunde-folding-chair-black-00217797/

**Comment by DoESsean** [comment]
How on earth have I never noticed that we have hooks on the back of the door?

@magman2112 Do you know where you got those? I can order a couple more and we can get them on the back of the other toilet door.

**Comment by magman2112** [comment]
I seem to recall actually buying some, but forgot to fit them. I’m not 100% sure where I put them though, I seem to recall that they are in my Maker box, you can have a look if you are in next before me, otherwise I will check some other possible storage (hiding) places.

**Comment by johnmckerrell** [comment]
I'm just closing this, the toilets work well enough.
