### ISSUE TITLE
Determine maximum occupancy figures for areas within the new space

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#729]
@johnmckerrell was mentioning a chat to me about us needing to get certain things signed off with the council with regard to the new space.

I was speaking with a friend who is an events coordinator. She mentioned a couple of things to me, one of which is having an official occupancy number for our spaces from a local safety officer.

You are no doubt all far ahead of me on this but I thought I'd put a placeholder issue here to capture

**Comment by MatthewCroughan** [comment]
@ajlennon This issue seems to have been left open, do we know the answer to this yet?

**Comment by ajlennon** [comment]
I'm working with a figure of 60 but I'm not sure I'm right

**Comment by DoESsean** [comment]
As the floor space of the Events Space is approximately 65 square metres, then for standing and milling around, the maximum occupancy would be 130 (using the 0.5 divisor listed in [this document](https://www.merseyfire.gov.uk/aspx/pages/protection/pdf/Calculating_Occupancy_assembly_buildings_GT.pdf) as it seems most accurate for the given use). I don't think that will ever be an issue.

For seated events, it would basically be however many seats we can safely fit in. Essentially, the doors are wide enough to comfortably be safe for egress of 200 people within a safe timeframe, and so we can work from there.

For Room 29, maximum occupancy should be 13 (using the 6.0 divisor) and for the main room, 20 (again using the 6.0 divisor).

We actually have more desks than that comfortably fitting in 29, and almost that many with loads of space in the main room (and, to be fair, I haven't taken into account the alcove or nook in the main room floor space) so I'm not sure we should get too hung up on it. It's a good thing to have worked out for the event space though.

**Comment by ajlennon** [comment]
Wow that’s useful. Much better than the 50-60 I’ve been working off for the events space

**Comment by amcewen** [comment]
Seated we can fit 50 chairs into the events room, theatre-style.
