### ISSUE TITLE
One of Sophia's fans isn't functioning

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#73]
Sophia has two fans to ventilate the control-board side of the case (the ones to the right-hand-side of the main area.

The one which is missing a number of blades isn't actually functioning now.  We should replace it.  IIRC @DefProc tried getting a replacement a while back, but got a 12V one rather than the mains voltage one it needs (IIRC, I'd check but it's busy cutting at the moment)

**Comment by DefProc** [comment]
I have a fan. Maintenence is scheduled for the 4th March.

**Comment by DefProc** [comment]
Fitted and fixed
