### ISSUE TITLE
Issues with the availability of alcohol on-premises during events

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#730]
In many ways I wish I didn't feel I had to raise this issue. But I was asking my events organiser pal for advice and she raised this as a potential problem.

Again, I'm sure much thought has gone into the availability of beer and pizza at events but am hoping to capture the discussion as a prelude to policy (which may already exist and I've just missed?)

I would hope that we have children and under-18's attending events at DoES. I like the laissez-faire attitude we adopt to enforcing behaviours on each other but I imagine we have a duty of care to ensure there is a policy that minors should not have access to alcohol without appropriate parental supervision.

I'm not clear on the law, or what DoES wants. Thoughts?

**Comment by paulfurley** [comment]
I spent a lot of time trying to think of a reply to this, but kept coming back to "if it ain't broke, don't fix it"... 

> But I was asking my events organiser pal for advice and she raised this as a potential problem.

Perhaps I'm being irresponsible, but I suspect we could make a long, long list of potential problems to worry about. This particular thing doesn't seem to have caused any problems in the last 6 years, as far as I know.
