### ISSUE TITLE
Buy new expanding wall bolts for the "bike securing smiley faces"

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#731]
M8 size - parts of one are taped to the smiley faces.
![img_20180401_113155](https://user-images.githubusercontent.com/12802256/38172290-af854538-35a1-11e8-94cf-c989d7bf09ee.jpg)

**Comment by ajlennon** [comment]
Where will bikes be stored? Will these be seen by visitors or affect #727 ?

**Comment by johnmckerrell** [comment]
I was going to suggest we wait before buying these as bike parking provision should be outside when the landlord gets that sorted. 

--

**Comment by amcewen** [comment]
Aye, @jackie1050 and I were just noting down what we'd left behind in the wall at Gostins so we'd know what to get to replace it :-)

**Comment by jackie1050** [comment]
I've put the smiley faces in the bottom of the solvents cupboard for the time being (they dissolve anything ...)

**Comment by DoESsean** [comment]
Are these going to be used again? Given that no-one is leaving bikes outside the office space, and we're about to get shiny, exciting new on street bike parking, is there any need for this issue anymore?
