### ISSUE TITLE
Prepare and provide carpet emergency boxes

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#733]
Wherever we have carpet we should have handy boxes with emergency supplies of Vanish carpet cleaner, dustpan & brush and additional accessories.

**Comment by amcewen** [comment]
In the  short-term (and also when things are dirtiest) @ajlennon suggested that the big roll of corrugated cardboard would work well to let us cover the carpet with, to provide some protection.
