### ISSUE TITLE
Have a dustpan and brush for every workshop area

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#734]
The required provision may change but we should aim to make it as easy as possible for people to access what they need to clean up the area they've been working in, whether that's a dustpan and brush hanging from every workshop desk or a full broom on the end of each aisle will be more clear once we've got the furniture laid out.

**Comment by drfraz** [comment]
How about designing a cleaning station that can be used in each area?
It could be a simple rack holding a broom, dustpan & brush, cloths/dusters, Blue roll & a box with specific things for that area e.g. Vanish carpet cleaner #733 
It would keep all the stuff together, people would know where to find it & when to restock.
Siting them next to the fire extinguishers would also mean people learn where they are kept.
