### ISSUE TITLE
Ensure there is adequate lighting at ground level and particularly the landing 

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#735]
It’s very dark entering DoES and particularly on the landing at the top of the stairs

My understanding is there is some temporary lighting on the landing which can be turned on at the top of the building.

I believe we should have something like PIR activated lights here as it’s pretty dark and horrible otherwise

**Comment by johnmckerrell** [comment]
The landlord is aware of this. He's had problems with his contractor but is intending to have it fixed.

**Comment by amcewen** [comment]
I moved (temporarily, I think @johnmckerrell took it back before they were in this morning) one of the floodlights from the top floor to use as a stair light yesterday.  Will likely do something similar this evening, and for LivLUG tomorrow evening.  If anyone comes across any of our workshop loupes or other plug-in lights in a box somewhere, please leave them somewhere obvious :-)

**Comment by johnmckerrell** [comment]
It looks like the proper lighting is now active, it's been turned on this afternoon at least. Maybe leave this ticket active overnight to see if it's still usable when the contractors have gone home.

**Comment by ajlennon** [comment]
Is it motion activated @johnmckerrell ?

**Comment by johnmckerrell** [comment]
There is a combination of lights that when finished will be on switches and some on PIR. For now he has set them up on a PIR so they should go off on their own

--

**Comment by amcewen** [comment]
The lighting on our floor is great now, but I'm not sure how we turn the lights on for the ground floor.  I'll try to remember to ask Jason when he calls in tomorrow.

**Comment by amcewen** [comment]
I mentioned the lights on the ground floor to Jason yesterday, and they got sorted out then.  The switch at the bottom of the stairs now works and turns the lights on the ground floor on and off.
