### ISSUE TITLE
Get door hardware for the internal doors

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#736]
As well as painting the doors to our new rooms (#697) we need to get door handles, etc. for them.  Dave, the builder, will pop back and fit them sometime, but we need to choose and buy them first.

**Comment by johnmckerrell** [comment]
I believe the door handles are from Beesley and Fildes
https://www.beesleyandfildes.co.uk/paa-19mm-lever-on-rose-ref-874-/

Satin or polished (tbc)

We need 4 of these and then perhaps we could use a big static handle for room29, if it's got a mag lock or other lock then it might not need a door handle with a latch. To match the others we have it would be this one:

https://www.beesleyandfildes.co.uk/loose-saa-concealed-fix-pull-handle-300mm/

(Our others are the 225mm version but this door already has holes for a 300mm so might as well go with that)

We'll also need loose mortice hatches similar to these, but not sure what length we need: https://www.beesleyandfildes.co.uk/-prepack-mortice-latch-2-5-bzp-economy-/

**Comment by johnmckerrell** [comment]
The door knob downstairs looks satin but then the other static handles are polished on our floor so maybe we should just go with that.

**Comment by johnmckerrell** [comment]
Meeting room: 125mm
Soundproof room: 45mm
Metal workshop: 105mm
Wood workshop: 55mm (actually has a suitable handle already)

**Comment by magman2112** [comment]
Closing this issue as all door hardware obtained and now installed.
