### ISSUE TITLE
Reassemble Gerald in the wood workshop

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#738]
Now we've got the floor sorted in the wood workshop, we can start moving things in.

We (@dazz-ling and @amcewen) are aiming to do this (as well as fit the belt for #288) ~~Wednesday~~ Thursday after work.

Opening this issue as much to advertise that to anyone else (@johncain39, @Dowz77...) who might want to gegg in.

**Comment by johncain39** [comment]
Hi Guys, can’t make Wed but can make Thursday if that’s any goood??! Can I also ask if the belt change on Sophia worked??

**Comment by amcewen** [comment]
Update, looks like we'll be attaching this on Thursday from 5pm.

**Comment by huffeec** [comment]
Gerald has been reassembled in the woodworking room. It is not functional, see #743 and #742
When these new parts are replaced the mirrors will need realigning so I'll leave this issue open.

**Comment by amcewen** [comment]
Gerald is now installed and working reasonably well (see #749) in the new wood workshop!
