### ISSUE TITLE
Update rooms page on wiki

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#739]
https://github.com/DoESLiverpool/wiki/wiki/Rooms

**Comment by amcewen** [comment]
Ditto in our labels here.

**Comment by Pezmc** [comment]
I started work on the wiki, though it's a little sparse and I'm not sure I have the latest information, but it certainly lays some groundwork!

**Comment by johnmckerrell** [comment]
Looks like a decent start, for the record it's actually Dinky 3.0 (or perhaps "new new Dinky" ;-) ) I doubt will make a point of that though!

**Comment by N-Sinnott** [comment]
Added some more info, doesn't seem complete, though. Needs a new room plan as well.

**Comment by magman2112** [comment]
I have updated the drawing with a few room name changes and saved a new .svg format file in somewhere safe. I have also updated the text for the wiki entry after the recent equipment moves. 

I think this is OK to close for now.

**Comment by johnmckerrell** [comment]
Fixed a typo, it’s “sewing" unless we’re planning on planting crops!
