### ISSUE TITLE
Gerald needs a new bracket inside the lid to hold the cut off switch

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#742]
The cut off switch under the lid is not working because the existing cardboard bracket is broken.
This needs replacing, ideally with a more durable laser cut bracket

**Comment by amcewen** [comment]
I'm not sure it *has* to be laser-cut :-)  Given its shape, I wonder if a 3D printed one would work better?

**Comment by huffeec** [comment]
Meh, I suppose there are other tools in the workshop..

**Comment by cheapjack** [comment]
I've re glued the sensor and repaired the cardboard bracket until we get a nice 3d printed one. Will leave this open for time being

**Comment by magman2112** [comment]
I mentioned to @amcewen yesterday that I should be able to bend one from aluminium sheet then fix this to the channel for the lid with countersunk screws. I suspect I may already have a bent piece that could be fitted quite easily. I will put it in my bag to bring it in when I’m next in.

**Comment by amcewen** [comment]
As we've got a temporary (like we've had for X years now...) solution in place, I'm dropping the `Broken` label.

**Comment by johnmckerrell** [comment]
FWIW it fell off again the other day and we taped it on, if that hasn't fallen off again.

**Comment by magman2112** [comment]
I made up an aluminium bracket yesterday and fitted it, so this sensor is now securely fixed and should hopefully not be an issue in the future. I also built in a degree of adjustment should this be needed in the future.

One of the other members, I think it was cheapjack, tested Gerald and things looked OK, so I will close this issue now.
