### ISSUE TITLE
Replace the flow switch on Gerald

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#743]
The flow switch on Gerald is not functioning and needs replacing.
The part is '[HT-30 pressure switch](https://www.ebay.co.uk/itm/Pump-Water-Flow-Sensor-Pressure-Switch-HT-30-Laser-Machine-G1-2-Thread-hh-/382295763827)'

**Comment by huffeec** [comment]
I asked smoke and mirrors if they had this part, Dominic's reply.

First thing to double check, you're not putting the water through the wrong way? Flows in through the anode (red wire) and out through the cathode (shooty laser end). I've been out to "mend" a lot of cutters where that's the problem. Nope I don't stock that. I should. You can probably bypass it in the meantime!

**Comment by cheapjack** [comment]
I've temporarily bypassed the flow sensor for now until we can with work that out. I've used some insulated bell wire across the connector strip and insulate taped the flow sensor abode and cathode in a way that we can remove easily.

**Comment by cheapjack** [comment]
@amcewen and I swapped the chiller water flow so:

 * Water inlet on Gerald to water outlet on chiller
 * Water outlet on Gerald to water inlet on chiller

So now the flow sensor is happy and must be working as tube fires successfully yay!

I've left some insulation and bell wire in the panel just in case we need to bypass in the future
