### ISSUE TITLE
Replace the water input connector on Sophia

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#744]
When we reassembled Gerald we noticed the water input connector was broken. #738 
In order to get one machine working we used the connector from Sophia. This will need replacing before Sophia is working again.

**Comment by Dowz77** [comment]
Can you post an image of what's required and I'll see if i've got anything suitable to bring with me tomorrow.

**Comment by amcewen** [comment]
A bit late @Dowz77, not long back at a computer after a day of getting the wood workshop into shape!

![](https://c1.staticflickr.com/1/878/39509749360_83fd07646b_b.jpg)

It's basically double-ended to allow two hoses to join.  Annoyingly the calipers aren't in their drawer at the moment, so I couldn't get a size for them.

**Comment by Dowz77** [comment]
I've got a hose connector that will work then

**Comment by amcewen** [comment]
Ta @Dowz77, I've [ordered one](https://www.ebay.co.uk/itm/8mm-5-16-Hose-Tail-Bulkhead-Connector-in-Brass-for-Fuel-Air-Water-Etc/222927938589?hash=item33e78a641d:g:s~YAAOSwB1Jap6Ho) for delivery to DoES, should be here at the end of the week or start of next.

**Comment by johnmckerrell** [comment]
I suspect this turned up today, @goatchurchprime probably opened the package.

**Comment by johnmckerrell** [comment]
Think Andy fitted this and Mike & I confirmed it worked today.
