### ISSUE TITLE
Work out what we're doing for the Fabric District festival in May

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#746]
I just met up with John Hyatt, who is organising the Fabric District festival in May.  More details on that at http://timetunnel.johnhyatt.co.uk/

We need to work out what events we want to do as part of it (it seems a good target for an official launch of us at the Tapestry), and let him know (not least so they can update the website - he'd just put something in more as a placeholder than anything else).

I also see that Saturday 12th May is [Arduino day](https://blog.arduino.cc/2018/03/23/save-the-date-arduino-day-2018-is-saturday-may-12th/) so we could tie into that too...

**Comment by johnmckerrell** [comment]
The placeholder is in as Maker Day 3-5pm so I've sent over the following:

Jelly Liverpool Free Coworking Thursday 10th 9:30-17:30
https://jellyliverpool.com

Maker Night Thursday 10th 18:30-21:00
https://github.com/DoESLiverpool/wiki/wiki/Maker-night

Maker Day Saturday 12th 10:00-18:00
https://github.com/DoESLiverpool/wiki/wiki/Maker-night

**Comment by jackie1050** [comment]
I have registered us for Arduino day, and will need to update with more details before 6 May at the latest. @amcewen I going to get more details of live streaming times. We will need to talk to MD too, to avoid noise issues.

**Comment by amcewen** [comment]
We had an Arduino day, and a makerday and it was Jelly on the Thursday and we showed people around during the opening of the building on the Thursday evening.
