### ISSUE TITLE
Check top double socket on the West side of the pillar in the middle of the main room

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#748]
When turning the left socket off earlier (it did have both oil-filled radiators on it, but they'd been on for ages by then) there was a visible flash in the switch, and it tripped the electrics for that circuit.

It didn't smell good.  The plug was fine, and not at all warm.

I've covered it with masking tape and written "CHECK" across it.  We should ask the electrician to have a look when he's back doing the water heater in the kitchen.

**Comment by amcewen** [comment]
Mentioned this to the electrician when he was in just now, and he's going to sort it.  Most likely a duff socket, happens sometimes on new ones it seems.

**Comment by amcewen** [comment]
I noticed yesterday that the circuit breaker for this circuit had tripped again.  I don't know if anyone noticed when it happened?  @johnmckerrell checked with the guys fitting the heating and they hadn't turned it off.  It's back on now, but would be worth keeping an eye on.

**Comment by johnmckerrell** [comment]
Mick has now replaced this.
