### ISSUE TITLE
Get a new set of laser cutter lenses

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#749]
We discovered that Gerald lens is cracked so we've replaced with Sophia's lens to try get at least one cutter operational. This means Gerald's measuring tool isn't right anymore but if you align the overall height of the current tool with the top of the lens thread grip it cuts cleanly. We've also re aligned the mirrors successfully.

**Comment by cheapjack** [comment]
![gerald_new_ruler_needed](https://user-images.githubusercontent.com/128456/38493188-3393587c-3be9-11e8-9577-72cb0f26b80a.jpg)

**Comment by cheapjack** [comment]
Dont know if @DoESsean or @DefProc  has any record of the last lenses we bought for sophia and/or gerald? HPC don't seem to list them anymore.. I couldnt find the envelope that had the spare optics that used to be in the office cupboard, and last time I swapped lenses (maybe 10 months back or more) we had no more 'fresh gerald lenses anyway

Mirrors in Gerald are ok so dont think we need a complete set of optics, just a spare lens for sophia and gerald; then when the lens degrades its a quick fix and not a 2-7day (?) wait for lenses.

They degrade less if we regularly clean lenses but I know thats hard to fit in when bookings are flowing

**Comment by cheapjack** [comment]
By the way Sophias lens we have cannibalised for gerald is not blemish free, Ive cleaned best I can alongwith the 2 mirrors on the gerald bed which are fine but it will gradually degrade and reduce power and reliability once there are blemishes

**Comment by johnmckerrell** [comment]
Do we know which ones we want? Smoke and Mirrors sell them so if we do know we should just go ahead and purchase them:

https://smokeandmirrors.store

**Comment by cheapjack** [comment]
We'll need to measure the lens diameter and the focal length we need which im assuming is the distance from lens to material that makes most sense for gerald and sophia. Gerald has a longer focal length than sophia but they are the same diameter: I think they are 20mm diameter but ran out of time to measure on Sunday...

So maybe see what's best out of the focal lengths they have in stock? Imagine Sophia would use the lowest. 
 * 38.1mm
 * 50.8mm
 * 63.5mm

Unfortunately I've no records of what focal lengths we've used in the past for Gerald 😞 
I'm unclear how focal length affects power tbh

**Comment by amcewen** [comment]
I've removed the `broken` label, as Gerald is currently running, just not ideally.

Presumably we can measure the distance from the lens to the surface of the material (and then add ~1.5mm as the focus should be to the centre of the material), and that'll let us work out which of the lenses to get.

Digging through the closed issues, #106 is when we last bought a lens for Gerald, so @DoESsean might be able to dig out the order details (from Sharks)

**Comment by DoESsean** [comment]
Unfortunately, the only confirmation I have for the last lens purchase is
to confirm that we ordered two lens sets, nothing about sizes.

**Comment by cheapjack** [comment]
I measured up Gerald on Saturday and a 20mm lens with 50.8mm focal length will do the trick and is what our measuring tool and head was arranged for.

So https://smokeandmirrors.store/collections/products/products/copy-of-ii-vi-infrared-znse-63-5mm-focal-length-lens-20mm-od would be suitable.

However without the smoke and mirrors (& perhaps ethics) the lens is 3 times cheaper on eBay
https://m.ebay.co.uk/itm/HQ-CVD-ZnSe-GaaS-Focal-Lens-for-CO2-Laser-Engraver-Cutter-12-15-18-19-20-25mm-/322418916341

This combined with re-alignment may help #762

**Comment by cheapjack** [comment]
Need to measure up Sophia's focal length for her lens before ordering though they are also 20mm diameter lenses

**Comment by amcewen** [comment]
Measuring them now, Sophia's will be the 50.8mm, and Gerald's the 63.5mm (which matches @DefProc's [memory](https://twitter.com/DefProc/status/986158336075862016))

**Comment by DefProc** [comment]
And I've just noticed the note that the focal length described as being set to the centre of the stock in the thread, but I'll have to disagree with that.

Focus height is set to the top surface, as the cutting surface produces and sort of lensing effect.

**Comment by amcewen** [comment]
I found the spare optics envelope last night, so have put it into the laser spares cupboard.

**Comment by amcewen** [comment]
I've ordered a replacement lens now from Smoke and Mirrors

**Comment by amcewen** [comment]
Dominic from Smoke and Mirrors is going to bring this with him when he calls in to have a look at the old failed tubes from Sophia next Tuesday.

**Comment by amcewen** [comment]
The new lens has been delivered and is fitted.  Power is very slightly down compared to the whiteboard settings - speed 12, power 70 was fine in the bottom right corner of the bed for my test, but didn't cut quite all the way through 3mm acrylic in the bottom left, so as ever, check your settings before you cut.
