### ISSUE TITLE
Get work surface and door for dishwasher

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#750]
Simon Derwent says he may have a suitable bit of worktop and door for the dishwasher and will bring them in sometime this week

**Comment by amcewen** [comment]
Simon has some stuff for this, but hasn't had chance to drop them off.  The door he's got is white though, so should we look for a black door?

**Comment by johnmckerrell** [comment]
Yes

**Comment by magman2112** [comment]
As mentioned in #663, we have now managed to find a length of black worktop in the yard. I will look to cut and fit this worktop this coming Saturday.

**Comment by magman2112** [comment]
The worktop has now been cut to size and placed in position, but it still needs to be fixed in place, which I plan to do in the next few days.
