### ISSUE TITLE
Make some new Gerald Rulers

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#752]
We need a new ruler until we get a new set of lenses for Gerald and Sophia

The [orginal ruler is here](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/LaserCut/Gerald_Ruler_608.svg) so we could amend that template once we have measured up properly.

Using the tool like below gives a good cutting focus in the interim; topmost edge of tool aligned with topmost edge of the lens thread grip

![gerald_new_ruler_needed](https://user-images.githubusercontent.com/128456/38493188-3393587c-3be9-11e8-9577-72cb0f26b80a.jpg)

**Comment by KarlDunkerley** [comment]
Can we do a version that is self-standing? A couple of times I tried to use the distance piece in the top left and could barely reach the up/down controls. 

Given the bed is not always fully horizontal and slightly bowed, it would be useful to do the adjustment in the place on the bed where cutting is being done. It can be 2-3 diff from top left to bottom right in my experience.

**Comment by amcewen** [comment]
I've dropped the priority for this, because now that #749 is fixed, the old rulers work correctly again.

However, if you want to design a self-standing version @KarlDunkerley, that'd be great.  (Or feel free to close this if you're unlikely to get to it).

**Comment by KarlDunkerley** [comment]
I will get this done asap. Promise!!!

Can I suggest and inaugual laser maintenance crew soon to see who is interested and do some brainstorming about the way forward?

**Comment by johnmckerrell** [comment]
I counted 6 rulers in total, 2 hanging on the outside and 4 hiding just inside on the right.
