### ISSUE TITLE
Look into the lock/handle sticking on the disabled toilet on the ground floor

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#754]
Last night was nearly stuck in the downstairs disabled toilet by the lift, for some reason it unlocks but the catch on the handle doesn't quite release I think... anyway after some panicy jiggling it released and I could get out. No idea how consistent this issue is but worth someone at Tapestry site to look into

**Comment by johnmckerrell** [comment]
This has been mentioned to contractors by Helen, it does seem like you just have to pull the door towards yourself and it clicks and opens, can be a bit worrying though!

**Comment by johnmckerrell** [comment]
Just tested this and it all seems fine now.
