### ISSUE TITLE
Setting up a Laser Maintenance Crew

### ISSUE THREAD

**Issue by KarlDunkerley** [DoESLiverpool/somebody-should#757]
Could we set up a team of volunteers to manage the laser fleet and keep them in tiptop condition? I'm new to Does and don't have any deep knowledge of lasers or mechanics so if someone could step forward I would gladly volunteer.

The immediate aims would be to get Gerald and Sophia back in action. Then we could create a rota of maintenance of the mechanics, laser, lenses and mirrors and make sure we have stocks to cover breakages and not have them out of action for long periods.

We could also clean and restore our new Harry the Humongous (copyright K Dunkerley) and find a home for this monster so that we get it running. Preferably without paying the nearly £2k the company wants.

Would anyone be willing to step forward as the main organiser and get an initial meeting off the ground?

**Comment by amcewen** [comment]
Sounds good to me.  There's already the beginnings of such a team (and it's a long-standing direction that we've been moving in - see #244 - and something the directors will be focusing more on once the move has settled down) with @johncain39, @dazz-ling and @Dowz77 getting involved in looking after Gerald and Sophia.

(For the record, Gerald is back in action, just with a modded focusing technique - see #749)

**Comment by KarlDunkerley** [comment]
Adrian, Sean, Julian etc, I've come across a chap called Richard Butler based in prestatyn who is a laser engineer. Had a brief chat with him. I was wondering if we could meet with him to discuss getting Sophia and Gerald back to their peak and then him train us up in routine maintenance so that we can handle most of it ourselves. He's up for it and also has tubes and he can re-gas them. He's free monday morning to come in and discuss things. Would it be okay to go ahead and who could be there? I've told him no promises at this stage. Ps he can also supply controller boards for the lasers to bypass the existing ones which might be useful for Harry the Humungous.

What are your thoughts?

**Comment by Dowz77** [comment]
I am up for joining the maintenance team and a bit of training would be good, unfortunately I'm not around on Monday. Would it be possible to do the training on a maker night?

**Comment by KarlDunkerley** [comment]
My thoughts were Monday would just be an introductory chat to see about how he might help us and how much it would cost. Any training etc I was thinking would be organised through Adrian, Julian etc. I'm too new to set it up but just want to know kit works when I want to use it and we can keep everything spot on regularly. I've read so much conflicting advice, seen so many contradictory YouTube videos it would be nice to get it from someone who really knows their stuff and will train us up and provide re-gassing etc.  I don't mind getting my hands dirty as long as I know what I'm doing.

I haven't heard anything yet from senior members but I'm sure they'll respond when they've had chance to discuss it.

**Comment by johncain39** [comment]
Hi Guys,

Sounds good to me but agree that if it goes ahead we need to make it viable for all personnel to make it. This is  probably either evening time or weekend? Also at a time when the machine(s) are not in use.

Regards

John

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amcewen** [comment]
Now the move is mostly out of the way, should we see if we can get this going properly?  I've been meaning to write up what I think the requirements for the group are, but we should just meet up and I'll either have worked that out or not, but either way things will move forward.

So, I've created a [doodle poll for us to find the most suitable date](https://doodle.com/poll/4txesv5da4gqf3yh).  Please fill it in if you'd like to join the laser-maintenance team (paging @magman2112, @KarlDunkerley, @johncain39, @dazz-ling and @Dowz77 but anyone else who wants to step up too is more than welcome).

I'm assuming outside-office-hours is likely to work best.  I don't think there'll be any actual fixing/maintenance of the lasers for this first one - it'll be to work out how best to organise it, and who's going to coordinate it in future.

**Comment by amcewen** [comment]
Okay, we've had a few responses to the Doodle now, and it seems that the morning of Sunday 9th September will be best.

So, @dazz-ling, @KarlDunkerley, @johncain39 and @huffeec have said they can make it, hopefully @magman2112 and anyone else who wants to join can come along then too.

Sunday 9th Sept, at 11am.

**Comment by KarlDunkerley** [comment]
See you then.

Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com

--------------------------------------------
On Tue, 28/8/18, Adrian McEwen <notifications@github.com> wrote:

 Subject: Re: [DoESLiverpool/somebody-should] Setting up a Laser Maintenance Crew (#757)
 To: "DoESLiverpool/somebody-should" <somebody-should@noreply.github.com>
 Cc: "KarlDunkerley" <karldunkerley@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, 28 August, 2018, 17:18
 
 Okay, we've had a few
 responses to the Doodle now, and it seems that the morning
 of Sunday 9th September will be best.
 So, @dazz-ling, @KarlDunkerley,
 @johncain39 and @huffeec have said
 they can make it, hopefully @magman2112 and
 anyone else who wants to join can come along then too.
 Sunday 9th Sept, at 11am.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
