### ISSUE TITLE
Set up doorbots on the doors at the Tapestry

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#759]
The roller shutter, inner door, and then the two doors into DoES need to be put onto Doorbots.

The door control is a bit different here, but we worked it out with Tam and Simon (who've fitted the door systems) yesterday.

Mostly we just need to short the 12v and ground feed on the Molex connector (as we aren't providing power to the door, just switching a contact) and then add a DC-DC convertor so we can use the 12v supply on the doors to also power the Pi.

I've ordered all the bits we'll need for that (there are more doors, plus a few bits needed for the existing  doorbots), so hopefully will get it installed early next week.

**Comment by amcewen** [comment]
All the parts apart from the 2x20 way headers have now arrived.

We need four doorbots at the moment (we might need a fifth for the door to Room 29, but that's not lockable (or ready for inhabiting properly) yet).

We have two PCBs from Gostins with white Molex connectors on, we need to short the 12V and Ground connections on them, and we have two new PCBs soldered up which have the 12V and ground connection shorted with a wire, and a green 2-way screw terminal for the 5V and ground connection to power the Pi.  The new PCBs will need the 2x20-way header soldered on once they arrive.

**Comment by amcewen** [comment]
There's Cat5 cable to run from the RFID reader to the PCB.  This needs female pins crimped onto the end of 6 of the wires and then connecting at one end to the RFID reader and the other end to the PCB.

Doorbot 2 (the old workshop doorbot) is now installed on the double-doors to the main room with its RFID reader wired up.  The reader needs fixing in its box properly (and the old acrylic case removed first).  It then needs the green 2-way screw terminal connecting to the maglock system with Tam.  It also needs a 5V power supply connecting up, although in the short term powering it via a standard Pi power supply would work (that's what @goatchurchprime and I tested it with).

Doorbots 4 and 5 (@johnmckerrell will understand what that means) are the new Pi3 boards for the roller shutter and entrance door downstairs.  They're in the cardboard Pi boxes in the drawer of doorbot parts (@goatchurchprime knows about that), with stacking headers already on and the new PCBs.

Doorbot 4 has the blue and white micro-SD card in it.

They both need duct tape over the USB and Ethernet ports on the Pi to protect against shorts from the underside of the PCB.  One is partly done.

There are 2.5A 12V to 5V power supply PCBs in the "doorbot drawer", which will need working out how to wire into the 12V supply with Tam.  Then the 5V supply should be connected to the 2-way screw terminal labelled "Molex" on the PCB.  5V on the left, ground on the right.

@johnmckerrell will need to set up fobs and copy them over to the doorbots 4 and 5 (I haven't updated the script to do that) for the contractors, MD and Gary Millar to give them access to the doors downstairs.

Finally, the old doorbot3 (a Pi 1 with a micro-SD adapter) will need to have the 12V and ground connections tied together on the Molex, and then be wired in like doorbot 2 is, but on the door to the Events Space.

**Comment by johnmckerrell** [comment]
Added issues on log cards for the software changes that are needed.

https://github.com/DoESLiverpool/logcards/issues/6
https://github.com/DoESLiverpool/logcards/issues/5

Accessing the main door Pis is going to be tricky as it will require long ladders, we will want to look at improving their network connectivity/uptime!

**Comment by goatchurchprime** [comment]
The RFID units are this one, the SL030 http://skpang.co.uk/blog/archives/946

According to the manual http://skpang.co.uk/catalog/images/wireless/rfid/SL030-User-Manual.pdf section 3.6 the jumpers JP1 and JP2 can be shorted to give 3 new alternative I2C addresses (0x51, 0x52, 0x53) in addition to the default 0x50.  

@johnmckerrell could code this into the doorbot for the front door so we could save on the ridiculous situation of having two separate doorbots there.  

We're basically treating this as the same door (in fact we only get one switch in the box on top of the door frame, which both opens the shutter and unlocks the magloc).  

It's not going to matter if you put your tag onto the outside RFID receiver or on the inside one between the doors.  In fact the inside one is completely unnecessary, but for the fear of being trapped between the shutter and the door.  But there's a white switch there already to send it up or down, so I don't even see the need for it.

The quick hack would simply to alternate polling between the two I2C addresses looking for a signal, and just respond to whatever happens.

**Comment by goatchurchprime** [comment]
I've wired up and showed all 4 the doorbots working.  Adrian's doorbot circuit board doesn't state which are the power positive and negative on it.  

One was already working into the main room.

Two on the top of the entrance door.  Both are wired from the same power supply and both go to the same E-lock (the magloc on the inside door).  I cannot find how to trigger the shutters, and have tried shorting the terminals in the other unit that is in the box, but it didn't do anything.  The green button somehow does it, so I don't know if there's another trick of wiring.  

Both RFID boxes work.  The magloc trigger can be fast as it regrabs the door if it doesn't get pulled out at same time.  

Then I fitted the old doorbot into the events room, which was much quicker as I'd worked out how to do crimping properly, so I didn't have loads of duff connections that needed tracking down.  The magloc relocks very fast here too.  

It's a shame that the doorbots aren't running music and a screen.  There are two spare wires that you could run a mini-speaker in the black RFID scanner box for welcome messages.

**Comment by johnmckerrell** [comment]
Tam came in today and help sort the final bugs out. Actually turns out that we had the relay connecting the mag lock pins whereas it should have been connecting the push button pins, so it was shorting a live connection hence everything rebooting. Tam switch those wires around and everything now works, no power issues and the shutter is controlled by our system. I'll leave this open until we've sorted out the access rights and other bits but we're almost there.

**Comment by johnmckerrell** [comment]
doorbot4, which is the one on the inner RFID, had lost network access today when I tried to update configs. To fix this I used the ladder to reach the box over the doors and flicked the white switch (like a light switch) to turn everything off, then on. Should be noted that this would then have power cycled doorbot5 too. Mainly noting this so that we can tell how long they're staying connected to the network.

**Comment by amcewen** [comment]
I'd forgotten we had an extra two wires in the cable to the reader.  That could easily run to a speaker with the I2S DAC/Amp boards that can be added to the Doorbot PCB.  I think we've got a couple of those lying around (at least one) from the Gostins install, and I have a few small speakers we could try it with.

**Comment by goatchurchprime** [comment]
Looks like this was done long ago
