### ISSUE TITLE
Make the "door phone" more obvious in multiple rooms

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#760]
The sign by the roller-shutter door lists the phone number for the DoES mobile phone.

That currently lives in the events space/co-working room.  

There are two issues with it:

 1. It's not obvious that it's someone at the door when it goes off (and the intercom, once set up, will just call the number too, so it will be a long-term issue) because it sounds like a phone
 1. If you aren't in the room that the phone is in (e.g. it's maker night and you're in the workshop) then you won't hear it

**Comment by johnmckerrell** [comment]
I could point out it's a *mobile* phone ;-) If we could find the old phone we could set that up and have the number call both of them, or even find one/some of the VOIP phones we recovered from Gostins and get those set up in a few places too.

**Comment by johnmckerrell** [comment]
I moved the mobile to the middle of the coworking table in the events room so it should be noticed more, hopefully an incredibly short-term solution given that we'll be moving into the main room oh so soon!

**Comment by Thingomy** [comment]
Is *that* what that really annoying noise was that kept bugging us the other night?

**Comment by johnmckerrell** [comment]
@Thingomy probably

I've switched the mobile phone's ringtone to a doorbell noise so that it's more obvious.

**Comment by johnmckerrell** [comment]
I'm going to close this now as it's more documented and has a better ringtone, the next step would be provisioning other VOIP phones but I think that can come later.

Documentation here: https://github.com/DoESLiverpool/wiki/wiki/Answering-the-telephone
