### ISSUE TITLE
Network socket in Event room (by safe) partially working

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#761]
![image](https://user-images.githubusercontent.com/1537834/38806482-4f01ff72-4171-11e8-88c3-44b443d4f8fe.png)

**Comment by magman2112** [comment]
I seem to recall that not all of these sockets were patched through to the LAN switch in the wiring closet, so this may easily be resolved with some quick patching.

I’m planning to come in to DoES this afternoon, so I will check this out and correct as necessary.

**Comment by magman2112** [comment]
As I thought, sockets weren’t patched through, so now fixed.

4 more sockets are available to be patched in the event room if needed.
