### ISSUE TITLE
Fix shelf in 3D printer supplies cupboard

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#763]
The shelf in the cupboard next to the door to the metal workshop is missing a support (far left corner).

For extra credit, clean the spilt (and dried) glue from it too.

**Comment by magman2112** [comment]
I was able to modify a coat hook I found in the electronics carousel to fit as a replacement bracket. With a few turns of insulating tape, it appears to be a good fit and the shelf is now stable.
