### ISSUE TITLE
Level the workbench frames

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#764]
The floor in the main space is a bit uneven.  We've moved the workbench frames into their final (for now) places.

The adjustable feet on them need adjusting so that the tops are level.  There's a spirit level in the "Pens, rulers, colouring in" drawer.

**Comment by magman2112** [comment]
The workbench frames between the workshops and adjacent to the Electronics bench have now been levelled. This leaves the frames in front of the main window to level.

We may need to fix most of these frames to the wall though, as with the worktop fixed to them, they can be a bit unstable if someone leans on the edge, as this acts as a lever. This is less of an issue for the worktop between the workshops as this has now been reduced in width.

**Comment by zarino** [comment]
I have opened a new issue (#785) for fixing the electronics and woodworking benches to walls.
