### ISSUE TITLE
Screw worktops onto the workbench frames

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#765]
There are worktops to go on the workbench frames.  Once the frames are level #674, then we should screw them in place.  With the backs flush with the frame (see the wood workshop one for reference)

**Comment by magman2112** [comment]
The worktops by the Electronics bench and between the workshops have now been screwed down. The latter worktop has also been reduced in width by cutting off the step on the back edge, so this worktop is now flush with the wall.

Some notches may need to be cut at the back of these worktops to allow safe and easy routing of power leads to the power sockets on the wall.

**Comment by magman2112** [comment]
All worktops now securely fixed to the frames.
