### ISSUE TITLE
Build shelves for the new 3D printer cabinet

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#766]
The two Ultimakers are going to live in the black server cabinet.  We'll need to make shelves to hold them.  One of the reasons for putting them in the cabinet is to further reduce the fire risk from them, so we should make them from a fire-resistant material (sheet metal, presumably?)

**Comment by amcewen** [comment]
Sounds good to me.  Shame I'm not around on Thursday to help out.

**Comment by magman2112** [comment]
First shelf installed. Figured out how to open the cabinet doors, which was just as well, as the brackets needed to be moved to fit the printers in.

**Comment by magman2112** [comment]
All shelves now made and fitted.
