### ISSUE TITLE
Paint the bannisters of the stairs

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#768]
I will do this with anybody who fancies it

If it needs to be stripped back by hand I doubt I could do that. But if there’s other cleaning stuff that should be done prior to painting I’m up for learning how to do things!

Plus I/we need a colour scheme - @zarino ?

**Comment by johnmckerrell** [comment]
We do not have stairs in our space. We should not be doing anything outside our space without consulting the landlord. I doubt very much that he wants them treating at all.

**Comment by jackie1050** [comment]
Would varnish look good?

On 18 Apr 2018 21:15, Alex Lennon <notifications@github.com> wrote:

I will do this with anybody who fancies it

If it needs to be stripped back by hand I doubt I could do that. But if there’s other cleaning stuff that should be done prior to painting I’m up for learning how to do things!

Plus I/we need a colour scheme - @zarino<https://github.com/zarino> ?

**Comment by johnmckerrell** [comment]
The entrance *is* appropriate for a professional working space.

phew, panic over...

If in your opinion you believe work is needed then making a suggestion of doing so would certainly be a good idea. As mentioned, working with the landlord would be the appropriate path, which we are doing. The renovation work is ongoing.

**Comment by ajlennon** [comment]
Semantics John.

The entrance is awful. Nobody visiting DoES cares whether it is the responsibilty of DoES or the landlord.

This needs fixing if we are to be a professional space. 

I'm happy to work with anybody who agrees with me it needs fixing.

**Comment by ajlennon** [comment]
Upon reflection. I take my comments back. If this is not a problem for DoES then... it's not a problem.
