### ISSUE TITLE
Roof in Dinky storeroom needs fixing

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#77]
The roof in the storeroom in Dinky is still broken from the flood, and being held up by various boxes and paint tins. It would probably be worthwhile fixing at some point.

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
