### ISSUE TITLE
Shallow (20cm?) storage solution for brick wall in kitchen?

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#771]
Broken out from #690.

Investigate open, narrow profile storage solution for regularly-accessed items, on the brick wall to your immediate right as you enter the kitchen (max 20cm depth, so as not to obstruct the walkway).

**Comment by DoESsean** [comment]
I believe you're still interested in doing this @zarino, is that right?

Or has the shallow shelf beneath the cupboards fulfilled this brief?
