### ISSUE TITLE
Fix or delete the inline Gostins address on https://doesliverpool.com/contact-us/

### ISSUE THREAD

**Issue by paulfurley** [DoESLiverpool/somebody-should#772]
![image](https://user-images.githubusercontent.com/254290/38981931-74eedfd6-43b8-11e8-9d31-d3f6dc1e8c24.png)

Given that it links to the location page it's probably best to just delete the duplicated address.

**Comment by johnmckerrell** [comment]
I've fixed it, figured it's not such a bad thing to have the information there with the other contact information.
