### ISSUE TITLE
Fix the laser printer

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#776]
The HP LaserJet Pro M402dn has been reporting "Load Paper". Pulling the paper tray out I found there was a fair few sheets trying to feed in so I removed those. After some minimal poking a small part fell out. Not sure where it's come from and with it removed the printer is still asking us to load paper so I imagine it needs to be replaced.

**Comment by magman2112** [comment]
The small part clipped back into its correct apparent location and then @johnmckerrell found that the paper tray was nor configured correctly. All fixed now and the printer no longer gives a “Load Paper” message.
