### ISSUE TITLE
Find missing letters for DoES tower or print new ones

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#779]
A few of the grey letter blocks from round the top of the DoES tower model are missing. It's possible that they've been misplaced during the move, so worth keeping an eye out. Otherwise we can print some more. I believe they were printed in faberdashery.com smoky grey filament. The files seem to be here: https://github.com/DoESLiverpool/st-johns-beacon/tree/master/large-multi-piece/Letter%20Ring

**Comment by amcewen** [comment]
Having got the DoES Tower up and running, we're missing an "oES"

**Comment by jackie1050** [comment]
I'm getting "failed to load" when trying to open these with Cura - will try again tomorrow

**Comment by jackie1050** [comment]
I've ordered some smoky black PLA from Faberdashery

**Comment by amcewen** [comment]
Three letters printed and left at the bottom of the Tower ready for installation.

**Comment by magman2112** [comment]
Letters installed prior to Makerfest Liverpool.
