### ISSUE TITLE
The laser-cutter coolant needs changing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#78]
With all the use it's been having of late, the coolant is looking rather dirty.  We should get some more distilled(?) water and replace the whole lot.

**Comment by DefProc** [comment]
Laser cutters are booked as closed on the 4th March to allow for maintenance.

**Comment by johnmckerrell** [comment]
Deionised water rather than distilled, previously we've bought from http://www.merseybatteries.co.uk in the Baltic triangle.

**Comment by DefProc** [comment]
everything's cleaned and there's new water in the system, but I'd suggest it needs a flush do get out any things that have grown in the laser tubes (especially as we're adding a new tube shortly) before replacing with de-ionised water with an ethyl glycol based anti freeze/summer coolant, and some algae inhibitor.

But it does all look a bit tidier round there now, especially with the holes for the tubes in the water-bin lid.

**Comment by DefProc** [comment]
closed with the next coolant change covered by #112
