### ISSUE TITLE
Get sanitary bins for the toilets

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#782]
I've requested a quote from the people that Jason is using, this issue to track progress.

**Comment by johnmckerrell** [comment]
Just called to follow up, they should be able to delivery these on the 14th May so long as we pay an invoice that shows up tomorrow.

**Comment by magman2112** [comment]
I noticed on Friday that these bins are present in both toilets, so we can close this task now.
