### ISSUE TITLE
Organise kid-friendly coworking meetup

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#783]
I'm thinking "Jelly Tots Coworking Playgroup". Playgroup makes it clear that this isn't childcare, using the Jelly branding will help with familiarity and hopefully Jelly Liverpool will help us, at least with social media promotion.

We can't run this until the events room is ready but there's certainly some things we can do now like working out the best day of the week, generating interest and collecting information on people who are interested.

- [x] Run a poll for best day to run it
- [ ] Collect email addresses of people interested in attending (probably via the poll)
- [ ] Prepare the space
  - #665
  - #961
  - #726
  - Other issues that might need breaking out (make the doors kid safe?)
 - [ ] Work our our policies on bringing kids for coworking (like getting it clear that you are responsible for your child's safety and behaviour, what are the expectations when bringing your kids when jelly tots  is not on?)

Things to consider obtaining but not mandatory:
- [x] Foam carpet tile jigsaw piece things
- [x] Small table and chairs
- [x] Crayons
- [x] Books
- [x] More toys

**Comment by johnmckerrell** [comment]
I was wondering if we could commit to doing it weekly over the summer, during school holidays. Perhaps not as we're really aiming this at younger-than-school-age children but MD Productions will be doing stuff for school age children so there might be a chance for a tie-in, drop one kid with them and then come upstairs with the younger one(a) to get some work done. For a free event we wouldn't really want to do it more than monthly but if people are interested we can always do a "paid" version more often, or really people can mostly self-organise for that as really it would just be "paid coworking".

**Comment by johnmckerrell** [comment]
We should get some of those foam carpet tile jigsaw piece things to protect the carpet somewhat. Heating of course. It might be worth getting big square cushions that keep crawling babies in one place but it really depends what age of kids we expect. A small table and chairs could be good too, we've got drawing paper already but we could do with some crayons. We've also got play-doh already. I'll add things to consider to the list above. More books and toys would be good also.

**Comment by johnmckerrell** [comment]
In my house we've got SUNDVIK table & chairs from Ikea for £30 and £15 respectively. There's more options though, KRITTER at £25 and £12 or even LÄTT for a table and 2 chairs for just £20. If we expect them to get a lot of use though we probably don't want to get anything too cheap (although if we don't know how well this is going to go we might!)

**Comment by Robotorium** [comment]
I'm pretty sure I have a few bits and bobs for tiny makers, probably some
coloured pencils and maybe some other things. I'll venture into the wilds
of the mostly-boxed Robotorium tomorrow and see what comes out.

Op do 7 feb. 2019 om 21:00 schreef John McKerrell <notifications@github.com

**Comment by DoESsean** [comment]
Excellent, I was planning on starting a list for things we need, and now I
don't have to :)

I will definitely be bringing in one of the 4 (four) duplicate Duplo trains
Xander has.

**Comment by Robotorium** [comment]
I'll bring in some crayons and colouring books later this week

Op di 12 feb. 2019 10:06 schreef Seán Gleeson <notifications@github.com:

> Excellent, I was planning on starting a list for things we need, and now I
> don't have to :)
>
> I will definitely be bringing in one of the 4 (four) duplicate Duplo trains
> Xander has.
>

**Comment by DoESsean** [comment]
We actually need to sort out a proper changing station.

If we can get some posters designed and printed (preferably on some decent paper stock as well if it's cost effective) I'll take some to put around the baby places I go.

**Comment by johnmckerrell** [comment]
I've brought in some magnetic letters. The whiteboard nearest the front of the pile is magnetic. Ideally we would want to mount this on the wall near the ground.

**Comment by DoESsean** [comment]
So, we're going to need:

- [ ] Foam Carpet Tiles
- [ ] Table and Chairs
- [ ] Crayons
- [ ] Books
- [ ] Toys
- [ ] Soft Play Mat
- [ ] Changing Station
- [ ] Toy/Baby Stuff Storage
- [ ] High Chair

I reckon I'll have a look around some charity shops over the weekend - you can pick up loads of stuff cheaply, and they're not of worse quality than brand new, the vast majority of the time. I'll also have a word with Laura and see what, if anything, she'll be willing to part with, even on a loan basis while we see how this goes and whether it's worth investing more money in.

The storage is an interesting thing. As we're already looking for something to go under the window, it might well be worth spending a bit on this and getting something good that will act as regular storage as well as for the kids' stuff. The more awkward thing will be finding somewhere to keep high chairs/kids tables and chairs/other things that don't easily break down into stuff-away-able size.

**Comment by johnmckerrell** [comment]
Added mention of steps for in the toilet, not absolutely required but if they're cheap they're worth having.

Another one for the list is that it might be worth having paper towels on hand as some kids (mine) get freaked out by the high power hand dryer.

**Comment by DoESsean** [comment]
I think mine is ok with them now, so long as he's prepared. I may have used quite a bit of exposure therapy on him.

**Comment by Robotorium** [comment]
Barring calamity, I'll bring in crayons, coloured pencils and colouring
books tonight.

Op do 21 feb. 2019 om 13:06 schreef Seán Gleeson <notifications@github.com>:

**Comment by DoESsean** [comment]
@johnmckerrell Are you able to take a lead on getting this stuff in by Tuesday? Happy to help, of course, but I won't be in again until half an hour before we're supposed to start, and I've got family down this weekend.

If there's anything I can do, just let me know.

**Comment by johnmckerrell** [comment]
Really I’ll just look on amazon if I get time. Anything from ikea Jackie should be able to get. 

--

**Comment by jackie1050** [comment]
I can get IKEA stuff tomorrow or Monday evening if you tell me what's wanted
________________________________

**Comment by Robotorium** [comment]
I dropped off 3 colouring books, a set of coloured pencils and one of
crayons. Adrian put them on Seán's desk for Tuesday.

Op do 21 feb. 2019 16:55 schreef Jackie Pease <notifications@github.com>:

> I can get IKEA stuff tomorrow or Monday evening if you tell me what's
> wanted
> ________________________________
> From: John McKerrell <notifications@github.com>
> Sent: Thursday, February 21, 2019 4:46:08 PM
> To: DoESLiverpool/somebody-should
> Cc: Subscribed
> Subject: Re: [DoESLiverpool/somebody-should] Organise kid-friendly
> coworking meetup (#783)
>
> Really I’ll just look on amazon if I get time. Anything from ikea Jackie
> should be able to get.
>
> --
> Sent from my mobile phone hence brevity and errors
>

**Comment by DoESsean** [comment]
I would say that if @jackie1050 can pick up the things listed above that come from IKEA, that'll be a good start 😊

**Comment by jackie1050** [comment]
Will do
________________________________

**Comment by johnmckerrell** [comment]
I've ordered foam carpet tiles, should delivered to my home tomorrow.

**Comment by johnmckerrell** [comment]
Apparently expedited shipping means "in about a week", I changed my order last night but they're now not due until tomorrow so we'll just have to see when they turn up. Coming to DoES now.

**Comment by johnmckerrell** [comment]
Checked B&M and they had the foam squares, got 2 packs of ten, only opened one so far, can see what we think if/when the others come tomorrow.

Another "toy" idea I had was dress up clothes, I notice all the museums have them these days. Would be nice to get relevant ones but I'm not sure there's a specific "maker" costume. White coat perhaps, boiler suit, er.. any more?

**Comment by Robotorium** [comment]
Goggles. Lots and lots of goggles.

Op ma 25 feb. 2019 om 15:11 schreef John McKerrell <notifications@github.com

**Comment by johnmckerrell** [comment]
Didn't understand what you meant at first but yeah safety goggles could be a fun one.

So we've done one event, it went pretty well although we didn't have all that many people turn up, people seemed to enjoy and appreciate it though. There was some talk about a Thursday being a good day for the next one. Do we think we're ready to try to commit to a monthly event yet?

**Comment by DoESsean** [comment]
I would say yes, definitely, unless there is a reason why not.

Monthly really isn't that often, so I can't see why we would struggle at
all. I think the bigger step will be to stop it just being a gimmicky thing
that we do on specific days, and make it so that it's just an option for
parents that want it, and how we actually do that. Would we need to make it
something you have to book ahead of time so we know to keep Dinky
available? Do Findout have preference over parents, or is it first booked,
first served? What do we need to cap numbers at before we have to move into
the Event Space (which we can't really do until the summer)?

I think we've made a good start - and it seems that Jennifer who came along
is very well connected and well placed to help us publicise, so that would
be great. From what she was saying, there was a lot of interest among the
Mummies That Make group, and that seems like an absolutely perfect fit, at
least in the initial stages. I think we now need to work out how we can
entice more parents in for next time.

**Comment by DoESsean** [comment]
As we've arranged the first day, and held more since (albeit with limited success), I think this can be closed, especially as the outstanding issues around how we get more people to attend and make it more visible are tied up in other open issues.
