### ISSUE TITLE
Fix electronics bench and woodworking benches to walls, to prevent tipping

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#785]
In #764 @magman2112 said:

> The frame next to the Electronics bench should ideally be fixed to the wall, for stability. This has already been done for the other frames by the windows. This should also be done for the bench in the woodwork room.

**Comment by magman2112** [comment]
All of the benches have now been fixed to the wall (and leveled where required). Thanks to Matt for his help in sorting out the Woodshop bench.
