### ISSUE TITLE
Roland the vinyl cutter spools 1½ metres of blank space before cutting

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#788]
@cheapjack and I wanted to cut some vinyl signs for the toilets today (#719) but when we printed, we couldn’t get Roland to stop spooling loads and loads of vinyl before he started cutting.

We were following [the instructions from the wiki](https://github.com/DoESLiverpool/wiki/wiki/RolandVinylCutter). We tried with and without the "rotate 90 degrees" option ticked, and we tried clicking "Apply" in the Print dialog box _before_ clicking the final "Print" button – it made no difference.

I guess we could just let Roland cut where he wants – two metres up the roll – but it seems like a waste to have this weird, 1½ metre offcut left over. 😢 

While investigating the cause, we noticed the wrong driver is installed on Roland’s PC – Roland is a CAMM-1 CX-24, but the driver is for the CAMM-1 GX-24. (Probably because Roland doesn’t make a CX-24 driver that will run on Windows 7.) We wonder whether that might be causing issues? Although it clearly _used_ to work before the move, albeit using the "rotate 90 degrees" hack.

@SayBeano you seemed to know a lot about the vinyl cutter a year or two back. Any ideas?

**Comment by zarino** [comment]
@SayBeano what doesn’t make sense is, our Inkscape canvas was 537x420mm, and we’d set the driver dimensions (as described in the wiki) to 537x420mm to match – so, even if there was an errant path somewhere _way off_ the Inkscape canvas, surely the printer driver would then scale the whole artboard down to fit it into a 420mm height? The plotter was _definitely_ reaming more than 420mm of vinyl before it started to cut.

**Comment by SayBeano** [comment]
That's that theory ruled out. Let me see how I am fixed and I'll try and get in this Thursday or Saturday for a bit. What software is being used to send the "print" these days?

Corel Drawn supports this plotter, which I think we have. Let me reach out to someone on twitter too, I'll tag us.

**Comment by amcewen** [comment]
It *didn't* do that for the test cut I did last week - might've spooled forward a bit, but only ~10cm.  I'd basically followed the wiki instructions, although @jackie1050 had done the first bit.

This  was in Inkscape, which AIUI is what's generally used these days.

**Comment by cheapjack** [comment]
Rather than invoking git blame it is worth noting that I wrote the wiki instructions on cutting from inkscape originally based on what seemed to consistently work at the time which was then edited and added to and improved by rest of us, which I didnt mention last night @zarino 😨 ... 

Thinking on I realised I ignored my own wiki writing 😜 and left the vectors of the "non-gender specific toilet symbol" I generated by converting a .jpg, as filled vectors.. I didn't check on any rogue nodes that this conversion *can* make sometimes in inkscape: so this may well override print driver settings so @SayBeano theory cant be fully ruled out. 

So our file we were printing probably not the best test esp. as @amcewen had no issues. If im in on Maker Night Ill test with a file im confident with and then review the wiki. It's on the desktop as of last night

Also Corel Draw (I love the idea of 'Corel Drawn' @SayBeano ;) ) was what my old `knackered-offcut-laptop` originally used with the cutter, and as it was windows 98 or something of that vintage it had the supported drivers for the CX-24 which are not available for Windows 7 after a quick trawl last night. It may well be worth trying Corel draw with it as an alternative. I think ideally we avoided this as we wanted to encourage inkscape use if possible so you could build skills in an open source tool that you could then use across vinyl cutting, sublimation printing, hot press & laser cutters. All this coming from someone who still uses illustrator for vectors as thats what I was trained in...

**Comment by johnmckerrell** [comment]
I just successfully cut some t-shirt vinyl. The first time I tried it the machine spooled the whole reel through. I then changed the height in the printer preferences to be just larger than the width of my design and It worked fine. Won't close this until you've tried again.

**Comment by zarino** [comment]
Ok, I think @cheapjack narrowed this down to weirdness in the SVG file we were trying to cut. He reimported the vector into a trial version of CorelDraw, cleaned it up there, and sent it to the cutter from there, and it worked.

**Comment by SayBeano** [comment]
Sound!

**Comment by cheapjack** [comment]
Ok sorry to be opener of closed issues...I attempted to document this last night but my github app sucks on my phone and failed
Eventually @jackie1050 & I managed to print by making a new `svg`, removing all fill, any errors we could see in Inkscape and ungrouped any artwork then cut it in a trial of CorelDraw we found on board the pc. Heres what happened in detail:

 * The new file in Inkscape still spooled over 1.5m of material when using the `ROLL` setting on the cutter, before cutting, despite changing and applying the print dialog print preferences to match the width of the roll that the machine specifies after loading and a suitable length to match our vector work. We made sure rotation was `off`
 * We then read the [manual](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/Manuals/Roland%20cx-12-24_use_manual_r5.pdf) 📜 😨 and looked at a few cutter options still assuming we wanted to use the `ROLL` loading setting 'cos thats what we tend to need to use. I fixed a broken link to this manual in the wiki page.
  * `AREA` on the cutter was set to 1.0m which manual suggested was how much it spooled before cutting which we changed to 0m so we thought that might be issue.
  * We also set the `ORIGIN` on the cutter before cutting to where we wanted
  * No other on board cutter settings seemed relevant
 * Despite this it still spooled out 😞 
 * We noted how the print driver (still mindful that it's the driver for a CAMM1 GX-24) dialog in Inkscape despite changing print preferences wrt dimensions prior to printing, when re-checking these settings seem to not be retained or saved.

So we took @SayBeano lead and gave up on Inkscape & used Corel Draw
 * CorelDraw V5 failed to open
 * CorelDraw V4 opened but is a trial with 14days left as of 11/5/18
 * We opened a test file @jackie1050 had seen someone print successfully 
 * Having zero Corel experience we then opened up the print dialog and settings, and it clearly used the same GX-24 driver; it had almost identical options as it appears in Inkscape but with some other Corel specific options. 
 * Using the defaults and the same procedure re rotation and dimensions we hit print and it spooled to where we expected on the test file. We then changed position of the vectors on the artboard in Corel and again it cut where expected with no spooling.
 * I then opened up my corrected toilet sign `svg` in Corel and followed procedure and lo it cut without ridiculous spooling 🍾 
 * Shortlived joy however when it seemed to cut in a very odd way:
  * Cut twice on almost all vectors: this is probably an error in the vector artwork, but was unable to detect it in vector nodes using either Inkscape of Corel
  * Seemed to be unable to cut a seemingly single vector between 2 points, but would split it into 2 or 3 cuts which leads to tiny nicking cut errors so not clean enough.
 
So overall Corel seemed to work (need to test a bit further and add some sort of guide to the wiki) but I don't really have any knowledge of it and could not work out how to edit vector nodes, so if we can get some knowledge on it (like reading the manual 😨 ) it may be a way forward. 

We could still encourage design in Inkscape. Maybe updating Inkscape might be a fix not sure.
So doubt there are any issues with the pc images or builds  @ajlennon :)

**Comment by cheapjack** [comment]
So it *works* for as long as Corel runs but ive kept it open for now, removed broken tag and retained bug tag until we get a licence for Corel and establish & document this as the recommended workflow. 😄

**Comment by ajlennon** [comment]
Oh good 👍

**Comment by johnmckerrell** [comment]
FWIW I loaded an SVG file into Corel and found it had applied fills where Inkscape did not show fills so that may be why you were getting double cuts (I'd imagine you would look for or notice that but perhaps as you had prepared it right in Inkscape you didn't notice Corel doing the wrong thing.
