### ISSUE TITLE
Make protective equipment easy to access at the entrance to the metal workshop

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#790]
Because the metal workshop contains CNC machines that might throw broken bits across the room, anyone inside it should have eye protection.  We should make it easy to remember (and apply) that.

 * [ ] A warning sign on the door
 * [ ] A rack of safety glasses on the wall outside, next to the door (Should it have ear defenders too?)

**Comment by amcewen** [comment]
We could print a few of these for hanging ear defenders on - https://cults3d.com/en/3d-model/gadget/duck-headphone-hanger

**Comment by amcewen** [comment]
![Ear defenders in place](https://pbs.twimg.com/media/Dgte3LCXUAMhtcq.jpg)

Ear defenders provision now installed.  We still need something for the safety glasses

**Comment by DoESsean** [comment]
Glasses are also hanging on the ducks right now. Seems to be working.
