### ISSUE TITLE
Investigate Gerald laser cutte software crashes

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#793]
The laser cutter software seems to be crashing frequently, sometimes 2 or 3 times before it works. 

I'm not sure if it's happening more often since the PCwas upgraded

**Comment by johnmckerrell** [comment]
Is this still happening?

**Comment by jackie1050** [comment]
I don't think it's been happening much - it did happen once when I was showing someone how to use the laser cutter around a week ago.

**Comment by amcewen** [comment]
Haven't heard of anyone complaining of this of late, so going to close it until it's reproducible (/happening)
