### ISSUE TITLE
Get new cam locks for the front panels of Gerald

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#794]
We need new cam locks so that Gerald's front panels are no longer held on with duct tape. I have ordered four 20mm locks from here:

https://www.ebay.co.uk/itm/16-20-25-30mm-CAM-LOCKS-Filing-Cabinet-Post-Mailbox-Drawer-Cupboard-Locker-2-Key/152505075459?ssPageName=STRK%3AMEBIDX%3AIT&var=451857368212&_trksid=p2060353.m2749.l2649

**Comment by johnmckerrell** [comment]
These have turned up, almost perfect size. Bit tight so we might want to bend the cam, see what others think.

**Comment by magman2112** [comment]
These have now been fitted and all work. These locks are keyed differently, so the numbers of the keys are shown on small labels below each lock. All keys are on the general Gerald keyring - stored in the laser spares cupboard.
