### ISSUE TITLE
Ensure our evening meetup organisers know how to get in and lock up

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#799]
We should make sure that the organisers of the various evening meetups know how to get into the new space and what they need to do lock up.

**Comment by DoESsean** [comment]
I've sent an email to the group organisers for Linux User Group, Wearables and Friends of the Earth as the regular groups that currently have meetings planned.

I've also put the salient text from that email into the 'Process' tab on the Organisers' gitlab, so it can be used in the future for new groups.
