### ISSUE TITLE
Improve the filament feed for the RepRap

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#80]
The RepRap can't be left unattended as it has a tendency to get its filament tangled, killing the print and also not doing great things to the printer (it has thrown itself off the desk in the past IIRC).

There are two things that would improve it:
- [x] Building a decent spool holder, maybe try printing off this one - http://www.thingiverse.com/thing:508896
- [ ] Adding a guide tube, similar to the one the UPs have.

**Comment by amcewen** [comment]
Spool holder printed and assembled.  Now we need to buy a longer length of guide tube and fit it (probably whenever the extruder is upgraded to the one @DefProc has printed to allow it to use flexible filament)

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.
