### ISSUE TITLE
Move the wiki/wiki to the somebody-should repository

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#801]
It would be a lot more convenient if the search on a github repo searches both our wiki and issues at the same time.  

I think this can be done with a pull and a push as the wiki is implemented as a self-contained github repo, so it should be easy to copy across.  (Unlike the issues which are in quite another form entirely.)

We want to encourage more of a back-and-forth between the two repositories of information.  As a piece gets fixed, the instructions get written up and put on the wiki.  While things wrong with items in the wiki have issues associated to them.

(Also, I with we could change the "somebody-should" name of the repo.  I don't like it, especially as it becomes more generic and central.)

**Comment by amcewen** [comment]
You don't appear to have done anything to disseminate this information to the community, beyond adding a "this has moved" message at the top of the "old" wiki.  Or if you have, I can't see any evidence of it in this issue (or any new "we need to tell everyone the wiki has moved" issue).

When we moved office, we did a bit more than just tack a "DoES Liverpool is now at the Tapestry" note on the door of the old space (we did do that, but that was probably the least important bit of telling people about the move).

If you did *all* of the job of moving the wiki, which includes communicating the changes (or at least making a decent effort to move that side along) then you'd get less push back from those of us who see issues like this one and can also spot the wider confusion and workload that you're proposing throwing onto our plate...

Off the top of my head, we'd need to:
 * Update the links on the main website
 * Update the homepages on the assorted computers around the workshop, which go to the wiki page for their respective bit of kit
 * Email the Google Group

You haven't even fixed the 19 links to the pages in the "old" wiki that are contained in the wiki itself.

**Comment by johnmckerrell** [comment]
~Just because you've moved something somewhere doesn't mean this is "done". All of the links on the website, the internet, and http://wiki.doesliverpool.com are pointing at the original repo. You shouldn't make sweeping changes like this just because you feel like it.~

What he said.

**Comment by DoESsean** [comment]
Did all this get updated so that everything reflects the wiki's new home? If so, let's get this closed.

**Comment by johnmckerrell** [comment]
Sean - checking if the changes have been made and changing them are surely within your skill set?

--

**Comment by DoESsean** [comment]
Fair point!

I've self assigned so that I can run through all the changes that needed making and update anything that I can.

**Comment by DoESsean** [comment]
There are no longer any dead links on the website, all have been redirected to the correct page on the new Wiki.

Equipment PCs are going to the right page.

Links to other pages within the wiki have been corrected so that there are none still going to the old site.
