### ISSUE TITLE
Put the new membership and rates on the wiki

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#802]
I can't find a page detailing the new schedule (memberships and all that) immediately to hand, but I'm pretty sure the numbers on the front page are wrong: https://github.com/DoESLiverpool/wiki/wiki

**Comment by goatchurchprime** [comment]
What about prices for the LaserCutting?  Are these accurate or need to be pointed at your page?  
    https://github.com/DoESLiverpool/wiki/wiki/LaserCutting

I'm not sure I like the layout of the page with all its colours, etc.  
    https://doesliverpool.com/services/

Something written out in a simple table or services...price, like a restaurant menu would make it a lot clearer, and could more easily encompass all the options.  (eg full day room hire, laser ply and 3D printing costs, can of coke 40p, etc).  

It would also be good to explain how to pay (get a monthly bill, or leave random bits of cash one people's desks).  

I think the price list is so important as the deal it ought to be on one sheet of PDF so it can be pinned on Sean's desk as the bottom line.  It gives so much clarity.  If you pay the very modest fee (which is wholly for the purpose of covering the running costs and making this place epic) you have as much right to be here as anyone else in the room, so you can feel comfortable.

**Comment by DoESsean** [comment]
[https://drive.google.com/open?id=1lBqcYOdwYqG29tnW1FsqV5cmjQjrnjIw](url)

I don't think I've missed anything, but holler if you see something obvious that isn't there.
