### ISSUE TITLE
Public nodered on a RaspberryPi with a big screen able to run a dashboard

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#803]
Following on from #616 we need to do something with all this MQTT signals we don't yet have

There are some lovely dashboards that can be controlled and thrown up on a big screen to show some activity:
    https://oneguyoneblog.com/2017/06/20/mosquitto-mqtt-node-red-raspberry-pi/

@amcewen's big idea is to put a Sonoff POW on every device, from the laser cutter to the 3D printers (as long as they don't keep rebooting like one version I had) and monitor the power and activity as a live stream that we can eventually publish onto the wider internet to show that we are quite busy.  Then use this to challenge other hackspaces to do the same with their equipment to show activity.

The Sonoff's could also have an RFID reader to control access to the devices to those authorized using the doorbot databases.

**Comment by ajlennon** [comment]
Oooh this sounds fun !!!

**Comment by goatchurchprime** [comment]
There's a RaspberryPI plugged into the big screen by the VR equipment (as well as my vocopi headset).  (This was an out of date doorbot Rpi that Adrian used for the mqtt server, so it's memory can be erased, and hopefully it can upgrade enough to run a nice dashboard.)

At the moment all I could do was run mosquitto_sub from the command line to watch my spoken words come up.  

I should re-install espurna on the Sonoff Pow plug right now to generate its copious messages to work with.

**Comment by goatchurchprime** [comment]
@willcrobinson has commissioned a Pi3 (on loan, and previously used for vocopi whose SD card is next to it) running the main screen at the front.  Its address is doris.local and you can get to its node-red program at http://doris.local:1880  There's also http://doris.local:1880/ui which shows the output of the dashboard, where we have some graphs of the fridge power useage.  

Other sonoff POWS (or POW2s) should get plugged into the laser cutters and the coffee machine to produce dashboards of activity and the age of the coffee (as well as turning the coffee machine off after 5pm to save electricity).  Kettle boiling (quantity and duration).  Also subject to testing: dishwasher, aircon, magloc, 3D printers, general table power sockets.  

There should be (1) sandbox development, (2) internal deployed and (3) public website deployed versions of the nodered dashboards for lessons, experimentation, operational and publicity.

**Comment by goatchurchprime** [comment]
This is in theory working of the mqtt.local server, but would like to mount it more safely on the wall and have the TV on more.  @MatthewCroughan is supposed to be coding it to do stuff.
