### ISSUE TITLE
General improvements to Gerald

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#805]
I have been discussing a few planned improvements to Gerald with @amcewen and @johnmckerrell, so time to capture these in one place so they can be ticked off as they are implemented.

## For Gerald
- [x] Obtain and install a new control panel.
- [ ] Install new Cam locks and obtain and install new hinges for front removable panels.
- [x] Install new x-axis drive belt and check alignment
- [ ] Find font for Gerald signage, cut and fit new vinyl signs.
- [x] Obtain and fit draught excluders on main lid to improve smoke clearance.
- [x] Replace Twin and Earth power cables with proper mains flex.
- [x] Check mirror alignment screws to see if any need threadlock to reduce alignment issues due to vibration.
- [ ] Investigate flatness of bed and identify methods to improve flatness.
- [x] Install new Silicone tubing for Air Assist nozzle

## General laser issues
- [ ] Build a log spreadsheet and store it on Github to capture laser tube, lens and mirror replacement dates, log lens cleaning and any other issues that should be logged for all laser cutters.

- [ ] Look at building a visible laser alignment tool to speed up mirror and lens alignment (possible 3D print of bracket to clip onto a mirror).

- [ ] Inventory spares in laser spares cupboard and agree with laser maintenance team what spares should be stocked.

**Comment by KarlDunkerley** [comment]
Should also document the controller type on Gerald and Sophia to see if there are better controllers and software available.

**Comment by JarmanSE** [comment]
My experience is limited to metal-cutting lasers, but the distance between the head and workpiece seems very large on the big laser - when cutting metal the laser just provides the heat and the airjet drives the cut, this is a lot more effective in close proximity.  I would have expected the focal plane to be just a couple of mm below the exit aperture, not an inch or so where it currently is.  Might be wrong lens?

The machine currently seems a bit slow and only cuts thin materials, this **MAY** make a world of difference if it's correct.

**Comment by KarlDunkerley** [comment]
All CO2 lasers I've used at various fablabs and with various makes are around 10-20mm from the head. The cutting depth is dependent on the focal length. Standard lenses are generally 50.8mm but they range from 30mm to 100mm. The latter are best for deep foam as the effective clean cutting range is much longer.
It would certainly be useful to have multiple lenses for different types of job and they cost around £10-20 each on eBay.
However, the gap on Gerald feels normal to me though I'm not up to date with whether we are still using the lens from Sophia as a stopgap.

Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On ‎Monday‎, ‎4‎ ‎June‎ ‎2018‎ ‎22‎:‎52‎:‎58, JarmanSE <notifications@github.com> wrote:  
 
 
My experience is limited to metal-cutting lasers, but the distance between the head and workpiece seems very large on the big laser - when cutting metal the laser just provides the heat and the airjet drives the cut, this is a lot more effective in close proximity. I would have expected the focal plane to be just a couple of mm below the exit aperture, not an inch or so where it currently is. Might be wrong lens?

The machine currently seems a bit slow and only cuts thin materials, this MAY make a world of difference if it's correct.

**Comment by JarmanSE** [comment]
Accepted.  I googled it and the optics on the more general purpose lasers are set up for maximum focal range (about 8-10 mm long useable focus), normally starting around 20mm below the aperture.  It's probably just fine as it is.

Sean

**Comment by magman2112** [comment]
I managed to pick up some hinges which look to be the right size - for the grand total of 44p + VAT from Beesley and Fildes the other day. We now need to remove the old hinges (chisel them off, as they appear to be spot welded on), then drill and rivet the new hinges in their place.

**Comment by KarlDunkerley** [comment]
Hi Mike,
What's happening with the laser maintenance crew?
Are we going to try and meet?
I'm working Wed-Fri now but up for other times.
Let me know.
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Thursday, 21 June 2018, 16:02:44 BST, Mike Gorman <notifications@github.com> wrote:  
 
 
I managed to pick up some hinges which look to be the right size - for the grand total of 44p + VAT from Beesley and Fildes the other day. We now need to remove the old hinges (chisel them off, as they appear to be spot welded on), then drill and rivet the new hinges in their place.

**Comment by magman2112** [comment]
Added a new task to fit new air assist tubing, now that this has been obtained.

**Comment by amcewen** [comment]
We got a new control panel from Dominic at Smoke and Mirrors last Friday, along with a spare lens and an O-ring (#387)

**Comment by magman2112** [comment]
New air assist tubing has been fitted several weeks ago - catching up on some of the actions.

Also, the new control panel needs mounting holes in slightly different places to the current panel. These holes will need to be adjusted before the new control panel can be installed.

**Comment by KarlDunkerley** [comment]
Hi Mike,
Saw you had made some much-needed improvements.
Haven't heard much on the LaserCrew front since that meeting.
Let me know if you would like a hand with anything.
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Thursday, 18 October 2018, 17:03:29 BST, Mike Gorman <notifications@github.com> wrote:  
 
 
New air assist tubing has been fitted several weeks ago - catching up on some of the actions.

Also, the new control panel needs mounting holes in slightly different places to the current panel. These holes will need to be adjusted before the new control panel can be installed.

**Comment by magman2112** [comment]
A draught excluder has now been fitted to the lid for Gerald, which should improve the airflow on the extractor.

**Comment by magman2112** [comment]
The twin and earth lead has now been replaced with correct mains flex. 

Also, all of the mirrors have been checked and cleaned. The one next to the laser was badly burned and was replaced by a silver mirror. Alignment was found to be good across the whole bed.

**Comment by DoESsean** [comment]
As this hasn't been updated in three years, during which time all kinds of stuff has been done to Gerald, can I assume that it's been supplanted by other issues and is closable?

**Comment by JackiePease** [comment]
Seems to be being dealt with under #1642
