### ISSUE TITLE
Connect the kitchen IR sensor bin to the mains (via AC-DC adaptor)

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#806]
Rather than changing the batteries every few months it's probably worth hooking this up to an adaptor plugged into a mains outlet. Takes 6 AA batteries so would need 9v, not sure what ampage, probably not all that much although it's a motor lifting a (small) load.

**Comment by DoESsean** [comment]
Are we bothered about this? I don't think changing the batteries is as much of a problem as overcoming the inertia that would have to be beaten to actually do it.

**Comment by johnmckerrell** [comment]
Yes I still want to do this.

**Comment by johnmckerrell** [comment]
I worked on this yesterday, played with possible voltages and currents. Found that 6-9v with around 500mA should do the trick. Found a 6v 600mA old Nokia charger and wired that in, seems to work well and is now in place. I would prefer to improve the wiring, if only because it's a bit short but also using proper connectors would also be better.

**Comment by johnmckerrell** [comment]
Looks like the cables on this got damaged, probably when cans of drink were delivered. I wanted to replace the bell wire anyway but it's certainly something to keep in mind, that the wires will make this a little tricky, they should probably be taped to the floor but we need enough flex that you can actually take the lid off the bin.

**Comment by johnmckerrell** [comment]
I did a lovely job of splicing in a longer piece of cable only to find the bin wouldn't then open. I've given up on re-use and found a brand new 9v adapter to use which is currently powering the bin. We need a socket that can be mounted on the bin and a few metre extension to finish the job nicely.

**Comment by johnmckerrell** [comment]
Finished, quite tidy now, I've duct taped the cable to the wall to hopefully avoid snags but I think we'll be ok. The connector is fitted quite nicely to the bin so any cabling can be replaced if necessary. Thanks @amcewen for the Farnell order.
