### ISSUE TITLE
Replace the toilet seats

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#807]
The existing seats are pretty nasty and flimsy. Replace with something sturdier, ideally soft close? Holes are 145mm apart and go all the way through.

**Comment by DoESsean** [comment]
I think this might still be a viable idea, but obviously isn't top of anyone's priorities. Are we still interested in doing it, or can it be (soft) closed?

**Comment by johnmckerrell** [comment]
This finally happened in #2026 !
