### ISSUE TITLE
Investigate flickering of LED lighting in main room

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#808]
The LED lights in the main room appear to flicker in such a way that some people can see and some people not. It really bothers some people though so we should check to see if there's a way of remedying it (I'm wondering if they're dimmable and it was decided to turn them down slightly which means they flicker more). I've mentioned to the landlord but he's asked me(/us) to talk to the electrician next time he's in so that it doesn't get lost in translation.

**Comment by goatchurchprime** [comment]
It's particularly noticeable if you wave wires about or pour water.  

Someone suggested that it's 100Hz (ie rectified mains).  We should at least get the make and brand and datasheet of that lighting equipment here so we know its parameters.  Maybe a tall ladder to see what it says on the side.

I've been meaning to run a light cell on an arduino to record its intensity at a 0.01ms resolution for half a second to see what kind of square wave it operates at.  (Maybe this is a job for makernight.)

**Comment by zarino** [comment]
+1 for changing these light, if budget allows. I find them super distracting, and I know other people do too.

**Comment by Thingomy** [comment]
+1 for sorting it out also -- it is actually bad enough I believe it will
discourage some people from using the space. In theory it could also cause
issues with some of the work going on in the space, product photography,
motion sensing security cameras and possably light gate end stops.

JR Peterson

**Comment by johnmckerrell** [comment]
I've contacted the electrician, waiting to hear back.

**Comment by johnmckerrell** [comment]
> I’ve arranged a site visit from a rep of the manufacturer of the light fittings to visit the job . I’ll call you when I get a time  , thanks

**Comment by johnmckerrell** [comment]
Mick has told me that the manufacturers will be in touch with me to arrange to replace the lights. He also talked about them having equipment that can use to test to see if there's something going on with interference from other things or something like that (not sure if that's electrical interference or optical). I did mention to him that we've tested with just the kitchen lights and that they still generated the effect in the events room so that would be with a single light fitting. Not really Mick's area anyway so we'll just need to wait for them to get in touch.

**Comment by paulfurley** [comment]
I *think* this was affecting me last week in room 29. Curiously I was getting painful eye / head aches every day I was in last week (I assumed I was just very tired).

On Friday I was working from a coworking space in Lisbon and expected to get a headache again, but didn't. Same thing on Monday and Tuesday.

Then I realised we only recently started putting the lights on in room 29 when the clocks went back.

I can't be sure but I *think* this is what's been causing the problem.

**Comment by goatchurchprime** [comment]
Someone needs to get up on a ladder and find out of there is a product ID on what these crappy lights are, get the datasheet for them, and then look for a compatible product we can replace them with, so we know what can be done should we decide to do it!

Some say the flicker can't be noticed:
   https://www.electro-tech-online.com/threads/100hz-flicker-in-lighting-is-hazardous-to-humans.154485/
And some say it sort of does:
   https://wwtonline.co.uk/67708/PressRelease/the-importance-of-choosing-flicker-free-led-drivers/34240

**Comment by zarino** [comment]
> I _think_ this was affecting me last week in room 29.

FWIW I think this thread, so far, as been about the LED lights in the main room, kitchen, and breakout nook. They’re the ones with a noticeable "flicker" when you move your eyes quickly.

I must admit, I can’t say I‘ve noticed any such flickering when standing under the more typical (but still LED?) flush surface mounted lights in Room 29, the small workshops, and the Events Space. I just did a quick test by waving my hand while under the light in "new" Dinky, and couldn’t see any strobing.

That’s not to say the lights in Room 29 weren’t affecting _you_ @paulfurley, but if they were, there’s a chance it was for a _different_ reason to the "flickering" from the hanging lights in the main room, kitchen, and meeting nook.

**Comment by johnmckerrell** [comment]
I’ve tried calling the number someone stuck on my desk for the guy who turned up and couldn’t see the problem so I’ll see if I can get anywhere with him again. (Just called but had to leave a voicemail).

**Comment by zarino** [comment]
If we’re approaching these as "broken" lights, then I’m not sure we’ll get anywhere. The lights are probably all functioning as intended – They’re just crap.

**Comment by johnmckerrell** [comment]
I’m told that they’re inappropriate for the space as they’re intended more for warehouse type facilities where they would be suspended more like 8m above the space and wouldn’t be around screens. “Jack” told me that they won’t have the problem on the ground floor (although it’s hard to be sure now as there’s no-one in there to ask and only some people have instant problems with them). Apparently he told the electrician this so it would be back to him and/or Jason to do something about it really.

**Comment by paulfurley** [comment]
> That’s not to say the lights in Room 29 weren’t affecting _you_ @paulfurley, but if they were, there’s a chance it was for a _different_ reason to the "flickering" from the hanging lights in the main room, kitchen, and meeting nook.

Yeah quite possibly it's not the flickering for me. I had forgotten the lights in room 29 aren't the same. It's possible that it's bright monitors in a (sometimes) poorly lit room. Or dim monitors in a (sometimes) extremely bright room!

I do mess around with the brightness on my monitors quite a lot trying to compensate!

**Comment by johnmckerrell** [comment]
Possibly relevant https://news.ycombinator.com/item?id=18644590

**Comment by amcewen** [comment]
The four lights in the main room have been swapped for different units now, which *seem* to show this problem less (testing with my phone camera I could still see a bit of strobing but *far* less than I did with the old lights).

It'd be good if any of the people who've found this more noticeable can report back on if it's an improvement.
