### ISSUE TITLE
Add linktr.ee to our Instagram

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#813]
I noticed lots of Insta accoubts Have línktr.ee, which lets you to link to more than one thing in your bio. 
Somebody should check if this is the best option, and set up account and links e.g. location and price pages on website, Twitter account etc.

**Comment by Pezmc** [comment]
I feel like our website can probably handle that task pretty essily, we
should have links to our location/price/Twitter etc clearly on the landing
page!

**Comment by jackie1050** [comment]
Great - I haven't seen the new website yet, but happy if that's the xase
