### ISSUE TITLE
Create new prices notice for the 3d printers

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#815]
We used to have a notice with the price per gram for 3d prints. I can't find a copy in Somewhere Safe. Somebody should check what we should be charging and produce a new notice (the scales are on the shelf under the Ultimakers.

**Comment by johnmckerrell** [comment]
This issue suggests £3.60/100g, that right? https://github.com/DoESLiverpool/somebody-should/issues/398

**Comment by johnmckerrell** [comment]
I think this is done.
