### ISSUE TITLE
Fit soundproofing into Room 29 and Events space

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#816]
Following discussions with landlord and MD we are looking at fitting soundproofing solutions in the floor of Room 29 and the events space. Unfortunately this delays us using room 29 but will hopefully block out the noise from below.

Current state is that we've had recommendations of products from Hush Acoustics and they've suggested two companies that would fit them. I've now contacted both companies asking for quotes.

**Comment by johnmckerrell** [comment]
#708 and #707 are blocked until this is done.

**Comment by paulfurley** [comment]
I'm doing my best to stay zen, but between the *unebelievable* racket from building upstairs and the intermittent booming from downstairs, and the *extremely loud* booming after about 5.30, it's not proving a great place to work at the moment :(

Regarding the events room and evening noise, have we got anywhere with our friends downstairs? I have to make a decision whether to relocate my digital self defence workshop ASAP so I can print posters... any update?

**Comment by paulfurley** [comment]
This is waaaay better since our neighbours sadly

> I'm doing my best to stay zen, but between the _unebelievable_ racket from building upstairs and the intermittent booming from downstairs, and the _extremely loud_ booming after about 5.30, it's not proving a great place to work at the moment :(
> 
> Regarding the events room and evening noise, have we got anywhere with our friends downstairs? I have to make a decision whether to relocate my digital self defence workshop ASAP so I can print posters... any update?

This is *waaay* better since our neighbours downstairs moved out. The work upstairs is *almost* finished (@Helen-8 and I talked to them today), and it's quieter now anyway. There's a bit of drilling going on downstairs, but it's looking up!

**Comment by johnmckerrell** [comment]
Great, to confirm the intention is to wait a few more days just to confirm the new tenants are quiet and then go for ply & carpet in Room 29.

**Comment by johnmckerrell** [comment]
As the noisy tenants have moved out we are no longer intending to do this.
