### ISSUE TITLE
Work out what port forwarding we want on our static IP

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#817]
@mattwilsondotuk has got a static IP address for us (just waiting for when he can get into the server cabinet downstairs to install a router for it) and he'll let us know when it's live (there'll also be ~30 minutes downtime when that happens, but it should be around midnight one day).

We need to work out what port forwarding we want from that.  We can always request more in the future, but what do we want set up initially?

**Comment by johnmckerrell** [comment]
The obvious ones to me are doorbots and webcams. We don't have the webcams active yet but perhaps we reserve some ready? So starter-for-ten:
* 2223-2227 for doorbots
* 8081-8085 for webcams

I'm assuming they just get port forwarded in to our router where we can then forward to a specific IP address, so we don't need to know the IP address now? Actually even if that's the case we could always assign IP addresses now as we've done for dootbots.

**Comment by skos-ninja** [comment]
Just a thought is we should probably not port forward things that provide access to the building and instead we should vpn into the network to then access that stuff?

**Comment by johnmckerrell** [comment]
While it wouldn't worry me too much as I'm confident in the security given by SSH (and that's the only thing we'd be port forwarding) being able to VPN in wouldn't be a bad thing either.

**Comment by skos-ninja** [comment]
Yeah I would trust SSH however making sure everything is kept up to date packages wise (with webcams that's a fun task!) is difficult and can be bad if someone managed to get into the front shutter Pi!

**Comment by skos-ninja** [comment]
For this to begin with I would say we should setup a vpn service on the networking Pi once I have rebuilt the image and then go from there as that should then give you access to any cameras and doorbots.

In future though I wonder if it's worth once we have an IPv6 block then we can just assign every device an IP and then they can access it externally from there and use per device firewall?

**Comment by johnmckerrell** [comment]
Yeah, I’ll go with that (VPN). I assume we know in advance which ports we’ll need for that?

**Comment by skos-ninja** [comment]
So I completely forgot that the UniFi Security Gateway actually supports running a VPN server on it so we can use that instead!

Once the Pi is setup I will go through the steps of setting this up and then give you the port and then the L2TP key. You can have multiple logins so this would be the best approach

**Comment by ajlennon** [comment]
Can I have whichever port was forwarded into my Linux build box back. Thanks.

**Comment by amcewen** [comment]
We've now got a static IP, so we can ask for whatever port-forwarding we're after.

**Comment by skos-ninja** [comment]
Is there a reason why Baltic can not just DMZ our router and then we can port forward from there?

**Comment by johnmckerrell** [comment]
I've pinged Baltic an email to check if we can DMZ the router.

**Comment by MatthewCroughan** [comment]
@johnmckerrell Do we have any idea how much a second IP would cost?

**Comment by johnmckerrell** [comment]
Not off the top of my head but I'll ask when they get back to me.

**Comment by johnmckerrell** [comment]
I'm going to close this as I think it's better covered by #1074 and #1075 now.
