### ISSUE TITLE
Investigate tension problems on sewing machine.

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#818]
Lots of loops of thread on the back of sewn fabric. Tension seems tight on top thread but couldn't see how to adjust it.

**Comment by ka81** [comment]
I'll grab that when I'm in Jackie. Be your shuttle on your bobbling feeder. Caz

**Comment by jackie1050** [comment]
This has been ok recently. We could still do with general advice from @ka81 when she's around.
