### ISSUE TITLE
Sophia's monitor shouldn't distort your designs

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#82]
The resolution of the monitor on Sophia is such that it stretches what is displayed on it - so a square cut will look like a rectangle on screen.

It doesn't affect the cuts, but regularly confuses users of the laser-cutter.  We should switch it for a monitor that doesn't exhibit the problem (especially as we've a few options to try just knocking around the space).

**Comment by DefProc** [comment]
This could also be solved by moving the hard drive over to the Dell machine under the desk and installing the correct graphics drivers.

**Comment by ReddbridgeMark** [comment]
Is this just a Windows issue with it not recognising the resolution of the monitor properly? If so, something like PowerStrip can be used to manually add the right resolution (you'd need to know what the resolution is supposed to be though) http://www.techrepublic.com/article/customize-monitor-resolution-settings-with-powerstrip/

**Comment by madjake45** [comment]
I do believe it is a driver issue but really I think we should move away from using a server for sophia so we can hear each other whilst the machine is on.

**Comment by ReddbridgeMark** [comment]
Server has been switched over, and a replacement monitor has been put in place.

This has helped to **minimise** the distortion issue but not eliminate it. I have tried to add the right resolution for the monitor (driver install didn't change it), but to no avail. One to try another day.

The resolution currently being displayed is 1600 x 1200.

The native resolution of the monitor now in place is 1920 x 1080 (standard widescreen) at 60hz.

**Comment by DefProc** [comment]
I realised that we do have a 4×3 VGA monitor in the workshop, so I've changed it over. unfortunately it's not a great resolution (*less than* 1600×1200), but it does give fix the distortion. 

On the basis that the original issue is gone, I'll tentatively close this.
