### ISSUE TITLE
Work out how to make the door entry phone ringing during events less stressful

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#821]
The intercom rings all the phones, including the one in the events room, and when I was running an event on Monday, I wasn't expecting it.  It was quite embarrasing.

I don't thind I'm asking for the phone to be turned off when the events are booked into that room, because they might be open events and the event organizer might need to let people in.

Do we need a sign near the phone that reminds events organizers they can silence the ringer if they're not expecting guests?

**Comment by johnmckerrell** [comment]
Yes, you could even unplug it, someone should really write a wiki page about this (see #820 !)

**Comment by zarino** [comment]
Ah, I was worried unplugging it might break it!

**Comment by JarmanSE** [comment]
How about using a cctv cam to look for QR codes and issuing event delegates a one-use QR to print and show the camera to gain access?

Interesting little project for someone?

**Comment by goatchurchprime** [comment]
Is there an app that lets your phone do an NFC that is compatible with the doorbot reader?   Something looks possible here: https://developer.android.com/guide/topics/connectivity/nfc/hce

Could this be a means of issuing one-off tickets to event members? 

Suppose the doorbot RFID thing was also able to communicate back to the tag (which happened to be a phone) and tell you that you've come too early.

**Comment by DoESsean** [comment]
Has this problem been solved/solved itself? I don't think anyone has commented on it for a while (at least certainly not to/within earshot of me).

**Comment by johnmckerrell** [comment]
For the record - don't unplug the phone, just turn the volume on the ringer down. Although try to remember to turn it back up again when you're done!

**Comment by johnmckerrell** [comment]
Further comments for the record, there's a pair of buttons that look like a volume slider, to turn the ringer down just press the button on the left, to turn it back up press the button on the right.

<img width="773" alt="yealink-phone" src="https://user-images.githubusercontent.com/27243/184032465-d70de36f-303f-474d-858e-8863b904045b.png">
