### ISSUE TITLE
Make/buy some durable black tablecloths for use at events

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#822]
It would be good to have some tablecloths to use at events, both to give the DoES stand a distinctive look, and to cover battered trestle tables.
Black seems like a good choice as it's in our logo, and won't show the dirt too much.
We should be able to get some cheap fabric at Abakhan and finish the edges by machine, or we might be able to get ready made.
Would be good to have for Makefest but not essential.

**Comment by amcewen** [comment]
We've got these now, right?  Can we close it @jackie1050 @zarino?

**Comment by jackie1050** [comment]
@zarino did a great job on sourcing and cutting these to size - our stand at Liverpool MakeFest looked awesome.
