### ISSUE TITLE
Organise World Cup Sweepstake

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#823]
Just sent this to the Google Group, but I'm putting it here as well because I reckon more people will read it here :)

We're looking to organise a couple of little games around the World Cup, one sweepstake and one prediction competition, and want to know what your thoughts are on costs/prizes and format.

For the sweepstake, we'd separate out the teams into two pots of 16 (one pot with the top 16 sides, and one with the bottom 16 as decided by FIFA ranking (with Russia automatically in the top pot as hosts and one of the number one seeds)), and each person would get one team from each pot. We're thinking £5 for two teams, with the prizes going to:

The winning team (£30)
The runners-up (£15)
The worst team (sorted by least points, then worst goal difference, then fewest goals scored) (£15)
First Own Goal (by round of games. If two teams score in the same round of games, the earliest in the match will win) (£10)
First red card (same rules as Own Goal) (£10)
These categories give absolutely anyone a chance of winning - while someone like Saudi Arabia may not have much chance of going to the final, they have as much chance as anyone of having the first sending off  And more than most of being the worst team.

The prediction competition would have no limit on number of people that could play, and would be £2 per person to enter. There will be various things to predict, and the people that get most right will split the money, with 50% going to first, 30% to second and third and last getting 10% each.

Does this seem like a good idea? Is anyone up for getting involved?

Let us know, and we'll get the thing swung into action next week in time for the big kick off.

**Comment by amcewen** [comment]
There wasn't enough take up of this to warrant it this time round.
