### ISSUE TITLE
Re-jig the co-working area in the main room

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#824]
At Maker Day on Saturday we did a bit of experimenting with a different layout for the co-working desks in the main room.

If we rotate the current desks through 90 degrees, and move them up to where the carpet starts then we can fit in a run of three desks.  That means we'll get an extra six desks into that space, which gives us potential for an extra ~£1000/month of income.  Plus it would make screens perpendicular to the windows rather than parallel, which would cut out reflections.

The bank nearest the door would butt up against the pillar, so it could get power and networking from there.  The other bank would get power/networking from the carpet end, running from the floorbox by the 3D printers.

There are some minor knock-on effects from that - we'd need to move the bank of six workshop desks about a foot nearer to the windows (basically moving the leg to the other side of the floor box); the 3D printers would need to move onto the carpet, and we'd need to re-jig where the coffee, small sofas, etc. live; similarly the printer and phone.

**Comment by amcewen** [comment]
It might be worth getting this done one evening this week before Jelly on Thursday

**Comment by amcewen** [comment]
We've moved all the furniture around and built the six new desks, and shuffled the sofas, etc round too.  It's looking like this:

![The new co-working area](https://pbs.twimg.com/media/DfvUFX_WkAESzKj.jpg)

Going to leave this open until I've worked out which of the power sockets on @ajlennon's desk need to be left plugged in or how we power things down safely, in order to tidy up the trailing cables providing power.

**Comment by ajlennon** [comment]
When you figure it out @amcewen can you let me know? ;)

**Comment by amcewen** [comment]
@ajlennon your various devices may have experienced brief network and power interruptions in the past half-hour :-D  On the upside your cables are probably tidier than they've been before ;-)

The power distribution to the bank of desks is sorted now.  In a final bit of rework I'm going to bring another extension from the floor box over to the East bank.  There's a 6-way in position on that bank, but I can't route it over to the floorbox until the 3D printer has finished its current print.

**Comment by amcewen** [comment]
I've finished reworking the power provision now, in a window in 3D printer usage.  Re-jig finished!
