### ISSUE TITLE
Member's rpi based storage 

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#827]
I was just looking at a new hard drive for backing up all my stupid videos-- and then I wondered if I could put it on a raspberrypi in the network cabinet so I could access it online.  

Apparently someone has thought of this before, to the extent that there is already like an open source version of dropbox.
    https://www.avoiderrors.com/raspberry-pi-3-into-a-personal-cloud-storage-2017/

I'd happily order the bits (Rpi, 2Tbyte drive), with a bit of help with the networking stuff if this is technically the best option.  

Ideally I'd like to plug and unplug the external drives into one of the many USB ports on the Rpi, and let other people do it with their own backup external drives too.  Is there a way to control the power out of the USB connector so we don't leave the disks spinning 24/7 for the months that no one needs them?  

If the UI is right, this could be a local member's service, like the postal address thing for a small fee, except you're using your own drive and are responsible for personally coming in and taking it away if you want it back.  It would very much be in the spirit of the way we do self-service laser cutting or 3D printing, you can do your own self-service cloud storage.

**Comment by Sean-anotherone** [comment]
I have an alternative for consideration...
Amongst the "under the bench pile" I have both Thecus and Buffalo 4-bay NAS boxes.  Both are dated, but both are working.  They will probably only take drives up to about 0.5 or 1Tb in size but I would happily donate one if someone wants to set it up.  They have FTP built-in too  as a possible alternative to drop-box.

If there is interest I'll bring one in.

**Comment by goatchurchprime** [comment]
Looks superceded by #947
