### ISSUE TITLE
Buy/find air assist tubing for Gerald

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#828]
The air assist tubing was recently damaged in a minor fire. @magman2112 has cut it down so that the undamaged part could be used. It is just long enough to not jump off again, now that @zarino has rotated the colllar that connects the plastic tube perpendicular to the cutting head.

There is some discussion in #596 about buying replacement tubing following a previous fire, so there should be some tubing of the correct diameter, but we haven't been able to find it.

**Comment by magman2112** [comment]
It would appear that all of the tubing we have in stock is too large, as @jackie1050 has already noted. I did find some silicone rubber tubing that fits over the existing tube though, so I put a small section of this on the air assist tube on Gerald today, which has extended the now sacrificial section slightly and allows easier subsequent changes as needed.

I also measured the existing tube, it appears that we need 5mm internal diameter tube for this application. There are a number of suppliers on eBay which have PVC tubing of this size, so I will order a couple of meters, to use as replacement sacrificial pieces should they be needed in the future.

**Comment by magman2112** [comment]
I now have received the tubing i ordered and it is now in the laser stores cupboard by Gerald. The tubing is silicone, so a bit more flexible, it also a bit thicker than the PVC tubing that is currently installed on Gerald. I have checked though, the tubing will both fit the nipple on the air assist nozzle and should fit through the cable guide. 

I would suggest that this tubing be fitted on the next planned maintenance outage for Gerald.
