### ISSUE TITLE
doesliverpool.com - no SPF record present

### ISSUE THREAD

**Issue by willcrobinson** [DoESLiverpool/somebody-should#829]
According to mxtoolbox.com, there's no SPF record published for doesliverpool.com. This might mean that some of the E-Mail sent from the domain will be dropped.

One of the GSuite administrators needs to log in at https://admin.google.com/, go to the GMail settings and create the SPF record from there. From there, they need to add a TXT record on the 34SP DNS settings page.

**Comment by johnmckerrell** [comment]
I've added:
`"v=spf1include:_spf.supportbeemail.com include:_spf.google.com ~all"`

Hopefully that'll work. Hopefully I'm right in thinking that just those two places will be sources of emails. It is possible to get supportbee to send emails via SMTP but Gmail refused to allow it and I didn't bother pushing it (you could enable insecure apps). Will leave this open until we've checked it's showing up and email still works.

**Comment by johnmckerrell** [comment]
Fixed the missing space in the previous comment *and* in the DNS record ;-)

**Comment by DoESsean** [comment]
Since @willcrobinson hasn't raised anything about this since, I'm going to assume that whatever @johnmckerrell did has worked and close this issue.
