### ISSUE TITLE
Improve storage in the solvents cupboard

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#830]
The solvents cupboard has a second shelf for it, but currently seems to be missing 3 of the fixings.

We should find/make fixings to allow that shelf to be mounted properly, and also make another shelf (or two?) to let us make better use of the storage space in it.

We could also then move the paint and varnish from the racking by the fire exit into the bottom of it to free up more space there.

**Comment by magman2112** [comment]
I made some new shelf brackets from some steel brackets today, using the one spare bracket as a template. The made brackets aren't exact copies but they work, so I think we can close this issue.
