### ISSUE TITLE
Work out which bits of "character" electricals metalwork we want to remove

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#831]
Jason has had the asbestos report back for the old electrics boxes, etc. dotted round the space.  None of it has any confirmed asbestos, and there are only two points in our space which have "potential asbestos".  That basically means two areas that they can't confirm the lack of asbestos because the units are sealed at present - if they remain sealed then there won't be a risk, but we'd probably have to label them appropriately.

Those areas are:
 * the wall between the windows in the main workshop area
 * the "Startet" box in the corner of Room 29 nearest the kitchen

Jason would like to keep as much of the rest of it on the walls as possible, but is happy to remove things if we need to use the wall space.

I think we should get the two areas with  "potential for asbestos" removed, as stickers would only be likely to worry people, and we've been talking about using the area between the windows in the main room for more storage anyway.

Are there any other areas we want to clear?

**Comment by jackie1050** [comment]
The box on the wall by the kitchen (with the clock) might get in the way of any potential television/gaming display solutions we want to put there, it already looks a bit messy with what we’ve got – on the other hand it does add interest.

________________________________

**Comment by ajlennon** [comment]
Could this be renamed "Work out which bits of beautiful authentic historical fittings must be removed for Health and Safety reasons" ?

**Comment by amcewen** [comment]
It could, but then it'd only be about two bits of it, rather than all of it...

**Comment by ajlennon** [comment]
Ouch

**Comment by ajlennon** [comment]
Could this be renamed "Work out which bits are beautiful authentic historical fittings which must be removed for Health and Safety reasons, yet which bits are "character" electrical fittings which only David Dickinson could possibly become engorged about?" ?

**Comment by DoESsean** [comment]
To be honest, I'd get rid of all of them and have clear walls, but I know
Jason isn't happy about that, and I doubt I'd find a majority within the
community that would agree with me either.

**Comment by amcewen** [comment]
They're coming to remove the bits we don't want tomorrow (Thursday 12th) afternoon, so we need to let them know then what to remove.  At present I think the list is:
 * the two bits that they haven't opened up to check for asbestos
 * All of the stuff in between the windows on North side of the main room
 * The stuff by the internal window in Room 29 (and we can close up the fuseboxes in there so they look nicer)

**Comment by DoESsean** [comment]
As this has sat untouched for so long, I have to assume that what is left on the wall is what is being left for good, so I'm going to close this issue.

**Comment by jackie1050** [comment]
We definitely want some of this stuff to go still e.g. between the workbenches where we want to add storage for vinyl etc

**Comment by jackie1050** [comment]
Jason is coming in to discuss with John on 14 November

**Comment by johnmckerrell** [comment]
We need to clear the area around the wall where we want to store the vinyl so that Jason's workman can get to it, they'll be in on Tuesday morning.

**Comment by johnmckerrell** [comment]
These went today.
