### ISSUE TITLE
Set up an OpenSource DoES testing OpenBTS GSM/GPRS cell

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#832]
Please make your issue:
* Specific

Setup an OpenSource OpenBTS GSM/GPRS cell

I've been having chats and have wanted to do this for ages.

I got some cell hardware ages ago off eBay and had it working but we need a test license to proceed. I got stuck filling in the form and could do with some help.

Anybody fancy working on this with me? @magman2112 ? @skos-ninja ? 

* Measurable

Box in place we can do cellular comms through

* Achievable

Had it working before. 

* Responsible

Alex et al

* Time-constrained

6 months

**Comment by ajlennon** [comment]
Some resources:

[OpenBTS](http://openbts.org/)

[OpenBSC](http://osmocom.org/projects/openbsc)

Harald Welte talk

[Abstract](http://www.embeddedlinuxconference.com/elc_europe10/sessions.html#Welte)

[Videos](https://bootlin.com/pub/video/2010/elce/elce2010-welte-openbsc.webm)

**Comment by amcewen** [comment]
It'd be worth chatting to @9600 about it, as he got a test licence for a year and spun up a cell at [OSHCamp2012](http://oshug.org/event/oshcamp2012).

Can we get it to run LTE Cat-M1 and/or NB-IoT too? :-D

**Comment by 9600** [comment]
Osmocom is a lot more interesting than OpenBTS, IMHO. They recently switched to a new architecture too, which more closely resembles that of a classic GSM network. This can also support 3G via a femto box. See:

https://osmocom.org/projects/cellular-infrastructure/wiki

I just recently got this running on our Circumference 8+1 node cluster. For a description and video of it in action, see:

https://www.crowdsupply.com/ground-electronics/circumference/updates/running-a-gsm-network-with-a-limesdr-mini

Of course, you can run it all on a single host if you like.

Not aware of any FOSS implementation of LTE Cat M1 or NB-IoT. Spectrum may also become more of a challenge with higher bandwidth waveforms.

**Comment by ajlennon** [comment]
That all sounds awesome @9600. For starters I think I'd like to get whatever I get can going on the old ip.access nano-BTS I have in a box somewhere around here?

**Comment by ajlennon** [comment]
I see something about #FOSDEM on your GitHub @9600 ? One of my favourite conference trips. You get out to Brussels much? Love the Delirium Café Friday night beer fest...

**Comment by ajlennon** [comment]
Found it. Now just got to remember howt to get it going...

![nanobts](https://user-images.githubusercontent.com/1537834/41812931-144da834-7724-11e8-8e1c-3d203962fe2f.JPG)

**Comment by 9600** [comment]
@ajlennon nice! Note also that packages are available, so you don't have to go building everything from source. 

Get to FOSDEM when I can. Was there for a day earlier this year. Do enjoy visiting Belgium.

What's the rack unit, a PA?

**Comment by ajlennon** [comment]
NB. I got to the point last night where I configured up the NanoBTS to talk to Osmo-BSC and was able to set up MNC and MCC and that. Got a bit stuck at that point. I do remember last time I had a phone connecting up to it though...

**Comment by 9600** [comment]
Looks like a PA + duplexer.

If you're using the new decomposed architecture you'll need OsmoHLR, OsmoMSC, OsmoMGW and OsmoSTP configured also.

Drop me a line via e-mail.

**Comment by ajlennon** [comment]
Will do! Cheers

**Comment by IfitsBrokeDontFixit** [comment]
Your correct, it is in fact a signal booster for GSM BTS ipaccess running on 800 - 1200 MHz 
(Not specific to ipaccess, but what it was used on)
Using Reverse Sma to Ntype Plug from BTS to Booster.
The unit is approx 20w max output, switches on the back are attenuation.

Not sure on the antenna, but the ones we used are alike. They where x polar 800 - 1200 MHz directional

Don't try and use your phone next to it, as it had an exclusion zone (approx 20m) used in external field operations. Great for outdoors mounted on a pole!

Hope this helps (Ex-FMS)

**Comment by DoESsean** [comment]
Where are we with this? I have literally no clue what any of it is about.

**Comment by ajlennon** [comment]
For me this is still awesome stuff. Have chatted to @magman2112 and he's willing to help me set up our own cell tower. I'm stuck on how to fill in the form to make it legal for us to test. People have advised me and apologies but I've dropped the ball. If anybody who knows how to fill in the form would sit and help me for an hour or so in exchange for cake/beer it would really help move it on

**Comment by IfitsBrokeDontFixit** [comment]
Hi guys,
If you need some help i can give you an email of a friend
He will be able to help you

**Comment by ajlennon** [comment]
Please - would really appreciate that! I am @embedded_iot on Twitter or ajlennon ... dynamic devices.co.uk

Thanks! A/

**Comment by ajlennon** [comment]
No progress on this for ages (and sort of superceded by LoRa and NBIoT LPWAN) so closing for now
