### ISSUE TITLE
Decide where the library should go

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#837]
The old library was in Dinky on a shelf.

There are books around and about to go onto a new (to us) bookcase but where should this go?

We're possibly blocked on other work to be done (e.g. quiet room) before this could be possible but we could decide where it should go (unless we want to do a Fahrenheit 451)

**Comment by DoESsean** [comment]
The library appears to have been sited in Room 29, in what I'm calling the Reading Zone, so I'll close this issue.
