### ISSUE TITLE
Update the photos on our yelp entry

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#838]
I've just updated our yelp entry (and claimed it) so that the address is right. It would be good to add some more up to date photos too.

**Comment by johnmckerrell** [comment]
That’s odd, I’m sure I changed it, I’ve done it again, we’ll see if it sticks.

John

**Comment by DoESsean** [comment]
Just had a look, and it seems to have changed now.

**Comment by johnmckerrell** [comment]
I've now updated the photos.
