### ISSUE TITLE
Prep Rm 29 for littlepinkmaker biomaterials workshop

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#840]
I think @magman2112 has been getting Room 29 ready for the workshop starting on Thursday at 5pm. Littlepinkmaker is arriving around 4.30pm to setup and will ring office intercom on arrival

@jackie1050 is arriving at 6pm to help out and Im around at 7pm. @magman2112 @amcewen  @zarino are any of you guys around at 4.30 to welcome her show her the room? 

Im around on Friday to help if she needs anything and there as ticket buying punter

Timings for her workshops from her [eventbrite](https://www.eventbrite.com/e/2020-futuristic-materials-3-day-workshop-tickets-46508624548) are:

 * 28th June 2018 - 17:00 - 20:00 Open sourcing and ethics - Presentaion/Talk, just needs projector she has her own laptop.

 * 29th June 2018 - 16:00 - 21:00 - Biomaterials and Bioplastics evening, think she just needs some workshop space for this but ive asked if she needs anything else

**Comment by amcewen** [comment]
If today's workshop is just a talk, it might be better to run it in the events space, as no-one else is in there today and that's got blackout blinds, which will work better with the projector.

**Comment by cheapjack** [comment]
I agree lets put her there instead. Inc. @jackie1050 & @magman2112 so they see this. Not sure why Room 29 suggested Id assumed there was a clash I didnt know about. Better i think and already setup and as this is an after hours event, easier to manage. Hope you or any others dont mind giving her a quick intro tour and housekeeping :)

Maybe when she's setup suggest she could hover by the entrance to manage workshop ticket holders who turn up? (No idea of no. of tickets sold)

PS Jackie and I had planned to be in office when she arrived, but she could not get time off work, and Ive got physiotherapy appointment cant afford to miss. She'll be there by 6, me by 7 in case littlepinkmaker needs anything

**Comment by jackie1050** [comment]
There was a clash when initially set up, and to me it seemed preferable to use the same room on both days (@magman2112 and I checked light levels and were happy there wouldn't be any glare affecting the projector at this time of day), but it is a bit hot in there so happy with this change.

I might be a bit later than 6, as I have to collect the wings from Uma - get back to me if that's an issue.

On 28 Jun 2018 12:51, "Ross Dalziel @cheapjack" <notifications@github.com> wrote:

I agree lets put her there instead. Inc. @jackie1050<https://github.com/jackie1050> & @magman2112<https://github.com/magman2112> so they see this. Not sure why Room 29 suggested Id assumed there was a clash I didnt know about. Better i think and already setup and as this is an after hours event, easier to manage. Hope you or any others dont mind giving her a quick intro tour and housekeeping :)

Maybe when she's setup suggest she could hover by the entrance to manage workshop ticket holders who turn up? (No idea of no. of tickets sold)

PS Jackie and I had planned to be in office when she arrived, but she could not get time off work, and Ive got physiotherapy appointment cant afford to miss. She'll be there by 6, me by 7 in case littlepinkmaker needs anything

**Comment by cheapjack** [comment]
Sounds like it went ok. Sorry could not be there to help out, migraine attack on motorway home :( Ill come in early for her workshop today. Ah yes remember reason for moving to rm 29 now. Sounds like she doesnt need anything additonal or has let people know in person. closing :)
