### ISSUE TITLE
Fit a door-closer to the laser cutting room

### ISSUE THREAD

**Issue by paulfurley** [DoESLiverpool/somebody-should#842]
When the extractor fan is being used the room makes quite a lot of noise, which gets quite draining after several hours.

The door unfortunately opens itself at the moment. It would be lovely if it closed itself instead.

**Comment by magman2112** [comment]
This door is missing it's striker plate (it is still fitted to a frame in Gostins building I believe). I have ordered one from eBay though, which should be with us in a few days. The door should then stay closed when it is closed once this is fitted.

I also suspect that we should try to avoid door closers, as this may cause problems from an accessibility point of view.

**Comment by KarlDunkerley** [comment]
I've just added some ideas for improving the laser cutters that may help with the noise issue. Check out #845 and #846

**Comment by magman2112** [comment]
I have now fitted the door plate for the Woodshop door, it will now stay closed if someone closes it, rather than blowing open with a breeze. It's down to people to get used to closing this door now methinks.

I will close this issue for now, but we can re-open it if it is deemed that a door closer may be advisable in the future.

**Comment by paulfurley** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thank you!                                                                                                                                                                          From: notifications@github.comSent: 9 July 2018 2:48 pmTo: somebody-should@noreply.github.comReply to: reply@reply.github.comCc: paul@paulfurley.com; author@noreply.github.comSubject: Re: [DoESLiverpool/somebody-should] Fit a door-closer to the laser cutting room (#842)  I have now fitted the door plate for the Woodshop door, it will now stay closed if someone closes it, rather than blowing open with a breeze. It's down to people to get used to closing this door now methinks.
I will close this issue for now, but we can re-open it if it is deemed that a door closer may be advisable in the future.
