### ISSUE TITLE
Hold a #MakerCarBoot

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#844]
I've got a load of stuff to get rid of and particularly with the ongoing #Maintainer talks @cheapjack @jackie1050 am loathe to just skip it.

I also don't want piles of stuff to be sitting all over irritating people.

I had thought of itemising things and sending out a big email but realistically it's going to take forever.

So instead I was thinking of a #MakerCarBoot one Sunday or something.

We could have brunch, put loads of stuff on tables and people could take things away.

I intend to give stuff I don't need/want any more away for free but maybe other people would want to sell or barter.

Good idea? Bad idea? Thoughts?

**Comment by johnmckerrell** [comment]
I think there’s still a bin in the Otterspool tip for small electronics so you might want to take the remainder there (or a more local tip with similar facilities!)

**Comment by ajlennon** [comment]
Excellent - thanks

**Comment by DoESsean** [comment]
Yeah, Otterspool does electronics.

I think the idea of a 'car boot' is great though. It might actually be a
fun thing to run on a semi regular basis - say bi-monthly - and allow
people to bring their own crap to shift on (with the proviso that nothing
gets 'accidentally' left behind, of course). Could even end up bringing a
little bit of money in for DoES.

**Comment by ajlennon** [comment]
Yeah good thinking. We could link it to the DNOD system. DNOD a bunch of stuff over the 2 months. Move it all to a table, have a Sunday makerbrunch and skip whatever is left over? #DoESCleanUp

**Comment by DoESsean** [comment]
That seems like it would work. Now we just need someone to run the burger
van.

**Comment by johnmckerrell** [comment]
I'm wondering about having a bring & buy sale or a jumble sale at the party. All profits to DoES.

**Comment by jackie1050** [comment]
I think if we did this at the party then we should move the launch event aspect to another date - or maybe we could have a table sale this Sunday before the match (and possibly do something for that too if England get through)?

On 11 Jul 2018 09:59, John McKerrell <notifications@github.com> wrote:

I'm wondering about having a bring & buy sale or a jumble sale at the party. All profits to DoES.

**Comment by DoESsean** [comment]
Well now I'm sad again.

**Comment by amcewen** [comment]
There was a bunch of stuff on tables, and now what's left has been taken to the tip, so I think this is done, right?

**Comment by ajlennon** [comment]
There's a printer of mine and a bunch of bits of table.

If nobody wants the printer then when I work up the courage I shall take it to the tip...
