### ISSUE TITLE
Future Improvements to Lasers - Air Filtration System

### ISSUE THREAD

**Issue by KarlDunkerley** [DoESLiverpool/somebody-should#845]
Once the Laser Maintenance Crew (or whatever it is called) is fully established, could we look at designing and building an air filtration system?

This should mean that;
We won't need to vent outside and therefore need ducting and holes bashing in walls
It will mean machines can be placed anywhere in the Tapestry more flexibly
Future machines will be easier to integrate
We avoid noxious materials being pumped into the atmosphere and upsetting neighbours

Ideally the system would be closed loop so that air going into the laser comes out, is filtered and goes back in cleanly. This will reduce airborne contaminates eg woodworking dust gumming up the works.

It should also use readily available filtration materials eg HEPA filters, fans, ducting and our own fabrication tools to build it with.

**Comment by DoESsean** [comment]
Is any of this possible or likely? Or should we close it as a nice idea that is unlikely to happen?

**Comment by goatchurchprime** [comment]
Assigned @Sean-anotherone to comment and close this as he's the most likely person to say something on the record and useful about the practicality.

**Comment by Sean-anotherone** [comment]
It is possible, but even allowing for the requirement to leave a window open a crack to ensure there is enough ventilation, I doubt this would be very affordable.  The hepa cartridges and filter media are all easily available but the restriction in flow needs a bigger fan to keep the air moving and it is not exactly a quick job to do a media change.
Given that we have the ducting and a hole through the wall, the best option is to continue with the plan to use a small filter to trap the bigger particulates and dilute the smoke and smells outside, round the corner from the current discharge window.

I have seem the filters fail in lab-grade fume cupboards after just a couple of weeks use and cause analytical work to come to a halt.  That lab had ducted cupboards reinstalled in short order.

**Comment by JackiePease** [comment]
Closed in favour of #1697
