### ISSUE TITLE
Future Improvements to Lasers - Cooling System

### ISSUE THREAD

**Issue by KarlDunkerley** [DoESLiverpool/somebody-should#846]
Once the Laser Maintenance Crew (or whatever it is called) is fully established, could we look at designing and building a passive water cooling system?

Having recently bought my own small laser, I noticed the water tank for the cooling system was getting hot after a few hours. I didn't want to use a chiller even though I have one as they are noisy and use a lot of energy. They also pump the heat into my stuffy summer working environment.

The water tank and separate pump I was using had 10L of de-ionised water so as a first step I added another 5L. The temperature dropped considerably to lukwarm. Since then, the temperature has remained reliably low. This led me to wonder what would happen if we did the same to Gerald, Sophia and Harry the Humungous.

If this idea of using a larger mass of water works, this should mean that;

Noise levels will be reduced (possibly significantly)
Machines can be placed anywhere in the Tapestry more flexibly
Future machines will be easier to integrate into the 
We avoid heat being pumped into the working environment
We won't need to buy another expensive CW-5200 chiller if existing one fails
Reduce energy consumption
Add cleaning and antifreeze to improve tube life

A CW-5200 has a 9L tank. We could try a 50-60L plastic water tank and submersible pump and even up it later. De-ionised water is only £3.50 for 5L at Halfords.

**Comment by johnmckerrell** [comment]
We originally had a bin full of water and submersible pump. This got complicated with much monitoring of temperatures as we continually had problems with high temperatures. I think we'd much prefer to stick with the coolers that we've got as they're much more reliable.
