### ISSUE TITLE
The flat roof upstairs isn't completely watertight...

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#847]
We've had the first heavy rain in ages, and some of it found its way into the entranceway to the kitchen.  Buckets have been deployed upstairs to catch it there instead, and Jason is on his way over to address it.

**Comment by amcewen** [comment]
Flood counter reset.  I'll leave this open until we hear that the roof is fixed.  I guess it counts as a snag for #700...

**Comment by johnmckerrell** [comment]
A fix has now been made and our buckets returned, there may be future work needed but for now I'll close this.
