### ISSUE TITLE
Lift door not closing properly on First Floor

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#848]
I noticed a couple of times in the last few days that the lift wasn’t working properly. One day I could not call the lift from the ground floor.

Yesterday though, I noticed that the door wasn’t closing properly on the first floor when I was in the lift. There is no handle on this door inside the lift, so I had to close the lift door from outside then call the lift from the ground floor. So this also explains the calling issue from other floors.

Obviously this is an issue for accessibility and potentially a safety issue if a disabled person gets to the first floor but can’t get down again.

**Comment by magman2112** [comment]
As luck would have it, the lift worked perfectly this evening, so we may have to describe this issue as intermittent.

**Comment by amcewen** [comment]
I'm not aware of anyone having problems with the lift recently, so going to mark it as closed.  We can always reopen it if it recurs.
