### ISSUE TITLE
Blinds for Dinky.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#849]
There are three sets of blinds that I believe came from the Gostins building that may be usable in Dinky. These blinds will need to be measured and likely cut down to fit, plus we need to find the mounting hardware to fit them (there is some blinds mounting brackets on the shelves by the toilets, need to confirm that these are the right ones).

**Comment by johnmckerrell** [comment]
For the record, I asked about lengthening them but was told that the stitching wouldn't hold, it would be better to just not have them all the way down (which in Dinky might be reasonable?)

**Comment by amcewen** [comment]
Ben is looking after sourcing new blinds for Dinky, after he and @magman2112 installed the old ones and some tissue-paper round the edges as a temporary measure last week.

**Comment by magman2112** [comment]
Ben and I have measured for the new blinds and Ben will order these tomorrow. With a bit of luck, we should have these fitted on Thursday.

**Comment by magman2112** [comment]
Ben picked up the new blinds this afternoon and they are now fitted.

So closing this issue.
