### ISSUE TITLE
Need to try a 512MB Pi on doorbot1

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#85]
We might be able to improve doorbot 1's performance by simply swapping out the Pi that's in it. Should be as simple as that as the MAC address will come from the Wi-Fi card and obviously the OS is on an SD.

**Comment by amcewen** [comment]
An alternative/additional step to improve doorbot1's reliability might be to install KWeb3, which is a Webkit-based browser written specifically for the Pi and can run without a window manager.

I used it to good effect on a recent install in FACT.  From my install notes...

// Install the minimal browser KWeb3
wget http://steinerdatenbank.de/software/kweb-1.6.3.tar.gz
tar -xzf kweb-1.6.3.tar.gz
cd kweb-1.6.3
./debinstall

Then add this to /etc/rc.local to have it run automatically:
su -l pi -c "xinit ./web_browser"

With the following as the contents of the web_browser script, and the page to display stored as /home/pi/homepage.html:
#!/bin/sh
export DISPLAY=:0
xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device

kweb3 -CZNDJK+-zbhrqfpoklgtjneduwxyavcsmi:#=?!

**Comment by johnmckerrell** [comment]
Just a quick note that the environment on doorbot1 (and 2) is a bit old and crap so installing new software may fail, if anyone gets interested in upgrading the OS they should look at the following scripts:

https://github.com/DoESLiverpool/doorbot-setup

That does work for setting up a basic doorbot (doorbot3 is in fact built from it) but should have the browser bits added to be complete (and enable it to setup a doorbot1).

**Comment by amcewen** [comment]
This was fixed as part of the fix to #164, so is now running on a Rev 2 Pi, and also using KWeb3 as the browser, so we can see how that does for memory usage.

However, I stole the Raspberry Pi Model B Rev 2 from @johnmckerrell's desk, so DoES needs to buy him a replacement (or a Pi 2)
