### ISSUE TITLE
Get a couple more USB mice

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#852]
We seem to be at least one USB mouse down for the various workshop computers at the moment, and maybe two...

Does anyone have one knocking around that they no longer need?  Otherwise we can buy a couple more sometime...

**Comment by chris-does** [comment]
@amcewen If this is still required, I have USB mice that I can provide.

Please just let me know where you would like them deposited.

**Comment by DoESsean** [comment]
Great, thanks @chris-does!

I think we need to go over what it is we actually need again - I'm fairly sure we won't have been totally mouseless for the last year, so some workaround must have been found - but we do have peripheral storage where we could keep them.

**Comment by amcewen** [comment]
Given that the vinyl cutter's mouse has been (temporarily) stolen right now, it seems that having one or two more mice would mean we can have a couple of spares that people can use if they want to borrow one for their laptop while they're in.

So yes, one or two more would be ace!

**Comment by chris-does** [comment]
Grand; I shall bring some with me when I am next in (likely Thursday 25th if not before).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chris-does** [comment]
Provided 5 [Logitech B100](https://www.logitech.com/en-gb/product/b100-optical-usb-mouse-business) wired USB mice

![DoES Peripherals Box](https://i.imgur.com/1FWZvLq.jpg)

5 [Logitech B100](https://www.logitech.com/en-gb/product/b100-optical-usb-mouse-business) wired USB mice have been deposited into the “DoES Peripherals” translucent plastic box (located at floor level in the corner between the soldering station and the dividing wall with Dinky).

Model Number:
B100 910-00357

Serial Numbers:
1920HS095AT9
1920HS094BM9
1920HS095L39
1920HS095AQ9
1920HS094BS9

![1920HS095AT9](https://i.imgur.com/Dovvumj.jpg)
![1920HS094BM9](https://i.imgur.com/DmUPjs4.jpg)
![1920HS095L39](https://i.imgur.com/ZHYI8Y4.jpg)
![1920HS095AQ9](https://i.imgur.com/ZZ6Q7CY.jpg)
![1920HS094BS9](https://i.imgur.com/7aETDPU.jpg)


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
