### ISSUE TITLE
Complete the dust extraction system for the CNC mill/router

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#855]
The Kinetic-NC mill is set up and working but it currently throws a lot of dust.

I have provided a cyclone-separator that has been tested and works wonders but a few more parts are required to make a fully effective system:

A good sturdy plastic or metal bin, must be round and have either a flat edge around the top, or have a sturdy enough top to have the cyclone mounted on it.

One, or possibly two more vacuum cleaner hoses - there's a really tightly coiled one that will work well to couple to the dust-box that surrounds the cutter, but it will not reach all the way to the cyclone inlet.

A better source of suction would also be great - the little green vacuum cleaner has a tiny dust bag  (and it has been reused a LOT of times) and it provides only limited suction, even on full power.

The hose and a better bin (a bucket is currently in use and even moderate suction collapses it) will get a working extraction, better vacuum cleaner as well would do the job properly.

**Comment by DoESsean** [comment]
Is there anything we can do to expedite this @Sean-anotherone? Or have you made some progress?

**Comment by JackiePease** [comment]
I  spoke to @Sean-anotherone. The cyclone worked well but the plastic bucket  wasn't up to the job (as expected, it was a prototype). We need to buy a metal bucket that will fit under the CNC bench. We need someone to spec and order this.

**Comment by plastictactics** [comment]
Yangshuo has updated this with a sturdier bucket - seems to work well.

The suction is not quite enough to get aluminium chips from the valleys in the extruded aluminium profile that makes up the bed of the CNC.

Is the grand plan to connect this to the router to extract dust at the point of cutting?

**Comment by amcewen** [comment]
The sturdier bucket was better, but the gaffer tape seal between the bucket and the lid is hard to keep sealed, particularly whenever the bucket gets emptied.

It feels like we should get something like [this metal bucket](https://www.ebay.co.uk/itm/401777622655?hash=item5d8bcffe7f:g:MY0AAOSwQTdc8UsQ) and transfer the cyclone to the lid of that.

There is a shoe to fit to the spindle to collect things at the point of cutting, and (I think) hoses to attach it to the cyclone, but I haven't seen anyone use it—not totally sure why.

**Comment by amcewen** [comment]
I've ordered one of the metal buckets.  Should be here at the end of the week.

**Comment by Sean-anotherone** [comment]
A length of pipe lagging would make a good gasket.


    On Wednesday, 16 February 2022, 11:51:47 GMT, Adrian McEwen ***@***.***> wrote:  
 
 


I've ordered one of the metal buckets. Should be here at the end of the week.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by amcewen** [comment]
The bucket has arrived.  I've left it in the CNC room next to the cyclone; we need to transfer that across to the lid.

There is a gasket on the lid already—not sure how good a seal it'll make, but lid itself clamps on pretty tight so it might be good enough.

**Comment by huffeec** [comment]
I made a start on transferring the cyclone to the metal bin today. There's now a suitable sized hole in the lid of the new bin.

The next step is to cut down the wooden lid to fit the new bin and glue/seal it in place

I think this is preferable to unpicking the glue between the lid and cyclone and re gluing to the metal lid. Either could give a good seal.

The other job that needs doing for this is some 3d printed crevice tools to help cleaning the bed.

**Comment by huffeec** [comment]
The extraction is complete. I've opened a new issues for the nozzle. (#1678)
