### ISSUE TITLE
Flow sensor on Gerald appears to be dripping

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#86]
Which leads to a continuous drip from the bottom of the laser. There's a bucket under that drip now and I've taped up some of the electronics to make sure they don't touch the water. I'm happy enough that it's not a major problem but we should definitely fix before all the water drips away!

**Comment by cheapjack** [comment]
Eek! Worth noting that one side panel of the laser has the motherboard inside; Id imagine water leaking into this when powered could be fatal; to the machine if no-one else. I did see some water on the floor other day but assumed it was from adding ice to the coolant bin. 

I really think we need to power down and investigate leak before we let anyone else on ;( just a bit worried on this effecting the power thats running through the machine and at worse the potential for electrocution! I'm unsure how exactly the laser power is earthed and with so many plugs underneath I think we need to get our heads together and satisfy ourselves that there is no danger to people using it. 
I guess if it would have been a possibility then it would have already happened to be fair; and John I do trust your judgement but dont want you to have the responsibility! I can see 2 people booked on it tomorrow so think we need to make a call or check up on it before they power up. I know the water is seperated from the tube electrics somehow but Im not 100% on how that works. Sorry to throw in a paranoid spanner but reckon we put it out of action until Patrick has a look!

**Comment by johnmckerrell** [comment]
It's a very small amount of water and the box that probably houses the motherboard is raised slightly so I'm reasonably confident that it's not a problem.

**Comment by johnmckerrell** [comment]
I'm going to try putting a cable tie on the tube to stop the leak.

**Comment by cheapjack** [comment]
Good idea, sounds fine in that case :)

**Comment by johnmckerrell** [comment]
Cable tie seems to have done the trick.
