### ISSUE TITLE
Hold a book sale for DoES

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#860]
I'm thinking books on tables for a pound each or something for two weeks. Then 50p, then free and finally we get some book reseller to pick up what remains?

**Comment by DoESsean** [comment]
Is this of books that DoES already holds? Or are we looking at getting
people to bring in some of their own stuff that they no longer want?

I'd suggest not bothering with a sliding payment scale, it could just lead
to things hanging around. How's about we just have a 'pay what you want'
honesty box?

**Comment by ajlennon** [comment]
Bringing in.

I'm firmly of the opinion that people don't value free stuff. I think it should be a minimum of £1 per book for a start.

**Comment by DoESsean** [comment]
Given the amount of times all @ajlennon's books sat around, it seems like, although it should be a good idea, it didn't really take off. So I'll close this.
