### ISSUE TITLE
Update our listing on coworker.com

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#867]
Needs new address, photos, etc. I have an account on my john@does address but it's not linked to the space so I can't edit. I tried various email addresses on the forgotten password link like hello@ and the one that worked was sean@ so @DoESsean may be the one that can edit, I've also emailed them though to see if I can get added too (and just in case Seán isn't anyway).

**Comment by johnmckerrell** [comment]
I found Seán's password and have made some simple updates but we should still update the photos and maybe someone can take a look and suggest other changes too. I'd also suggest Coworker.com could add a few amenities but I'll wait until someone else has had a look so we can give a full list.

I've also requested that I be made an admin but they haven't done that yet.

**Comment by johnmckerrell** [comment]
I ended up uploading some photos yesterday but maybe Seán can do a quick review today and push any suggestions back to Coworker.com before closing this out.

**Comment by DoESsean** [comment]
Pretty much all of what you've written seems fine to me, just done some
very minor tweaks on a couple of bits. I guess this means that the profile
is now all up to date.

**Comment by johnmckerrell** [comment]
Cool, I've pinged the changes to Coworker.com so I'll close this.
