### ISSUE TITLE
Create Mailbox for Paid Work

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#868]
@paulfurley and @Helen-8 have reported higher than usual instances of people ringing up asking for work to be done rather than to do it themselves, and it's been suggested that we set up a mailbox that people can access where these requests can be sent.

We have various people in the community who will be able to take on paid work, and it seems daft to end up directing people who have come to DoES for these services elsewhere.

As an initial suggestion, I would ask Jade, Amy, John/Laura Cain and Ste if they would like to be involved, as they're the people I see using the cutters most, although I'm sure there will be plenty more that I don't know about.

I assume @amcewen or @johnmckerrell will need to create the mailbox?

**Comment by MatthewCroughan** [comment]
I'd love to be involved, delegate as much work as you can to me!

**Comment by DoESsean** [comment]
As of yet, there's been no movement on this. Although it seems like the calls for paid work have dried up a bit, I still think it would be worth having this option in place.

@johnmckerrell do we have enough free DoES mailboxes to create this?

**Comment by johnmckerrell** [comment]
Feels like it probably wouldn’t need a mailbox just an alias, you’d need to make it clear to people using it that it goes out to multiple people. I’ve been sending people to the google group recently. Granted maybe not everyone’s on there but perhaps they should be!

**Comment by DoESsean** [comment]
I'm the same, I always point people to the Google Group but I really don't
know if the right people would be seeing it.
