### ISSUE TITLE
Be Better About Laser Inductions

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#869]
I know that's a terrible and vague heading.

We currently have one available slot for laser induction bookings, and it's two weeks away. It may be worth finding out who is able and willing to give these inductions, and get them to commit, if possible, to a certain time each week - even if it's only a couple of hours, and even if we only have one block per week, it would be very useful to be able to say to people, 'Laser inductions take place on x'.

When we had regular Thursday morning inductions, they were bringing in reasonably good money, all of which has been lost. I do understand that it's difficult to ask so much of people, but I don't think it hurts to ask, so long as everyone knows they are more than welcome to say no.

**Comment by ajlennon** [comment]
Is there a written induction procedure covering everything that needs to be conveyed?

**Comment by DoESsean** [comment]
There is not (at least not one that I'm aware of).

**Comment by johnmckerrell** [comment]
There is the beginnings of one here:

https://github.com/DoESLiverpool/wiki/wiki/LaserCutterTraining

**Comment by ajlennon** [comment]
Can I suggest than an expert inductor creates an induction document because then people like me who could probably induct but aren’t sure they are clear on what they need to cover could think about committing some time?

**Comment by ajlennon** [comment]
I can't commit to regular times however I may be able to commit some time in advance.

- how do I get on the list of "accredited inductors" ?

- how to I make organisers aware that I can provide induction for slots on certain times/dates, say a week in advance?

**Comment by johnmckerrell** [comment]
The main thing is that the slots are added to a shared calendar that powers the youcanbook.me site. I guess if you’re available on an ad-hoc basis we might not put that in the calendar, but it might give us some leeway to say “contact us for further availability”. The way to get on the “list” is basically to say you’re available, which you mostly have :-)

**Comment by jackie1050** [comment]
Thanks Alex - That's great. You can tell me what times you'll be  available and I'll add them to the laser calendar (I need to add some times back in for myself, now that the move stuff is mainly over).

I will be writing an induction procedure this weekend, as it came up at the recent Directors'meeting, so it would be great if you could help me go through that.

If anyone else has any time available to do inductions could you get in touch too - obs we are shot of people as Chris hasn't been available recently.

**Comment by ajlennon** [comment]
Happy to @jackie1050 just give me a shout

**Comment by jackie1050** [comment]
"short of people"!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MatthewCroughan** [comment]
I'm more than happy to help people out with the laser, have been doing so for the past two weeks anyway. Whether I'm ready enough to induct people is up to one of you. Happy to take on more and more responsibilities, so let me know when I'm needed.

**Comment by jackie1050** [comment]
Thanks Matt - that's really useful. It would be great if you could start helping out with some of the inductions on Maker nights, and then we can see if there's any other times you're free.

Speak to you this week.

Jackie


On 5 Aug 2018 21:41, MatthewCroughan <notifications@github.com> wrote:

I'm more than happy to help people out with the laser, have been doing so for the past two weeks anyway. Whether I'm ready enough to induct people is up to one of you. Happy to take on more and more responsibilities, so let me know when I'm needed.

**Comment by DoESsean** [comment]
I've contacted five people who are currently either involved with, or have expressed an interest in, delivering inductions. The aim is to have a much more regular schedule of paid induction slots available.

**Comment by jackie1050** [comment]
Hi Seán

This is already under discussion between Adrian, Darran and me. There are regular induction slots on Wednesdays from 17:00 and Saturdays at 10:00 (not this Saturday as I've just cancelled it) that you could mention.

Regards

Jackie

On 25 Jul 2019 15:54, Seán Gleeson <notifications@github.com> wrote:

I've contacted five people who are currently either involved with, or have expressed an interest in, delivering inductions. The aim is to have a much more regular schedule of paid induction slots available.

**Comment by DoESsean** [comment]
Since we now have two regular slots, and a group that is happy to step in if none of those are suitable and work something out, I'm closing this issue.
