### ISSUE TITLE
One of Gerald's fans has failed

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#87]
The big boxy fan seems to have stopped working today or become clogged up and so was not performing any useful function. We replumbed the pipes so that only the smaller fan was in action and that seemed to work better.

**Comment by cheapjack** [comment]
Probably needs a hoover around the big boxy fan's filter usually sorts this out.

**Comment by johnmckerrell** [comment]
Ok, in which case we probably need a procedure where this is a regularly performed job every Monday morning or something like that.

**Comment by DefProc** [comment]
As a more permanent solution, we should look at replacing the fans with a better one. The new fan for Sophia will give us some idea of what we need for replacement's specification.

**Comment by amcewen** [comment]
Replacement activity raised as issue #106
