### ISSUE TITLE
Doorbot5 isn't responding to tags

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#871]
Doorbot5 (the shutter) isn't responding to tags at the minute.  The Pi is up fine, and there's power to the RFID reader, but no cards are being detected.  Luckily I was first in today and had my key with me to open the shutter.

**Comment by amcewen** [comment]
Hmm, seems to be a dodgy connection on the RFID reader.  Wiggling the leads I got it to start responding for a few tap ins, but none since.  Currently working up the courage to re-crimp all the connectors on it...

**Comment by ajlennon** [comment]
We've recrimped and fixed it up! Plus we re-situated the sensor so I can open the shutter with my hand! Hurray!

https://www.instagram.com/p/BmBR7VrFl4N/?utm_source=ig_twitter_share&igshid=1gvge40n80l9m
