### ISSUE TITLE
Print replacement top head part for Prints Adam

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#872]
The material may have worn away round the edge of the collet, as the collet is jumping out midway through printing. See #634 for file - I have started a print now.

**Comment by magman2112** [comment]
After clearing the nozzles on Felicity, the new part was successfully printed for Prints Adam. The disassembly and re-assembly of the printhead on prints Adam was quite involved, as a number of cables needed to fit through the new part, but this has now been successfully fitted and appears to be working OK.
