### ISSUE TITLE
Uninstall Lasercut 6 from Gerald's PC

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#875]
Gerald's PC currently has three versions of the LaserCut software installed - versions 5.0, 5.3 and 6.1.

Version 5.0 is the right one.  We should uninstall versions 6.1 and 5.3 (we could /maybe/ leave 5.3 on there as Sophia uses it, but should make it harder to open accidentally - at present it's the only one that shows up on the Start menu...)

**Comment by magman2112** [comment]
Matt owned up to installing this software, he has now removed it. Also, Matt made the Start Menu entry and desktop icons to default to Version 5.0 on Gerald's PC. Version 5.3 is still installed but is not on the Start Menu.
