### ISSUE TITLE
Vinyl cut the building number for over the door

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#876]
Jason has agreed to us doing vinyl cut numbering to go on the box above the shutter on the main door. White would be best. I need to confirm the font, he has a standard Tapestry font that's a nice open source one but I can't recall it right now. We'll work out a design and ideally mock it up on the attached photo, confirm with Jason and then get it cut out.

I think it would also help if we put the building number on the actual mailbox too although this can be done easily with a label printer. Both tasks should be done before this issue is complete.

This should help with #865 

![2018-08-09 11 45 45](https://user-images.githubusercontent.com/27243/43900772-b45dd3fc-9bdd-11e8-8d67-5983aaad3a7e.jpg)

**Comment by johnmckerrell** [comment]
The font is BEBAS NEUE. We need measurements next and to confirm if there's any white vinyl.

**Comment by johnmckerrell** [comment]
300mm x 1320mm, I have a design agreed with Jason so I just need to get that fitted to these dimensions then actually cut it. We do have some (off) white vinyl, don't think it's enough and actual white would of course be nicer!

**Comment by DoESsean** [comment]
Anyone fancy cutting this?

**Comment by johnmckerrell** [comment]
This is out of date now, Jason has sorted it.
