### ISSUE TITLE
Consider pulleys for bike storage

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#877]
I joked that we should try a pulley for storing bikes but having considered it more I think it could work. A bike hanging from the ceiling should still give plenty of clearance for someone walking below. This one from Halfords is what got me thinking about it but others may be available:

https://www.halfords.com/cycling/bike-maintenance/bike-storage-solutions/mottez-bike-lift-pulley-system

We are supposed to be getting storage outside but I'm not sure how that will work with the exit-only door that's there now and there's currently no timeline for it going in anyway.

I'm not sure where the best place would be, main room seems the obvious place as everyone has access, in the alcove would be out of the way, above the fire exit would also be out of the way so long as it didn't cause issues with emergency exiting.

**Comment by mdunschen** [comment]
The problem with storing the bikes inside on the first floor is carrying
them up the steep stairs. I dread carrying my bike plus pannier up or down,
and the space in front of the double door between stairs and door is very
limited and it is quite awkward to open the door when leaving, or hold them
open whilst shouldering your bike when arriving. There is an accident
waiting to happen with bikes being carried on the stairs, in my view.

I would propose having as an alternative on-street parking in a secure bike
cage: take away one or two parking spaces from the metered parking outside
and put a hangar style lockable bike cage there, like this one in London
Southwark:
https://consultations.southwark.gov.uk/environment-leisure/cycle-hangars-2/consult_view/


This is something the council would have to do, and I am not sure if there
is precedence anywhere in Liverpool. But hey, we welcome cyclists in the
Fabric District and I remember seeing a tweet about now having a National
Cycle Route going through the area, so it would be a great addition.

Martin

**Comment by jackie1050** [comment]
I agree that it's quite difficult to get bikes up and down the stairs (and time consuming to use the lift).

**Comment by johnmckerrell** [comment]
Yeah that’s fair enough, and the doors can be particularly tricky. The hack with the lift, at least on the way in, is to put the bike in then call it from above so you don’t need to spend your time in the lift! On the way out that’s less useful. I agree it would be good if we could persuade the council to do something, as usual it would be tricky to gauge a timeline but certainly something to raise with the Fabric district group.

**Comment by johnmckerrell** [comment]
Martin has emailed some councillors and they've been very responsive so far.

I talked to Jason and he's arranged for us to have 5 extra fobs for the big shutter to the courtyard, can anyone recommend some bike storage we could put in there temporarily?

**Comment by ajlennon** [comment]
Can't we just screw those things on the wall that used to be in the Gostins building hallway?

**Comment by johnmckerrell** [comment]
I for one would prefer something more weather proof. 

--

**Comment by ajlennon** [comment]
As a short term measure it would surely be a sensible option?

**Comment by ajlennon** [comment]
I can't recall the layout - what's it like underneath the metal stairs? Do they keep the rain off the space underneath?

**Comment by goatchurchprime** [comment]
Totally need to get the pulley system for a bike, particularly if it has Martin's POV setup (#881), we were supposed to put on a wheel by now, in case we've forgotten.  

It could be a good looking bike pimped out with all the tech detailed in the intro with all the tech detailed in the intro section of https://en.wikipedia.org/wiki/Virtual_Light and have it for hire.

**Comment by DoESsean** [comment]
I'm closing this as there seems to be no way that we're installing pulleys for bike storage. If someone wants to reopen it and change the title to reflect something more likely, feel free.
