### ISSUE TITLE
Felicity not working

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#878]
I had to dismantle the input feed mechanism due to a filament jam (while trying to feed through filament because previous reel had run out). This has resulted in several issues:

- there is a small metal collet which was found afterwards and could be part of the Ultimaker. Need to find out whether it is or not

- the drive belt on the left hand side (when looking from the front) is loose. This could be because 2 screws on the top of the printer on that side were undone while trying to find out how to remove the side panel

- the metal panel covering the motors on the left hand side (when looking from the front) is loose. I thought it was like that to start off with, but that isn't the case with Prints Adam, so maybe not.

- some of the M3 square nuts which hold the side panels on to the dibond top and bottom panels are missing

I have found an assembly manual here: https://github.com/Ultimaker/Ultimaker2/blob/master/um2%20assembly%20manual%20V1.1%20_english.pdf

There is a printed copy on the shelf under the printers.

**Comment by jackie1050** [comment]
I have ordered some M3 square nuts. Their estimated delivery time is Sat, 11 Aug–Mon, 13 Aug

**Comment by MatthewCroughan** [comment]
Helped fix with Jackie, all done, with a bit of double sided tape. It's true, it fixes everything! @amcewen 

How to fix an ultimaker:
![image](https://user-images.githubusercontent.com/26458780/44005135-2ffd2cc6-9e66-11e8-8645-7d7688be5f88.png)
