### ISSUE TITLE
Fix the accessible toilet's occupancy indicator

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#880]
In trying to fix the occupancy indicator to show correctly, whereas before the indicator wasn't always moving, I appear to have glued it all together and it won't now move at all. I've soaked in acetone but it hasn't freed yet.

**Comment by ajlennon** [comment]
fwiw I've found the problem to be you have to pull the door closed hard for the lock to fit, and I suspected that people not doing this were instead forcing the lock/indicator and damaging it. I find it difficult to close so I imagine somebody with movement impairment would have much more trouble.

I was wondering what's wrong with it? Maybe something out of alignment somewhere?

**Comment by Robotorium** [comment]
Oh, yeah actually. Really sorry, it absolutely didn't occur to me to say.
It's really hard to close from a chair, definitely, and I can see how that
might have damaged the lock over time.

Sorry. I'm really used to issues with the accessible loos not being taken
seriously, so it didn't even come into my head that I should say anything.

Op di 14 aug. 2018 09:54 schreef Alex Lennon <notifications@github.com>:

**Comment by johnmckerrell** [comment]
@magman2112 worked out the door appears to have warped at some point. Quite possibly this (or even the pulling the door to lock it, which I do myself) has damaged the lock. Obviously the important bit here is that the accessible loo door is a pain to lock but I'm not sure we have a separate issue for that, if not then we should!

**Comment by ajlennon** [comment]
Let me know if I can help - I'd been meaning to mention it too but with everything else it went out of my head
