### ISSUE TITLE
Wire up Martin's Persistence of vision tech on a bike wheel 

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#881]
Martin soldered together a very bulky kit of red LEDs years ago onto three spokes of a bike wheel, which is now gathering dust in a box somewhere.  

We should get it together and have it out mounted on a wall so you can spin it like a prayer wheel when you want to know what it says.  

It it doesn't look good, we can always put it away again.  But it's a shame to have this already built and functioning thing that is the same sort of thing as the laser galvos not looked at and wasted.

**Comment by zarino** [comment]
@goatchurchprime it’d be fun to have this mounted in the event space, or the hallway outside, so visitors could spin it. Maybe mounted with a gear, chain, and crank below, so you can get the wheel spinning nice and fast? Maybe turning the crank could generate enough power to run the lights and whatever microprocessor is controlling it?

**Comment by mdunschen** [comment]
I brought the spokepov "persistence of vision" boards in, they are on my desk, together with the USB programming dongle: a standard USB A/B cable is needed and a small neodymium magnet to trigger the hall sensors. We will also need 6 AA batteries, and you need to install some SW from adafruit on a computer to change the images from https://sourceforge.net/projects/spokepov/ Remember you can upload up to 4 different images, so very simple animations are possible. Hall sensors and on/off switches are on the opposite side to the battery mounts. To fix to a bicycle wheel best use zip ties.

Feel free to pick up from my desk.

**Comment by goatchurchprime** [comment]
I've moved them to my desk and found some batteries for them.  I'll bring in a spare front wheel for it tomorrow that has a magnet.  

There's no switch, so we could use a little inset of hard plastic to push behind the AA battery terminals to turn it off (and save losing the batteries).

I'd like to be able to mount it like, on a wall, so we can spin it.  I hope that it's a normal enough wheel that folks can borrow it and take it for a spin round town with the DoES logo flashing, for example.

**Comment by ajlennon** [comment]
#SpokePOV looks amazing

**Comment by goatchurchprime** [comment]
Those must be long shutter speed.  Less impressive in real life!

It's on the wall above the knittick with a spoke magnet on the pipe behind.  You have to hold the axle just right so it's close enough to the hall sensors behind the outermost IC

**Comment by goatchurchprime** [comment]
It's been mounted for a while on @amcewen's spoke fixing frame
