### ISSUE TITLE
Lock on our more accessible toilet door is quite hard to use

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#883]
We believe it's due to the door warping. @magman2112 has tried filing the catch down but that hasn't sorted it out yet.

**Comment by jackie1050** [comment]
Especially an issue for visitors

**Comment by ajlennon** [comment]
Have we got a tool for this?

**Comment by ajlennon** [comment]
So I had a go and ended up moving the hole for the lock rather than sanding the door. Seems much better.   A little still but not, I think, a problem.

@Robotorium can you test out and let me know if it suffices?

**Comment by johnmckerrell** [comment]
@magman2112 had another go at this yesterday, planing the edge and tweaking Alex's job and it's pretty much silky smooth now. He replaced the entire mechanism with the one I'd got too so it's no longer wobbly.
