### ISSUE TITLE
Update 2D printers page on the wiki

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#884]
https://github.com/DoESLiverpool/wiki/wiki/OfficePrinters

We now have a quite multi-functional printer in Room 29 which appears to be on the Wi-Fi, I'm not sure if that's the one mentioned on the wiki page. Also the B&W laser printer is active. We haven't found the power lead for the colour one. Probably worth mentioning sublimation printer if only to say "this isn't for printing documents" and linking to its own page.

**Comment by magman2112** [comment]
@ajlennon updated this page recently and I added some brief comments on the Dye-Sub printer. So closing this issue now.
