### ISSUE TITLE
Have two spare 1U machines for the server room, compiling, network storage, livestreaming, hosting etc.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#886]
I have 2 spare hp dl server that has been sitting in my room for quite some time, now that I'm getting settled in at DoES, I'd like to put it to some good use as a compiler, network storage and massive amounts of virtualisation. 

2x Proliant DL385P servers, 16 threads, and capacity for 6 disks each.

I volunteer to do all necessary management or configuration of the machine, tend to people's issues, install required things, etc. I intend to install Proxmox in both, then anybody at DoES can provision a virtual machine for their use case.

We could offer a few services with these machines, and make a bit of money for the space if there were any interest at all.

We need servers like these to manage the suggested livestreaming infrastructure, lots of cores encode footage. @ajlennon has the brilliant idea of creating a federated maker-space livestreaming setup, wherein we use rtmp servers to create an always-on livestream that promotes the existence and visibility of DoES and other maker spaces in the UK. This is a big opportunity to get modern and create a much larger online presence.

This is only one possible application we can commit to as a space, over time. With the ability to spin up as many virtual machines as we like (within reason), we can do a lot more than livestreaming.

**Comment by Sean-anotherone** [comment]
I am not a cloud user so have no idea of hoe DoES functions without a NAS - a must-have in my book.  Rather than freenas I'd suggest a basic OS running both xampp and NAS so it can serve pages & files externally, too.

**Comment by MatthewCroughan** [comment]
@Sean-anotherone I couldn't stomach using a solemn xampp instance if given the option to use freenas, just because it makes zfs arrays easy. ZFS has proven to be arguably **the** best filesystem in the industry in terms of future expandability, resilience and features. For example, files are just automatically compressed and disk fragmentation is an automated process, both mean network throughput and on-disk size is maximised. Not to mention all of the other features freenas offers, even if they are superfluous from your point of view. 

Keep in mind that there's no reason we can't just run a single xammp server on a separate virtual machine for your purposes anyway. My idea was to put a [proxmox](https://www.proxmox.com/en/) installation on the server and give people user accounts on the hypervisor they can spin up virtual machines for their use case. Rather than having to use AWS for things, people could just use this server locally at DoES, within reason. We could do up to around 16 VMs comfortably, if each one were given two CPU cores each. It'd be such a waste to not turn this into a hypervisor for multiple virtual machines.

**Comment by ajlennon** [comment]
Sounds a great idea to me and fits with #927

**Comment by DoESsean** [comment]
Did @MatthewCroughan do anything with this? I know he was playing with a load of computers at some point, but I have absolutely no idea whether any of it was connected to this or, if we're being really honest, what most of 'this' is.

**Comment by MatthewCroughan** [comment]
@DoESsean They're still available, and would be great resources for giving anyone and everyone computing resources that were local if they needed them. For example, in the case of @ajlennon working on #933, this would have provided him with a local method of setting this up, rather than having to buy resources from Hetzner. We don't need both machines I'm offering, but we do have one locally in the Free Stuff pile waiting to be utilised if were able to throw it in the networking room.

Any thoughts @johnmckerrell ?

**Comment by MatthewCroughan** [comment]
No longer available, I've managed to get rid of both of them :)
