### ISSUE TITLE
Clean and oil sewing machine

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#887]
It's working ok at the moment, so not urgent, but Restart's wiki suggests that a well used sewing machine might need to be oiled several times a year (https://wiki.restarters.net/Sewing_machines).

There are generic instructions on the Restart wiki, plus some other useful info.

Needs specific oil for sewing machines.

**Comment by DoESsean** [comment]
I'm going to assume that the sewing club have made sure the machine is in good condition, so I'll close this. If anyone knows otherwise, please feel free to reopen.

**Comment by jackie1050** [comment]
This isn't the responsibility of the sewing club - they bring their own sewing machines.
It hasn't been done (the machine is still working but, like others, would benefit from some preventative maintenance).

**Comment by JackiePease** [comment]
Cathy has oiled Heidi and Caroline (Ben will need fixing first) using the sewing machine oil from the solvent cupboard. This needs doing approx. once a year
