### ISSUE TITLE
Gerald doesn't detect his datum point

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#889]
While I was doing a laser induction this morning, I tried to datum Gerald and he didn't stop on the right-hand side (until I turned power off...).

I don't think people use datum all that often, but it'd be good to fix.

**Comment by magman2112** [comment]
When testing Gerald with @Thingomy, we noticed that both of the sensors on the X and Y axis are not working. We didn’t have time to investigate this at the time, but this is looking to be either an electrical or sensor programming issue.

**Comment by DoESsean** [comment]
Has Gerald sorted himself out? Seems to be ongoing issues with him, so I'm not sure whether this can be closed and it's something else that is the problem these days!

**Comment by magman2112** [comment]
No, this is still an issue. I would like to keep this open as a separate issue as it is one of the issues that will get covered by a major overhaul of Gerald, once we get Morris working.

**Comment by magman2112** [comment]
Closing this issue as Gerald has a new controller, as in #1642, which no longer has a Datum control. There is a homing command with the new software which does the same thing as a Datum, which is now working with the new controller.
