### ISSUE TITLE
Double check taping of power-brick for webcams

### ISSUE THREAD

**Issue by osfameron** [DoESLiverpool/somebody-should#89]
These had fallen off and were trailing on floor this morning.  I've taped to side of door, but not sure that's right -- looking again, looks like it might have been taped *above* e.g. next to the webcams themselves?

**Comment by johnmckerrell** [comment]
Sounds about right, the tape on the side had come off recently and I guess the weight of the cable then pulled it off above too. We should really clip this on properly.

**Comment by amcewen** [comment]
I've swapped the six-way for a two-way, so we aren't holding so much weight up with gaffer tape.  That doesn't have any screw mounting holes, but I've used lots of fresh gaffer tape.  Not sure if we should leave this open though for someone to effect a better fix...

**Comment by amcewen** [comment]
Well, the two-way seems to have lasted about 6 weeks :-/  We should find a better fix.

**Comment by johnmckerrell** [comment]
Hammered in some cable clips, reckon that'll do the trick.
