### ISSUE TITLE
Test Sony HDV Camera for Live Streaming.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#894]
The Sony HDV Video Camera that was in DoES has a history of poor connections on its DV Port, which is needed to Live stream video. I have taken the camera apart to check on the the connector on this port and there were some poor solder connections that I have re-soldered, but there is still the issue that the connector itself is faulty. 

To test this further we need a mini DVi (4 pin Firewire) to mini DVi connector, to enable us to plug this into Adrians laptop, which I have not been able to find in DoES. Has anyone got one of these cables available that they could bring into DoES so that we can do some testing?

**Comment by amcewen** [comment]
@jackie1050 and I gave this a quick test yesterday but the laptop didn't recognise there being a camera on the other end of the cable when we plugged it in, so I don't think it's fixed :-(

**Comment by magman2112** [comment]
I’ve done a few more tests and have identified that the DVi connector in the camera is damaged, one of the pins has been pushed in so that i5 no longer makes contact.

I have been looking to try and identify a replacement socket without success so far, but will keep digging. I am also going to desolder and take apart the existing socket to see if the bent pin can be repaired, but from previous experience even if I can bend the bent pin back it will be likely to fail again in the future.

**Comment by Thingomy** [comment]
If the search for a spare socket comes up blank, and  the camera is
otherwise a gonner, consider soldering in a cable -- that way it works, but
the cable is permanently attached, better than nothing.

JR

**Comment by magman2112** [comment]
Replacement part ordered. Even though it was ordered on Thursday night with next day delivery, shipping wasn’t notified till Monday evening (I had an order acknowledgment on Friday that I mistook for a complete processing of the order.

The part should be with me on Tuesday.

**Comment by magman2112** [comment]
The new connector arrived today and was installed. The camera was tested in DoES on Tuesday evening and the DVI connector is now working.

Closing this issue.

**Comment by cheapjack** [comment]
Thanks Mike!
