### ISSUE TITLE
The phone system is down

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#895]
The VoIP phones (the one on Sean's desk and the ones in Room 29 and the events space) are all down at the moment.

That means no-one can buzz in from the intercom outside.  We also can't make any outgoing calls on them, or dial in separately - it diverts instantly to a "sorry no one is available to take your call" message.

The Internet itself seems fine in the space, so presumably it's an issue with Andrews and Arnold?

**Comment by amcewen** [comment]
Hmm, can't see any reported issues on [the A&A status page](https://aastatus.net/)

**Comment by amcewen** [comment]
There is a whitelist on the outgoing settings, which was set to our old IP address.  I tried setting that to the new IP and did at one point have the phone ring, but that's not working now :-/  I've turned off the whitelist for now, which does seem to have done the trick.  Will leave this open for a day or so in case we want to try setting the whitelist again.

**Comment by johnmckerrell** [comment]
I've updated the IP to the new one, looking at the AA documentation it does seem this is the correct behaviour:

> IP Lockdown - a VoIP number can be given an IP address to which is only allowed to register (i.e. you can add the IP of your phone, and only that phone will be able to register)

Just a shame it's not clear that this affects incoming as well as outgoing.

https://support.aa.net.uk/VoIP_Security
