### ISSUE TITLE
Need to replace the belt on the x-axis on Gerald

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#899]
Gerald had a small fire earlier in the week.  I replaced part of the air-assist tubing as it was melted, and cleaned the lens and mirror.

However, Suzy noticed that the belt was also a bit melted and needs replacing.

**Comment by magman2112** [comment]
Drive belt now replaced. Will likely need re-tensioning after a bit of use, say in a week or so.
