### ISSUE TITLE
Box up Raspberry Pi on the door

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#9]

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by DoESsean** [comment]
This has been sitting here for a few years with no progress made.

As it seems a bit daft to do before we move, and will be part of the fit out process in the new building, I'm closing this issue.
