### ISSUE TITLE
Spare air assist laser cutting tube needs replacing

### ISSUE THREAD

**Issue by 5x5Stuido** [DoESLiverpool/somebody-should#904]
I was cutting some foam in gerald and it was set alight. It was a small chunk of foam so the fire was only small. Adrian replaced the air assist tube so the spare needs replacing

**Comment by magman2112** [comment]
The air assist tube was replaced with silicone tubing during the Laser Maintenance day on Sunday 9th. This should hopefully be a bit more resilient than the old PVC tubing, but we have also built in a sacrificial end to the air assist tubing should it be damaged in the future.

**Comment by johnmckerrell** [comment]
Do we have spare in stock for the future though? That's what I took this to refer to.

**Comment by magman2112** [comment]
Yes, we have approx 1.5m of spare tubing left over from the upgrade on Sunday, this should be sufficient for about 10 replacements.
