### ISSUE TITLE
Gerald is stalling on the y-axis

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#909]
Related to #287, now that we've worked round it with some tape, the y-axis is consistently stalling when moving in the top-right corner of the bed, and the bottom left (IIRC).

It's cutting nicely elsewhere on the bed, so Suzy managed to get the cutting done that she needed.

The problem area is completely repeatable, so I'll dig out one of the suspect files for testing.

**Comment by magman2112** [comment]
I took out the bearing rail as commented in #287, replaced the missing screw and tightened the existing screw and re-installed everything.

Basic tests of loading a large rectangle for Gerald to test ran with no issues, so I am going to say this issue is closed.
