### ISSUE TITLE
Create status.doesliverpool.com to show status of equipment

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#91]
It would be useful to have a system to notify people of, and provide somewhere to check, the status of any broken equipment.

Given that anything broken would (/should) end up with a ticket here, I'm wondering if we could add a "broken" tag, which marks the offending item as out-of-action.  At a minimum, the status page could be the list of things with the "broken" tag.

A more advanced system would check for additions/removals from the tag and send an email (and tweet?) to the Google Group to let people know which bits of kit aren't available and when they're fixed.

**Comment by DefProc** [comment]
We can use the github issues list directly for this to list any broken equipment, using the broken tag. then any open issues with the "broken" tag will appear in the list from this link:

https://github.com/DoESLiverpool/somebody-should/issues?q=is%3Aopen+is%3Aissue+label%3A%22broken%22

**Comment by madjake45** [comment]
Has now got it's own [repo](https://github.com/DoESLiverpool/status) and is supported by all but the doorbots

**Comment by amcewen** [comment]
DNS set up so http://status.doesliverpool.com is now live :-)
