### ISSUE TITLE
When we get our static IP back, re-enable the whitelist on the phones

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#912]
The power outage this morning caused a knock-on network outage from Baltic.  They've got the network generally back up, but haven't got the static IP address working yet.

So, to get the phones working again, I've disabled the whitelist that only allows connections from our IP address.  Once we've got a static IP, we should re-enable the whitelist.

**Comment by johnmckerrell** [comment]
I've now done this, think we've had the static IP back for a little while now.
