### ISSUE TITLE
Make the big green "exit" button for main door more obvious

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#913]
Lots of visitors seem to have trouble working out how to open the main door (next to the coat stand), when they’re leaving. They tend not to notice the **big green button** behind them and to the left. Some even end up flicking the light switches to their immediate left, assuming those must be the door release!!

Perhaps we could have a sign on the door, showing people how to press the **big green button** to open the door?

**Comment by johnmckerrell** [comment]
Now that Jason's added a "turn lock to exit" sticker, I've bought a "push button to exit" sign and an arrow to make the button more clear. I should've bought two of the "push button" stickers to cover the events room too but we'll see how this one goes and get another.

**Comment by DoESsean** [comment]
Stickers are on the door. Now nobody help anyone for the whole of August and see how they work.
