### ISSUE TITLE
Workshop doorbot isn't booting

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#92]
The workshop doorbot is down at the moment.  A simple turn it off and on again isn't working (the power supply fan comes on, so I think that's probably okay), but no lights on the Raspberry Pi.

The four-way that the security cameras are plugged into had fallen off again, and the speaker hooked into the Pi was dangling by its wire (knocked off by the four-way maybe?).  My guess is that the speaker falling off has pulled a couple of wires out of the Raspberry Pi - there are a couple of loose wires in the block for the GPIO, but I've not investigated further (yet).

**Comment by amcewen** [comment]
Tried powering the Pi from a USB power supply and it looks like it comes up okay, but the RFID reader doesn't work (no red LED when a card is presented, at least)

**Comment by amcewen** [comment]
Wires coming from the RFID reader: green wire is SDA, white is SCL, yellow is Out, blue is In, red is 3V3 and black is ground.  We don't need the blue wire, and might not need the yellow.  

Of the headers to go onto the Pi, there's a two-pin header with the white wire from the RFID and then a 5V supply, which confuses me, as looking at the Pi pinouts in http://elinux.org/RPi_Low-level_peripherals there shouldn't be a 5V and SCL pins next to each other.  There's also currently a loose 3-pin header with only one wire going to it, which is a ground connection.

It'll need further investigation before we get it solved :-/  

I've reconnected the door activating pin, so when the Pi boots (which it will if you use the 5V and ground connections I've found, or the two-pin header in the corner of the perf-board with some jumper wires) you can run the opendoor.sh script to unlock the door.

The Pi is on at the moment - powered with jumper wires from the two-pin header on the perf-board - so you can ssh into it and unlock the door with software if that's easier than getting the key.

**Comment by amcewen** [comment]
I've moved the blue 5V wire from the two-pin header onto the three pin header, and that now powers up the Pi correctly.

I then resoldered the green wire onto the two-pin header, but even when that's connected up the RFID reader still doesn't work.  I'm wondering if I managed to kill that pin on the Pi because I think I might've tried it connected up while it had 5V going to it :-/

Maybe try swapping it with another Pi to see if that fixes it as a next step, but I'm done for the evening I'm afraid.  Pi left powered up, so you can ssh into it and open the door with "sudo ./opendoor.sh"

**Comment by johnmckerrell** [comment]
I've now tried swapping the Pi out for one that belonged to Patrick and was similar vintage (having tried Doorbot 3's Pi, which had problems reading the SD card). It behaves the same as the other Pi so is booting fine and the door can be opened using the script but the RFID reader's not working.

**Comment by johnmckerrell** [comment]
Just a note that the IP address seems not to have been registered in the router's config, or that setting has been lost somewhere along the way. The current IP address is 192.168.0.106, external access will not currently work. I've added a reservation to ...116 which will take effect the next time the router is rebooted.

**Comment by johnmckerrell** [comment]
IP Address is now fixed having rebooted the router today.

**Comment by johnmckerrell** [comment]
Played with it somewhat today. It does look like the RFID board isn't functioning correctly. Weirdly there appears to be an LED missing from the board but when holding an RFID card to the powered board, there's 3.3v going over the LED's connections, and yet the Pi still isn't getting any information.

I've ordered a new board, hopefully that will work.

**Comment by johnmckerrell** [comment]
Both the old Pi and Patrick's are on my desk, along with the old RFID reader. I don't imagine the new RFID reader will come tomorrow (Saturday) but if it does feel free to open the parcel and try it out.

**Comment by johnmckerrell** [comment]
Turns out both the RFID reader and the Pi were broken. Replaced both today and it's now working. The RFID PCB needs a cover but I've opened a separate issue #98 for this.
