### ISSUE TITLE
We have a leaky pipe!

### ISSUE THREAD

**Issue by paulfurley** [DoESLiverpool/somebody-should#924]
The downpipe behind the fridge has lots of water dripping down!

**Comment by DoESsean** [comment]
It's coming from upstairs  - they have tightened the joins that appear to
be letting water in, but can't actually seal it until after the rain has
stopped. The dripping has already slowed down considerably, and it looks
like Paul's eagle eye and fortuitous timing has spared any real damage.

**Comment by johnmckerrell** [comment]
Someone should update the flood counter.

**Comment by DoESsean** [comment]
Not had a problem with this for ages, so I can only assume the issue from upstairs has been fixed.

**Comment by johnmckerrell** [comment]
We had a wet patch on the floor earlier this week but I just cleaned it up and it didn’t come back. The drainpipe felt dry to the touch at least

--
