### ISSUE TITLE
Document/diagram the building entrance dimensions

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#926]
The building entrance involves a quite sharp corner which might be difficult to get through on a mobility scooter. We should draw a diagram with measurements to provide to visitors.

**Comment by johnmckerrell** [comment]
While we're at it we should measure the lift.

**Comment by johnmckerrell** [comment]
I've taken the measurements and some photos, will post them somewhere tonight. Just adding a note that we had an enquiry about mobility scooter access and that the person wanted to go to the Ladies who UX event. I should get back to them once the documentation is live.

**Comment by ajlennon** [comment]
Presumably if anybody asks we can support mobility scooters? Are there any limitations we need to be aware of, size/weight etc.?

**Comment by jackie1050** [comment]
Possibly we might get more people with assessibility issues for Lost18 on Saturday too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by magman2112** [comment]
A small issue with your diagram John, the main entrance doors open outwards, not inwards, which actually means that access is a little wider as a consequence.
