### ISSUE TITLE
Get an omnidirectional microphone for livestreams such as community meetings

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#929]
We need some sort of microphone that can sit in the center of the table for the community meetings and other live streamed events that have many people in the same room. Something like a blue-yeti is well suited to this, but anything that is omnidirectional will do just fine.

I heard that @johnmckerrell might have some sort of bluetooth "conference-thingy" that might fit the bill.

**Comment by johnmckerrell** [comment]
Yes there is such a thing. It used to live in the stationery cupboard but not sure where it is now. 

--

**Comment by DoESsean** [comment]
I can't see that mic in the stationery cupboard now that it's been more organised, so, unless anyone knows better, there's a reasonable chance it's gone walkies during the move.

Similar ones cost in the hundreds of pounds, so something like [this](https://www.amazon.co.uk/dp/B008BS3CF8/ref=asc_df_B008BS3CF858142109/?tag=googshopuk-21&creative=22146&creativeASIN=B008BS3CF8&linkCode=df0&hvadid=218081924305&hvpos=1o4&hvnetw=g&hvrand=10092669290109027773&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9046555&hvtargid=pla-404766549319) could be a reasonable compromise.

**Comment by johnmckerrell** [comment]
Well one that’s exactly the same as the lost one is £80:

https://www.amazon.co.uk/gp/product/B00AARRS9Y/ref=oh_aui_search_asin_title?ie=UTF8&psc=1

Annoying if it’s just gone missing, it didn’t actually belong to DoES after all (but then I never did find my monitor either 😠)

**Comment by DoESsean** [comment]
Ah, I was looking at (and for, to be fair) one of those octopussy type
things with multiple legs. I'll have to have another look for this one...

Nope, still can't see it in the cupboard.

**Comment by DoESsean** [comment]
It appears that we're looking at the £70-85 range for one of these that seems decent.

Do we want to go ahead and purchase one? I'm inclined to say that there has been no need for one, and it seems daft to spend the money on something which wouldn't have been used at all anyway in the last 18 months, so, unless someone says otherwise, I'll close this next week.

**Comment by johnmckerrell** [comment]
The one I talked about did turn up. Can you check in the cupboard?

--

**Comment by DoESsean** [comment]
It's there! Issue closed.
