### ISSUE TITLE
Gerald out of alignment

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#931]
Jade was having trouble getting Gerald to cut through 3mm ply today.  We traced the problem to the laser hitting the air-assist cone and so only partial power reaching the wood.

As a temporary fix, I've removed the air-assist cone so she can carry on with her cutting, but we need to adjust the mirror to fix things (maybe exacerbated by #387?)

**Comment by magman2112** [comment]
I adjusted the alignment of the mirrors on Sunday and Gerald was then able to cut 6mm MDF over the extremes of the bed.

I also found a few loose bolts on the lens block as well as a few loose screws on the mirror on the lens block. All were tightened and the mirror screws will be checked on future alignments.

**Comment by johncain39** [comment]
Hi Guys, the laser is slightly out of alignment and could do with a little TLC to put it right. Only just heard about the orings for the mirrors which are needed too. Laser head has been removed for now and air assist tube secured by a zip tie aimed at nozzle.

**Comment by magman2112** [comment]
@dazz-ling adjusted the top mirror slightly last week and the Gerald now appears to be cutting OK with the Air Assist nozzle re-fitted again. So closing this issue again.
