### ISSUE TITLE
Felicity squeals when she prints

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#934]
Felicity has started squealing a bit while printing, presumably because the rods holding the extruder up could do with lubricating.

We've got grease and oil, but it'd be good to check what Ultimaker recommend.  Probably worth lubricating Prints Adam at the same time...

**Comment by amcewen** [comment]
The Ultimaker website recommends [a single drop of sewing machine oil](https://ultimaker.com/en/resources/150-lubricating-the-axles).  I've done that (on both printers), which has improved things.

However, while doing that, I noticed that the drive rod at the back has a fair bit of play in it, so we should tighten that up too.

**Comment by johnmckerrell** [comment]
Still/again squeaking

**Comment by drfraz** [comment]
I just love the title of this thread, I assume she is squealing with delight.

**Comment by amcewen** [comment]
I noticed at maker night that the rod holding the extruder that runs left-to-right was fouling against the side on the left (you can see where it's worn a bit of the side).  I adjusted it so that it sits a bit further from the side, and it doesn't seem to be squealing any more.
