### ISSUE TITLE
Leak in ceiling is pouring onto electrical sockets

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#936]
I and Darren discovered this earlier, placed a bucket and support underneath of it to catch the drips. If left unchecked it will pour right over the mains. Coincided with massive construction noise upstairs, and also some degree of light rain.

**Comment by johnmckerrell** [comment]
Did you report it to anyone upstairs?

--

**Comment by MatthewCroughan** [comment]
@johnmckerrell Someone from upstairs came down shortly after, we let him know, he saw it, didn't have much to say. Unsure where to go from here, or if it was even caused by them, @dazz-ling was present too.

**Comment by johnmckerrell** [comment]
This seems to have cleared up now.
