### ISSUE TITLE
Change our address with the ICO

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#939]
I've just renewed our data protection fee but we need to change our address. I'm wondering if Sean knows where the access key is otherwise we'll need to send for another one. (This and the receipt will actually go to Gostins).

**Comment by johnmckerrell** [comment]
> On 30 Oct 2018, at 12:30, Seán Gleeson <notifications@github.com> wrote:
> 
> Do you have our registration number @johnmckerrell <https://github.com/johnmckerrell>?
> 
> I'll need it to get a new access code sent out.
> 
> 
Is it on the recent paperwork we got? The access code’s definitely not somewhere in the filing cabinet?

**Comment by DoESsean** [comment]
Good point, recent letter sitting right on my desk. I never claimed to be
smart.

The original paperwork isn't in the filing cabinet - I assume they must
have sent it via email otherwise I'm sure it would be. I'll apply for a new
access code.

**Comment by DoESsean** [comment]
Emailed today to change the address, will close this issue once we get confirmation that it's gone through.

**Comment by DoESsean** [comment]
Never got a confirmation, but I've just checked the register and our address has been updated. Consider this closed.

**Comment by johnmckerrell** [comment]
Well the renewal came to the right address ;-)
