### ISSUE TITLE
The black webcam for the workshop door needs its power supply fixing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#94]
When I unplugged the power supply for the black webcam while swapping the extension during issue #89, the other end fell out - looks like the plug has partially fallen apart.

We'd need to get a ladder to fix it, so for now I've labelled the power supply "black webcam above workshop door" and stuck it into the DoES Infrastructure box on the racking for safe keeping.

**Comment by amcewen** [comment]
Need to work out exactly which plug it'll need - I've probably got a spare we can use (see "Power" drawers on my desk), and soldering up and re-deploying

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by DoESsean** [comment]
@amcewen Did the power supply for this ever get worked out?

**Comment by johnmckerrell** [comment]
I think we can forget this one.
