### ISSUE TITLE
Design new Code of Conduct poster for the main space

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#940]
As mentioned in the Community Meeting, we have been working with Anna of Liverpool HR to refine our policies on safe spaces, grievance procedures etc.
As part of this, Anna has drafted a Code of Conduct for community members. This needs to be made into a poster to be displayed in the main space. I've passed the details to Zarino as he's willing to do this.

**Comment by DoESsean** [comment]
@zarino was any progress made on this? Once we have it done, it can go up in one of the frames that are dotted around.

**Comment by DoESsean** [comment]
Fantastic, thank you!

**Comment by zarino** [comment]
Oh, @jackie1050 adds that the thing we were waiting for is a "grievances" address / list of individual grievance team addresses to go at the end, in place of the "organisers" address.

**Comment by DoESsean** [comment]
I guess that would be something for @johnmckerrell or @amcewen (or someone else with email admin privileges) to do.

**Comment by johnmckerrell** [comment]
We have grievances@ set up but we need a page to link to as well that lists who’s on it and gives the individual email addresses too.

**Comment by DoESsean** [comment]
Would a Wiki page do, or does it need to be on the website?

**Comment by DoESsean** [comment]
Also, do we have a list of who is on the team and their addresses? If so, I can add that page today.

**Comment by Robotorium** [comment]
John, Adrian, Jackie, Chris T, Helen C, Zarino, JR and me. I think.

Op do 31 jan. 2019 14:44 schreef Seán Gleeson <notifications@github.com:

**Comment by zarino** [comment]
Ok folks – Thoughts?

<img width="567" alt="screen shot 2019-02-01 at 05 10 20" src="https://user-images.githubusercontent.com/739624/52103860-bcfad280-25df-11e9-9d64-0df5e7774ed6.png">

**Comment by jackie1050** [comment]
Looks great and really readable.

Not sure if the diagonal elements look particularly
"DoESy", but then again what is our house style for subheadings...
________________________________

**Comment by jackie1050** [comment]
@robotorium - I've got some actions from the recent Directors' meeting relating to Grievances and Safe Spaces which I'll be sorting out this weekend. I need to add the email addresses to the Grievance procedure and publish.
@johnmckerrell - do we have a definitive source for the email addresses?

**Comment by DoESsean** [comment]
I am LOVING the new poster style that Zarino is using. I think they'll look
great in the space.

**Comment by jackie1050** [comment]
We should adopt it for everything then ??
________________________________

**Comment by zarino** [comment]
> We should adopt it for everything then ??

This sounds like something for a separate ticket! I’d like to get DoES using more standardised branding, but there are many factors involved. I’m hoping to have some more time to do something about it this year. In the meantime, one-offs like the poster above will have to do.

**Comment by jackie1050** [comment]
Sorry - I meant "for new things"! (also if people like it)
________________________________

**Comment by jackie1050** [comment]
I've added the names and email addresses of Grievance Team members to the people page of the Wiki

**Comment by zarino** [comment]
An updated version, with links to the "People" wiki page, and full Safe Spaces policy page.

<table><tr><td>
<img src="https://user-images.githubusercontent.com/739624/52521109-f4195580-2c69-11e9-88f1-41a2b0937c83.png" alt="">
</td></tr></table>

**Comment by zarino** [comment]
This poster has now gone up, on the back of the main door. I expect there are lots of other places we could put it too – somewhere near the entrance to the events space, and in the toilets seem like good spots to me?

Anyway, I think the core of the issue has been solved here now, so I’m going to close the ticket.
