### ISSUE TITLE
Replace toner (and belt unit?) in the OKI colour printer

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#943]
Message says "C Toner is empty"

**Comment by ajlennon** [comment]
Reading the manual it says first try tapping the cartridges so I'll do that now

**Comment by zarino** [comment]
Message now _also_ says "Please change Belt Unit".

![img_7851](https://user-images.githubusercontent.com/739624/47745706-2a633400-dc7c-11e8-9705-91648ce7a94b.jpg)

![img_7854](https://user-images.githubusercontent.com/739624/47745708-2cc58e00-dc7c-11e8-9781-8742640ce988.jpg)

Web seems to suggest you can continue printing even after this message is displayed, but it’s not recommended.

**Comment by zarino** [comment]
Official toner cartriges for the ES5462 seem to go for £45–60 a piece, and last 6000 pages. Non-official compatibles cost £30-40.

Most places seem cagey about showing prices for a replacement Belt Unit, but I did spot one price online:

[ES44472202 Belt Unit](https://photostatic.com/transfer-belt/153-es5462-belt-unit.html) – £64 (£53 + VAT)

Another alternative—but probably not one I’d recommend—is spending less money on a shiny piece of paper that tricks the printer into thinking the Belt Unit is new:

["Image Transfer Belt Reset Chip"](https://www.ebay.co.uk/itm/Super-Easy-Drum-Belt-Fuser-Reset-Kit-for-OKI-ES3452-ES5462-dnw-MFP-C5H-5462/121761322117) – £15 inc VAT

**Comment by magman2112** [comment]
I've had another look at this printer and some of the other supplies and parts are low as well,

The Fuser unit is showing 4% life left - I found one of these online for £59.30+VAT (and likely plus carriage).
As has already been mentioned, the Cyan cartridge is empty, but the Magenta Cartridge is only at 10% and the black cartridge has 30% remaining. I have found a few original cartridges on eBay for £28 inc postage (for the black) and re manufactured ones for £20-25 each.

All told, we will likely need to spend in the region of £200 to get this printer working and to keep it working in the near future.

As alternative, the HP Printer that Alex brought in appears to work, but needs a new black Toner cartridge. These are currently available for £53.99 from Amazon. This would appear to be a cheaper option in at least the short term.

It might still be worth keeping hold of the Oki printer in the short term though, as this appears to be the only scanner we have on site at the moment.

**Comment by amcewen** [comment]
The black A3 inkjet printer is also an A4 scanner, so we'd still have a scanner if we got rid of the Oki.

**Comment by ajlennon** [comment]
Thoughts...

I have a great deal of sentiment for my old HP Colour Printer. I picked it up from Cambridge Resale back in the day and it's a real workhorse. Has worked very well for me.

That said, if we only want one main colour printer the other one is very useful. 

I use the scanning feature on and off. The auto-feed on the scan and store to USB or email or whatever is excellent, e.g. for document signing and scanning. So it would be a shame to see this go

**Comment by DoESsean** [comment]
Did we fall down on an agreement as to whether it is (financially, rather than nostalgiacally!) worth the money to get this up and running?

Would we lose any capabilities if it's got rid of?

**Comment by zarino** [comment]
Pro:

* Colour laser (although we already have another colour laser – the black one @magman2112 brought in – which needs some more black toner)
* A4 scanner (although we alreday have another scanner – part of the A3 multifunction inkjet)
* Document feeder (aparently)

Con:

* At least two of us have been unable to scan to a USB, despite them being just regular FAT32 USB drives – not sure what’s going on there.
* Needs a new belt.
* Needs at least one new toner cartridge.

**Comment by ajlennon** [comment]
> At least two of us have been unable to scan to a USB, despite them being just regular FAT32 USB drives – not sure what’s going on there.

Yeah the USB scanning is a bit temperamental. I usually have to try a couple of different USB sticks.

That said it works once you get a stick it likes and I find the USB scanning incredibly useful when I need to scan something...

**Comment by ajlennon** [comment]
Possibly we want a couple of known good sticks with a "For the scanner" woodcut tag on it or something
