### ISSUE TITLE
Fuse for Dinky electrics was turned off

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#945]
The electrics (sockets at least) weren't working in Dinky. I looked in the fuse board and the fuse at the bottom left was turned off. I turned it on and things came back on.

This was used not so long ago for the heaters for the Scobys, I imagine this was related to the sound proof room electrics although their contractors insist not.

**Comment by amcewen** [comment]
Given that @zarino's computer is powered from that circuit, I presume it's something that happened yesterday (can't remember now whether it was a different guy doing the plastering)

**Comment by zarino** [comment]
The contractors in the soundproof room have been using power from the extension lead under my desk, for most of last week.

**Comment by zarino** [comment]
And yes, that extension was working fine on Saturday. So if something killed that ring, it must have been on Sunday.

**Comment by johnmckerrell** [comment]
Went off again overnight, causing the shutter to not open (similar to #944). Not sure why, no-one was using the soundproof room but a few people did use Dinky so would be worth checking with them in case they noticed it happening and when it happened @goatchurchprime @MatthewCroughan

**Comment by johnmckerrell** [comment]
Thought I'd add that the fuse on the bottom left was not labelled so now is ("East Sockets & Shutter" IIRC). This does not cover the lights on that side or the emergency light within the soundproof room though.
