### ISSUE TITLE
Set up doorbot system on the roller shutter at the back for cyclists

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#948]
referring to #759 but want to apply it so our fobs work on the back roller shutter.  

Attempting to make the garage door wireless signal didn't work as the controller uses a different 66 bit code each time, so you can't read and replay it.  

However, we can solder into a controller board and use it to send the wireless signal by controlling the buttons.  The buttons close a 12V circuit on the battery and sends the signal.  

I have soldered in some wires and made a mosfet circuit so that it can be driven from a pinout of an ESP32 (pins 12 and 13).  

The MQTT reading code that has been loaded onto the ESP32 is:
https://github.com/goatchurchprime/jupyter_micropython_developer_notebooks/blob/master/scriptlet_technology/MQTT_garageshuttercontroller.ipynb
(this uses async stuff so it can be reset.  Could have used the more general-purpose scriptlet tech, but the payloads would have been bigger.)

The command line mqtt commands are:
> mosquitto_pub  -h mqtt.local -t "garageshutter/code" -m "down 0.9"
> mosquitto_pub  -h mqtt.local -t "garageshutter/code" -m "up 0.9"

The "0.9" is the seconds that the button is held down.  

(The shutter has stopped working at the moment.  I think I've hit the button too many times and it's sulking.  Hopefully it will work later again.)

Next up: showing we can run an I2C wire from by the shutters up to a doorbot in room29 to carry the rfid readers.  Then we can build this back in as a direct plugin from the rpi.

**Comment by ajlennon** [comment]
If it's like this you just need to work out the pseudo RNG algorithm in use

https://auto.howstuffworks.com/remote-entry2.htm

**Comment by DoESsean** [comment]
Is there still a requirement or desire for this? It seems like it was something that might have been given some consideration, but has been completely forgotten about, particularly given the discussions around getting on street cycle parking.

**Comment by johnmckerrell** [comment]
Do we have cycle parking yet?

--

**Comment by amcewen** [comment]
The cycle parking is under the stairs now, and Melodic Distraction handle opening the yard shutter, so I think this can be closed...
