### ISSUE TITLE
RFID reader on main door isn't working

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#95]
I think in the fiddling with the RFID reader that @johnmckerrell and I did earlier today while investigating #92 the wiring for the RFID reader has been disturbed.

I noticed when I was locking up to leave - I did have the reader read my card once, with some fiddling of the wiring, but haven't been able to get it into a state where it works.

**Comment by johnmckerrell** [comment]
Was just the 3.3V line had been pulled up as we were investigating the pin-outs. I've soldered it back on and it's working fine now.
