### ISSUE TITLE
Plan a Christmas decoration making workshop at DoES

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#953]
### What

A hands-on workshop for 10–20 people, over 2-3 hours, making 2 or 3 Christmas decorations of different styles/materials/techniques. Charging £15-20 per person? With profits going to DoES.

Participants will get to learn a whole bunch of new techniques, as well as flexing their creative muscles, customising and personalising their decorations, before taking them home to impress the family.

Entry price could include maybe 1 of each decoration type, but if participants wanted to make more, we could just add £1 per item to cover costs?

### Who

People who haven’t been to DoES before! Can we target parents via our school / pre-school / mother and baby group connections? Or older ladies who fancy an afternoon doing something fun as a group?

Might there be connections to be made via the fashion hub?

### When

Could potentially run it on December Maker Day (Saturday 8th December). Or, if we think the space will be too full already (or the equipment too busy) we could do the weekend before (Saturday 1st).

### Things to plan

1. How / where we can market it
2. How much to charge
   * Will be easier once we know what materials the projects will involve
   * Do we provide food? Could potentially charge more if we include lunch.
3. The projects
   * A laser cut one
   * A papercraft / origami one
   * And something with very _very_ basic electronics??
4. Date and time
5. Helpers
6. "Here’s one I made earlier" demo pieces, for marketing, and on the day

**Comment by jackie1050** [comment]
I've made a couple of laser cut baubles - they're currently attached to the side of the solvents cupboard with magnets. There are dxf files in Dropbox/DoESLaser/jackie/bauble and I've also emailed a copy to @zarino . They were created the with OnShape so I could send the link for that. Some of the lines seem to be doubled, possibly due to the way I used reflection in OnShape.

bauble cut 1, 2, and 3 are parts for the 3D bauble.
You need one with 4 slots on the outside, one with 4 slots on the inside and one with 2 slots on the inside and 2 on the outside.
The material needs to be flexible. MDF worked but acrylic shattered. I haven't tried ply yet.
The small holes were intended for attaching the diamond shapes with jump rings, but these would need to be be quite large for use with 3mm material. Some of the holes need to be moved further from the edges or deleted if not needed.
The design could be personalised by using a name for the hanging part in the middle. @ajlennon and Anthony are going to try something out.

string art bauble is the one for wrapping with gold thread. There is some in the sewing drawer. It might be useful to change the loop at the top to a hook as there is a slot at the top which it is difficult to feed the thread through.

I can also work on the infinity mirror design to use with cheaper battery powered lights.

**Comment by zarino** [comment]
I‘ve created a new repo with the updated vector files in it: https://github.com/DoESLiverpool/christmas-decorations

**Comment by zarino** [comment]
If we end up letting people typeset their own names, we’ll want some nice fonts.

These Adobe ones I can use for free as part of my Creative Cloud subscription:

* https://fonts.adobe.com/fonts/bistro-script
* https://fonts.adobe.com/fonts/cortado
* https://fonts.adobe.com/fonts/alana
* https://fonts.adobe.com/fonts/al-fresco
* https://fonts.adobe.com/fonts/spumante

These ones, would cost separately:

* https://www.myfonts.com/fonts/aerotype/turbinado/
* https://www.myfonts.com/fonts/sudtipos/blog-script/
* https://www.myfonts.com/fonts/mika-melvas/organika/
* https://www.myfonts.com/fonts/medialabco/snowdrop/
* https://www.myfonts.com/fonts/mika-melvas/handelson/
* https://www.myfonts.com/fonts/kimmy/catalina/

Open Source fonts tend to be less characterful, but there’s a few I spotted that could do for us:

* https://fonts.google.com/specimen/Amatic+SC
* https://fonts.google.com/specimen/Shadows+Into+Light
* https://fonts.google.com/specimen/Cookie
* https://fonts.google.com/specimen/Sacramento
* https://fonts.google.com/specimen/Grand+Hotel

**Comment by ajlennon** [comment]
Or there are some useful free font sites?

eg 

https://www.dafont.com/

**Comment by Helen-8** [comment]
This all sounds great. Can imagine this being a very fun afternoon together with some mince pies and Christmas tunes in the background.

The papercraft one should be fairly simple, as long as we have some time to practice, and it'll be useful to act as 'filler' if the workshop tools get quite busy.

Some examples of designs:
![image](https://user-images.githubusercontent.com/33836782/47793355-fdfbf600-dd15-11e8-8253-0a0b4a9b57ad.png)
![image](https://user-images.githubusercontent.com/33836782/47793400-11a75c80-dd16-11e8-82b9-0b62177a68ec.png)
![image](https://user-images.githubusercontent.com/33836782/47793483-40bdce00-dd16-11e8-8156-24668d8e325a.png)
![image](https://user-images.githubusercontent.com/33836782/47793503-4ca99000-dd16-11e8-9842-bc6063645e7d.png)

You can also get quite reasonable packs of Christmas origami paper from Amazon - 
![image](https://user-images.githubusercontent.com/33836782/47793523-5b904280-dd16-11e8-854d-9c83b0a978e7.png) - or I expect Abakhan would have some too

**Comment by jackie1050** [comment]
They look really good

On 31 Oct 2018 14:08, Helen-8 <notifications@github.com> wrote:

This all sounds great. Can imagine this being a very fun afternoon together with some mince pies and Christmas tunes in the background.

The papercraft one should be fairly simple, as long as we have some time to practice, and it'll be useful to act as 'filler' if the workshop tools get quite busy.

Some examples of designs:
[image]<https://user-images.githubusercontent.com/33836782/47793355-fdfbf600-dd15-11e8-8253-0a0b4a9b57ad.png>
[image]<https://user-images.githubusercontent.com/33836782/47793400-11a75c80-dd16-11e8-82b9-0b62177a68ec.png>
[image]<https://user-images.githubusercontent.com/33836782/47793483-40bdce00-dd16-11e8-8156-24668d8e325a.png>
[image]<https://user-images.githubusercontent.com/33836782/47793503-4ca99000-dd16-11e8-9842-bc6063645e7d.png>

You can also get quite reasonable packs of Christmas origami paper from Amazon -
[image]<https://user-images.githubusercontent.com/33836782/47793523-5b904280-dd16-11e8-854d-9c83b0a978e7.png> - or I expect Abakhan would have some too

**Comment by zarino** [comment]
Ok, we’re currently thinking:

# 1. Papercraft stars

Like this, except with different colours on the various surfaces (possibly painted/printed through a laser-cut stencil):

![img_7888](https://user-images.githubusercontent.com/739624/48225391-9b010380-e394-11e8-93ad-bcf306e6cd00.jpg)

# 2. Mirrored acrylic snowflakes (with free spirograph bauble!)

Like these little orange flowers, except in more Christmassy mirrored acrylic colours (gold, silver, red, green?) and in more snowflakey shapes, and a bit bigger:

![img_7886](https://user-images.githubusercontent.com/739624/48225493-e3202600-e394-11e8-9e36-adcee4cb8450.jpg)

The advantage here, is that while we’re laser cutting the snowflake parts, we can get a "free" hollow bauble around the edge, which they can then do spirograph string art on!

# 3. Glittered name bauble

Attendees get to customise the text, then it’s laser cut out of plywood, and decorated with spraymount and glitter, maybe in a few different colour blocks:

![img_7887](https://user-images.githubusercontent.com/739624/48225537-ffbc5e00-e394-11e8-8e9c-d8ba8fca591c.jpg)

**Comment by KarlDunkerley** [comment]
Looks good. Not sure about papercraft but can help with others. Do you have dates in mind?
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Thursday, 8 November 2018, 20:29:48 GMT, Zarino Zappia <notifications@github.com> wrote:  
 
 
Ok, we’re currently thinking:

1. Papercraft stars

Like this, except with different colours on the various surfaces (possibly painted/printed through a laser-cut stencil):



2. Mirrored acrylic snowflakes (with free spirograph bauble!)

Like these little orange flowers, except in more Christmassy mirrored acrylic colours (gold, silver, red, green?) and in more snowflakey shapes, and a bit bigger:



The advantage here, is that while we’re laser cutting the snowflake parts, we can get a "free" hollow bauble around the edge, which they can then do spirograph string art on!

3. Glittered name bauble

Attendees get to customise the text, then it’s laser cut out of plywood, and decorated with spraymount and glitter, maybe in a few different colour blocks:

**Comment by zarino** [comment]
@KarlDunkerley We’ve just been looking at dates today. Hoping to share a few possibilities over the next few days.

**Comment by Helen-8** [comment]
The eventbrite for this is up and running! We settled for 2pm on Sunday 9th December. More details here:
https://www.eventbrite.co.uk/e/does-liverpool-presents-make-your-own-christmas-decorations-tickets-52685643177

**Comment by magman2112** [comment]
I mentioned to Jackie last night that I have found a flashing LED module at a reasonable price on eBay.

https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.co.uk%2Fulk%2Fitm%2F262892712517

This might be an option for one of the laser cut baubles.

Also, I am quite happy to help out on the day.
