### ISSUE TITLE
Finalise networking for soundproof room and Dinky

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#954]
Ben from Find Out says the network sockets in his two rooms aren’t working.

It might be that they’ve never been patched into the switch in the cupboard.

@johnmckerrell says he’ll investigate, but we’ll keep this ticket open until it’s sorted.

/cc @magman2112 in case he has any insights to lend.

**Comment by skos-ninja** [comment]
@johnmckerrell if you plug them into a port on the UniFi switch and let me know which port I can do this remotely for them

**Comment by johnmckerrell** [comment]
Ok, thanks, we'll leave it for now as they /will/ want it accessible from the Wi-Fi so don't want to complicate matters.

**Comment by skos-ninja** [comment]
I can setup a seperate WiFi network for them at the same time too. Just let me know on Slack what you would like the ssid and key to be

**Comment by skos-ninja** [comment]
@amcewen yes it is all setup for them

**Comment by johnmckerrell** [comment]
Details of it are here https://github.com/DoESLiverpool/networking-secure/blob/master/find-out-digital.md (Only accessible to the networking team)

**Comment by amcewen** [comment]
Great, assuming we can close this now then.
