### ISSUE TITLE
Saw blade broken in large bandsaw.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#956]
The blade broke with a bang on the large bandsaw on Maker night, which now means we have no working bandsaws in DoES. @Sean-anotherone did look to see if the broken belt could be welded, but on closer examination there were quite a few additional cracks and broken teeth, so a new blade is the way forward for this machine.

The replacement blade appears to be 2369mm, and this is available from a few suppliers. We do need to measure the width and the TPI (tooth per inch) to find an equivalent blade. Typical prices ar £11 to £14, so they are not massively expensive. A couple of links to suppliers are included below.

https://www.powertoolspares.com/startrite/301s-bandsaw.m/301s/accessories

https://www.axminster.co.uk/axcaliber-freshcut-37-gt-straight-cut-bandsaw-blades-ax947760

**Comment by Sean-anotherone** [comment]
I would suggest a relatively fine-toothed bi-metal blade - that way it will still work for wood (although not optimally) but would be OK for metal cutting too.  Higher tooth-count also suits cutting of thinner materials which is what the machine seems to mostly do.  I'd guess that the old blade was either 20 or 24 tpi.

**Comment by jackie1050** [comment]
Could you recommend a specific blade - I'll order. We've been very happy with the service provided by Axminster up to now so I'd be keen to use them.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sean-anotherone** [comment]
Axminster don;t seem to keep one.

I found this page on eBay - 

https://www.ebay.co.uk/itm/1-2-13mm-Bandsaw-Blade-Any-Length-and-TPI-UK-Manufactured/291879294272?hash=item43f55c9540:m:mNVhvhHHBEK7c6Ghqr0Xv4Q:rk:2:pf:1

They will make a 93 1/4 by 1/2 by 24tpi for £14.29 delivered.

That is for a "flexback hardened tooth" blade, no-one seems to supply bimetal blades in the right size.

I also have several spare blades that will probably fit the small tabletop bandsaw, I'll bring one next week.

**Comment by Sean-anotherone** [comment]
Or from here a tenner plus post : 
https://www.northeastgrinding.co.uk/blades/93-2362mm-starrett-duratec-sfb-super-flex-back-band-saw-blade-for-scheppach-startrite-machines/

 (the half-inch by 24tpi one again)

**Comment by jackie1050** [comment]
I'll check tomorrow

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sean-anotherone** [comment]
I found a broken blade under the woodworking bench and successfully welded it back together, large bandsaw fixed.

**Comment by amcewen** [comment]
Unfortunately the fix hasn't lasted too long - @magman2112 reported it broken again yesterday.  I've ordered one of the blades from North East Grinding (it came to £14.45 with postage)

**Comment by amcewen** [comment]
Blade has arrived and @Sean-anotherone fitted it at maker night on Thursday.
