### ISSUE TITLE
Automate opening the front door when people are in

### ISSUE THREAD

**Issue by paulfurley** [DoESLiverpool/somebody-should#957]
Every time the phone rings, most people in both rooms look up, look around, perform some nonverbal negotiation, then someone stops what they're doing, walks over to the phone, picks it up, ignores the caller and presses 3 to let them in.

As far as I can tell, pressing 3 is the only valid option—I'm not aware of any circumstances where we *don't* let the person in.

So it appears we're using the telephone as a human-powered sensor of whether there's anyone in DoES. This doesn't seem like a task we should burden humans with, especially when they're trying to get on with some work.

Suitable alternative approaches:

* test: is it between 9.30 and 17.30 on a week day? (we could implement this today)
* test: has there been motion in the space in the last 5 minutes? (we could implement this with a bit of work)
* pay @DoESsean full time (blocked unless we have more permanent desks to be able to afford him)

Am I missing something, or is this something we can just automate and make the space a little more peaceful?

**Comment by amcewen** [comment]
I don't ignore the caller and just press 3.

Most people who are allowed to just wander into the space will have fobs to let them do just that.  We can, and should, be encouraging more people in those categories to get fobs.

Anyone else - someone who wants to look round; people delivering parcels; people who want to get onto the roof to rescue seagulls... - will require *some* sort of additional interaction beyond unlocking a door.  That can't be automated, so automating the door wouldn't save us much.

The other fix would be to find enough people to take desks, etc. so that we're profitable enough to be able to afford a full-time @DoESsean

**Comment by paulfurley** [comment]
> Anyone else - someone who wants to look round; people delivering parcels; people who want to get onto the roof to rescue seagulls... - will require some sort of additional interaction beyond unlocking a door. That can't be automated, so automating the door wouldn't save us much.

Aren't all these people covered by the fact that they have to ring a doorbell when they reach the upstairs door?

> The other fix would be to find enough people to take desks, etc. so that we're profitable enough to be able to afford a full-time @DoESsean

I've added that to the list of options, marked as *blocked* until we rent more permanent desks.

**Comment by amcewen** [comment]
Who deals with the people who ring the doorbell?  *Maybe* it could be the person who's just answered the phone?

**Comment by johnmckerrell** [comment]
Also people who are using the intercom are less likely to know that they need to come up to the 1st floor, there's been a few times I've waited then gone looking for the person who I've just let in and they're downstairs.

To me it feels like there's definite improvements that could be made but I don't feel like automatically opening the door from the intercom is the first step.

**Comment by paulfurley** [comment]
> Also people who are using the intercom are less likely to know that they need to come up to the 1st floor, there's been a few times I've waited then gone looking for the person who I've just let in and they're downstairs.

At risk of jumping to a solution, we could have a voicemail that say "Please come up to the first floor and ring the doorbell", then sends the 3 DTMF tone.

**Comment by paulfurley** [comment]
> Who deals with the people who ring the doorbell? _Maybe_ it could be the person who's just answered the phone?

Or anyone else.

**Comment by paulfurley** [comment]
> To me it feels like there's definite improvements that could be made but I don't feel like automatically opening the door from the intercom is the first step.

Cool, what do you think *is* the first step?

**Comment by johnmckerrell** [comment]
It hasn't been said but there are times when I don't press 3. If I get no response from the person or if they don't sound like they should come here I won't press it.

My initial improvements would be to make it easier to get to a phone, so placing them better and/or adding more.

**Comment by jackie1050** [comment]
It feels to me that we shouldn't even let unidentified people into the building. We might as well leave the front door unlocked in that case, and people might be able to steal stuff from unsupervised areas, hang around in corridors etc.

Maybe we shouldn't need all the phones to ring though, just set priority (e.g. if someone's using the Event Space they let people in ...).

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amcewen** [comment]
@paulfurley, by "Or anyone else." do you really mean "not me"?  Because that's how it's coming across but maybe it's just that you hadn't realised before the additional work you've been handing off to other members of the community when you just buzz people in.

There's agreement (I think?) that most of the times the intercom goes it's an interruption that requires some level of human interaction.  That dance of social negotiation that you've identified is us collectively working out who the "anyone else" is for handling that interruption this time, isn't it?

**Comment by ajlennon** [comment]
fwiw I always have a quick word with the person calling before I decide whether to let them in.

I also work on the basis that unless I know them / they say they've forgotten their pass / they sound confident then they're probably a newbie and need some metaphorical hugs.

It generally involves going to meet them, sometimes handing them off to whoever they are trying to find and sometimes half an hour showing them the joys of DoES.

I take the view this is part of the time cost of working out of a community like DoES.

**Comment by paulfurley** [comment]
> @paulfurley, by "Or anyone else." do you really mean "not me"? Because that's how it's coming across but maybe it's just that you hadn't realised before the additional work you've been handing off to other members of the community when you just buzz people in.

@amcewen It's kinder not to put words in other people's mouths :)

I hear you that I've been handing off additional work to other members of the community—thanks for being honest!

> It generally involves going to meet them, sometimes handing them off to whoever they are trying to find and sometimes half an hour showing them the joys of DoES.
> I take the view this is part of the time cost of working out of a community like DoES.

@ajlennon I think this is a very nice way of putting it.

The reason I'm bringing this up at all is that I find it extremely harmful to my focus to get up and answer the phone, then walk round and let the person in, and possibly give them a 30 minute tour (I presume others find it harmful to their focus too).

I'm not saying that my focus is any more important than anyone else's *but* I wasn't clear that having a permanent desk costs both money *and* being interrupted throughout the day.

More important than the doorbell: what I really want to avoid is quiet resentment from others that I'm not "pulling my weight". I'd like to know that supporting DoES by paying for a permanent desk, telling people about it etc is good, and not have a hanging guilt that I don't do enough here. Now I'm thinking properly about it, I *do* have that feeling, that's not healthy.

(Related note: I did offer to receive the doorbell calls on my desk phone but @johnmckerrell didn't go for it!)

**Comment by ajlennon** [comment]
> I'm not saying that my focus is any more important than anyone else's but I wasn't clear that having a permanent desk costs both money and being interrupted throughout the day.

I do agree the bell ringing all the time (it feels like it) and starting and stopping at different times in different rooms, and having to evaluate each time whether I should stop what I'm doing because it's my informal turn, is all really distracting.

Agreeing with the above too, it feels like as a process it could be improved, but I'm at a loss to know how
