### ISSUE TITLE
Reinstate the FreshStaleLastChance boxes

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#959]
So that we can keep the space tidier, @Helen-8 suggested having an area that "lost property" could live, so that things can be tidied there if there's no obvious home for them.  That reminded me that we haven't set up the [FreshStaleLastChance](https://github.com/DoESLiverpool/wiki/wiki/FreshStaleLastChance) boxes in the new space.  We should do that.

Back in DoES 1.0 (at Gostins) this didn't work perfectly, mostly because (I think) we didn't do the disposing step frequently enough, so things tended to accumulate.  Would anyone be up for taking stuff to the tip once-a-month or similar so we can try to keep on top of it?

Beyond that, we likely need to get some boxes we can designate for that purpose, and find somewhere for them to live.

**Comment by amcewen** [comment]
I think we need some better signage on them so that people understand what they're for.  I got part-way (as I added the "Free Stuff" stickers), so I've been leaving this open to remind me it needs finishing.

One of the 3 boxes has gone awol too - @ajlennon, you don't know its whereabouts do you?  IIRC we only got one back (taking us to two) after your tip run but I *thought* you'd taken two to the tip?

**Comment by DoESsean** [comment]
Fair point :)

**Comment by ajlennon** [comment]
I think it’s on my desk :)
