### ISSUE TITLE
Workshop Doorbot (3) needs a new header socket fitting

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#96]
When borrowing the Doorbot3 Pi the plastic fell apart surrounding the header socket that plugs into the GPIO pin on the Pi for opening the door. It appears to be working again with the metal parts of the socket touching the GPIO pin on the Pi but it's not ideal as there's no protection and no guarantee that they will remain touching when the door slams shut so a new header socket needs fitting (probably worth having more than 1 pin's worth for structural stability).

**Comment by amcewen** [comment]
This should be fixed once https://github.com/DoESLiverpool/doorbot-setup/issues/6 is fixed.

**Comment by johnmckerrell** [comment]
@amcewen feels like this is an old issue and probably fixed now?

**Comment by amcewen** [comment]
Yes, the boards for the other two doorbots haven't been installed yet (although @helicalbytes has soldered them up ready) but the workshop doorbot is all sorted.
