### ISSUE TITLE
We need a price list poster for services

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#962]
We should have a poster up listing all the prices for desk and workshop usage, and covering membership discounts.

**Comment by DoESsean** [comment]
I've spoken before about getting the kind of displays they have in pub toilets.

[https://www.ukpos.com/snap-frame-25mm-frame?vat=2&gclid=EAIaIQobChMI5r6x3cCz3gIVi7HtCh009gXbEAQYASABEgJDPvD_BwE#sku:PFG3A4&infinity=ict2~net~gaw~ar~225563535997~kw~~mt~~cmp~UKPOS%20%7C%20Shopping%20%7C%20Snap%20Frames%20%7C%20Cheap]This kind of thing.(url)

I appreciate that this is probably the kind of thing we could knock up in house, but, given that I'm not likely to be the one that would do it, how viable is it that it would get done in a timeframe where we don't think, 'I could have just bought those?' 

They're not massively expensive, and we wouldn't need loads. As well as that, it would be better than just having A4 posters blutacked to the wall, and would possibly encourage us to switch them up more often if we're seeing the same thing all the time, meaning we'd be more inclined to publicise more things.

**Comment by DoESsean** [comment]
In my head, it would be one in each toilet, one on the back of the main door, one on the CNC door, one on the laser door. Possibly a couple of others if we can figure out where else would be good to put them.

**Comment by johnmckerrell** [comment]
Your link didn’t work but putting print outs in picture frames seems sensible and simple to me. 

--

**Comment by DoESsean** [comment]
No idea why that link went nuts.

@zarino, as our resident Design Dude, could you take a look at these and let me know whether you think black or silver will look better in the space. They will be on doors as outlined above, but also used for general notices in places like the kitchen.

[https://www.ukpos.com/snap-frame-25mm-frame](url)

**Comment by zarino** [comment]
@DoESsean I’d get white if the frame’s going on a white wall, or black if it’s going on a door or a brick wall.

**Comment by DoESsean** [comment]
Apparently I can't link. Amazing.

**Comment by DoESsean** [comment]
Given that white are a few quid more expensive, would black work across the board? I'm not sensing a lot of love for silver.

**Comment by zarino** [comment]
Black across the board then.

**Comment by DoESsean** [comment]
Great, thanks Design Dude™

**Comment by DoESsean** [comment]
There is a price list poster [here](https://docs.google.com/document/d/1-RmCZhzh-X97IrxIT3XIH-lZBVO-NpT1tk_vzfpV2ZE/edit) but I can't connect to the A3 printer to print them off - it's saying I don't have the drivers.

If someone else wants to print a couple off (making any changes to style you might see fit), then I'll get them up around the space.

**Comment by zarino** [comment]
@DoESsean The google doc link still isn’t accessible.

**Comment by DoESsean** [comment]
Weird, I got the shareable link from the doc itself. Should be ok now, hopefully.

**Comment by DoESsean** [comment]
Also, it's worth noting that it seems Google Docs doesn't support the DoES house font, so it's changed it slightly.

**Comment by DoESsean** [comment]
That is perfect. I knew there was a reason we kept you around ;)

**Comment by DoESsean** [comment]
Ooo, actually yes, adding the surcharge makes sense, then there are no
surprises at all.

**Comment by zarino** [comment]
Updated to include the big laser cutter surcharge.

<table><tr><td><img src="https://user-images.githubusercontent.com/739624/52521157-ae10c180-2c6a-11e9-8cbc-82206038d29e.png"></td></tr></table>

**Comment by johnmckerrell** [comment]
Non member permanent desk should be 180 iirc

--

**Comment by johnmckerrell** [comment]
Oh and the mailbox is an annual fee not 1 month

--

**Comment by zarino** [comment]
Thanks @johnmckerrell! I’ve updated source file, and the image in my comment.

**Comment by zarino** [comment]
This poster has been designed, and a copy has been put up in the frame on the laser room door. Going to consider this ticket "done".
