### ISSUE TITLE
Building lift is breaking/broken

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#963]
I apologise if this is the wrong place, since it isn't DoES itself but the building, but I couldn't figure out a better place for it as I'm a bit ill and a lot feckless.

This evening, when Chris Huffee and I got in the lift to come up, the door wouldn't close on the ground floor unless he reached up and moved a metal flap out of the way.

On the way down, when I was nearly on the ground floor, the lift made a horrific grinding/shrieking noise and I think I felt the grinding but it may have been psychosomatic. It was incredibly loud within the shaft, and loud enough outside of it that Chris and Chris could hear it by the exit door. I let go of the 0 button, it stopped, and when I resumed pressing the button it proceeded down to the ground floor without further incident.

I'm worried because I don't want to get stuck. I have plans to come in tomorrow, in my (heavier) powerchair, but I have a fairly natural fear of lifts making loud shrieking/grinding noises while I am in them, which I believe is an evolutionary response to the prehistoric lifts that roamed the wilds in olden times.

I do not exceed or even approximate the max weight limit in either chair, in case that's relevant when reporting the issue to the appropriate people.

Again, my apologies if this is the wrong venue for this particular issue.

(While we're speaking to the landlord, would it be possible to also ask if he can tell other tenants not to block the hallway with giant furniture, please?)

**Comment by johnmckerrell** [comment]
Hi Snoof, the landlord has actually told us the lift will be serviced today, I'm not sure if this because the lift phoned home or perhaps someone else had a problem, or it's just coincidence. This may impact you as it will be out of action while they service it:

> The lift is being serviced today around 11am & will be out of action

Sorry about the furniture in the hall, I had spotted it but annoyingly it hadn't occurred to me how much of a problem it could be. I've mentioned it to the landlord so I'll need to leave it with him as I'm not in today.

There's nothing wrong with reporting problems here, you could also email hello@doesliverpool.com but I think with notifications either is just as visible, to me at least.

**Comment by Robotorium** [comment]
Excellent, thanks John. Any ideas how long the lift will be out of service
for? I am currently in DoES and need to leave about half two ish.

Op vr 2 nov. 2018 09:56 schreef John McKerrell <notifications@github.com:

**Comment by johnmckerrell** [comment]
The message above is all I've had. I've texted the landlord to tell him that someone should come into DoES and talk to you before putting the lift out of service.

**Comment by Robotorium** [comment]
Fantastic, thanks so much!

Op vr 2 nov. 2018 om 10:33 schreef John McKerrell <notifications@github.com

**Comment by Robotorium** [comment]
The lift repair man has been, his name is Brian and he's stuck a sticker in the lift with his phone number on it. That number usually goes through to his phone, but in case someone's stuck and can only text or whatnot, his mobile number is 07881 471 234.

He did say that if there's only one person left in the building, they shouldn't use the lift because if they get stuck he won't be able to get in.

The grinding noise is caused by the cold, if it keeps happening or gets too loud he'll oil it more, but either way the lift is unlikely to eat anyone on the basis of that noise. The door downstairs was not shutting due to an anti-tampering device someone had accidentally activated, so that is also fixed now.
