### ISSUE TITLE
Take a look at the wooden floorboards on the entry stairway landing

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#965]
I was walking downstairs this afternoon, got to the landing halfway to the entrance, heard a cracking noise and suddenly my ankle went sideways from under me.

The area seems to have two smallish boards which are patching a hole and I suspect but am not certain if you stand in the middle of them they give way.

@amcewen has taken a look and kindly put some warning tape and the warning plastic sign on top but it's possibly something we should ask the landlord to look into sooner rather than later.

**Comment by jackie1050** [comment]
I Whatsappd Jason. He's since asked for a photo, which John has sent

**Comment by magman2112** [comment]
The broken floorboards now appear to have been replaced.

**Comment by ajlennon** [comment]
Great news!
