### ISSUE TITLE
Hang a monitor connected to entry doorbot to display the calendar and welcome messages

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#969]
We had this in the Gostins building, and it was great for spotting what was going on.  

@johnmckerrell has found the original monitor, which needs to be hung on the wall beside the entry way (needs this connector to be printed)  https://www.thingiverse.com/thing:3111424

Also need a connector from HDMI to DVI converter.

**Comment by johnmckerrell** [comment]
Or something like this https://www.amazon.co.uk/DRALL-INSTRUMENTS-Holder-PLASMA-50-200x100-Black/dp/B00K1P9BD6/ref=sr_1_10?ie=UTF8&qid=1541538351&sr=8-10&keywords=10cm+vesa+mount

**Comment by goatchurchprime** [comment]
The monitor is up and wired in to the doorbot Rpi.  Then @johnmckerrell said it should be in portrait mode, but this is not possible with the bracket I scavenged from the original stand.  

Doorbot now needs to be reprogrammed to boot up with a browser, the calendar and welcome messages.

**Comment by johnmckerrell** [comment]
I updated the ansible scripts as can be found in this pull request - https://github.com/DoESLiverpool/doorbot-setup/pull/24

I have run the script against DoorBot 2 so it now has the browser set up. We probably need to update the HTML that it displays to add anything extra we'd like, for instance the "first in/last out" checklist. The HTML for that can be found here: 
    https://github.com/DoESLiverpool/doesscreens 

Once updated it needs manually deploying.
