### ISSUE TITLE
Move wiki.doesliverpool to github wiki

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#97]
This wiki is old, out of date and people can't sign up to it:  http://wiki.doesliverpool.com/

This one is empty and easier to sign up to edit: https://github.com/DoESLiverpool/somebody-should/wiki

If this sounds like a good idea, I'd need to get a login to the current wiki so I can copy the pages over and delete the old ones as they get moved.

**Comment by osfameron** [comment]
That's a good idea.  Any features that we'll miss?  e.g. the private organiser-only pages?

Actually this may not be a problem:  we can move public pages to github, and keep the existing wiki for the organiser only pages (as there, the lack of signup is a feature rather than a bug :-)

**Comment by amcewen** [comment]
Good question on the private organiser-only pages (but similarly on a workaround).

Is it possible to have the github wiki show up as wiki.doesliverpool.com?  i.e. future-proofing us for wanting to move away from github (and I guess, not killing the current URLs...)  @goatchurchprime, do you know if that's possible?

Similarly, is there a way to split the wiki from the somebody-should repo (have it live in its repo if need be)

**Comment by johnmckerrell** [comment]
+1 on pretty much all of that, not killing existing URLs would be optimal, if not then keeping wiki.does would be very good, and if not then the https://github.com/DoESLiverpool/somebody-should/wiki really is a bit long.

Also agree that we shouldn't worry too much about the private organiser pages, it would be nice if we could keep them in the same place but not the end of the world to leave on the old wiki.

**Comment by goatchurchprime** [comment]
I moved a couple of page sketches over to https://github.com/DoESLiverpool/CoffeeBot/wiki to test it out.  

You can git clone all the source pages in the wiki in one bundle, so we're not locked in as such.  

However, I hate the default markdown format.  Unfortunately their implementation of the mediawiki format is flaky, so we might have to live with it.  Any thoughts?  

Someone needs to give me editing rights to the current wiki.does pages so I can blank them with a link as they get moved over.  (I was going to start with pages for the Mangusta Mill.)

Also, can someone create a new repository called wiki, so we can use:
   https://github.com/DoESLiverpool/wiki/wiki ?

**Comment by goatchurchprime** [comment]
Work has begun under that link.  So far only moved Arcitype page.

**Comment by goatchurchprime** [comment]
3D printing and 3D cutting category pages are all moved over.  Probably another day of work to shift the 2D laser cutting and misc pages across and then we can kill the current wiki system.

**Comment by goatchurchprime** [comment]
Moved general links over.  All that remains is the 2D laser cutting pages

**Comment by goatchurchprime** [comment]
All information pages from the doeswiki have been copied over and the links converted to markdown.  

I've consolidated batches of pages, such as the kinectscanner ones and doespledges

I would like to decommission the current wiki so we can move forward with making this new wiki into a more organized reference source for the kit we have.  

However according to the [recent changes](http://wiki.doesliverpool.com/RecentChanges) it's still being used for http://wiki.doesliverpool.com/Network/Devices and http://wiki.doesliverpool.com/DoESMeetingAgenda201512 stuff.  

Perhaps the latter could be moved to another repo so that this one is reserved just for kit and infrastructure.

**Comment by huffeec** [comment]
I've made some changes to [[https://github.com/DoESLiverpool/wiki/wiki]] to split Sophia information into more manageable pages. Should I mirror it at [[http://wiki.doesliverpool.com/]] ?

Will try and get more post August settings for [[https://github.com/DoESLiverpool/wiki/wiki/CutEtchSettingsSophia]] at Maker Nights.

**Comment by amcewen** [comment]
@huffeec Lovely.  Don't worry about mirroring it onto the old wiki, that's deprecated now (and all the links from the main page go straight to the new wiki version anyway).  It should be better when issue #234 is fixed.

Pages I still need to check/move over:
 * [ ] http://wiki.doesliverpool.com/NewDinky
 * [ ] http://wiki.doesliverpool.com/InternTasks
 * [ ] http://wiki.doesliverpool.com/Insurance
 * [ ] http://wiki.doesliverpool.com/Bills
 * [ ] http://wiki.doesliverpool.com/FreeAgent
 * [ ] http://wiki.doesliverpool.com/GostinsBuilding
 * [ ] http://wiki.doesliverpool.com/CoffeeBot
 * [ ] http://wiki.doesliverpool.com/Krigsmjöd
 * [ ] http://wiki.doesliverpool.com/administrator
 * [ ] http://wiki.doesliverpool.com/DinkyAVEquipment
 * [ ] http://wiki.doesliverpool.com/AeroPress
 * [ ] http://wiki.doesliverpool.com/Salsa
 * [ ] http://wiki.doesliverpool.com/ManchesterMiniMakerFaire
 * [ ] http://wiki.doesliverpool.com/Coffee
 * [ ] http://wiki.doesliverpool.com/MakerDay
 * [ ] http://wiki.doesliverpool.com/DoorBot
 * [ ] http://wiki.doesliverpool.com/RegularTasks
 * [ ] http://wiki.doesliverpool.com/Status
 * [ ] http://wiki.doesliverpool.com/IoTLiverpool
 * [ ] http://wiki.doesliverpool.com/FriendsOfDoES
 * [ ] http://wiki.doesliverpool.com/VisionsOfDoES
 * [ ] http://wiki.doesliverpool.com/GeekUpLiverpool
 * [ ] http://wiki.doesliverpool.com/GardeningGroup
 * [ ] http://wiki.doesliverpool.com/HealthAndSafety
 * [ ] http://wiki.doesliverpool.com/UKMakerBelt

**Comment by goatchurchprime** [comment]
That does look like a job of work there.  I was completely unaware of all those pages till just now!

Best try some of them

**Comment by goatchurchprime** [comment]
Okay, I've scavenged all the content from the pages in that list, and rammed most of the content into https://github.com/DoESLiverpool/wiki/wiki/Unorganized-administrative-content
for dealing with later
