### ISSUE TITLE
Consider replacing SupportBee

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#970]
We currently use a service called SupportBee as a CRM to deal with the hello@ emails but we're not really using it enough to make it worth paying $40/month. The only thing we use on it is the ability to make sure that everyone gets all replies (rather than someone clicking "reply" rather than "reply to all"). This just makes sure each of the organisers is aware when someone else has replied to an email and what they said. If anyone reading this has alternative suggestions for a service or a simple self-hosted solution just shout.

**Comment by amcewen** [comment]
There'd still be a problem with email coming back *in* - people externally won't know they need to reply-all, and that will mean that stuff won't go back to everyone.  It does seem expensive for pretty much that one feature though...

**Comment by DoESsean** [comment]
If, instead of using the 'reply all' feature, we remembered to change the
outgoing address to organisers@ (I know I have that drop down option),
would that work?

**Comment by johnmckerrell** [comment]
Not sure I have the option. I’d like it to be automatic really just to make sure.

**Comment by DoESsean** [comment]
We're still using supportbee, months after this was flagged. What, if anything, can we do to move away from it? Are there other, cheaper options that do the same thing if nothing else?

**Comment by johnmckerrell** [comment]
There is a monthly hack the space event working on this. 

--

**Comment by johnmckerrell** [comment]
Closing this as there's a newer dupe - #1478 - which has more useful comments
