### ISSUE TITLE
Gerald ghosting when engraving- 7th Nov 2018

### ISSUE THREAD

**Issue by ASlater15** [DoESLiverpool/somebody-should#972]
It seemed to be engraving fine on the first engrave which was over 5 hours, but the second engrave was when it started to slip, i noticed it more as it was quite small type so gave it a fuzzy appearance

Tried it slower which worked only a tiny bit better, but it would be worth turning the Bi-direction off for the time being until its sorted.

**Comment by magman2112** [comment]
With the laser move and some realignment that @Sean-anotherone and I did on Saturday and Sunday, Gerald now appears to be cutting a lot better. 

A faulty mirror was also replaced and all of the other mirrors were removed and thoroughly cleaned which will have significantly affected the laser power. The laser tube was also levelled and the vertical alignment through the cutting head was also adjusted.

Closing this issue now as the primary causes for this issue have now been addressed.
