### ISSUE TITLE
Laser cutters warp/distort output seemingly randomly

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#974]
I referred to this as an ongoing issue, it's one that I've been aware of ever since joining DoES however Adrian pointed out that one had never been raised on github

I'll update this with more images that demonstrate the issue as they happen. 

![img_20181112_111636](https://user-images.githubusercontent.com/26458780/48344410-df2e2580-e66c-11e8-9702-c89288bf6b9a.jpg)

@magman2112 Has suggested to me in the past that this may be a problem with the USB Serial connection, however this happened a week ago to Paul (unknown second name).

He downloaded the data, started the cut, the result was warped. He then pressed stop, flipped his wooden piece, then started again. This is without re-downloading the file or altering the data in the laser cutter's ram in any way, and the result on this second cut came out just fine.

The image in my post may be unrelated currently, and more related to the maintenance applied via #968 but it brought up the issue in my mind, and I'll post more images and evidence of what I'm describing as the incidents occur.

**Comment by amcewen** [comment]
That specific problem in the photo is the y-axis missing steps and ending up with the laser head not being where the cutter thinks it is.  I've loosened the tension on the belt slightly to see if that improves matters.

**Comment by amcewen** [comment]
It still happened with the looser belt, so we tried again with it tightened again, similarly to no success.

The problem file has been saved to the Desktop on Sophia's computer, in a `Problem Cut Files\974` folder.

**Comment by Sean-anotherone** [comment]
I'd propose that these issues are a combination of the wheels the sled runs between note being brilliant, plus the belts are probably getting old.
I believe a set of v-groove wheels have already been procured, so making a new sled is actually a fairly simple job and that might help a lot.  I'm happy to do it if the wheels are available.

New belts are cheap and a bit of modification to make the belt tension spring-loaded  would probably not be too difficult, the sled delivers no "power" so the belts only need be tight enough to overcome the momentum of the sled while reversing.

**Comment by DoESsean** [comment]
As with the other issue about the overhaul, I'm closing this one.

This problem should have been fixed, and the issue closed, or at least there should have been further updates in the last eight months.

As it is Sophia is currently out of action pending a complete overhaul, so this should be addressed during that and, if not, a new issue opened marking it down as a separate problem. If anyone thinks otherwise, please reopen.

**Comment by amcewen** [comment]
Sophia isn't out of action, btw.  Has been of late, but has also been fixed.  I can see no issues with both the `Sophia` and the `Broken` labels...
