### ISSUE TITLE
Air compressor plug is loose

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#975]
The compressor for the air-assist on Sophia is plugged into a US-style socket (two flat pins anyway) on the left-hand side of the case, next to where the extraction hose is attached.

It's rather a loose fitting now, and can work its way out, thus turning off the air-assist.  We should replace or secure it better so that doesn't happen.

**Comment by magman2112** [comment]
I’ve been looking at some shuttered IEC sockets which may be a good replacement for the existing sockets. 

Something like this - https://uk.farnell.com/bulgin/px0675-63/outlet-iec-flange-fixing/dp/313701

Or this - https://uk.farnell.com/bulgin/px0714-2-15-28/outlet-iec-dual/dp/865308

Would appear to be good possibilities.

I expect that a mounting plate would have to be made up to replace the existing connection and electrical safety would be paramount, as these connectors are accessible with the lid up on Sophia.

**Comment by magman2112** [comment]
The air assist on Sophia has now been plugged into the socket strip on the back of Sophia. This means that the air assist is now on all the time Sophia is switched on and there is no program control of the air assist, but the plug can’t fall out now.
