### ISSUE TITLE
6mm cnc collet and flat mill has been broken

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#978]
Thanks to an unfortunate lack of tightening, or some other issue, me and Martin rendered the 6mm Collet and flat milling tool unusable, it came loose during a cut. Just thought I'd note it here, since it's good to log these events. Since these items are considered consumables, it might make sense to make a central issue or repository that logs tool breakage.

**Comment by goatchurchprime** [comment]
We need a new one!  Collet sets are sold here:  https://www.cnc-step.com/collet-kit-kress/

I have just sent an email asking for that single 6mm collet, and not the whole set.

**Comment by mdunschen** [comment]
It's a Suhner spindle. I tried to work out from the website if the Kress
collets would fit, but it does not say. Worth asking when you order.

Martin

**Comment by MatthewCroughan** [comment]
@mdunschen @goatchurchprime If we can source one from China, Andy Su is currently in China, and we can have him bring a bunch of collets and bits home. He'll be home soon, so the sooner we source these the better.

**Comment by goatchurchprime** [comment]
CNC-step quoted 24,37 Euro plus shipping, and state it's for "1050-FME-1 and 1050 FME"

The CNC-Plus website has it for 14.80 Euros and includes those two codes in its list of suitable spindle types:
https://cnc-plus.de/en/Collets---Clamping-Nuts/Collets-for-Kress-and-AW-FSE-Milling-Spindle-Motors-.html

I have asked for clarification.  Also CNC-Plus has a wide variety of bits, which I should add into the order.  We could include prices and reordering information in the records for each tool.  

I'd like to get an order in by end of today.

**Comment by goatchurchprime** [comment]
I've created a much worse problem.  I did the 1.8inch collet up too tight on a 3mm tool, and now it's completely jammed in -- tool and collet.  I'm asking cnc-step for help instead of complaining about their high prices.  

Is there a 3mm collet anywhere?  I've only got a 1/4inch and this big one that measures at 8mm.

**Comment by goatchurchprime** [comment]
It's been extracted.  CNC-step says they don't know if the CNC-plus collet will work.  Can't tell if it's a half-lie and they know it's perfectly okay, but don't want to fully lie and tell me it doesn't.

**Comment by goatchurchprime** [comment]
The CNC-step guy says: "No, it think the collet is damaged." which is not much good.  I am checking with cutwel if they can supply Kress collets.  

@magman2112 Is there a 3mm collet around for all these 1 flute 3mm tools in the drawer?  I only have a 1/4"=3.125mm collet, which caused that jam when I tried to use it with a 3mm cutter.

**Comment by goatchurchprime** [comment]
I've placed an order for the replacement 6mm collet.  A bit steep when you add in all the extra costs:

(Also ordered 2 milling bits for aluminium).

-------------
Products:
--
Units:           Products:           Product No.:           Price per unit:           Price:                                        1 x            			 				Collets for Kress and AW-FSE Milling Spindle Motors. 				Selection  Ø:Ø6.00 								 				Shippingtime: 2-4 days			 		             Z-10-0101-060            14,80 EUR            14,80 EUR | Units: | Products: | Product No.: | Price per unit: | Price: | 1 x | Collets for Kress and AW-FSE Milling Spindle Motors. 				Selection  Ø:Ø6.00 								 				Shippingtime: 2-4 days | Z-10-0101-060 | 14,80 EUR | 14,80 EUR
Units: | Products: | Product No.: | Price per unit: | Price:
1 x | Collets for Kress and AW-FSE Milling Spindle Motors. 				Selection  Ø:Ø6.00 								 				Shippingtime: 2-4 days | Z-10-0101-060 | 14,80 EUR | 14,80 EUR

**Comment by Sean-anotherone** [comment]
I have fixed the collet - it appeared that the tool had "spun" and caused a bit of melting/welding over just the first 0.5 - 1mm of the bore, but the tool is held over at least a 10mm length of the shank when tightened, so I used the dremmel to dress off the welded nasty and the collet is fit for use again.

**Comment by goatchurchprime** [comment]
I successfully did 2 hours of milling using this collet on tool T7 here:  https://github.com/DoESLiverpool/somebody-should/wiki/tool-crib

So we can consider this collet repaired.  

Please note that it's not a Kress Collet.  I just wasted £30 ordering one in, and it doesn't fit.  Ho hum.
