### ISSUE TITLE
Tall wall rack shelving northwall between windows for hanging vinyl and other hangy things

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#979]
Once we get rid of the character electricals, I propose putting up some rails of this twinslot kind:
https://www.toolstation.com/shop/Ironmongery/d170/Shelf+Brackets/sd2230/White+Twinslot+Shelving/p31030

It might be necessary to paint them first so they aren't beige.  

Then it will be possible to put in various brackets, which we can hammer to different angles and generally adapt, or make new type brackets.
https://www.toolstation.com/shop/Ironmongery/d170/Shelf+Brackets/sd2230/White+Twinslot+Shelving/p20828

We'd favour not having any general-purpose shelves, but supported rods to thread and hold tubes of vinyl, possibly 3D printed filament (in plastic bags) on a 2-rod shelf, numerous reels of electrical wires, and generally anything else in terms of supplies that we want to make visible, filed according to colour.

**Comment by goatchurchprime** [comment]
#831

**Comment by johnmckerrell** [comment]
As mentioned, if you want to choose what we need someone else can then order, or if easier you could sit down with @DoESsean on Thursday and choose.

**Comment by goatchurchprime** [comment]
There seems to be various extra rail-like attachments you can have, like trails and notched waterfall clothes arms we could hang horizontal rods on with the vinyl.  

https://www.displaysense.co.uk/shelving-racking-c5/twin-slot-shelving-c38

I hope the dimensions are standard.  It's not obvious what the right distance between the rails are, but maybe it should be so it can fit this basket:  https://www.homebase.co.uk/duraline-basket-runner-white_p107839

![image](https://user-images.githubusercontent.com/677254/48836832-b77d4280-ed7b-11e8-905a-5f56cd012b47.png)

**Comment by DoESsean** [comment]
We've ordered 4x2m long strips of this, no brackets so far as @goatchurchprime said we have some that can be experimented with to begin with.

**Comment by goatchurchprime** [comment]
Two of the strips are up on the north wall between the windows, extending quite high.  

I've been down to Salesflo and got a selection of attachments (which can be spray-painted black), as well as a small sample of grid metal (can be spray-painted black, or comes in chrome) and a selection of other fittings.  

I've chucked some various vinyl and wire stock onto both things from the drawers -- and it's not looking quite as tidy and cool as it did in my imagination.  

There's some potential, but I think it needs a good bit of thinking -- by other brains.  The grid metal can be bought second hand from salesflo at £12 a sheet 4ft by 5ft about.  This could be put on the wall in the laser cutter room so as to hang up saws and chisels and other tools that are now in the drawers, and for which we had thought of using a pegboard.  

We can put narrow strips of this grid metal onto the sides of the brick column by the windows and have rods coming out with the wire rolls on them so you can see them from the side.  It may well be better to have some horizontal half-metre rods projecting out from the left wall above the vinyl cutter on which to slot the rools of vinyl.  It works as long as the rod goes beyond the CofG of a roll, and this might be the right place for them.  

There's still no good answer for sheet materials (to get them out of the drawers and off the floor and somewhere visible).  However, the shelf supports on the vertical slots can be 12inches long, so could support a wide enough shelf to hold working stocks of acrylic and ply in the laser cutter room.  Tests could be undertaken on the shelving in the main room before affixing them to the laser cutter room.

**Comment by goatchurchprime** [comment]
Jackie points out that it's best to keep vinyl out of sunlight or it wrecks it.  I think the cupboards under the vinyl cutter is very deep -- deep enough to store the rolls end on.  There's room above the last set of shelves by the wall, or it could go in the cupboard bit with the doors removed.

**Comment by zarino** [comment]
> I've chucked some various vinyl and wire stock onto both things from the drawers -- and it's not looking quite as tidy and cool as it did in my imagination.

I think it looks really promising! If all the crossbars were the same length, and black, it’d look really smart. It’s nice to see all the rolls of stuff hanging up when you enter from the other side of the room … although @jackie1050’s comment about storing the vinyl out of sunlight makes me wonder whether we’ll _actually_ have that much stuff to store here, other than wire spools and the odd roll of fabric?

> The grid metal can be bought second hand from salesflo at £12 a sheet 4ft by 5ft about. This could be put on the wall in the laser cutter room so as to hang up saws and chisels and other tools that are now in the drawers, and for which we had thought of using a pegboard.

I like this idea. Perhaps this is straying too much from the original topic of this ticket, but the grids feel smart enough that, if we used them on the walls in lots of the other rooms—like Dinky, Room 29, and the events space—they’d become a bit of a DoES "aesthetic" and help tie the space together. They add visual interest even when they’re totally empty, but with a few hanging buckets or pockets, they could be used for storing all sorts of stuff that you need to hand. 3D printing some cable clips that snap onto the wires is an obvious next step. Maybe we should open a new ticket…

**Comment by amcewen** [comment]
I think if we're hanging tools on it, pegboard has the advantage that we can make it a shadow board so it's obvious what is missing.  Nice idea for other areas though, and if there are some empty bits, we could try embroidering it (although it's quite a big "weave").

It's a good start on working out what to do there.  I think @zarino's right that black fittings and black-and-equal-length versions of the wooden rods would improve the looks.

The vinyl has always been exposed to sunlight, so we're probably not *losing* things by hanging it there, right?  But if it's better for it to be out of the sun, is there a drawer it could live in?  Do any of the drawers have things that could be hung on the wall instead?

The battens go pretty high - maybe the top end could be used for things that aren't often required?  Some of the electronics test gear, etc. by the oscilloscope won't get used much - maybe that could live on a shelf on the wall?

Another suggestion has been the spools of 3D printer filament.  Two suitably-spaced rods would let the spools sit on the shelf in the same orientation as the wire spools do now (but in bags to keep the moisture out).  Maybe with a parts bin (like the ones on the back of the electronics workbench) to store spare ziplock bags and silica gel packs?

Some labelling or small signs dotted round it would help too, as that could explain that things are for members to use (and have pricing details or "free or small donation" for the wire, etc.)

**Comment by jackie1050** [comment]
We had to throw away two large rolls of masking material which had been left in the sun for a long time while in the old workshop. The glue on one side had completely set. There were some similar but less clearcut effects on vinyl.

I think the main rack between the two windows should be ok, but there was a suggestion of hanging on the side part which seemed less advisable.

On 2 Dec 2018 23:54, Adrian McEwen <notifications@github.com> wrote:

I think if we're hanging tools on it, pegboard has the advantage that we can make it a shadow board so it's obvious what is missing. Nice idea for other areas though, and if there are some empty bits, we could try embroidering it (although it's quite a big "weave").

It's a good start on working out what to do there. I think @zarino<https://github.com/zarino>'s right that black fittings and black-and-equal-length versions of the wooden rods would improve the looks.

The vinyl has always been exposed to sunlight, so we're probably not losing things by hanging it there, right? But if it's better for it to be out of the sun, is there a drawer it could live in? Do any of the drawers have things that could be hung on the wall instead?

The battens go pretty high - maybe the top end could be used for things that aren't often required? Some of the electronics test gear, etc. by the oscilloscope won't get used much - maybe that could live on a shelf on the wall?

Another suggestion has been the spools of 3D printer filament. Two suitably-spaced rods would let the spools sit on the shelf in the same orientation as the wire spools do now (but in bags to keep the moisture out). Maybe with a parts bin (like the ones on the back of the electronics workbench) to store spare ziplock bags and silica gel packs?

Some labelling or small signs dotted round it would help too, as that could explain that things are for members to use (and have pricing details or "free or small donation" for the wire, etc.)

**Comment by goatchurchprime** [comment]
This is about done.  Useless tech has been put on shelves (that are screwed secure) up by the ceiling.  A couple of racks of 3D filament are there.  (Might need better shelves, as a bit bendy, but hey).  

Sewing machines moved out and to beside the solder station.  The thought is that if we (in particular I) try to keep the big block of white tables clear, then you can do the sewing here where there's lots of space.  

I've done a lot of wiping down of surfaces around the sublimation printer, which was very dirty.  

I've turned out several shelves of scrambled antique components onto the lowest shelf to make room for my projects (in labelled drawers).  We should get round to throwing this stuff at some point.  Cannot imagine ever being used.
