### ISSUE TITLE
Single common temporary dropbox directory on all DoES computers 

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#980]
We shouldn't ever need to move things from one DoES computer to another on a USB key when there's such a good network.  

This could be done if we have one dropbox-like shared directory between all of the public computers and laser cutter machines, that was treated as a convenient public resource -- rather like the pot of USB keys beside the laser cutter.  

This directory should have a permanent README.txt document in it at the top that says it's a public directory, and things are going to get deleted from it when it's too cluttered.  

@MatthewCroughan did this on theory, but it might not be working yet.  When it works, it needs to be documented in the https://github.com/DoESLiverpool/somebody-should/wiki/Digital-infrastructure page.  

Ideally, it should be accessible to anyone's computer on the network -- probably as a drag-and-drop webpage interface, but better as a dropbox-like direcory if it's not too -- so that people can copy their work into it and thence onto the laser cutter machine seamlessly.

**Comment by johnmckerrell** [comment]
Well we’ve had an actual shared Dropbox folder since forever but the internet connection on those machines as been a bit variable. 

--

**Comment by MatthewCroughan** [comment]
I've added notes to the Wiki regarding the existence of both a local and external facing Nextcloud instance (which also includes a tunnel to the local samba!) along with the details for the local smb (samba) server. I'll create documentation that explain show to utilise both soon.

**Comment by goatchurchprime** [comment]
i guess this is done!

**Comment by zarino** [comment]
@MatthewCroughan I’ve updated [the wiki page](https://github.com/DoESLiverpool/somebody-should/wiki/Digital-infrastructure#shared-storage) with what I _think_ are the right instructions for connecting to `does-samba` now that it’s at `//samba` rather than `//10.0.39.222`. Feel free to edit if anything’s not quite right.
