### ISSUE TITLE
Door to Room 29 won't shut

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#984]
Since getting the carpet fitted and a threshold strip installed this door no longer shuts, I imagine it just needs a bit taking off the bottom.

**Comment by johnmckerrell** [comment]
Note that there's also the door to Dinky needing doing #1038

**Comment by magman2112** [comment]
The door has now had a little shaved off the bottom, as well as the top corner, so is a good fit now. I also found that one of the screws for the metal carport rail was damaged, which caught the bottom of the door, this has been replaced now.

I also fitted the handle for now, to make opening and closing this door a little easier. It can easily be removed when we get round to painting this door.
