### ISSUE TITLE
Gerald acting weak, not cutting through or engraving at full power

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#987]
The tubes might very well be dying, since we've been having this problem intermittently for a while now, with no clear evidence for why it's happening.

**Comment by johnmckerrell** [comment]
Not just dirty is it? Sophia was terrible the other day but when I took the lens out it was black! ⚫️

--

**Comment by magman2112** [comment]
I cleaned the lens on Gerald last night, as well as checking the alignment, so I suspect it is not the lens.

We are struggling to cut even 3mm ply at the moment. It may be a worn tube issue, but I don’t know how to check this. 

I am looking to set up a laser maintenance day on 2nd December, but we may have to move this forward if Gerald gets any worse.

**Comment by huffeec** [comment]
There's a flow chart on the Smoke and Mirrors forum. From what's been said here it looks like it leads to replacing it. We definitely moved at least one, probably part used, tube. Has that already been used?

https://community.andmirrors.co.uk/t/does-my-laser-cutters-tube-need-replacing/42

**Comment by magman2112** [comment]
I seem to recall that there is a spare tube for Gerald stored behind him. I believe that this is not a new tube, but it might be worth trying to see if it improves the performance of Gerald before we commit a lot of money in buying a new tube.

I could possibly come in on Sunday to try this, as long as there is someone who can help me, as I expect this is more than a one person job.

**Comment by KarlDunkerley** [comment]
What time you thinking of?
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Friday, 23 November 2018, 19:42:40 GMT, Mike Gorman <notifications@github.com> wrote:  
 
 
I seem to recall that there is a spare tube for Gerald stored behind him. I believe that this is not a new tube, but it might be worth trying to see if it improves the performance of Gerald before we commit a lot of money in buying a new tube.

I could possibly come in on Sunday to try this, as long as there is someone who can help me, as I expect this is more than a one person job.

Calling out to @DoESLiverpool/laser-maintenance

**Comment by magman2112** [comment]
Sorry Karl, should have replied earlier. About 1 ish on Sunday looks to be a reasonable meeting time, given that Darren should be there around this time anyway.

**Comment by KarlDunkerley** [comment]
Unfortunately am taking mum out for Sunday lunch.
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Sunday, 25 November 2018, 00:32:51 GMT, Mike Gorman <notifications@github.com> wrote:  
 
 
Sorry Karl, should have replied earlier. About 1 ish on Sunday looks to be a reasonable meeting time, given that Darren should be there around this time anyway.

**Comment by magman2112** [comment]
I did a text yesterday before changing the tube and was unable to cut 3mm plywood at 6mm/sec and power 70. The replacement tube was able to cut at 6mm/sec, but only just, so I don’t think either of them are great at the moment. I obviously checked alignment and this was spot on before the test cuts.

We also need to top up the water in the chiller, as this is about half full at the moment, though I doubt this will cause any power issues. This will need either distilled or de-ionised water methinks.

**Comment by DoESsean** [comment]
According to Dominic at Smoke and Mirrors, regassing isn't an option as it would be far too expensive. 

They currently don't have the right tube in stock, and it would take about two weeks to get them in, so I'm exploring other options. Given that Gerald had an 80w tube, he's suggested it was likely []https://smokeandmirrors.store/collections/co2-laser-tubes/products/reci-65w-co2-80w-peak(url) (or at least one analogous to that), so that's what we're looking for.

S&M's would cost £650 (plus shipping), so if anyone can find anything that will get here quicker for around the same amount, let us know.

**Comment by DoESsean** [comment]
Here's one on eBay:

https://www.ebay.co.uk/itm/RECI-80W-90W-Peak-100W-CO2-Laser-Tube-W2-S2-120cm-Express-Insurance/221655476532?hash=item339bb22934:g:GM8AAOSwjZlb648r:rk:2:pf:0

**Comment by amcewen** [comment]
The supplier that Simon used for his tube has http://www.laserwd.com/product_c80-80w-co2-laser-tube_9120.html  It'd come from China, but Simon was really happy with how well his worked.  That's longer than the one Dominic sells (1600mm vs 1200mm) and narrower (60mm vs 80mm), but seems to match the previous one we'd had (and the one @magman2112 and @dazz-ling refitted on Sunday)

**Comment by DoESsean** [comment]
Whatever we're looking at, it needs to be ordered asap - we can't afford for Gerald to be out of commission coming up to Christmas. Since this is going to have to be done anyway, it actually makes sense to pay a bit more to get the thing quicker so that we're not losing days worth of work in the meantime.

**Comment by amcewen** [comment]
Agreed on the getting it ASAP given the time of year.

**Comment by DoESsean** [comment]
I've contacted the supplier @amcewen has listed, so we'll wait and see when they get back to us. Hopefully it'll be sooner rather than later. I've given them the hello@ email address so it can be picked up if I'm not here.

**Comment by DoESsean** [comment]
I could get a return flight to Beijing, leaving Thursday and coming back Saturday or Sunday, for just under £500. Just sayin'...

**Comment by DoESsean** [comment]
http://hpclaser.co.uk/index.php?main_page=product_info&cPath=2&products_id=7

This is from HPC. Look right? It seems a bit long...

**Comment by amcewen** [comment]
HPC have one in stock, but we'd need to go over to Halifax to collect it from them.  Anyone fancy a trip over for us?  We can pay expenses, obv.

**Comment by magman2112** [comment]
I am actually travelling over to Sheffield tomorrow morning, so could make a detour on the way back if that helps.

**Comment by KarlDunkerley** [comment]
If no-one else can do it then I'm in my delivery van to Leeds most Thursdays. Usually have a bit of time to do a detour.
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Tuesday, 27 November 2018, 13:34:48 GMT, Adrian McEwen <notifications@github.com> wrote:  
 
 
HPC have one in stock, but we'd need to go over to Halifax to collect it from them. Anyone fancy a trip over for us? We can pay expenses, obv.

**Comment by johnmckerrell** [comment]
Ok, I've bought the tube, actually £540 with VAT. We'll go with @magman2112 picking it up tomorrow as he's "passing". They're open 8:30am-5pm.

**Comment by johnmckerrell** [comment]
It's been making a horrible screechy noise and there's some arcing or bad light of some sort coming from the end of the tube so I've put a notice on it not to be used and turned the laser off with the key.

**Comment by magman2112** [comment]
The noise was arcing from the laser HT tube, which was too close to the back cover when this was refitted late on Sunday. The cable and chocolate block were quite melted, @paulgeering has taken a photo of the offending part for posterity, as the original is now in the bin.

The new laser tube has now been fitted with help from @paulgeering, @Sean-anotherone and another member I didn’t catch the name of. Special attention was paid to the HT lead, which is now soldered with 2 layers of heat shrink. Additional protection has been added using some of the spare air assist silicone tubing.

After an initial alignment, Gerald was easily cutting 3mm birch ply at 18mm/sec and 70 power. I do expect that some additional alignment will be needed in the coming days, I hope to be in on Sunday afternoon to have a look at this.

**Comment by LeeCarmichael** [comment]
I have been using Gerald today and it was working fine. I checked with @magman2112 and he said its ok. No further action needed.

**Comment by amcewen** [comment]
Leaving this link to [these laser-tube alignment brackets](https://www.thingiverse.com/thing:2214741) here, in case it's of use next time we're fitting a tube (and we're likely to check this issue then to find out where we got the last tube from ;-)

I expect they'd need adapting for an 80W tube, but thought it could be of use...
