### ISSUE TITLE
Workshop Doorbot screen not turning on or useful

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#99]
The workshop doorbot screen is currently black, it's definitely worked in the past, it might just be that the Pi is not outputting video or it could be that the screen is turned off, although pressing on and the AV switch buttons hasn't fixed. When it is on it would be nice if it did something useful like Dinky/doorbot3

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by stevesparrow** [comment]
Closing as moving anyway...

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
