### ISSUE TITLE
Amend Weeknote Generator program so that it can be run at e.g.21:00 on Sundays

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#998]
This would be a more convenient time to check through and post the Weeknotes, as it can be difficult during the week.
Spoke to @amcewen about this:the program currently only deals with whole days.

**Comment by DoESsean** [comment]
How is this going? I know @jackie1050 has been running weeknotes quite regularly, so I assume it is easy for her to do now. Is this as a result of something being fixed with this issue?

**Comment by jackie1050** [comment]
It isn't that easy for me - I'd still like to his to happen

**Comment by DoESsean** [comment]
In the last three years, has this solved itself?

**Comment by JackiePease** [comment]
It would still be useful, but there are higher priorities for amendments to the Weeknote Generator
