### ISSUE TITLE
Find a way to remove the broken bit of Gerald's duct pipe from the outside of the building

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#999]
The duct piping was torn, and caught on the outside of the building. Someone had closed the window.
I wa unable to unattach it, so have cut the wire, and repaired the still attached part.
We will need to think of a way to remove the bir that's still on rge outside of the building.

**Comment by magman2112** [comment]
I had a look outside the building last week and couldn’t see the torn ducting, so either it blew away or someone else has removed it, so closing this issue.
